### ISSUE TITLE
Placeholder dont work in papi

### ISSUE THREAD

**Issue by n54b** [Zrips/Jobs#1001]
***Description of issue:***

When i use %jobsr_user_points_fixed% with Placeholder api, that don't work ... He parse me %jobsr_user_points_fixed% :'(

**Server Type (Spigot/Paperspigot/etc): Spigot** 

**Server Version (using `/ver`): 1.16.3** 

**Relevant plugins (Delete if this isn't needed): PlaceholderAPI / Jobs**

**Comment by montlikadani** [comment]
What's the result in `/jobs placeholders`?

**Comment by n54b** [comment]
Its work, but i need to update placeholderapi to the dev version and now its work fine ;)
