### ISSUE TITLE
[SUGGESTION] Anti player-killing farming (with same IP)

### ISSUE THREAD

**Issue by Tomi010817** [Zrips/Jobs#1003]
**Description of new idea**
If two players have the same IP and one kill the other, then he won't receive any money/points/experience or anything.

It would potentially avoid players that use alts to farm player-kills to earn a lot of money or stuff.

Cheers!

**Comment by montlikadani** [comment]
There is action for this called `Kill`, with this you can configure Players kills. [Example](https://github.com/Zrips/Jobs/blob/master/src/main/resources/jobConfig.yml#L306-L312)

**Comment by Tomi010817** [comment]
Oh! Alright, this is already fixed?
so if two player with the same IP kill each other, they won't receive anything right?

**Comment by montlikadani** [comment]
> There is action for this called `Kill`, with this you can configure Players kills. [Example](https://github.com/Zrips/Jobs/blob/master/src/main/resources/jobConfig.yml#L306-L312)

Did you understand what I'm described? It seems not

**Comment by Tomi010817** [comment]
Apparently no, I apologize.
I only understood that you told me how to configure player-kills on a job.

**Comment by Tomi010817** [comment]
I've been looking up this more detailed, and I haven't found any current option on that action to only listen for player kills **only** when your target has a different IP.

**Comment by montlikadani** [comment]
You can't set different player IPs for actions. It requires only the Player as LivingEntity not other thing. I don't see why do we need the IP to be different between two players and check whenever their IPs are not the same so player will not get paid for killing them. Literally this Jobs plugin is not per-player manipulated working actions. Its like when you working in the current life, but in game related.

I close this issue. We will not implement a way to check IPs between two players and don't get income for killing them.

**Comment by Tomi010817** [comment]
It's fine, thanks for the quick response!
