### ISSUE TITLE
A missing placeholder ?

### ISSUE THREAD

**Issue by AdiLeTwix** [Zrips/Jobs#1004]
I dont know if is a Bug report or a Feature request..

***Description of issue:**
 I would like to have a placeholder(papi) of the total level of jobs even the inactive ones.
But accutaly:
%jobsr_user_totallevels% return the level of activ jobs of a player
and %jobsr_user_jlevel_(jname/number)% return 0 if if the player does not have it. 😭 

How could I get this value (with placeholder api, to have it in an other plugin)?

I use paper last version and jobs last version.

**Comment by montlikadani** [comment]
`%jobsr_user_archived_jobs%`

**Comment by AdiLeTwix** [comment]
> 
> 
> `%jobsr_user_archived_jobs%`

🤔 
It's the number of jobs that the player has performed but not the level of exp.

**Comment by montlikadani** [comment]
`%jobsr_user_jexp_(jname/number)%` https://github.com/Zrips/Jobs/wiki/Placeholders

**Comment by AdiLeTwix** [comment]
Please read my problems before close the issue...
This placeholder retnurn "0" once the player has left it.

**Comment by montlikadani** [comment]
Ah, yeah, you can't retrieve placeholders where the player left from jobs.

**Comment by AdiLeTwix** [comment]
Yes and I would like to have statistics on the total level accumulated by a player.
By a direct placeholder or the addition of all jobs level.

**Comment by montlikadani** [comment]
Take a look at the wiki what I've sent before. Find it, there is a placeholder for it.

**Comment by AdiLeTwix** [comment]
I've already looked at it and I've just checked it, these are always exp value of jobs that are currently in progress. 
Would it be possible to add access to this value with a (new?) placeholder ?

**Comment by montlikadani** [comment]
`%jobsr_user_totallevels%`

**Comment by AdiLeTwix** [comment]
Same thing :/

**Comment by AdiLeTwix** [comment]
So can you please re open the issue that a developer can see it and fix it.  🙏

**Comment by montlikadani** [comment]
Would be good to describe it more clearly what is your issue.

**Comment by AdiLeTwix** [comment]
The `%jobsr_user_jlevel_(jname/number)% ` PAPI didn't return a correct value when the player isnt in the jobs.

### Example: 
If i am woodcutter level 32 and I have the jovs the papi is : 32
But if i leave the jobs the papi is: 0

And i want to ger this value even if the player is not currently working in this job. 
Also it would be good to add a placeholder which is the total of all the level/exp/point of all jobs, even those that are not in progress?

**Comment by AdiLeTwix** [comment]
I don't know if this will help you to solve the problem but I noticed that in the shopitems.yml file we can defind a `RequiredTotalLevels` 
Would there be a way to get an placeholder from this ?

**Comment by montlikadani** [comment]
> The `%jobsr_user_jlevel_(jname/number)% ` PAPI didn't return a correct value when the player isnt in the jobs.
> ### Example:
> 
> If i am woodcutter level 32 and I have the jovs the papi is : 32
> But if i leave the jobs the papi is: 0
> 
> And i want to ger this value even if the player is not currently working in this job.
> Also it would be good to add a placeholder which is the total of all the level/exp/point of all jobs, even those that are not in progress?

I don't see the point in that. Why would we need a placeholder to look at a player’s level, or any similar option, when a player has left the job? This is unnecessary and makes no sense, since a player has left the given jobs, is able to get back only the level of the old job, but not the whole one, because we have taken a given interval from him. Adding this placeholder would increase Jobs memory usage and also cause a leak because a lot of players need to be stored. We don’t want to get more questions about similar memory leaks. The memory leak was mostly from a database because there were so many players on a server that they lost data. I can recommend the database of one of the servers that had a similar problem.

> I don't know if this will help you to solve the problem but I noticed that in the shopitems.yml file we can defind a `RequiredTotalLevels`
> Would there be a way to get an placeholder from this ?

PlaceholderAPI placeholders cannot be used within Jobs because Jobs has its own placeholders that the user can use. Anyway, the Jobs shop has nothing to do with this issue.

I will close this issue. As I assumed this will not be implemented.

**Comment by AdiLeTwix** [comment]
I'm actually looking for a total **of all the lvl jobs** (for give an achivement) 
I understand that you are afraid to use this feature if it can cause problem. However I feel that the plg has no problem to calculate the gtop etc...

**Comment by montlikadani** [comment]
> If i am woodcutter level 32 and I have the jovs the papi is : 32
> But if i leave the jobs the papi is: 0

You want all jobs level without player job.

**Comment by AdiLeTwix** [comment]
Yes I wanted all a or I would do the sum of Jobs1+Jobs2+Jobs3...
(sorry for my bad english 😂 )
