### ISSUE TITLE
Smaller boost values (still) taking precedence over larger ones

### ISSUE THREAD

**Issue by WhatsTheBadNews** [Zrips/Jobs#1005]
***Description of issue:**
Sorry to make a repeat of this issue, but the problem #984 still persists on Jobs v4.16.4 (from Discord) and I don't have the ability to re-open the issue.

Method to test:
1.) Install Jobs and give jobs.use permission
2.) Join Woodcutter job
3.) Chop 1 log, this should (and does) give $1 as you have no boosts
4.) /lp group default permission set jobs.boost.all.money.0.15
5.) Chop 1 log, this should (and does) give $1.15 as you have a 15% boost
6.) /lp group default permission set jobs.boost.all.money.1
7.) Chop 1 log, this should give $2 as you have a 100% boost that should override the 15% boost you also have. However, the 15% boost overrides the 100% boost and you still only get $1.15 from chopping the log
---

**Server Type (Spigot/Paperspigot/etc):**  Tuinity (latest)

**Server Version (using `/ver`):**  1.16.4

**Comment by WhatsTheBadNews** [comment]
I had an expert programmer look into the issue. He claims there is a "flat out bug in the boolean logic" in permissionsmanager.java file inside the getMaxPermission function. He says this is the function signature of the bug:

`public Double getMaxPermission(JobsPlayer jPlayer, String perm, boolean force, boolean cumulative, boolean allowMinus)`

According to him, this code fixes it and my tests seem to confirm this for me. Sadly, this expert programmer does not know how to use Github. Nor do I, so in the absence of a pull request, I will be leaving the code here in hopes that it be considered for implementation in the plugin.


```
            try {
                double temp = Double.parseDouble(permission.getKey().replace(perm, ""));
                if (cumulative)
                    amount += temp;
                else if (!allowMinus && temp < 0D)
                    continue;
                else if (temp > amount)
                    amount = temp;
            }
```

**Comment by Zrips** [comment]
32ffb88e9d96ad7cabe20915d827a6e6bb0b3a53
