### ISSUE TITLE
modded ores not adding to break list for miner job

### ISSUE THREAD

**Issue by archmichaeliii** [Zrips/Jobs#1006]
Hello i am using the plugin on magma and it is working great but i am trying to add some other ores to what users can get payed for. i have tried both the ingame edit job and adding the block names to the job config getting the name from the jobs blockinfo command. any idea why its not taking the info ? 
thanks

**Comment by montlikadani** [comment]
We're not supports forge/magma related blocks/new features as it needs this plugin to be recoded. #739
