### ISSUE TITLE
timebased Database cleanup doesn't work

### ISSUE THREAD

**Issue by Serial1990** [Zrips/Jobs#1007]
Hey, im using the newest Dev version of Jobs (v4.16.4 -dev), but the DBCleaning doesn't work with time based cleaning.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  DBCleaning:
    Jobs:
      # Warning!!! before enabling this feature, please make data base backup, just in case there will be some issues with data base cleaning
      # When set to true, jobs data base will be cleaned on each startup to avoid having not used jobs
      # keep in mind that this will only clean actual jobs, but not recorded players
      Use: false
      # Any one who has jobs level equal or less then set, hies job will be removed from data base
      Level: 1
    Users:
      # Warning!!! before enabling this feature, please make data base backup, just in case there will be some issues with data base cleaning
      # When set to true, data base will be cleaned on each startup from user data to avoid having old player data
      Use: true
      # Any one who not played for defined amount of days, will be removed from data base
      Days: 60
```

---

**Server Type (Spigot/Paperspigot/etc): Paper-231

**Server Version (using `/ver`): 1.16.3 Paper-#231

**Comment by montlikadani** [comment]
The specified 60 days have not elapsed.

**Comment by Serial1990** [comment]
> The specified 60 days have not elapsed.

That means, from the point in time when it is true, do the 60 days begin?

**Comment by montlikadani** [comment]
It depends on when the player last logged in, as there is a column in the database called `seen` that we can use to calculate the time of the player when he was last available on the server.

**Comment by Serial1990** [comment]
> It depends on when the player last logged in, as there is a column in the database called `seen` that we can use to calculate the time of the player when he was last available on the server.

![Unbenannt](https://user-images.githubusercontent.com/1337501/100343224-62660e00-2fdf-11eb-8a0a-0946a91ddbd5.PNG)
I think the player hasn't been online for more than 60 days, right?

**Comment by montlikadani** [comment]
No, that player's time hasn't reached 60 days yet. I checked using Calendar.

**Comment by Sulort** [comment]
Timestamp Converter
1540154342
Is equivalent to:
10/21/2018 @ 8:39pm (UTC)

i think, thats more than 60 days!!! :-)
