### ISSUE TITLE
jobs archive over MultiServer (Bungee) don't work

### ISSUE THREAD

**Issue by Serial1990** [Zrips/Jobs#1008]
Hey, if I unlearn a job on Server1, it is displayed in / jobs archive. If I switch to Server2, the job is no longer in / jobs archive
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
# Enable if you are using one data base for multiple servers across bungee network
# This will force to load players data every time he is logging in to have most up to date data instead of having preloaded data
# This will enable automatically save-on-disconnect feature
MultiServerCompatability: true
```

---

**Server Type (Spigot/Paperspigot/etc): Paper-231

**Server Version (using `/ver`): 1.16.3

**Comment by montlikadani** [comment]
Literally you don't have the same database on the second server which should connect to the main database.

**Comment by Serial1990** [comment]
> Literally you don't have the same database on the second server which should connect to the main database.

Both servers use the same database.

**Comment by Sulort** [comment]
i can confirm this bug. this is a bug since years. i reported this bug several times, unfortunately without success.
and we are not alone with this issue, take a look here:
https://github.com/Zrips/Jobs/issues/475#issue-464428522

**Comment by mechcalvin** [comment]
does it means even you go back to server 1, the jobs archive is reset as well?

**Comment by Serial1990** [comment]
> does it means even you go back to server 1, the jobs archive is reset as well?

look here: https://github.com/Zrips/Jobs/issues/475#issue-464428522

As already explained there, when i leave a job as an example Woodcutting LvL100 on Server 1 and use /jobs archive , the Job Woodcutting is listed with lvl 100. When i leave Server 1 and Join Server 2 and use /jobs archive then nothing is listed.

**Comment by mechcalvin** [comment]
what if you go back to server 1 and join the same job? still level 1 or have archive level?

**Comment by Zrips** [comment]
It cant be a bug when it never was a feature. But made some changes which should resolve this issue.
7544eea2acd146196bcd7443c665b7c9818b3f62
