### ISSUE TITLE
Boosted items + Enchantment

### ISSUE THREAD

**Issue by MrKakotu** [Zrips/Jobs#1011]
**Description of new idea or improvement on existing one**
So, about the boosted items. I have a suggestion that prevent players from enchanting the boosted items? If they enchant the boosted item it will no longer work. Execluding the ones that are set in the config of course.

**Detailed information what should do what and when**
Maby add an option within every boosted items in the config that i can set to true or false (If i want to use this or not). If the option is true. Then that specific boosted item won't give bonus xp/money/points, it should just work like regular item.

**Comment by montlikadani** [comment]
Literally this seems to be unecessary. As you stated, if the players enchant a boosted item it will no longer work. So the bonus will not be granted.

**Comment by MrKakotu** [comment]
> Literally this seems to be unecessary. As you stated, if the players enchant a boosted item it will no longer work. So the bonus will not be granted.

As i also mentioned this SHOULD be an option if added, i know lots of serverowners who want to prevent their players from enchanting the boosted items. Therefore i added it as a suggestion
