### ISSUE TITLE
Very Easy Infinite money glitch found.

### ISSUE THREAD

**Issue by wearenoobsuk** [Zrips/Jobs#1012]
Hey so, I have heard and read about the glitch when 'two' people have the miner job, But my players have found an even more OP glitch to get infinite money at any time.

I'm aware you can set blocks in 'memory' for a maximum of so many days, But this is rendered useless by the fact most servers reboot at least once every 24 hours.

I'm also aware you can prevent 'silk touch' payouts, but this won't work on, Iron, Gold, Ancient debris, As these don't need to be silked and drop their raw variation.

So to the glitch/bug.

If you have a miner job, And one person who doesn't have the job.

You can Mine any of these ores, (iron, ancient debris, gold etc) and then pass it to a person who doesn't have the miner job, And they can place it, (without being 'charged money' to place it) and you can mine it again, Pass it to them, And keep doing this until you earn an insane amount of XP and money.

I'm honestly not sure how you can fix this, The jobs plugin is awesome on my server and the player rate has increased a lot, But unfortunately, due to this bug people are heavily abusing and hurting the economy, And I cannot really keep up with constantly watching people and punishing them for it.

I have an 'x-ray notification' plugin, That gives admins notifications when somebody mines ores. It doesn't give notifications for 'player placed ores' and it works across reboots because it stores which blocks have been 'mined' in a flat database file. Yes, this takes up more storage, But it would prevent this entire issue. and probably fix a lot of other possible abuse methods people use with Jobs reborn. and the user could 'clear' the database whenever they want if space is an issue.

I really hope we have a solution for this, I love the plugin and don't want to take it away from my players due to people abusing it!

thankyou!

Latest Paper Spigot Build. 1.16.4
Latest Jobs.jar available

**Comment by NotGeri** [comment]
It'd be lovely to have this fixed asap, can replicate on 1.16.4 latest

**Comment by unholymac** [comment]
yeah this really needs to be fixed asap

**Comment by Zrips** [comment]
This can be mitigated by adding BlockProtection (restrictedBlocks.yml) to those blocks which will apply even if player without job places it. This will not be bullet proof, but it can save block protection for defined time even after server restarts. We cant really have any permanent block protection without introducing some huge amount of data being saved and checked each time player places/breaks a block.

**Comment by strahil211** [comment]
> This can be mitigated by adding BlockProtection (restrictedBlocks.yml) to those blocks which will apply even if player without job places it. This will not be bullet proof, but it can save block protection for defined time even after server restarts. We cant really have any permanent block protection without introducing some huge amount of data being saved and checked each time player places/breaks a block.

Can you fix this or do we have to figure it out on our own :P

**Comment by broken1arrow** [comment]
> > This can be mitigated by adding BlockProtection (restrictedBlocks.yml) to those blocks which will apply even if player without job places it. This will not be bullet proof, but it can save block protection for defined time even after server restarts. We cant really have any permanent block protection without introducing some huge amount of data being saved and checked each time player places/breaks a block.
> 
> Can you fix this or do we have to figure it out on our own :P

In newest build on github, you have a new job option "none.yml" file  (they get this job before join real job). soo you can set they get zero or less on ores if they place it. Only thing if player has no money, they get no penalty (if it goo below zero, they get 0 when relog again, can depend what money plugin you use).

**Comment by montlikadani** [comment]
> 
> 
> This can be mitigated by adding BlockProtection (restrictedBlocks.yml) to those blocks which will apply even if player without job places it. This will not be bullet proof, but it can save block protection for defined time even after server restarts. We cant really have any permanent block protection without introducing some huge amount of data being saved and checked each time player places/breaks a block.

The answer is here.

For future consequences: we're not planning to implement this, cause it is possible to limit the "infinity break" ore payment generating by players. You can add those blocks into `restrictedblocks.yml` and enabling `PlaceAndBreakProtection` in generalConfig.
