### ISSUE TITLE
MySQL duplicated info about job

### ISSUE THREAD

**Issue by TheNety** [Zrips/Jobs#1013]
**Description of issue:**
When using MySQL to save Jobs data, in tables `jobs_archive` and `jobs_jobs` there's duplicated info about the job player is in. It uses "jobid" as a number but it also uses "job" as a word, which is unnecessary to use, if I'm right. So the solution would be to don't use and save "job" column anymore.
![image](https://user-images.githubusercontent.com/42073765/101022658-f866df00-3571-11eb-9ea7-d12a172791e6.png)

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):** Paper version git-Paper-294 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Comment by montlikadani** [comment]
We need these two columns because we have recently added the option to retrieve a given job from somewhere by ID to be an exact query if it does not exist by name or something is wrong.
