### ISSUE TITLE
Advanced Enchantments support

### ISSUE THREAD

**Issue by ArnoPompio** [Zrips/Jobs#1014]
**Description of new idea or improvement on existing one**
Support the "Advanced Enchantments" plugin Enchantments, especially TRENCH.

**Detailed information what should do what and when**
(TRENCH) We are having trouble when our players are mining with the enchantment TRENCH of the Advanced Enchantments. They get paid for 27 blocks instead of only 1 block. We are waiting for a long time for a way to fix this, but don't having any solutions.
I would like that there is a way to divide the payment when my players have the enchantments on their pickaxe, or considering the pay for only the block mined. I don't know if it's possible from your side, but it would be perfect.

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/a45165382025f8e0cc381691847f182274c06253
