### ISSUE TITLE
Furnaces resetting ownership during hopper interaction

### ISSUE THREAD

**Issue by PGPShoweryGnat** [Zrips/Jobs#1018]
***Description of issue:**
When an item is placed into a claimed furnace using a hopper, it causes the ownership to reset, and the furnace needs to be reclaimed. This prevents things such as automatically fueling furnaces from working properly. 
- - -
```
```

---

Server Type: Paper

Version: 1.16.4

**Comment by montlikadani** [comment]
This normal behavior. Therefore, there is an ownership option to prevent the part of making money that can be made almost continuously and with a lot of money. We need to remove ownership from the specified block so that the work does not count for twice as much salary (income).
