### ISSUE TITLE
Scoreboards show up for everyone, not just yourself.

### ISSUE THREAD

**Issue by mibby** [Zrips/Jobs#102]
Jobs 3.9.4
@Zrips Typing ```/jobs top <job> ``` pops up a scoreboard for everyone online, not just yourself.

**Comment by EvilOlaf** [comment]
Confirmed

**Comment by freethemice** [comment]
also is stays up forever and it won't go away

**Comment by sirmyllox** [comment]
+1

**Comment by Zrips** [comment]
+5
