### ISSUE TITLE
GlobalBlockTimer Bug

### ISSUE THREAD

**Issue by benzkungx10** [Zrips/Jobs#1020]
# All blocks will be protected X sec after player places it on ground.
    GlobalBlockTimer:
      use: true

The watermelon that came out repeatedly counted the time.

**Comment by montlikadani** [comment]
What is watermelon? Is this exist? I don't see. Also, where this material came from?

**Comment by benzkungx10** [comment]
melon_block

**Comment by montlikadani** [comment]
Closing, as there is no response.
