### ISSUE TITLE
Restrict Specific Job by World

### ISSUE THREAD

**Issue by brandinarsenault** [Zrips/Jobs#1021]
Hello team,

This might exist already and I just don't know the syntax for the permission, but are we able to restrict a specific job to a specific world? I know we can do an overall restriction with `jobs.world.worldname` but I don't know if you can make this more granular and drill down into specific jobs. This would be a great feature for us to allow mining worlds, only for miners, and worlds with more fishing land and opportunities for fishers, etc.

Thank you in advance,
Brandin.

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/blob/master/src/main/resources/jobs/example.yml#L563

**Comment by brandinarsenault** [comment]
> https://github.com/Zrips/Jobs/blob/master/src/main/resources/jobs/example.yml#L563

Thank you for this - is there a `world-whitelist` which would avoid us having to update this file anytime we create a new world? If not, I'll adjust my feature request.

**Comment by montlikadani** [comment]
There is an option in generalConfig called `UseAsWhitelist` within worlds.
