### ISSUE TITLE
Jobs Damage % for mobs doesn't count McMMO bonus damage as player damage

### ISSUE THREAD

**Issue by JustAMatt** [Zrips/Jobs#1025]
***Description of issue:**

When using the damage requirement for mob kills in jobs (for example for a hunter) the bonus damage the player does to a mob from an McMMO skill is not counted as part of the player damage, causing players to not get paid. 

**Server Type (Spigot/Paperspigot/etc):** Purpur

**Server Version (using `/ver`):**   902 (1.16.4)

**Relevant plugins (Delete if this isn't needed):** McMMO and Jobs

**Comment by JustAMatt** [comment]
Green thumb alsos messes with farmer jobs.

**Comment by Momshroom** [comment]
> ***Description of issue:**
> 
> When using the damage requirement for mob kills in jobs (for example for a hunter) the bonus damage the player does to a mob from an McMMO skill is not counted as part of the player damage, causing players to not get paid.
> 
> **Server Type (Spigot/Paperspigot/etc):** Purpur
> 
> **Server Version (using `/ver`):** 902 (1.16.4)
> 
> **Relevant plugins (Delete if this isn't needed):** McMMO and Jobs

I'm also seeing this issue with Paper (many versions, but just tested thoroughly with Paper 79 (1.17), Jobs 5.0.0.1 and mcmmo 2.1.200.  If I have no mcmmo combat skills, I get proper credit for killing mobs, if I have high level skills, it's very glitchy:  armored mobs don't give credit, mobs punched to death do not, mobs killed with sweeping edge do not, etc...  I'm wondering if perhaps this has to do with the way mcmmo applies limit break damage, but that's just speculation.  Either way, it is still very much a problem in recent versions of all involved plugins.  Thx in advance for looking into this!

**Comment by Momshroom** [comment]
For more information, my config for mob damage is:
`    MonsterDamage:
      # This section controls how much damage player should do to monster for player to get paid
      # This prevents from killing monsters in one hit when they suffer in example fall damage
      Use: true
      Percentage: 80`
      
And I have mcMMO set to apply limit break damage in PvE.

**Comment by JustAMatt** [comment]
Issue never been fixed for us either.

**Comment by mrfloris** [comment]
I had very little time to test, but it looked okay to me. However, subscribing to this to keep an eye on it. And I have to deep dive into this myself. I am on 1.17.1, latest jobs, and latest build of mcMMO overhaul. Will double check tomorrow if there's no follow up yet.

**Comment by Momshroom** [comment]
I saw the most issues with unarmed.

**Comment by Zrips** [comment]
c8936fc65331e9fd6e800e4fe34b221f02eda4f4
