### ISSUE TITLE
What does permissions in jobsconfig do?

### ISSUE THREAD

**Issue by mechcalvin** [Zrips/Jobs#1027]
i have difficulty understand these jobsconfig

permissions:
      aaaaaatest:
        node:
          value: true
          level: 0
        node2:
          value: true
          level: 10
      firstNode:
        # The permission node
        permission: aaaaaatest.node
    conditions:
      first:
        requires:
        - j:Miner-50
        - j:Digger-50
        - p:essentials.notnoob
        perform:
        - p:essentials.fly-true
    commands:
      fly:
        command: manuaddp [player] essentials.fly
        levelFrom: 100
        levelUntil: 100
      kit:
        command:
        - manuaddp [player] essentials.kits.woodcutter
        - msg [player] Now you can use woodcutter kit!
        levelFrom: 150
        levelUntil: 150
    items:
      firstOne:
        id: 278
        name: '&8Miner Pickaxe'
        lore:
        - '&eBobs pick'
        - '&710% bonus XP'
        enchants:
        - DAMAGE_ALL=1
        - FIRE_ASPECT=1
        moneyBoost: 1.1
        expBoost: 1.2
        pointBoost: 1.3
      helmet:
        id: 310
        name: '&8Armor'
        lore:
        - '&eBobs armor'
        - '&710% bonus XP'
        moneyBoost: 1.1
        expBoost: 1.1
    limitedItems:
      firstOne:
        id: 278
        level: 5
        name: '&8Miner Pickaxe'
        lore:
        - '&eBobs pick'
        - '&710% bonus XP'
        enchants:
        - DAMAGE_ALL=1
        - FIRE_ASPECT=1

**Comment by montlikadani** [comment]
Ask in the proper support section. Github is not the place to get support.

**Comment by mechcalvin** [comment]
OK, where is the proper support channel? i see there are no responds in spigot discussion
