### ISSUE TITLE
/jobs archive information not displaying

### ISSUE THREAD

**Issue by WhatsTheBadNews** [Zrips/Jobs#1028]
**Description of issue:**
On the latest version of Jobs (built from source), /jobs archive doesn't display the level nor the job name correctly

Steps to recreate:
- Join any job, do /jobs promote jobName 5
- Do /jobs leave jobName
- Check /jobs archive and you'll see it doesn't display properly

![image](https://user-images.githubusercontent.com/29821149/102399135-d6c01b80-3fa5-11eb-8802-5130283b2b96.png)

---

**Server Type (Spigot/Paperspigot/etc):** Tuinity latest

**Server Version (using `/ver`):** 1.16.4

**Comment by WhatsTheBadNews** [comment]
Our server's expert programmer looked into it and claims that it can be fixed by going into this class: `JobsCommands.java` and replacing, Line 449:
`String message = Jobs.getLanguage().getMessage("command.stats.output",`
with
`String message = Jobs.getLanguage().getMessage("command.stats.output.message",`

**Comment by Zrips** [comment]
15ae2988e0861c0819d0b732ee668ad17ed28ac1
Thanks for reporting issue and actually finding out solution to it.
