### ISSUE TITLE
Chat message set to "Title" shows both long name and short name combined together

### ISSUE THREAD

**Issue by 4xMeister** [Zrips/Jobs#1032]
Here is an example of the problem:
In titleconfig,yml I have:
-----
Titles:
  Apprentice:
    Name: SugarCube
    ShortName: SC
    ChatColour: WHITE
    levelReq: 1
-----
In jobConfig.yml I have (for all jobs):
chat-display: title

When level 1 is reached, the chat will show:
**[SugarCubeSC] {login name} blah...blah...blah**

It is combining both the "Name" & "ShortName" fields.

**Comment by montlikadani** [comment]
Are you sure that you not have chat prefix set in generalConfig?

**Comment by 4xMeister** [comment]
Thank you for your response.
Here is what I have set in generalConfig.yml: (which I believe is set correctly?)

modify-chat:
  use: true
  prefix: '&c['
  suffix: '&c]&r '
  separator: ' '

**Comment by Zrips** [comment]
899fe889473c99a0a7ccf55086c6ca9abb42e40c

**Comment by 4xMeister** [comment]
Hooray!! Thank You!! That solved the problem! My 8 year old son is sooooo happy!! I helped him put together a Minecraft Server that we are running together and he gets fixated on little details (nothing wrong with that :-) )- and that was one of them!! He is so happy now - and I am happy because I don't have to hear him complain about it ;-)
Thank you! Thank you! Thank you!
His minecraft server address is (in case you are curious): infinitybladesurvival.serveminecraft.net
