### ISSUE TITLE
Not able to give permission upon reaching a job level

### ISSUE THREAD

**Issue by silentnyte** [Zrips/Jobs#1033]
I am trying to add a permission to players when they reach level 10 in that job. I have tried all of these settings and none of them seem to do anything:

    permissions:
      firstNode:
        value: true
        permission: jobs.join.digger_miner
        level: 10
    conditions:
      first:
        requires:
        - j:Digger-10
        perform:
        - p:jobs.join.digger_miner-true
    commands:
      p_miner:
        command:
        - manuaddp [player] jobs.join.digger_miner
        - msg [player] You can now join the Miner job!
        levelFrom: 10
        levelUntil: 200

---

**Server Type (Paperspigot)** 

**Server Version (git-Paper-332 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)):** 

**Relevant plugins (Jobs 4.16.3):**

**Comment by isaaclepes** [comment]
can you gist or pastebin the entire configs for the 2 jobs?

Each job should be in a separate yml file.

What you have above says
"If they are in the job, they get permission jobs.join.digger_miner" (allows joining job named digger_miner)
"If they have Digger level 10, also add jobs.join.digger_miner-true" (Allows joining job named digger_miner-true)
"When reaching at least level 10 in the job this file is for, but not over 200, execute 2 commands, including one that allows joining digger_miner again"

But it isn't really easy to see what you are trying to do here.  I am guessing you want them to be level 10 in digger to be given access to Miner, but you have it referencing a new job type of digger_miner.

Firstly, to join this job they will require jobs.join.digger_miner permission

Second, lets review the example at https://github.com/Zrips/Jobs/blob/master/src/main/resources/jobs/_EXAMPLE.yml
# permissions granted for joining class
permissions:

# Permissions granted when particular conditions are meet
conditions:

# Commands executed when player reached level
commands:

Essentially, you wouldn't want to use all 3 of these.

In your 'Digger' job, you would want to have

commands:
  p_miner:
    command:
    - manuaddp [player] jobs.join.miner
    - msg [player] You can now join the Miner job!
    levelFrom: 10
    levelUntil: 200

This will execute the commadn to add jobs.join.miner, which unlocks miner for the player.

**Comment by montlikadani** [comment]
Without any permission plugin will not grants the permissions.
