### ISSUE TITLE
Try your new version true github, has some suggestions for improvement

### ISSUE THREAD

**Issue by broken1arrow** [Zrips/Jobs#1034]
**Description of new idea or improvement on existing one**
I like rely much you has split the job (I can finely see soo a job has a specific block easy). Save lot of time to not have to go true 5000 lines :)

And what i see has conversion from old to new format work fine, but one thing should generate even when it emigrated from the old to the new format. is the none.yml file soo server owners and similar, see that the opportunity exists.

If it possible to solve. 

Will test this out and see if it work better an 4.16.4 (that version lose linking with furnaces).

**Detailed information what should do what and when**

**Comment by montlikadani** [comment]
> And what i see has conversion from old to new format work fine, but one thing should generate even when it emigrated from the old to the new format. is the none.yml file soo server owners and similar, see that the opportunity exists.

I do not understand the correctness/word formation of this sentence. What should we do with the none.yml job file?

**Comment by broken1arrow** [comment]
> > And what i see has conversion from old to new format work fine, but one thing should generate even when it emigrated from the old to the new format. is the none.yml file soo server owners and similar, see that the opportunity exists.
> 
> I do not understand the correctness/word formation of this sentence. What should we do with the none.yml job file?

When the plugin convert jobConfig.yml to separated ´jobs files, it not create the new none.yml (only one you not has a old jobConfig.yml).

**Comment by montlikadani** [comment]
During migrating jobs from jobConfig into separate files, it depends from the jobConfig if you had last time a "none" job in the section, it will generate a none yml file in the directory. But if you removed from jobConfig or you not let the plugin grow up again after cleanup, it will not generate you. So, if you make a full cleanup to jobs (removing `plugins/Jobs` directory) it will generate you the "none" job. Or just copy the none file from [there](https://github.com/Zrips/Jobs/blob/master/src/main/resources/jobs/none.yml)

**Comment by broken1arrow** [comment]
> During migrating jobs from jobConfig into separate files, it depends from the jobConfig if you had last time a "none" job in the section, it will generate a none yml file in the directory. But if you removed from jobConfig or you not let the plugin grow up again after cleanup, it will not generate you. So, if you make a full cleanup to jobs (removing `plugins/Jobs` directory) it will generate you the "none" job. Or just copy the none file from [there](https://github.com/Zrips/Jobs/blob/master/src/main/resources/jobs/none.yml)

Yes i know  it do it if you remove the folder, but was a suggestion. So it bee easier for others to see it exist :) But if you think is unnecessary,
