### ISSUE TITLE
McMMO WoodCutting fails after 30 seconds

### ISSUE THREAD

**Issue by jordanwilliams1** [Zrips/Jobs#1039]
If you have tree feller ability for more than 30 seconds with mcmmo jobs no longer will limit the 'TreeFellerMultiplier'

Set your woodcutting level high in mcmmo then use the tree feller ability after 30 seconds. The first 30 seconds the jobs plugin tracks you are using mcmmo, but after that it dies and no longer tracks.

https://www.youtube.com/watch?v=_tC336d8C1k&ab_channel=JordanWilliams

Tested with McMMO Classic

**Comment by Zrips** [comment]
It was made in this way to protect against some issues if treefeller disable event is not fired properly and after 30 seconds it would remove record of player being in treefeller mode. We can definitely increase this timer to something like 60 seconds.
49ebf6ee88abb2f155a07d27c9698cc83ab2cf54
