### ISSUE TITLE
PreventHopperFillUps: true OPTION doesnt work via config

### ISSUE THREAD

**Issue by jordanwilliams1** [Zrips/Jobs#1040]
PreventHopperFillUps: true OPTION doesnt work via config (smelting)

**Comment by jordanwilliams1** [comment]
Papers disable-move-event: true caused this.  Will have to disable the optimization. Is there a possible work around for this as this is a huge optimization option that paper provides.

**Comment by montlikadani** [comment]
If you disables move event option in paper's config, that will not calls anymore the hopper move events, that prevents plugins from working ability. _That option should be removed from paper's config_
