### ISSUE TITLE
Message translation bug

### ISSUE THREAD

**Issue by LordVZlomka** [Zrips/Jobs#1042]
***Description of issue:** I changed the language to Russian (RU) and in message_ru.yaml lines 15-38 didn't translate.

![Screenshot_7](https://user-images.githubusercontent.com/71541816/103544396-0f009e80-4e6e-11eb-9fff-ae62b21879e9.png)
 
**Server Type (Spigot/Paperspigot/etc):** paper

**Server Version (using `/ver`):** 1.16.2

**Comment by Zrips** [comment]
Those lines no longer exist in a latest version due to centralized message format being implemented for multiple types of blocks. Simple wait for next release and test it out again and if issue still there let us know.

**Comment by LordVZlomka** [comment]
I don't think much changed...
![Screenshot_8](https://user-images.githubusercontent.com/71541816/103790171-db10af00-500e-11eb-9321-8b5df15eab3d.png)
