### ISSUE TITLE
Message translation bug

### ISSUE THREAD

**Issue by LordVZlomka** [Zrips/Jobs#1044]
*Description of issue: I changed the language to Russian (RU) and in message_ru.yaml lines 15-38 didn't translate.

![image](https://user-images.githubusercontent.com/71541816/103790354-157a4c00-500f-11eb-940a-7b3493fc50e9.png)

Server Type (Spigot/Paperspigot/etc): paper

Server Version (using /ver): 1.16.2

You said after your update the issue will be fixed

"Those lines no longer exist in a latest version due to centralized message format being implemented for multiple types of blocks. Simple wait for next release and test it out again and if issue still there let us know." 

Well, didn't work!
![Screenshot_8](https://user-images.githubusercontent.com/71541816/103790437-32af1a80-500f-11eb-87d0-8fdbea57814f.png)

**Comment by montlikadani** [comment]
Replace it with these and translate if you want:
```yml
newRegistration: '&eRegistered new ownership for [block] &7[current]&e/&f[max]'
noRegistration: '&cYou''ve reached max [block] count!'
```
