### ISSUE TITLE
Replace it with these and translate if you want: Can you give me the number of the lines to replace?

### ISSUE THREAD

**Issue by LordVZlomka** [Zrips/Jobs#1045]
Replace it with these and translate if you want:
```yml
newRegistration: '&eRegistered new ownership for [block] &7[current]&e/&f[max]'
noRegistration: '&cYou''ve reached max [block] count!'
```

_Originally posted by @montlikadani in https://github.com/Zrips/Jobs/issues/1044#issuecomment-755401809_

Can you give me the number of the lines to replace?

**Comment by LordVZlomka** [comment]
Can you give me the number of the lines to replace?
![image](https://user-images.githubusercontent.com/71541816/103792483-af42f880-5011-11eb-82da-73a0630903ab.png)

**Comment by montlikadani** [comment]
Stop creating so many issues. Support is on discord, github is not the place to get support.

**Comment by Geolykt** [comment]
Delete the file and let it regenerate. I think that is the best approach if you haven't edited too much
