### ISSUE TITLE
CAPS clic on inventory

### ISSUE THREAD

**Issue by TheCalypso** [Zrips/Jobs#1047]
**Description of new idea or improvement on existing one**
Hello,
I installed your plugin on my server and my players would like to know if it is possible to add the following functionality:
In Minecraft when you want to collect several items at the same time (crafting, melting, cooking ...) you use the CAPS right click key. However when we do this the plugin does not take into account the number of items retrieved. On the other hand you have marked that the plugin was compatible with 1.16 and in this version there is a method allowing to add this functionality, here it is https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/inventory/ClickType.html .

Congratulations for your jobs !

Have a good day !

- Caly -

**Comment by montlikadani** [comment]
There is an option in generalConfig called `Crafting.PayForEachCraft` which doing this.
