### ISSUE TITLE
World White-/Blacklist for each Job

### ISSUE THREAD

**Issue by Mawobi** [Zrips/Jobs#1048]
@Zrips Could you please add the World-White/Blacklist for each Job? This would be really helpful. For example you can enable then, that Farmer only works in your Claimworld and Hunter only in the Farmworld.

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/blob/master/src/main/resources/jobs/_EXAMPLE.yml#L566-L569

**Comment by Mawobi** [comment]
Oh, didn't saw this, sorry. Have a nice day and Thanks really much :)
