### ISSUE TITLE
Multiplier for Mobs from Spawners

### ISSUE THREAD

**Issue by Mawobi** [Zrips/Jobs#1049]
There is an option for "enable-pay-near-spawner". Please add a multiplier for money,points and xp, when the SpawnReason of a mob is equals Spawner. This would be really useful, that mobs from spawner give only 25% of earnings when spawned by spawner. Have a nice day! ~Mawobi

**Comment by montlikadani** [comment]
```yml
# Use jobs.nearspawner.[amount] to define multiplayer. Example jobs.nearspawner.-0.5 will pay half of payment, jobs.nearspawner.-1 will not pay at all
```

**Comment by Mawobi** [comment]
Oh man, thanks.
Will be checked if the player is near by the Spawner when killing the mob or if the mob is spawned by a spawner? Can't find it in the Code.

**Comment by montlikadani** [comment]
It is stored as entity metadata after the entity is spawned from spawner block.
