### ISSUE TITLE
GlobalBlockTimer overrides restrictedBlocks.yml for blocks affected by gravity and trees

### ISSUE THREAD

**Issue by JustAMatt** [Zrips/Jobs#1050]
***Description of issue:**

Blocks such as gravel and sand (and others affected by gravity) default to the GlobalBlockTimer value even if they have a specified value in restrictedBlocks.yml. You can break a static sand block, but if that action updates other sand blocks and they fall they will have the GlobalBlockTimer as if they were placed by a player. 

The same thing happens with trees, if trees are grown, they will sometimes (more likely to happen if you grow a tree over and over in the same spot) default to the GlobalBlockTimer even if they 1- weren't placed by a player 2- they have a lower specified value in restricedBlocks.yml.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## RestrictedBlocks: https://hastebin.com/zayabunibe.yaml
## GeneralJobs: https://hastebin.com/awiwumebep.yaml
#####################################
```

---

**Server Type (Spigot/Paperspigot/etc):** Purpur (Paper) (Happens in paper too)

**Server Version (using `/ver`):** 940 

**Relevant plugins (Delete if this isn't needed):** Jobs "4.17.0" (Latest from spigot)

**Comment by JustAMatt** [comment]
On further investigation, this bug is happening all across the board.

It pretty much breaks timed protection. If a player breaks a melon and then waits for the melon to regrow from the same stem and breaks it they will suffer the penalty even if it's not the same melon. 

Same thing happens with trees, the block placement is not being logged, just if space = block type. This is very harmful for the gameplay experience.

**Comment by montlikadani** [comment]
Fixed with above PRs ^
