### ISSUE TITLE
Reward system after levelling up in a job

### ISSUE THREAD

**Issue by harmatosbikafing** [Zrips/Jobs#1051]
Reward system after levelling up in a job

When you level up in a job like miner, you will get reward which you can edit in jobs' config. For example, you leveled up from 1 to level 2 in miner, you get money with the command "/eco give". In my opinion, that would be a good thing to reward players after gathering resources.

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/blob/master/src/main/resources/jobs/_EXAMPLE.yml#L544-L556

**Comment by harmatosbikafing** [comment]
i didn't saw that. Thanks your help
