### ISSUE TITLE
Jobs fireall earse exp

### ISSUE THREAD

**Issue by AdiLeTwix** [Zrips/Jobs#1054]
***Description of issue:**

---
I recently changed my job limit from 2 to 1
So I wanted to fire everyone from their jobs (white the command _/jobs fireall all_). The plugin does it but it doesn't save the exp of one of the 2.
Eg: 
I have 18lvl in Job A and 5 in JobB .
When I fireall and look at my stats I get "job A = 18 and job B = 0".

---

**Server Type Paper Build** 

**Server Version 1.16**

**Comment by AdiLeTwix** [comment]
Hey, if you need more info about this bug don't hesitate to ask me.
I'm really waiting for it to be fixed ^^'

**Comment by Zrips** [comment]
9d44da2daa0c1950afb5fc737fa5028d29d50989
