### ISSUE TITLE
PAPI Placeholder(s) not updating

### ISSUE THREAD

**Issue by greydayz1** [Zrips/Jobs#1057]
***Description of issue: After updating to 4.17.0, the %jobsr_totalplayers_JOB% placeholder doesn't update unless I reload the plugin. This may be happening with other placeholders too but I haven't tested it.**

---

**Server Type (Spigot/Paperspigot/etc): Paper** 

**Server Version (using `/ver`): Paper version git-Paper-400 (MC: 1.16.4)** 

**Relevant plugins (Delete if this isn't needed): PlaceholderAPI**

**Comment by montlikadani** [comment]
We need more information.

- Where did you use this placeholder
- We don't know whether you have PlaceholderAPI installed at all and which of the version.
- `%jobsr_totalplayers_woodcutter%` requires one of the jobName from jobs replacing by JOB
- Also try to make a screenshot about that placeholder and providing what is the output from `/jobs placeholders parse %jobsr_totalplayers_miner%`

**Comment by greydayz1** [comment]
The placeholder is being used in DeluxeMenus (1.13.4 DEV) and PAPI 2.10.9 is installed.

https://youtu.be/lZWPWrWUxYE
In the menu, when I hover over the job, look at where it says how many workers there are. It doesn't update unless the plugin is reloaded.
