### ISSUE TITLE
Option to make payments on players completely silent.

### ISSUE THREAD

**Issue by Tomi010817** [Zrips/Jobs#1059]
**Description of new idea or improvement on existing one**
It would consist on a config option that would make payments messages silent in both actionbar and chat sides if enabled.

NOTE: When I go to the locale file and change the messages to "" they don't disable, and you can still see the empty messages showing, that is why I suggest this option.

**Comment by montlikadani** [comment]
Does not make sense. We shouldn’t hide the messages when a player gets paid for doing something at a job. If this were to happen, for the future, players would not know where and how they would receive cash rewards, but this could still happen to server owners who only disable options with different behaviors.

**Comment by Tomi010817** [comment]
Hello @montlikadani !
Well, I currently use the actionbar for notifications with other plugin, and I don't want cash reward messages on chat since it is very spammy. You would ask "How will people realise when they get paid?" I have a configured scoreboard on my server which shows your currency, and when you do something at your job, you see how your currency increases. That is why I would like an option to disable it. On versions older than Jobs Reborn 4.17.0, I could disable payments messages in both actionbar and chat by setting `EnabledByDefault` to `false` on the generalConfig, but now when I set that to false it will return into chat messages. A way to disable payment messages would be sweet.

**Comment by Tomi010817** [comment]
@montlikadani Thanks a lot! <3
