### ISSUE TITLE
Jobs archived placeholders with job name not works as intended

### ISSUE THREAD

**Issue by Laukage** [Zrips/Jobs#1060]
***Description of issue:**
Hello, i'm having some trouble using your placeholderapi integrations, in my opinion the wiki around isn't really a "goto" i couldn't wrap my head around it atleast, i wanna show archived jobs stats when the player isn't a part of the job any longer but still has xp, however this isn't working, i also tried the /jobs placeholders parse - nothing works for me :/

![image](https://user-images.githubusercontent.com/46964809/104794030-6de6e180-57a5-11eb-8732-32cfa99db2c8.png)
![image](https://user-images.githubusercontent.com/46964809/104794046-8656fc00-57a5-11eb-9060-876276b98739.png)

---

**Server Type (Spigot/Paperspigot/etc):** Purpur

**Server Version (using `/ver`):** 1.16.4 (build-939)

**Jobs version**: I tried both on latest aswell as on 4.16.3

**Relevant plugins (Delete if this isn't needed):**
PlaceholderAPI
DeluxeMenus

**Comment by Laukage** [comment]
@montlikadani Is there a place where i can download Dev builds? or do i need to wait 2-3 months before a new release?

**Comment by montlikadani** [comment]
You can mention me on discord, and I'll upload the file with this fix.
