### ISSUE TITLE
Error on start server

### ISSUE THREAD

**Issue by SnaiilGaming** [Zrips/Jobs#1061]
***Description of issue:**
When I start my server I have an error
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://pastebin.com/RftPE24T
```

---

**Server Type (Spigot/Paperspigot/etc):** 
iSpigot 1.8.8 (Is a Fork of PaperSpigot)
**Server Version (using `/ver`):** 
https://prnt.sc/x5ztvb

**Comment by montlikadani** [comment]
Your server software does not supports the new sqlite which causes for plugins to do not start on server startup.
