### ISSUE TITLE
Add potions meta to shop configuration items

### ISSUE THREAD

**Issue by Convoy20** [Zrips/Jobs#1064]
Add new configuration options for giving potion items with their effect and level abilities.

This should be implemented to `GiveItems` section
https://github.com/Zrips/Jobs/blob/11700861660fc31c3680d56cfca790589f55325b/src/main/java/com/gamingmesh/jobs/config/ShopManager.java#L392

**Comment by AdiLeTwix** [comment]
It would also be nice to have it in the quests section (for the alchemist job).
