### ISSUE TITLE
Add javadoc for API

### ISSUE THREAD

**Issue by Elikill58** [Zrips/Jobs#1065]
**Description of new idea or improvement on existing one**
There isn't any javadoc for method showed on API use example.

But, personnally, I would like to know if` getJobsPlayer(Player)` or `getJobProgression(Job)` can return null, or if I have to add the player to the job progression before getting it. And that's only example.

So, can you add Javadoc please ?

**Comment by DevGalacticB69** [comment]
This would be an awesome feature!
