### ISSUE TITLE
Add menu for rewards

### ISSUE THREAD

**Issue by JessyDrew** [Zrips/Jobs#1067]
**Description of new idea or improvement on existing one**

I propose the idea of ​​a menu with level rewards. Example level 100 minor I unlock a new pickaxe. But not automatically, you would have to go to / jobs menu, choose our job and click on the reward.

**Detailed information what should do what and when**

Add the / jobs menu command. Which displays the jobs available.
Once on the job that you want, you have all the vision on the available rewards.
Example: level 10 -> 15 gold ingot
level 20 -> ///
level 100 -> New pickaxe
level 200 -> ///

And when we click on the rewards not available a message says "You do not have the reward for the moment"

**Comment by Convoy20** [comment]
Maybe possible to unlock with shops...

But you could also just give permissions to essential kits with the rewards too

**Comment by JessyDrew** [comment]
I do not understand what you want "with shops" can you enlighten me? I hadn't thought of the kits. but in this case it is necessary to set the conditions of **job level: x?**

did you manage to do what I'm looking for? if so would it be possible to show me?

**Comment by Convoy20** [comment]
https://i.imgur.com/hlH0uhD.gif

We have a bunch of different things set up at different levels, it costs points, and I haven't figured out if there is a way to do onetime only usage, but you could add shop items that give permissions to a one time use kit if you needed to.

**Comment by montlikadani** [comment]
I don’t think this feature should be in Jobs, as it’s not tied to doing the work. It would be unnecessary to add this, as there are plenty of plugins that would work with the Jobs plugin if its author adds the plugin as a dependency. This is, for example, [AdvancedAchievements](https://www.spigotmc.org/resources/83466/), which was recently added as a dependency by the author.

**Comment by JessyDrew** [comment]
I dont think it's related to JobsReborn. but i saw someone using it on their server.
But it would be interesting to add it!

Example: 
Since we have the possibility to configure the rewards in the "example.yml" in the "orders" category,
you need a command like / jobs rewards <jobs> or / jobs <jobs> and display all the rewards.

**Comment by montlikadani** [comment]
> i saw someone using it on their server.

They probably uses an unique or a public plugin which has compatibility with jobs.

There are some options in jobs config called, `conditions`, `permissions` and `commands`. With this users can configure the level-up, level-from when the players can get reward commands or even payout. https://github.com/Zrips/Jobs/blob/master/src/main/resources/jobs/_EXAMPLE.yml#L509-L564

**Comment by JessyDrew** [comment]
https://imgur.com/a/lC97Yvs

**Comment by montlikadani** [comment]
That is called [Command Panel](https://www.spigotmc.org/resources/67788/), [Chest Commands](https://github.com/filoghost/ChestCommands) or [BetterGui](https://www.spigotmc.org/resources/75620/)

**Comment by JessyDrew** [comment]
Can you help me?
How could I go about putting the <commands / permission> in a bettergui?

**Comment by montlikadani** [comment]
Please look at the well-documented page of that plugin or ask the author. It provides much more documentations on how to use. We can't help you with that. https://github.com/BetterGUI-MC/BetterGUI/wiki/Basic-tutorial

**Comment by broken1arrow** [comment]
Is even more gui menu plugins out too.
