### ISSUE TITLE
Individual and Global Limit for Furnaces

### ISSUE THREAD

**Issue by TKwSni** [Zrips/Jobs#1073]
**Description of new idea or improvement on existing one**

This commit broke one of the stuff we had configured, a global limit.
https://github.com/Zrips/Jobs/commit/3059833910e88c903e5b25b76de976ed53b1ec1c

Could it be possible to make it work as a global limit instead per type of furnace ?

It was great the way it worked before

**Detailed information what should do what and when**

Basically Keep individual limits for furnace, blast-furnace, smokers and add global limit for all of the three if we setup like that in the config. So each server can configure it to their liking

**Comment by montlikadani** [comment]
The above commit "re-" implements this, so in the future releases you need to use `jobs.maxownership.5` to specify how many furnaces/stands can the player have globally.

**Comment by TKwSni** [comment]
Thanks but I meant like this 

Furnace, smoker, and blast furnace all count for "furnace limit" and

Brewing stands in a different limit.

**Comment by montlikadani** [comment]
[This commit](https://github.com/Zrips/Jobs/commit/30e09d443b466030b898211611fa7dc5e442d4d4) will be implemented in the future release. You need to use `jobs.maxfurnaceownership.3`
