### ISSUE TITLE
allow two same type of materials

### ISSUE THREAD

**Issue by lostINParadies** [Zrips/Jobs#1077]
I just put a new job on. In the job menu occur twice oak_log, because I want to pay differently depending on the level. Once from level 1-34 and then again from level 35. However, this does not work because I think you can always mention only one block. It would be cool to expand that to give more options and set pay by level. With the permissions I can only give a boost for all materials, not only for single materials. I also don't know if this is not wanted or a bug. 

Example: 

``` 
    oak_log:
      income: 0.1
      points: 1
      experience: 1
      from-level: 1
      until-level: 35
    oak_log:
      income: 0.2
      points: 1
      experience: 2
      from-level: 36 ```

**Comment by lostINParadies** [comment]
this is how I set it up: https://pastebin.com/K8QtMiPR

**Comment by Zrips** [comment]
Yaml file cant support format like this in general. We cant have same name for 2 different sections, one will be skipped automatically.
