### ISSUE TITLE
Enchantments registered from other plugins as vanilla enchants are not picked up by JobsReborn

### ISSUE THREAD

**Issue by AZFire1** [Zrips/Jobs#1078]
**Description of issue:**
Hello, I use EcoEnchants. It registers all of its new enchantments as vanilla enchants. It already works with all of my plugins but doesn't work with Jobs for some reason. JobsReborn does not detect any of the enchants it registers but CMI on the other hand, detects all enchantments it registers. I looked at the source code for Jobs (note: I currently have barely any experience with coding), but if I am looking at it right, the enchants it detects added into the plugin are provided by CMI when it hooks into it? I'm likely wrong though as then it would require CMI to run. Does the plugin strictly only have support for vanilla enchants possibly being hardcoded? I wouldn't assume so as when it starts up it says "Loaded (x) custom enchantment names", absolutely none of these are EcoEnchants enchants. I talked to the developer of EcoEnchants before coming here. They said it should work with most, if not, all plugins as all enchantments registered are as vanilla and he also said you might've hardcoded the vanilla enchants in Jobs and sent me here. I doubt they are hardcoded, I'd love your help in fixing this as I've already put a lot of time and effort into configuring these enchantments and adding them into the plugin and wouldn't want the time to go to waste. Thank you, hope to receive a response from you soon!
---

**SERVER LOGS:**
https://bin.bloom.host/emusubecey.yaml

**CONFIG SECTION:**
Here's one of my jobs I have set up with some custom enchants: https://bin.bloom.host/oqiteriziy.yaml

---

**Server Type (Spigot/Paperspigot/etc):** Purpur, yes I've tested this on Paper, same result.

**Server Version (using `/ver`):**  https://bin.bloom.host/ojijuqitaf.yaml

**Relevant plugins (Delete if this isn't needed):**
EcoEnchants: https://www.spigotmc.org/resources/%E2%9A%A1-1-15-1-16-5-ecoenchants-%E2%9C%A8-220-custom-enchantments-%E2%9C%85-essentials-cmi-support.79573/
EcoEnchants Compatability Page: https://ecoenchants.willfp.com/usage/compatibility
Eco: https://www.spigotmc.org/resources/eco.87955/

**Comment by Zrips** [comment]
36a3051452c54c178c29a08ebf2cf7b4ba69eae2
