### ISSUE TITLE
Suggestion - Certain items require a player have a job to craft

### ISSUE THREAD

**Issue by Bysokar** [Zrips/Jobs#108]
Hi There,

Just a quick idea I had, it'd be really cool if certain items could be restricted to a certain profession, and even level before they can craft them.

An example of this would be say, a Diamond Pickaxe for Miners.

I'm not suggesting that players have to have a profession to make everything miner related.
It'd just be a way for the good stuff to be harder to get and force players to use an in-game marketplace to trade higher end items and force interaction with each other in general.

Config would be:

Under a configuration section for each job, an optional section could be called "itemsRestrictedCrafting" or something similar, with entries like the one below.

ItemMaterial: DIAMOND_PICKAXE
ItemMeta: 0
LevelRequired: 50

Now I run a modded server, which drastically increases the number of items I can have / use under this, but I just thought I'd share the idea to see if you'd be interested before trying to make my own version of the plugin :)

**Comment by TheDeviantCrafter** [comment]
This could sort of be done with existing options, but it wouldn't be very intuitive. You could disable a crafting recipe using another plugin, then add the desired items to `/jobs shop` for zero points.
