### ISSUE TITLE
 Force custom recipe name

### ISSUE THREAD

**Issue by Reeferx7** [Zrips/Jobs#1082]
**Description of new idea or improvement on existing one**

Hello i use recipe manager to make custom recipes and i add on job this:
  Craft:
    '!Tomato Soup':
      income: 10.0
       points: 0
      experience: 6.0

It works, give me the xp/money but in /jobs info <jobname> GUI dont show the name its say none.
Is possible to force the name on info gui?

![PhSFn74](https://user-images.githubusercontent.com/8740881/108113346-15ef1380-70a0-11eb-9500-f0298fe09790.png)
![gI2Uiyt](https://user-images.githubusercontent.com/8740881/108113351-1687aa00-70a0-11eb-8c21-a5cdb92f38b0.png)

**Comment by Zrips** [comment]
ef3eac05bcad807cfad796409bb704da48bba4fc
