### ISSUE TITLE
Words_lang.yml

### ISSUE THREAD

**Issue by Thin-Troll** [Zrips/Jobs#1083]
***Description of issue:**
some names are not in Words_lang.yml at all and I can't add them?
Instead
Stone, Granite, Andesite, Diorite is written - STONE STONE STONE STONE.
So not only with a stone, but also with other objects. there is a lot of things missing from the blocks for 1.12.2
and I can't add to the list, it just deletes my new lines
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## PASTE ERROR HERE ##
####################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```
https://paste.ee/p/PLACy
---

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
1.12.2 (build #1618)

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/36a3051452c54c178c29a08ebf2cf7b4ba69eae2
