### ISSUE TITLE
Version incompatibility in item names

### ISSUE THREAD

**Issue by Thin-Troll** [Zrips/Jobs#1085]
***Description of issue:**

I already reported a problem with word_lang.yml, but I translated it and the problem persists.
I think it is similar, but not with translation files, but with the works themselves, they define 4 different blocks as one.
https://i.imgur.com/ykEH7Or.png (STONE, STONE, STONE, STONE)
but should be: Stone, Granite, Andesite, Diorite

```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
https://paste.ee/p/EaTLY
I will throw off the miner as an example, but there is actually all the work. there it will be incorrectly defined in almost every block.

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
1.12.2 (build #1618)

**Comment by Zrips** [comment]
33bcbd6d626587be5ce6a9c65175f9a3e90144df
