### ISSUE TITLE
Full Description Feature Not working

### ISSUE THREAD

**Issue by KingofAnomaly** [Zrips/Jobs#1087]
***Description of issue:**

I have tried almost everything with my job configs but I just can't seem to get the full description feature to work, it just doesn't show any description when I try to use it.

**CONFIG SECTION**

Crafter:
  fullname: Crafter
  shortname: C
  FullDescription:
  - '&aEarn Money By Crafting Basic Items'
  - '&2Unlocks Jobs:'
  - '  &6Carpenter'
  - '  &cCook'
  - '  &5Enchanter'
  ChatColour: GRAY
  BossBarColour: GOLD
  chat-display: shorttitle
  max-level: 100
  leveling-progression-equation: 20000-(20000*0.999^joblevel)
  income-progression-equation: baseincome-(baseincome*0.999^joblevel)
  points-progression-equation: basepoints+(basepoints*(joblevel-1)*0.15)-((basepoints+(joblevel-1)*0.01)*((numjobs-1)*0.05))
  experience-progression-equation: baseexperience-(baseexperience*((numjobs-1) *0.01))
  rejoinCooldown: 10
  Gui:
    Item: crafting_table
    slot: 1
  maxDailyQuests: 0
  Quests: []
  cmd-on-join:
  - 'lp user [name] parent set crafter-0 world=world'
  commands:
    alchemy-1:
      command: lp user [player] promote sk-alchemy
      levelFrom: 10
      levelUntil: 10  
    repair-1:
      command: lp user [player] promote sk-repair
      levelFrom: 10
      levelUntil: 10  
  Craft:
    acacia_button:
      experience: 0.1
      income: 10
      points: 0.1
    acacia_planks:
      experience: 0.45
      income: 74
      points: 0.1
    birch_button:
      experience: 0.1
      income: 10
      points: 0.1

**Server Type** 
Paperspigot
**Server Version** 
git-paper-467

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/7ecb26548480496103f63f11e7942b331bbc93e1

Temporary you should use `description` and use `\n` for new line.
