### ISSUE TITLE
JobsReborn+GroupMnager

### ISSUE THREAD

**Issue by nikolaknife** [Zrips/Jobs#1088]
How can i connect jobs reborn and group manager , i mean when somebody pick miner he gets miner and miner permissions if that is possible please tell me how , thanks!

**Comment by HeyWinkeyFace** [comment]
Perhaps ask for support in the Discord instead of asking for support with a New Feature Suggestion Ticket...

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/blob/master/src/main/resources/jobs/_EXAMPLE.yml#L598-L600

> Perhaps ask for support in the Discord instead of asking for support with a New Feature Suggestion Ticket...

^
