### ISSUE TITLE
VipMaxLevel Not working

### ISSUE THREAD

**Issue by BobbyMere** [Zrips/Jobs#1089]
***Description of issue:**

The permission jobs.[name].vipmaxlevel.[numer] has stopped working since version 4.16.3

The config max level is set to 20 and I give myself the permission jobs.artisan.vipmaxlevel.25, even though the viplevel is higher than the default config max, doing /jobs stats while at lvl 20 will return the message "max level." If I manually promote myself 1 level higher, the "max level" goes away and the viplevel will function as normal and I can freely train to level 25 

This issue doesn't happen in v4.16.2 but does happen in v4.16.3-4.17.1

I tested this with just luck perms, jobs ,vault and essentials with jobs v4.16.0, 4.16.1, 4.16.2, 4.16.3. 4.17.0 and the dev build 4.17.1
With paper spigot version 1.16.3, 1.16.4 and 1.16.5

```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```
  max-level: 20
---

**Server Type (Spigot/Paperspigot/etc):** 
paper spigot 1.16.3, 1.6.4 and 1.16.5 but main version was 1.16.4
**Server Version (using `/ver`):** 
v1.16.4 B396

**Relevant plugins (Delete if this isn't needed):**
I tested this with just luck perms, jobs ,vault and essentials with jobs v4.16.0, 4.16.1, 4.16.2, 4.16.3. 4.17.0 and the dev build 4.17.1

Also switched out luck perms and tried Groupmanager
<img width="436" alt="Screenshot 2021-02-20 121256" src="https://user-images.githubusercontent.com/25316276/108604689-0bb96780-7375-11eb-8139-a9d37ebe63fd.png">

All of these are level 20 but with a granted viplevel much higher than 20
<img width="233" alt="Screenshot 2021-02-20 121558" src="https://user-images.githubusercontent.com/25316276/108604754-7a96c080-7375-11eb-9682-041b3a6048c7.png">

**Comment by BobbyMere** [comment]
Is being looked into? Or perhaps an already known issues?

**Comment by Zrips** [comment]
Should be in working order with next build
