### ISSUE TITLE
error

### ISSUE THREAD

**Issue by KonoromiHimaries** [Zrips/Jobs#109]
logs
https://gist.github.com/mat41997/12625974697b1552a6dedcb75641ea3d

timings
https://timings.aikar.co/?id=2fedfe3aa03d4f62b8cb68d6502b44e1#plugins

**Comment by Zrips** [comment]
Seams that your locale file is messed up, can you post it here so I can check what is incorrect or just remove it and let it regenerate.

**Comment by mat41997** [comment]
[Jobs.zip](https://github.com/Zrips/Jobs/files/1117796/Jobs.zip)
