### ISSUE TITLE
Incorrect display of names on version 1.12.2.

### ISSUE THREAD

**Issue by Thin-Troll** [Zrips/Jobs#1092]
***Description of issue:**

Incorrect display of names on version 1.12.2.
Log 1, Log2, Log 3
Step 1, Step 2, Step 3
Stained Glass 1, Stained Glass 2, Stained Glass 3 
etc

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## PASTE ERROR HERE ##
####################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---
![image](https://user-images.githubusercontent.com/61376903/108917244-44955d00-7651-11eb-8207-5276001979f4.png)
![image](https://user-images.githubusercontent.com/61376903/108917348-68f13980-7651-11eb-9d09-c9deb1696bca.png)

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
1.12.2 (build #1618)

________
I understand that you have a lot of work, but could you check until the end if the problem remains?
this is already the third report, it's not difficult for me to write them, I just wait a long time until you put together the build to upload it to yourself
https://github.com/Zrips/Jobs/issues/1085
https://github.com/Zrips/Jobs/issues/1083

**Comment by montlikadani** [comment]
Stained glass 1 2 3 is not supported. Use the full name of those materials. `green_stained_glass`, `red_stained_glass`
