### ISSUE TITLE
Command execute by console once the player have reached a certain job level

### ISSUE THREAD

**Issue by Hei5633** [Zrips/Jobs#1094]
I think it would be pretty useful that if we can set console to execute a command when a player have reached a certain job level.

Let say we have a reward system, for every 25 level the player have reached, we will give a small reward, in this case a diamond. Once the player have reached lv25, lv50, lv75, lv100, the server will automatically execute the give command to the player, rewarding them for archiving it.

I know daily quest can do that but it would be meaningless if the level reward can be obtain over and over again. I see a command on join and leave config but not command on level, so I really hope that this could be included in a future update. Much thanks on maintaining the plugin.

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/blob/master/src/main/resources/jobs/_EXAMPLE.yml#L546-L567

**Comment by Hei5633** [comment]
```
> 
> 
>  commands:
>     # command name, just to have better idea what this do
>     weapon:
>       # Command its self, this will be executed from console, so all commands should work
>       # Possible variables are: [player] [jobname] [oldlevel] [newlevel]
>       command: minecraft:give [player] minecraft:netherite_axe{AttributeModifiers:[{AttributeName:"generic.attack_damage",Amount:15,Operation:0,UUID:[I;-121125,34908,94915,-69816],Slot:mainhand,Name:"generic.attack_damage"},{AttributeName:"generic.attack_speed",Amount:1,Operation:0,UUID:[I;-121125,35008,94915,-70016],Slot:mainhand,Name:"generic.attack_speed"}]} 1
> 
>       # When to execute this command first time
>       levelFrom: 100
> 
>       # Until when to do this command
>       # This can be set to same level as levelFrom, so this command will be executed only once
>       levelUntil: 100
```

**Comment by Hei5633** [comment]
Am i making any mistakes here?
