### ISSUE TITLE
Compability with oneblock (Bentobox)

### ISSUE THREAD

**Issue by kFxDaKing** [Zrips/Jobs#1095]
Hello, could you please look into this?
https://github.com/BentoBoxWorld/AOneBlock/issues/88

**Comment by montlikadani** [comment]
> Hello, its still not working, it always work just for a while, then it stops work, and Jobs plugin stop counting broken blocks.
> 
> When i teleport to normal world here it works, but its not counting blocks from oneblock untill server restart, and then it works just for few minutes.

Just disable `PlaceAndBreakProtection` in generalConfig

**Comment by kFxDaKing** [comment]
Well that fixes it, but its not fix at all, players now can abuse it.
