### ISSUE TITLE
Add Hex support?

### ISSUE THREAD

**Issue by AZFire1** [Zrips/Jobs#1101]
**Description of new idea or improvement on existing one**
I'd love it if Hex support as added to the Jobs plugin. For the most part, I've managed to get around all barriers with Hex by doing things similar to "§x§f§2§9§9§c§2§l" to get it working though this workaround no longer works since the new dev releases.. I'd love if Hex support was officially added to the plugin.

**Detailed information what should do what and when**
As I mentioned, I'd just like Hex code support for Jobs.

**Comment by montlikadani** [comment]
It is already a thing since the 1.16 is released. Also, where you trying to use hex colors?

**Comment by AZFire1** [comment]
@montlikadani if it's already a thing? How do I correctly use them with the plugin? I've tried CMI's method of "{#hex}" thought that did not work. As I said, the only way I've gotten hex to work is with the above way I mentioned. I am trying to use them in the job names. The job names do not show up properly in both the command tab completion and in the "/jobs browse" GUI.

**Comment by AZFire1** [comment]
@montlikadani any updates on this? Have you had a chance to try it out?

**Comment by Zrips** [comment]
01e47f457ac9585ec647ffa2ed07936399f9fffc
Color codes are not supported in jobs name, as its used in different places. But we can add new config section for defining actual jobs display name which will be used in specific places like GUI
