### ISSUE TITLE
Problem execute command

### ISSUE THREAD

**Issue by Chrqmated** [Zrips/Jobs#1102]
Hello ! When I reach level 10 in the hunter profession, I want to be able to send a command (/ give diamond_sword ...) to the player who has just unlocked level 10. How do I do this? (1.12.2 Paper / Spigot)

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/blob/master/src/main/resources/jobs/_EXAMPLE.yml#L547-L559
