### ISSUE TITLE
[Jobs] join <job> <another_text> signs don't work

### ISSUE THREAD

**Issue by bobhenl** [Zrips/Jobs#1103]
***Description of issue:**

---

Hi, I have VIP jobs. And I use signs there that contains on the latest line that this job is from specific VIP rank. BUT when I add this text to the latest line, then clicking on it doesn't work.... 
![image](https://user-images.githubusercontent.com/18662086/109621524-5d16e300-7b3b-11eb-9b7e-10203d8b6e18.png)
This doesn't work, in chat it show the help for command /jobs join.

BTW on info signs it works great, just here it doesn't.
![image](https://user-images.githubusercontent.com/18662086/109621566-6bfd9580-7b3b-11eb-90f3-7461bbe31484.png)
This works
---

**Server Type (Spigot/Paperspigot/etc):** Yatopia 

**Server Version (using `/ver`):** 1.16.5

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/fc5c5bfd08d2b732d9fcae06621eb6400fb75aa2 and https://github.com/Zrips/Jobs/commit/1413662c19532ea79010aedebb034285623247fb
