### ISSUE TITLE
Main and Side Jobs

### ISSUE THREAD

**Issue by Dudel3698** [Zrips/Jobs#1106]
**Adding job categories**

I would like Players to be able to join a Main-Job and a Side-Job.
example:
1 Main-task(Job): Miner, Hunter, ...
 1 Task, that aren't done frequently: Brewing Enchanting, ...

Players should be able to join 1 of each of the job categories. 
(possible example: Miner and Brewing) (impossible example: Miner, Hunter)
but "max-jobs: 2" gives players the possibility of choosing independently.

I am sorry for my bad english (no native)
and once again sorry if it is already possible via permissions or the like and I wasn't intelligent enough to think of a solution other than giving all main jobs the settings of the side-jobs (is not in my intention)

Thx for reading c:

**Comment by montlikadani** [comment]
That doesn't sound like a good idea. If this were to be included, it would break the current behavior and cause problems for the players as well. If you want to solve this on another GUI interface, or into the current Jobs GUI, it may be acceptable. The other thing is that if the `max-jobs` setting were ignored when this feature is implemented, the players and most importantly the server owner would be confused as to why the maximum number of jobs is not working properly.
