### ISSUE TITLE
Curse of Vanishing on an item causes infinite Jobs exp from grindstone for Weaponsmith

### ISSUE THREAD

**Issue by Skizzles** [Zrips/Jobs#1107]
***Description of issue:**
Infinite exp when using grindstone with curse of vanishing
---
https://www.youtube.com/watch?v=r0CBRjc23gU
---

**Server Type (Spigot/Paperspigot/etc):**  Purpur

**Server Version (using `/ver`):**  1.16.5

**Relevant plugins (Delete if this isn't needed):** Jobs Reborn

**Comment by montlikadani** [comment]
Which of the Jobs version you use and what is the action for Weaponsmith leather_hat?

**Comment by Skizzles** [comment]
Jobs version: 4.17.0
Weaponsmith action is Craft

**Comment by montlikadani** [comment]
Well, I can't reproduce in 4.17.1 version of Jobs. So you have to wait for the next release.
