### ISSUE TITLE
Vtrade documentation

### ISSUE THREAD

**Issue by AdiLeTwix** [Zrips/Jobs#1109]
Hello, I know that it has been added the possibility to gain experience by trading with villager. However, there is no documentation on it. Could you tell me what to do? Thanks 😸

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/blob/master/src/main/resources/jobs/_EXAMPLE.yml#L311-L320

**Comment by AdiLeTwix** [comment]
Ok thanks !
