### ISSUE TITLE
Jobs multiple jobs issue

### ISSUE THREAD

**Issue by NotAShelf** [Zrips/Jobs#1115]
***Description of issue:** On version 4.17.1, players can join only one job at a time despite having the maximum amount of joinable jobs to 3. When a user joins a job and then tries to join another, they see the message "You are already in [Jobname]" with jobname being the first job they've taken (which is the only active one after choosing a job) and NOT the job they try to join.

---

---

**Server Type (Spigot/Paperspigot/etc):** Paper 1.16.5

**Server Version (using `/ver`):** build 525

**Comment by montlikadani** [comment]
Can't reproduce here, works as intendent.

https://user-images.githubusercontent.com/30026208/111800027-d6e4f580-88cb-11eb-9add-e4a195778385.mp4

**Comment by NotAShelf** [comment]
turned out to be a problem with sqlite database appearing read only

resolved by switching to msql

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/51a0b4bef7461e7cba2bb065b77dcbb9062d2224
