### ISSUE TITLE
Job title missing from chat after newest update (4.17.1) with EssentialsXChat

### ISSUE THREAD

**Issue by Bloodlex** [Zrips/Jobs#1118]
**Description of issue:** Before the update titles were displayed in chat, but now it's only {jobs}. The placeholder is not filled with the right titles. I use EssentialsXChat:

EssentialsXChat configuration:
  format: '{DISPLAYNAME} {jobs}: {MESSAGE}'

Jobs Configuration:
modify-chat:
  use: false

Example:
![image](https://user-images.githubusercontent.com/1086720/111497035-13381a80-8741-11eb-86f4-08ea72dbba73.png)

Everything worked until the update.

Please help me. Jobs is an amazing plugin, thank you! 🙂 

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** This server is running Paper version git-Paper-550 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Relevant plugins (Delete if this isn't needed):** EssentialsX, EssentialsXChat, LuckPerms

**Comment by Bloodlex** [comment]
@montlikadani Could you please help? 😢

**Comment by TheCiROMG** [comment]
If you made a backup, put the previous version, unfortunately we will not see an update for a long time

**Comment by Bloodlex** [comment]
> If you made a backup, put the previous version, unfortunately we will not see an update for a long time

Oh, I see, can I ask why?
