### ISSUE TITLE
[Jobs] join <job> <another_text> signs still don't work

### ISSUE THREAD

**Issue by bobhenl** [Zrips/Jobs#1119]
***Description of issue:**

---

Hi, this problem still isn't solved... https://github.com/Zrips/Jobs/issues/1103

![image](https://user-images.githubusercontent.com/18662086/111511318-e985f000-874e-11eb-8b63-f41e7a3577da.png)

![image](https://user-images.githubusercontent.com/18662086/111511322-ea1e8680-874e-11eb-97b8-120f02b6f4bb.png)
![image](https://user-images.githubusercontent.com/18662086/111511345-ef7bd100-874e-11eb-8484-6941466502c2.png)

---

**Server Type (Spigot/Paperspigot/etc):** Tuinity

**Server Version (using `/ver`):** 1.16.5

**Comment by montlikadani** [comment]
https://user-images.githubusercontent.com/30026208/111512344-f0613280-874f-11eb-8479-3aef1ece93c5.mp4

For me works as intended.

**Comment by bobhenl** [comment]
![image](https://user-images.githubusercontent.com/18662086/111849451-eedd6900-890d-11eb-9c83-62193b3b2a5e.png)
Try exactly this text, &c&lSomething works for me too, but &b&lod MVIP doesn't work @montlikadani  Maybe it's too long or why?

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/0d138d66645840435d261bfe7c784925f6253a67
