### ISSUE TITLE
save-period - Crash in Jobs-DatabaseSaveTask

### ISSUE THREAD

**Issue by lippoliv** [Zrips/Jobs#112]
Hi there,
thanks for that awesome Plugin.

I'am trying to Setup a Server with it, but the `save-period`-Job crashes it down. Here the Crash: https://pastebin.com/gdEGUQv4

Whole Server runs on `docker-compose`-Project based on `itzg/minecraft-server` in SPIGO. I will switch to mysql now and give it a try.

Server: Offline-Test-Maschine. Just me online.

**Comment by lippoliv** [comment]
Good news: It works with MySQL without any Problems.

**Comment by Zrips** [comment]
What mc build are you using?

**Comment by lippoliv** [comment]
Spigot 1.11.2


--
Mit freundlichem Gruß
   Oliver Lippert

Am 04.07.2017 um 13:02 schrieb Zrips:

**Comment by Zrips** [comment]
Strange, from everything it just looks like plugin was denied from writing data into sqlite data base. Does plugin have permission do to so? or maybe sqlite file is only-write, never encountered issue like this before, so can't really be in help at this point :)

**Comment by lippoliv** [comment]
Folder and SQLite-File where created by itself, so I think permissions schould be fine.

For me switching to MySQL Worked fine and is the more stable way since multiple plugins now are using same DB. Better for Backups ;)

Feel free to close as `works for me` if you cant reproduce the Problem. If other users start reporting such behavior deeper analyses could start.

**Comment by CodingKoopa** [comment]
Reproduced on [my own](https://gitlab.com/CodingKoopa/yamdi) Docker setup, with a very similar [error](https://gitlab.com/snippets/1858201). I tried making the SQLite DB executable, but the server still crashes.
