### ISSUE TITLE
/jobs bonus now not show numbers if you has 1% bonus or -1%.

### ISSUE THREAD

**Issue by broken1arrow** [Zrips/Jobs#1120]
***Description of issue:**

The command /jobs bonus, not show -1% (has no jobs some has lower an -1% so don´t know if -2% work) and 1%, but 2% and higher work (dynamic bonus). In placeholders it show the numbers.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**

---

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
415
**Relevant plugins (Delete if this isn't needed):**
jobs 4.17.1 from spigot.

**Comment by montlikadani** [comment]
What? What you mean by jobs bonus does not show -1%? Your grammatical correctness is a bit confusing.

**Comment by broken1arrow** [comment]
> What? What you mean by jobs bonus does not show -1%? Your grammatical correctness is a bit confusing.

Sry for that. If dynamic bonus is -1  0 or 1 it show it as 0. 2 and up show properly.

**Comment by Zrips** [comment]
84be2eba795366b0a4a1a127104b80447f01e373
