### ISSUE TITLE
[Jobs] join <job> <2 words text> signs still don't work

### ISSUE THREAD

**Issue by bobhenl** [Zrips/Jobs#1121]
***Description of issue:**

Hi, I just wanna continue to ticket https://github.com/Zrips/Jobs/issues/1119. i've discovered that two words are needed on the latest line.

But weird is that on info signs 2 words on the latest line normally work.

![image](https://user-images.githubusercontent.com/18662086/111849644-63180c80-890e-11eb-8de8-90bb1f31d455.png)

---

**Server Type (Spigot/Paperspigot/etc):** Tuinity

**Server Version (using `/ver`):** 1.16.5

**Comment by montlikadani** [comment]
Don't open same issue so many times, we can't be online in every minute, wait for the reply patiently.
