### ISSUE TITLE
Procosmetics error

### ISSUE THREAD

**Issue by n54b** [Zrips/Jobs#1123]
A little error when i use ProCosmetics (https://www.spigotmc.org/resources/procosmetics-300-cosmetics-treasurechests-eula-compliant-1-8-1-16-support.49106/)

Gadget => Merry go round

https://pastebin.com/jex9CTrc

**Comment by broken1arrow** [comment]
> A little error when i use ProCosmetics (https://www.spigotmc.org/resources/procosmetics-300-cosmetics-treasurechests-eula-compliant-1-8-1-16-support.49106/)
> 
> Gadget => Merry go round
> 
> https://pastebin.com/jex9CTrc

If i read the error right is it a issue in cosmetics.

I look on this line, and seams they has probably not set up a event correctly. 

They has pretty odd set up of file path.

sv.file14.procosmetics.cosmetic.gadget.AbstractGadget.onEvent(Unknown source)

**Comment by montlikadani** [comment]
Also, it seems that 
```
com.gamingmesh.jobs.listeners.JobsPaymentListener.onArmorstandPlace(JobsPaymentListener.java:1363)
```
line refers to
https://github.com/Zrips/Jobs/blob/51a0b4bef7461e7cba2bb065b77dcbb9062d2224/src/main/java/com/gamingmesh/jobs/listeners/JobsPaymentListener.java#L1363
which does not contain any number-conversion process or any nan-double related things in code.

Looking again this code there is `armorStandPlace` method just calculates the distance of armor stands from players and thats all.
https://github.com/Zrips/Jobs/blob/51a0b4bef7461e7cba2bb065b77dcbb9062d2224/src/main/java/com/gamingmesh/jobs/listeners/JobsPaymentListener.java#L1318

I think that resource uses modified Jobs which breaks things.
Closing, as we can't do anything.
