### ISSUE TITLE
Join Jobs

### ISSUE THREAD

**Issue by Odsidz** [Zrips/Jobs#1128]
Hello,
Here is the bug: when I join a job, whatever means, on the graphical interface or even with the values ​​of the placeholders. They tell me that I am in all the Jobs. Problem I cannot join other jobs than 1.

Jobs Reborn version: **4.17.1**

Server Type: **Paper**

Server Version: **1.16.4**

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/issues/1115
