### ISSUE TITLE
Better Maven

### ISSUE THREAD

**Issue by SettingDust** [Zrips/Jobs#113]
Maybe you can find some online maven dependencies. Or I can help you change your pom. Why not?

**Comment by Zrips** [comment]
Why not

**Comment by SettingDust** [comment]
can u get into http://betonquest.betoncraft.pl/mvn/net/elseland/xikage/MythicMobs/mythicmobs/4.0.1/
I can, but my IDEA build mvn failed xDDD.

**Comment by SettingDust** [comment]
I have push correct pom to my fork. You can try to build it? I can't understand why Mb is failed XD.
