### ISSUE TITLE
Different Job-XP with Bungeecord

### ISSUE THREAD

**Issue by Schwabba** [Zrips/Jobs#1132]
Hi,

i recently discovered that when you use the plugin on a bungee server, it does not save the xp properly.

I think the problem is that when you join the Server, it loads the xp amount from the database and stores it in a local variable - on each bungee server. When i join the farmworld (different bungee server) and do my jobs, i'll farm the xp as i should. But as soon as i go back to the building server, i lose all the progress. But if i join back to the farm server, i'll get my progress back. When i join another bungee server, there i got a different xp amount as well. When i leave the server, the xp from the current bungee server will be stored in the database and when i rejoin, i'll get that xp amount back.

So the xp should be updatet when you switch between the bungee servers. Unfortunately that does not work.

Hope you read that and can help us.

Thanks.
![jobs](https://user-images.githubusercontent.com/44524851/112671951-28105e80-8e63-11eb-897f-86cd28ce82ba.png)

**Comment by Schwabba** [comment]
This server is running Paper version git-Paper-569 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Jobs Version latest dev from Discord

**Comment by montlikadani** [comment]
Development version from discord has been removed already. Please update to the new one. Second, make sure you have enabled `MultiServerCompatability` option in generalConfig.

**Comment by Schwabba** [comment]
It's newest dev now, MultiServerCompatability is enabled, but it still dont work. Same Problem as before.

**Comment by Schwabba** [comment]
bump

**Comment by Zrips** [comment]
87587d3852ffd4b69bde381214b2b657ca4f1662
