### ISSUE TITLE
All jobs automatically joined when one job is joined  (altough only being paid for the one job that has been joined)

### ISSUE THREAD

**Issue by nissiongot** [Zrips/Jobs#1137]
***Detailed description of the issue:**
When selecting a job, it automatically selects all jobs (in jobs browse menu all jobs show middle click to leave option). When  middle clicking one all jobs are left. When all jobs are automatically selected (keeping in mind auto join is off and so are the perms), only the job that was first selected is being paid for though. I also cannot join other jobs cause it says that all jobs are joined however wont get paid for them.

This is not happening when i first install 4.16 and then after configs are generated then replacing with 4.17 jar file
---

**Jobs version:** 
4.17.1
**Server Type (Spigot/Paper/etc):** 
PaperSpigot

**Server Version (using `/ver`):** 
16.4

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/issues/1135
