### ISSUE TITLE
Jobs join problem

### ISSUE THREAD

**Issue by Albin323** [Zrips/Jobs#1138]
Well, the title is both correct and incorrect in a way, yes you can join A job. But after that, it says that u have every other job. Surely you can leave them and join them again but that doesn't change the fact that it only says that you have the job you last joined... Like if I was a miner and joined a fisherman I'm a fisherman and not a miner anymore even tho I'm able to have at least 3 jobs.

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/issues/1137

**Comment by Albin323** [comment]
I can tell you, I tried and it didn't work in any way shape, or form... Something else must be wrong but I can't figure out what...

**Comment by Albin323** [comment]
> #1137

I can tell you, I tried and it didn't work in any way shape, or form... Something else must be wrong but I can't figure out what...
