### ISSUE TITLE
Jobs Browse / Join Client Window - Popup cuts off

### ISSUE THREAD

**Issue by lippoliv** [Zrips/Jobs#114]
![_2017-07-03 07_30_35-minecraft 1 11 2](https://user-images.githubusercontent.com/2561859/27779191-9df15cb4-5fc1-11e7-96b9-5977a802943f.png)

The description window is cut off by Mincraft Main window border. Any Option to set Position to "Bottom Center" instead of "Bottom Left"?

**Comment by Zrips** [comment]
Its places automatically where is can depending on size of that text window. All this is done by client, not from server side. I would suggest to minimize shown text by placing it into next line with \n or deleting whats not essential.

**Comment by lippoliv** [comment]
@Zrips thanks for the fast Reply. @Sprungente [mentioned](https://github.com/Zrips/Jobs/pull/107#issuecomment-312860241) that the `\n` would be printed as text, I will have a look on that and then maybe reopen a new issue for possibility to split text into two lines.

**Comment by Zrips** [comment]
I will have to retest, but usually this will split line
