### ISSUE TITLE
Jobs shop item order is messed 

### ISSUE THREAD

**Issue by Threshian** [Zrips/Jobs#1140]
***Detailed description of the issue:**

Since the last update the order of items in jobs shop are random. I didn't found any logic on the order with the config.

---

**Jobs version:** 
4.17.1
**Server Type (Spigot/Paper/etc):** 
Paper
**Server Version (using `/ver`):** 
paper-1.16.5-576

**Screen of the shop before and after the update**
https://i.imgur.com/5YedfSR.png
https://i.imgur.com/YfRP1nr.png

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/7e5ab9bb9c96cb73360305e6ee19d44879e89361
