### ISSUE TITLE
PlayerJointEvent

### ISSUE THREAD

**Issue by naikyy** [Zrips/Jobs#1146]
Hello, Im sorry for Issue category but there was not Question option. I came here with some possible lags from Jobs plugin. I have problems overwide with Zrips plugins and don't know why so I need to solve it step by step. With Jobs I have a problem that I can see some big loading in Timings. For example PlayerJoinEvent some kind of PaymentListener and other things. Could you take a look on it and tell me what to do to reduce these lags? Thanks.

Timings report: https://timings.pl3x.net/?id=a51ae281c4dd46bd8a40b289561f9ce7#plugins
Timings report v2: https://timings.pl3x.net/?id=4b21fadb03fd419bb0daad6355bbff3c#plugins

---

**Jobs version:** Jobs4.17.1

**Server Type (Spigot/Paper/etc):** Purpur, newest build

**Server Version (using `/ver`):** Purpur 1.16.5

**Comment by Zrips** [comment]
Do you have is this bungee type server or normal one? Those timings only indicate some slow down when player joins, which could be caused by slow data reads from your database in case you have multiserver compatibility enabled which forces to load player data.
