### ISSUE TITLE
Infinite jobs quest

### ISSUE THREAD

**Issue by Threshian** [Zrips/Jobs#1147]
***Detailed description of the issue:**

Players can do infinitely quests with the command /jobs quests next. They can do their quest, get the reward and do /jobs quests next to have another quest.

---

**Jobs version:** 
Jobs 4.17.2
**Server Type (Spigot/Paper/etc):** 
Paper
**Server Version (using `/ver`):** 
584

**Comment by RSLuke** [comment]
Same here

**Comment by Zrips** [comment]
1f98b5fb2b5ec14cf688048a125b718f2548ac73
