### ISSUE TITLE
Furnace events optimization 

### ISSUE THREAD

**Issue by andris155** [Zrips/Jobs#1148]
**Description of new idea or improvement on existing one**
Currently, the Furnace events uses the most resources in the Jobs plugin. I think it could be optimized.

**Detailed information what should do**
Optimize Furnace events.

![Screenshot 2021-04-12 143152](https://user-images.githubusercontent.com/8324198/114394751-d6264300-9b9b-11eb-8c5a-453f38da8364.jpg)

**Comment by montlikadani** [comment]
`0.02ms` is not a big one CPU usage time. The highest begins from 15.0+
