### ISSUE TITLE
enable-pay-near-spawner: false doesn't work with drowned zombies from a zombie spawner

### ISSUE THREAD

**Issue by Tiippex** [Zrips/Jobs#1150]
Hello,

I disabled the option "enable-pay-near-spawner" in the generalConfig.

I noticed that this works well for normal zombie spawners, but when the zombies transform into a drowned zombie Jobs doesn't detect this.

**Jobs version:** 
4.17.1

**Server Type (Spigot/Paper/etc) & Server Version (using `/ver`)** 
git-Paper-597 1.16.5

**Comment by montlikadani** [comment]
Expected behavior. When a zombie comes from a spawner and becomes drowned, the "mobspawner" metadata no longer exists, as it was not spawned from a mob spawner, but spawned/created manually.

**Comment by Tiippex** [comment]
Mhh is it possible to add an extra option or something similiar?

Right now players are able to bypass the hole enable-pay-near-spawner feature with drowned zombies from a spawner.

**Comment by IAmSoccer** [comment]
This also happens for Magma Cubes and Slimes when they split.

From what I've seen it is possible to fix this as a plugin I use removes AI from Spawner spawned Mobs and it continues to work after the slimes have split.
