### ISSUE TITLE
Error with limit of joinable jobs

### ISSUE THREAD

**Issue by Stryker46** [Zrips/Jobs#1156]
**Detailed description of the issue:**
With the correct permissions (jobs.use and jobs.max.3) and with a set limit of 3 jobs, if I join one job I can't join another telling me I'm already in that job.
Using /jobs stats, it turns out that I am only in the first job I joined.
---

**Jobs version:** 4.17.1

**Server Type (Spigot/Paper/etc):** Purpur Spigot 

**Server Version (using `/ver`):** 1.16.4

**Relevant plugins (Delete if this isn't needed):** Custom economy plugin with Vault integration

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/issues/1137
