### ISSUE TITLE
cant get the jobs to pay people in the Ultimate Economy plugin system 

### ISSUE THREAD

**Issue by titan120812** [Zrips/Jobs#1159]
***Detailed description of the issue:**
I can not get jobs reborn to pay people in Ultimate Economy system. I have tried turning sync economy false and it still does nothing with the money.
can someone help me?

**Jobs version:** 4.17.1

**Server Type (Spigot/Paper/etc): spigot latest 1.16.5

**Server Version (using `/ver`):** 

**Relevant plugins Ultimate Economy

**Comment by montlikadani** [comment]
Jobs only supports the popular and most used one and that is the Vault. I think UE have integration for Vault, so you need to check that out.

**Comment by titan120812** [comment]
ok thanks

**Comment by titan120812** [comment]
that worked. using vault fixed the problem.
