### ISSUE TITLE
Only getting paid for one job

### ISSUE THREAD

**Issue by JustinDevB** [Zrips/Jobs#1164]
Players are only getting paid for one job, when they are in 3 jobs. /jobs stats only shows 1 job even though they can join multiple jobs.

---

**Jobs version:** 4.17.1 

**Server Type (Spigot/Paper/etc):**  Purpur

**Server Version (using `/ver`):** This server is running Purpur version git-Purpur-1060 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 16 version(s) behind
Previous version: git-Purpur-1056 (MC: 1.16.5)

**Comment by montlikadani** [comment]
If you have discord and joined at our server, you can install the development release of Jobs.
