### ISSUE TITLE
New placeholder

### ISSUE THREAD

**Issue by D3BoxOfficiel** [Zrips/Jobs#1165]
Add a placeholder to retrieve the boot by business
%jobsr_user_boost_{jobsr_user_jobs}_money%

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/wiki/Placeholders#complexed-placeholders

**Comment by D3BoxOfficiel** [comment]
It is to recover the current profession of the player and not a specific profession

**Comment by montlikadani** [comment]
You can't display such a variable without giving the job name at least.
