### ISSUE TITLE
Clarify getJobName API method

### ISSUE THREAD

**Issue by PyvesB** [Zrips/Jobs#1166]
Hey there! :wave:

**Description of new idea or improvement on existing one**

The API methods provided for third-party plugins could benefit from some clarification, in particular `JobsLevelUpEvent.getJobName`.

What job name is it referring to?
* is it the job name specified as the top-level key of configuration entries (i.e. `exampleJob` in [_EXAMPLE.yml](https://github.com/Zrips/Jobs/blob/master/src/main/resources/jobs/_EXAMPLE.yml))?
* is it the full job name specified by the `fullname` parameter (i.e. `Woodcutter` in [_EXAMPLE.yml](https://github.com/Zrips/Jobs/blob/master/src/main/resources/jobs/_EXAMPLE.yml))?
* is it the short job name specified by the `shortname` parameter (i.e. `W` in [_EXAMPLE.yml](https://github.com/Zrips/Jobs/blob/master/src/main/resources/jobs/_EXAMPLE.yml))?

This has caused confusion in https://github.com/PyvesB/advanced-achievements/issues/1014 for example, where both @Teyir and myself assumed it was the first bullet point in the above list, but turns out it was the second one, `fullname` parameter.

**Detailed information what should be done**

From what I can tell, one of two simple things could be done in the Jobs API to avoid future confusion:
* change the Javadocs of `JobsLevelUpEvent.getJobName` so it explicitly states `the full job name` rather than vague `job name`.
* deprecate `JobsLevelUpEvent.getJobName` and add a new `JobsLevelUpEvent.getFullJobName` method as the new preferred means of getting the job name.

**Comment by montlikadani** [comment]
Instead, I added a new method that returns the actual `Job` instance to be accessible to methods with the above commit.
