### ISSUE TITLE
Add support for secure MySQL servers

### ISSUE THREAD

**Issue by runelynx** [Zrips/Jobs#117]
Hello Zrips,

First, thank you for being one of the most active plugin developers out there. Jobs is very regularly used on my server and everyone appreciates how involved you are with it!

In 3.9.8 the changelog says you've added useSSL as a tag for the config, which is super nice for us mysql 5.7+ users. 

However - I went the route of actually securing mysql, which means if I have that tag it needs to be true... but an additional tag needs to be false. 

?verifyServerCertificate=false&useSSL=true

Here are 2 examples of other plugins where the developer has done it (along with the changes they made which may expedite it for you). 

https://github.com/Gamealition/GPrism/issues/13
https://github.com/BanManagement/BanManager/issues/738

Thanks :) 
Rune of Runic Paradise

**Comment by Zrips** [comment]
Good point, will add option to define things like this
