### ISSUE TITLE
List All Commands On Wiki PLEASE!

### ISSUE THREAD

**Issue by Dracathio** [Zrips/Jobs#1172]
List Commands On Wiki

Well Lets see here.

CMI's commands are listed on the website/wiki
Selection Visualizer has it's commands listed on the website/wiki
Residence has it's commands listed on the website/wiki
Even Bottled EXP has it's commands listed on it's spigot page.

So for all Server Admins and Server Owners who use the jobs plugin, it would be quite nice to have the commands listed so we're able to do our work for more easily.

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/wiki/Commands
