### ISSUE TITLE
Anvil as a method of payment in enchantments

### ISSUE THREAD

**Issue by Okhami** [Zrips/Jobs#1174]
Currently you can earn money using the enchantment table, but at the same time, enchantments can be added on the anvil by joining items and books.

The main idea is to allow that when you write in the code that you can earn money by enchanting an item or by obtaining a specific enchantment, you can get money in both ways.

Here is an example of what I am explaining:

Enchant:
   Iron_axe:
      income: 10.0
      experience: 10.0
   DIG_SPEED-2:
      income: 10.0
      experience: 10.0

With this code, the user should get money by enchanting the table and adding enchantments to it from the anvil.

The same would also happen with enchantments, you can choose to add a book manually on the anvil or get lucky and get it on the enchantment table, as currently happens.

Thank you in advance!

**Comment by montlikadani** [comment]
There is an option in generalConfig called `PayForEnchantingOnAnvil`

**Comment by Okhami** [comment]
Oh, I didn´t see it sorry.
