### ISSUE TITLE
Stone blocks in gui

### ISSUE THREAD

**Issue by typecek123** [Zrips/Jobs#1178]
***Detailed description of the issue:**
So when I open /jobs join or /jobs browse, half of these jobs have stone blocks in that gui, even through I'm sure, that I have set it up correctly.

**Jobs version:** 
4.17.2 (dev version)
**Server Type (Spigot/Paper/etc):** 
Paper 1.16.5
**Server Version (using `/ver`):** 
Paper version git-Paper-585 (MC 1.16.5-R0.1-SNAPSHOT) 
![obrazek](https://user-images.githubusercontent.com/74290177/117586571-3f589200-b119-11eb-8e75-d8c6311a7e57.png)

**Comment by typecek123** [comment]
But when I renamed in config ID: to Item: it works! Btw miner is not giving xps

**Comment by Br0H0gg** [comment]
Can repro.

**Comment by montlikadani** [comment]
Use the full material name instead of IDs.
