### ISSUE TITLE
Jobs Not working 

### ISSUE THREAD

**Issue by masterhacka** [Zrips/Jobs#1179]
Please help: https://pastebin.com/adzsh3j5

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/issues/1115

**Comment by masterhacka** [comment]
This is not a duplicate of 1115. I am using MySql. Before I used sqlite an everything worked fine. Now I am using MySql over bungeecord and have this issue

**Comment by montlikadani** [comment]
Doesn't matter, the link in the linked issue contains the fixed mysql data truncation.

**Comment by masterhacka** [comment]
Okay and how am I going to use this?

**Comment by montlikadani** [comment]
https://github.com/mrfdev/Jobs/blob/main/Resources/FAQ/Jobs-jar-files.md#the-different-jobs-jar-files

**Comment by masterhacka** [comment]
Okay thanks! Should I use Discord or Github version? Which one is mostly stable

**Comment by montlikadani** [comment]
both
