### ISSUE TITLE
User storage

### ISSUE THREAD

**Issue by didjee2** [Zrips/Jobs#118]
Please god remove the part that loads all existing users into a hashmap.
It's just asking for a memory leak ...

Our server has over 40000 stored users which were loaded into that stupid hashmap, which made our server lagg out & crash all the time.

https://github.com/Zrips/Jobs/blob/master/src/main/java/com/gamingmesh/jobs/Jobs.java#L518-L555

**Comment by Zrips** [comment]
Duno, but 5k users takes more or less unnoticeable amount of memory on test server, as database it self is like 1MB in size. Don't have 40000 legit users to test out.
Will do some changes for player data preload, but in general, we have to have it to prevent lag spikes on player login event. 
If you have a better idea, I'm always open for ideas.
And I would suggest to clean up your database from old user data.

**Comment by didjee2** [comment]
Several ideas are possible, if you add an index into your database it will speed it up already, I don't think that you do that right now.
Maybe add an option into the plugin that automatically cleans up the old user data, would be amazing.
Or another option that you can choose wether the plugin should load the data on join (& remove on quit) or load on startup.
(Small servers: startup load, bigger servers: join load (quit unload)).

**Comment by Zrips** [comment]
Issue is that we need to load data from several tables. And as there are already plugins performing a bunch of actions on player login event, additional ones don't help.
There is an option to clean data base by jobs level or by how long player was offline.
Send me your database for testing. If it actually fails to work with your data base, then I will change mechanics for that. Other wise there is an issue somewhere else.
