### ISSUE TITLE
Jobs info text is used twice

### ISSUE THREAD

**Issue by thedarkcookieez** [Zrips/Jobs#1187]
**Description of new idea or improvement on existing one**

**Detailed information what should do**
http://prntscr.com/134lz4f
Can you insert an extra line so that you can insert 2 different texts?
On the picture you can see that / jobs info [jobname] [action] in the command list and when executing the command share the texts

**Comment by montlikadani** [comment]
No

**Comment by thedarkcookieez** [comment]
nice ty
