### ISSUE TITLE
Chickens that hatch from thrown eggs pay in the Farmer job as if you had bred 2 chickens

### ISSUE THREAD

**Issue by WhatsTheBadNews** [Zrips/Jobs#1188]
***Detailed description of the issue:**

Chickens that hatch from thrown eggs pay in the Farmer job as if you had bred 2 chickens.

There's an issue to this though. If one throws eggs at someone, the person who gets hit with the hatching egg is paid for breeding the chickens. This opens the door to another issue. It is possible to create a fully automatic income farm using dispensers by having chickens lay eggs on top of hoppers and those hoppers direct the eggs to the dispensers, then the eggs get thrown at the player and they get paid as if they were breeding 2 chickens

---

**Jobs version:** 4.17.2

**Server Type (Spigot/Paper/etc):** Tuinity 231

**Server Version (using `/ver`):** MC 1.16.5

**Comment by Zrips** [comment]
Unless you have different plugin which fires second event for chicken spawn event, other than this it cant be double payments as its only paying for each event which is fired for each spawned entity.

**Comment by trevor1097** [comment]
Still happens in Jobs 5.0.1.0 on Paper 1.18.1(build 121). Is it possible to not pay for chickens that spawn from eggs?
