### ISSUE TITLE
Jobs in Tabcomplete are shown in english since last version 4.17.2

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/Jobs#1189]
![Snag_204e4c4](https://user-images.githubusercontent.com/12080017/119234323-a587e080-bb2d-11eb-933a-8c9c06450cd5.png)

Before they where german
i took a look in the obs folder

file.brewer.yml
```
Brewer:
  fullname: Brauer
  shortname: Br
```

is this an issue or do we have to rename all jobs inside the jobfiles now?

**Comment by CloudeLecaw** [comment]
i looks like 1.17.2 works with the filenames
i created a file in jobs folder called brauer.yml end enters Brewer: in it.
Tab Complet suggested now Brauer

So this means i have to rename all the jobs ymls to the german wanted name right?

**Comment by montlikadani** [comment]
<https://github.com/Zrips/Jobs/commit/5f5e1f71133816d917bee9a4a1b822b6165b13ef>

After the new release of Jobs you will be able to use a job's full name to display in anywhere in the command completions. You need `[jobfullname]` variable to be specified in your preferred language in `args` string.

> The question is does this effect current database of jobs?

Yes, unless you change the saved jobs one by one in database including for players.

**Comment by CloudeLecaw** [comment]
Well i have a question i didnt understoof where we can define `[jobfullname] ` so it will be shown in the comands.

could you give me an example?

**Comment by montlikadani** [comment]
Like in `join` command
```yml
  join:
    help:
      info: Join the selected job.
      args: '[jobfullname]'
```

**Comment by CloudeLecaw** [comment]
So we need to wait now for the next Dev release right? :D

**Comment by montlikadani** [comment]
You can build and compile Jobs at any time, [docs here](https://github.com/mrfdev/Jobs/blob/main/Resources/FAQ/Jobs-jar-files.md#the-different-jobs-jar-files)
