### ISSUE TITLE
Particle/Sounds When Configured

### ISSUE THREAD

**Issue by Isaiah-labs** [Zrips/Jobs#1190]
**Description of new idea or improvement on existing one**
I think it would be really cool to add small particle effects or sounds when getting paid

**Detailed information what should do**
Let's say a Miner breaks a coal ore block (and configured to do so) breaking that block would spawn the configured particles or play the configured sounds. I was originally thinking of configuring little dropped items that you'd have to pick up (imagine 30 emeralds dropping for $30, but you can change the item to anything, and change the ratio for cash:items dropped for those inflated economies)

    COAL_ORE:
      income: 1.05
      experience: 1.08
      particle: spell_witch;30    (particle/item;amount)
      sound: block_note_block_pling;0.5;2  (sound;volume;pitch)

**Comment by montlikadani** [comment]
There are plenty of plugins that do this, the Jobs plugin is not for playing particles or sounds, but for executing jobs.

**Comment by Isaiah-labs** [comment]
I know there are plugins that add particles or play sounds, but is there a way to tie them together? If there isn't I feel like this is something that should be added. To my knowledge, you can't have a command run when a player gets paid, only when a player levels up (which would be the only time you'd be able to have particles/sounds shown or played)
