### ISSUE TITLE
Bonus on armor / tools

### ISSUE THREAD

**Issue by JessyDrew** [Zrips/Jobs#1198]
**Description of new idea or improvement on existing one**
I want to do an action on my server. That is, if the person wears the helmet / breastplate or whatever, it gives them a% bonus in points and boost money received in the profession.

**Detailed information what should do**
Can be created a.yml file in the jobs to make items with the boost. Example:
Helmet: money 20% xp 20%.
And in game make the order / jobs giveitem helmet

**Comment by montlikadani** [comment]
There is already armor/item boost, find `boostedItems` file in Jobs directory.
