### ISSUE TITLE
You have to wait 1 second until you can get paid spam when working a job.

### ISSUE THREAD

**Issue by mibby** [Zrips/Jobs#120]
Jobs 4.0, mysql database.

@Zrips The jobs plugin is spamming people with "you have to wait 1 second until you can get paid" when people work a job, but it also pays them apparently. Perhaps it has something to do with having the GlobalBlockTimer enabled?

```
    GlobalBlockTimer:
      use: true
      timer: 10
```

**Comment by Zrips** [comment]
Block protection is being triggered when this happens. You need to check what actually they are doing when this message appears and tweak appropriate file for that.
