### ISSUE TITLE
Rounded exp placeholders

### ISSUE THREAD

**Issue by Miwasak** [Zrips/Jobs#1200]
Hi,

It would be nice if you could add rounded placeholders for jobs experience

Example: If i have 5.120,541 exp, it show "5120" (or 5.120)

It could be great for deluxemenu and scoreboard for showing current xp without taking large place

Thanks

**Comment by montlikadani** [comment]
`%jobsr_user_points%` placeholder already do this.

**Comment by Miwasak** [comment]
> for jobs experience

I'm not looking for points placeholder
