### ISSUE TITLE
DIsable payments by vanilla pets like wolf

### ISSUE THREAD

**Issue by ehetteNandaYo** [Zrips/Jobs#1205]
**Description of new idea or improvement on existing one**

Some people on my network are just spawning 50 wolfs and they just farm with them afk while the wolves kills everything that tries to kill them

**Detailed information what should do**
Not pay if a wolf kills the mobs or maybe nerf it a little bit somehow... different % pay if killed by wolf

**Comment by WhatsTheBadNews** [comment]
I believe this can be done via permissions.

You can negate the `jobs.petpay` to give no pay for pet kills.

Or if you just want to give a percentage, you can give the permission `jobs.petpay.[number]`

**Comment by ehetteNandaYo** [comment]
> I believe this can be done via permissions.
> 
> You can negate the `jobs.petpay` permission to give no pay for pet kills.
> 
> Or if you just want to give a percentage, you can give the permission `jobs.petpay.[number]`

No thats for mypet plugin, I'm talking about vanilla pets like wolf you can tame with bones

**Comment by WhatsTheBadNews** [comment]
Are you sure? Where did you read that that permission is for the mypet plugin? I can't find that anywhere. I negate the permission I mentioned on my server to block pet pay and it seems to do the job for me (and I don't have the mypet plugin). ¯\_(ツ)_/¯

**Comment by montlikadani** [comment]
Both are supported (vanilla and mypet one) as how @WhatsTheBadNews said, just not documented.

**Comment by pacificminer** [comment]
> Both are supported (vanilla and mypet one) as how @WhatsTheBadNews said, just not documented.

It doesn't work for vanilla pets though.

**Comment by montlikadani** [comment]
> It doesn't work for vanilla pets though.

You probably don't uses any of permission plugin or you did not denied the `jobs.petpay` permission.
