### ISSUE TITLE
Command Autocomplete issue

### ISSUE THREAD

**Issue by Seeroh** [Zrips/Jobs#1208]
***Detailed description of the issue:**

When typing in Jobs commands, instead of narrowing down which command you are looking for as you type, it just shows all the commands available. 

This is how it used to be a few versions ago:
![image](https://user-images.githubusercontent.com/9147655/121507142-37e70b80-c999-11eb-83c4-099c708fe1c1.png)

This is what it is like now:
![image](https://user-images.githubusercontent.com/9147655/121507218-49c8ae80-c999-11eb-9e9e-4c8a8e0c44f0.png)

Before it properly removed commands that didn't match the typed characters from the suggested autocomplete, and now it just moves the suggested commands to the top of the list

---

**Jobs version:** 4.17.2

**Server Type (Spigot/Paper/etc):** Paper

**Server Version (using `/ver`):** Paper-288 (MC: 1.16.4)

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/efd1c91386826073d155fc3ea8beeaf51c8bad42
