### ISSUE TITLE
How to make a profit with REDSTONE ORE

### ISSUE THREAD

**Issue by kacpiklPL** [Zrips/Jobs#1211]
Hi, I have a problem with the Jobs Reborn plugin, in the yml file where there is a specific job, I enter a block that after destruction is supposed to be earnings for the work, more precisely, I mean redstone ore I looked at the list of available blocks, from what I found I used each possible format for this block (REDSTONE_ORE, LEGACY_GLOWING_REDSTONE_ORE, LEGACY_GLOWING_REDSTON_ORE), however, after digging this block, you do not receive earnings for work, how else do I have to enter this block to get paid for it?

Jobs 4.17.2
PaperMC 1.12

**Comment by montlikadani** [comment]
It should only be `glowing_redstone_ore` in 1.13 and lowest versions.

**Comment by kacpiklPL** [comment]
not work

**Comment by kacpiklPL** [comment]
flower pot, all banner and end crystal olso not work

**Comment by montlikadani** [comment]
Show us your job including the action where are you trying to use these materials.
