### ISSUE TITLE
Commands or Permissions sections in jobs.yml doesn't work

### ISSUE THREAD

**Issue by Replaycchi** [Zrips/Jobs#1212]
***Detailed description of the issue:**

The "commands" or "permissions" section of jobs.yml seems to not work anymore 

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
  permissions:
    # example node
    # Any name can be accepted
    firstNode:
      # true to give, false to revoke
      value: true
      # The permission node
      permission: aaaaaatest.node
      # minimum level needed to grant permission. Use 0 for all levels

---

**Jobs version: 4.17.2** 

**Server Type (Spigot/Paper/etc): Purpur** 

**Server Version (using `/ver`): This server is running Purpur version git-Purpur-1060 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)**

**Comment by montlikadani** [comment]
You don't have any permission plugin installed, and you didn't leveled up in that particular job.
