### ISSUE TITLE
EXP dupe bug due to incompatibility with Lands plugin

### ISSUE THREAD

**Issue by Weark** [Zrips/Jobs#1215]
You can get infinitely EXP and Money, just go on the claimed land of another person who has a plantation or ores that were not placed by the player and keep breaking it infinitely and you receive EXP and Money from work and the block remains there because it doesn't I have permission on other people's land.

It could add compatibility with Lands in the same way that it already has compatibility with WorldGuard.

Plugin: https://www.spigotmc.org/resources/lands-land-claim-plugin-grief-prevention-protection-gui-management-nations-wars-1-17-support.53313/

See the problem in this screenshot: https://i.imgur.com/F6tEhZz.png

**Jobs version:** 4.17.3

**Server Type (Spigot/Paper/etc):** Purpur

**Server Version (using `/ver`):** 1.16.5

**Comment by montlikadani** [comment]
There was a similar issue with BlockBreakEvent recently and it has been fixed. But now it seems that one plugin is canceling the event and the other plugin is not, so Jobs is currently invoking this event even if it has been canceled with a plugin. #1194, [commit](https://github.com/Zrips/Jobs/commit/8d65bb7b7e6216a7d8ca9866ce0948cb2eac38a7#diff-e240a650c412b0fba5826fea7036c4039394ce57e6a57f16080279a6e26e2e31)

So what to do now? Suppose we add each existing plugin as compatibility (as a dependency) to prevent the event call (about 200) and it might work? It wouldn’t make sense and it would be disgusting.

**Comment by Zrips** [comment]
Should be resolved with latest version.
