### ISSUE TITLE
No Creative XP/Money/JXP

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/Jobs#1225]
When your in Creative since latest CMILIB Update you dont get XP,MONEand ob-XP for most Jobs 
I am Fisher for example and need to switch to gm0 to get xp
XP from furnace i got in gm1 too... but not the fished one..
i aspect this also effect the other jobs too.

the permission jobs.paycreative is alltready hardset

**Jobs version:** 
5.0.0.1 with CMILib 1.0.2.7
**Server Type (Spigot/Paper/etc):** 
PaperMC 1.17 Build 75

Effect appeared since CMILib updated to 1.0.2.7...

**Comment by Zrips** [comment]
281542d7458604e02163a1f83a375296fcfe6a7c

**Comment by CloudeLecaw** [comment]
Does it mean it will be fixed with job 5.0.0.2? :)

**Comment by Zrips** [comment]
It does mean that.
