### ISSUE TITLE
RewardCommands not executing a tellraw command

### ISSUE THREAD

**Issue by Pirito10** [Zrips/Jobs#1226]
**Detailed description of the issue:** the `RewardCommands` section from the `Quests` section on the job config is not executing a tellraw command.

---

### **Example:**
```
RewardCommands:
      - eco give [playerName] 500
      - tellraw [playerName] \"test\"
```

The eco command is executed correctly, but not the tellraw (altough nothing is displayed on the console).
I have to add the backlash or else the plugin doesn't read correctly the job file. I'm not sure if that is causing the command to not be executed correctly.
In case that was the issue, it should display an error on the console. Can be easily seen executing the command `/tellraw [playerName] \"test\"`. But it doesn't.

---

**Jobs version:** 5.0.0.2

**CMILib:** 1.0.2.10

**Server Type:** Purpur

**Server Version:** 1.17 build 1255

**Comment by Zrips** [comment]
Its not a correct tellraw command format. Correct one would look something like
`      - 'tellraw [playerName] {"text":"test","color":"yellow"}'`
