### ISSUE TITLE
Some furnaces do not register properly

### ISSUE THREAD

**Issue by Momshroom** [Zrips/Jobs#1228]
***Detailed description of the issue:**
Some furnaces will show they are registering when interacting with them, but do not add to the registered count and will show registering every time they are interacted with.   Ie, I interact with the furnace, it says "Registered new ownership for furnace: 1/20". I then click on it again and get the exact same 1/20 message.   If I do /jobs clearownership it tells me I had 0 furnaces registered.  Other furnaces do work properly and I'm unable to tell which will cause an issue and which will work fine, but the behavior is consistent across a restart.  Other players have the exact same issue when interacting with the glitched furnaces, so it's a furnace issue, not a player one. There  is no message on console related to this.

---

**Jobs version:** 
5.0.0.1
**Server Type (Spigot/Paper/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper 762 (1.16.5)

**Comment by Momshroom** [comment]
Not sure if it's relevant, but we do have both mcmmo (2.1.200) and LWC interacting with furnaces, though all the furnaces in question (both working and non-working) were locked, so I don't think that's likely the issue.

**Comment by Zrips** [comment]
4f87750bfab14c9dea9bb79a81d1e5e2b7111bfc
