### ISSUE TITLE
Player may get unlimited money

### ISSUE THREAD

**Issue by Xuan1418** [Zrips/Jobs#1229]
***Detailed description of the issue:**
I found a bug which can get unlimited money ....
My player select `Miner` job and I set it like 
```  Break:
    diamond_ore:
      income: 50```
      
This situation player will get $50 for each diamond ore mined. 
But I found out player able to get unlimited income from that with the method : 
1) Get a *silk touch* pickaxe and keep mining and place it

If I add another rules which is 
```  Place:
    diamond_ore:
      income: -50.0```
They will ask their friend to place it.... so is there any ways that can detect the player mine the *diamone_ore* that generate naturally?
---



**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```Miner:
  fullname: Miner
  shortname: M
  FullDescription:
  - "Earns money mining minerals and ores."
  ChatColour: DARK_GRAY
  chat-display: full
  leveling-progression-equation: 10*(joblevel)+(joblevel*joblevel*4)
  income-progression-equation: baseincome-(baseincome*0.1)
  points-progression-equation: basepoints+(basepoints*(joblevel-1)*0.01)-((basepoints+(basepoints*(joblevel-1)*0.01))
    * ((numjobs-1)*0.05))
  experience-progression-equation: baseexperience-(baseexperience*((numjobs-1) *0.01))
  rejoinCooldown: 10
  maxDailyQuests: 1
  Gui:
    Item: wooden_pickaxe
    slot: 11
  Break:
    coal_ore:
      income: 5.0
    lapis_ore:
      income: 15.0
    redstone_ore:
      income: 15.0
    diamond_ore:
      income: 50.0
    emerald_ore:
      income: 80.0
    nether_quartz_ore:
      income: 15.0
  Smelt:
    iron_ingot:
      income: 20.0
    gold_ingot:
      income: 30.0
    netherite_scrap:
      income: 100.0
  Place:
    coal_ore:
      income: -5.0
    lapis_ore:
      income: -15.0
    redstone_ore:
      income: -15.0
    diamond_ore:
      income: -50.0
    emerald_ore:
      income: -80.0
    nether_quartz_ore:
      income: -15.0
```

---

**Jobs version:** 
Jobs5.0.0.2.jar
**Server Type (Spigot/Paper/etc):** 
Paper 
**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-706 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 76 version(s) behind
Previous version: git-Paper-704 (MC: 1.16.5)
**Relevant plugins (Delete if this isn't needed):**

**Comment by Momshroom** [comment]
You can set a time for which they cannot be paid if they remine a placed block to prevent this somewhat, or you can create a job that everyone has that charges for placing blocks like this that pay well.

**Comment by Xuan1418** [comment]
“set a time for which they cannot be paid if they remine a placed block” 
How do I set a time ?Is there any example for that?

**Comment by Zrips** [comment]
@Xuan1418 
You have restrictedBlocks file where you can define how long we should wait before we will pay for placed block. This is a fix/workaround to issue with players placing and braking same block over and over again. You do need to enable PlaceAndBreakProtection in generalConfig file, which should be enabled by default but you might still need to add 
`  DIAMOND_ORE: -1` into restrictedBlocks files blocksTimer list
