### ISSUE TITLE
lag spike while crafting for first time after server restart

### ISSUE THREAD

**Issue by Rivils** [Zrips/Jobs#1231]
commit 509ac682adef8ec64fde0912722bd688e430a9ff

still didn't fix the issue
```
[22:17:45 ERROR]: (org.bukkit.craftbukkit.v1_17_R1.legacy.CraftLegacy:259) Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[22:17:48 INFO]: [⚡] Tick #3915 lasted 3225.96 ms. (6351.87% increase from avg)
```
Jobs Version: 5.0.0.3

Server Type:Purpur-1267

Server Version: 1.17.1

**Comment by Zrips** [comment]
Can you specify which item in specific you tried to craft and which what action?

**Comment by Rivils** [comment]
it happens each time only once after server restart. opening inventory and shift crafting multiple oak logs for example cause the lag spike to occur and you get that message in console.

**Comment by Zrips** [comment]
Tested multiple things, cant really trigger this one to happen anymore. Are you sure your are on 5.0.0.3 version? Just double check it as i cant think a reason why it would trigger for you while its just fine for me and by the code it should no longer get triggered. 
And just FYI it could be triggered by different plugin in general, so you might want to test it with Jobs plugin only just to make sure its Jobs which causes this and not another plugin as this is not limited to one plugin, any older plugin which uses older API can trigger this to happen.

**Comment by Rivils** [comment]
i am on 5.0.0.3 version, tested without Jobs plugin, it doesn't happen, it is caused by jobs plugin.

**Comment by Zrips** [comment]
At this point i cant reproduce this issue and debug it properly to know what would cause it to trigger this for you specifically. And you still need to test it with Jobs plugin only. Removing Jobs to check if issue is gone is only half of test as this can be compatibility issue. If you could perform one more test with Jobs only that would narrow down possible causes.

**Comment by Rivils** [comment]
deleted the jobs folder and generated a new one, seems like that was the issue. still don't know how that would be the cause.

**Comment by Zrips** [comment]
Do you still have copy of those files for testing? Some specific setup might have caused this, would be interesting to know which in particular.

**Comment by Rivils** [comment]
Yes. Here: https://www.mediafire.com/folder/3zxc7rhnelkel/Jobs
