### ISSUE TITLE
Jobs failing to startup

### ISSUE THREAD

**Issue by LoJoSho** [Zrips/Jobs#1235]
***Detailed description of the issue:**

Jobs is disabling itself on startup.

---

**ERROR:**
```
https://paste.gg/p/anonymous/9bbb59aa14b04456b66e768c3c52a811
```

---

**Jobs version:** 5.0.0.5

**Server Type (Spigot/Paper/etc):**  PurPur 1.17.1

**Server Version (using `/ver`):** git-Purpur-1260 (MC: 1.17.1)

**Comment by Zrips** [comment]
Update CMILib to latest version
