### ISSUE TITLE
Latest version get heavy tasks

### ISSUE THREAD

**Issue by WarnDa** [Zrips/Jobs#1237]
***Detailed description of the issue:**
When I use jobs, a task to "get the lore" of the item I'm using is heavy (I think it's related to 'boosters items')

**Jobs version:** 
5.0.0.5

**Server Type (Spigot/Paper/etc):** 
Airplane 1.16.5

**Server Version (using `/ver`):** 
'Airplane-Purpur version git-Airplane-4 (MC 1.16.5)
**Relevant plugins (Delete if this isn't needed):**

Heavy Task : 
https://cdn.discordapp.com/attachments/526402919826849804/865630848160890890/Screenshot_5099.png

Spark : 
https://spark.lucko.me/sHSPqzLQ37

**Comment by WarnDangerous** [comment]
edit : 
I know my server isn't "lagging", or plugin isn't taking 50% of server ticks, but with only 1 player, this tasks is quiet heavy, also I DON'T use "boosters items" and I don't have any boster items setup.

**Comment by WarnDangerous** [comment]
Edit :

I updated my paiement to 30s, so paiement are fine, but the interact event takes 80% of plugin's usage :/
https://prnt.sc/1g6o424

It's soo heavy, I don't use this event (I don't get custom items/boosters items), so I really want to disable thoses checks

**Comment by WarnDangerous** [comment]
Jobs get really a lot of performances issues :/

for example on this spark : 
https://spark.lucko.me/h8or2uqOfD

1.17% for jobs, just when 1 single player was mining, 0.21% for the bossbar things, seems a lot high.
Questcreator is using the same bossbar system (and it was refreshing as often as jobs) but it's less than 0.1% for the whole plugin on this spark.

and onLimitedItemInteract is still 0.56% :/

**Comment by Zrips** [comment]
Sorry for long delay. Made few changes relating to handling of limited items which was made made in efficient way, new way should introduce up to 100x better performance
c18916bd567b162d290cf2b3922871492ef41b6f
