### ISSUE TITLE
Jobs not working in overworld

### ISSUE THREAD

**Issue by DarrienNN** [Zrips/Jobs#1240]
***Detailed description of the issue: My Traveller(Explorer) jobs not working in overworld after server restart, i already tried to use back default config/name but still same not working in overworld and i already give [ jobs.use / jobs.world.world but still same and i already set jobs.world.flatroom deny but still working in that world**

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
##JOBS TRAVELLER CONFIG
https://pastebin.com/q8FNKYvG 
restrictedAreas CONFIG 
https://pastebin.com/xBWAiDKP##
#####################################
```

---

**Jobs version: 5.0.0.6 | CMILib version: 1.0.3.0** 

**Server Type (Spigot/Paper/etc): Tuinity 1.17.1 (Also tried to use spigot and papermc but still same not working** 

**Server Version (using `/ver`): This server is running Tuinity version git-Tuinity-23 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)**

**Comment by Zrips** [comment]
If something doesn't work in one world, but works in another, then its been effected by ether your config file or by permission nodes player has access too. Make sure that player doesn't have access to specific permission by actually checking its access to them, as permission inheritance can mess things up. Most likely it will be issue with permissions if resetting config files to default ones dint resolved it. 
As of testing all seams to be working correctly.
