### ISSUE TITLE
LOST/DUPE ITEMS when interacting with registered blocks

### ISSUE THREAD

**Issue by ghost** [Zrips/Jobs#1242]
***Detailed description of the issue:**

Upon placing a any block that requires registering, shift-click an item into the gui will disappear, and be lost. We have tested it out and made sure that this was the plugin cause the issue. Once you have registered it, and interacted it with it at least once, then you can shift-click the items in. But the first time you do it, you will lose the items you shift-click. I have attached a gif below showing.

https://gyazo.com/7ac612c8dfe9dfe1d10e47a2e52f3dae.gif

**Jobs version:** 5.0.0.6

**Server Type (Spigot/Paper/etc):** Purpur 1292

**Server Version (using `/ver`):** 1.17.1
incase you didnt want to click on the link.
![gif](https://user-images.githubusercontent.com/46063612/126878680-06659c04-40a3-45ee-90e4-feb0f719a569.gif)

**Comment by therbz** [comment]
You can also duplicate items if you register ownership of a furnace with items already inside and shift-click them out,

Tested on Paper b125 MC 1.17.1, Jobs 5.0.0.6

**Comment by thefullnacho** [comment]
I am having a similar issue where if you are at the maximum allowed furnaces the first time you interact with the furnace and place items without shift clicking they just disappear. It doesn't seem to happen when you are interacting with a registered furnace just if it's outside of your registered amount. Playing on 1.17.1, Jobs 5.0.0.5, CMLib 1.0.3.2, and Airplane git-airplane-56

**Comment by Zrips** [comment]
Blockownership handling went over dew changes which should resolve your issue
