### ISSUE TITLE
gtop shows 0 exp for all players after the lvl

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/Jobs#1245]
![Snag_7f1fa7c](https://user-images.githubusercontent.com/12080017/127564772-cc511488-c6f1-4feb-b418-140fac7bfc77.png)

Well i thought there should be listed the JobXp the player has.. so if he has lvl 20 and 500 exp
he currently shows the same as someone with lvl 20 and  830 xp

```
  gtop:
    help:
      info: 'Zeigt die %amount% höchsten Level an.'
      args: ''
    error:
      nojob: 'Es sind keine Informationen abrufbar.'
    output:
      topline: '&aTop&e %amount% &aSpieler nach globalen Joblevel'
      list: '&e%number%&a. &e%playername% &aLevel &e%level% &amit&e %exp% &aeXP'
      prev: '&e<<<<< Vorherige Seite &2|'
      next: '&2|&e Nächste Seite >>>>'
      show: '&2Toplist von &e[from] &2bis &e[until] &2anzeigen'

```

Jobs_5.0.0.6
![Snag_7f57c7f](https://user-images.githubusercontent.com/12080017/127565253-2b2d6b67-7bad-495e-bdc4-4b52c5e0eb0a.png)

**Comment by Zrips** [comment]
b35bdd5087f13d65a2dfc9fa787e41511f370c51
