### ISSUE TITLE
Issues with the explorer job

### ISSUE THREAD

**Issue by Momshroom** [Zrips/Jobs#1246]
***Detailed description of the issue:**
The explorer job stops giving money xp after a little when traveling in the same direction, even in previously unexplored chunks and fresh worlds.  As best as we have been able to tell, it gives xp for 21 chunks travelled in a cardinal direction, then stops, but if you move one chunk in another direction and then continue in the other direction, it will give xp for 21 chunks again.  This works until you've gone about 21 chunks in the perpendicular direction, after which you no longer get xp at all, or only very sporadically.

Pattern:
```>>>>>>>>>>>>>>>>>>>>>x
                     >>>>>>>>>>>>>>>>>>>>>x
                                          >>>>>>>>>>>>>>>>>>>>>x
                                                               >>>>>>>>>>>>>>>>>>>>>x
                                                                                    >>>>>>>>>>>>>>>>>>>>>x```
Where > is the direction of travel and gives xp/money and x is a new chunk that doesn't give xp or money.

                       `
                                                   `
---


**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  Explore:
    '1':
      income: 1
      experience: 14
    '2':
      income: 0.75
      experience: 9
    '3':
      income: 0.6
      experience: 6

```

---

**Jobs version:** 
Jobs version 5.0.0.6

**Server Type (Spigot/Paper/etc):** 
 Paper 
 
**Server Version (using `/ver`):** 
 Paper version git-Paper-137 (MC: 1.17.1)

**Comment by Zrips** [comment]
7822f9a194eb2c5b2ce706bf0d464dfb4d4aa4ca
