### ISSUE TITLE
Can't add wither skeleton to jobs reborn

### ISSUE THREAD

**Issue by LuluxClient** [Zrips/Jobs#1248]
***Detailed description of the issue:**
I cannot add a wither skeleton to the hunter job. 
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
<-- Try to use pastebin.com server if you have long error. -->
```
####################
## PASTE ERROR HERE ##
####################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Jobs version:** 
5.0.0.6
**Server Type (Spigot/Paper/etc):** 
PaperSpigot
**Server Version (using `/ver`):** 
1.8.8

**Comment by Zrips** [comment]
Use skeletonwither which would be more appropriate name for older servers. Will add more recognitions for older mob types with next update.
