### ISSUE TITLE
message blocktimer sometimes appear without proper job

### ISSUE THREAD

**Issue by EvilOlaf** [Zrips/Jobs#125]
Hey there,

we recently discovered that from time to time users without having farmer job get the messages blocktimer and/or placeblocktimer. I could reproduce this once by placing/breaking sugar cane while being fisherman.

Also happens when placing torches while being terraformer and miner.

Using Jobs 3.9.8
Spigot 1.8.8

**Comment by Zrips** [comment]
Block timer is being triggered before checking for payments to lower loads. Will move this after possible payment is being checked, to avoid unneeded messages.
