### ISSUE TITLE
Milk a goat

### ISSUE THREAD

**Issue by Gorderok** [Zrips/Jobs#1253]
Milking a goat does not work

  Milk:
    Cow:
      income: 0.18
      experience: 0.15
    Goat:
      income: 0.18
      experience: 0.15

**Jobs version: 5.0.0.6

**Server Type (Spigot/Paper/etc): PaperSpigot 1.17.1 #166

**Comment by LogGits** [comment]
Oddly enough i have this configuration and it's showing as "Glowing Squid" in the gui, must be grabbing the name incorrectly.

**Comment by Gorderok** [comment]
It is because of this problem:
https://github.com/Zrips/Jobs/issues/1254

**Comment by Zrips** [comment]
6a073dd68cf922dc50366cedef46c1b4ebfc69f8
