### ISSUE TITLE
id problem for translation

### ISSUE THREAD

**Issue by Gorderok** [Zrips/Jobs#1254]
There is an id problem between the glow_squid and the goat, they both have number 932 in the Words_ file. This poses a problem for the translation

  931-AXOLOTL: Axolotl
  932-GLOW_SQUID: Glowing Squid
  932-GOAT: Goat
  914-PLAYER: Player

**Jobs version: 5.0.0.6

**Server Type (Spigot/Paper/etc): PaperSpigot 1.17.1 #166

**Comment by Sandukhan** [comment]
You can find the right item/mob IDs in the CMILib of jobs.
  A lot of this stuff is not part of the default config.
  
  931-AXOLOTL: Axolotl
  932-GLOW_SQUID: Glowing Squid
  933-GOAT: Goat
