### ISSUE TITLE
Placholder boost

### ISSUE THREAD

**Issue by D3BoxOfficiel** [Zrips/Jobs#1255]
It is possible to check with a placeholder if there is a money / exp / points boost without specifying a trade example: 
%jobsr_user_boost_all_money%
(without having to specify the job to check permissions)

**Comment by Zrips** [comment]
No, boost in general is stored per Job, even tho we can enable boost for all jobs, it still applies boost to each separately, so placeholder like that doesn't really have reference point from which it would return any useful value.
