### ISSUE TITLE
Block-break issue

### ISSUE THREAD

**Issue by WarnDangerous** [Zrips/Jobs#1257]
***Detailed description of the issue:**

If you place some restricted block (where you shouldn't be paid or gain exp if it's players' posed blocks, like ores, but someone else break them, he will earn exp/money

So you can easily bypass the protection feature.

**Jobs version: 5.0.0.6** 

**Server Type (Spigot/Paper/etc): Airplane** 

**Server Version (using `/ver`): Airplane 1.16.5-10**

**Comment by Zrips** [comment]
Block protection is not based on who placed block but on the fact that it was placed by player in general. If some one else can earn money by breaking block then your restricted block file might not be configure properly. Double check if block gets protection with /jobs bp and properly enable all the features relating to this. Dont forget that you need to enable this one in general config file.
