### ISSUE TITLE
Change numbers in the bossbar to roman style and change the pattern color

### ISSUE THREAD

**Issue by LordVZlomka** [Zrips/Jobs#1258]
Hi, can you please add a possibility to change the bossbars pattern and the numbers? I would like to use roman numbers instead of the regular ones.
![image](https://user-images.githubusercontent.com/71541816/129487482-8f92e917-fd2d-4957-90f2-45678e26e460.png)

**Comment by Zrips** [comment]
493f94264d2c20eaa6293df60156cee3a04d278b

**Comment by LordVZlomka** [comment]
> [493f942](https://github.com/Zrips/Jobs/commit/493f94264d2c20eaa6293df60156cee3a04d278b)

Hi, I saw you closed the thread. Does it mean that it will be added with the next update?

**Comment by Zrips** [comment]
Yes, with next update you can use roman numbers to represent playes levels

**Comment by LordVZlomka** [comment]
> Yes, with next update you can use roman numbers to represent playes levels

Thank you very much! Now jobs and skills plugin will look similar in the bossbar!

**Comment by LordVZlomka** [comment]
> Yes, with next update you can use roman numbers to represent playes levels

I downloaded the latest update and couldn't find how to use Roman numbers. Please help.
