### ISSUE TITLE
Errors Editing Quests using /jobs editquests

### ISSUE THREAD

**Issue by StevenRadio94** [Zrips/Jobs#1264]
***Detailed description of the issue:**

When I try to make any changes with /jobs quests, I get an internal error. This will happen when I do /jobs editquests and try to edit the default quests or attempt to create a new one. I also get no option to edit the Kill or Custom Kill on the /jobs, as well. 

https://pastebin.com/enH3KZ2f

**Jobs version:** 5.0.0.6

**Server Type (Spigot/Paper/etc):** Spigot

**Server Version (using `/ver`):** 3232-Spigot-3c1fc60-cbd747a (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
b9733e801d0b9ab5105af3348da20f2b70cc68ce
