### ISSUE TITLE
Characters that cannot be modified in the language text

### ISSUE THREAD

**Issue by SheerYin** [Zrips/Jobs#1269]
![Snipaste_2021-09-08_17-07-49](https://user-images.githubusercontent.com/83099762/132481256-8e83f762-efe0-4bb6-acc1-4458fed269c3.png)

      petpay: ' &ePetPay bonus: &2%money% &6%points% &e%exp%'

**Comment by Zrips** [comment]
97beb812a24b43e7adfdd01f2e3313fad06bb5ad
