### ISSUE TITLE
Sugar Cane Glitch

### ISSUE THREAD

**Issue by zPorto** [Zrips/Jobs#127]
So, for some reason, when I restart my server, the payment for breaking and placing sugar cane is not working. I've searched through some forums for a bit, and found something that the option PlaceAndBreakProtection could cause this, but even after I turned it off, payment wouldn't come, doesn't matter where or how the sugar cane got broken, nothing happened.

**Comment by Zrips** [comment]
Most likely incorrect block id, check with /josb blockinfo command
