### ISSUE TITLE
Furnace ownership unregistered on restart

### ISSUE THREAD

**Issue by slvlr** [Zrips/Jobs#1271]
***Detailed description of the issue:**

When someone claims Furnaces, Cookers or Blast Furnaces via Jobs, it works absolutely fine, however when the server restarts, players do not get paid for their registered containers.
They need to type /jobs clearownership and then re-claim them every restart.

I think you need to change the way the ownership data is stored as it clears on restart?

---

**Jobs version:** 5.0.0.6

**Server Type (Spigot/Paper/etc):** Paper 

**Server Version (using `/ver`):** This server is running Paper version git-Paper-255 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: c3d5018)
You are 2 version(s) behind
Previous version: git-Paper-251 (MC: 1.17.1)

**Relevant plugins (Delete if this isn't needed):** CMILib 1.0.3.7

**Comment by Gorderok** [comment]
same problem

**Comment by Zrips** [comment]
a18ba89dedb91779115e26310db80d7f7498e561
