### ISSUE TITLE
Money & Xp bossbar display incorrect values. 

### ISSUE THREAD

**Issue by slvlr** [Zrips/Jobs#1272]
*Detailed description of the issue:

the on-screen bossbar is showing incorrect values for jobs money and xp.
It looks like you get paid the correct amount, but it is displaying the wrong amount, which is confusing a lot of players.
Every player has this, and it is a confirmed issue. Server is not lagging. 

Jobs version: 5.0.0.6

Server Type (Spigot/Paper/etc): Paper

Server Version (using /ver): This server is running Paper version git-Paper-255 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: c3d5018)
You are 2 version(s) behind
Previous version: git-Paper-251 (MC: 1.17.1)

Relevant plugins (Delete if this isn't needed): CMILib 1.0.3.7

**Comment by Gorderok** [comment]
same problem

**Comment by nivcoo** [comment]
same issue

**Comment by Zrips** [comment]
Could anyone elaborate on exact example on what is shown instead of what expected value?

**Comment by Zrips** [comment]
And maybe locale setup for bossbar message?

**Comment by slvlr** [comment]
> And maybe locale setup for bossbar message?

I haven't edited my locale files.
Not sure if this is what you are asking for...

  stats:
    help:
      info: Show the level you are in each job you are part of.
      args: '[playername]'
    error:
      nojob: Please join a job first.
    output:
      message: 'Level %joblevel% for %jobname%: %jobxp%/%jobmaxxp% xp'
      max-level: '     &cMax level   -   %jobname%'
    bossBarOutput: 'Lvl %joblevel% %jobname%: %jobxp%/%jobmaxxp% xp%gain%'
    bossBarGain: ' &7(&f%gain%&7)'

**Comment by slvlr** [comment]
> Could anyone elaborate on exact example on what is shown instead of what expected value?

The boss bar at the top of the screen displays the XP, and the message above the hotbar displays the money earned.
The issue is that players are getting the correct amount of money & xp that I put in the file, however it is displaying the incorrect values on both of these displays. 

(Display does not match what they receive).

**Comment by Zrips** [comment]
What they receive can be quite different from your config file due to bonuses and job level. So i still some specific numbers here, what you see on screen, what you expect to get and what you have set on jobs config file which determines what player should receive

**Comment by slvlr** [comment]
> What they receive can be quite different from your config file due to bonuses and job level. So i still some specific numbers here, what you see on screen, what you expect to get and what you have set on jobs config file which determines what player should receive

  max-level: 200
  leveling-progression-equation: 10*(joblevel)+(joblevel*joblevel*4)
  income-progression-equation: baseincome+(baseincome*(joblevel-1)*0.01)-((baseincome+(baseincome*(joblevel-1)*0.01))
    * ((numjobs-1)*0.05))
  points-progression-equation: basepoints+(basepoints*(joblevel-1)*0.01)-((basepoints+(basepoints*(joblevel-1)*0.01))
    * ((numjobs-1)*0.05))
  experience-progression-equation: baseexperience-(baseexperience*((numjobs-1) *0.01))
  
  I use this equation for every job.
  This issue happens both when users follow this equation, or have boost(bonuses) enabled.

**Comment by Gorderok** [comment]
cmlib version 1.0.3.7 created this problem with version 1.0.3.6 it works fine.

**Comment by Zrips** [comment]
ok, this clarifies somethings here and now i have basic idea whats going on, duno why its behaving incorrectly, but if issue appeared with 1.0.3.7 then atleast we know which change caused this issue. Will investigate. Thanks for information.

**Comment by Zrips** [comment]
Ok, will not avoid asking for extra things here. It would be nice to have generalConfig (remove mysql data if using that) file for testing as this might be related to some settings in it and maybe basic image of action bar and bossbar message. And just keep in mind that while action bar is stacked and might show results from multiple actions, bossbar can show change on every change depending on your config setup.

**Comment by slvlr** [comment]
I have sent you a copy of my config on Discord.

**Comment by slvlr** [comment]
This has been fixed. 
Thank you
