### ISSUE TITLE
Changing the decimal doesn't update the bossbar.

### ISSUE THREAD

**Issue by LordVZlomka** [Zrips/Jobs#1274]
***Detailed description of the issue:** Changing the decimal doesn't update the bossbar. It suppose to show (10/320). In general config, under "decimalplaces" I have xp, money and points set to 0.
![image](https://user-images.githubusercontent.com/71541816/133412335-e25fb461-6a4e-471a-8d4f-34adcbe29d56.png)

**Jobs version:**  5.0.0.7

**Server Type (Spigot/Paper/etc):**  Paper

**Server Version (using `/ver`):**  1.16.5

**Comment by Zrips** [comment]
81072b26ece7236d60e4c20088250dca2f551735
