### ISSUE TITLE
Async option moves economy calls to the main thread

### ISSUE THREAD

**Issue by DaniFoldi** [Zrips/Jobs#1282]
Hi,

I believe this should be a `runTaskAsynchronously`, to be truly async - right now it is scheduled for the main thread. It should be a quick fix.
 https://github.com/Zrips/Jobs/blob/52547b94a566574cad1e318c2df985b38fc6a8e7/src/main/java/com/gamingmesh/jobs/tasks/BufferedPaymentTask.java#L44

**Comment by roboalex2** [comment]
I agree since... i don't know when... all transaktions are sync even do i switched to async in the config, causing database lag.

**Comment by Zrips** [comment]
Cant argue with this. Looks like some dev decided to basically make that option for async economy transaction to not do what it was suppose to do... 
c4dfa50a167e4f841badb5fda2fc4594ccc7361b
