### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by WarnDa** [Zrips/Jobs#1283]
***Detailed description of the issue:**
Error in console when a player is killed

**ERROR (DELETE IF YOU HAVE NO ERROR):**
https://pastebin.com/bkePuFSX

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Jobs version: 5.0.0.8** 

**Server Type (Spigot/Paper/etc): Airplane** 

**Server Version (using `/ver`): git-Airplane-11 1.16.5**

**Comment by Zrips** [comment]
Made small fix relating to this, but in general error originates at WildStacker plugin and not in Jobs.
dd955ec79e298d9f4885923ca6b5d350b3651326
