### ISSUE TITLE
New translation - messages_hu.yml

### ISSUE THREAD

**Issue by montlikadani** [Zrips/Jobs#129]
Welcome!
**I want to give you a new language. Language name: messages_hu.yml (Hungarian).**
I'm sorry to write here, but I did not know about Pull Request.
**File Required: "UTF-8 Encoding Without BOM" - Required for Minecrafter, because if it is not configured, it will send meaningless messages (for example: é). The file was verified but not tested.
What I've Changed: I put a ('') sign before and end of each text.**
Here is the file: https://pastebin.com/c7h0Vt0Z
Or download: http://www.mediafire.com/file/k7w637lbwnoe2nk/messages_hu.yml

**Comment by Zrips** [comment]
Will add, thanks.
