### ISSUE TITLE
No payment for crafting suspicious stew

### ISSUE THREAD

**Issue by Sandukhan** [Zrips/Jobs#1292]
Players recive no payment (exp,money,..) for crafting suspicious stew.
Worked in older version of jobs before.

**Config:**
 
>   Craft:
       SUSPICIOUS_STEW:
         income: 0.75
         experience: 0.75

**Jobs version:** 
Jobs 5.0.0.8
CMILib 1.0.3.11

**Server Type (Spigot/Paper/etc):** 
paper 1.17.1 build 321

**Comment by Zrips** [comment]
Hard to say if your config file properly formatted, but as of testing it does look to be working correctly and players getting money for crafting it.
