### ISSUE TITLE
Enchantements and materials not rewarding

### ISSUE THREAD

**Issue by Simblizok** [Zrips/Jobs#1293]
Hello,

I have issues with some enchantments and some collectible not paying the player when he does the action.
For exemple, the action collect sweet_berries-3  doesn't give a reward. Also some enchantments also like PROTECTION_EXPLOSIONS + PROTECTION_FIRE + DAMAGE_ARTHROPODS + WATER_WORKER  the lvl doesn't matter.
Find attached my job configuration for the jobs where i found troubles. Maybe it's a bug or maybe i am an idiot and made errors in the config but either way, please help me out! ^^ 

[mage.txt](https://github.com/Zrips/Jobs/files/7316352/mage.txt)

[fermier.txt](https://github.com/Zrips/Jobs/files/7316353/fermier.txt)

**Comment by Zrips** [comment]
Sweet_berries-3 is a correct format and should give out payout when you interact with FULLY grown berry bush.
Side note, your files are in .txt format which will not get recognized by plugin in general. Those need to be in .yml format. Other than this everything looks to be working correctly as of some testing.
