### ISSUE TITLE
PayForEachCraft option duplicating rewards

### ISSUE THREAD

**Issue by Blamo27** [Zrips/Jobs#130]
Hello,

There is an issue with the "PayForEachCraft" config option. When it is set to true, the first craft you do will always give you twice the money and experience. That means that if you only craft one item, let's say, a furnace, you will earn the money and experience you would have gained if you crafted TWO furnaces. That bug only applies for the first item you craft, when you craft multiple items : if you craft 3 furnaces at once, you will gain twice the money and experience for the first one, and you will gain normal money and experience for the 2 others.

To make it perfectly clear we made a demonstration with a video :
https://cdn-e2.streamable.com/video/mp4/pnhgh.mp4?token=1505574228_7f0b5fda394772c119054c803dfd2e5873630264
We performed this on a 1.12 server with litterally just Jobs, Vault, and Essentials installed. Everything is by default, jobs and general config, EXCEPT for the "PayForEachCraft" config option that we set to true. Therefore you should be able to reproduce this bug very easily (you just have to enable "PayForEachCraft").

Because of this, we can't use the "PayForEachCraft" option, because the players would be able to gain twice the money and experience by crafting only one item each action. This means that the players are obligated to craft their items one by one, which is quite tiring - also, many players don't realize that they won't gain more money by crafting more items in a single action, and they complain.

Please note that we reported this issue over a year ago ( https://github.com/Zrips/Jobs/issues/33 ), but maybe we didn't give enough details on how the bug works for you to fix it. Anyway, we still have this bug, so we would greatly appreciate if you could look into it.

**Comment by Ferocimo** [comment]
Just to make it even clearer, here is a recap of how the bug works : 

PayForEachCraft : true

Crafting 1 furnace is supposed to reward you 1$ and 1xp
Crafting 1 furnace actually gives you 2$ and 2xp

Crafting 3 furnaces at once is supposed to reward you 3$ and 3xp
Crafting 3 furnaces at once actually gives you 4$ and 4xp
(you gain 2$ and 2xp for one furnace in the stack, and 1$ and 1xp for each additionnal furnaces in the stack).

**Comment by Zrips** [comment]
Correct, reproduced and will be fixed with next build

**Comment by Ferocimo** [comment]
Fixed indeed with last build, thank you.
