### ISSUE TITLE
Bypassing max jobs by cycling protection request

### ISSUE THREAD

**Issue by mrfloris** [Zrips/Jobs#1300]
It currently is technically possible to join the max jobs, but to quit and quickly join another, then go back ~ we noticed a slight increase in this, sometimes even with mods that auto switch as they switch their tool or block breaking. Something we wish to discourage. And yes, there's a "loss" you can configure if you switch jobs.

But, would it be possible (i couldn't find it) to have a cooldown or timeout setting in generalConfig.yml that would inform the player: Sorry, you can only leave and rejoin a job once per day (or whatever is technically logical to do to achieve this)

max jobs: 1

Player> join miner
- joined miner

Player> leave miner
- left miner

Player> join builder
- joined builder

Player> leave builder
- left builder

Player> join miner
- sorry, you left miner earlier today, you can switch jobs once per day

Player> join builder
- sorry, you left miner earlier today, you can switch jobs once per day

Player> join fisherman
- join fisherman

**Comment by Zrips** [comment]
```
  # Defines how often in seconds player can rejoin this job. Can be bypassed with jobs.rejoinbypass
  rejoinCooldown: 10
```
This can be found in _EXAMPLE.yml file and allows to set timer on rejoining jobs top prevent this job jumping. And for good practice i would recommend to keep exp loss when leaving job to atleast like 10% to discourage such actions but still keep it for those who wants to do it at some point.
