### ISSUE TITLE
Job info issue

### ISSUE THREAD

**Issue by Agaloth** [Zrips/Jobs#1315]
***Detailed description of the issue:**

The plugin says that people don't get money for anything but they do.
![image](https://user-images.githubusercontent.com/33335971/140053315-a8d10166-6f87-44d4-8c91-84858314c9f0.png)

**Jobs version:** 
5.0.0.9

**Server Type (Spigot/Paper/etc):** 
Purpur

**Server Version (using `/ver`):** 
git-Purpur-1382 (MC: 1.17.1)

**Comment by eyebrawl123** [comment]
tthe same here

Jobs version:
5.0.0.9

Server Type (Spigot/Paper/etc):
Paper

Server Version (using /ver):
Server Type (Spigot/Paper/etc):
Purpur

Server Version (using /ver):
This server is running Paper version git-Paper-359 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: bc43f40)
You are running the latest version
Previous version: git-Paper-358 (MC: 1.17.1)

**Comment by amarcais53** [comment]
i have the same issue

**Comment by ItsSynchro** [comment]
+1 Same issue started to occur after updating to the latest build on Spigot (5.0.0.9).

**Comment by Agaloth** [comment]
> the same here
> 
> Jobs Version: 5.0.0.9
> 
> Server Type (Spigot/Paper/etc): Paper
> 
> Server Version (using /ver): Server Type (Spigot/Paper/etc): Purpur
> 
> Server Version (using /ver): This server is running Paper version git-Paper-359 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: bc43f40) You are running the latest version Previous version: git-Paper-358 (MC: 1.17.1)



> +1 Same issue started to occur after updating to the latest build on Spigot (5.0.0.9).



> i have the same issue

I found a solution, use /jobs info {job} {action}
Like /jobs info Woodcutter Break

But I think it's not supposed to be that way anyways

**Comment by Jinendra1** [comment]
the same prob

**Comment by Momshroom** [comment]
We also have this issue.  Using Jobs Reborn 5.0.0.9, Paper 381.

**Comment by SkeletonAce** [comment]
I'm also setting the same issue :(

(Paper 384, Jobs Reborn 5.0.0.9)

**Comment by Zrips** [comment]
4c6c41bc52683888f0bf09599ba3f81af6c8929a
