### ISSUE TITLE
No payment when fishing in a boat

### ISSUE THREAD

**Issue by elaineandsparky** [Zrips/Jobs#1318]
Not sure if this is a bug or intentional but my players aren't being paid for fishing whilst in a boat. If this is intentional, why?

The only thing I can see that might be affecting this is configs is the below but I thought that was for riding horses for example when exploring:

# Disables the payment when the player riding on an entity.
disablePaymentIfRiding: true

**Comment by KermX** [comment]
Boats are entities, https://www.digminecraft.com/lists/entity_list_pc.php

**Comment by elaineandsparky** [comment]
Any way the two cam be separated in configs?

**Comment by Zrips** [comment]
33b4dfe6cee5be705c73d3c09fb3c5b473144050
