### ISSUE TITLE
Very serious performance problem

### ISSUE THREAD

**Issue by p82183645** [Zrips/Jobs#1319]
Check this timings, jobs loadworld is mandatory
https://timings.aikar.co/?id=825f814b5b0b4723b46f4459fad45301
I have set world whitelist restrictions

But jobs still force loading the world
Because my dungeon plugin is to create world events
Please fix this problem, it will cause a lot of performance lag
![image](https://user-images.githubusercontent.com/5382252/141286778-43c790fc-39b4-407c-ba90-fc107efbbaaf.png)

---

**Jobs version:** 5.0.0.9

**Server Type (Spigot/Paper/etc):** paper

**Server Version (using `/ver`):** 1.12.2

**Comment by Zrips** [comment]
Jobs by itself isint force loading worlds, there maybe might be some triggers while jobs tries to check some things located in those unloaded worlds, but by itself it wont load worlds. What your timings points to is basic listener which gets triggered when world loads, in which case plugin adds default permission node for that world. 
What i can do here is to cache worlds we added permissions for and avoid doing that same action again, other than this there might be some more core issues when it comes to setting default permissions on your server which are not directly related to Jobs plugin.
63a8abc7498f0ce103c4dbb17a1493383890655b

**Comment by p82183645** [comment]
> 

so how to fix this?
