### ISSUE TITLE
Signs don´t translate jobs.

### ISSUE THREAD

**Issue by coleccion72** [Zrips/Jobs#1321]
Signs doesn't translator jobs.

---

![2021-11-17_13 50 57](https://user-images.githubusercontent.com/88706819/142208896-1f5c332f-c67e-4345-8d46-4113e7aa0005.png)

![2021-11-17_13 51 30](https://user-images.githubusercontent.com/88706819/142208938-0b9a0c9d-f595-4e25-983a-034c1f8476d6.png)

**CONFIG SECTION:**

 *** FILE: generalConfig.yml ***
locale-language: es

*** FILE: jobs/hunter.yml ***
Hunter:
  fullname: Cazador
  shortname: H

---

**Jobs version: 5.0.0.9** 

**Server Type (Spigot/Paper/etc): Spigot** 

**Server Version (using `/ver`): 1.16.5**

**Comment by Zrips** [comment]
17005f2823e00245a621ffae88bd39b8fd8772a9
