### ISSUE TITLE
Jobs Reborn | Placeholders in the ActionBar

### ISSUE THREAD

**Issue by Woodpecker123** [Zrips/Jobs#1322]
Placeholders in ActionBar don't work for some reason, what should I do?
Example in the attached screenshot:

![Знімок екрана 2021-11-17 134034](https://user-images.githubusercontent.com/87870686/142395637-aca9c6e3-1882-47d9-a917-1d13809f0525.png)

Additional information:
Server Core: Purpur
Server version: 1.17.1
Plugin Name: Jobs Reborn
Plugin version: v5.0.0.5
CMILib plugin version: v1.0.3.3

**Comment by Woodpecker123** [comment]
?

**Comment by Zrips** [comment]
Because those lines only translate original variables and not all of them. And gain is batched so its not coming from a single action/job so there isint real meaningful to indicate that. For something like that we have bossbar messages
