### ISSUE TITLE
GUI bugs

### ISSUE THREAD

**Issue by SkeletonAce** [Zrips/Jobs#1323]
**Hiding item attributes option does not work:**
```
Do we hide all item attributes in GUI?
  HideItemAttributes: true
```
**Gui button 'next' does not work:**
```
Defines next button slot in GUI
  NextButtonSlot: 45
```
**Gui resize does not resize the gui:**
```
Defines size in rows of GUI
  Rows: 5
```
Jobs version (5.0.0.9)

Server Type (Paper-384)

Server Version (1.17.1)

**Comment by Zrips** [comment]
As of testing, options looks to be working. Just keep in mind that those are for /jobs join, while shop gui resizes automatically and adds buttons at bottom for next and previous page automatically when needed while at same time doesn't hide item attributes as it should be visible if you are selling item with those.
