### ISSUE TITLE
Maximum payout per hour

### ISSUE THREAD

**Issue by JustAMatt** [Zrips/Jobs#1325]
**A limit to how much money the plugin will doll out to a player in a configurable amount of time.**

**Before paying out the plugin should check if the player has exceeded the maximum pay (config) allowed in X period of time (config).**

maximum-pay:
money-limit: 0 #maximum amount of money that can be handed out in the time period, 0 to disable.
billing-period: 1h #defined in Minutes, or Hours, or Days (24hours), or Weeks (7 Days).

**Comment by Zrips** [comment]
We have entire section dedicated for payment limitations already. Additionally there is /jobs limit command to indicate how much you have for current limit and when it resets. Just search for "Money gain limit" in general config file
