### ISSUE TITLE
Explore action NOT work

### ISSUE THREAD

**Issue by ken-kentan** [Zrips/Jobs#133]
Hi, Im using Jobs Reborn 4.1.3.

Explore action doesnt work at all world in my server.
I,m not FLY mode.

This bug has been reported many. why did you not fix it?

Im using default jobConfig.yml.

plz fix it.

thanks.

**Comment by TheDeviantCrafter** [comment]
Are you by any chance using a pre-generated world? I noticed that broke the plugin on my server.
