### ISSUE TITLE
Jobs always clear

### ISSUE THREAD

**Issue by DoctaEnkoda** [Zrips/Jobs#1334]
ISSUE : https://github.com/Zrips/Jobs/issues/1307

You have not fixed this bug, it always recurs and causes clears of jobs

**Comment by mrfloris** [comment]
Your title is about jobs clearing, i am not sure what you mean.

What you linked to is a bug about duplicated entries. How are they related?

CAn you type  this in console and share the full output?

```
ver
ver jobs
ver cmilib
ver luckperms
```

Are you on a bungee network? How do you store your jobs data, default sqlite3 or mysql database? You use any jobs-plugins-addons that hook into jobs (besides vault and maybe mcmmo). Or a third party plugin that shares plugin data over a proxy network?

Please define better what 'jobs cleared' means to you.

**Comment by DoctaEnkoda** [comment]
ver : 
```[23:33:01 INFO]: This server is running Purpur version git-Purpur-"c877ef7" (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: c877ef7 on ver/1.17.1)```
ver jobs:
```[23:33:26 INFO]: Jobs version 5.0.1.0
[23:33:26 INFO]: Jobs plugin for the BukkitAPI
[23:33:26 INFO]: Website: https://www.spigotmc.org/resources/4216/
[23:33:26 INFO]: Authors: Zrips and montlikadani```
ver cmilib:
```[23:33:53 INFO]: CMILib version 1.0.4.3
[23:33:53 INFO]: CMI library
[23:33:53 INFO]: Website: https://www.spigotmc.org/resources/cmilib.87610/
[23:33:53 INFO]: Author: Zrips```
ver luckperms
```
[23:34:07 INFO]: LuckPerms version 5.3.85
[23:34:07 INFO]: A permissions plugin
[23:34:07 INFO]: Website: https://luckperms.net
[23:34:07 INFO]: Author: Luck
```
Its Velocity Network
Jobs data are save in MYSQL database
No jobs addons (only vault)

Jobs are clear because id player is always changed with new entry

**Comment by DoctaEnkoda** [comment]
Exemple Multiple Entry : 
![image](https://user-images.githubusercontent.com/26461373/145732377-62597d58-a339-4bfd-a8bb-f0993519e488.png)

**Comment by mrfloris** [comment]
Jobs 5 on 1.17.1 requires cmiblib 1.1
Upgrade to 1.1.0.2 or newer.

Thanks for the extra info, hopefully it's helpful to zrips.
