### ISSUE TITLE
Could not pass event PlayerInteractEvent

### ISSUE THREAD

**Issue by Sandukhan** [Zrips/Jobs#1335]
Yerserday, I updated jobs to the newest version and got some error spam. Not quite sure about the cause.

PasteBin:
https://pastebin.com/r80KXVXR

**Jobs version:** Jobs 5.0.1.0, CMILib 1.1.0.2

**Server Type (Spigot/Paper/etc):** paper-1.17.1 build 399

**Comment by JonneSaloranta** [comment]
Did you solve the issue?

**Comment by Zrips** [comment]
Issue wasn't originating from Jobs plugin but from paper build itself.
