### ISSUE TITLE
Placeholder problem

### ISSUE THREAD

**Issue by Adriianh** [Zrips/Jobs#1339]
***Detailed description of the issue:**
For MONTHS, I have had this problem; I have repeatedly asked for help on the discord but they just ignore me. 

So here goes... the problem is that the placeholder %jobsr_user_canjoin_[job]% just doesn't work, it always returns false even though the user can login to the job.
---

---

**Jobs version: 5.0.1.0** 

**Server Type (Spigot/Paper/etc): Paper** 

**Server Version (using `/ver`): 1.17.1**

**Comment by Zrips** [comment]
dfa564aa749f6f1b00c141a962654233db237052
