### ISSUE TITLE
 org.sqlite.SQLiteException: [SQLITE_BUSY] The database file is locked (database is locked) When doing anything with the plugin

### ISSUE THREAD

**Issue by beabuenodev** [Zrips/Jobs#1341]
Everytime someone runs a command from the plugin, the console dumps this:

---
(https://pastebin.com/DcjM7k9J)

storage:
  # storage method, can be MySQL or sqlite
  method: sqlite
# Requires Mysql
mysql:
  username: root
  password: ''
  hostname: localhost:3306
  database: minecraft
  table-prefix: jobs_
  verify-server-certificate: false
  use-ssl: false
  auto-reconnect: true
  characterEncoding: utf8
  encoding: UTF-8

---

Jobs version: last version 

**Server Type (Spigot/Paper/etc): Paper

**Server Version (using `/ver`): This server is running Paper version git-Paper-77 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 5ad1d9a)

**Comment by beabuenodev** [comment]
It deletes all jobs data everytime i reload, is there any fix to this bug?

**Comment by JonneSaloranta** [comment]
Try removing DeluxeMenus from your plugins folder. Not sure if that's your issue, but it's throwing an error
[15:33:38 WARN]: at DeluxeMenus-1.13.4-Release (1).jar//com.extendedclip.deluxemenus.action.ClickActionTask.run(ClickActionTask.java:44)
