### ISSUE TITLE
Plugin deactivated on startup. Error: Queue full

### ISSUE THREAD

**Issue by thorbm1500** [Zrips/Jobs#1347]
***Detailed description of the issue:**
The plugin Plan posted in console, something about either reporting and/or disabling the Jobs plugin. So I just went ahead in the plan config files and set Jobs to false. I then restarted my server and noticed the error codes and that Jobs was deactivated in the plugin list. Haven't updated anything, and I'm on the latest version of Paper. 121

**ERROR:**
```
https://pastebin.com/TGQYp4qw
```

**CONFIG SECTION:**
```
https://pastebin.com/8T49NgMP
```

**Jobs version:** 
Jobs 5.0.1.0
**Server Type (Spigot/Paper/etc):** 
Paper
**Server Version (using `/ver`):** 
`
This server is running Paper version git-Paper-121 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 4bf2aef)
You are running the latest version
Previous version: git-Paper-114 (MC: 1.18.1)
`
**Relevant plugins (Delete if this isn't needed):**
I don't think Plan had anything to do with it, but I'm mentioning it anyway, since it's the plugin that made me notice the error.

**Comment by thorbm1500** [comment]
I rolled back to the version of paper I was running prior to updating my server and it fixed the issue. 
This is the version I'm currently on with no issues
`
This server is running Paper version git-Paper-114 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: a99a33c)
You are 7 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-121 (MC: 1.18.1)
`

**Comment by thorbm1500** [comment]
Updated to a newer version, as it is now available. The problem has been fixed. Might just have been an error on paper version 121

**Comment by ecstaticnoodle** [comment]
I am still getting it on queue full on 1.18.1-124.

**Comment by thorbm1500** [comment]
Yeah, mine stopped working again, out of nowhere

**Comment by mrfloris** [comment]
It seems on first start it is fine, on server restart it fails. for some ppl.

This started happening last week when spigot updated 'comments in configs via snakeyml', and that is the error i see mentioned here.

i can't reproduce it, none of my plugins have this (thankfully) but i have seen jobs, and Other plugins report the same type of queue full issue.

**Comment by thorbm1500** [comment]
The problem is that it worked fine yesterday, and then out of nowhere it stopped working. I didn't restart my server or anything

**Comment by mrfloris** [comment]
maybe update the oldest ticket about this ^ the one i linked there, with things like
```
java --version
```
```
ver
ver cmilib
jobs version
ver luckperms
ver vault
```
And if you use a control panel, a proxy like velocity or something, 

If you use plugman to do this, or /reload, or /restart, or /stop and start .. 

If it happens during startup or at a specific command.


If you use any startup parameters, this could help debug as well.

**Comment by Thihi** [comment]
I had this same problem earlier today with Paper Spigot build 124. I downgraded back to 119 and the bug disappeared. I then upgraded to the new 125 build and Jobs seems to work for now.

Some info:

Spigot load command:
java -Xms8G -Xmx8G -jar

Java version:
openjdk 17.0.1 2021-10-19
OpenJDK Runtime Environment (build 17.0.1+12-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 17.0.1+12-Ubuntu-120.04, mixed mode, sharing)

Spigot version and various plugins
![image](https://user-images.githubusercontent.com/24212905/147877124-96a4d416-1cfd-454a-a2c5-f4b30b470cb4.png)

**Comment by Chamikaz** [comment]
Me too, i have this bug ^^
https://pastebin.com/F9P5cC2J

**Comment by ecstaticnoodle** [comment]
Mine looks pretty much the same as everyone else's I just have less ram. Still a problem on 1.18.1-126

**Comment by ecstaticnoodle** [comment]
Ok I've restarted a bunch of times now. I regenerated the whole folder, then I started removing comment lines in the _Example job and it seems to have fixed the issue.

**Comment by mrfloris** [comment]
> Mine looks pretty much the same as everyone else's I just have less ram. Still a problem on 1.18.1-126

please provide some info, just "samesies" isn't helping debug this. 
```
java --version
```
and
```
ver
ver cmilib
ver luckperms
jobs version
```
and if you use a control panel or any jvm startup flags, or if you use a proxy like bungee or velocity

**Comment by mrfloris** [comment]
> Me too, i have this bug ^^ https://pastebin.com/F9P5cC2J


please provide some info, just "samesies" isn't helping debug this. 
```
java --version
```
and
```
ver
ver cmilib
ver luckperms
jobs version
```
and if you use a control panel or any jvm startup flags, or if you use a proxy like bungee or velocity

**Comment by chrisraj1** [comment]
Having the same problem

https://pastebin.com/YbP58vy3

Purpur 1479
CMILib version 1.1.0.4
Jobs version 5.0.1.0
Luckperms version 5.3.89
Java 17 (OpenJDK 64-Bit Server VM 17.0.1+12)

**Comment by mrfloris** [comment]
i saw some info on spigot about it from another dev/person
https://www.spigotmc.org/threads/plugin-config-api-java-lang-illegalstateexception-queue-full.540774/

**Comment by chrisraj1** [comment]
One quick and very temporary fix that seems to work for me and at least one other is deleting all of the comments from the _EXAMPLE.yml file in the jobs folder. What I believe is happening is that every time the server restarts or the plugin is reloaded (maybe some other event), the comments in that folder get duplicated. Eventually, that file gets overloaded with comments which for some reason causes the plugin to fail to load.
<img width="622" alt="jobs" src="https://user-images.githubusercontent.com/80594307/147909885-892d4373-f261-4188-aad3-e2ad28247b77.png">

**Comment by mrfloris** [comment]
Shame, I see it now also caught cmilib 
https://ptb.discord.com/channels/452792793631555594/526402563847880725/927455719559692308

**Comment by mrfloris** [comment]
This crap started happening after this post (and spigot update) https://www.spigotmc.org/threads/9-years-of-spigotmc-spigot-bungeecord-1-18-1-18-1-release.534760/page-14#post-4327851

**Comment by Zrips** [comment]
Pushed out update for CMILib which resolves this issue, please update it
