### ISSUE TITLE
Compatibility issue with the Crazy Enchantment's plugin's Furnace enchantment

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Zrips/Jobs#135]
[Crazy Enchantments ](https://www.spigotmc.org/resources/crazy-enchantments-new-gkitz.16470/) has a plugin called Furnace that automatically smelts mined ores. When this happens, the Miner job doesn't register the action.

I would expect it to give the same amount of xp and money you would get from mining an iron ore with an unenchanted pickaxe, but it doesn't give any at all. Mining it with a regular pickaxe works as intended.

**Comment by Zrips** [comment]
If plugin is not firing actual smelt event with appropriate data which can be process by Jobs plugin, then i cant really help you out. Things like this should be handled by Furnace plugin it self.
