### ISSUE TITLE
Lag spikes, after adding new blocks to the job Builder in builder.yml

### ISSUE THREAD

**Issue by thorbm1500** [Zrips/Jobs#1354]
***Detailed description of the issue:**
Player will experience lag spike, after placing a block added manually in the file builder.yml when they get paid.

**Jobs version:** 
Jobs: 5.0.1.0 SqLite
CMILib: 1.1.0.6

**Server Type (Spigot/Paper/etc):** 
Paper

**Server Version (using `/ver`):** 
git-Paper-134 (MC: 1.18.1)

**Comment by Zrips** [comment]
You will need to gather timings to get any idea whats going on there exactly

**Comment by thorbm1500** [comment]
I've sent you a timings report on discord, as I'd like to keep that information somewhat private. I've titled the message "Lag spikes after CMILib update #1354"

**Comment by Zrips** [comment]
Gets resolved with next CMILib update
