### ISSUE TITLE
Brewer

### ISSUE THREAD

**Issue by FireBug7191** [Zrips/Jobs#1359]
Was wondering if you could add drinking potions to count towards brewer. 

Drink a potion to count towards brewer xp and moneys

**Comment by JinnFletch** [comment]
Must my 0.02c -- I think you mean "consume".  Not brewer-specific.  But that consuming any consumable could be used as a hook for experience.   You personally might configure the brewer such that consuming certain potions gains them some xp.  But someone else might configure that a fisherman eating fish raises theirs.  Same with consuming milk, spider's eye, and whatever else.

**Comment by JinnFletch** [comment]
BTW: Not sure if the `Eat` command does this or not, but there IS an `Eat` command.  May wanna try it.  I'm not a dev here, lol

**Comment by JinnFletch** [comment]
Weird, I happened to be reading the website, and it says there is a `Drink` action that works with potions.  Even though it wasn't in my EXAMPLE.yml (Maybe brand new?)  So just apply those to your Brewer and see if it works out :)

**Comment by FireBug7191** [comment]
ok will try that thankyou
