### ISSUE TITLE
Crafting 64 items with the Crafter job gives you 1 item's worth of XP/money

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Zrips/Jobs#136]
By default, crafting a single cauldron gives $6.30. If you craft one cauldron at a time, this works as intended. If you craft a stack at a time using shift click, however, you still get $6.30. It should give $403.20 by my math.

**Comment by Ilinalta** [comment]
I'm also experiencing this issue, with multiple items. An example is trying to craft pumpkin pies by shift clicking the output for 16 pies at once, but only getting paid for making 1 of them. I **love** the plugin thus far and would like to see a fix for this soon - only issue I've had.

**Comment by Ilinalta** [comment]
Is this gonna get a response? Is it being looked into or going to? @zrips

**Comment by Zrips** [comment]
If anyone would bother to look up throw config file, you would find a section with the name of **PayForEachCraft** which will pay for each separate item when crafting.

**Comment by Ilinalta** [comment]
Finally. Thanks for actually replying. Wasn't clear to me what that section is for when I first read through the notes in the config, nothing about the shift clicking action in the explanation. So I didn't touch it.
