### ISSUE TITLE
Expboost issue

### ISSUE THREAD

**Issue by Threshian** [Zrips/Jobs#1366]
***Detailed description of the issue:**

Hi, i'm not sure if it's a bug or if i don't use correctly the command but when i use /jobs expboost [jobs] [time] [rate] the time never work and the rate don't go off even after using /jobs expboost reset [jobs]. I'm forced to /jobs reload to make the reset work.

---

**Jobs version:**  5.0.1.1

**Server Type (Spigot/Paper/etc):**  Paper

**Server Version (using `/ver`):** Paper 1.18.1-152

https://www.youtube.com/watch?v=FJEYyJIjaWk

**Comment by Zrips** [comment]
3b0cfc662f0673b4864d7a532090738e887c94f0
