### ISSUE TITLE
NPE on attempting to skip a quest in Jobs 5.0.1.1

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/Jobs#1367]
**Detailed description of the issue:**

Getting an NPE when a player attempts to skip a quest via the internal "click to skip this quest" function in `/jobs quests`. Results in the "An internal error occurred while attempting to perform this command" response, and the quest is not skipped.

**ERROR (DELETE IF YOU HAVE NO ERROR):**
https://gist.github.com/mercurialmusic/3ec8fd3636fbf3bcc89477de42d26cb4

**Jobs version:** 
Jobs 5.0.1.1, CMILib 1.1.0.8
**Server Type (Spigot/Paper/etc):** 
Paper
**Server Version (using `/ver`):** 
git-Paper-152 (MC: 1.18.1)

**Comment by Zrips** [comment]
Your error log cut off at exact place where it indicates place of failure. I need entire section of that log.

**Comment by Zrips** [comment]
33d14cf927726f21fc72ac79df1c1fac53b54573
