### ISSUE TITLE
Temporary Permission Boosts Bug

### ISSUE THREAD

**Issue by benzkungx10** [Zrips/Jobs#1368]
***Detailed description of the issue:**

---

I've tested giving temporary perms, when the bonus timeout is still active. The bonus server must be restarted before it disappears. It should disappear with the Perms.

jobs.boost.jobName.money.amount
jobs.boost.jobName.exp.amount
jobs.boost.jobName.points.amount

---

**Jobs version: 5.0.1.1** 

**Server Type (Spigot/Paper/etc): Paper** 

**Server Version (using `/ver`): 1.18.1**

**Comment by Zrips** [comment]
There is a delay of 1 minute before this permission gets recalculated. This is to avoid constant permission recalculations as its not a simple permission check, this one requires allot more checks to be done, so we limited it to once every minute.

**Comment by benzkungx10** [comment]
I waited more than 30 minutes, still working.

**Comment by benzkungx10** [comment]
Only need to restart the server to normal bonus, I've tried.

**Comment by WhatsTheBadNews** [comment]
We are also having this issue. Permissions boosts not going away (after they are finished) until after restarts.

**Comment by Braynblocks** [comment]
Happening on my server as well. The boost won't go away until the server restarts.

**Comment by BakiDance** [comment]
I'm also affected by this issue.
