### ISSUE TITLE
1.18.1: Jobs promote is not executing commands

### ISSUE THREAD

**Issue by ACluco1** [Zrips/Jobs#1369]
When you re preforming command /Jobs promote (which is giving players levels), the last level you will get from it, is not preforming commands as it is on /jobs exp. For example, if you will preform /Jobs exp player job add amount (10 000) you will get for ex. 5 levels up and the last level you get, it will preform commands from that level. So when im at level 5 and i will get level 5 from that 10K exp, it will preform command from level 10 (broadcast for example or what is configured). Which is really nice, because i have some vouchers for jobs levels. (not actually exp, but levels - /jobs promote) But! When i would like to give my players level with that command (/jobs promote) it wont preform any commands at all, which is kinda sad, because i have configured that when they got level 50, which is my max level, they wont be able to use those vouchers for particular job. (cuz they will get blacklist permission for particular voucher) Of course, it is working when you re giving them EXP via command and when they re gaining EXP as normal. But when they got levels via command jobs promote, the command wont be preformed and they will be able to use that vouchers again, which i dont want to.

 I hope you understand the problem, but in short, Jobs promote is not preforming jobs levelup commands but jobs exp is preforming them. I would like to make jobs promote also preforming jobs commands

I tried as well /jobs level but it is the same except this command can go above max level.

**Jobs version:** 
5.0.1.1

**Server Type (Spigot/Paper/etc):** 
Purpur 1.18.1

**Server Version (using `/ver`):** 
git-Purpur-1502 (MC: 1.18.1)

**Comment by JinnFletch** [comment]
(Not a mod)
Yo!  I wonder if you and I are having the same issue.  Are you specifically talking about commands as in the _EXAMPLE.yml

```
  # Commands executed when player reached level
  commands:
    fly:
      command: lp user [player] permission set essentials.fly
      levelFrom: 100
      levelUntil: 100
```

Whenever I run command `jobs level PlayerName JobName set ##`, the command at that number is not run.  But whenever a player legitimately levels up from the prior level into ##, then the command does run.

Same issue?  Or different?

**Comment by ACluco1** [comment]
yes, kinda the same. Instead of jobs level im using jobs promote, because with jobs promote you cant go above max level of the job, which with jobs level you can

**Comment by Zrips** [comment]
Well promoting some some one isint triggering commands as you might have quite few of those getting triggered at once and it might not be a desired behavior in general for some one. What I could do is to add extra variable to trigger commands associated to player leveling up which would be triggered in same way as it would happen when player levels up normally

**Comment by Zrips** [comment]
0811283201806357e16f1bb9d4d611e74c0b1646

**Comment by ACluco1** [comment]
Thanks!
