### ISSUE TITLE
levelUp commands never fire if XP given via command is enough to jump over level

### ISSUE THREAD

**Issue by viveleroi** [Zrips/Jobs#1372]
***Detailed description of the issue:**

When a player receives job XP via command `/jobs exp...`, levelUp commands are not executed if the xp is enough to *skip* that level entirely. 

Example: player is level 4, we have a command trigger configured at level 5. They get enough XP to jump to level 6. The level command is never fired.

**Jobs version:** Jobs5.0.1.1

**Server Type (Spigot/Paper/etc):** Purpur

**Server Version (using `/ver`):** This server is running Purpur version git-Purpur-1520 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: dec07e6 on HEAD)
Previous version: git-Purpur-1509 (MC: 1.18.1)

**Comment by Zrips** [comment]
7970b15d02f5d837bb05241dbb3e581a5492ba03
