### ISSUE TITLE
Compatibility issue with the Crazy Enchantments telepathy enchantment and the miner job

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Zrips/Jobs#138]
[Crazy Enchantments ](https://www.spigotmc.org/resources/crazy-enchantments-new-gkitz.16470/) adds an enchantment called Telepathy that can be applied to a pickaxe. It teleports blocks you mine directly into your inventory.

This enchantment is incompatible with the Miner job. When you mine an ore with a Telepathy pickaxe, you don't get Miner xp or money for it.

**Comment by Zrips** [comment]
If new enchantment is not properly registered with minecraft server and all enchants are being handled directly by plugin, then i cant help you out with this. Get in contact with plugins dev for possible fix from his end.
