### ISSUE TITLE
ExpBoost time not accumulating

### ISSUE THREAD

**Issue by Threshian** [Zrips/Jobs#1382]
***Detailed description of the issue:**

Hi, i was wondering if there is a way to accumulate time (not the multiplicator) from exp/money/point boost using the command ? It don't work by doing the command multiple time

---

**Jobs version:** 5.0.1.2

**Server Type (Spigot/Paper/etc):** Paper

**Server Version (using `/ver`):** 1.18.1-152

**Comment by Zrips** [comment]
There isint any command currently to add time to existing timer, you can only enable it for defined time or disable.
