### ISSUE TITLE
Claimed Furnaces randomly unclaiming

### ISSUE THREAD

**Issue by Heliosares** [Zrips/Jobs#1383]
***Detailed description of the issue:**

---
Claimed smelters, furnaces, blast furnaces, etc. are intermittently lost when players relog or the server restarts.
---

**Jobs version:** 
5.0.1.0

**Server Type (Spigot/Paper/etc):** 
Paper

**Server Version (using `/ver`):** 
1.18.1-124

**Comment by Zrips** [comment]
Should be fixed with latest builds
