### ISSUE TITLE
Reset total quests for all players (support question)

### ISSUE THREAD

**Issue by DjeyMute** [Zrips/Jobs#1385]
_Hi,_
I have a problem I would like to reset the total quests of all my players in the Sql in "donequests" but I have a problem.
When I set my players to "0" or "NULL" in the "donequests" some players come back with "23" or "36" for **no reason**.

Can you tell me if I should do anything else to reset the total of quests done by my players?
Or if it's possible **create a command** to remove the total quests a player has done?
For example with a command like this _/jobs resetquesttotal_

_Thank you in advance._

---

Jobs version : 5.0.1.1

Server Type (Spigot/Paper/etc) Spigot : Paper

Server Version (using `/ver`): 177

**Comment by Zrips** [comment]
f53a32e35ac297f1e971ba9706ace8e5d626ea9f
