### ISSUE TITLE
Tipped arrow don't work

### ISSUE THREAD

**Issue by DjeyMute** [Zrips/Jobs#1386]
I have a problem with the special arrows.
They just don't work anymore.
I tried with different formats but I can't.
Has the format changed? Or is this a problem with 1.18?

```
**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
My format : 
    tipped_arrow:night_vision:
      income: 0.25
      experience: 0.29
    tipped_arrow:invisibility:
      income: 0.25
      experience: 0.29
    tipped_arrow:jump:
      income: 0.25
      experience: 0.29
    tipped_arrow:fire_resistance:
      income: 0.25
      experience: 0.29
#####################################
```

---

**Jobs version:** 5.0.1.1

**Server Type (Spigot/Paper/etc):** Paper

**Server Version (using `/ver`):** 166

**Comment by Zrips** [comment]
Main thing I have noticed would be `tipped_arrow:jump:` you are using double : which basically brakes entire line. Use dash like `tipped_arrow-jump:`
