### ISSUE TITLE
Make trading a valid action

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Zrips/Jobs#139]
I've been wanting to create my own jobs, but all of the valid actions are already used by jobs. It would be difficult to design new ones that aren't just rehashed of existing jobs.

With that in mind I'd like to suggest a few new actions:

•Trading:

Two actions would exist here. One triggers when you give an item to a villager such as emeralds or paper. The other would trigger when you receive an item from a villager, such as an enchanted book.

Enchantments should also be taken into account, meaning a mending book would be worth more than a sharpness 1 book.

•Looting items from chests:

This would only work for items in naturally generated chests not taken by the player. I'm not really sure how this would be done in a way that doesn't result in you gaining money from taking iron from your own chests.

•Traveling:

There would be separate events for riding by pig, minecart, elytra, boat and horse. They would probably trigger for every meter traveled. If this is added, it could easily be rolled into the explore job by default.

**Comment by Ilinalta** [comment]
Some great ideas for additions which I would personally use too.

**Comment by Zrips** [comment]
Trading is possible to add, but only on actions when you are getting some trade result
Looting is an interesting idea, but more or less not reasonable to make as we would need to save every chest being interacted into database to separate naturally generated and placed by players. We can, of course, utilize block protection to check this one, but end result can be quite messy.
Traveling and calculating each meter would be too harsh on server performance as we would need to check each players position and travel distance from last x seconds. Maybe some implementation of vanilla statistics into this would be more efficient way in rewarding players for particular actions.

**Comment by TheDeviantCrafter** [comment]
Hooking into the statistics system is certainly possible. That's how the Advanced Achievements plugin seems to do it.
