### ISSUE TITLE
Ability to define the age of a crop within a job configuration.

### ISSUE THREAD

**Issue by 7hatGuyAJ** [Zrips/Jobs#1397]
I'm unsure if this is currently a feature as I am unable to find any infomation on it.  
I would like the ability to define a crop age when harvesting so if a crop does not meet its preset age there will be no payout.

we should be able to add an argument to define the growth stage of a crop so if a crop is broken before its defined growth stage there would be no payout for the action, I'm no coder so I don't know the best way to implement this but I included an example yml of what this could look like within a job the age of the crop its self explanatory "growth stage 4" to keep it simple.

Break:
    wheat-4:
      income: 1
      points: 1
      experience: 1
    potatoes-4:
      income: 1
      points: 1
      experience: 1
    carrots-4:
      income: 1
      points: 1
      experience: 1
    beetroots-4:
      income: 1
      points: 1
      experience: 1

**Comment by Zrips** [comment]
Its already a feature. you can check growth stage by looking at plant and using `/jobs blockinfo` which will print out current stage. For fully grown one its wheat-7, i know its a weird number but its some what legacy one which indicates fully grown wheat plant
