### ISSUE TITLE
Pay For Above only giving XP for one item in Minecraft XP bar

### ISSUE THREAD

**Issue by TheJoigoMan** [Zrips/Jobs#1398]
I'm using Jobs to boost XP gain on my server. When farmers break bamboo or kelp they are supposed to gain XP for all of the blocks broken automatically above the first one. 

The system gives money, points and exp correctly for the Jobs Interface, but it only gives the Minecraft XP the value for one broken block. So the systems registers all of the calculated XP for all broken items, but just adds the value from one to the bar.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
pay-for-above: true
```

Jobs Reborn 5012
Paper
git-paper-188
Plugins (17): AdvancedTeleport, BetterRevive, CMILib, DeathCoordinates, Essentials, EternalLight, Graves, Jobs, LoginPlus, LuckPerms, LWC, NBTAPI, PL-Hide, ProtocolLib, SkinsRestorer, TabList, Vault

**Comment by Zrips** [comment]
Should be working correctly with next update. If issue persists let me know. Tho side note, this could be effected by slow server performance.
