### ISSUE TITLE
Jobs Dynamic display different

### ISSUE THREAD

**Issue by Sprungente** [Zrips/Jobs#140]
Hello 
Its a minor bug.
The Job penalty or bonus in the GUI have different value as the /jobs browse command chat-output. 

The chat-output from /jobs browse has the right value. 

Maybe the germantranslation has the bug or the GUI it self.

No error in Logs or chat
I use Jobs 4.1.3 on CraftBukkit version git-Spigot-7754231-a3b3a42 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Bug, will be fixed
