### ISSUE TITLE
[Suggestion] Adding a placeholder for Jobs Quests Description

### ISSUE THREAD

**Issue by TZ122** [Zrips/Jobs#1406]
Using GeyserMC, Bedrock (MCPE) players lack the ability to hover over chat to view jobs quest descriptions. I am suggesting a placeholder for jobs quest descriptions be added to Zrips jobs. This could also be helpful for server owners who may want to put the placeholder in menus etc.

**Comment by Tejay17** [comment]
Hey I have a ton of my bedrock players also having this problem. Possible at add this palceholder?

**Comment by Donkk0** [comment]
I would also like to see this, as I use DeluxeMenus for Jobs. I have thousands of quests. I just can't provide info on those through the DM, as I would have to write all of the descriptions myself.

**Comment by Zrips** [comment]
c8a811ca6ea9dac3293d6afa99c1b489e36c1969

**Comment by TZ122** [comment]
Sorry, opened up a bug report on this issue again as I did not see that I could continue to comment here after an issue was closed. Please see:

https://github.com/Zrips/Jobs/issues/1448
