### ISSUE TITLE
New placeholder (with PlaceholderAPI)

### ISSUE THREAD

**Issue by ZIIROX77** [Zrips/Jobs#1409]
This placeholder would display the progress bar to move to the next level of the job. 
![unknown](https://user-images.githubusercontent.com/72636099/156420740-39269d25-fc73-43be-8a01-6505f088311c.png)

The colors when the progress bar would be configurable. 
Exemple:
Progress completed: "§a" | Progress not completed: "§7"

The characters that are displayed would also be configurable.
Exemple:
displayCharacters: "|"

**Comment by Zrips** [comment]
51657e8b9a63e0895ee8eeacc95504d1135eb7ae
