### ISSUE TITLE
New Placeholders

### ISSUE THREAD

**Issue by Threshian** [Zrips/Jobs#1411]
Hi, it would be great to add two new placeholders for peoples who make menu with jobs placeholders.

Placeholder for the missing xp to the next level : %jobsr_user_missing%

It would be really cool to know and be able to use the placeholder of the progressbar of /jobs stats to be able to integrate it into a menu.
![javaw_MU9OWa4Nmn](https://user-images.githubusercontent.com/67510777/156588171-27c9c2e2-7b84-4ea1-9d52-7980e337825b.png)

**Comment by Zrips** [comment]
51657e8b9a63e0895ee8eeacc95504d1135eb7ae
a811f79b1df6ac9a0e61ac9ff2964caf2536ff30
