### ISSUE TITLE
Adding job level in title

### ISSUE THREAD

**Issue by yungaudi** [Zrips/Jobs#1413]
How do i ad d job level in the title next to the job

![Screenshot (1)](https://user-images.githubusercontent.com/101153482/157141025-21b56b40-c1c7-4e70-9d0f-84374714b588.png)

**Jobs version:** 
Newest
**Server Type (Spigot/Paper/etc):** 
Spigot
**Server Version (using `/ver`):** 
1.18.2

**Comment by Zrips** [comment]
Add {jobs} to your chat format manager plugin or enable modify-chat in general config file.
