### ISSUE TITLE
Boosted items combining in anvil

### ISSUE THREAD

**Issue by Threshian** [Zrips/Jobs#1415]
***Detailed description of the issue:** Hi, i just downloaded the lastest version of jobs who in the update said "Fix for issue relating to custom enchants" and i suppose that include boosteditems. But i still can enchant boosteditems in an anvil : 
https://www.youtube.com/watch?v=jgmFxHhLCQ0

---

**Jobs version:** 5.0.2.0

**Server Type (Spigot/Paper/etc):** Paper

**Server Version (using `/ver`):** 1.18.2 paper 237

**Comment by Threshian** [comment]
Up ?

**Comment by Zrips** [comment]
6822508631bb69cc6a88735dc8bd968fc2948b55
