### ISSUE TITLE
MythicMobs v5.0.1 no compatibility 

### ISSUE THREAD

**Issue by EugisOne** [Zrips/Jobs#1416]
I am trying to install the Mythicmobs plugin with the latest update and it does not recognize the new version of the plugin.
---
<Error>
```
"Your MythicMobs version is not supported by Jobs! Supported versions: 4.9.1+"
```

Jobs version: 5.0.2.0

Server Type : Paper 

Server Version : git-Paper-235 (MC: 1.18.2)

Relevant plugins : MythicsMobs v5.0.1-e876be12

**Comment by Momshroom** [comment]
I'm having the same issue with MythicMobs version 5.0.3-SNAPSHOT-06d9297c
on Paper git-Paper-259 (MC: 1.18.2)
and Jobs version 5.0.2.1

**Comment by Zrips** [comment]
a984589dce93d78176b0f42d470fa2783b44146e
