### ISSUE TITLE
[ERROR]: Jobs can not load MythicMobs.

### ISSUE THREAD

**Issue by ErythroCraft** [Zrips/Jobs#1419]
Hello

I downloaded the latest free build of MythicMobs but the console says your plugin doesn't support the current version.

**ERROR:**
[22:16:12] [Server thread/INFO]: Your MythicMobs version is not supported by Jobs! Supported versions: 4.9.1+

**Jobs version:  5.0.2.1** 
**Spigot version: (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT)**  **3462-Spigot-ffceeae-2c47af0**

**Relevant plugins:**
**MythicMobs version: 5.0.1-e876be12**

**Comment by ErythroCraft** [comment]
Reopened this issue because your plugin is not working properly with MythicMobs. 
Please update the dependencies.

**Comment by ErythroCraft** [comment]
Reopened this issue because your plugin is not working properly with MythicMobs. 
Please update the dependencies.

**Comment by Zrips** [comment]
Works perfectly fine with 5.0.4 free version and latest Jobs builds.
