### ISSUE TITLE
Can't see the penalty/bonus on the /jobs browse

### ISSUE THREAD

**Issue by Daxxas** [Zrips/Jobs#142]
Hello,

I can't see the penalty in the /jobs browse, and I don't know why.

Here is an before/after of someone joining a job : 
First screen : http://prntscr.com/h1x6jy
Second screen : http://prntscr.com/h1x6u1

My GeneralConfig.yml : https://hastebin.com/asetafaxej.bash

We can do see the 0.00% turning red in the job that the player join, but nothing else,

Best regards, aDaxxas

**Comment by Zrips** [comment]
If that penalty is really small, what you can expect when you have only one guy joining that job, then penalty will turn red, as its negative bonus, but you will still see it as 0% as its rouding up. You can change equation for this or just have more people joining jobs to see bonus/penalty
