### ISSUE TITLE
Jobs is throwing an error in console and is not starting

### ISSUE THREAD

**Issue by MoonCourier** [Zrips/Jobs#1421]
The plugin is not starting at all but before it was working, I've not moved anything I'm not sure what is causing the issue, i've also tried to do a clean install but same situation

####################
15.03 10:29:54 [Server] Server thread/INFO ------------- Jobs -------------
15.03 10:29:54 [Server] Server thread/INFO [PlaceholderAPI] Successfully registered expansion: jobsr [5.0.1.4]
15.03 10:29:54 [Server] Server thread/INFO PlaceholderAPI hooked.
15.03 10:29:54 [Server] Server thread/INFO Connected to database (SqLite)
15.03 10:29:55 [Server] Server thread/INFO Loaded 8 titles
15.03 10:29:55 [Server] Server thread/WARN java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.ConfigurationSection.get(String, Object)" because "section" is null
15.03 10:29:55 [Server] Server thread/WARN at org.bukkit.configuration.MemorySection.get(MemorySection.java:265)
15.03 10:29:55 [Server] Server thread/WARN at org.bukkit.configuration.MemorySection.get(MemorySection.java:230)
15.03 10:29:55 [Server] Server thread/WARN at org.bukkit.configuration.MemorySection.isString(MemorySection.java:335)
15.03 10:29:55 [Server] Server thread/WARN at com.gamingmesh.jobs.config.RestrictedBlockManager.load(RestrictedBlockManager.java:43)
15.03 10:29:55 [Server] Server thread/WARN at com.gamingmesh.jobs.config.GeneralConfigManager.reload(GeneralConfigManager.java:268)
15.03 10:29:55 [Server] Server thread/WARN at com.gamingmesh.jobs.Jobs.reload(Jobs.java:836)
15.03 10:29:55 [Server] Server thread/WARN at com.gamingmesh.jobs.Jobs.startup(Jobs.java:531)
15.03 10:29:55 [Server] Server thread/WARN at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:736)
15.03 10:29:55 [Server] Server thread/WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
15.03 10:29:55 [Server] Server thread/WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
15.03 10:29:55 [Server] Server thread/WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
15.03 10:29:55 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:525)
15.03 10:29:55 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:439)
15.03 10:29:55 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:612)
15.03 10:29:55 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414)
15.03 10:29:55 [Server] Server thread/WARN at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:262)
15.03 10:29:55 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:994)
15.03 10:29:55 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
15.03 10:29:55 [Server] Server thread/WARN at java.base/java.lang.Thread.run(Thread.java:833)15.03 10:29:54 [Server] Server thread/INFO ------------- Jobs -------------
15.03 10:29:54 [Server] Server thread/INFO [PlaceholderAPI] Successfully registered expansion: jobsr [5.0.1.4]
15.03 10:29:54 [Server] Server thread/INFO PlaceholderAPI hooked.
15.03 10:29:54 [Server] Server thread/INFO Connected to database (SqLite)
15.03 10:29:55 [Server] Server thread/INFO Loaded 8 titles
15.03 10:29:55 [Server] Server thread/WARN java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.ConfigurationSection.get(String, Object)" because "section" is null
15.03 10:29:55 [Server] Server thread/WARN at org.bukkit.configuration.MemorySection.get(MemorySection.java:265)
15.03 10:29:55 [Server] Server thread/WARN at org.bukkit.configuration.MemorySection.get(MemorySection.java:230)
15.03 10:29:55 [Server] Server thread/WARN at org.bukkit.configuration.MemorySection.isString(MemorySection.java:335)
15.03 10:29:55 [Server] Server thread/WARN at com.gamingmesh.jobs.config.RestrictedBlockManager.load(RestrictedBlockManager.java:43)
15.03 10:29:55 [Server] Server thread/WARN at com.gamingmesh.jobs.config.GeneralConfigManager.reload(GeneralConfigManager.java:268)
15.03 10:29:55 [Server] Server thread/WARN at com.gamingmesh.jobs.Jobs.reload(Jobs.java:836)
15.03 10:29:55 [Server] Server thread/WARN at com.gamingmesh.jobs.Jobs.startup(Jobs.java:531)
15.03 10:29:55 [Server] Server thread/WARN at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:736)
15.03 10:29:55 [Server] Server thread/WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
15.03 10:29:55 [Server] Server thread/WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
15.03 10:29:55 [Server] Server thread/WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
15.03 10:29:55 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:525)
15.03 10:29:55 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:439)
15.03 10:29:55 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:612)
15.03 10:29:55 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414)
15.03 10:29:55 [Server] Server thread/WARN at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:262)
15.03 10:29:55 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:994)
15.03 10:29:55 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
15.03 10:29:55 [Server] Server thread/WARN at java.base/java.lang.Thread.run(Thread.java:833)
####################

Jobs version:
[5.0.1.4
Server Type (Spigot/Paper/etc):
Paper
Server Version (using /ver):
1.18.1

**Comment by Zrips** [comment]
Update Jobs to latest build including CMILib and Paper spigot and this error should go away.
