### ISSUE TITLE
NoSuchMethodError in Jobs.java:169

### ISSUE THREAD

**Issue by ShortException** [Zrips/Jobs#1424]
***Detailed description of the issue: The Plugin isn't starting because spigot says it isn't up to date**

---

Error: 
https://www.toptal.com/developers/hastebin/asipoyawiv.yaml

---

Jobs Version: v2.12.0

**Server Type (Spigot/Paper/etc): Spigot** 

**Server Version (using `/ver`): 1.18.2**

**Comment by Zrips** [comment]
You have 2.12.0 version, latest one is at 5.0.2.2, so yes, its not up to date.
