### ISSUE TITLE
Jobs Reborn issue

### ISSUE THREAD

**Issue by Fersteax** [Zrips/Jobs#1425]
Greetings. I get no money and xp if i do my jobs (craft, hunt, mine etc. after joining respective jobs) and cannot buy anything in the store without being opped. what permissions am i missing? Console: https://mclo.gs/pdYz1vM

**Comment by Zrips** [comment]
Mohist type server isint officially supported. But besides this, you dont need any special permission to get money for actions if you are performing actions which should be paying you. You should get action bar notification about payment and bossbar with indication of increase in exp. If none of those appear then plugin simply fails to detect your actions for one or another reason. With such limited information I cant really help out more than this.
