### ISSUE TITLE
Add permission node for job helppages

### ISSUE THREAD

**Issue by bluestormhunter** [Zrips/Jobs#1431]
**Description of new idea or improvement on existing one**
Currently entering /jobs will give users a 6 Page overview of every command the plugin supports. 
I would request moving these helppages to the command /jobs help and adding the permission node jobs.command.help. 
This way you can negate the permission and there wouldn't be an easy way to find bugs or glitches to abuse through commands.

I imagine the following commands to look like this:
/jobs
[Jobs] Subcommand required.
/jobs help
-------- ==== Jobs ==== -------
All 6 pages of those juicy commands
------- << Prev 1/6 Next >> -------

**Comment by Zrips** [comment]
help page is filled with commands you have access too. So regular player will only get ~3 pages of those by default while OP gets all 6. Its just convenience for players to know what they can actually use. There is no real need currently to separate any of those as its already separate by your personal access to those commands.
