### ISSUE TITLE
Stats not showing up correctly

### ISSUE THREAD

**Issue by trevor1097** [Zrips/Jobs#1433]
**Detailed description of the issue:**
Stats are now showing in a weird format and not on a new line for each jobs

![image](https://user-images.githubusercontent.com/7597614/162643691-db286f24-17b0-45a0-b92a-40a387bf139c.png)
---
**Version output:**

![image](https://user-images.githubusercontent.com/7597614/162643723-fa2f6336-bbee-40e5-bc91-9af1f9968881.png)

**Comment by Zrips** [comment]
c6438684fabdadd4e203602356ac7d2fa6d0f6ca
