### ISSUE TITLE
%jobsr_user_boost_(jname/number)_(money/exp/points)% doesn't work with all for job name

### ISSUE THREAD

**Issue by neokyle** [Zrips/Jobs#1435]
So when using the moneyboost command to give all jobs a money boost of 2x for example, the placeholder won't return anything.

%jobsr_user_boost_all_money% returns nothing

%jobsr_user_boost_miner_money% return 0.0

Jobs 5.0.2.1
Paper 216

**Comment by Zrips** [comment]
a50af311d0fa785365214be193307dfb2ff13e47
