### ISSUE TITLE
Players riding horses get explorer rewards for entering chunks they have already explored

### ISSUE THREAD

**Issue by MKieburtz** [Zrips/Jobs#1437]
**Detailed description of the issue:**
If a player is using the explorer job, and riding a horse, they will be granted job rewards for entering chunks that they have already explored. They are able to ride back and forth between two chunks and gain rewards each time. On foot the issue doesn't happen.
---

**Jobs version:** 5.0.2.1

**Server Type (Spigot/Paper/etc):** Paper

**Server Version (using `/ver`):** version git-Paper-287 (MC: 1.18.2)

**Comment by Zrips** [comment]
0fab1919808df499a5c15a0bc6091c59f0978a99
