### ISSUE TITLE
Jobs Reborn for Forge 1.12.2 ?

### ISSUE THREAD

**Issue by smmmadden** [Zrips/Jobs#144]
Hi @Zrips , I've been setting up additional servers running on Sponge Forge 1.12.2 and trying to get some of the plugins I've used for the Spigot servers also added as Mods for Forge.  Did you ever create a forge version of this?  Any plans to if you haven't?
Thanks -Steve

**Comment by Zrips** [comment]
Hey, in general i have 0 experience with moded servers. Most plugins are working with servers like that. But to make special support for it and add special features, well i don't have so much time to invest in stuff like this currently. I could fix some small compatibility issues, if there is any.

**Comment by smmmadden** [comment]
Thanks - I guess I'll need to find out from someone what the real difference is between them which I'm assuming is how classes are loaded or some meta data Forge expects that isn't there for Spigot.  I'll dig into that and go from there to see if there is something that's simple to do.
