### ISSUE TITLE
Near Spawner penalty not working correctly

### ISSUE THREAD

**Issue by SpeedManT** [Zrips/Jobs#1442]
***Detailed description of the issue:**

On our server players can get spawners and spawneggs from lootboxes, so we set permission **jobs.nearspawner.-0.98** to default group. Now players get 1/50 of base income for killing mob from spawner, thats correct. Problem starts, when players are using boost items, or at night, when we have scheduled night bonus +100% income. It seems like every bonus/penalty add up to final bonus. So at night we have -98% near spawner and +100% night bonus, that equals +2%, so player get more than base income. But we want to have 98% of boosted income (200% of base income), thats 1/25 of base income.

I think equation for bonuses is now: 
_income **=** base income **x** sum of every bonuses_
But logically it should be: 
_income = base income **x** sum(scheduled bonuses, boost items, dynamic payment bonus, permission bonuses,...) **x** near spawner penalty_
Because this feature is for getting certain part of income for killing mob spawned naturaly, when you are near spawner, not just to decrease it "randomly" depending on other bonuses.

**Jobs version:** 
5.0.2.1
**Server Type (Spigot/Paper/etc):** 
Purpur
**Server Version (using `/ver`):** 
git-Purpur-1610 (MC: 1.18.2)

**Comment by Zrips** [comment]
I can add option to pick one of two behaviors here. Will default to old one. Look for multiply-boosted-extra-values in general config file with next update
b69a4f1397a79b7e2ddfaea2cafc434939106b72
