### ISSUE TITLE
Running /jobs stats for a player who doesn't exist hangs the server

### ISSUE THREAD

**Issue by MKieburtz** [Zrips/Jobs#1443]
**Detailed description of the issue:**
If a player runs `/jobs stats <player>` and inputs a player who has never joined the server (for example `/jobs stats p`), the server will hang and possibly crash on some servers. Although on mine I've only seen everybody who is online get kicked.
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
https://pastebin.com/JkgVHkfd

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
I don't think our configs are relevant, but let me know if you want them.

---

**Jobs version:** 5.0.2.1

**Server Type (Spigot/Paper/etc):** Paper 

**Server Version (using `/ver`):** git-Paper-313 (MC: 1.18.2)

**Comment by Zrips** [comment]
2689a69c78b0e0089c8ea0496a2b3526264d3df1
