### ISSUE TITLE
MyPet & Tamed Pet Pay Permission Not Working

### ISSUE THREAD

**Issue by TZ122** [Zrips/Jobs#1449]
Players with permission jobs.petpay.100 for ex. do not get money when their MyPet kills a MythicMob/Vanilla Mob

This also goes for Tamed Pets given the permission jobs.petpay players do not gain money when their tamed pet kills a MythicMob or Vanilla mob.

Jobs version: 5.0.3.0

Server Type: Purpur

Server Version (using /ver): Current: git-Purpur-1623 (MC: 1.18.2)*

Relevant plugins: Latest MyPet release

**Comment by Zrips** [comment]
3a2b60db896d1e3c866fa4f70dcd10fb9216e161
