### ISSUE TITLE
Jobs bonuses do not work correctly

### ISSUE THREAD

**Issue by Hordoss** [Zrips/Jobs#1451]
**Jobs bonuses whether exp or currency do not work correctly. some do not earn anything more while others do.
I saw that leaving a job and coming back to it made the bonus work again but if a player already has a profession, he will not be able to benefit from bonuses**

**Jobs version: 5.0.2.1 : I saw that a new version was available but no fix related to this bug was declared in the patchnote** 

**Server Type : Paper** 

**Server Version : 1.18.1**

**Comment by Zrips** [comment]
There are multiple bonuses in game, you need to be allot more specific here. And screenshot from /jobs bonus command would be nice to see if bonus is actually detected for the players in this command. There is simply not enough information to work on here.
