### ISSUE TITLE
"Payments from ... got disabled" spam in chat

### ISSUE THREAD

**Issue by Folas1337** [Zrips/Jobs#1452]
***Detailed description of the issue:**
When an item gets moved from one container (like an oven or a brewing stand) to another you get a message telling you that "Payments from Brewing Stand got disabled"
https://gyazo.com/484aa8209179a35f255423517bd4cd06

---

**Jobs version:** 
5.0.3.0

**Server Type (Spigot/Paper/etc):** 
Paper

**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-357 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: f210f67)
You are running the latest version
Previous version: git-Paper-352 (MC: 1.18.2)

**Relevant plugins (Delete if this isn't needed):**
Vault version 1.7.3-b131

**Comment by Zrips** [comment]
6dd5ff0907a97192be5de1f37b8700482276058f
