### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by uploadx10** [Zrips/Jobs#1454]
***Detailed description of the issue:**

Server crash

**ERROR (DELETE IF YOU HAVE NO ERROR):**
https://pastebin.com/X4uZFbtr

---

**Jobs version:** 5.0.3.0

**Server Type (Spigot/Paper/etc):** paper

**Server Version (using `/ver`):** 1.18.1

**Comment by Zrips** [comment]
Dropped connection with mysql database, you might want to keep that on your local server as your actual minecraft server or switch to sqlite

**Comment by uploadx10** [comment]
I use multiserver

**Comment by Zrips** [comment]
Where is your database located at? Same host as your minecraft servers or completely different one?

**Comment by uploadx10** [comment]
different host

**Comment by Zrips** [comment]
This can definitely be an issue if mysql connection drops for one or another reason, which can definitely happen when you have mysql somewhere else. I would strongly recommend to move to local storage.
