### ISSUE TITLE
Add %jobname% Placeholder to Actionbar Message

### ISSUE THREAD

**Issue by Pyario** [Zrips/Jobs#1463]
If you earn money/Xp in a job, the actionbar message comes up. I would like to have the placeholer %jobname% in this one so that the job name can also be displayed there like in the boss bar.

**Comment by Zrips** [comment]
Action bar message is batched, meaning that all payments in defined amount of time will be summed and displayed in action bar which on itself doesn't include job name as it can include more than one. Bossbar message works in different way and it can display multiple lines indicating which job exactly gained how much. Its not that its not possible to be added, but its not really workable with single text line at the moment.
