### ISSUE TITLE
JobsJoinEvent not cancelling

### ISSUE THREAD

**Issue by InsideIntel** [Zrips/Jobs#1466]
***Detailed description of the issue:**
I'm trying to cancel the jobs join event to make a join cooldown on jobs, but when i tried to do this, the event wasn't actually getting cancelled. It seems to be only from JobsJoinEvent, JobsLeaveEvent works fine, but cancelling JobsJoinEvent doesn't seem to work.
@EventHandler
    public void onJobsJoin(JobsJoinEvent event) {
        event.setCancelled(true);

    }
---

**Jobs version:5.0.1.4** 

**Server Type (Spigot/Paper/etc):Paper** 

**Server Version (using `/ver`):1.18.2**

**Comment by InsideIntel** [comment]
bump

**Comment by Zrips** [comment]
f8d94952bdfdb5033fb8628b47b2ad67e41da770
