### ISSUE TITLE
Config option to check for which armor slot a boosted item is in

### ISSUE THREAD

**Issue by neokyle** [Zrips/Jobs#1467]
Boosted items work regardless of armor slot placement, so for example I have a chestplate which is better than other items. Players can glitch a chestplate onto there legs, head and feet and wear 4 chest plates receiving the boost for all of them.

This can also be problematic if you have boosted weapons and tools and enable main hand and off hand in the config, players can just hold a chestplate or any boosted armor piece in their offhand and receive the boost even though they aren't wearing it.

Adding a config option for weather or not the plugin should only apply the boost if the armor piece or item is in the correct spot would fix this issue and give more control over boosted items.

**Comment by Zrips** [comment]
c1675cf9281e6cbefa8509e29f08ba62b9c6eb33
