### ISSUE TITLE
Jobname.yml constantly reapears when restarting server.

### ISSUE THREAD

**Issue by Thomas-Lecuppre** [Zrips/Jobs#1468]
Hi, I don't if it is a bug are not but when I try to delete some insertyourjobname.yml (because I don't want it to my server) it always reapears when restarting my server.

I have tried to find in config file a parameter or an array of job name list to remove these but nothing.

Jobs version: Jobs5.1.0.0

Server Type (Spigot/Paper/etc): purpur-1.19-1685

Server Version (using `/ver`): 1.19 

Relevant plugins (Delete if this isn't needed): Chunky, CoreProtect, DeathMessage, EssentialsX, EssentialXChat, EssentialsXDiscord, EssentialsXSpawn, FastAsyncWorldEdit, HolographicDisplays, Lands, LuckPerms, Multiverse-Core, Multiverse NetherPortals, PlayerKits, PsudoCommands, QuickShop, Sentinel, SuperVanish, TimeIsMoney, Vault, Worldguard, XConomy.

**Comment by dragontekgaming** [comment]
Out of curiosity, are you stopping the server, deleting the file, then restarting? Or are you deleting the file while the server is running?

**Comment by Zrips** [comment]
Generally speaking example job files are only created if there isint sub folder with name "jobs" in any other case it gets ignored even if you keep that folder completely empty.
