### ISSUE TITLE
JobsJoinEvent issue

### ISSUE THREAD

**Issue by InsideIntel** [Zrips/Jobs#1473]
***Detailed description of the issue:**
I'm trying to cancel the jobs join event to make a join cooldown on jobs, but when I tried to do this, the event wasn't actually getting cancelled. It seems to be only from JobsJoinEvent, JobsLeaveEvent works fine, but cancelling JobsJoinEvent doesn't seem to work.

**Jobs version:** 5.1.0.0

**Server Type (Spigot/Paper/etc):** Purpur
This also doesn't work with paper/spigot either, have tested all 3
**Server Version (using `/ver`):** git-Purpur-1612 (MC: 1.18.2)

**Comment by Zrips** [comment]
f8d94952bdfdb5033fb8628b47b2ad67e41da770
