### ISSUE TITLE
Quests progress mistmatch

### ISSUE THREAD

**Issue by Cruwzky** [Zrips/Jobs#1474]
***Detailed description of the issue:**

Sometimes the quests progress is not showing correctly for the players. The progress bar itself in /jobs quests is correct but the numbers shown then hovering the quest is not. See the screenshots.
---

**Jobs version: 5.1.0.0** 

**Server Type (Spigot/Paper/etc): Purpur** 

**Server Version (using `/ver`): git-purpur-1708 (MC: 1.19)** 

![image](https://user-images.githubusercontent.com/20445289/180093615-476bf2dd-8065-499e-a965-3780405ae973.png)

![image](https://user-images.githubusercontent.com/20445289/180093623-92f71e28-685f-4a4b-b8e2-3a3a70924f3a.png)

**Comment by Zrips** [comment]
7c7b269e7d1e1d05a3521c58693fb84eca2310af
