### ISSUE TITLE
Craft action doesn't count item amounts

### ISSUE THREAD

**Issue by erkutay07** [Zrips/Jobs#1476]
***Detailed description of the issue:**
https://www.youtube.com/watch?v=fRUz5P5tJXU
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  Quests:
    1:
      Name: "Kitap Üret"
      Objectives:
      - Craft;BOOK;8
      RewardCommands:
      - "jobs grantxp [playerName] magic 50"
    2:
      Name: "Kitap Üret"
      Objectives:
      - Craft;BOOK;16
      RewardCommands:
      - "jobs grantxp [playerName] magic 50"
    3:
      Name: "Kitap Üret"
      Objectives:
      - Craft;BOOK;24
      RewardCommands:
      - "jobs grantxp [playerName] magic 50"
```

---

**Jobs version:**  5.1.0.0

**Server Type (Spigot/Paper/etc):**  paper

**Server Version (using `/ver`):**  paper-387 1.18.2

**Comment by Zrips** [comment]
Check generalconfig file and enable PayForEachCraft, this is disabled by default as it can introduce some issues with crafting balancing where players would start batch crafting insane amounts of items making crap tone of revenue, so its better to keep it disabled by default and if some one wants to play with that and understands risks, then they can enable it.
