### ISSUE TITLE
People cant enchant items from the shop

### ISSUE THREAD

**Issue by MADS0LADEN** [Zrips/Jobs#1477]
**Detailed description of the issue:**
Players can buy a trident without enchantments from the shop but they can not combine it with enchanted books.
They can enchant the item in a enchantment table but not put enchanted books on it.

It works fine if I remove the plugin, then I can put enchanted books on the trident

It has the NBT tag "JobsItemBoost"

---

**Jobs version:** 
5.1.0.0
**Server Type (Spigot/Paper/etc):** 
Purpur
**Server Version (using `/ver`):** 
Purpur 1.19-1732

**Comment by Zrips** [comment]
b9f5b40b4676d3a425790a6cc81eaab989d09b5c
