### ISSUE TITLE
Jobs generated an exception while executing task

### ISSUE THREAD

**Issue by SirKillian** [Zrips/Jobs#1479]
Console error, can't forcefully replicate.
---

**ERROR:**
```
https://paste.helpch.at/uvibaqetaf.log
```

---

**Jobs version:**  5.1.0.0
**Server Type (Spigot/Paper/etc):**  Paper
**Server Version (using `/ver`):**  1.19 paper build cd215af (61)

**Comment by Zrips** [comment]
dfab76b2737d2b0eab134dfc662cac7a1e3a6816
