### ISSUE TITLE
Traduction for Tipped arrow effect

### ISSUE THREAD

**Issue by nicolas1920** [Zrips/Jobs#1480]
Hello , 

That can be cool to add possibility  edit  in french  all Tipped arrow effect 
![unknown](https://user-images.githubusercontent.com/78266223/180914932-e1cdd4a0-6b07-46af-91ae-a28c980b6246.png)

**Comment by Zrips** [comment]
2056525a16abe8a083cc5b90fb3268ff43e24e9d
