### ISSUE TITLE
Color is broken

### ISSUE THREAD

**Issue by HEMO313** [Zrips/Jobs#1481]
***Detailed description of the issue:**

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
<-- Try to use pastebin.com server if you have long error. -->
```
####################
## PASTE ERROR HERE ##
####################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Jobs version:** 

**Server Type (Spigot/Paper/etc):** 

**Server Version (using `/ver`):** 

**Relevant plugins (Delete if this isn't needed):**

![image](https://user-images.githubusercontent.com/39499245/181063411-eb95bd55-927f-4c49-a400-aae31b423f44.png)

**Comment by Zrips** [comment]
You might want to double check if you are using correct & symbol in config file, but this report is lacking basic information in general. Some example of a config file which was not working would help out to debug. As of basic testing everything seams to be working correctly at the moment.
