### ISSUE TITLE
jobs.maxquest.all permission

### ISSUE THREAD

**Issue by nolberh2** [Zrips/Jobs#1484]
***Detailed description of the issue:**

the permissions
jobs.maxquest.[jobName].[number]
jobs.maxquest.all.[number] 

This permission does not work at all, how can I make it work?

Even if I set higher or lower value in the jobs folder it does not add more jobs to the player with the permission. 

**Jobs version:** 5.1.0.0

**Server Type (Spigot/Paper/etc):** Paper

**Server Version (using `/ver`):** 1.17, 1.18, 1.19

**Comment by Zrips** [comment]
0964e5b32b6f535f7271080078e1620ff7807bae

**Comment by nolberh2** [comment]
I don't know what to do with a commit

**Comment by nolberh2** [comment]
i have seen the update in spigot and it includes this, thanks
