### ISSUE TITLE
Quest - Sheer: Colored Sheep not counting

### ISSUE THREAD

**Issue by th3lucas** [Zrips/Jobs#1485]
Quest: Sheeps are not getting counted properly when you sheer them. Example in the Screenshot.

<img width="600" alt="image" src="https://user-images.githubusercontent.com/96976624/182687417-d55ff4fb-9d5e-410b-962a-92979171cd9a.png">

```
Config File of the job
https://paste-bin.xyz/72626

---

**Jobs version:** 5.1.0.0

**Server Type (Spigot/Paper/etc):** Paper

**Server Version (using `/ver`):** 
git-Paper-81 (MC 1.19) 
latest version atm

**Comment by Zrips** [comment]
Using your example job **#12 Farbige Wolle** got correct results where shearing specific color sheep counts towards specific requirement based on that color. 
![image](https://user-images.githubusercontent.com/10416201/183380468-68375a9b-19f5-487e-928c-2c21e182183a.png)
Do you get appropriate payments for shearing specific colors of sheep?

**Comment by th3lucas** [comment]
Do you get appropriate payments for shearing specific colors of sheep?
-> Yes, i do.

As you see in my example the sheep itself get counted, but not displayed which color you already have.

**Comment by th3lucas** [comment]
It works now (idk how but i take it)
