### ISSUE TITLE
MySQL does not connect with my Database

### ISSUE THREAD

**Issue by Sailingjulia** [Zrips/Jobs#1486]
***Detailed description of the issue:**
When I reload or restart the Server the MySQL database will not connect even when I delete the Database and create a new one
---

####################
####################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
#####################################
```

---

**Jobs version:** 
Jobs5.1.0.0
**Server Type (Spigot/Paper/etc):** 
Paper
**Server Version (using `/ver`):** 
1.18,2

**Comment by Zrips** [comment]
b1a4e64288a4c3b009a1cf11543194b016866de4
