### ISSUE TITLE
dye section miss default messages_en.yml

### ISSUE THREAD

**Issue by andris155** [Zrips/Jobs#15]

**Comment by Zrips** [comment]
Its not missing, its self generating from plugin itself

**Comment by andris155** [comment]
Not found default messages_en.yml:
dye:
info: Dye
none: '%jobname% does not get money from dyeing.'

**Comment by Zrips** [comment]
och ok, miss understood issue, i will include it in next update

**Comment by andris155** [comment]
Fixed
