### ISSUE TITLE
Cannot invoke because the return value of "com.gamingmesh.jobs.config.YmlMaker.getConfig()" is null

### ISSUE THREAD

**Issue by drnosstv** [Zrips/Jobs#1510]
[WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.file.FileConfiguration.getConfigurationSection(String)" because the return value of "com.gamingmesh.jobs.config.YmlMaker.getConfig()" is null
>.... [WARN]: at Jobs5.1.0.1.jar//com.gamingmesh.jobs.config.ConfigManager.reload(ConfigManager.java:957)
>.... [WARN]: at Jobs5.1.0.1.jar//com.gamingmesh.jobs.Jobs.reload(Jobs.java:834)
>.... [WARN]: at Jobs5.1.0.1.jar//com.gamingmesh.jobs.Jobs.startup(Jobs.java:536)
>.... [WARN]: at Jobs5.1.0.1.jar//com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:741)
>.... [WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
>.... [WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
>.... [WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536)
>.... [WARN]: at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563)
>.... [WARN]: at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477)
>.... [WARN]: at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633)
>.... [WARN]: at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419)
>.... [WARN]: at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:306)
>.... [WARN]: at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1121)
>.... [WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302)
>.... [WARN]: at java.base/java.lang.Thread.run(Thread.java:833)
>.... [INFO]: [Jobs] [STDOUT] There was some issues when starting plugin. Please contact dev about this. Plugin will be disabled.
>.... [WARN]: Nag author(s): '[Zrips]' of 'Jobs' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger)..lugin#getLogger)..

Jobs Version: 5.1.0 1

Server Type: Paper

Server Version: git-Paper-51 (MC: 1.19)

**Comment by Zrips** [comment]
Most likely issue with one of the config files beings misformatted.
