### ISSUE TITLE
Negative values on jobs

### ISSUE THREAD

**Issue by doitliketyler** [Zrips/Jobs#1511]
***Detailed description of the issue:**
My players are seeing negative values and loosing xp when completing job actions. I've tried to figure out what is causing this but am at a lose. I've checked all the obvious things like config and permissions and such but there is nothing I can see. Here is a screenshot of what they are seeing: https://imgur.com/a/eydefnn

I've shared an example of the Miner job I'm using below. Any idea why this would would happen and how to fix it? Thanks in advance

**Jobs version: 5.1.0.1

**Server Type (Spigot/Paper/etc): Paper 

**Server Version (using `/ver`): 1.19.2

**Comment by doitliketyler** [comment]
Closing this as I've found what was causing the issue.

**Comment by Phantom466** [comment]
@tylerking I'm having the same issue, could you share how you resolved it?
