### ISSUE TITLE
Placeholder for "none"-Jobs not working

### ISSUE THREAD

**Issue by AnimeDrache** [Zrips/Jobs#1514]
***Detailed description of the issue:**
The **%jobsr_user_jobs%** placeholder does show all jobs but the "none" one (so when you have no job it wont show the name you setup for "none")
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
<-- Try to use pastebin.com server if you have long error. -->
```
####################
## PASTE ERROR HERE ##
####################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Jobs version:** 
5.1.0.1 SLite
**Server Type (Spigot/Paper/etc):** 
Paper
**Server Version (using `/ver`):** 
paper-1.19.2-210.jar
**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
f0d6576c77912d16bf89399b95063aa3af2c9b07
