### ISSUE TITLE
Autojoin feature ignores max jobs limit

### ISSUE THREAD

**Issue by AlexanderMoebius** [Zrips/Jobs#1515]
***Detailed description of the issue:**
The auto join feature ignores the maximum number of jobs al player is allowed to have.
Because of this players can leave the jobs they auto joined into, take other jobs and be reassigned to the auto join-jobs.
Therefore players can have more jobs than they are allowed to have.

---

**Jobs version:** 
5.1.0.1

**Server Type and Version:** 
Paper 1.19.2 - 232

**Comment by Zrips** [comment]
bf064408114bcc6467c53ccd280fa563f1fc4d67
