### ISSUE TITLE
Option to add custom skulls to the shop

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/Jobs#152]
Custom Heads are everwhere nowadays. They add a sweet little detail to your buildings and player love the get them as a reward. So please add a possibility to add custom skulls to the shop menu. Basically you need to add a base64-line in the config so one can add a skull to the shop menu using the texture-value.

**Comment by TheoRetisch1** [comment]
I am still highly interested in this feature. What does the label open to PR means?

**Comment by montlikadani** [comment]
PR means that Pull Request suggests a feature or something to the plugin, such as this, but it needs to be encrypted to work. We will do it or somebody else will.
