### ISSUE TITLE
The plugin has a small memory leak

### ISSUE THREAD

**Issue by DimaSergeew** [Zrips/Jobs#1524]
***Detailed description of the issue:**
As can be seen in the screenshot below, there are problems with the fact that the plugin accumulates memory but does not clear it and so I have to restart the server every day. Other developers have already fixed the problem only Jobs is left

**Jobs version:** 

[15:25:53 INFO]: Jobs: 5.1.0.1 SqLite
[15:25:53 INFO]: CMILib: 1.2.3.7
[15:25:53 INFO]: Server: Purpur 1.19.2-R0.1-SNAPSHOT
[15:25:53 INFO]: Economy: CMIEconomy Vault: 1.7.3-CMI

**Server Type (Spigot/Paper/etc):** 
PurPur

**Server Version (using `/ver`):** 

[15:26:12 INFO]: Version Server: Purpur 1.19.2-R0.1-SNAPSHOT
![unknown](https://user-images.githubusercontent.com/75163645/201091436-7b24645d-7af8-4d23-ae25-b0ee98cfe0f3.png)

**Comment by itsTyrion** [comment]
What did you use for that overview?

**Comment by DimaSergeew** [comment]
> What did you use for that overview?

eclipese memory analizer

**Comment by Zrips** [comment]
b79b8a1e9d133cb7292f9e5cc3c815e4c283ca58
