### ISSUE TITLE
Support the multipe stages of the nether wart

### ISSUE THREAD

**Issue by Daxxas** [Zrips/Jobs#154]
Hello,

I saw that with the /jobs blockinfo, the netherwart at its last stage and at its first stage have the same ids
The `NETHER_WARTS-3` doesn't work :(

**Comment by montlikadani** [comment]
@Daxxas 
The /jobs blockinfo command only supports blocks. _Items not supported._
http://minecraft-ids.grahamedgecombe.com/

**Comment by montlikadani** [comment]
You can find it the all materials here: https://github.com/Zrips/Jobs/blob/master/src/main/java/com/gamingmesh/jobs/CMILib/ItemManager.java#L1129
