### ISSUE TITLE
Jobs playerinfo doesn't work for unlearned archive jobs

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/Jobs#1548]
***Detailed description of the issue:**
The command `/jobs playerinfo <player> <job>` doesn't work for unlearned jobs: It used to show the earnings related to the `/jobs archive` level. Currently, the jobs archive level for the job is ignored and for unlearned professions the info for level 1 is always displayed.

---

**Jobs version:** 
5.1.1.1
**Server Type (Spigot/Paper/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper-368 (MC: 1.19.3)
**Relevant plugins (Delete if this isn't needed):**
1.2.4.1

**Comment by Zrips** [comment]
Can't recall when it was showing stats from archived jobs, but well, I can add that.
e6c476f756ae6823bfab7ef31270fcc4ec8ec12a

**Comment by TheoRetisch1** [comment]
Thanks! 🎉
