### ISSUE TITLE
Auto join jobs feature doesn't work

### ISSUE THREAD

**Issue by GodDirtman** [Zrips/Jobs#1549]
***Detailed description of the issue:**
Auto join jobs feature doesn't work. After experiencing the issue on my live server, I've set up a testing server - new, clean Paper instance with just Jobs, CMILib and LuckPerms installed. 

I've enabled `AutoJobJoin` in the config and given the default rank permission `jobs.autojoin.explorer`. Then I removed OP from myself, stopped the server, and deleted Jobs' SQLite file and other user cache files from the server. I started the server back and didn't get the Explorer job. This also applies to the other jobs, as I have tested.

---

**Jobs version:** 
5.1.1.1

**Server Type (Spigot/Paper/etc):** 
Paper

**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)

**Comment by Zrips** [comment]
As of testing, there seems to not be an issue with auto join feature. Make sure that player actually has this permission node when timer runs out

**Comment by GodDirtman** [comment]
After further testing, I think I found where the problem lies.

It's an issue with the `max-jobs`. Setting it to `0` should disable the maximum amount of jobs a player can join, according to the information in the config.

This hoverer breaks the auto-join feature. When I set this to a positive number, auto-join worked. 

---
Tested on the latest Jobs version - 5.1.2.0.

**Comment by comonier** [comment]
give it permissions if you want everyone have all jobs
```yaml
    - jobs.autojoin.farmer
    - jobs.autojoin.digger
    - jobs.autojoin.weaponsmith
    - jobs.autojoin.explorer
    - jobs.autojoin.brewer
    - jobs.autojoin.fisherman
    - jobs.autojoin.woodcutter
    - jobs.autojoin.hunter
    - jobs.autojoin.crafter
    - jobs.autojoin.builder
    - jobs.autojoin.miner
    - jobs.autojoin.enchanter
    - jobs.use
    - jobs.world.world
    - jobs.world.world_nether
    - jobs.world_world_the_end
    - jobs.max.12
    ```

**Comment by Zrips** [comment]
Well if you have set max jobs to a number which will be lower than amount of players jobs, then well, it will do what it should do, simply not auto join job. Don't know if we should consider overriding jobs amount limitations on autojoin. Closing ticket for now.
