### ISSUE TITLE
Website URL takes you to a page not found

### ISSUE THREAD

**Issue by Bushpeng** [Zrips/Jobs#1551]
***Detailed description of the issue:**
https://www.zrips.net/jobs/ has the job example, but the site:

https://github.com/Zrips/Jobs/blob/master/src/main/resources/jobConfig.yml
has a 404 error. The correct URL is:
https://github.com/Zrips/Jobs/blob/master/src/main/resources/jobs/_EXAMPLE.yml

The website needs an update :)

---
No additional information filled out because it's a website error.
---

**Jobs version:** 

**Server Type (Spigot/Paper/etc):** 

**Server Version (using `/ver`):**

**Comment by mrfloris** [comment]
Hey there, thank you for reporting. I've updated the URL on the website.
