### ISSUE TITLE
Placeholder %jobsr_user_jtoplvl_jobName_1% don't parse

### ISSUE THREAD

**Issue by RenardFarceur** [Zrips/Jobs#1553]
***Detailed description of the issue:**

---I use the placeholder %jobsr_user_jtoplvl_jobName_1% or 2_3_4... to make a leaderboard per job on my spawn. I use Decent Holograms plugin to make my holograms. Every placeholders looks to parse. Even when I try to make /jobs placeholders parse ... It don't give any return of this placeholder. Could you fix this ? (When I use the internal classement of Jobs (parsed on scoreboard) it works perfectly ! 
I have no errors in my console & no error on starting.

**Jobs version:5.1.2** 

**Server Type (Spigot/Paper/etc):Paper 1.18.2-388 ** 

**Server Version (using `/ver`):1.18.2** 

**Relevant plugins (Delete if this isn't needed): DecentHolograms-2.7.9.jar**
                                                                       ProtocolLib : Last Update

**Comment by Zrips** [comment]
%jobsr_user_jtoplvl_jobName_1% placeholder was... broken, to put it lightly. Reworked it and made it actually working, now it will be as %jobsr_jtop_name_[jobName/number]_[1-15]% which will provide player name by provided job name and place in the top list. Additionally new %jobsr_jtop_level_[jobName/number]_[1-15]% will be added to provide level.
2fd03a4384bf2204cc4ef4c04cda07e089f7457e
