### ISSUE TITLE
Accumulate permission boosts !

### ISSUE THREAD

**Issue by Darkseno** [Zrips/Jobs#1557]
**Description of new idea or improvement on existing one**

Hello,

My request is quite simple.

On my server I have a rank that gives +50% bonus and I would like to add a VIP Pass that gives the same thing except that it is impossible to add them together.

I'd like to make this possible, I didn't know it wasn't and I'm being harassed by my players.

**Detailed information what should do**

**Comment by Zrips** [comment]
4d11d4ef03c180bf0660c46e9c8d4167126b0097

**Comment by Darkseno** [comment]
> [4d11d4e](https://github.com/Zrips/Jobs/commit/4d11d4ef03c180bf0660c46e9c8d4167126b0097)

I don't really understand what this has to do with my request?
