### ISSUE TITLE
Eco and Jobs Reborn Money doesnt work

### ISSUE THREAD

**Issue by Sereax** [Zrips/Jobs#1561]
Hello,
im running a Minecraft Spigot Server on 1.19.2. I have installed the Essentials, Jobs Reborn and the Vault Plugin. Also both Plugins (Essentials and Jobs Reborn) are hooked in Vault but the money doesnt match together. 
If I look in /jobs shop. It says i have not enough money. Any one has an Idea? All Plugins are up to date.

This is what I got with /money
![image](https://user-images.githubusercontent.com/124920441/217907650-d8616699-77ec-4da5-bd78-02bf3b57264e.png)

In /jobs shop it says I have only 15482 and I cant buy this item
![image](https://user-images.githubusercontent.com/124920441/217907735-89bd017a-b261-43e8-a8d1-7f956bdafc7a.png)

Is that a Bug only in Spigot 1.19.2? I tried everything but nothing worked for me... 

Here is the log:
[latest_log.zip](https://github.com/Zrips/Jobs/files/10700520/latest_log.zip)

**Comment by Zrips** [comment]
This might have been unclear in config file but jobs shop is used to buy items with jobs points and not Vault money which are separate one from the other. Will add support for regular vault currency with next update.
2165e1fe685e2fe905b6da73382d6f62d0de2e49
