### ISSUE TITLE
/jobs clearownership - No permissions and still runs

### ISSUE THREAD

**Issue by Lightkeks** [Zrips/Jobs#1563]
***Detailed description of the issue:***
When having permssions like OP, the command "/jobs clearownership" is executed correctly. If you have no permission for the command, the command show's "You don't have permission" and still show up the successfull removal.

---
####################
####################

```
https://imgur.com/a/rlWeIPH
```
---
**Jobs version:** 
5.1.2.0

**Server Type (Spigot/Paper/etc):** 
PaperMC 1.19.3

**Server Version (using `/ver`):**
git-Paper-399 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: f2f9e8c)

**Comment by Zrips** [comment]
Permission check is done way before actual command will be executed and if you see error about missing permission there should not be any way for it to continue performing command itself. 
Do you have any special setup for it? And just keep in mind that player gets access to this command by default and you will need to negate appropriate permission node to prevent its usage. And you can hover over that error message to double check which permission node is actually required there as it could be from different command entirely.

**Comment by Lightkeks** [comment]
Okay, as I can see now, there is a node showing up, thats true. Still if you use the command with a username at the end as variable AND without permissions set, the command is still executed even not having permissions set.

So it show's up "You don't have permission!" AND the actual command execution.

**Comment by Zrips** [comment]
Och ok, it looks to be issue with jobs.command.admin.clearownership permission check, will make some adjustments to avoid this confusion and inconsistency.
bd430b3cd7970d03c0839449eb0edc1568f038fa
