### ISSUE TITLE
Console Spam in 5.1.2.1

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/Jobs#1564]
***Detailed description of the issue:**

Major console spam in Jobs 5.1.2.1. Console is just all this every time someone places a block and players don't seem to be getting paid. Rolling back to 5.1.2.0 solves the issue.
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
https://gist.github.com/mercurialmusic/fb806be2c839523e31def70162dfcb83

---

**Jobs version:** 5.1.2.1

**Server Type (Spigot/Paper/etc):** Paper

**Server Version (using `/ver`):** git-Paper-403 (MC: 1.19.3)

**Comment by Zrips** [comment]
Posted new version which should resolve this error message

**Comment by mercurialmusic** [comment]
Thank you!
