### ISSUE TITLE
Create a new job

### ISSUE THREAD

**Issue by Baikele** [Zrips/Jobs#1565]
**Description of new idea or improvement on existing one**
I want to use other plugins as a front, create a new job
**Detailed information what should do**
I want to use other plugins as a front, create a new job

**Comment by Zrips** [comment]
Those plugins can use existing API to create new jobs, even basic creation of new jobs file and initiating /josb reload would achieve that. Duno what is missing for this to be possible.

**Comment by Baikele** [comment]
I want to create a job for a third-party plugin, but I don't know how, the api doesn't seem to mention

**Comment by Baikele** [comment]
I want to create a job for a third-party plugin, but I don't know how, the api doesn't seem to mention

**Comment by Baikele** [comment]
I want to create a job for a third-party plugin, but I don't know how, the api doesn't seem to mention

**Comment by Baikele** [comment]
> Those plugins can use existing API to create new jobs, even basic creation of new jobs file and initiating /josb reload would achieve that. Duno what is missing for this to be possible.

I want to create a job for a third-party plugin, but I don't know how, the api doesn't seem to mention
