### ISSUE TITLE
Add ResetTime to reset at 0:00 every day

### ISSUE THREAD

**Issue by SheerYin** [Zrips/Jobs#1573]
for example
Trigger the limit at 8:00, then he will have 24-8=16, 16 hour limit
Trigger the limit at 16:00, then he will have 24-16=8, 8 hours limit

**Comment by Jackboittv** [comment]
Hell yeah

**Comment by Zrips** [comment]
3bfb0f60cc05be7e51fd3964ec27d9b30a80bc49
