### ISSUE TITLE
Farming job not paying for melons, pumpkins, and sugar cane.

### ISSUE THREAD

**Issue by monochrome-blue** [Zrips/Jobs#158]
I've noticed, using the 4.2.1 version of jobs, that players aren't getting paid for pumpkins, melons and jobs. It seems like they pay the first time after being planted, but after being harvested once, won't pay anymore.

**Comment by MilesBHuff** [comment]
We seem to be having this issue, as well, but just with pumpkins and melons.

**Comment by Oxta31** [comment]
Same issue, just with pumpkins and melons.
