### ISSUE TITLE
/jobs:jobs command doesnt work

### ISSUE THREAD

**Issue by ItsVaidas** [Zrips/Jobs#1586]
***Detailed description of the issue:**
When trying to launch the command /jobs:jobs join, it doesn't show anything. /jobs yea, it works, but so do /jobs:jobs should.

**Jobs version:** 5.1.2.2

**Server Type (Spigot/Paper/etc):** PurPur

**Server Version (using `/ver`):** 
Current: git-Purpur-1916 (MC: 1.19.3)*
Previous: git-Purpur-1933 (MC: 1.19.3)
* You are 17 version(s) behind
Download the new version at: https://purpurmc.org/downloads

**Comment by Zrips** [comment]
Would suggest to check any plugin which would disable double commands like that one as by default Jobs will not do anything about commands like that and will perform as usual.

**Comment by ItsVaidas** [comment]
Then is there a way to make /jobs to open /jobs browse or /jobs join GUI? 
I had an idea to do it with MyCommands by using /jobs:jobs join run as player. 
How will the logic work with /jobs:jobs disabled?

Do I need to create a separate plug-in for this functionality?

**Comment by Zrips** [comment]
Go to generalConfig file and near bottom you will see Commands section where you can define what should happen when you perform clean /jobs command which can open browse window or you can define your own command.
