### ISSUE TITLE
Multiple identical actions within 45ms of eachother do not fire a JobsPrePaymentEvent

### ISSUE THREAD

**Issue by ks-hl** [Zrips/Jobs#1587]
**Detailed description of the issue:**

Rapid successive actions will intermittently not fire a JobsPrePaymentEvent, for instance, breaking dirt or sand quickly. This leads to plugins which depend on this event getting incomplete data.

**Jobs version:** 5.1.2.2

**Server Type (Spigot/Paper/etc):** Paper-504

**Server Version (using `/ver`):** 1.19.4

**Comment by Zrips** [comment]
Merged
