### ISSUE TITLE
use of getEffectivePermissions  is heavy

### ISSUE THREAD

**Issue by WarnDa** [Zrips/Jobs#1592]
***Detailed description of the issue:**
My LuckPerms was taking some ressources on spark, so I asked the dev and he told me a part of this was because of Jobs checking for permissions in a bad way that could be optimised : 
![image](https://user-images.githubusercontent.com/31826333/235350449-acb416d8-6bfb-4a23-bd9e-9da3768c9ae9.png)

here is the spark with 160 players online : https://spark.lucko.me/m3EsB6pXbh?hl=1584,1647,1680,8505,10394,10416,10477,10494,31125,31167,35511,35595,35622
![image](https://user-images.githubusercontent.com/31826333/235350472-6f9bb193-04ba-4578-a1fb-fb64bdd6aee0.png)

So if you could look to change the method used to check for the max permission, would be perfect

**Jobs version:** 
5.1.2.2
**Server Type (Spigot/Paper/etc):** 
PufferfishPus-44 1.19.3

**Relevant plugins (Delete if this isn't needed):**
LuckPerms

**Comment by Zrips** [comment]
86c94786cfb12f24068fd2303db31ce0ab78a0f9
