### ISSUE TITLE
StripLogs doesnt count towards quest progress

### ISSUE THREAD

**Issue by zDarkinhell** [Zrips/Jobs#1594]
I was writing some Woodcutter quests, one of them has this requirement:

StripLogs;oak_log;16

In the game menu (chat) the quest says the right material and right action (So it says Strip 16 oak logs), but whenever a player is stripping the log, it doesnt count towards the quest progression

**Jobs version:** 5.1.2.2

**Server Type (Spigot/Paper/etc):** Paper

**Server Version (using `/ver`):** 1.19.4

**Comment by zDarkinhell** [comment]
![image](https://user-images.githubusercontent.com/129414483/236024611-dba6967d-f762-4727-9c82-55b0371efbe8.png)

**Comment by Zrips** [comment]
You will need to define final block type for stripped blocks, in your case correct format would be 
`StripLogs;STRIPPED_OAK_LOG;16` in same way jobs actions for stripping logs will require you to define block type after stripping and not before.
