### ISSUE TITLE
Base config isn't giving for any ore money.

### ISSUE THREAD

**Issue by Dreandor** [Zrips/Jobs#1596]
***Detailed description of the issue:** Not every ore is giving money. In my case Iron and Copper are give money but no diamond ore

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Base config

---

**Jobs version:**  5.1.3.0


**Server Type (Spigot/Paper/etc):** Paper

**Server Version (using `/ver`):** git-Paper-519 (1.19.4)

**Relevant plugins (Delete if this isn't needed):** Essentials and Vault

**Comment by Zrips** [comment]
It all depends on your jobs setup, keep in mind that you might have block protection enabled which prevents from players being able to place and brake same block over and over again. Additionally players in creative will not receive payments by default. Other than this most common blocks should pay out by default, some newer ones might be needed to be added into jobs actions list.

**Comment by Dreandor** [comment]
I used the default config and checked all blocks. I could fix the wood job but diamond ores are not working with the default miner job.
