### ISSUE TITLE
bPermission

### ISSUE THREAD

**Issue by BellemareMederic** [Zrips/Jobs#16]
i try to give fly permission to some jobs and the permission is not take 

  Architecte:
    fullname: Architecte
    shortname: Ar
    description: Faite de largent en Construisent.
    ChatColour: WHITE
    chat-display: full
    leveling-progression-equation: 120_((1.13+(0.01_(numjobs-1)))^(joblevel-1))
    income-progression-equation: baseincome_((1.05)^(joblevel-1))
    experience-progression-equation: baseexperience_((1.05)^(joblevel-1))  
    Place:
      COBBLESTONE:
        income: 1.0
        experience: 1.0
      WOOD:
        income: 1.5
        experience: 1.5
      FENCE:
        income: 1.5
        experience: 1.5
      WOOL:
        income: 1.5
        experience: 1.5
      STONE:
        income: 1.5
        experience: 2.25
      GLOWSTONE:
        income: 3.0
        experience: 3.0
      SANDSTONE:
        income: 2.0
        experience: 2.0
      GLASS:
        income: 3.0
        experience: 3.0
      BRICK:
        income: 4.0
        experience: 4.0
      LAPIS_BLOCK:
        income: 5.0
        experience: 5.0
      DOUBLE_STEP:
        income: 2.0
        experience: 2.0
      STEP:
        income: 2.0
        experience: 2.0
      BOOKSHELF:
        income: 3.0
        experience: 3.0
      WOOD_STAIRS:
        income: 2.0
        experience: 2.0
      COBBLESTONE_STAIRS:
        income: 2.0
        experience: 2.0
      MOSSY_COBBLESTONE:
        income: 5.0
        experience: 5.0
      DIAMOND_BLOCK:
        income: 5.0
        experience: 5.0
      GOLD_BLOCK:
        income: 5.0
        experience: 5.0
    permissions:
      - simple.fly:
          value: true
          level: 0

**Comment by Sprax2013** [comment]
I can confirm this issue with LuckPerms (v4.0.18)
