### ISSUE TITLE
Problems with wheat and sugar cane counting

### ISSUE THREAD

**Issue by Manul-Newton** [Zrips/Jobs#1609]
I have a problem with the payment for plant harvesting (wheat, sugar cane and some tree logs)
Sometimes players who have a farmer or woodcutter profession receive payment for only 1-2 actions, while they perform hundreds of them.
The problem is not manifested regularly and I no longer understand what is wrong.
Already disable the schedule of bonuses and all quests, wheat and sugar cane was excluded from restrictedBlocks, restart the plugin and server, but the problem does not disappear.
By the way, more of other blocks like potatoes-7 works good. 

---

Config:
https://pastebin.com/XLV55r9a

Farmer job:
https://pastebin.com/9JRXnXVk

Woodcutter job:
https://pastebin.com/zq0AZttH

---

**Jobs version:** 5.1.0.0 (5.1.3.0 was also tested - problem does not disappear)

**Server Type (Spigot/Paper/etc):** Paper

**Server Version (using `/ver`):** 1.18.2

**Relevant plugins (Delete if this isn't needed):** Valut, xconomy

**Comment by mrfloris** [comment]
I've tried with wheat and that was counted fine. I think sugar cane might be that if they break the middle and 3 drop, it counts the hit for the middle perhaps as 1? despite how many drop? 

For completeness, can you do a /ver and /jobs version, and share the Full output, not just the numbers?

**Comment by Zrips** [comment]
@Manul-Newton 
Could you elaborate more on the part you mentioned that its not paying for hundreds of actions. Do you mean by braking all those blocks with hand or does it happen with 3rd party plugin like tree assist or something like that which could create more unique situations?

**Comment by mrfloris** [comment]
<img width="951" alt="Screen-Shot 2023-06-16 at 11 21 12" src="https://github.com/Zrips/Jobs/assets/28841349/32fbf817-e09d-4f0d-a49f-74248374e0dc">

Newton, it looks like you mentioned on Discord this is not caused by Jobs, I assume that means we can close the bug report?

**Comment by Manul-Newton** [comment]
It is block protect feature from Jobs. I don't understand why this feature does permanent protection for wheat. In restrictedBlocks the timer for wheat was set to 20 seconds.
But I have fixed that problem by cleaning the protection Database. This issue is closed.
