### ISSUE TITLE
NaN prices when using dynamic payment

### ISSUE THREAD

**Issue by dandud100** [Zrips/Jobs#1610]
***Detailed description of the issue:**

How is #857 closed? It is still an issue in the newest version. This issue happens when no players are in a specific job. Meaning that jobstotalplayers - 1 will output -1 which will break the equation. Similarly with only having a single player in a specific job, then same principle applies jobstotalplayers - 1 will now output 0, which of course will also break the equation.

**Comment by Zrips** [comment]
At this moment even having division by zero should return value in between defined MaxPenalty and MaxBonus. Cant really reproduce issue you are having here with NaN values being shown. Could you provide jobs files relating to this particular job you tested and maybe generalconfig file for testing and hopefully determination what causing this issue?

**Comment by dandud100** [comment]
You have a Discord message with the config files.

**Comment by Zrips** [comment]
d20e865cb0fbc276240e4d315d13d12c7432364b
