### ISSUE TITLE
Jobs limit output rounded down to MAX_INTEGER/100 when higher than it

### ISSUE THREAD

**Issue by edgecdec** [Zrips/Jobs#1623]
A Small bug I seemed to have found with the ```/jobs limit``` command:
It appears the left-hand side is being capped at the max value of an integer (2147483647) divided by 100. The actual limit works correctly…I am able to make money over the limit for a while and then it stops me (I’m guessing I’m getting to the limit), so I'm guessing this is just a display issue.

![image](https://github.com/Zrips/Jobs/assets/29873285/54b0a7db-ade8-42c8-bf02-8b01f760f83e)

[I believe this line is what's causing this issue by casting to Integer BEFORE dividing by 100 when the value can go all the way up to an integer's max value](https://github.com/Zrips/Jobs/blob/d20e865cb0fbc276240e4d315d13d12c7432364b/src/main/java/com/gamingmesh/jobs/commands/list/limit.java?fbclid=IwAR2-GB2LSCJ9QLMVUhMLz_kkZ-Y73pdSukrw6VZFygT2d8mh4-ZWUB_Qnfg#L68)

**Comment by Zrips** [comment]
Casting was actually correct, its a quick way to eliminate any fractional numbers past 2, tho it does fail to properly show bigger numbers. Will use different approach here to get better results. 
2e1d9afc9f1a65a15081d0cec2ce75a1f7c40946

**Comment by edgecdec** [comment]
> Casting was actually correct, its a quick way to eliminate any fractional numbers past 2, tho it does fail to properly show bigger numbers. Will use different approach here to get better results. [2e1d9af](https://github.com/Zrips/Jobs/commit/2e1d9afc9f1a65a15081d0cec2ce75a1f7c40946)

Ah, gotcha. Thank you for fixing it!
