### ISSUE TITLE
Jobs boost reset not working for singluar job.

### ISSUE THREAD

**Issue by ILikeOrangeJuice** [Zrips/Jobs#1627]
*** When using the boost command it does set it correctly either per job or overall. For example "jobs boost money 1.5 30m" does add the bonus of 150% to each job. Using "jobs boost builder money 2.5 12h" it does add 250% to builder, all fine so far. When using "/jobs boost reset" it does indeed reset ALL boosts as intended, the issue now comes when using for example "/jobs boost reset builder" or "/jobs boost reset money builder" nothing happens but outputing that it has a boost  like this: https://prnt.sc/hpWeGBGxSVSl  I also tried all types of capilization, but no success.

This was how it was named in your update "You can reset all boosts with /jobs boost reset if needed specific job name or action can be provided to only reset boost for that specific thing" - did I missunderstand it eventually?**

---

**Jobs version: 5.2.0.0** 

**Server Type (Spigot/Paper/etc): Paper** 

**Server Version (using `/ver`): git-Paper-72**

**Comment by ILikeOrangeJuice** [comment]
To add, it seems like using /jobs boost points/exp/money reset, does work, only specifying a specific job doesn't seem to work for me.

**Comment by Zrips** [comment]
0c38f6cc2033662e081cf7d04b1f767467650693
