### ISSUE TITLE
Use minecraft translations instead of translatableWords

### ISSUE THREAD

**Issue by Leymooo** [Zrips/Jobs#163]
I think will be better download a original minecraft transtalions, because translate each word is difficult and waste allot of time.
This plugin https://www.spigotmc.org/resources/%E2%98%AF-divinedrop-%E2%98%AF-awesome-drop-remover.51715/ can download minecraft translations an use it.

**Comment by montlikadani** [comment]
You can disable in the generalConfig.yml file.

**Comment by Denias3** [comment]
This still doesn't work in 5.2.4.5
