### ISSUE TITLE
Able to access the sign edit screen when trying to join a job

### ISSUE THREAD

**Issue by baailey** [Zrips/Jobs#1637]
***Detailed description of the issue:**

With the recent introduction of Minecraft's vanilla sign edit feature, it seems players are now able to access the sign edit GUI when right clicking a join job sign. It will still allow them to join the job, but it'll also open the GUI.
---

**Jobs version:** 
5.2.0.0
**Server Type (Spigot/Paper/etc):** 
Paper
**Server Version (using `/ver`):** 
git-Paper-100 (MC: 1.20.1)
**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
5bb3414ea7983e1b31caf760294b906bbbc73088
