### ISSUE TITLE
This is not a bug, I was told to come here for help with an issue I have. No clue where to put this other than here.

### ISSUE THREAD

**Issue by LadyRayvyn** [Zrips/Jobs#1638]
Jobs reborn v: 5.2.0.0
Server version: 1.20.1
Description:
Angler job not showing up in GUI (Jobs browse). I can't figure out what happened to make it disappear like that.
File:
[angler.zip](https://github.com/Zrips/Jobs/files/12295217/angler.zip)

**Comment by Zrips** [comment]
You jobs file is unproperly formatted, starting from "permissions" line all the way down. Additionally commands line uses tabs instead of spaces for indentations. Additionally both requires lists are improperly formatted.
