### ISSUE TITLE
Plugin will be disabled.

### ISSUE THREAD

**Issue by Reikshadow** [Zrips/Jobs#1641]
20.08 15:03:10 [Server] Server thread/WARN java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.ConfigurationSection.get(String, Object)" because "section" is null
20.08 15:03:10 [Server] Server thread/WARN at org.bukkit.configuration.MemorySection.get(MemorySection.java:265)
20.08 15:03:10 [Server] Server thread/WARN at org.bukkit.configuration.MemorySection.get(MemorySection.java:230)
20.08 15:03:10 [Server] Server thread/WARN at org.bukkit.configuration.MemorySection.isString(MemorySection.java:335)
20.08 15:03:10 [Server] Server thread/WARN at com.gamingmesh.jobs.config.RestrictedBlockManager.load(RestrictedBlockManager.java:45)
20.08 15:03:10 [Server] Server thread/WARN at com.gamingmesh.jobs.config.GeneralConfigManager.reload(GeneralConfigManager.java:279)
20.08 15:03:10 [Server] Server thread/WARN at com.gamingmesh.jobs.Jobs.reload(Jobs.java:832)
20.08 15:03:10 [Server] Server thread/WARN at com.gamingmesh.jobs.Jobs.startup(Jobs.java:536)
20.08 15:03:10 [Server] Server thread/WARN at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:741)
20.08 15:03:10 [Server] Server thread/WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
20.08 15:03:10 [Server] Server thread/WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
20.08 15:03:10 [Server] Server thread/WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
20.08 15:03:10 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:525)
20.08 15:03:10 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:439)
20.08 15:03:10 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:612)
20.08 15:03:10 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414)
20.08 15:03:10 [Server] Server thread/WARN at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:262)
20.08 15:03:10 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:994)
20.08 15:03:10 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
20.08 15:03:10 [Server] Server thread/WARN at java.base/java.lang.Thread.run(Thread.java:833)
20.08 15:03:10 [Server] Server thread/INFO There was some issues when starting plugin. Please contact dev about this. Plugin will be disabled.

5.2.0.0

Spigot

1.18

**Comment by Zrips** [comment]
Double check that your restrictedBlocks.yml is in correct format as this is indication of it being improperly setup.  
14b7e837d87a02eceacb5c445173edd8ab18ad4f
