### ISSUE TITLE
Jobs transfer issue

### ISSUE THREAD

**Issue by AMIGOSK** [Zrips/Jobs#1646]
i updated the plugin to new versiun maybe a few weeks ago and since i updated we have problems with jobs transfer function, when i use it on console doesn't work  and also when i use it in chat as a player also doesn't works
no warnings no errors nothing
i try reset whole plugin also doesn't work

---

**Jobs version: 5.2.0.0** 

**Server Type: purpur** 

**Server Version: 1.20.1**

**Comment by Zrips** [comment]
Job transfer simply changes your current job with its level and exp to new one, you need to be working in a job you are transferring from and NOT working in a job you are transferring to. 
Will add extra error message when conditions are not correct, as there was one situation where no feedback was given and command wasn't performed. 
6051c78d219462666ea795b624f0debabef8bbfe
