### ISSUE TITLE
Job Quests progress showing incorrectly

### ISSUE THREAD

**Issue by Bushpeng** [Zrips/Jobs#1650]
***Detailed description of the issue:**

When a player types into chat /jobs quests and hovers over a quest they have, it'll show the progress in yellow at the bottom. This does not match what is shown in chat. The number in chat is correct, but the lore is not.

**Jobs version:** 5.2.1.0 MySQL

**Server Type (Spigot/Paper/etc):**  Paper(169) 1.20.1-R0.1-SNAPSHOT

**Server Version (using `/ver`):** 1.20.1

**Relevant plugins (Delete if this isn't needed):** CMI Economy and Vault

![image](https://github.com/Zrips/Jobs/assets/94489904/8146825b-acf8-4e43-b7ba-8acabbdb17e9)

**Comment by Zrips** [comment]
80b8ac5684df0952dcf28d2ca86adf67e792b4d6
