### ISSUE TITLE
[Bug] Jobs limit wrong calculation

### ISSUE THREAD

**Issue by JeremyDarbellay** [Zrips/Jobs#1652]
***Detailed description of the issue:**
I'm using a third-party plugin called EcoEnchants (by auxilor), this plugin adds customs enchantments. One of them is called lumberjack, it's a common feature, but in short, when you break a log, it cut down the entire tree.

My problem is that jobs limit is incorrectly calculated, the amout of income is perfectly calculated, when you break a tree of 5 blocks, you earn five blocks of xp/points/income. But only the broken block is added to the limit.

So, in short : is it possible to count all broken blocks in the limit instead of only broken block, like it works for income ?

**Other details**
I've tested it with points limit (limit: 1000), the action "break" and oak_log as block.
The enchantment is an "effect" called "mine_vein".

Steps to reproduce :
- Break 5 block with an unenchanted axe,
- Do /jobs limit -> 5 blocks counted
- Break a 5 blocks tree with an enchanted axe with "lumberjack" enchant
- Do /jobs limit -> 1 block counted

 --------------------------------------------------
 Jobs: 5.2.1.0 MySQL
 CMILib: 1.4.1.1 
 Server: Paper(170) 1.20.1-R0.1-SNAPSHOT
 Economy: CMIEconomy Vault: 1.7.3-CMI 
--------------------------------------------------

**Relevant plugins :**  EcoEnchants - 10.35.2 + eco -  6.65.3

Thank you in advance for your support, have a nice day. I can provide more information if needed.

**Comment by Zrips** [comment]
Hard to say here exactly what's going on as EcoEnchants is premium plugin, can't really properly test it out. But Jobs can handle quick block breaks if those trigger BlockBreakEvent, what my suspicion here is that EcoEnchants directly modifies income you will get from those actions while not properly updating payment limits, so it's more up to EcoEnchants to add extra line into code for this to be properly recorded as it should be.

**Comment by JeremyDarbellay** [comment]
Hi, i'm back,
I contacted eco dev and he says that : 
"When mining blocks our plugins use built-in spigot methods to break blocks as a player
Which includes calling the block break event"

I've searched a bit where and how they do that thing (i don't code with java so a bit hard, but...)
There is the method i've found : https://github.com/Auxilor/libreforge/blob/master/core/src/main/kotlin/com/willfp/libreforge/effects/templates/MineBlockEffect.kt

There is its method to breakBlocks :
```java
    protected fun Player.breakBlocksSafely(blocks: Collection<Block>) {
        if (plugin.configYml.getBool("effects.use-setblock-break")) {
            blocks.forEach { it.type = Material.AIR }
        } else {
            this.runExempted {
                for (block in blocks) {
                    block.setMetadata("block-ignore", plugin.createMetadataValue(true))
                    this.breakBlock(block)
                    block.removeMetadata("block-ignore", plugin)
                }
            }
        }
    }
```
I don't have "use-setblock-break" toggled on, i've tested with it, but there is no payment at all.

Fortunately, eco plugins are open source !

I'm sorry, I don't know who can solve my issue, so i'm posting this a bit further here, along i'm discussing with eco dev.

Have a good day, thank you !
