### ISSUE TITLE
JobsReborn wrong limit calculation with EcoEnchants plugin (more information added).

### ISSUE THREAD

**Issue by JeremyDarbellay** [Zrips/Jobs#1659]
**Detailed description of the issue:**

Hi, it's me again, with the same issue as before, this time I'll provide a bit more information. 

**Information added**:
 link to effect Library repo, which is responsible for block breaking by enchantments : 
[LibReforge by Auxilor](https://github.com/Auxilor/libreforge/tree/master)

link to method which sent the block break event : 
[MineBlockEffect.kt](https://github.com/Auxilor/libreforge/blob/master/core/src/main/kotlin/com/willfp/libreforge/effects/templates/MineBlockEffect.kt)

method which break block effect (seems to dispatch spigot/ bukkit block break event) :
```java
protected fun Player.breakBlocksSafely(blocks: Collection<Block>) {
        if (plugin.configYml.getBool("effects.use-setblock-break")) {
            blocks.forEach { it.type = Material.AIR }
        } else {
            this.runExempted {
                for (block in blocks) {
                    block.setMetadata("block-ignore", plugin.createMetadataValue(true))
                    this.breakBlock(block)
                    block.removeMetadata("block-ignore", plugin)
                }
            }
        }
    }
 ```
_seems to use bukkit method to break block_

link to effect that breaks blocks without taking into account jobs limit :
[MineVein Effect](https://github.com/Auxilor/libreforge/blob/master/core/src/main/kotlin/com/willfp/libreforge/effects/impl/EffectMineVein.kt)
_use Player.breakBlockSafely method_

 --------------------------------------------------

## Previous issue :
I'm using a third-party plugin called EcoEnchants (by auxilor), this plugin adds customs enchantments. One of them is called lumberjack, it's a common feature, but in short, when you break a log, it cut down the entire tree.

My problem is that jobs limit is incorrectly calculated, the amout of income is perfectly calculated, when you break a tree of 5 blocks, you earn five blocks of xp/points/income. But only the broken block is added to the limit.

So, in short : is it possible to count all broken blocks in the limit instead of only broken block, like it works for income ?

**Other details**
I've tested it with points limit (limit: 1000), the action "break" and oak_log as block.
The enchantment is an "effect" called "mine_vein".

Steps to reproduce :
- Break 5 block with an unenchanted axe,
- Do /jobs limit -> 5 blocks counted
- Break a 5 blocks tree with an enchanted axe with "lumberjack" enchant
- Do /jobs limit -> 1 block counted

 --------------------------------------------------
 Jobs: 5.2.1.0 MySQL
 CMILib: 1.4.1.1 
 Server: Paper(170) 1.20.1-R0.1-SNAPSHOT
 Economy: CMIEconomy Vault: 1.7.3-CMI 
--------------------------------------------------

**Relevant plugins :**  EcoEnchants - 10.35.2 + eco -  6.65.3

Thank you in advance for your support, have a nice day. I can provide more information if needed.

**Comment by Zrips** [comment]
Well its written in script (kotlin?) language, and not java. Doesn't really use Bukkit API, atleast not in your examples, as those need to be written in java. So these examples would only be middle ones, between these and actual plugin which translates it into java. If it trigger block brake then we would be issuing payments for those broken blocks, it's quite straight forward process as long as there is event for it. EcoEnchants should either fire appropriate events while removing all those blocks or have direct integration with Jobs to give out appropriate payments and include those into limits. 
You will need to get into contact with EcoEnchants plugin developers and ask about this.

**Comment by JeremyDarbellay** [comment]
Thank you very much, will come back as i receive answer, have a good day

**Comment by JeremyDarbellay** [comment]
You can close this issue, eco enchants dev hasn't answered, i'm sorry for wasting your time have a good day.
