### ISSUE TITLE
receiving message "/jobs" on chat every single time after executing command /jobs join

### ISSUE THREAD

**Issue by homerek111** [Zrips/Jobs#1660]
**Detailed description of the issue:**

hello every single time while executing command /jobs join i receive this line on chat (screenshot):
https://i.imgur.com/EsOAwpU.png

---

**Jobs version:** 
5.2.1.1
**Server Type (Spigot/Paper/etc):** 
Paper
**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
**Relevant plugins (Delete if this isn't needed):**
CMILIB 1.4.2.0 (i also tried with 1.4.1.2 and still happening)

**Comment by Zrips** [comment]
cbff3e61383a733386eef94df5db2b6a07fc9cf6
