### ISSUE TITLE
Adding Tipped Arrows into job config not paying the player

### ISSUE THREAD

**Issue by Bushpeng** [Zrips/Jobs#1664]
***Detailed description of the issue:**
I am trying to add crafting tipped arrows work to pay a player for crafting them.
None of the known configurations will work for this action and items.

I have tried with the "-", ":", and just "tipped_arrow" without success in paying the player for the craft.

```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  Craft:
#   #Tipped Arrows#

    tipped_arrow-fire_resistance:
      income: 24
      experience: 8
    tipped_arrow-harming:
      income: 24
      experience: 8
    tipped_arrow-healing:
      income: 24
      experience: 8
    tipped_arrow-invisibility:
      income: 24
      experience: 8
    tipped_arrow-leaping:
      income: 24
      experience: 8
    tipped_arrow-luck:
      income: 24
      experience: 8
    tipped_arrow-night_vision:
      income: 24
      experience: 8
    tipped_arrow-poison:
      income: 24
      experience: 8
    tipped_arrow-regeneration:
      income: 24
      experience: 8
    tipped_arrow-slowness:
      income: 24
      experience: 8
    tipped_arrow-slow_falling:
      income: 24
      experience: 8
    tipped_arrow-strength:
      income: 24
      experience: 8
    tipped_arrow-swiftness:
      income: 24
      experience: 8
    tipped_arrow-turtle_master:
      income: 24
      experience: 8
    tipped_arrow-water_breathing:
      income: 24
      experience: 8
    tipped_arrow-weakness:
      income: 24
      experience: 8
```

**Jobs version:** 5.2.1.2

**Server Type (Spigot/Paper/etc):** 1.4.2.0

**Server Version (using `/ver`):** Paper (169) 1.20.1-R0.1-SNAPSHOT

**Relevant plugins (Delete if this isn't needed):** CMIEconomy and 1.7.3-CMI vault.

**Comment by Zrips** [comment]
29d65dc3c4f35ebc3eefb277604a433ad9d15417
