### ISSUE TITLE
Please add ability to pay for drinking potions

### ISSUE THREAD

**Issue by Bushpeng** [Zrips/Jobs#1665]
**Description of new idea or improvement on existing one**

Having the ability to add paying for players to drink potions.

**Detailed information what should do**

In the config file, if people so choose - add in the ability to eat potions

eat:
  potion:
    income:
    points:
    experience:
    
**if possible, and: else or**

eat:
  potion-healing:
    income:
    points:
    experience:
 
and repeat for all potion types

**Comment by Zrips** [comment]
9254c8f3fbeafb616ceadb1f7b217fdaec9c49cc

**Comment by 7hatGuyAJ** [comment]
How to use "Drink" in quests?

      Name: Beginner Hunter
      Objectives:
        - DRINK;ominous_bottle[ominous_bottle_amplifier=4];1
      RewardCommands:
        - money give [playerName] 100
