### ISSUE TITLE
Resetting levels is not persisting after a server restart

### ISSUE THREAD

**Issue by FireML** [Zrips/Jobs#1668]
***Detailed description of the issue:**
I am trying to reset a player's level and exp in a job. This will apply until the next restart, then the player's level will be returned.

Commands:
`/jobs level [name] [job] set 1`
`/jobs exp [name] [job] set 1`
---

**Jobs version:** 
5.2.1.2

**Server Type (Spigot/Paper/etc):** 
Paper

**Server Version (using `/ver`):** 
![image](https://github.com/Zrips/Jobs/assets/106587317/fb433ba9-63fc-4597-af7b-f8cd620abe0c)

**Comment by Zrips** [comment]
6d20ca3d33c57a0d62510e565883653bb2cd8d38
