### ISSUE TITLE
Quest 1 sample (log) not appearing in quests list

### ISSUE THREAD

**Issue by smmmadden** [Zrips/Jobs#167]
![image](https://user-images.githubusercontent.com/10309346/35484473-38a1281a-041e-11e8-80a2-d02212744785.png)
I put this in exactly (and quests 2 and 3 are showing, but 1 is not).
I tried each variation of the target name: 17-0, 17, 17 0, log, LOG, LOG-0, minecraft:log and MINECRAFT:LOG but none of these variants appear.
With 1.13 coming soon, the ID's will need to be replaced with the names so we'll need to make sure that will work.
I have maxDailyQuests: 3, toLevel: 50 and fromLevel: 5 but after /jobs reload, I still do not see it listed for the "Hunter" job type which is where the configuration was added.
![image](https://user-images.githubusercontent.com/10309346/35484581-d8df37da-041f-11e8-8995-f90efc41fbf9.png)

I'm on Spigot 1.12.2 (built today), Java 1.8.0_162, BuildTools v71, Waterfall 165 and Jobs 4.3.1

Edit: I changed log to "stone" and then it appears in the list (ignore description, it was a test)
![image](https://user-images.githubusercontent.com/10309346/35484638-90a1b816-0420-11e8-886d-823c5ed4cf7d.png)

**Comment by montlikadani** [comment]
Example 1 is just an example and will not even indicate 4 or more.
