### ISSUE TITLE
2 things, Jobs perks issue and how to add Job booster %'s in configs/where to do it?

### ISSUE THREAD

**Issue by LadyRayvyn** [Zrips/Jobs#1671]
***Detailed description of the issue:**
1. Trying to add job perks but its not working properly. I also need other info/help. please read this all.
   conditions: 
      first: 
        requires:
          - j:mole-15
        perform: 
          - 'lp user [player] permission set craft.copper_drill-true'
      second:
        requires:
          - j:mole-30
        perform:
          - 'lp user [player] permission set craft.golden_drill-true'
when a player joins a job they are getting both permissions when it should be at 15 and 30.  I can't figure out how to fix nor find any help at all for this. Please help! ALSO...
There are no video's old or new to explain how to add the job booster item %'s in configs so you can add them to items in game. I would greatly appreciate help on both of these issues please please :)

**Jobs version:** 
5.2.1.2

**Server Type (Spigot/Paper/etc):** 
Paper

**Server Version (using `/ver`):** 
version 1.20.1

**Comment by Zrips** [comment]
Conditional section will give you permission access by what you will set it to be which should be in a format as 'p:some.perm.here-true' while you are trying to perform command instead which will not be performed. Which only means that entire section isint being done entirely and player already has access to those permission nodes. If you want to perform commands on specific level then utilize "commands" section, you can check _EXAMPLE job which contains all possible options for the jobs. 
For boosted items, well just check boostedItems.yml file, default one will have one example, which is quite straightforward, after that you can get it ingame with command like **/jobs give Zrips Miner items boostedshovel**
