### ISSUE TITLE
Hi if i wanted to boost all jobs by 50% in a certain world would this be the permission node to use? 'jobs.boost.all.all.1.5' or is it 'jobs.boost.all.all.0.5'? Thank you

### ISSUE THREAD

**Issue by Riddimmmm** [Zrips/Jobs#1672]

**Comment by Zrips** [comment]
Simplest way to know would be to just give it to yourself and check what bonus you have with **/jobs bonus miner** and what you need is jobs.boost.all.all.0.5 as it defines how much of a bonus you are getting, in this case 0.5 would translate to 50% of bonus.
