### ISSUE TITLE
Not obtaining money from jobs

### ISSUE THREAD

**Issue by TheBadshah** [Zrips/Jobs#1673]
Not obtaining money from jobs

---

https://pastebin.com/9P7L5H4m

---

**Jobs version:** 5.2.1.2

**Server Type (Spigot/Paper/etc):**  Purpur

**Server Version (using `/ver`):** git-Purpur-2004 (MC: 1.20.1)

**Comment by Zrips** [comment]
ffd4309de7051aff7cbb3ab524059eb73ce326b3
