### ISSUE TITLE
JobsPrePaymentEvent Error

### ISSUE THREAD

**Issue by Avankziar** [Zrips/Jobs#1679]
A hook of the JobsPrePaymentEvent has shown that the value JobsPrePaymentEvent.getJob() returns null. But this shouldn't or can't be, because the players were always equipped with one in their action.

This bug has also been replicated on the latest version of MC and Paper. (Attached data is from the production server).

---

[ErrorCode](https://pastebin.com/970pYhp0)

---

**Jobs version:** 5.2.0.0

**Server Type (Spigot/Paper/etc):** Paper

**Server Version (using `/ver`):** 170

**Relevant plugins (Delete if this isn't needed):**
AdvancedEconomyPlus (My own Plugin with a Jobs hook)

**Comment by Zrips** [comment]
613be4780ef3f78abeb25c49be031357f2a1df54
