### ISSUE TITLE
Bug with `/jobs browse` GUI

### ISSUE THREAD

**Issue by PhoenixCodingStuff** [Zrips/Jobs#1681]
***Detailed description of the issue:**
Jobs GUI items get money lore on right click which gets fixed ONLY when you `/jobs reload`.
On opening the GUI the first time -> 
![image](https://github.com/Zrips/Jobs/assets/97077949/3b76aecb-2e99-485e-b4ab-923fb5148f1b)
After right clicking to see more info -> 
![image](https://github.com/Zrips/Jobs/assets/97077949/aa1cf0d3-ea71-403f-8d03-12a6d4f9e2c1)

**Steps to reproduce;**
1. Add jobs and CMILib, edit configs, and start server.
2. Use `/jobs browse` in game.
3. Right Click / Left Click [Depends on the config, whatever you need to see more info].
4. Go back in the GUI.

**Jobs version:** 5.2.1.2

**CMILib version:** 1.4.2.2

**Server Type (Spigot/Paper/etc):** Purpur 

**Server Version (using `/ver`):** Current: git-Purpur-2077 (MC: 1.20.2)

**Comment by Zrips** [comment]
c5863bb121062bfdc3e8242eca6a61da4ce0a512
