### ISSUE TITLE
Putting nametags in anvil results in StackOverflowError and console spam

### ISSUE THREAD

**Issue by bradnak** [Zrips/Jobs#1682]
***Detailed description of the issue:***
I placed an anvil in a fresh world and attempted to name a nametag with it. Once the name tag is placed in the slot, the console reports a really long error message with one line repeating 
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[12:35:43 ERROR]: Could not pass event PrepareAnvilEvent to Jobs v5.2.2.0
java.lang.StackOverflowError: null
        at com.gamingmesh.jobs.PlayerManager.containsItemBoostByNBT(PlayerManager.java:1090) ~[Jobs5.2.2.0.jar:?]
```
Last line repeated many times. I can pastebin the log if you want but all the lines look identical to me.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
Config still default

---

**Jobs version:** 5.2.2.0

**Server Type (Spigot/Paper/etc):** Paper

**Server Version (using `/ver`):** Paper version git-Paper-292 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 0a8c873)

**Relevant plugins (Delete if this isn't needed):** Only running Jobs and CMILib for this test, also happened with more plugins.

**Comment by DexterSK** [comment]
same issue

**Comment by bradnak** [comment]
Just adding a bit more detail for debugging. I didn't actually test if this error occurs with other items in anvils or other situations.

**Comment by mrfloris** [comment]
To better debug this, can you all please include the full output of `/jobs version`

**Comment by mercurialmusic** [comment]
Confirming as well. 

Spam: https://gist.github.com/mercurialmusic/d335cd95e27f5c1ec3fc8867f8efa3ed

Jobs: 5.2.2.0 SqLite
CMILib: 1.4.3.2 
Server: Paper(292) 1.20.2-R0.1-SNAPSHOT
Economy: CMIEconomy Vault: 1.7.3-b

**Comment by bradnak** [comment]
> To better debug this, can you all please include the full output of `/jobs version`
```
Jobs: 5.2.2.0 MySQL-> 5.2.2.1
CMILib: 1.4.3.2 
Server: Paper(291) 1.20.2-R0.1-SNAPSHOT
Economy: EssentialsX Economy Vault: 1.7.3-b131 
```
In my test world, I also experienced this bug with no economy plugin installed.

**Comment by bradnak** [comment]
It appears on first impressions that upgrading to Jobs 5.2.2.1 may have solved my issue. I will test this when I can and get back to you to confirm.

**Comment by bradnak** [comment]
Yes, upgrading to 5.2.2.1 has fixed this issue both on my production server and on my minimal test server.
