### ISSUE TITLE
Possible broken API

### ISSUE THREAD

**Issue by KermX** [Zrips/Jobs#1683]
***Detailed description of the issue:**
I am having issues with another plugin that uses the jobs api. This issue only appears when a jobs multiplier is combined with any other effect that mines multiple blocks at once.
Here is a link to the issue: 
part that includes jobs api: 
https://github.com/Auxilor/libreforge/tree/master/core/src/main/kotlin/com/willfp/libreforge/integrations/jobs/impl
part that does multiple block breaks:
https://github.com/Auxilor/libreforge/blob/master/core/src/main/kotlin/com/willfp/libreforge/effects/impl/EffectMineRadiusOneDeep.kt

The multiplier seems to be applied entirely incorrectly resulting in massively increased pay outs. Is this an issue on their end or is it a problem with jobs?

**Jobs version:** 
Jobs version 5.2.1.2

**Server Type (Spigot/Paper/etc):** 
Pufferfish

**Server Version (using `/ver`):** 
git-Pufferfish-23 (MC: 1.20.1)

**Relevant plugins (Delete if this isn't needed):**
https://github.com/Auxilor/libreforge/tree/master
https://github.com/Auxilor/eco

**Comment by Zrips** [comment]
I'm not familiar with this plugin or its code. You will need to get in contact with that plugin dev to figure out why their multiplier payments are incorrect.

**Comment by KermX** [comment]
> I'm not familiar with this plugin or its code. You will need to get in contact with that plugin dev to figure out why their multiplier payments are incorrect.

I send the relevant class files for this reason. Of course, I have already contacted the other plugin developer and they could not understand why it was giving the incorrect amount as this same exact method worked in the past. I was hoping that you could explain why/how this is incorrect usage of your api. The relevant classes are fairly short and are directly linked in my original issue. I would greatly appreciate if you could take a deeper look at some of this. I've looked myself and I also do not understand why this usage is incorrect.
