### ISSUE TITLE
java.lang.StackOverflowError

### ISSUE THREAD

**Issue by daniel-skopek** [Zrips/Jobs#1684]
```
[08:12:12] [Server thread/ERROR]: Could not pass event PrepareAnvilEvent to Jobs v5.2.2.0
java.lang.StackOverflowError: null
        at com.gamingmesh.jobs.PlayerManager.containsItemBoostByNBT(PlayerManager.java:1090) ~[Jobs5.2.2.0.jar:?]
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Jobs version:** 5.2.2.1

**Server Type (Spigot/Paper/etc):** Pufferfish

**Server Version (using `/ver`):** This server is running Pufferfish version git-Pufferfish-"979d3a2" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 979d3a2 on HEAD)

**Comment by Zrips** [comment]
Your error log indicates it to be 5.2.2.0 version and not 5.2.2.1 which contains fix for this issue. Just update to the latest version and you are good to go.
