### ISSUE TITLE
Infinite farming with placed blocks/breaking loop

### ISSUE THREAD

**Issue by moonies44** [Zrips/Jobs#1686]
***Detailed description of the issue:**
Hello. So with the mining/lumberjack jobs, players can just farm logs, place them, then farm them again, and just keeping looping to farm money/xp/experience. Does the plugin not check natural/player placed?
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
No error. 
```

**Jobs version:** 
5.2.2.1
**Server Type (Spigot/Paper/etc):** 
paper
**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
@moonies44 
Do you have PlaceAndBreak option enabled in generalConfig file? This should prevent from players placing and breaking blocks.
