### ISSUE TITLE
ignore-jobs-max Not working as expected

### ISSUE THREAD

**Issue by SlyGuy89** [Zrips/Jobs#1694]
I've noticed with the jobs that have "ignore-jobs-max: true" you can join them in addition to being at your max number of jobs with no issue. However, if you have a job with "ignore-jobs-max: true" included in the selection of jobs that puts you at max, you cannot add any jobs that do count against the max, even though some of your jobs shouldn't count towards the limit.

THE PROBLEM

Player job limit is 10. They join 10 jobs that count towards the max, and then join 1 job that ignores the job max. This puts the player at 11 jobs without issue.

However, if a player joins 9 jobs that count towards their max of 10, then join 1 job that ignores the max jobs. This puts them at 10 jobs with 1 of the jobs that ignores the job max, but if the player then attempts to join a job that DOES count towards the max, they receive the "you've already joined too many jobs!" error.

On my server the Max Job Limit is 10. A player has 8 jobs with "ignore-jobs-max: false" and 3 jobs with "ignore-jobs-max: true." Unless I'm misunderstanding this setting, they should still be able to join 2 more jobs with "ignore-jobs-max: false" but when they attempt to they receive the error saying they have too many jobs.

Another player first joined 10 "ignore-jobs-max: false" jobs and then joined the same 3 "ignore-jobs-max: true" jobs, giving them a total of 13 jobs.

I could be mistaken, but I do not believe this is the intended behavior of jobs with this setting.

---

5.2.2.1

Paper

Previous version: git-Paper-260 (MC: 1.20.2)

**Comment by Zrips** [comment]
a23b0af09b70a571d569f44550bc3606e600d93a
We should now ignore jobs with ignore-jobs-max while checking for job amount while joining jobs
