### ISSUE TITLE
No Rewards for Killing Cave Spiders

### ISSUE THREAD

**Issue by SlyGuy89** [Zrips/Jobs#1697]
Did a little bit of testing and it seems that Killing Cave Spiders does not pay out for jobs. This is true with "enable-pay-near-spawner: true" and also for Cave Spiders spawned via Spawn Egg.

Jobs Reborn 5.2.2.2

Paper

Paper version git-Paper-278 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 8cafc07)

**Comment by Zrips** [comment]
Basic testing resulted into payment being issued correctly. Make sure that your jobs config file is set correctly and that cave spider is present in jobs payment list when using /jobs info command.
