### ISSUE TITLE
trident not working

### ISSUE THREAD

**Issue by Produktecheck** [Zrips/Jobs#1698]
***Detailed description of the issue:**

Since the latest version (5.2.2.2) you no longer get a reward for killing mobs with the trident.

**ERROR (DELETE IF YOU HAVE NO ERROR):**
<-- Try to use pastebin.com server if you have long error. -->
```
####################
## PASTE ERROR HERE ##
####################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Jobs version:**  5.2.2.2

**Server Type (Spigot/Paper/etc):** Paper

**Server Version (using `/ver`):** 1.20.1

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
adf2fbb6408aa0a32ce964c44d84a4bbd11a5909
