### ISSUE TITLE
Issue with latest update

### ISSUE THREAD

**Issue by WarnDa** [Zrips/Jobs#1699]
***Detailed description of the issue:**
Since the latest update, there is a : 
`Fix entities that die due to fire damage,magma blocks,cactus, or other after being hit not rewarding job payouts (DersWasTaken)`
But this create issue with stacking plugin, if you hit 1 mob and put them in lava, all the mobs of the stack will die 1 by 1 and give you the exp

So put a config option for this settings would be the best solution.

**Jobs version:** 
5.2.2.2
**Server Type (Spigot/Paper/etc):** 
Pufferfish
**Server Version (using `/ver`):** 
1.20.1 
**Relevant plugins (Delete if this isn't needed):**
Tested with WildStacker

**Comment by Zrips** [comment]
d9cb1bf3374373469c11c6bea16079c001b48c7c
