### ISSUE TITLE
Bow and Trident not working

### ISSUE THREAD

**Issue by FrecciaTricolore** [Zrips/Jobs#1702]
***Detailed description of the issue:**

Good morning, lately mob kills via bow or trident throw are not counted and pay accordingly. This can also be seen in quests: mobs killed in that way do not increase the count.

Thank you.

**Jobs version: 5.2.2.2

**Server Type (Spigot/Paper/etc): Paper 

**Server Version (using `/ver`): 1.20.2

**Comment by Zrips** [comment]
adf2fbb6408aa0a32ce964c44d84a4bbd11a5909
