### ISSUE TITLE
Method org.bukkit.inventory.meta.PotionMeta.getBasePotionData() doesn't exists on 1.8.9

### ISSUE THREAD

**Issue by SkylerBoy** [Zrips/Jobs#1714]
***Detailed description of the issue:**
When consuming a potion containing PotionMeta, the console throws the error shown below.
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**

```
https://hastebin.com/share/qeperutuzo.scss
```

---

**Jobs version:** 5.2.2.3

**Server Type (Spigot/Paper/etc):** Spigot

**Server Version (using `/ver`):** ImanitySpigot3 (TacoSpigot 1.8.9 fork)

**Comment by Zrips** [comment]
2d01ec3cc73f38c39172fccb94de7a225ec44ce6
