### ISSUE TITLE
Points payment bug

### ISSUE THREAD

**Issue by Wolf2323** [Zrips/Jobs#172]
When someone do things in his job where he lose money and points, and he is not able to pay, the plugin try it again and again(economy-batch-delay) to get the money.
Every time the plugin try this, the player lose the points related to this payout

**Comment by montlikadani** [comment]
**Try update to the latest version.**

**Comment by montlikadani** [comment]
In the generalConfig file, the `Optimizations.DBCleaning` is enabled?
