### ISSUE TITLE
If I set the GlobalBlockTimer to -1, will the server be under a lot of pressure

### ISSUE THREAD

**Issue by xxg697** [Zrips/Jobs#1721]
Since I set
      GlobalBlockTimer:
        Use: true
        Timer: -1
My server tps became lower,Is it because this option is very performance-intensive?

**Comment by Zrips** [comment]
Without timings can't say for sure, but setting global timer to -1 isn't recommended as it will increase database by astronomical amount. Will make some changes to not allow -1 in global timer, global timer should only be set to some generic positive value as a default protection for blocks without increasing load too much.
1fb79f4ba238c588508f7a41f09f151f4487e37d
