### ISSUE TITLE
Quest Break oak_log and spruce_log not counting (or soup is counting only one)

### ISSUE THREAD

**Issue by PatalkokGIT** [Zrips/Jobs#1726]
***Detailed description of the issue:**

Break oak_log and spruce_log not counting
in picture from player (is the 2 first objectives)

it same for Soup if player craft 10 for exemple is count only 1
---
![rn_image_picker_lib_temp_fb632030-84e9-4a9a-970a-6130af23e318](https://github.com/Zrips/Jobs/assets/155537899/77621935-7efc-4ae5-b9f6-7982a7f61db4)

#####################################
#####################################
    '14':
      Name: Bûcheron - Impossible
      Objectives:
      - Break;oak_log;428
      - Break;spruce_log;428
      - Break;birch_log;428
      - Break;acacia_log;256
      - Break;dark_oak_log;256
      RewardCommands:
      - eco give [playerName] 1000
      - msg [playerName] Quête terminée!

---

**Jobs version:** 

Jobs5.2.2.3

**Server Type (Spigot/Paper/etc):** 

Paper

**Server Version (using `/ver`):** 
1.20.2-R-0.1

**Comment by Zrips** [comment]
Craft is based mostly on what you have payments set too, if you are only paying for single craft event and not for crafted amount (PayForEachCraft option) then it would could as single craft for daily quest. For quest not filling up when you perform actions, this might require server/plugin full restart for it to properly update criteria for that quest. 
Will add few small changes to more properly record quest changes in some instances.
ede3e4ede7a4b75f832aaf6f46c007cf730e551e
