### ISSUE TITLE
After Serverrestart last night Jobs Reborn throws a NullPointerException and will been disabled

### ISSUE THREAD

**Issue by WeltensiedlerDE** [Zrips/Jobs#1727]
Server going down last night for backup and after starting up again, Jobs got disabled and in the log is shown a NullPointerException.
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
<-- Try to use pastebin.com server if you have long error. -->
```
####################
## PASTE ERROR HERE ##
####################
https://pastebin.com/54CNhKBf

---

**Jobs version:** 
5.2.2.3

**Server Type (Spigot/Paper/etc):** 
Purpur

**Server Version (using `/ver`):** 
Current: git-Purpur-2124 (MC: 1.20.4)

**Comment by Zrips** [comment]
Pastebin link expired.
