### ISSUE TITLE
New option in plugin

### ISSUE THREAD

**Issue by DjeyMute** [Zrips/Jobs#1729]
Hi,
My community had an idea for your plugin.

The idea is to be able to pass the levels of your jobs without problem.
But once you reach a "certain level", you no longer earn more money than that of this "certain level".

Let me explain.
If a miner earns €30 by breaking a diamond block at level 100 then at level 101, 102, 103 he will still earn €30 by breaking a diamond block.
Because we will have put in the configuration that from the level 100 the player no longer earns additional money.

Thank you in advance for your answer.

**Comment by FireML** [comment]
You're wanting the `softIncomeLimit` option.

In each job file, add `softIncomeLimit: 100` to cap the income at level 100.

**Comment by DjeyMute** [comment]
Making this on my config.[https://image.noelshack.com/fichiers/2024/13/3/1711546579-capture-d-ecran-2024-03-27-143541.png
](url)

But I still make money...

**Comment by DjeyMute** [comment]
Maybe no?
What is this "softIncomeLimit" variable for?

**Comment by FireML** [comment]
from the example job file:
```
  # [OPTIONAL] Soft limits will allow to stop income/exp/point payment increase at some particular level but allow further general leveling.
  # In example if player is level 70, he will get paid as he would be at level 50, exp gain will be as he would be at lvl 40 and point gain will be as at level 60
  # This only applies after players level is higher than provided particular limit.
  softIncomeLimit: 50
  softExpLimit: 40
  softPointsLimit: 60
```

**Comment by DjeyMute** [comment]
Yeah so it doesn't work...
Please help me :(

**Comment by Zrips** [comment]
Having `  softIncomeLimit: 40` should limit income to the set level even if player is way above that level. Retested just to be sure and it seemingly works as it should. All the earning will be calculated by the set level if player is over it.

**Comment by DjeyMute** [comment]
I have test 3 time this.
It doesn't work, I take more monney when I level up

**Comment by Zrips** [comment]
Try testing this by adjusting softIncomeLimit: 40 and check if income you are getting by doing same job changes. For example, join Miner job, set your jobs level to 30, mine stone block and check income, go to jobs config file and set `softIncomeLimit: 20` reload jobs plugin with /jobs reload and check if income changed from previous amount you got.
Retested it again and everything looks to be working correctly, payments are being adjusted acord to set soft limit, so something else might be going on. You might even want to test it without any other plugin in case you have 3rd party plugin which issues payments and do not account for that option.
