### ISSUE TITLE
VIP Rank permission not increasing Level Limit

### ISSUE THREAD

**Issue by SlyGuy89** [Zrips/Jobs#1733]
Hello! So, as the title implies, my players are not currently able to unlock VIP rank with their jobs.

The specific job is "Smelter." The player has the required permission, and the configuration has been proved working previous to this by other players who have unlocked VIP ranks. The only changes since then regarding this plugin would be the latest CMILib update to version 1.4.6.1.

Jobs 5.2.2.3

Paper 1.20.2

This server is running Paper version git-Paper-278 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 8cafc07)
You are 40 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-260 (MC: 1.20.2)

![Screenshot 2024-04-10 205117](https://github.com/Zrips/Jobs/assets/143980718/558abc37-2ba2-409e-9628-3f334b80bb83)
![Screenshot 2024-04-10 205012](https://github.com/Zrips/Jobs/assets/143980718/ade6823e-566c-495a-8208-be58f6ae145e)
![Screenshot 2024-04-10 204952](https://github.com/Zrips/Jobs/assets/143980718/32e3c110-f303-49f1-826c-d0dae9d3e38a)

**Comment by SlyGuy89** [comment]
*** UPDATE***

It turns out this was a Display issue only! The /jobs stats command listed the job at "Max Level" until it levelled up to 201, then it displayed correctly.

**Comment by Zrips** [comment]
b7cfc104bbad99c5ee2410ba260de9631ebc74b0
