### ISSUE TITLE
Could not pass event EnchantItemEvent to Jobs v5.2.2.5

### ISSUE THREAD

**Issue by rayhandestian** [Zrips/Jobs#1738]
***Detailed description of the issue:**
Players cannot complete enchant job quest after updating to the latest version of Jobs (v5.2.2.5)

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
https://mclo.gs/tZWKUei

---

**Jobs version:** v5.2.2.5

**Server Type (Spigot/Paper/etc):** Purpur

**Server Version (using `/ver`):** git-Purpur-2095 (MC: 1.20.2)*

**Comment by Zrips** [comment]
Update CMILib and it should resolve your issue
