### ISSUE TITLE
Jobs Stats display issues

### ISSUE THREAD

**Issue by SlyGuy89** [Zrips/Jobs#1740]
[Screenshot 2024-04-20 005649](https://github.com/Zrips/Jobs/assets/143980718/a565bfc5-d3b7-4f59-ada5-e6a302b201a5)

---

Seems to still be a display issue with VIP ranked Jobs. Most of the jobs that say "Max Level" in that screenshot aren't actually to the max VIP level, but they have surpassed their configured max level in their configs.

Also, it seems color codes aren't properly working in the Jobs Stats display.
```


Jobs 5.2.2.5

Paper 1.20.2

This server is running Paper version git-Paper-278 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 8cafc07)
You are 40 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-260 (MC: 1.20.2)

**Comment by Zrips** [comment]
Are you sure that player isint at max vip level? As of retesting it does show stats of the job up until he hits max vip level. Will update locale of it to be more informative. You can add %joblevel% variable to max-level locale line to just indicate it more clearly what is the current level and to know if player is at the correct max level he should be for this message to be visible.

**Comment by SlyGuy89** [comment]
I will continue investigating until I can find something that seems indicative of the problem.
The only job I looked up the level to verify was "FungusHerder," which returned a current level of 359, whereas the VIP max level for that job is 500. 
Also, I do remember noting that immediately following the latest update the color codes weren't showing properly in the Jobs stats, but the inaccurate "Max Level" labeling wasn't an issue, and the stats displayed correctly. It seems that the first time those jobs were leveled up AFTER updating to 5.2.2.5 the stats readout reverted to the "Max Level" label.
Great suggestion on using the placeholder in the locale, I'll definitely do that!
I can't know for sure if it is amazing any effect, but I feel I should mention on my server players are able to increase their Max VIP level by intervals of 50 using LP groups and promoting players along a track. These groups use the jobs.all.vipmaxlevel.[maxlevel] permissions, starting at 500 and maxing out at 1000.
So, these players have 2 permissions handling their VIP jobs/levels:
jobs.[jobsname].vipmaxlevel-and-jobs.all.vipmaxlevel.[maxlevel]
Not sure if this could be causing the problem but I figured it's worth noting since it may not be the way those permissions were intended to be used.
Thank you for your time, and I'll be sure to let you know if I'm able to figured anything out!

Yahoo Mail: Search, Organize, Conquer 
 
  On Sat, Apr 20, 2024 at 6:19 AM, ***@***.***> wrote:   


Are you sure that player isint at max vip level? As of retesting it does show stats of the job up until he hits max vip level. Will update locale of it to be more informative. You can add %joblevel% variable to max-level locale line to just indicate it more clearly what is the current level and to know if player is at the correct max level he should be for this message to be visible.
