### ISSUE TITLE
The plugin saves every players on startup

### ISSUE THREAD

**Issue by IbanEtchep** [Zrips/Jobs#1741]
***Detailed description of the issue:**
When the server starts, the plugin saves every players. This causes somes problems:
- Can't stop the server before every players arent saved (I have 12k players so it takes more than 3 hours)
- Sync problems in multi server environment. If a player win xp, another server saves old data so the player has a rollback.

I recompiled the plugin with some console logs:
- one on setSaved(false) method
- one on save method
---

[https://mclo.gs/bF3wELb](https://mclo.gs/bF3wELb)

**Jobs version:** 5.2.2.5

**Server Type:** Pufferfish

**Server Version:** 1.20.4

**Comment by Zrips** [comment]
42e3043062cfc569bc486159708b3e17300d6b6c
