### ISSUE TITLE
Killing Non-Stacked Mobs Pays Out More Than Intended

### ISSUE THREAD

**Issue by EcoSMP** [Zrips/Jobs#1749]
***Detailed description of the issue:**
We run StackMob on our server. Ever since update 5.2.2.3, killing a single mob that is not in a stack pays out far more Hunter money/exp than it should. Killing mobs that are stacked 2 or more pays out the correct amount still.

---

This is a video showing how killing a stack pays out correctly, but a single mob does not: https://youtu.be/G7sOx0h-Kc8

---

**Jobs Reborn Config:**  
https://pastebin.com/faJPnt9F

**StackMob Config:**  
https://pastebin.com/LZHqG512

---

**Potential Solutions We Tried:** 

- We tried changing the Jobs section of the StackMob config to IGNORE instead of MULTIPLY, but that didn't seem to make any difference.
- We tried running this on a 1.20.4 server instead of 1.20.2, but that didn't seem to make any difference either.
- We tried disabling the death animation in StackMob just to see if that would make any difference and found out that Jobs will not pay out at all for killing mobs if the death animation is disabled.

---

**Jobs version:** 
5.2.2.3 thru 5.2.2.5

**Server Type (Spigot/Paper/etc):** 
PurPur

**Server Version (using `/ver`):** 
git-Purpur-2095 (MC: 1.20.2)
Also tried on a 1.20.4 Purpur server to test it.

**Relevant plugins (Delete if this isn't needed):**
StackMob 5.8.10 (latest)

**Comment by Zrips** [comment]
339ec5be3ed4d42cd411a7179ac35c616a912fa0
