### ISSUE TITLE
1.20.6 Support

### ISSUE THREAD

**Issue by JuergenUniVie** [Zrips/Jobs#1750]
***Detailed description of the issue:**
Jobs doesn't start yet on 1.20.6
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
[<-- Try to use pastebin.com server if you have long error. -->](
####################
####################
[```](https://pastebin.com/nJPsm7pX)

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Jobs version:** 
5.2.2.5
**Server Type (Spigot/Paper/etc):** 
Paper 1.20.6 [36]
**Server Version (using `/ver`):** 

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Will be supported with next release
