### ISSUE TITLE
Impossible to modify equations

### ISSUE THREAD

**Issue by iJuju68** [Zrips/Jobs#1753]
***Detailed description of the issue:**
When I change the equation, the jobs no longer works, and I no longer receive money or XP.
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
  leveling-progression-equation: 1*(joblevel)*(1.2)
  income-progression-equation: baseincome+(baseincome*(joblevel-1)*0.01)-((baseincome+(baseincome*(joblevel-1)*0.01)) * ((numjobs-1)*0.05))
  points-progression-equation: basepoints+(basepoints*(joblevel-1)*0.01)-((basepoints+(basepoints*(joblevel-1)*0.01)) * ((numjobs-1)*0.05))
  experience-progression-equation: (baseexperience)*1.1

---

**Jobs version: 5.2.2.1** 

**Server Type (Spigot/Paper/etc):* PaperSpigot* 

**Server Version (using `/ver`):*PaperSpigot-445 (MC: 1.8.8) *

**Comment by Zrips** [comment]
Equation looks to be correct and valid. You might want to double check if during your testing you didn't reach daily payment limit which prevented any further gains. Closing ticket for now.

**Comment by iJuju68** [comment]
Hello,

No, I have not reached the daily payment limit.

As soon as I reset the basic equation, it works again...

Can you test with the version of the plugin I have?
Thanks

**Comment by iJuju68** [comment]
Hello,

Were you able to see my problem?
