### ISSUE TITLE
Jobs schedules.yml not working

### ISSUE THREAD

**Issue by AyerYT** [Zrips/Jobs#1755]
***Detailed description of the issue:**
Please help, everything seems to be correct, but for some reason schedules.yml does not work, it shows some kind of error where everything is correct, and when I remove the line where it shows the error, it starts showing an error in another line. All version plugins is last. Paper 1.12.2 

---

**ERROR (DELETE IF YOU HAVE NO ERROR): After /jobs reload happened this: https://pastebin.com/0F4Y7pku**
<-- Try to use pastebin.com server if you have long error. -->

**CONFIG SECTION (DELETE IF NOT RELEVANT): https://pastebin.com/HSWQbHwj**

---

**Jobs version: 5.2.3.0** 

**Server Type (Spigot/Paper/etc): Paper** 

**Server Version (using `/ver`): Paper-1620 (1.12.2)**

**Comment by Zrips** [comment]
Missing ' at line 27
