### ISSUE TITLE
/jobs archive command not working as intended

### ISSUE THREAD

**Issue by Pirito10** [Zrips/Jobs#1764]
**Detailed description of the issue:*** the `/jobs archive` output does not show any information

---

**Jobs version:** 5.2.3.0

**Server Type (Spigot/Paper/etc):** Purpur

**Server Version (using `/ver`):** git-Purpur-2176 (MC: 1.20.4)

**To reproduce:**

- Use default configuration.
- Join a job, for example `/jobs join Miner`
- Give yourself some levels, for example `/jobs level <player> Miner set 10`
- Leave the job, for example `/jobs leave Miner`
- Run `/jobs archive`

You will see a progression bar, with nothing else:
![image](https://github.com/Zrips/Jobs/assets/74465348/2901f00f-7d4a-4c42-aeb3-cc1b48d9dde1)

**Comment by KermX** [comment]
Same update also broke the colors on `/jobs stats`
![image](https://github.com/Zrips/Jobs/assets/94108444/1342fa6d-0db0-4dfb-92b6-54cb81531f79)

**Comment by Pirito10** [comment]
Then it might be a duplicated of #1758

**Comment by Zrips** [comment]
@Pirito10 
eb5908cbac8f33ddf653cfe7b8400c600ec34492
@KermX 
Its not really a broken, it was simply changed to new default look
