### ISSUE TITLE
/jobs top shows incorrect line when using wrong job name

### ISSUE THREAD

**Issue by Pirito10** [Zrips/Jobs#1765]
**Detailed description of the issue:** when you run command `/jobs top <job>` but the job name is incorrect, it shows an extra line saying "/jobs"

---

**Jobs version:** 5.2.3.0

**Server Type (Spigot/Paper/etc):** Purpur

**Server Version (using `/ver`):** git-Purpur-2176 (MC: 1.20.4)

**To reproduce:**

- Use default configuration
- Run command the command with an incorrect job name, for example `/jobs top a`

You will see the line corresponding with the translation key `command.top.error.nojob`, then another line saying "/jobs":
![image](https://github.com/Zrips/Jobs/assets/74465348/c7ad0447-16da-44e9-ae82-f7bd4a3a706b)

**Comment by Zrips** [comment]
c60bbf3738117ca7035cf0f11032d67fc7504d6b
