### ISSUE TITLE
Sweet Berries do not give exp while crouching

### ISSUE THREAD

**Issue by WarnDa** [Zrips/Jobs#1768]
If you collect a sweet berries while crouching, it doesn't give exp/money/points, but if you aren't crouching it works correctly.

**Jobs version:** 
5.2.3.0

**Server Type (Spigot/Paper/etc):** 
Universespigot (also tested on paper)
**Server Version (using `/ver`):** 
This server is running UniverseSpigot version git-UniverseSpigot-"132b1fb" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 132b1fb on ver/1.20.4-plus-fix)

**Relevant plugins (Delete if this isn't needed):**
/

**Comment by Zrips** [comment]
ad577e60ff2e5610137af62e7744392f9de74016
