### ISSUE TITLE
Jobs Name (Fullname) not replaced with Jobname in Bossbars and /jobs stats

### ISSUE THREAD

**Issue by MineTommy** [Zrips/Jobs#1769]
***Detailed description of the issue:**
_ /jobs stats

![image](https://github.com/Zrips/Jobs/assets/17363482/df64a14c-d874-411c-b7df-937e41ebeb43)

![image](https://github.com/Zrips/Jobs/assets/17363482/ffe341e8-3a9a-4071-b834-98744169c2e9)

We are use Language "de"

Jobs join is the Same (Maybe the Translation of %jobsname% dont work)

Best Regards
Tommy
---

---

**Jobs version:** 5.2.2.5

**Server Type (Spigot/Paper/etc):** 1.20.1 Purpur

**Server Version (using `/ver`):** 

![image](https://github.com/Zrips/Jobs/assets/17363482/6902b333-a44c-4b6b-b45e-b57fed149c1d)

**Comment by GodDirtman** [comment]
Has this been updated? I'm still experiencing this issue on Jobs 5.2.4.0 and Paper version 1.21-116.
