### ISSUE TITLE
[!] I get money when other player smelting Iron ingot in his residence

### ISSUE THREAD

**Issue by smscentras** [Zrips/Jobs#1770]
***Detailed description of the issue:**

I get money when other player smelting Iron ingot in his residence, maybe it's because i'm admin, don't know why.
One time open other player Furnace while he smelt iron and.... allways i get money from Jobs. Strange situation.

**Jobs version:** 
Jobs: 5.2.3.0 SqLite

**Server Type (Spigot/Paper/etc):** 
Purpur

**Server Version (using `/ver`):** 
Purpur 1.20.4-R0.1-SNAPSHOT

**Comment by Momshroom** [comment]
Opening an unregistered furnace will have registered it to you.   You can fix this by doing 
/jobs ownedblocks
And then clicking the furnace in question to remove it from your owned blocks.   When the player interacts with it, it will be registered to them and they will start to get the income and xp.

**Comment by Zrips** [comment]
5c194bc8ca8860c1f43057b76f6d4a1111a5cbca
New permission node which should be given to OP by default which will prevent you from taking over blocks ownership when you just want to check its contents
