### ISSUE TITLE
When “-all” is used, some are missing.

### ISSUE THREAD

**Issue by ustk256** [Zrips/Jobs#1771]
***Detailed description of the issue:**

 If color-all is used for wool shearing income, there is no income for light_gray_wool and light_blue_wool. (wool-all in Place and Craft works fine).

---

**Jobs version:** 
5.2.3.0
**Server Type (Spigot/Paper/etc):** 
Paper 1.20.4
**Server Version (using `/ver`):** 
git-Paper-496

**Comment by Zrips** [comment]
Should be fixed with next CMILib update
