### ISSUE TITLE
Jobs Reborn dont loaded successfully

### ISSUE THREAD

**Issue by svdermant** [Zrips/Jobs#1773]
Hello, I have a problem activating Jobs Reborn on my PaperMC server version 1.19.4.
Here is the server log: https://pastebin.com/YigXUZhU
I don't understand the error message that concerns Jobs Reborn.
How do I fix it?

Same Error on Startup if i change from sqlite to Mysql. Jobs Reborn not loaded: 
https://pastebin.com/35VrVC8G

**Jobs version: Jobs v5.2.3.0 

**Server Type (Spigot/Paper/etc): PaperMC

**Server Version (using `/ver`): This server is running Paper version git-Paper-550 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4)

**Relevant plugins (Delete if this isn't needed):
https://ibb.co/X8xF3bf
https://ibb.co/rwzG6YZ

**Comment by Zrips** [comment]
From error and where it originates looks to be issue relating to enchants on your server, quite likely due to incorrectly created ones which produced situation causing this error to happen. Will issue a fix with next update, but you could resolve it by disabling plugin responsible for custom enchantments

**Comment by svdermant** [comment]
The only plugin I remember that sets custom enchantments would be CrazyEnchantment.

I don't know of any others because I haven't used the server for a while.

**Comment by svdermant** [comment]
But the error message doesn't mention anything about enchantments, so how do you know that might be the cause?

I've apparently removed CrazyEnchantment.

Still no success:
https://pastebin.com/PUjFf3nW

**Comment by Zrips** [comment]
Error points towards a line of code responsible of creating local file record based on enchant name. So issue is with recorded enchants on your server. You could test this by only having CMILib and Jobs on your server and check if it starts or not, if it does then you will know that there is another plugin doing something it should not do

**Comment by svdermant** [comment]
That's where I'm at right now, it's tedious, but it will also help you for the next update if you know which plugin is causing this error.

It's certainly not CrazyEnchantment. I'll continue to analyze and let you know.

**Comment by Zrips** [comment]
I will make a fix to avoid this issue in the future, tho it would be nice to know which plugin in particular caused this issue for the future reference

**Comment by svdermant** [comment]
I found the plugin that caused the error.
It's not PlaceHolderAPI or CrazyEnchantment.

It was the plugin mythicdrops in version 8.5.5
I have now loaded the latest version of this plugin, i.e. version 8.6.1 and Jobs reborn was also loaded including all other plugins.

**Comment by Zrips** [comment]
d0c36fc246dd7601c4bea2019522f8b23308704c
