### ISSUE TITLE
Prevent shop item enchanting not working

### ISSUE THREAD

**Issue by brygy** [Zrips/Jobs#1783]
***Detailed description of the issue:***
I have prevent-shop-item-enchanting set to true in config but people still can add enchants usning enchanted books in anvil to shop purchased items. Am I missing any further setting/permission/dependencies or is this setting broken right now?

Screenshots of generalConfig and example of item that can be enchanted below.

---

**CONFIG SECTION:**

![obrazek](https://github.com/Zrips/Jobs/assets/55452383/b42af030-14c5-4e89-b1c6-25da912d156c)

![obrazek](https://github.com/Zrips/Jobs/assets/55452383/a07bf7bc-15d5-475c-a648-4ceff048fa43)

![obrazek](https://github.com/Zrips/Jobs/assets/55452383/b898a964-036d-4af5-96f9-e36be5f24cc8)

---

Jobs: 5.2.4.0 SqLite
CMBLib: 1.5.0.4
Server: Spigot 1.21-R0.1-SNAPSHOT
Economy: EssentialsX Economy
Vault: 1.7.3-b131

**Comment by brygy** [comment]
If it helps, there is also complete list of plugins currently on server

![obrazek](https://github.com/Zrips/Jobs/assets/55452383/6c6a205b-8c66-4674-8163-2e24e72ffe58)

**Comment by Zrips** [comment]
b8822c2a576ef327a1c0d90d282d88b0e7a7193a
Tho keep in mind that this new protection will only apply to newly created items and not to the ones which already exist
