### ISSUE TITLE
JobsChunkChangeEvent | Spamming Console

### ISSUE THREAD

**Issue by Dshooot** [Zrips/Jobs#1785]
***Detailed description of the issue:**

I have the newest JobsReloaded and CMILIB and my console is filled with errors when walking or breaking block etc. I don't really know where is the issue since it spams even though noone has a job activated.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
https://pastebin.com/V0paLTDQ

```
![image](https://github.com/Zrips/Jobs/assets/174878910/4f9d2d75-172f-4e43-8a59-ca857c48ce39)

```

---

**Jobs version: 5.2.4.0** 

**Server Type (Spigot/Paper/etc): Paper** 

**Server Version (using `/ver`): 1.20 - 1.20.1** 

**Relevant plugins (Delete if this isn't needed): JobsReloaded 5.2.4.0 and CMILIB 1.5.0.5**

**Comment by Dshooot** [comment]
(https://imgur.com/EOfMDOh)

**Comment by matiasOliva64** [comment]
I have exactly the same error with that version of the plugin!

**Comment by Dshooot** [comment]
With the new CMILIB 1.5.0.6 The issue is fixed! Thanks.
