### ISSUE TITLE
PlayerItemConsumeEvent Errors In Console

### ISSUE THREAD

**Issue by DemarcoFC** [Zrips/Jobs#1786]
There is multiple errors in my console involving Jobs unable to pass PlayerItemConsumeEvent. 

---
https://pastebin.com/CmWdrRWq

---

**Jobs version:** 5.2.4.0

**Server Type (Spigot/Paper/etc):** Paper

**Server Version (using `/ver`):** Paper 1.20.6-147-ver

**Comment by Zrips** [comment]
326ce9e01b97178d3ff35a3c7db10151399c8995
