### ISSUE TITLE
Memory leak with Jobs Metadata Usage

### ISSUE THREAD

**Issue by Fabelz** [Zrips/Jobs#1792]
***Detailed description of the issue:**
Jobs currently saves various pieces of data to the metadata of entities and blocks. This is usually fine, but on higher player count servers with a lot of actions being performed this can cause various performance issues as the metadata system is **never garbage collected**.

This can be demonstrated easily by collecting a heap dump, spawning however many entities you want via a mob spawner or spawner egg (to utilize the jobsMobSpawner metadata tag) and then performing another heap dump after removing the entities to compare the metadata entries.

This is because spigot's metadata system intentionally doesn't clear old entries when the entity backing it dies or is unloaded as it is up to the individual plugin to handle it itself as the map that stores the data is shared between all entities globally, and is the same reason that when you save player metadata it is persistent between their logins (until the server itself shuts down).

A potential fix for this would be to use the persistent data storage (on servers above 1.14, honestly not quite sure what could be done easily for servers below it other than storing them in a separate map) when relevant objects that use the metadata system are unloaded/loaded back in (which you guys are doing partially already), and removing the old entries from metadata when no longer needed.

For entities specifically, you can also use the Entity#getEntitySpawnReason method on later paper versions to avoid saving anything to a map at all.

I may make a pull request for this, but I thought it'd be best to leave it up to the plugin devs as you guys know your own source best 😂
---
**Jobs version:** Latest, works on older versions as well.

**Server Type (Spigot/Paper/etc):** Custom Spigot

**Server Version (using `/ver`):** 1.20.1 (Replicateable on latest spigot, however)

**Comment by ericlmao** [comment]
Confirmed. Also having this issue.

**Comment by Zrips** [comment]
9df5287555e5e3038c548a533bf2153d69b4661b
