### ISSUE TITLE
enchanter don't work

### ISSUE THREAD

**Issue by istarengwa** [Zrips/Jobs#1796]
***Detailed description of the issue:**
Hello, latest version of cmilib, cmi, jobs, but when a player tries to enchant an object, no gain with the enchanter job, but this error on the console
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
![image](https://github.com/user-attachments/assets/2ec9cbfd-b640-4069-841f-868f0a7edc65)

---

**Jobs version:** 5.2.4.0

**Server Type (Spigot/Paper/etc):** Pufferfish

**Server Version (using `/ver`):** 1.20.4

**Comment by Zrips** [comment]
a0dd4c2925b166dee8d40d88cf05640d0cd8f93c
