### ISSUE TITLE
Certain jobs like miner, digger etc do not give payouts. I'm unaware of what is wrong with it.

### ISSUE THREAD

**Issue by foepgames2** [Zrips/Jobs#1797]
***Detailed description of the issue:**

--- Hello im having some issues with certain jobs getting no payout. I dont know what is or isnt relevant so feel free to ask me for more information.

**ERROR (DELETE IF YOU HAVE NO ERROR):**
<-- Try to use pastebin.com server if you have long error. -->

https://pastebin.com/J3DDMDLV

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
https://pastebin.com/RnkPWD3Y
```

---

**Jobs version:** 
1.4.7.15 (cmilib)
5.2.4.0 (jobs)

**Server Type (Spigot/Paper/etc):** 
git-paper-497

**Server Version (using `/ver`):** 
git-paper-497

**Relevant plugins (Delete if this isn't needed):**
Jobs
Jobs Patchplacebreak

**Comment by rautamiekka** [comment]
The Jobs plugin is the only thing you've updated, everything else (apart from the patch which ain't mentioned) is old.

**Comment by Zrips** [comment]
@foepgames2 
Updating CMILib would resolve issues like that. Try to keep both plugins up to date, especially if you upgrade server version
