### ISSUE TITLE
Jobs Plugin 'NullPointerException' on '/jobs browse' Command in Minecraft 1.21

### ISSUE THREAD

**Issue by var1nthon** [Zrips/Jobs#1799]
***Detailed description of the issue:**
I encountered an issue with the Jobs plugin when attempting to use the /jobs browse command. It appears to be related to a NullPointerException caused by a null ItemStack in the GUI setup for the jobs. This prevents the GUI from opening correctly and results in an error message in the server console.

---

**Steps to reproduce the issue:**
1. Start the server with the specified plugins and configurations.
2. Log in as a player.
3. Execute the /jobs browse command.

---

**ERROR:**
Error log: https://paste.helpch.at/osezovupun.php
Latest log: https://paste.helpch.at/umahonozoz.md

---

**Jobs version:** 
5.2.4.0

**Server Type (Spigot/Paper/etc):** 
Paper

**Server Version (using `/ver`):** 
Paper version 1.21-124-master@df3b654 (MC: 1.21)

**Relevant plugins (Delete if this isn't needed):**
PlaceholderAPI
Vault
ProtocolLib
Citizens
DeluxeMenus
Multiverse-Core
CustomCrops
CMILib
AuraSkills
ProtectionLib

**Comment by Zrips** [comment]
7a16af10788aae90a4be3506f2568a41334a886d
