### ISSUE TITLE
Rabbit translate not work ItemList.yml

### ISSUE THREAD

**Issue by andris155** [Zrips/Jobs#18]

**Comment by Zrips** [comment]
There will be rework of ItemList file in upcoming 3.0 version

**Comment by andris155** [comment]
3.3.6 - not work Rabbit Translate.
![2016-04-27_12 00 05](https://cloud.githubusercontent.com/assets/8324198/14848835/f5fe5390-0c6f-11e6-80e5-44d2b007484c.png)

**Comment by andris155** [comment]
And Shear: Sheep translate not work.
![2016-04-27_12 03 52](https://cloud.githubusercontent.com/assets/8324198/14848875/2a0d95a6-0c70-11e6-8c86-6fea9b1ef8b9.png)

**Comment by Blamo27** [comment]
Still not working.

**Comment by Blamo27** [comment]
@Zrips Can you fix that ? (Husk Stray Rabbit Llama)
