### ISSUE TITLE
To reduce salary.

### ISSUE THREAD

**Issue by kimar321** [Zrips/Jobs#180]
how to Reduce wages?

**Comment by DmitryRendov** [comment]
@kimar321 I tried to use permission "jobs.boost.all.money.[amount]" (like "jobs.boost.all.money.-1.0") but it doesnt work for me, so I just replaced all values in configuration files by reducing them to 10 times.

**Comment by kimar321** [comment]
@DmitryRendov Спасибо!

**Comment by Zrips** [comment]
093675b86c900f7e5cc30306db6a3be828d797c0
