### ISSUE TITLE
/jobs toggle actionbar no longer showing in chat

### ISSUE THREAD

**Issue by Caroline4747** [Zrips/Jobs#1809]
Previously, if you had /jobs toggle actionbar set to off, the payments and exp would send to your chat, this is no longer the case. 
---

**Jobs version: 5.2.4.2** 

**Server Type (Spigot/Paper/etc): Spigot** 

**Server Version (using `/ver`): 1.21.0**

**Comment by KermX** [comment]
Same issue, this has been a pretty key feature for a very long time.

**Comment by ItzRegen** [comment]
Having the same issue.. It was really good feature.

**Comment by Zrips** [comment]
4d941951460eb7c43784fa6509d49169421b602c
