### ISSUE TITLE
Kill tasks arent working

### ISSUE THREAD

**Issue by Malikplays** [Zrips/Jobs#1817]
**Jobs version: 5.2.4.2

**Server Type (Spigot/Paper/etc): Paper

**Server Version (using `/ver`): 1.20.4

I attempted to create a custom job and noticed that the kill tasks weren’t working. I then tested the kill tasks with jobs originally included in the plugin, but those didn’t seem to work either—for example, the Merchant job.

**Comment by Malikplays** [comment]
Was orginally  on Jobs5.2.2.3, just tried to update it to see if this would work and neither version work.

**Comment by Zrips** [comment]
fed6ef13551b6fde928b2ef6a28a01c56779010a
