### ISSUE TITLE
Error After Jobs Update

### ISSUE THREAD

**Issue by Darkstar2508** [Zrips/Jobs#1821]
**Detailed description of the issue:**

After updating to the latest version of Jobs (V.5.2.4.2) Began receiving the error listed below constantly spammed in console.

**ERROR**
https://paste.md-5.net/ibaqoyuqad.pl

**Jobs version:** 
5.2.4.2

**Server Type (Spigot/Paper/etc):** 
Pufferfish

**Server Version (using `/ver`)**
This server is running Pufferfish version git-Pufferfish-40 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 8d20921 on HEAD)

**Comment by Zrips** [comment]
This was resolved with later Pufferfish updates, just download latest #52 update and it should be good to go
