### ISSUE TITLE
commands :in _EXAMPLE.yml not working/correct

### ISSUE THREAD

**Issue by perlsol** [Zrips/Jobs#1822]
***Detailed description of the issue:**

Using the example.yml to run a command on level up, fails to run the command(s).

*** FIX ***
The quotes are missing, wrap the command in quotes and all works fine. please amend your example.

  commands:
    keys1:
      command:
      - "lp user [player] permission set can_craft_keys_lvl1 true"
      - "msg [player] Now you can craft crate keys level1!"
      levelFrom: 5
      levelUntil: 5

**Comment by Zrips** [comment]
Quotation marks are not required in some instances, in general for general safety when you have more complex text you should add " or ' depending what you used inside text itself, but if you have clean text then you can define it without any quotation marks and it would still work correctly. This is just how yml file is being handled and saved by default
