### ISSUE TITLE
Not working on the 1.21.1 version

### ISSUE THREAD

**Issue by Alan-Woj** [Zrips/Jobs#1827]
### Description of Issue

The plugin is not working at all with the 1.21.1 version neither with Spigot, nor with Craftbukkit...
Is there something I should do ?
Repository does not even show up after I start my server so I can't see the Jobs files.

### Version Information

```shell
Minecraft version : 1.21.1
Server : Spigot / Craftbukkit
```

### Relevant Plugins

Vault 1.7.3, EssentialsX-2.21.0-dev+115-6157668, RealPermissions v.0.4.2, worldedit-bukkit-7.3.6, worldguard-bukkit-7.0.12-dist

**Comment by Zrips** [comment]
Quite likely you forgot to install CMILib plugin which is required, you can always check console for any errors relating to specific plugins which might give you some idea what went wrong.

**Comment by Alan-Woj** [comment]
Exactly, thank you for your answer.
