### ISSUE TITLE
Could not pass event FurnaceSmeltEvent to Jobs v5.2.4.3

### ISSUE THREAD

**Issue by crumpkatrina** [Zrips/Jobs#1835]
### Description of Issue

Noticing this in in the console quite often lately.

### Version Information

```shell
Jobs: 5.2.4.3
CMILib: 1.5.1.4
Server: Paper 1.21.1-119-master@57c75a4
```

### Errors

```shell
https://pastebin.com/raw/pggy3VA6
```

### Relevant Config Sections

```yaml
No relevant configs
```

**Comment by Zrips** [comment]
59a0362292169eea82f46c5b07a48439b522ef01
