### ISSUE TITLE
jobs money limit bug , no reset , and error

### ISSUE THREAD

**Issue by p82183645** [Zrips/Jobs#1837]
### Description of Issue

jobs plugins
Please fix this feature
I set it to reset at 6:30am
But a small number of people will not be reset
I think there is something wrong with your data

This should reset for all players, regardless of whether they are online or not.
![image](https://github.com/user-attachments/assets/23eaeb63-371c-4d5f-9c9a-894043f3eb3b)

and some plugins error
![image](https://github.com/user-attachments/assets/599a2819-4b2c-4208-8db0-4b95d4c7e6c4)

### Version Information

```shell
5.2.4.3
```

**Comment by Zrips** [comment]
1d3b15ab87b61cb85533256d556571568ad39af0
