### ISSUE TITLE
jobs info - item display bug

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/Jobs#186]
Typing /jobs info [job] armorstands are displayed as cobweb, painting as still water and item frames as spruce leaves. The jobconfig.yml contains the correct itemname and a player will get the correct amount of money for crafting armorstands, cobweb and itemframes. So its "just" a very confusing display bug. I appreciate any help you can provide :).

```
      ARMOR_STAND:
        income: 0.84
        experience: 0.84
```
```
      PAINTING:
        income: 3.22
        experience: 3.22
```
```
      ITEM_FRAME:
        income: 4.29
        experience: 4.29
```
jobs info: https://imgur.com/a/6tux4

PaperSpigiot 1.12.2 - 1137
JobsReborn 4.5.1

**Comment by Zrips** [comment]
d10ee9f1d407f9d5f78ca7f8a8816b8e1c6f362d
