### ISSUE TITLE
REQUEST: Multiple Commands by reach Level X 

### ISSUE THREAD

**Issue by HomeLandingsDE** [Zrips/Jobs#189]
can you insert multiple commands?
Say, for example, if a player has reached level 10, the following should happen:

       Woodcutter1: #firstCommand
         command: pex user [player] group add woodcutter1
         levelFrom: 10
         levelUntil: 10
     woodcutterKit1:
         command: cmi kit woodcutter1 [player]
         levelFrom: 10
         levelUntil: 10

is that possible?

**Comment by montlikadani** [comment]
This already added, please update to the latest version.
