### ISSUE TITLE
EXTREME LAG WHEN EXECUTE A JOBS COMMAND

### ISSUE THREAD

**Issue by TheJuanGaymerMC** [Zrips/Jobs#190]
Jobs::Command: Jobs:jobscount(2)  total(0.45% 0.899s, 2.29% of tick)avg(449.39ms per - 1.15ms/0.00 per tick)

**Comment by arenmarsden** [comment]
I'm guessing you're using a flat file for jobs, from previous experience once the flat file gets too large it starts having trouble grabbing the data. I suggest switching to MySQL if you aren't already using it.

**Comment by juancruzdal** [comment]
With MySQL i got the same problem

**Comment by arenmarsden** [comment]
> With MySQL i got the same problem

Can you specify your servers specifications, please?

**Comment by arenmarsden** [comment]
> Spigot 1.8.8
8/4 cores
32GB RAM
and if i set the default config the problem persist

It's looking like you are either using an outdated version of the plugin or your databases aren't setup properly, I can't find anyone else having a similar issue.
