### ISSUE TITLE
Some EntityIDs do not work

### ISSUE THREAD

**Issue by Sandukhan** [Zrips/Jobs#192]
The "newer" EntityIDs like Zombie_Villager(bukkit/mc) or ZombieVillager (Jobs) doesnt work with the latest version of Jobs (I tested this with 4.5.3 and 4.5.2 on Spigot 1.12.) with a Kill event in the deafult jobConfig.
The mob is shown in the Jobinfo but no rewards like xp or money is given.

    Kill:
      ZombieVillager:
        income: 7.5
        points: 7.5
        experience: 7.5

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/blob/master/src/main/java/com/gamingmesh/jobs/CMILib/ItemManager.java#L383
This already fixed, please update to the latest version.
