### ISSUE TITLE
/jobs top

### ISSUE THREAD

**Issue by Seff300** [Zrips/Jobs#194]
Hi! When I do /jobs top Fisherman or type any other job name it kicks me out of the server and says
![2018-04-23_18 20 02](https://user-images.githubusercontent.com/37154442/39141256-ea9579fa-472f-11e8-9bb0-d0c4604edf1f.png)
Using Spigot 1.12.2 and Jobs 4.5.3

**Comment by Seff300** [comment]
Tried with other job names but still not working

**Comment by montlikadani** [comment]
It throws it out of the game because it puts a long word in the GUI somewhere. That is, in the configuration there is a long word, please send the jobConfig.yml file.

**Comment by Zrips** [comment]
Should be ok with next update
