### ISSUE TITLE
Option Shear does not reward players with Money and Job XP

### ISSUE THREAD

**Issue by Nelythia** [Zrips/Jobs#195]
I added the option to shear sheeps into the farmers job config however it does not reward players for shearing sheeps, despite having all colors and normal wool as option available.

Screenshots:
https://i.imgur.com/BksrZQE.png
https://i.imgur.com/FOf2UdY.png

*Landwirt = Farmer
*Scheren = Shear

Part of the config:

    Shear:

      WHITE_WOOL:

        income: 1.12

        experience: 1.0

      ORANGE_WOOL:

        income: 1.12

        experience: 1.0

      MAGENTA_WOOL:

        income: 1.12

        experience: 1.0

      LIGHT_BLUE_WOOL:

        income: 1.12

        experience: 1.0

      YELLOW_WOOL:

        income: 1.12

        experience: 1.0

      LIME_WOOL:

        income: 1.12

        experience: 1.0

      PINK_WOOL:

        income: 1.12

        experience: 1.0

      GRAY_WOOL:

        income: 1.12

        experience: 1.0

      LIGHT_GRAY_WOOL:

        income: 1.12

        experience: 1.0

      CYAN_WOOL:

        income: 1.12

        experience: 1.0

      PURPLE_WOOL:

        income: 1.12

        experience: 1.0

      BLUE_WOOL:

        income: 1.12

        experience: 1.0

      BROWN_WOOL:

        income: 1.12

        experience: 1.0

      GREEN_WOOL:

        income: 1.12

        experience: 1.0

      RED_WOOL:

        income: 1.12

        experience: 1.0

      BLACK_WOOL:

        income: 1.12

        experience: 1.0

**Comment by montlikadani** [comment]
This already fixed. Please update to the latest version.
