### ISSUE TITLE
limit resets in multi server

### ISSUE THREAD

**Issue by ysy960108** [Zrips/Jobs#198]
I have Jobs in 2 servers enabled and using the same database and want to set money/exp/point limit on them. 
But when player reaches limit in one server, if he goes to another server (using the same Jobs database) and goes back to the first one (and DO NOT use /jobs limit during this), the limit (in the first server) would be reset.

**Comment by smmmadden** [comment]
Maybe I'm missing something in what you stated or trying to do, but why would you want two servers/worlds sharing the same database.  Aside from possible locking issues and/or corruption from one world writing to the same database as another, it isn't something I would recommend.  I've got 8 servers with 4 being Spigot and each have Jobs Reborn on them, but none of them sharing the same database instance.  The only scenario I can think of is if you use BungeeCord Server and allowing teleporting between the two worlds and want to retain "the same" stats between them.  Meaning that the same jobs/xp/levels, etc are identical in both server/worlds.

Perhaps you can describe your setup and what errors if any you see in your logs.  Like what server and version you are on, Jobs Reborn Version, other plugins, etc.

**Comment by ysy960108** [comment]
These config options are in the GeneralConfig.yml , obviously they are for multiserver with same database instance.

```
save-on-disconnect: true 
MultiServerCompatability: true
```

Unfortunately, my scenario is exactly the only one, in these 2 servers almost everything on player should be the same, including the limit status of player in Jobs Reborn. 

What I have found is that when player quit the 2nd server(whether quit the BungeeCord or connect to 1st server), the data of this player in table 'job_limit' (contains data about limit) are just GONE.

A temporary solution is to set Triggers on this table in MySQL Server, to avoid delete from these entries, SQL code like these:

Avoid delete from entry:
```
DELIMITER $$
CREATE TRIGGER tg_jobs_limit_delete
BEFORE DELETE
ON job_limits
FOR EACH ROW
BEGIN
SET @nowtime =  (SELECT unix_timestamp()*1000),
    @diff = @nowtime - OLD.started;
    IF @diff<86400000 THEN
        SIGNAL sqlstate '45001' set message_text = "ERROR!";
    END IF;
END $$
DELIMITER ;
```

Avoid duplicate enrty:
```
DELIMITER $$
CREATE TRIGGER tg_jobs_limit_insert
BEFORE INSERT
ON job_limits
FOR EACH ROW
BEGIN
SET @userid_new =  (SELECT NEW.userid),
@type_new = (SELECT NEW.type),
@count = (SELECT COUNT(*) FROM job_limits WHERE (userid = @userid_new AND type = @type_new));
    IF @count>0 THEN
        SIGNAL sqlstate '45001' set message_text = "ERROR!";
    END IF;
END $$
DELIMITER ;
```

**Comment by Zrips** [comment]
adf91bea983d4626ac58d4d94e9e8ae77a4c9633
