### ISSUE TITLE
Bug with Schedule (Broadcast interval)

### ISSUE THREAD

**Issue by jere62smi** [Zrips/Jobs#199]
Hello,

I noticed that the cooldown option does not apply well, basically the cooldown does not respect the minutes I feel, I do not know if this is a bug or not but a priori, during my tests on my server, we were 3 and all receive the message but never in the agreed time.

My config:

```
 Enabled - with this false this schedule will be ignored
 From and Until is in 24 hours format with : signs to separate minutes and seconds
 Exp and Money determines how big is boost, to reset it. keep it at 1.0. so if you use 2.0 that means all money/exp is doubled
 Days variables: Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday, All
 Jobs can be any of your settup job or use All to give for all jobs at once
 BroadcastOnStart or BroadcastOnStop - set it false to disable message when boost starts/stops
 MessageOnStart or MessageOnStop - optional messages, if not given, then message from locale file will be shown
 BroadcastInterval - how often in minutes to broadcast message about money/exp boost for jobs
 BroadcastMessage - message to show every x minutes
```

Boost:
  ShortExpBoost:
    Enabled: true
    From: '12:00:00'
    Until: '00:00:00'
    Exp: 2.0
    Money: 1.0
    Days:
    - Sunday
    Jobs:
    - Mineur
    - Chasseur
    - Pêcheur
    - Bûcheron
    - Aubergiste
    - Fermier
    - Assassin
    - Sorcier
    BroadcastOnStart: true
    MessageOnStart:
    - '&a***********************************************'
    - '    &2Boost Xp x2 pour tous les métiers !'
    - '    &2De 12h00 à 00h00 !'    
    - '&a***********************************************'
    BroadcastOnStop: true
    MessageOnStop:
    - '&a***********************************************'
    - '    &2Boost métiers terminé !'
    - '    &2De retour Dimanche de 12h00 à 00h00 !'
    - '&a***********************************************'
    BroadcastInterval: 30
    BroadcastMessage:
    - '&a***********************************************'
    - '    &2Boost Xp x2 pour tous les métiers !'
    - '    &2De 12h00 à 00h00 !'    
    - '&a***********************************************'

**Comment by montlikadani** [comment]
**Try update to the latest version.**
