### ISSUE TITLE
REDSTONE_ORE automatically changed to GLOWING_REDSTONE_ORE

### ISSUE THREAD

**Issue by klugemonkey** [Zrips/Jobs#202]
In 1.13, there is no specific block for GLOWING_REDSTONE_ORE as the glowing effect is a state, so the block will not change when the user interacts with it.

The configuration loader is changing references to REDSTONE_ORE to GLOWING_REDSTONE_ORE automatically.  This "feature" should be disabled for 1.13.

[Jobs] Job Miner is using REDSTONE_ORE instead of GLOWING_REDSTONE_ORE.
[Jobs] **Automatically changing block to GLOWING_REDSTONE_ORE.**  Please update your configuration.
[Jobs] In vanilla minecraft, REDSTONE_ORE changes to GLOWING_REDSTONE_ORE when interacted with.
[Jobs] In the future, Jobs using REDSTONE_ORE instead of GLOWING_REDSTONE_ORE may fail to work correctly.

**Comment by Zrips** [comment]
6d239bf83dbdabe0ed6462aeada3889da77a92eb
