### ISSUE TITLE
MELON not recognized as block for Break or Place

### ISSUE THREAD

**Issue by klugemonkey** [Zrips/Jobs#203]
Doesn't look like MELON is being recognized as a proper block type on 1.13.

[Jobs] Job Farmer has an invalid Break type property: MELON! Material must be a block!
[Jobs] Job Farmer has an invalid Place type property: MELON! Material must be a block!

On 1.12 and earlier versions, MELON referred to the melon slice, and MELON_BLOCK was the block.  This is no longer the case for 1.13, as it is MELON for the block, and MELON_SLICE for the slice.

**Comment by montlikadani** [comment]
Yes, do not recognize that the melon is block or slices.
https://github.com/Zrips/Jobs/blob/master/src/main/java/com/gamingmesh/jobs/CMILib/ItemManager.java#L1092 and this https://github.com/Zrips/Jobs/blob/master/src/main/java/com/gamingmesh/jobs/CMILib/ItemManager.java#L1090
The two links where there is a marked similarity are, and therefore do not recognize it.
