### ISSUE TITLE
Entities don't work in jobs

### ISSUE THREAD

**Issue by MasterGordon** [Zrips/Jobs#204]
Actions just display/use "Player" as Entities in jobs like the hunter (tame, kill animals...) and farmer job (shear, milk cow, breed, tame).
Only some like the Chicken and Rabbit work
(no errors)

**Comment by Fabrimat** [comment]
For me only works Chicken and Rabbit

**Comment by Flexxxxx** [comment]
Same issue here. Also isn't listing any Mythic Mobs either.

**Comment by DonSensiLeone** [comment]
1.13.2 Paper 627 , Jobs 4.12.0 
Job Hunter doesn't pay for passive mobs (Kill : Cow , Chicken , Sheep , Pig , Rabbit , Mooshroom , Squid ) (Breed : same except Squid ) and some hostile mobs (Kill : Silverfish , Ghast , Magma_cube & Slime smaller than the biggest)  , pastebin from my jobconfig : https://pastebin.com/bGmiHHLT ( starting at line 258 )

**Comment by montlikadani** [comment]
@DonSensiLeone Did you tried with only lower-cased chars? Such as `cow`, `chicken`

**Comment by DonSensiLeone** [comment]
oh , it was Cow , Chicken .. before then i tried to write upper case , i'll try lower case
