### ISSUE TITLE
Claiming Brewing Stand

### ISSUE THREAD

**Issue by Momonche** [Zrips/Jobs#205]
Hello,
I have a problem with the brewing stand, when a player claim a brewing stand and destroy it, the place of this brewing stand stay claim for the player.
But this system with furnaces work fine.

**Comment by montlikadani** [comment]
**Try update to the latest version.**

**Comment by Momonche** [comment]
I just test that issue on 4.7.2

**Comment by montlikadani** [comment]
Does the player have Builder's job? In the jobConfig.yml file, is there a block type in the Place method that is Brewing_Stand?

**Comment by Momonche** [comment]
Nothing of that, I don't use the Builder's job

**Comment by montlikadani** [comment]
I'll test it and, if that's what it is, we'll try to fix it. If it works properly, it may take time.
