### ISSUE TITLE
Jobs not registering some actions.

### ISSUE THREAD

**Issue by postal291** [Zrips/Jobs#206]
Spigot 1.12.2
Jobs 4.6.0
Vault 1.6.6
EssentialsX 2.0.15.1

Pastebin of my jobConfig.yml: [https://pastebin.com/Jua0b1Ru](https://pastebin.com/Jua0b1Ru)
Pastebin of my generalConfig.yml: [https://pastebin.com/tiLy2S0Q](https://pastebin.com/tiLy2S0Q)

Woodcutter:
- No actions registered for payment/xp/points gains
- Commented out the example job in jobConfig.yml (as it was woodcutter)
- Tried a few ways of referencing the blocks (block names, single quotes block ID's)

Miner: Works perfectly as far as I can tell.

Builder: 
- Placing any block which would have a data value doesn't seem to register (planks, wool, slabs, etc...)

Digger: Works perfectly as far as I can tell.

Farmer:
- Taming not registering
- Breeding not registering (with any animals)
- Shearing not registering
- Breaking of carrots, potatoes, beetroot, saplings, lilypads, dandelions, poppy (and other data values for it), and melons not working.

Hunter:
- Taming not registering
- Killing of sheep, cow, wolf, pig, creeper, zombie, skeleton, spider all don't register gains.

Explorer: Works perfectly as far as I can tell.

Crafter: Works perfectly as far as I can tell.

Fisherman: Works perfectly as far as I can tell.

Weaponsmith: Works perfectly as far as I can tell.

Brewer: Works perfectly as far as I can tell.

Enchanter: Doesn't seem to register any book enchantments.  (It's all I do, didn't test other items)

(Sorry if this is a little long-winded or repetitive, wanted to be thorough.)

**Comment by postal291** [comment]
Spigot 1.12.2
Jobs 4.6.2
Vault 1.6.6
EssentialsX 2.0.15.1

my yml's were deleted and regenerated when updating to 4.6.2

Straight out of the box throws these:
[14:30:36 INFO]: [Jobs] Your defined (93) protected block id/name is not correct!
[14:30:36 INFO]: [Jobs] Your defined (149) protected block id/name is not correct!
[14:30:36 INFO]: [Jobs] Your defined (83) protected block id/name is not correct!
[14:30:36 INFO]: [Jobs] Your defined (115) protected block id/name is not correct!

Tried using the /jobs blockinfo block names instead of the ID numbers, same errors thrown.
redstone repeaters, comparators, sugar cane and nether warts are problematic.

[14:30:37 WARN]: [Jobs] Job Miner has an invalid Break type property: NETHER_BRICK! Material must be a block!
[14:30:37 WARN]: [Jobs] Job Digger has an invalid Break type property: CLAY! Material must be a block!
[14:30:37 WARN]: [Jobs] Job Farmer has an invalid Break type property: SUGAR_CANE_BLOCK!
[14:30:37 WARN]: [Jobs] Job Farmer has an invalid Break type property: 115!
[14:30:37 WARN]: [Jobs] Job Farmer has an invalid Place type property: SUGAR_CANE_BLOCK!

Was able to resolve the NETHER_BRICK by changing it's reference to '112'
Was able to resolve the CLAY by changing it's reference to '82'
SUGAR_CANE_BLOCK throws the same "invalid Break type property" error when using it's ID number.
115 (netherwart) throws the same "invalid Break type property" when using it's block name.

Woodcutter:

No actions registered for payment/xp/points gains
Commented out the example job in jobConfig.yml (as it was woodcutter)
Tried a few ways of referencing the blocks (block names, single quotes block ID's)
Miner: Works perfectly as far as I can tell.

Builder:

Placing any block which would have a data value doesn't seem to register (planks, wool, slabs, etc...)
Digger: Works perfectly as far as I can tell.

Farmer:

Taming not registering
Breeding not registering (with any animals)
Shearing not registering
Breaking of sugarcane, netherwart, carrots, potatoes, beetroot, saplings, lilypads, dandelions, poppy (and other data values for it), and melons not working.
Hunter:

Taming not registering
Killing of sheep, cow, wolf, pig, creeper, zombie, skeleton, spider all don't register gains.
Explorer: Works perfectly as far as I can tell.

Crafter: Works perfectly as far as I can tell.

Fisherman: Works perfectly as far as I can tell.

Weaponsmith: Works perfectly as far as I can tell.

Brewer: Works perfectly as far as I can tell.

Enchanter: Doesn't seem to register any book enchantments. (It's all I do, didn't test other items)

(Sorry if this is a little long-winded or repetitive, wanted to be thorough.)

**Comment by montlikadani** [comment]
Try updating to the latest version (4.7.2) if it does not work again, please write.

**Comment by Zrips** [comment]
Should work correctly with next official update
