### ISSUE TITLE
Cant gain money on 4.7.2 + Error

### ISSUE THREAD

**Issue by SoraShiunin** [Zrips/Jobs#214]
https://pastebin.com/DbgnqYL0
Simple as that, cant gain money, that error appears sometimes in console (when someone joins?).

**Comment by montlikadani** [comment]
This is duplicate of #209 & #210

**Comment by SoraShiunin** [comment]
About that 'cant gain money' issue hummmm

**Comment by montlikadani** [comment]
Is the official Vault plugin installed?
Did you edit something in this feature?:
``
income-progression-equation: baseincome+(baseincome*(joblevel-1)*0.01)-((baseincome+(joblevel-1)*0.01) * ((numjobs-1)*0.05))
``
