### ISSUE TITLE
Meta-id no longer works in 1.13

### ISSUE THREAD

**Issue by jere62smi** [Zrips/Jobs#218]
Hello, After several job tests in version 1.13, I realized that some of my old configs were not working properly. I will give an example: 

Break: 
POTATO-7: 
income: 0.07 
experience: 0.10 

Before the potatoes gave that reward and experience when it was in "final" state, ie pushed to the maximum but now no. I have the impression that the meta-id no longer works with the 1.13 on jobs, I looked on the Java doc but there is no other specific id for it. I hope you can help me solve this problem, I've done a lot of different ids to see if this has changed, with "" and others.

**Comment by smmmadden** [comment]
The ID's have changed and I did provide updated xml files to @Zrips last week.  They most likely not been added to source yet for the latest build.  Here is a list I've been using to manually change them in my files: [https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html)

**Comment by jere62smi** [comment]
Yes but my material is good, I think there is a problem with the meta-id because when I harvest potatoes pushed or not I still earn the money when I should win that when it is pushed to the maximum.

**Comment by Zrips** [comment]
Actually material is not good as now its POTATOES-7, ask Mojang why...

**Comment by Nogapra** [comment]
Spigot may have changed their APIs and digital function no longer exists to define a plant age of growing state.
