### ISSUE TITLE
Not grown plants give money

### ISSUE THREAD

**Issue by CryingFox** [Zrips/Jobs#221]
I have a farmer job where you have to break full grown crops to earn money.
The jobconfig.yml looks like this : 

    Break:
      BEETROOT_BLOCK-3:
        income: 1
        points: 1.5
        experience: 4
      CROPS-7:
        income: 2
        points: 1.5
        experience: 5
      CARROTS-7:
        income: 1
        points: 1.0
        experience: 4
      POTATOES-7:
        income: 1
        points: 1.0
      COCOA-2:
        income: 0.5
        points: 4
        experience: 3.5

But when i break not grown crops (just planted / first stage) it gives me money anyway. I thinks the data values don't work in 1.13 because of the new IDs system without data values.

**Comment by montlikadani** [comment]
Did you try with ID instead of names?

**Comment by CryingFox** [comment]
Yep, same problem using IDs.

**Comment by montlikadani** [comment]
_Fixes, [commit_](https://github.com/Zrips/Jobs/commit/643b9dc842ffd393397c5ae674a6125a10fe24be)

**Comment by Zrips** [comment]
ac31db0927384f66c1862582c5e91081f86bedbf
