### ISSUE TITLE
Quest doesn't work with wooden logs

### ISSUE THREAD

**Issue by Fabrimat** [Zrips/Jobs#222]
If I create a quest and as target i insert "17-0", "LOG-0" or anything like this it doesn't register the action and the quest remains at 0%

>       1:
>         Name: "Rompi Oak Wood"
>         Action: Break
>         Target: "17-0"
>         Amount: 60
>         RewardCommands: 
>         - "acb [playerName] 50"
>         - "msg [playerName] Quest completata!"
>         RewardDesc: 
>         - "Rompi 60 blocchi di legno grezzo"
>         - "Ottieni 50 blocchi di claim!"
>         Chance: 100

**Comment by montlikadani** [comment]
Do not type -0 after the ID.
I mean that:
`17`

**Comment by smmmadden** [comment]
I would refrain from using the numeric ID's as they are being phased out.  1.13 removed tons and most developers are moving to Material ID's instead (names) which is where we've been trying to get to for years.  https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

**Comment by Fabrimat** [comment]
If I set Target: "OAK_WOOD" it says [Jobs] Loaded 0 quests for Woodcutter and it doesn't load the quest.
PS I am using Jobs 4.7.4 on Spigot 1.12

**Comment by montlikadani** [comment]
Did you try to replace OAK_WOOD with [OAK_LOG](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html#OAK_LOG)?

Otherwise, you can look at material IDs and names: https://minecraft-ids.grahamedgecombe.com/

**Comment by Fabrimat** [comment]
It doesn't work neither with OAK_LOG nor with minecraft:log (with this last one it doesnt load the quest)
I also tried something like POTATO-7 and doesn't work, the only things that works are stone and ores (STONE, COAL_ORE...)

**Comment by Fabrimat** [comment]
And with "17-0" the job works, just the quests don't

**Comment by smmmadden** [comment]
@Zrips - any update on this issue?  Thanks, Steve

**Comment by Zrips** [comment]
This should be working with next update.
