### ISSUE TITLE
TranslatableWords doesn't work in 1.13.1

### ISSUE THREAD

**Issue by HansscMe** [Zrips/Jobs#224]
I set locale-language to zhcn in the generalConfig,the message-zhcn.yml works well,but the World_zhcn.yml doesn't work.
Then,I set it to zhtw,but it still doesn't work.
I'm using 4.7.4,the newest version.
Please fix it,
THX.

**Comment by montlikadani** [comment]
Send an error message to the console?

_World_zhcn.yml_ What is this file? Such a file does not exist, but is like this: `Words_zhcn`

**Comment by DmitryRendov** [comment]
the same for me

**Comment by Zrips** [comment]
a6a02b3ef4423d66b0bf246c70aa05801a14f1d6
