### ISSUE TITLE
PlaceholderAPI expansion uses uncached MySQL calls

### ISSUE THREAD

**Issue by tlaundal** [Zrips/Jobs#228]
This was the most appropriate place I found to post this issue.

The PlaceholderAPI expansion for Jobs Reborn currently does MySQL calls for every placeholder, every time it is used, which is extremely expensive as most placeholders are executed on the main server thread.

I suggest a warning is written next to the placeholders in the [placeholder list](https://www.spigotmc.org/wiki/placeholderapi-plugin-placeholders-page-1/#jobs-reborn), and that at least a cache is introduced so the MySQL queries aren't executed every time the placeholders are used.

The ideal solution would be to load that data into memory, or use data already in memory, so no MySQL calls would have to be made at all.

**Comment by totokaka** [comment]
So this means the jobs expansion for Placeholderapi is not created by you / the creators of jobs?
