### ISSUE TITLE
jobs top returns no results for one player

### ISSUE THREAD

**Issue by smmmadden** [Zrips/Jobs#231]
While it is rare that only one player would be earning money in jobs, testing the plugin on 4.8.0 and 1.13.1 (Paper), it makes it hard to tell if the command is working when no results are returned.  If there is a record, it should be returned regardless how many there are.
/jobs top (in-game and server console)
[17:22:38 INFO]: Usage: /Jobs top [jobname]
[17:22:38 INFO]: * Shows top 15 players by jobs name.
>

**Comment by smmmadden** [comment]
@Zrips - any update on this issue?  Thanks, Steve

**Comment by Zrips** [comment]
Hmmm, that one works with only one player in list. After next official update, try to retest it and if issue still there for you, reopen ticket and we will have second look.

**Comment by smmmadden** [comment]
will do - thanks!
