### ISSUE TITLE
jobs browse on server console only returns 10 rows

### ISSUE THREAD

**Issue by smmmadden** [Zrips/Jobs#232]
While testing Jobs 4.8.0 with 1.13.1 (Paper), I typed in jobs browse on the server console to check for the jobs I've configured and only 10 of the 15 are shown when all 15 should be returned.
> jobs browse
[17:24:33 INFO]: ========== 15 Available Jobs =========
[17:24:33 INFO]:     1. TreeFarmer
[17:24:33 INFO]:     2. Woodcutter
[17:24:33 INFO]:     3. Miner
[17:24:33 INFO]:     4. Builder
[17:24:33 INFO]:     5. Digger
[17:24:33 INFO]:     6. Farmer
[17:24:33 INFO]:     7. Hunter
[17:24:33 INFO]:     8. Explorer
[17:24:33 INFO]:     9. Crafter
[17:24:33 INFO]:     10. Fisherman

**Comment by montlikadani** [comment]
You just need to enter the page number to get the list of other jobs. And in the configuration (generalConfig.yml) you can set the maximum page number. `JobsBrowse.AmountToShow`
E.g: /jobs browse 2

**Comment by smmmadden** [comment]
I tried multiple variations of jobs browse 2, jobs browse next and jobs browse page 2 and no difference.  It's a bug in the command being executed from the console.  I've similar behavior when testing Residence.

**Comment by montlikadani** [comment]
Now, the `/jobs browse` command shows all the jobs in the console and not a specified one.

**Comment by smmmadden** [comment]
excellent news @montlikadani - thanks for fixing it :-)

**Comment by montlikadani** [comment]
_I've released a DEV. version which includes lots of fixes, add new items, and more. [release](https://github.com/Zrips/Jobs/releases), You can test it._

**Comment by smmmadden** [comment]
jobs browse on console now returns 0 rows
[15:02:30 INFO]: =========== 15 Available Jobs ==========

**Comment by montlikadani** [comment]
@smmmadden 
I have fixed and uploaded the file: https://github.com/Zrips/Jobs/releases

**Comment by smmmadden** [comment]
the link you provided shows only a zip file and uncompiled. We'll need the compiled jar file to use it.

**Comment by montlikadani** [comment]
Zrips update the plugin now, I think.

**Comment by smmmadden** [comment]
The latest dev build added now returns results.  Not the cleanest display but that can always be improved on as time permits.
Here is what it looks like in the latest.log
![image](https://user-images.githubusercontent.com/10309346/46881713-59734c00-ce1a-11e8-97ff-ea4329874526.png)

Here is what it actually looks like on the console - note that the screen is maximized.  A single line for each should be used for each job (15 total for me). Otherwise it is a bit messy to read. :-)
![image](https://user-images.githubusercontent.com/10309346/46881752-70b23980-ce1a-11e8-8fe3-a866cd8f3c30.png)

**Comment by montlikadani** [comment]
How would you like the best in the console? One or two changes can be made in the messages file. It is not very nice to create a nice message format in a console.

**Comment by smmmadden** [comment]
similar to the below would of course be ideal
![image](https://user-images.githubusercontent.com/10309346/46884788-11f1bd80-ce24-11e8-84db-f0d8ca8ab145.png)

**Comment by montlikadani** [comment]
Are the arrows replaced by spaces?
I remove new lines from the code.

**Comment by smmmadden** [comment]
yes, those are tabs from Notepad++ to let me know when yaml files are not formatted right.  They can be ignored in the screenshot.  It was more for alignment purposes if possible.
