### ISSUE TITLE
FullDescription not visible to any command/player

### ISSUE THREAD

**Issue by smmmadden** [Zrips/Jobs#235]
During testing of Jobs 4.8.0 with 1.13.1 (Paper), I can add the FullDescription field to the jobConfig.yml, but it is not visible to users or using any commands.
![image](https://user-images.githubusercontent.com/10309346/45123133-e4826780-b133-11e8-8e30-b91ce05035f8.png)
![image](https://user-images.githubusercontent.com/10309346/45123245-4ba01c00-b134-11e8-905c-cd201453c062.png)
Left click shows details of that job earnings but no full description either.
![image](https://user-images.githubusercontent.com/10309346/45123277-64103680-b134-11e8-9e60-81232fac3c6f.png)

**Comment by smmmadden** [comment]
please be more specific - type what with the job name?  Show an example, as I've not seen it appear for any command. As shown above, I did /jobs info Builder and neither short or full descriptions are returned.

**Comment by montlikadani** [comment]
Oh, you can disable this function, `JobsGUI.OpenOnBrowse` and enable this if you want to display the jobs in chat, `JobsGUI.ShowChatBrowse`.
Example command: /jobs browse [jobname]

**Comment by smmmadden** [comment]
@montlikadani what are you talking about??  The bug is about the FullDescription not showing up in any way other than the configuration file.  I did use the /jobs browse as did someone else.  I think this is a question for @Zrips to answer since it appears you may not know.

**Comment by montlikadani** [comment]
Zrips will not answer because I told him I could help with the plugin development and added, so I'll help her. **As I said, FullDescription will not appear in the GUI because it is not added.** FullDescription will only appear in chat when `JobsGUI.ShowChatBrowse` is enabled and `JobsGUI.OpenOnBrowse` is disabled.

**Comment by smmmadden** [comment]
okay, then there is a different bug.  As you identified, I had JobsGUI: OpenOnBrowse: true and ShowChatBrowse: true
Once I set OpenOnBrowse: false as suggested, now we see nothing - no jobs or GUI
![image](https://user-images.githubusercontent.com/10309346/45220495-4948d980-b27c-11e8-8028-52c307edb26f.png)

![image](https://user-images.githubusercontent.com/10309346/45220559-7f865900-b27c-11e8-95b2-d143a788a7ba.png)

**Comment by montlikadani** [comment]
Hm... I've fixed the console error, soon the commit is coming. I also try to fix the player in the game, as this will indicate to me on the chat.

**Comment by smmmadden** [comment]
Thanks - I think it would be better to also allow the FullDescription to be visible on the GUI of jobs browse - when someone left clicks to get more info. Even if it means adding a block to show it since it could be multiple lines. Turning off GUI just to see a full description doesn't sound right, when most users want GUI's. :-)
![image](https://user-images.githubusercontent.com/10309346/45222253-068a0000-b282-11e8-9030-ec640c8558c2.png)

**Comment by smmmadden** [comment]
@Zrips - any update on this issue?  Thanks, Steve

**Comment by montlikadani** [comment]
_I've released a DEV. version which includes lots of fixes, add new items, and more. [release](https://github.com/Zrips/Jobs/releases), You can test it._

**Comment by smmmadden** [comment]
The FullDescription is not fixed in the 4.8.1 Dev release.  There are no more errors, but still no where does it show FullDescription.

**Comment by Zrips** [comment]
Showing full description would cover entire screen in some situations, so need to have that one.
For error that one is fixed with
99f13e5c475750614385ac2a62d19a35a56aa4be
