### ISSUE TITLE
Meta-id not work in 1.13

### ISSUE THREAD

**Issue by jere62smi** [Zrips/Jobs#241]
Hello, After several job tests in version 1.13, I realized that some of my old configs were not working properly. I will give an example:

Break:
POTATO-7:
income: 0.07
experience: 0.10

Before the potatoes gave that reward and experience when it was in "final" state, ie pushed to the maximum but now no. I have the impression that the meta-id no longer works with the 1.13 on jobs, I looked on the Java doc but there is no other specific id for it. I hope you can help me solve this problem, I've done a lot of different ids to see if this has changed, with "" and others.

**Comment by montlikadani** [comment]
Duplicate and same, #218
