### ISSUE TITLE
Breaking trees does not count

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/Jobs#246]
If adding logs to the woodcutter job - breaking the logs does not count; however, stripping the logs then breaking them does work. 

      acacia_log:
        income: 1.6
        points: 0.0
        experience: 0.5
      birch_log:
        income: 1.6
        points: 0.0
        experience: 0.5
      dark_oak_log:
        income: 1.6
        points: 0.0
        experience: 0.5
      jungle_log:
        income: 1.6
        points: 0.0
        experience: 0.5
      oak_log:
        income: 1.6
        points: 0.0
        experience: 0.5
      SPRUCE_LOG:
        income: 1.6
        points: 0.0
        experience: 0.5
      stripped_acacia_log:
        income: 1.6
        points: 0.0
        experience: 0.5
      stripped_birch_log:
        income: 1.6
        points: 0.0
        experience: 0.5
      stripped_dark_oak_log:
        income: 1.6
        points: 0.0
        experience: 0.5
      stripped_jungle_log:
        income: 1.6
        points: 0.0
        experience: 0.5
      stripped_oak_log:
        income: 1.6
        points: 0.0
        experience: 0.5
      stripped_spruce_log:
        income: 1.6
        points: 0.0
        experience: 0.5

**Comment by Sprungente** [comment]
Yes because Jobs Reborn mean that OAK_log (and other logs) is a stripped_oak_log

it's a bug i think

**Comment by montlikadani** [comment]
STRIPPED_LOGs are not yet supported. It's given, but Minecraft has not given IDs on it, so it does not work.

**Comment by smmmadden** [comment]
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
There are enum constants for stripped logs.  
![image](https://user-images.githubusercontent.com/10309346/46419915-ef152a00-c6fc-11e8-80aa-d92d45588fdf.png)

**Comment by montlikadani** [comment]
All right. You use it, sometimes I too. But even the official site does not write the ID because it has not yet been completely released.

**Comment by Sprungente** [comment]
Use /jobs iteminfo with logs in the hand and use the number instead of the name. That should it fix temporary

**Comment by montlikadani** [comment]
@Sprungente 
It does not matter that material name or an ID, as both will give the same.

**Comment by Sprungente** [comment]
I have the issues too 
Jobs looks Oak_log as Stripped_oak_log

**Comment by Sprungente** [comment]
Example: 

I use this:
https://hastebin.com/noteloloya

and the result: https://picload.org/view/dcrrrrrw/jobsi.png.html

Hopes it helps you to fix^^

**Comment by Zrips** [comment]
7b8fa29cd441c010bf6067d1e0ec774322d3942e
