### ISSUE TITLE
Crafting job issues

### ISSUE THREAD

**Issue by LogGits** [Zrips/Jobs#251]
My players are reporting that crafting sticks aka 180 doesnt pay them. It's currently set to give 0.1 exp,money,points. Any idea on this one? I tested it out and i can confirm getting no money from it. I have cmi vault 1.6.11.

**Comment by montlikadani** [comment]
Do you use JobsReborn plugin? If you use CMI, then this is not JobsReborn error.

**Comment by LogGits** [comment]
Yeah i use jobsreborn

**Comment by montlikadani** [comment]
This error has just been fixed. It will be visible in the next commit release. [bug](https://github.com/Zrips/Jobs/blob/master/src/main/java/com/gamingmesh/jobs/CMILib/ItemManager.java#L1413)

**Comment by LogGits** [comment]
XDDD I was looking everywhere in the code for potential issues. ofc it was the wrong id haha. Cheers @monochrome-blue thanks for the help.

**Comment by montlikadani** [comment]
wut?
