### ISSUE TITLE
Error in job miner : invalid Break type

### ISSUE THREAD

**Issue by ltsquellette** [Zrips/Jobs#258]
Hello, i've installed your plugin Jobs4.8.0 recently and I noticed a warning in my console when I launched the server :

[Jobs] Job Miner has an invalid Break type property: NETHER_BRICK (NETHER_BRICK)! Material must be a block!

The only thing i've done to correct this is to replace NETHER_BRICK in jobConfig.yml by NETHER_BRICKS.
I don't know if this needs to be fixed but I wanted to warn the author about it.

Thanks for reading me.
~ltsquellette

**Comment by smmmadden** [comment]
It's wrong in the 4.8.0 build, but correct in the 4.8.1 build.  I'd recommend taking the latest build as it fixes a number of other reported issues besides this one.
