### ISSUE TITLE
birch log registering as oak?

### ISSUE THREAD

**Issue by smmmadden** [Zrips/Jobs#259]
PaperSpigot: 1.13.1 (build 355) with the 4.8.0-Dev build, when I use /itemdb on the birch log in my hand, it returns as OAK, not BIRCH.
![image](https://user-images.githubusercontent.com/10309346/46844043-5426ea80-cda3-11e8-8981-ab67a63ac454.png)

Also note that the plugin.yml version does not match the version listed on this project that was done today.
![image](https://user-images.githubusercontent.com/10309346/46844090-918b7800-cda3-11e8-8bc6-5e9c0b89e2c7.png)
![image](https://user-images.githubusercontent.com/10309346/46844120-b2ec6400-cda3-11e8-988b-d33f43c44553.png)

**Comment by montlikadani** [comment]
wut? This is not the JobsReborn command, this EssentialsX cmd.

**Comment by smmmadden** [comment]
Just entered issue on EssentialsX for this.  Thanks!
