### ISSUE TITLE
[Issues] max Level missing in Jobsbrowse

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/Jobs#261]
The Max level in Jobs Brows is missing

Official 4.8.0
![image](https://user-images.githubusercontent.com/12080017/46898856-3e8def80-ce8d-11e8-8364-d83e1ddf73a9.png)

Dev 4.8.0
![image](https://user-images.githubusercontent.com/12080017/46898873-641af900-ce8d-11e8-937e-2be29800fe1e.png)

**Comment by Nogapra** [comment]
I have the same things

**Comment by montlikadani** [comment]
_Fixed, [commit](https://github.com/Zrips/Jobs/commit/5e64f83605993563373235607fdf7e68e81ab220#diff-876b21b4a1e3a78479e9e24b8e4747f5)_

**Comment by CloudeLecaw** [comment]
hmm are they deleted? :3

**Comment by montlikadani** [comment]
Yes, I deleted it because Zrips update the plugin soon.
