### ISSUE TITLE
[Issue] version 4.9.1 colors in translatable words_xx.yml

### ISSUE THREAD

**Issue by Sulort** [Zrips/Jobs#267]
Hi,

in the translatable words_de.yml there are two colors not working. I think it is also not working in all different language word files.

3-lightBlue: '&9Hellblau'      it should be       3-light_blue: '&9Hellblau'
8-silver: '&7Hellgrau'            it should be       8-light_gray: '&7Hellgrau'

**Comment by montlikadani** [comment]
In translatable words file does not support for colors.

**Comment by Sulort** [comment]
So, maybe there is a misunderstanding-problem between us.
Here is the part of the colors in the translatable words-file:

ColorList:
  0-white: '&fWhite'
  1-orange: '&6Orange'
  2-magenta: '&dMagenta'
  3-lightBlue: '&9Light blue'
  4-yellow: '&eYellow'
  5-lime: '&aLime'
  6-pink: '&dPink'
  7-gray: '&8Gray'
  8-silver: '&7Light gray'
  9-cyan: '&3Cyan'
  10-purple: '&5Purple'
  11-blue: '&1Blue'
  12-brown: '&4Brown'
  13-green: '&2Green'
  14-red: '&cRed'
  15-black: '&0Black'

there are colors, and there is a support, also in the different language files. 
take a look at the job farmer. there you will get paid for shearing. the color silver is not working.
but the color light_gray is working perfectly!!! and there is also the color light_blue (with an underline).
In the translatable words file you can translate the names for the colors. 
But there is still the problem only for the two colors lightblue and silver. it must be light_blue and light_gray. Could you please fix it. thanks a lot.

**Comment by montlikadani** [comment]
Uh.. I'm sorry, this is really a mistake. :(
This error also occurred to me, but it does not show all the colors. We're trying to fix it.

**Comment by Sulort** [comment]
Hi,
im sry, but your fix is not working. Please change the names of the colors in the following section of the file in:
src/main/java/com/gamingmesh/jobs/config/NameTranslatorManager.java

	    // Color list
	    c.get("ColorList.0-white", "&fWhite");
	    c.get("ColorList.1-orange", "&6Orange");
	    c.get("ColorList.2-magenta", "&dMagenta");
	    c.get("ColorList.3-lightBlue", "&9Light blue");  	    c.get("ColorList.3-light_blue", "&9Light blue");
	    c.get("ColorList.4-yellow", "&eYellow");
	    c.get("ColorList.5-lime", "&aLime");
	    c.get("ColorList.6-pink", "&dPink");
	    c.get("ColorList.7-gray", "&8Gray");
	    c.get("ColorList.8-silver", "&7Light gray");            c.get("ColorList.8-light_gray", "&7Light gray");
	    c.get("ColorList.9-cyan", "&3Cyan");
	    c.get("ColorList.10-purple", "&5Purple");
	    c.get("ColorList.11-blue", "&1Blue");
	    c.get("ColorList.12-brown", "&4Brown");
	    c.get("ColorList.13-green", "&2Green");
	    c.get("ColorList.14-red", "&cRed");
	    c.get("ColorList.15-black", "&0Black");

The color light_gray is already existing in the code. maybe the color Light should be changed into Light_Blue. Take a look at the file
/src/main/java/com/gamingmesh/jobs/CMILib/ItemManager.java from line 321

 public enum colorNames {
	White(0, "White"),
	Orange(1, "Orange"),
	Magenta(2, "Magenta"),
	Light(3, "Light Blue"),
	Yellow(4, "Yellow"),
	Lime(5, "Lime"),
	Pink(6, "Pink"),
	Gray(7, "Gray"),
	Light_Gray(8, "Light Gray"),
	Cyan(9, "Cyan"),
	Purple(10, "Purple"),
	Blue(11, "Blue"),
	Brown(12, "Brown"),
	Green(13, "Green"),
	Red(14, "Red"),
	Black(15, "Black");

thanks a lot

**Comment by montlikadani** [comment]
I'm so sorry I'm making a lot of mistakes, but I'm not a big plugin coder.
You could have opened a [Pull Request](https://github.com/Zrips/Jobs/pulls) for this and I merge it.

**Comment by Sulort** [comment]
i think we are all in the same situation. i'm also not a big plugin coder. so i also don't know exactly you to solve this problem. i only explaint my suggestion in the post befor. maybe you can test this, and if it's working then pls put it into your dev version. this would be very nice. thanks a lot, i appreciate it

**Comment by montlikadani** [comment]
I fixed this bug. I'm releasing a DEV now. version to test.
You will need to use it:
```
3-light blue: '&9Light blue'
5-lime green: '&aLime'
8-light gray: '&7Light Gray'
```

**Comment by Sulort** [comment]
i'm sry, but the color lime was ok. there wasn't a problem, only with the colors lightblue and silver.
now light_blue and light_gray are working perfectly.
But with your changes for the color lime there is a problem with this color.
could you pls change only the code for the color lime into the original code. 
thanks a lot.

**Comment by montlikadani** [comment]
No, I couldn't change the lime_green to lime because it has buggy. So, if I had to change it back to the original, it would be wrong, because that was the problem.

**Comment by Sulort** [comment]
Hi, ok i can use lime_green but it's only working when i'm also using lime_green in the jobconfig.yml for shearing wool in the farmer job. so far so good. but you would not be payed for shearing lime_green.
i think  you also have to change lime into lime_green in the relevant code for the jobconfig.

could you pls test it. thanks for your hard work.

**Comment by montlikadani** [comment]
Re-opened, because this could not be done because it did not work under my test. I tried to change the color name, but I did not succeed. Sorry!
