### ISSUE TITLE
Modify Chat

### ISSUE THREAD

**Issue by navlis3** [Zrips/Jobs#270]
Hi,

I've updated my Minecraft server to v1.13.1 and also Jobs to v4.9.1. As Chatmanager i use the newest version of EssentialsX. After the update no jobs where displayed in the chat. I've turned on modify chat (of course). After that I turned it off and placed in the Essentials config a {jobs} tag (i've read that in the wiki) but there wasn't an effect. 

Can you help me fixing this Bug? If you need more information like the config or a pluginlist from the Server, just ask.

Thank you!

Jobs configpart: 
  modify-chat:
  use: true
  prefix: '&c[a'
  suffix: '&c]&r'
  separator: ' '

Essentials configpart:
format: '{JOBS} {DISPLAYNAME}: {MESSAGE}'

**Comment by montlikadani** [comment]
Fix, https://github.com/Zrips/Jobs/commit/5c18493fc04e8bfda441a4954c8d79dfcc6d03d5
Soon I will release a DEV. version.
