### ISSUE TITLE
[Question] Can Stained_Glass and Stained_glass_pane be shorten?

### ISSUE THREAD

**Issue by enterih** [Zrips/Jobs#271]
Question in title. 

With shorten i mean 
stained_glass for all colors 

If i can read it anywhere please tell me a link. Thanks for helping!

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/cbb6c534e2819f280ca8121d7cf64303bff58418

**Comment by montlikadani** [comment]
Re-opened, because the commit is invalid. What I did in that commit did not work properly.
