### ISSUE TITLE
Job Explorer options

### ISSUE THREAD

**Issue by smmmadden** [Zrips/Jobs#272]
What is the significance of the below Explorer Job entries.  There are entries for 1, 2, 3, 4 and 5 but I couldn't find what they related to or if they are even valid for 1.13.x.

Should these be changed to the material names for 1.13.x (assuming it is for the first five blocks in game)? Or are these something else that should be explained better in the jobConfig.yml file?
![image](https://user-images.githubusercontent.com/10309346/47259610-9a520d00-d479-11e8-9f61-bad4360e19cb.png)

**Comment by montlikadani** [comment]
Read the comments in the example job.
https://github.com/Zrips/Jobs/blob/master/src/main/resources/jobConfig.yml#L438

**Comment by smmmadden** [comment]
Thanks - it must have been removed with all the editing I did unintentionally. Note there is a typo in the comments (Change "ho" to "who")
![image](https://user-images.githubusercontent.com/10309346/47262157-0307ac80-d4af-11e8-8043-98672a6f6259.png)

**Comment by montlikadani** [comment]
In fact, I do not even know what this Explore job is doing. This plugin was written by Zrips and I have been back for half a month to help her, but I did not know much about what was doing.

I think this Explore job is doing it to count the chunks in that particular world. Or something similar.

**Comment by smmmadden** [comment]
understood and appreciate you helping out :-)
The way I was trying to use this one is every player would autojoin the Explorer job as a means to earn some money/points/exp while they get around the world and basically explore.  Then when they are ready to settle on a location, they would then join the job(s) that pay for the work they are doing while still holding onto the explorer job.  Everyone will always be exploring the worlds.

So if we go with the theory this is all chunk vistit based, then if the player enters into a chunk the first time, they get the payout listed but not paid again for this chunk.  Every new chunk a player enters, they would get the payout, but not paid again for that chunk.  This would work well for all players if there was an option for saying "All" players.  What we would not want to do is list 10,000 entries for the number of players a server has.  That would be silly and very time consuming.

It would require new parameters in the config to support something like the above where we could select all players, players in a job, players in a certain permission group and then something about the chunks.  What do you think?
`Explore:
   AllPlayers:
     NewChunk:
       income: 2.5
       points: 2.5
       experience: 2.5
     VisitedChunk:
       income: 0
       points: 0
       experience: .01
   Group:
     Default: 
       NewChunk:
         income: 2.5
         points: 2.5
         experience: 2.5
       VisitedChunk:
         income: 0
         points: 0
         experience: .01
   Job:
     Miner:
       NewChunk:
         income: 2.5
         points: 2.5
         experience: 2.5
       VisitedChunk:
         income: 0
         points: 0
         experience: .01'

**Comment by montlikadani** [comment]
Hmmm.. This could be solved, but not simple. This VisitedChunk may cause problems, such as server lag, crash, freezing. Because chunk is not good for servers.

**Comment by smmmadden** [comment]
agreed, perhaps using coordinates then?  Something like traveling total distance of x and or z from joined world coordinates since we should have where they are when they enter the game.  Then each day (24h) it would reset for the next day.  
X-Z: 
Use: (values: X, Z or Both)
  x: 500
  z: 500

So it would be like if I joined today at 9:00AM and travelled 500 blocks North or South, I'd get paid.  If I traveled 500 blocks East or West, I'd get paid.  If I traveled both X & Z distance, I'd get paid.  But that would be it for the day.  Similar to taking a quest. It's a one time payment for that day.

**Comment by montlikadani** [comment]
For this feature, the [Advanced Achievements](https://www.spigotmc.org/resources/advanced-achievements.6239/) plugin is perfect.

**Comment by smmmadden** [comment]
Thanks for the referral.  I didn't notice anything about exploring or Jobs support.  Is this a resource you have used or know someone that did what I was looking for?

**Comment by montlikadani** [comment]
Yes, that's what you want. Only with a different name. By doing this: "Distance-by-foot" or something similar.
