### ISSUE TITLE
Hunter not being paid from spawners

### ISSUE THREAD

**Issue by Stager83** [Zrips/Jobs#274]
Hi there

I have inputted the perm as below for each player rank but still am unable to have hunters paid for killing mobs from spawners? This is the issue with both naturally occuring spawners as well as the epicspawners I am using.

jobs.vipspawner

**Comment by montlikadani** [comment]
_EpicSpawners_ is not supported by the plugin.
Did you try without the EpicSpawners plugin?

**Comment by Stager83** [comment]
Yep, I even tried on a naturally occuring blaze spawner in a nether that is not associated with epicspawners at all.

**Comment by montlikadani** [comment]
Did you try with enabling this?: `enable-pay-near-spawner`

**Comment by Stager83** [comment]
Issue has been resolved, I had a dev create a plugin that spoke between both plugins, thanks for your replies though :)
