### ISSUE TITLE
The gtoplist signs don't display properly anymore

### ISSUE THREAD

**Issue by doitliketyler** [Zrips/Jobs#276]
I'm not sure when these broke but they no longer display properly. Only this shows up on line 1:

"1.doitlike~:3"

Could you fix this and maybe consider adding a little more control over how these display? Would be nice to be able to edit each line and prevent the names from being truncated.

**Comment by montlikadani** [comment]
It is displayed as only one player joins a job and display the player on the sign.

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/c3ccf30b6d393632c0d6c48b208a1bd3da7d2aba

**Comment by doitliketyler** [comment]
How is this closed without a single response? Was this fixed?

**Comment by montlikadani** [comment]
This is not a bug. You can change the sign lines in your current set locale messages file. If you wants to change player names on the sign, simply break it and place it.

**Comment by montlikadani** [comment]
I understood. So it doesn't display the other players on sign. Check these options:
- Break the sign and place it.
- Make sure you are using the latest version of Jobs.
- Make sure the players on the server exist and join at least one job to display on the sign.
- Check that you are using the data cleanup feature found in the generalConfig file. (Optimizations.DBCleaning)

**_and please if you can send a screenshot of the error._**
