### ISSUE TITLE
Furnace Nightmare

### ISSUE THREAD

**Issue by Stager83** [Zrips/Jobs#277]
Good Day

The furnaces are being de-registered for users if they are feeding items into the furnace from hoppers. Why is this? After each smelt or cook a player has to right click the furnace again to register it and then will get paid for that one smelt only. This is the case with normal furnaces as well as epicfurnaces. I have come across this on other servers as well, this become this way after one of your previous updates. Is there a setting somewhere where the furnace just allows people to be paid and feed in with hoppers?

**Comment by montlikadani** [comment]
In generalConfig.yml, this:
![kep](https://user-images.githubusercontent.com/30026208/47640123-3909f800-db63-11e8-86ae-38df27080e08.png)

**Comment by Stager83** [comment]
Thanks going to give a try now

**Comment by Stager83** [comment]
I have mailed you a video so you can see :)

**Comment by montlikadani** [comment]
Oh.. Do you want to turn off the Furnace protection?
Then find out this:
![kep](https://user-images.githubusercontent.com/30026208/47641321-0b727e00-db66-11e8-9d52-22166ecb73ad.png)

**Comment by Stager83** [comment]
Whether I have re-assign set to true or false furnaces still de-register, should I send you my yml file to your mail address?

**Comment by Stager83** [comment]
Ok I have mailed to you.

**Comment by Stager83** [comment]
![bane-of-my-life](https://user-images.githubusercontent.com/44499727/47642621-cc4a2a00-db71-11e8-8f54-931230b05e74.jpg)

So that is the my only issue, when you feed into furnace with hopper it de-registers the furnace and you have to right click every smelt to get it to register the furnace again. This means that you can only get paid if you don't use hoppers into furnaces.

**Comment by montlikadani** [comment]
Ok, I checked the video and the screenshot. For this furnace registration, needs to restart the server to save the furnace in the file.

**Comment by Stager83** [comment]
Just a restart? I have done that a few times. Or do you mean a complete reset or wipe?

**Comment by montlikadani** [comment]
I don't know why not work for you. I tested it now and it's work correctly for me.
Are you using the latest version at all?

**Comment by Stager83** [comment]
I seem to have gotten to work now, I thank you for your time and patience :)
