### ISSUE TITLE
Error of traductions

### ISSUE THREAD

**Issue by AcePolisson** [Zrips/Jobs#279]
Hello, while using the plugin Jobs, I found that every wood type have the same name. I went into Translatable Words to change that. But when I add a line in the file, it get remove each time I reload the plugin. Can you help me ? Thank you ! 
Jobs Reborn 4.9.1 (last one)

![error_2](https://user-images.githubusercontent.com/44675050/47858120-987a3900-ddeb-11e8-8f3c-e6b40a7140d2.png)

![error](https://user-images.githubusercontent.com/44675050/47858039-6963c780-ddeb-11e8-8321-21d348957960.png)

**Comment by montlikadani** [comment]
Do you send me a jobConfig.yml file with a job wich problem is?

**Comment by AcePolisson** [comment]
Ok i send you that thanks

[Jobsconfig.zip](https://github.com/Zrips/Jobs/files/2539399/Jobsconfig.zip)

**Comment by montlikadani** [comment]
I'm sorry for the late reply...
Did you try to use full name instead of IDs? E.g.: BIRCH_LOG, OAK_LOG, ACACIA_LOG etc..

**Comment by AcePolisson** [comment]
As soon as I note something in the file and reload it erases it, whatever I mark.
And sorry for my English, i'm french.

**Comment by montlikadani** [comment]
wut? The plugin does not delete the files.

**Comment by AcePolisson** [comment]
Sorry for my response time. It's not the file it deletes but what I added to the file (a line)

**Comment by Nogapra** [comment]
Hi if you need help AcePolisson I am also French and I have no problem translating the plugin.

I modified my Translatable words also on the other hand if you make a mistake inside the system this is reset by default and you have to redo everything.

On the other hand for the wood to appear correctly, in the Jobconfig I used the new name of the Minecraft object (so not the numeric IDs, nor the naming of the blocks as the API Spigot the recommended and its running Nikel)





Salut si tu as besoin d'aide AcePolisson je suis aussi français et je n'ai aucun problème de traduction sur le plugin.

J'ai modifié mon Translatable words aussi par contre si tu fait une erreur à l'intérieur le système ce remet par défaut et il faut tout refaire.

Par contre pour que le bois apparaissent correctement, dans le Jobconfig j'ai utilisé le nouveau nom des objet Minecraft (donc pas les ID numérique, ni le nommage des Blocs comme l'api Spigot le recommand et sa marche nikel)

**Comment by montlikadani** [comment]
I have now tested and worked correctly for me, as you are configured in the Translatable_words and in the jobConfig file. Try updating [DEV. version](https://github.com/Zrips/Jobs/releases).

**Comment by istarengwa** [comment]
@Nogapra 

J'ai le problème en effet, sur la traduction française, impossible de la modifié moi même, elle ce remet automatiquement mauvaise a chaque /jobs reload, A savoir que dans le fichier zip elle n'as aucun soucis la traduction, mais une fois sur le serveur elle change totalement. Pourrais tu me montrer la façon dont tu as traduit le fichier pour savoir comment m'y prendre, un exemple sur un item me suffira pour travailler sur le reste. Cela m'aideras beaucoup même.
