### ISSUE TITLE
Bug smelt with CHARCOAL 1.13.2

### ISSUE THREAD

**Issue by jere62smi** [Zrips/Jobs#280]
Hello, 
Since the passage in 1.13, cooking wood charcoal no longer gives the gains, I tried all possible ID but no change. I would like to know if this is a bug on your side and if it is possible to be fixed.
Cordially.
   
 Smelt: 
      CHARCOAL:
        income: 0.20
        experience: 0.20

**Comment by montlikadani** [comment]
I don't know why not works for you. I tested it and it's working correctly for me.
Try update to the DEV. version. [this](https://github.com/Zrips/Jobs/releases/download/v4.9.1/Jobs.jar)
