### ISSUE TITLE
Error with /jobs info <job>

### ISSUE THREAD

**Issue by jere62smi** [Zrips/Jobs#281]
Hello,
Error with the command /jobs info <job>.

Latest version of the plugin
Paper 1.13.2

https://pastebin.com/We9Q443F

**Comment by Nogapra** [comment]
If you use MythicMobs Make sure you use the last Version 6.0.0 snapshot because is the only version work with Spigot/Paper 1.13.X

**Comment by montlikadani** [comment]
@Nogapra 
We do not yet support the latest MythicMobs version, as I have not used the plugin yet. Zrips will not upgrade, but I will. [Here you can see what version of it we support.](https://github.com/Zrips/Jobs/tree/master/libs)

**Comment by Nogapra** [comment]
Apologies for being wrong. MythicMob is not in V6 but the latest compatible version is the 4.5.0 Snapshot version and I confirm that Jobs track it correctly.

In my console Jobs tells me : MythicMob4 was found-Enabling capabilities.

After in my config I have not put any job option that can work with Mythic Mob so I do not know if everything will work.

However I confirm that to run in 1.13.2 (Spigot/Paper) It takes the snapshot of MythicMob accessible only to the premium on their site

**Comment by montlikadani** [comment]
Now the plugin supports latest version of MythicMobs. https://github.com/Zrips/Jobs/commit/dfbf7963da10b2e26e19deb6f94bc75ed9a7c5e3
