### ISSUE TITLE
Error of translation jobs reborn 4.9.1 in serveur 1.8.9 (fr)

### ISSUE THREAD

**Issue by istarengwa** [Zrips/Jobs#288]
Translation issue : 

http://image.noelshack.com/fichiers/2018/45/7/1541942651-7c2bce83dc24cd5ff89ba090c3a229ec966d3465.png

server 1.8.9 jobs reborn 4.9.1 = 

http://image.noelshack.com/fichiers/2018/45/7/1541942646-89169eccd817ed9d983a96af026eba09b9830157.png

jobs reborn 4.9.1 in folder = 

http://image.noelshack.com/fichiers/2018/45/7/1541942644-231896e47ea66c0db11301e4eb3cfbc070084f4a.png

Can not get the right translation on my server. Help me please

**Comment by istarengwa** [comment]
https://transfernow.net/6b06h0zexb7g

**Comment by montlikadani** [comment]
Link is invalid, please send to [pastebin.com](pastebin.com)

**Comment by montlikadani** [comment]
Do you use the latest version of JobsReborn?
This error did not appear to me. I think you do not use the latest version as the generalConfig file has not been updated.

**Comment by istarengwa** [comment]
https://pastebin.com/ZJ52pXkP : generalconfig

**Comment by montlikadani** [comment]
Sry, read the last post by sended me.

**Comment by istarengwa** [comment]
i use jobs reborn 4.9.1

**Comment by istarengwa** [comment]
Sorry....

the latest version does not install and the translation of 4.9.2 is correct in the jar file and still incorrect once on the server

jar file 4.9.2 : 
[http://image.noelshack.com/fichiers/2018/46/4/1542317959-2018-11-15-13.png](url)

server 1.8.9 jobs reborn 4.9.2 : 
[http://image.noelshack.com/fichiers/2018/46/4/1542317833-2018-11-15-12.png](url)

And delete all the file and the jar and reinstalling it there is even more translation file :
[http://image.noelshack.com/fichiers/2018/46/4/1542318589-2018-11-15-14.png](url)

**Comment by montlikadani** [comment]
To fix these issues see this instructions to fix some repeated material names: https://github.com/Zrips/Jobs/wiki/Legacy-config-support
Some names are not work correctly, but this is not plugin problem, this is client issue.
