### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by BestMark** [Zrips/Jobs#290]
Jobs 4.5.4 (from SpigotMC.org)
Paper 1.12.2
![default](https://user-images.githubusercontent.com/18399104/48349434-57a8dc80-e695-11e8-82cc-c5be1317b3b7.PNG)
Please, fix it as soon as possible because the plugin uses a lot of extra RAM.

**Comment by montlikadani** [comment]
Jobs 4.5.4?? Please update to the latest version.

**Comment by BestMark** [comment]
Is this bug fixed in the latest version?

**Comment by Zrips** [comment]
We will know after some one tests it with latest version. You have 5 months old version.
