### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by BestMark** [Zrips/Jobs#292]
![default](https://user-images.githubusercontent.com/18399104/48364906-b2086400-e6ba-11e8-8774-abe14ef90814.PNG)

If you don't want to support the plugin, please write about it and I won't use your plugin that uses more than 6GB of RAM.

**Comment by montlikadani** [comment]
Please do not spam the same issue. **You can check and download the latest version of JobsReborn.**
This is not a bug, we can checked from the Spigot timings and tps and this plugin does not causes lag.
