### ISSUE TITLE
 invalid Break type property: 

### ISSUE THREAD

**Issue by a7ssan** [Zrips/Jobs#295]
```
13.11 18:21:49 [Server] WARN [Jobs] Job Woodcutter has an invalid Break type property: stripped_oak_log!
13.11 18:21:49 [Server] WARN [Jobs] Job Woodcutter has an invalid Break type property: stripped_spruce_log!
13.11 18:21:49 [Server] WARN [Jobs] Job Woodcutter has an invalid Break type property: stripped_birch_log!
13.11 18:21:49 [Server] WARN [Jobs] Job Woodcutter has an invalid Break type property: stripped_jungle_log!
13.11 18:21:49 [Server] WARN [Jobs] Job Woodcutter has an invalid Break type property: stripped_acacia_log!
13.11 18:21:49 [Server] WARN [Jobs] Job Woodcutter has an invalid Break type property: stripped_dark_oak_log!
13.11 18:21:49 [Server] WARN [Jobs] Job Miner has an invalid Break type property: tube_coral_block!
```
Version : 1.8.8 Spigot
Jobs Version : 4.9.3v

**Comment by montlikadani** [comment]
STRIPPED material does not exist on versions 1.8, only versions higher than 1.9. You ignoring it or remove it from the the job.

**Comment by smmmadden** [comment]
You'll need to either remove those from the jobConfig file or upgrade to 1.13.2.  They are invalid for 1.8.

**Comment by a7ssan** [comment]
ty <3 but should make code ignore this block if u running in 1.8.8

**Comment by montlikadani** [comment]
No. We can not ignore it because the user uses version 1.8 and has a version 1.13 material in the file and there is no bug display on the console, so understand it works. Therefore, it is not to be ignored.

**Comment by a7ssan** [comment]
ok sorry u can remove this ticket if u want <3
