### ISSUE TITLE
Andesite And Birch are repeating

### ISSUE THREAD

**Issue by xinxcode** [Zrips/Jobs#296]
I used it from 4.9.1 because Im configuring my server and still not going online (house project).
I think this will be fixed when there's a new update, but there's nothing change until 4.9.3
Please any help.
![1](https://user-images.githubusercontent.com/31354780/48437418-e3188f80-e7b3-11e8-9134-badb4ff3824a.png)
![screenshot_4](https://user-images.githubusercontent.com/31354780/48437428-e7dd4380-e7b3-11e8-8f85-10702590af4a.png)

**Comment by montlikadani** [comment]
Use the latest version. Instead of using IDs, use lower case material names such as: https://github.com/Zrips/Jobs/blob/master/src/main/resources/jobConfig.yml#L690
We recently updated the material names to work properly.

**Comment by montlikadani** [comment]
Try with the new release of Jobs (4.13.0)

**Comment by montlikadani** [comment]
To fix these issues see this instructions to fix some repeated material names: https://github.com/Zrips/Jobs/wiki/Legacy-config-support
Some names are not work correctly, but this is not plugin problem, this is client issue.
