### ISSUE TITLE
Prevent entity from giving rewards.

### ISSUE THREAD

**Issue by ploppyperson** [Zrips/Jobs#297]
Hi,
I was wondering if there is a way to prevent an entity from giving rewards using the API?

The only thing I have found so far is to use the "jobsMobSpawner" metadata tag, however I would rather use an API so it doesn't break after updates etc.

Thanks.

**Comment by montlikadani** [comment]
You can use this code:
`Jobs.getPlayerManager().getMobSpawnerMetadata()`
