### ISSUE TITLE
ExploreManager using a lot of memory

### ISSUE THREAD

**Issue by xDacon** [Zrips/Jobs#298]
https://i.imgur.com/ogFjuL9.png
anyway to optimize this?

Jobs: 4.9.3
Paper 1.12.2

**Comment by montlikadani** [comment]
This was expected for the remaining chunks.
But since this is not the Spigot/Paper timings & tps, this is invalid, as this does not prove that are consuming the memory. #292

**Comment by Zrips** [comment]
@xDacon 
As you can expect, we have to record each visited chunk with player names, so it can get decently big. Will check out and maybe there is a way to optimize it or even exclude players which are not in explorer job, tho that solution would make this job less useful.

**Comment by BestMark** [comment]
@montlikadani, you're wrong. Read, please, in more detail about what timings are doing before saying such stupid things. Timings do not show the use of RAM.
@Zrips, I have default job jobConfig and I have same problem.

**Comment by montlikadani** [comment]
@BestMark Congratulations on your smartness... What @xDacon  said is an application cracked, so it doesn't meet the requirements to be able to use the job chunks. If I see Eclipse well, it is used to check for invalid timings. This is not good for timings, so we need timing based on Minecraft, which contains all the information we need to improve. What you see from it is not the timings sought by Minecraft but the application called Eclipse.

**Comment by BestMark** [comment]
@montlikadani in the standard Minecraft core there are no timings, like plugins. It is Spigot feature.

**Comment by ColdKVanT** [comment]
@montlikadani Holy God, what're you talking about? Stupid excuse, used for justifying shit coding, that causes this leaks.
That person provided you all the information from Eclipse tool but you still argue.
Minecraft timings are not able to show all underwater rocks of plugins. Try testing your plugins more deeply, that'll help you a lot.

**Comment by montlikadani** [comment]
Do you know that if you check "chunk" in Eclipse from the code, then this is a Java problem, for example HashMap stores the remaining amount of data? First, check that the plugin is checked based on Spigot timings. If this huge number of chunk stays, then it will obviously be a mistake. Yeah, and use the /tps command to show the server current Ticks Per Second.

**Comment by ColdKVanT** [comment]
@montlikadani Either you thing, that we are stupid, or you're joking. The plugin causes memory leaks due to that bug and it is developer's problem in code and we ask to fix it.
We don't debate TPS of the server. There's a leak, and because of it we can't use this plugin on the server. Not only does it affect server performance, but also stores a lot of shit, that also causes a lot of problems.
If the plugin is free, it doesn't mean, that you must create a bad plugin. Did you create the plugin, you would either support or close the development of the plugin.
Take a look of your code, only after that tell us about tool's inefficiency.

**Comment by ColdKVanT** [comment]
Dude, you're not right

**Comment by montlikadani** [comment]
To check the official timings see this site: https://timings.spigotmc.org/

**Comment by xDacon** [comment]
@montlikadani This is a memory issue, timings is useless. How many times do you need to be told this

**Comment by ColdKVanT** [comment]
@montlikadani Call the developer of Jobs here. It seems, that you're not the person, who is able to fix smth big, like memory issue, cross my heart....

**Comment by montlikadani** [comment]
@xDacon  @ColdKVanT
Check this question for hashmap memory usage: https://stackoverflow.com/questions/41314160/java-8-hashmap-high-memory-usage

Zrips said, we need to save explorer data in map to prevent data loss when a player exploring some areas.

**Comment by ColdKVanT** [comment]
@montlikadani In the end of the day ExploreManager stores up to 1-2 gb of information.
Is there really such a lot of information to save?

**Comment by montlikadani** [comment]
Yes, because of the HashMap algorithm that stores the data you want to save.

**Comment by BestMark** [comment]
Where does the plugin save 2-3 GB of information?
How can I disable this?

**Comment by montlikadani** [comment]
This is not a plugin problem, but a Java Map algorithm data backup performance error that affects all Java platform plugins, programs that use the Map algorithm. So it can't be disabled.

**Comment by BestMark** [comment]
It's not Java feature, it's memory leak. So, you should optimize it.
