### ISSUE TITLE
Wrong Toplist-ranking

### ISSUE THREAD

**Issue by Sprungente** [Zrips/Jobs#299]
Hello everyone 
I saw irregularities with the rankingsystem (Global Toplist). It is possible to get a check? 

What i mean:
https://picload.org/view/dcoccwgg/unbenannt.png.html
![image](https://user-images.githubusercontent.com/15361899/50531701-0b174480-0b0f-11e9-9659-32873cc280b8.png)

Jobs Reborn 4.9.3 --> Still exist in 4.9.5
Spigot 1.13.2 
Using MySQL 

If i forget something please let me know :)

**Comment by montlikadani** [comment]
Try to ask the player to quit from the job and re-join again.

**Comment by Sprungente** [comment]
another player claimed the 9th place and on the sign 9th and 10th are the same again.

but this is doesn't matter for the weird error this the command /jobs gtop. 
15. place will be displayed also on place 16. 

If i see page 2, then place 26-30 will be displayed on th 31-35 on page 3.

on page 3:  place 33-44 will be also displayed on page 4 with place 46 - 57

If you don't believe me, i did screenshots.

**Comment by Sprungente** [comment]
https://imgur.com/a/4VLW4Wy

**Comment by montlikadani** [comment]
Okay, ok I see and believe it.

**Comment by Sprungente** [comment]
![image](https://user-images.githubusercontent.com/15361899/50531720-369a2f00-0b0f-11e9-94b8-266f089dd129.png)

Issue expanded

**Comment by Zrips** [comment]
c3ccf30b6d393632c0d6c48b208a1bd3da7d2aba
