### ISSUE TITLE
Jobs Action Display

### ISSUE THREAD

**Issue by Spedwards** [Zrips/Jobs#30]
I've modified the experience gained using the API supplied, and it works, however the title text that comes up displays the XP before it gets altered.

I was looking through the methods but couldn't for the life of me find where it gets displayed in any of them to reorder it.

**Comment by Zrips** [comment]
Backwards engineering always helps :) Find action bar class, rename method and you will see where it was used, then check again where that method was used. In any case, jobs events needed to be moved couple lines up, before actual payment. Will push fixed version today.

**Comment by Spedwards** [comment]
I meant that I couldn't even find what method was called in the class to show them. Probably doesn't help that I didn't know what they're were called. "Action Bars" were added during my minecraft hiatus.

Anyhow, thanks. :)
