### ISSUE TITLE
Negative Boost with LuckPerms

### ISSUE THREAD

**Issue by Endothelium** [Zrips/Jobs#307]
Hello,

I am trying to set a negative boost on a job with luckperm permission.

When i set a negative boost like this `jobs.boost.miner.all.-0.1` it doesnt work.

When i set a positive permission like this `jobs.boost.miner.all.0.1` it works.

So it really seems to be a problem with the "-" character.

Is there a solution?

Thanks

**Comment by montlikadani** [comment]
It doesn't work because if you specify "-", it means to take from your payments and rarely give you payment. Only positive values can be entered.
