### ISSUE TITLE
 Language file problem

### ISSUE THREAD

**Issue by TheCalypso** [Zrips/Jobs#309]
Hello,
I want to switch my server to 1.13 (currently 1.12.2) we put the last update of your plugin with the new configuration files. I have selected the default language on FR for French but basic in the plugin there is no corresponding file while in your old version though. On the other hand the plugin create a file Words_fr but everything is in English. Could you help me ? Moreover, when I modify the last part of the plugin on the form of the GUI menu with the / jobs join it does not work. I have no major error in the console.

Thank you very much, congratulations on your plugin, which remains very good!

**Comment by montlikadani** [comment]
It's all in English because you have not seen the latest version of the file yet. We recently updated the files with new methods, in this comment you will find: https://github.com/Zrips/Jobs/issues/283#issuecomment-436291200
Send the configuration where your problem is.

**Comment by Zrips** [comment]
163af81253e966d6e8408934442ea7782e591b54
