### ISSUE TITLE
Menu GUI problem

### ISSUE THREAD

**Issue by TheCalypso** [Zrips/Jobs#312]
Hello, 
I reopen a post because I just found a bug, when we do / jobs join the GUI menu opens, in my config.yml file I configured the number of lines on 3 but it does not work however, it works with 5 and 4. Can you help me? here is a screen of my config. 

![image](https://user-images.githubusercontent.com/33781244/49692717-9c734680-fb61-11e8-8242-8d1a4355eb6b.png)

Thank you very much for your help !

TheCalypso

**Comment by montlikadani** [comment]
I tested now and it's working correctly for me your current configuration.
Do you use the latest version of JobsReborn?

**Comment by Zrips** [comment]
@montlikadani 
As strange as this will sound, send me a PM on a spigot web page.

**Comment by Zrips** [comment]
0439d5eeda4fd78d7c55ad22ce233b22e16ed0cb
