### ISSUE TITLE
4.9.5 GUI changed; Config incorrect

### ISSUE THREAD

**Issue by OpalMoonstride** [Zrips/Jobs#321]
I updated to 4.9.5, and the GUI has Stone in all the filler spaces. The config for the GUI says stained_glass_pane. I can change it to black_stained_glass, but then the display name is too long. I think I saw issue #312 mention the length of the glass name. 

A display-name option would help, maybe. 
This is mostly cosmetic, though. 

Thanks

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/432cbbbd093833508e468e099d8b344aac348697#diff-2bbefed2dca880e596848b248efa0102
