### ISSUE TITLE
Error spam Jobs 4.9.5

### ISSUE THREAD

**Issue by ArathiaMC** [Zrips/Jobs#322]
This error is being spammed: https://pastebin.com/avhmT0f6

Jobs version: 4.9.5
McMMO version: 1.60 (latest)
PaperSpigot: Paper-474

**Comment by montlikadani** [comment]
Are you using paid official MCMMO? Because we support the free version.

**Comment by ArathiaMC** [comment]
Using the latest free version

**Comment by LogGits** [comment]
By free version are you talking about: https://ci.ecocitycraft.com/view/McMMO/job/McMMO-Classic/

The original dev came back and is now working on: https://www.spigotmc.org/resources/official-mcmmo.63489/

**Comment by Zrips** [comment]
af4d6ce282dfed17dc5d04d03ff1aa86970a8a3d
