### ISSUE TITLE
Issue with weaponsmith job, perhaps others for infinite money/xp

### ISSUE THREAD

**Issue by kelso6969** [Zrips/Jobs#325]
With the job weaponsmith, If you have a full inventory and shift click the item you're repairing
It doesnt consume XP or the material but you get the Job XP and money

**Comment by montlikadani** [comment]
If the player inventory is full, will not get money, points or exp, as receives only one message that the inventory is full.

**Comment by kelso6969** [comment]
Thats what I'd expect, but not how it works out on my server. You can keep click clicking and racking up money and xp. Using 4.9.5

**Comment by TheWolfsHeart** [comment]
Adding on to this, a copy paste from the Discord I posted some details of this on:

Recreation: Get a damaged weapon, like a sword.
Fill inventory with something simple like cobble.
Get item to repair sword.
Put sword and repair material in anvil
Fill in the last two slots of your inventory with simple material.
Shift+click repair output.

I personally tested this and it gave money and EXP towards the job. Especially broken if used with a macro. 25 levels in Weapon smith within the span of like.. 2 minutes.

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/92564ee8b161b7392887985083dc538cd4d9b462
