### ISSUE TITLE
Feature: Jobs boosts per player (exp/money/points)

### ISSUE THREAD

**Issue by Rakdos8** [Zrips/Jobs#327]
Hi there !

I'm wondering if there is a way to grant any boost (exp/money/points) with a command for a defined time length.

I'm willing to open a new package in our shop where player can buy a "boost" for all of his/her jobs during the next 24 hours.
At the moment, we have 2 solutions:
- grant the boost on a job to every player with */jobs expboost [jobname]* but every player has the boost
- grant an item which give a boost when using it but we can't retrieve the item automatically after 24 hours

Did I miss a configuration or command ?

**Comment by smmmadden** [comment]
Use the schedule.yml to do a timed boost.

**Comment by montlikadani** [comment]
You can use permission. We will not add it by command as it can already be used with permission.
Please refer to the main page (Spigot) for permission in the permission section.

**Comment by Rakdos8** [comment]
Indeed, I didn't check that before.
I've just give it a try with a friend and it's working. Still we have a slight delay, but it does the required job.

Thank you @montlikadani !
