### ISSUE TITLE
Rewards x2

### ISSUE THREAD

**Issue by Blamo27** [Zrips/Jobs#33]
(PayForEachCraft: true)

> Craft:
>       '322-1':
>         income: 80
>         points: 0
>         experience: 80

I set this, and all the players are earning twice the money

**Comment by Blamo27** [comment]
There is no bonus

**Comment by Blamo27** [comment]
@Zrips ?

**Comment by Zrips** [comment]
don't see reason why it could double payment only for crafting without any bonus enabled.

**Comment by Blamo27** [comment]
I can send you some screenshots

**Comment by Zrips** [comment]
config file and some screens would be nice

**Comment by Blamo27** [comment]
> Config file : http://pastebin.com/ZpDkANK8

Screen :
> http://i.imgur.com/VUc1HHH.png
> http://i.imgur.com/WgB3GMk.png ("Pomme enchantée" --> Enchanted golden apple)
> https://streamable.com/czgf
I'm earning 323, so 161.5 * 2 :/

**Comment by Blamo27** [comment]
@Zrips The issue is still there

**Comment by Blamo27** [comment]
@Zrips No ans ?

**Comment by Blamo27** [comment]
Hello @Zrips

As you can see on that picture, crafting one Notch golden apple (ID : 322:1) is supposed to give 1003$ and xp.
--> /jobs stats : http://i.imgur.com/YdvsTql.png

But, as you can see on that video, crafting one Notch golden apple gives 2006$ and xp, exactly the double of what it is supposed to give. However, when you craft multiple apples at once, you get the normal amount of money (here, crafting 32 apples gives roughly 32 000$, which is what it is supposed to be).
--> https://streamable.com/ibos

That means that the bug, which doubles the xp and money given, only occurs when crafting one, and only one, of the item. Note that it seems to happen with every kind of item with the action "crafting", not just the golden apple : it's just an example.

We've had this problem for a long time and it's really annoying, we would greatly appreciate some help on that matter. Here is our JobConfig file for further testing :
--> http://pastebin.com/SzHDDCSm

And the generalConfig file :
--> http://pastebin.com/z1mfMcmp

Thank you.
