### ISSUE TITLE
Jobs pay players in Spectator mode

### ISSUE THREAD

**Issue by aeonlamb** [Zrips/Jobs#330]
Players in spectator mode should not be paid, the same way players in creative mode should not be paid. However, players in spectator mode are paid for being near explosions (miner job) and for exploring the world (explorer job). 

All you can do in spectator mode is float around and watch people, you should not be getting paid for whatever you do in this gamemode. Tested on version: 4.9.5 , using Paper 1.13.2

**Comment by aeonlamb** [comment]
Update on this. The issue of spectator players getting paid (for exploring) did not exist in version 4.9.3. I think this is because of the way the "not flying" check was changed for the explorer job, it was done erroneously, because the plugin doesn't seem to recognize anything as "flying" anymore. I can even use essentials' /fly command and fly around in survival mode and get paid, whereas this was previously not possible in version 4.9.3.

**Comment by aeonlamb** [comment]
I am using the latest plugin version on my test server. I have that option set to "false" in my config, yet I'm still paid for exploring while in spectator mode (as well as while using /fly in survival mode)

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/28f8e24465586e07c54b9c0823349ae74ef26fb8
