### ISSUE TITLE
1.10 Bow issue

### ISSUE THREAD

**Issue by SirKillian** [Zrips/Jobs#34]
Yesterday we updated our server to 1.10 running on paperspigot 1.10 using the latest version of jobs.

we have a hunter job setup and they get paid for killing hostile mobs.
now after we updated to 1.10 our hunters are not getting paid for killing mobs with a bow.

our configs:
- GeneralConfig.yml http://pastebin.com/aZ5d0WYM
- JobsConfig http://pastebin.com/gKs3ygyP

Thanks for the help :)

**Comment by Zrips** [comment]
Should be fixed now
