### ISSUE TITLE
Certain Blocks not registering for job(s?) 

### ISSUE THREAD

**Issue by Faunsce** [Zrips/Jobs#341]
Atm, certain blocks simply aren't able to register properly for jobs and my current list is below

[Farmer]
Wheat and Sugarcane are not detected under the Farmer job.

**Comment by Zrips** [comment]
Double check your block material names. Or atleast provide your current settup which doesn't work.

**Comment by Momonche** [comment]
Hello,
I confirm the problem, loot at my error (default config)
[19:06:10 WARN]: [Jobs] Job Fermier has an invalid Break type property: WHEAT (wheat-7)! Material must be a block!

**Comment by montlikadani** [comment]
@Momonche Describes WHEAT invalid break type you need to use `wheat-7` in small letter and specify the age of plant.
_Next time join our Discord server and write your problems, not to random sites._
