### ISSUE TITLE
Specific Jobs per World (Question)

### ISSUE THREAD

**Issue by Pyario** [Zrips/Jobs#343]
Would it be possible to add specific worlds for certain jobs? Unfortunately the disableworld function in the generalconfig only offers you no job money. Should a job be added to the jobconfig in the job the job will work in the world. 

Small example:

You have three jobs: Lumberjack, Miner and Digger. If the world farm world is now disabled in the generalconfig and the lumberjack job is activated in the jobconfig, the job still works.

Best regards.

**Comment by montlikadani** [comment]
If there is no answer, do not close it because we will answer it later.

**Comment by Pyario** [comment]
> If there is no answer, do not close it because we will answer it later.

Ok.

**Comment by Pyario** [comment]
@montlikadani 
It's been over 2 months now. Is there anything else to come, is not it? I know you have a lot of work to do bugs or others, but would like to have an answer.

Best regards,

Pyario

**Comment by montlikadani** [comment]
We do not add this option. We stay with disabledWords. To do this I add which commands/functions should not work when the player is in that blocked world.
Which commands can be:
- demote (not sure)
- fire/fireall
- info
- leave/leaveall
- join (most of all)
- level/exp
- quest (possibly)

**Comment by Pyario** [comment]
okay.

**Comment by montlikadani** [comment]
Don't close it. We closing this if we done this task.

**Comment by montlikadani** [comment]
Solution: The `jobs.disabledworld.commands` permission is ignore the disabledWorlds option if the player have.
