### ISSUE TITLE
[Question] /jobs stats implement placeholder %titlename%

### ISSUE THREAD

**Issue by Sulort** [Zrips/Jobs#344]
Hi,

is it possible to implement the placeholder %titlename% for the jobtitles in the command /jobs stats ? so that you can use the placeholder in the locale message.yml file in the part of the stats message?

**Comment by montlikadani** [comment]
What does jobtitles mean? The current job in which you have or list all available jobs?

**Comment by Sulort** [comment]
in the file titleconfig.yml you can define the name of a title. and the placeholder %titlename% stands for this jobtitle. i'm using the same jobtitles for all jobs.

**Comment by montlikadani** [comment]
I added this, and commit soon.
