### ISSUE TITLE
Jobs 4.10.0 StripLogs action throws exceptions

### ISSUE THREAD

**Issue by smmmadden** [Zrips/Jobs#345]
With the latest build running on Waterfall build 253 (1.13.2) / PaperSpigot 1.13.2 (Build 515), I made the changes to the STRIPPED_****_LOGS to use an action of StripLogs for both the Quests and the job actions.
The result on startup was the exception here: 
[jobsfailed.txt](https://github.com/Zrips/Jobs/files/2834772/jobsfailed.txt)

For the Woodcutter job, I have added this section for the Stripped_Logs.
![image](https://user-images.githubusercontent.com/10309346/52319244-b03afd80-2996-11e9-96a1-a42b1e142ffd.png)

Similarly in the Quests section of the Woodcutter job, I have added the same actions.
![image](https://user-images.githubusercontent.com/10309346/52319275-da8cbb00-2996-11e9-9c10-2f7d5d0de31f.png)

Have both parts of the jobConfig been updated or just one of them?

**Comment by smmmadden** [comment]
just updated my other servers without changing the jobConfig file as I did above and still getting the same exception - so there appears to be something wrong with the build with PaperSpigot?

**Comment by montlikadani** [comment]
There is no problem with your server software and StripLogs has already been supported in Quest.
https://github.com/Zrips/Jobs/commit/cee99ce8509370e04d347ccc00a7549e42a1bb3c

**Comment by smmmadden** [comment]
I don't understand what you you referenced. As stated, this is not just a Quest reference I made, but the Jobs details section with Place, Break, etc.  So is there a fix for this or am I doing something wrong?

**Comment by montlikadani** [comment]
What I have referred to is the patch that you have sent an error. StripLogs is only required for the action string as an example in the quest or action section. And if the problem is that you create two quests and the action is similar to StripLogs, will the plugin throws an exception?

**Comment by smmmadden** [comment]
sorry @montlikadani - that's more confusing.  Please take a look at what I posted above there are Quests for Woodcutter for stripping of each logs and there is a StripLogs: action section of Woodcutter job that pays for stripping of the logs.  The two are different, but both actions are StripLogs.

**Comment by montlikadani** [comment]
As I said when we add an action, the action can already be used for quests and action sessions automatically. Now I look at the 14th quest name repetitive so it gets caught up in the quest command, so change it to another. Actions may be similar to quest, but names are not.

**Comment by smmmadden** [comment]
13 and 14 are not repetitive by name.  One is OAK and the other is DARK OAK.  I have 6 Quests where each cover all 6 different logs (birch, oak, dark oak, jungle, acacia, spruce).  
Or are you saying that quests cannot have more than one Action of StripLogs in a given job, meaning I can only use Action: StripLogs in one Quest but not in multiple quests for the same job name?

**Comment by montlikadani** [comment]
No, sorry. I'm confused.
Now I look at you not having the problem with the quest, but there was an NPE in JobsItems that caused the plugin when load. That's what I referred to, this fixed.
