### ISSUE TITLE
Placeholder that display job level even if the player not in the job

### ISSUE THREAD

**Issue by Endothelium** [Zrips/Jobs#347]
Hello, 

It would be nice if we could have a placeholder that show player job level for a specific job, even if the player isnt actually in the job.

I have a RP server where players can have 2 jobs at the same time, and can leave a job and join another one by paying money.

I would like to be able to show their job for every job even if they are not in the job, like that they can track their progression.

Thanks :)

**Comment by montlikadani** [comment]
This could be solved, but we can only retrieve the player's data from the database. If the player leaves the job and joins back, then loses a little (about 1.0) of every progression (e.g. points, level).

**Comment by montlikadani** [comment]
Nop, the player job data will removed from the base when the player left from that job.
