### ISSUE TITLE
Jobs 4.9.5 Potted Items no money/XP

### ISSUE THREAD

**Issue by Sulort** [Zrips/Jobs#348]
Hi,

ich would like to use the potted items, e.g. POTTED_DANDELION
so when ich put a dandelion in a flowerpot nothing happens for the action place.
what am i doing wrong? or is it not working and maybe a bug?

**Comment by montlikadani** [comment]
Potted_dandelion has no official ID yet released by Minecraft, so it doesn't work.

**Comment by Sulort** [comment]
ah ok thanks for the quick response
