### ISSUE TITLE
Permission jobs.command.quests and jobs.max.[numer] do not work?

### ISSUE THREAD

**Issue by Sandukhan** [Zrips/Jobs#349]
**Jobs 4.10.0
Spigot version 1.13.2**
Vault: 1.7.1-b91
Luckperms: 4.3.73
EssentialsX 2.16.0.3

The two permissions **jobs.command.quests** and  **jobs.max.[numer]** do not work with the latest version of JobsReborn.

Players cant use /jobs quests even with the correct permission (jobs.command.quests). Only players with full plugin permission can run this command (jobs.*).

Also jobs.max.[numer] does not seems exits anymore, we are used that permission in the jobconfig to allow players to join a secound job after reaching a certain level. But its also not shown in luckperms anymore as suggested permission for jobs.

        Smelt:
            terracotta:
                income: 0.2
                experience: 0.3
            BRICK:
                income: 0.2
                experience: 0.1
        permissions:
          jobs.max.2:
            value: true
            level: 30

**Comment by montlikadani** [comment]
The permissions section is only works when this world permission is set to specified group/player: **jobs.world.worldname**
Hmm.. Quest permission is invalid in the code. I'll check this.

**Comment by Sandukhan** [comment]
so without jobs.world.[worldname] as grouppermission in luckperms,  jobs.max.[numer] do not work in the jobconfig?

**Comment by montlikadani** [comment]
Yea, only works when the jobs.world.worldname permission is set to permission system.

**Comment by Sandukhan** [comment]
Ok thx, we recently switched from PermessionEX to Luckperms and i gues it hadnt be added automatically back in.

**Comment by montlikadani** [comment]
The `jobs.command.quests` fixed in this commit: https://github.com/Zrips/Jobs/commit/62f5718eb1f36f3b918edb5e6cbc91e26ce1bac3

**Comment by montlikadani** [comment]
The `jobs.max.[number]` is working correctly. Use the compatible permission plugin, such as LuckPerms.
