### ISSUE TITLE
Placeholder %jobsr_maxjobs% not working with PAPI command

### ISSUE THREAD

**Issue by Endothelium** [Zrips/Jobs#355]
Hello,

Some of the placeholders are not working when used with PAPI.

For example, this one works
`/papi parse me %jobsr_user_isin_breeder%` ===> `True`

but

`/papi parse me %jobsr_maxjobs%` ===>  `%jobsr_maxjobs%`

However, if i use `/jobs placeholders`, if display the result of `%jobsr_maxjobs%`

![image](https://user-images.githubusercontent.com/11161697/52477618-de8d2880-2ba2-11e9-866c-2de7737c048a.png)

**Comment by montlikadani** [comment]
PlaceholderAPI is not using the latest version of Jobs, so it still uses version 1.1.0, which does not include the latest placeholders.
![kep](https://user-images.githubusercontent.com/30026208/52501475-bc1a0000-2be0-11e9-9630-487cb8637a73.png)

![kep](https://user-images.githubusercontent.com/30026208/52501321-588fd280-2be0-11e9-8162-f29646445382.png)

**Comment by montlikadani** [comment]
With `/jobs placeholders parse %jobsr_maxjobs%` works correctly.
