### ISSUE TITLE
Issues with Explorer job

### ISSUE THREAD

**Issue by aeonlamb** [Zrips/Jobs#357]
Hello, I submitted another issue report a while ago where I mentioned this, but I thought I would create a new issue because this is different.

The explorer job has a few issues. Namely:
1. The explorer job will consider a chunk as "explored" even if the player who "explored" it is flying around in creative mode. The permission node jobs.paycreative does not affect this. I don't know if this is intended, but I would like to at least be able to toggle it if so.

2. The explorer job will pay players in survival mode who have flying enabled, i.e. with essentials' /fly command. Players with fly mode enabled in survival mode can easily gain a lot of money this way.

Tested using Jobs 4.10.0 on Paper 1.13.2

**Comment by montlikadani** [comment]
For the first: Make sure the **enable-pay-creative** option is disabled/enabled in the generalConfig file.

For the second: Make sure the **enable-pay-for-exploring-when-flying** option is disabled in the generalConfig file.

**Comment by aeonlamb** [comment]
Yes, sorry, I forgot those were config options. They're both disabled in the config.

Also worth noting, prior to version 4.9.4, survival mode players with /fly enabled did not get paid for explorer job, so something in that update caused the 2nd issue.
