### ISSUE TITLE
Boosted Items off-hand issue

### ISSUE THREAD

**Issue by ArathiaMC** [Zrips/Jobs#359]
Hello.

I have encountered a bug with the Jobs plugin.
When holding items with a booster in your off-hand the booster does not apply. It appears to only work for armor slots and the item in hand. Could it be made to work for off-hand also?

Thank you.

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/7fbfab2c4cc2233868126648274dbd64ca42e489
