### ISSUE TITLE
Suggestion: Allow selling of items

### ISSUE THREAD

**Issue by Faunsce** [Zrips/Jobs#360]
Item's specific to a job should be able to be sold to an invisible shop either for money, and/or points, and/or exp.
can enable with something like allow_item_sale: [true/false] 
and a section to determine those values

**Comment by montlikadani** [comment]
With no money and exp transfer, Jobs will be able to sell the items that a user specified.

**Comment by Faunsce** [comment]
?

**Comment by montlikadani** [comment]
Find a plugin that supports Jobs, so can create compatibility with the plugin and pay for points.
