### ISSUE TITLE
Suggestion: Per job point shops alongside global point shop

### ISSUE THREAD

**Issue by Faunsce** [Zrips/Jobs#361]
Miners can use miner point after certain levels for items like picks, ores, pre enchanted picks, pick enchanment books, etc. same for other jobs

**Comment by montlikadani** [comment]
I don't think this should be because you can use the Jobs shop, where you can specify minimum job levels when a player reach it, and so the player can buy that item.

**Comment by Faunsce** [comment]
well, i find a per jobs shop more organized. also, not being able to see the next items to unlock would add a neat suprise factor

**Comment by montlikadani** [comment]
There are plugins that can create compatibility with the Jobs plugin, so they can create a per-job shop.
