### ISSUE TITLE
/jobs info as gui

### ISSUE THREAD

**Issue by sandwally** [Zrips/Jobs#364]
Would it be possible to add an option in the config to have "/jobs info jobsname" show up in the gui instead of in chat?
Or can you already do that?

**Comment by montlikadani** [comment]
You can use the /jobs browse command to open a GUI, that shows informations about the jobs.
If **JobsGUI.OpenOnBrowse** boolean is enabled in generalConfig file, then opening a GUI.

**Comment by sandwally** [comment]
Want to use it in my own gui created with a plugin and others might also want to see payments with "/jobs info name" directly in jobs gui instead of printing it to chat or have to go through /jobs browse for payment info for each jobb.

**Comment by montlikadani** [comment]
As I said, you can find all the information about the job in /jobs browse. If you want to display job information in the GUI, enable **JobsGUI.OpenOnBrowse** in the generalConfig file.
And if you want the job information to appear in your own GUI, ask the developer of the plugin that you are using for your GUI.
