### ISSUE TITLE
Negative permission bonuses aren't applied

### ISSUE THREAD

**Issue by smellyonionman** [Zrips/Jobs#365]
I have a default user group with jobs.boost.jobname.all.-1 and a group that gets jobs.boost.jobname.all.0 with a higher weight.
The idea is to nullify the job's payout by default and then "activate" it in certain cases where the permission is applied to the player.

It's just not working.  The job pays full pay no matter who is assigned to the special group or not.

It may seem like a strange thing to do, but I am using Denizen to assign the class according to specific outcomes of scripted events, so I find the bonus permissions are the only way I can get this to work given the config options available.  But it does not. = (

**Comment by montlikadani** [comment]
#307 
It doesn't work because if you specify "-", it means to take from your payments and rarely give you payment. Only positive values can be entered.

**Comment by adamlaughlin** [comment]
From the Spigot page:
`jobs.boost.[jobname].exp.[amount] - Boosts exp for specific job by defined amount. Example: jobs.boost.miner.exp.-0.5`
Sorry if I misread that or maybe it's out of date.  That was actually what I was hoping to do!

Basically I want players paid only in a certain area, but using RestrictedAreas.yml would affect *all* jobs, I only want this to affect one job.

Do you know a smarter way to do that?

**Comment by TKwSni** [comment]
Tested this commit, permission boosts ie: "jobs.boost.all.all.1.00" dont work after this, did it change the format ? @montlikadani

**Comment by montlikadani** [comment]
> 
> 
> Tested this commit, permission boosts ie: "jobs.boost.all.all.1.00" dont work after this, did it change the format ? @montlikadani

Every boost permissions have a delay. If you do something in a job, you'll get the first time boost, but not the second times. Also you not using any of permissions plugin.

**Comment by TKwSni** [comment]
> 
> 
> > Tested this commit, permission boosts ie: "jobs.boost.all.all.1.00" dont work after this, did it change the format ? @montlikadani
> 
> Every boost permissions have a delay. If you do something in a job, you'll get the first time boost, but not the second times. Also you not using any of permissions plugin.

But in the previous version when I use the permission node boost if I check using /jobs bonus Jobname I can see the boost I have

for example jobs.boost.all.all.10.00 gives me this
![imagen](https://user-images.githubusercontent.com/9063912/88507799-3b54ec80-cfab-11ea-8950-2cb4bbfff564.png)


But after that commit, the same node does nothing

![imagen](https://user-images.githubusercontent.com/9063912/88507716-0779c700-cfab-11ea-8ac6-8abbfe125a42.png)

have you tried it ?

**Comment by montlikadani** [comment]
@TKwSni 
https://github.com/Zrips/Jobs/commit/47d4cd12586d902556cbd1d7aef49c920a652248
