### ISSUE TITLE
Data value not recognise in words.yml

### ISSUE THREAD

**Issue by Momonche** [Zrips/Jobs#367]
Hello,

Since the translation files updated to the new format, we can't name the items with metadata anymore. For instance, the different types of wood, wood planks, leaves, stones, etc, are all named "wood", "plank", "leaf", "stone". This means that the display list of the rewards will show something like :
Stone -> 1$ 1xp
Stone -> 2$ 2xp
Stone -> 2.5$ 2xp
Stone -> 0.5$ 0.5xp
Which is completely pointless and obscure.

Jobs version: 4.10.1
Spigot version: 1.12.2

**Comment by montlikadani** [comment]
So, if you want to use the stone material as an example for an action, does it characterize all types of stones?
This has already been removed due to the change of material data in version 1.13.
And if you have a problem, for example, if you specify granite and diorite material, then indicate the stone material for the job information instead of the specified?
If so, it has already been reported.

**Comment by Ferocimo** [comment]
I'm not sure I understand what you are saying. 
Writing "1-GRANITE: [translation" doesn't work, it's automatically erased upon reload.
Currently I found absolutely no way (despite many tests) to write the different types of stones (and blocks when there are variations).

If it has already been reported, could you reference the issue please ?

**Comment by montlikadani** [comment]
Yea, this already been reported.
#288 
#296

**Comment by Ferocimo** [comment]
Okay then my bad, hope it will be fixed soon. Thank you.

**Comment by Momonche** [comment]
Some news about this ?

**Comment by Ferocimo** [comment]
@montlikadani Hello, would you mind telling us where are we on this issue ? Thank you.

**Comment by montlikadani** [comment]
@Ferocimo Actually, nowhere, because we can't find the source of the error, so it's not yet possible to fix. It can take up to several months.

**Comment by Zrips** [comment]
Words_en.yml will get filled by all possible materials automatically with corresponding ID's for them, you cant add extra ones and you cant remove existing. But you should find all of them in new list. There was issue, which was fixed, where you would get duplicated visualizations like that Stone - Stone - Stone, but simply removing Words files and allowing them to be regenerated will fix it
