### ISSUE TITLE
Boost Money/Exp by player

### ISSUE THREAD

**Issue by CAJV** [Zrips/Jobs#369]
Sorry for my english i'm french

I saw that we could put boosts exp/money per job but I would like to know if it was possible to put a boost per player

Thx :)) !

**Comment by montlikadani** [comment]
Please describe more clearly what you want.
Boost schedulers are this:
https://github.com/Zrips/Jobs/blob/master/src/main/resources/schedule.yml

**Comment by CAJV** [comment]
Hi !

Yes, we can have boosts (ex: money x2 for all the players who are mined, x2 exp for all the players who are farmer) but we can not do for example money x2 for 1 player only, we have to put for players who have this job

I hope I have described better

And sorry for english ;c

**Comment by montlikadani** [comment]
I don't think this would be very necessary as it would be very burdensome for the server, for example, if 25 people are online on the server and 10 of them are using the boost, but as a per-player, this can reduce server performance, This can lead to freezing.

**Comment by Rakdos8** [comment]
Sounds like a duplicate to me: https://github.com/Zrips/Jobs/issues/327
Also it has been fixed in my case. i've created specific groups and provide the given permission accordingly.

It can takes upto 20 seconds to Jobs to understand the boost but it's taken in account.
