### ISSUE TITLE
Suggestion : TopPlayer of quests !

### ISSUE THREAD

**Issue by DjeyMute** [Zrips/Jobs#372]
Hello,
I would like to propose my idea!
I would like it to be possible to display in sign (such as topplayer) a top of the players who made the most quests.
I am French so I hope you have understood me anyway.

**Comment by DjeyMute** [comment]
it's not a good idea ? :(

**Comment by El-pika** [comment]
It is a nice idea indeed

**Comment by skyturn** [comment]
it's interesting, I like it I think it can be really good

**Comment by Flo504** [comment]
Good idea!

**Comment by Iyago** [comment]
I hope this will happen quickly good idea :)

**Comment by OPP-MegaReminou** [comment]
Great idea, it could help many players !

**Comment by PatateGivree** [comment]
Yes, it's a great idea !

**Comment by Kristopher2306** [comment]
Very good idea! I agree with you.

**Comment by Zrips** [comment]
f7936dafb71d13fcc58f7524ab0880d3a9625924
