### ISSUE TITLE
 Could not pass event InventoryClickEvent to Jobs v4.10.1 org.bukkit.event.EventException: null

### ISSUE THREAD

**Issue by kelso6969** [Zrips/Jobs#374]
https://pastebin.com/MFu97HU2

using 1.13.2 latest spigot build and latest jobs available on spigot resources.

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/78ff26d124491ee2ac73fc41f1bfb33f0bc555fe
