### ISSUE TITLE
crafter bug!

### ISSUE THREAD

**Issue by successed** [Zrips/Jobs#379]
`Crafter:
    fullname: Üretici
    shortname: Ür
    description: Çeşitli malzemeler üreterek para kazanırsınız. Örn dispenser
    ChatColour: RED
    chat-display: shortjob
    max-level: 200
    leveling-progression-equation: 10*(joblevel)+(joblevel*joblevel*4)
    income-progression-equation: baseincome+(baseincome*(joblevel-1)*0.01)-((baseincome+(joblevel-1)*0.01)
      * ((numjobs-1)*0.05))
    points-progression-equation: basepoints+(basepoints*(joblevel-1)*0.01)-((basepoints+(joblevel-1)*0.01)
      * ((numjobs-1)*0.05))
    experience-progression-equation: baseexperience-(baseexperience*((numjobs-1) *0.01))
    rejoinCooldown: 10
    Gui:
      Item: CRAFTING_TABLE
    Craft:
      stick:
        income: 0.1
        points: 0.1
        experience: 0.1`

this my config and
When I make 1 stick, it gives 0.1.
and
When I do 64 bars, she pays 0.1.
how to fix ?
version is : Jobs4.10.1

**Comment by montlikadani** [comment]
Enable `Economy.Crafting.PayForEachCraft` option in generalConfig file to pay.
