### ISSUE TITLE
Plugin Loading failed

### ISSUE THREAD

**Issue by Aslaak** [Zrips/Jobs#38]
Hello,

I have an issue on the server start with the last version of jobs ( 3.5.6 ), and spigot 1.10.2, and this is the error : 

http://hastebin.com/perubowega.avrasm

voila, hope it can help you for improve the plugin, because it cut the access of commands and win money for everyone on the server, if you need more informations i'm ok !

Thank you ! :)

**Comment by Zrips** [comment]
Can you repost error as link is no longer valid.
