### ISSUE TITLE
Head problem since Jobs Reborn 4.10.3 

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/Jobs#380]
Since the latest update of Jobs Reborn 4.10.3 the player heads are no longer displayed above the shields! They are all just standard heads now

**Comment by montlikadani** [comment]
What is shields?

**Comment by Blueeyestar** [comment]
The heads above the signs with 1st place , 2nd place

**Comment by montlikadani** [comment]
Already fixed, please next time check the closed issues.
https://github.com/Zrips/Jobs/commit/2c0451aa55e097f31125ce16b7e56cfad4d858de

**Comment by Blueeyestar** [comment]
It's not fixed!!! It is still present!!! Where is that fixed please?
https://pic.lululand.de/upload/Webseite/2019_03_04_18.28.30.png

**Comment by montlikadani** [comment]
@Blueeyestar It's fixed just we not updated the plugin.

**Comment by Blueeyestar** [comment]
Now I'm not gonna let it happen. So the next update will fix it ?

**Comment by montlikadani** [comment]
yea, will fix

**Comment by Blueeyestar** [comment]
Thanks a lot :) Have a nice evening :)
