### ISSUE TITLE
Jobs and McMMO

### ISSUE THREAD

**Issue by Daphsquid** [Zrips/Jobs#382]
Hi there,

On my server, we have an issue where Jobs are paying out full prices for McMMO abilities such as tree feller. Players can obtain ridiculous amounts of money this way. I found [this issue](https://github.com/Zrips/Jobs/issues/362) where it was stated that the "Overhaul" version of McMMO should be compatible with Jobs, however, using both the Classic and Overhaul versions of McMMO do not fix our issue. 

In our Jobs generalConfig.yml:
McMMO:
  TreeFellerMultiplier: 0.1
  gigaDrillMultiplier: 0.1
  superBreakerMultiplier: 0.1

Jobs version: **v4.10.3**
McMMO (Overhaul) version: **v2.1.12**
Server version: **Paper 1.13.2 #544**
If any further information is required, please feel free to request it. 

Looking forward to a fix! 

- David (Daphsquid)

**Comment by veteranmina** [comment]
I'm also having this issue:

Mcmmo:
TreeFellerMultiplier: 0.2
gigadrillMultiplier: 0.2
superBreakerMultiplier: 0.2

Jobs Version: v4.10.3
mcMMO version: 2.0.0
Server Version: PaperSpigot  #525

Reviewing mcMMO code, there are changes from AbilityType.Skillname to SuperAbilityType.Skillname however Job referencing to AbilityType have been removed completely and without the introduction to SuperAbilityType. In order for this to function again there needs to be a check between pre-overhaul and the overhaul of mcmmo on which api to use.

Notes in mcmmo's changelog mention in the api this has changed accordingly:
https://github.com/mcMMO-Dev/mcMMO/blob/67bcb8da11074e1d5468299d60f4c7538a083564/Changelog_2.1.0.md

**Comment by montlikadani** [comment]
#384
