### ISSUE TITLE
Job limit does not change with player level but changes when plugin is reloaded

### ISSUE THREAD

**Issue by KingofAnomaly** [Zrips/Jobs#385]
I am currently on version 4.10.3 and I have experienced this problem through many previous versions. When a player levels up their limit does not change with their level until I reload the plugin. I have also tried waiting until the limit automatically resets and it still does not change. My money limit equation is (5000-(4000*(0.99^(totallevel)))) while my exp limit is (98+(2^(totallevel))). I am wondering if there is a bug with exponential equations. I have points disabled and the job for each player is limited to 1. I hope the info I have provided is helpful.

**Comment by Zrips** [comment]
7a52b9c94d26ff2ebcea170185659aa4995bd48b
