### ISSUE TITLE
Jobs leave and leaveall warning

### ISSUE THREAD

**Issue by LogGits** [Zrips/Jobs#386]
I have had a tonne of players complain to me about not knowing that leaving a job makes you loose your experience. It would be nice to have a feature whereby when a user goes to leave a job they need to type it twice. The first time, it would say a configurable message like "&cAre you sure you want to do this. Leaving a job will result in a reset of experience.". The second, (they have to type the command again within 1 minute) would make them leave the job. 

This same method could be applied to leaveall.

**Comment by montlikadani** [comment]
To manage when leave from job level/exp/points loss in the generalConfig file, see the **old-job** section.

**Comment by LogGits** [comment]
ye i want them to lose the exp but i also want them to know that they will lose it by using the command. Players go in blind, that's why i think a warning message would be good (so they know they will lose exp/points/levels by leaving).

**Comment by montlikadani** [comment]
Hmmm.. Ok, good suggestion!
