### ISSUE TITLE
Player can access jobs without permission

### ISSUE THREAD

**Issue by thammachet** [Zrips/Jobs#389]
First of all, sorry for my English.
Hello, I am using your plugin. When I put this plugin in my server. Everything is working fine but the player can access /jobs join. I didn't set any permission to them. Is there any way to not allow it? I would like to let the player register their jobs by sign only. Thank you =>

**Comment by montlikadani** [comment]
**jobs.command.join** (For /jobs join command)
**jobs.join.[jobName]** (To disable the specified job to join)

**Comment by thammachet** [comment]
Hello, I understand but I didn't give them a permission yet and they can use /jobs join.

**Comment by mrfloris** [comment]
Do they have any * permissions, granting them access to everything, or are they perhaps operators?

**Comment by thammachet** [comment]
No, they don't. They have some common permission ex./home /sethome /spawn /pcst. But they don't have any permission about jobs plugin. Another plugins are fine.
-----------------------------------------------------------------
The plugin that I am using for permission is  (group manager plugin)
