### ISSUE TITLE
Thermos compatibility

### ISSUE THREAD

**Issue by DwarfyAssassin** [Zrips/Jobs#393]
Jobs version : 4.10.3
Thermos version: 57 (1614)
MC Version: 1.7.10
Error: https://pastebin.com/x2W0DuAc

If you don't know what thermos is, thermos is a server jar that allows for both mods and plugin It's like sponge but then it's for 1.7.10 https://cyberdynecc.github.io/Thermos/install

So it tries to check `Player.isGliding()` which doesn't exist in 1.7.10 but just before it is a version check. The weird part is that somehow it passes that version check but when I recreate your version checker in my own plugin it gives the correct version (1_7_R4)

So I don't really know what the cause is but it would be nice if someone could figure that out.

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/753ecefb10c412bdd2321709ba33287a5173f147

This commit describes, that the `player.isGliding()` method not valid for 1.8 and below versions and this fixed.
