### ISSUE TITLE
convert money to point

### ISSUE THREAD

**Issue by PSILONCRAFT** [Zrips/Jobs#395]
Is there a way to convert money earned into points like a sign shop exchange???
like 10 points cost 1000 $ or do a cfg to customize it

**Comment by montlikadani** [comment]
I don't think this should be, because what the player gets is already in the Vault economy account, and the conversion will take all the money, so it may not be useful because it may lose the money it has earned so far.

**Comment by PSILONCRAFT** [comment]
What if you had a sign shop where you can buy like 100 point for 1000$ or something like that?

**Comment by montlikadani** [comment]
To do this, the author of the sign plugin need to make compatibility with the Jobs plugin to buy points and not Jobs.
