### ISSUE TITLE
Give and remove special items when leaving and joining a job.

### ISSUE THREAD

**Issue by PSILONCRAFT** [Zrips/Jobs#397]
Hi is there a mechanic for giving a job special items like real good axe to the woodcutter and if the woodcutter leaves the job the item is removed from that player?

**Comment by montlikadani** [comment]
If the player is no longer in the job where the items are located, will no longer receive a bonus for the specified item usage.
If you want to give yourself a item then execute this command: **/jobs give [playername] [jobname]/[jobitemname] [items/limiteditems] [jobitemname]**
