### ISSUE TITLE
Wheat and Sugar Cane doesn't pay and errors in console 1.12.2

### ISSUE THREAD

**Issue by IITFA** [Zrips/Jobs#399]
Server git-Spigot-79a30d7-acbc348 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Jobs v4.10.3

There's a bunch of errors about items I know 1.12.2 doesn't have, but the following caught my eye:
10.04 04:49:52 [Server] WARN [Jobs] Job Farmer has an invalid Break type property: WHEAT (wheat-7)! Material must be a block!
10.04 04:49:52 [Server] WARN [Jobs] Job Farmer has an invalid Break type property: SUGAR_CANE (sugar_cane)! Material must be a block!
10.04 04:49:52 [Server] WARN [Jobs] Job Farmer has an invalid Break type property: NETHER_WART (nether_wart)! Material must be a block!

Oddly enough, Jobs was paying for wheat at least at one point but at some point unknown it stopped paying.

**Comment by montlikadani** [comment]
Describes WHEAT needs to specify age of plant.
WHEAT replace to: wheat-7
SUGAR_CANE to sugar_cane_block
NETHER_WART to nether_wart

**Comment by IITFA** [comment]
They're already set to that it seems in the config. Still doesn't pay.

https://hastebin.com/ajebicucat.coffeescript
