### ISSUE TITLE
bad performance

### ISSUE THREAD

**Issue by k3ldon** [Zrips/Jobs#4]
hi zrips can you take a look with this...

http://timings.aikar.co/?url=11456271

**Comment by Zrips** [comment]
Are you getting any errors?

**Comment by Zrips** [comment]
And paste your generalConfig file

**Comment by k3ldon** [comment]
here: http://paste.ubuntu.com/11456955/

**Comment by Zrips** [comment]
try to set up economy-batch-delay: 5 to 10 and check if this will help with performance. If not give me a shout.

**Comment by Zrips** [comment]
or you can try to set up economy-async: true

**Comment by k3ldon** [comment]
ok I'll try
