### ISSUE TITLE
EntityDeathEvent error

### ISSUE THREAD

**Issue by PabloMA98** [Zrips/Jobs#40]
This error occurs every time a player kills a mob: https://www.spigotmc.org/attachments/error-txt.160079/

I use Jobs v3.5.7 (Beta) in Spigot 1.10.2.

**Comment by sgtcaze** [comment]
I believe Zrips addressed it in:
https://github.com/Zrips/Jobs/commit/558f775b2b1f8824c1cee3c71db03835e499a9a0

**Comment by Portanna** [comment]
I got the same error..
