### ISSUE TITLE
Worldguard region support does not work

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/Jobs#400]
Adding a Worldguard region to disable job earnings does not work and throws an error :/.

I do the following:
1) //pos1 + //pos2
2) /rg define test
3) /jobs area add wg:test 0

Error: https://pastebin.com/HEeGTBt0
Jobs 4.10.3
Paper 1.13.2 - 616
AsyncWorldEdit version 3.6.0-rc-05
WorldEdit version 7.0.0-beta-05;6bbf29b

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/06538ed4e63d43aedcdd11e34d18cf9ceed38a76

**Comment by TheoRetisch1** [comment]
Nice, thanks! Is there a way to download the fix as a development build or do I have to wait for an official release?

**Comment by montlikadani** [comment]
We will do soon a development build on Releases tab.
