### ISSUE TITLE
Hunter and Spawner

### ISSUE THREAD

**Issue by newbie029** [Zrips/Jobs#406]
enalbe-pay-near-spawner: false
will still pay you. I use StackMob Legacy

Server version : Paper 1.12.2
Plugin version : latest

**Comment by montlikadani** [comment]
- Make sure that you have enabled in the StackMob configuration the `jobs-reborn.enabled` option.
- Make sure that you have added an entity to the `jobs-reborn.blacklist` in StackMob configuration.
