### ISSUE TITLE
1.14

### ISSUE THREAD

**Issue by ziemniok99** [Zrips/Jobs#407]
Hello will this plugin work with 1.14

**Comment by smmmadden** [comment]
based on the long list of material id's being changed and introduced, some things will work and others will not.  You can review the list of changes on their release announcement here: https://www.minecraft.net/en-us/article/village---pillage-out-java-

So I suspect the team will be updating the plugin as they are able to.  Personally, I'd hold off a couple weeks before upgrading your servers as it has only been out for <48 hours and history has proven that there will be a patch for 1.14 once the bugs start coming in.  I also know that there haven't been many 1.13.2 plugins updated for 1.14 just yet.

**Comment by montlikadani** [comment]
@ziemniok99 Spigot/Paper or other server software has not yet officially released version 1.14. At Spigot, the last commit was just a trial and not the official 1.14 release.

**Comment by mrfloris** [comment]
The dev build of spigot 1.14 was released today though.

**Comment by montlikadani** [comment]
@mrfloris Ok, but the BuildTools is not generating a 1.14 jar file, just the old 1.13 replaces to new. Many sites, if a new version is released, will be updated, but not now because there is no release. Spigot writes that 1.14, but not final.

**Comment by mrfloris** [comment]
--rev 1.14
on buildtools, and you get the jar.

Loads of plugins can already start development now and update. Actually, loads of plugins appear to be working on 1.14

That all said, i DO agree that it's for dev/testing only at this stage, and not the 'recommended' version. I agree.

**Comment by Zrips** [comment]
Without special update Jobs will not work for 1.14 Will be working on it shortly enough.
