### ISSUE TITLE
java.lang.ClassCastException: org.bukkit.material.MaterialData cannot be cast to org.bukkit.material.Sign

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/Jobs#410]
spigot: CraftBukkit version git-Spigot-1eece4f-8ddb94d (MC: 1.14) (Implementing API version 1.14-R0.1-SNAPSHOT)

Our console is full written with these errors

https://pastebin.com/QtvyqF3U

**Comment by Blueeyestar** [comment]
Unfortunately, the mistake keeps coming back. I hope you will get the bug fixed.

https://pastebin.com/G01QJJzK

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/197232cdfc4596405117b8b0b02a5fe20608ed64
