### ISSUE TITLE
Jobs doesn't hook into vault?

### ISSUE THREAD

**Issue by Dracathio** [Zrips/Jobs#412]
Alright so I'll just leave this here.
http://prntscr.com/nl7uw8

I'm using the last 1.13.2 update of Jobs before the 2 1.14 updates to the plugin... so...
No clue why it's not hooking into the latest version of vault > . >

**Comment by montlikadani** [comment]
Take a screenshot about your server plugins.

**Comment by Dracathio** [comment]
http://prntscr.com/nl867t

**Comment by Dracathio** [comment]
Like I said I'm using the latest version of Vault in the link given from the "Error" and using Jobs version 4.10.3

**Comment by montlikadani** [comment]
You using the CMI plugin that handles the Vault plugin. Do you installed the Vault from CMI page?

**Comment by Dracathio** [comment]
ugh... when will you guys have CMI hook properly into a regular vault...  I'm sure the version of vault used by CMI is why I can't have towny or other plugins work properly with my formated version of currency.

**Comment by montlikadani** [comment]
Then enable the Vault economy hook in CMI  configuration.

**Comment by Dracathio** [comment]
but yea I did forget the Injector, hopefully that fixes it.
