### ISSUE TITLE
Re-brand JobsReborn to be an alternaitve to AutoRank

### ISSUE THREAD

**Issue by FrozenBeard** [Zrips/Jobs#415]
Please can you adapt JobsReborn to be an alternative to AutoRank, the structure is there to have a fully automated ranking system based on Stats, Add more stats like blocks broken/placed and distance travelled and instead of money have we run commands to upgrade ranks, its so close to being an alternative to autorank, but with a better UI in-game.

**Comment by montlikadani** [comment]
AutoRank is compatible with JobsReborn, and these are what you want to do not in this plugin, but in the AutoRank plugin.
