### ISSUE TITLE
[PlaceholderAPI] Jobs is currently using a deprecated method to hook into PlaceholderAPI. This will be disabled after the next update. Please consult [phrstbrn] and urge them to updat

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/Jobs#421]
[PlaceholderAPI] Jobs is currently using a deprecated method to hook into PlaceholderAPI. This will be disabled after the next update. Please consult [phrstbrn] and urge them to updat

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/issues/413
Install the dev version.

**Comment by Eth3rn3l** [comment]
@montlikadani , Which one PlaceHolder or Jobs plugin ? i need to download in dev version !

**Comment by montlikadani** [comment]
> 
> 
> @montlikadani , Which one PlaceHolder or Jobs plugin ? i need to download in dev version !

https://github.com/Zrips/Jobs/releases/tag/4.11.2

**Comment by Eth3rn3l** [comment]
Omg , thanks !
