### ISSUE TITLE
Jobs money not feeding into EssentialsX economy

### ISSUE THREAD

**Issue by Elibaby** [Zrips/Jobs#422]
I have EssentialsX, Vault, and Jobs Reborn, all most recent updates. I get no errors of any sort, but when people earn money in my server, it goes nowhere. I can see that Vault knows which economy it's using, but it doesn't seem Jobs knows where to direct the money earned.

**Comment by comonier** [comment]
same problem
14.05 19:33:57 [Server] Craft Scheduler Thread - 0/WARN [Jobs] Plugin Jobs v4.11.1 generated an exception while executing task 598
14.05 19:33:57 [Server] INFO java.lang.IllegalStateException: UserBalanceUpdateEvent cannot be triggered asynchronously from another thread.
14.05 19:33:57 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[spigot-1.14.jar:git-Spigot-1eece4f-8879c31]
14.05 19:33:57 [Server] INFO at com.earth2me.essentials.User.setMoney(User.java:429) ~[?:?]
14.05 19:33:57 [Server] INFO at com.earth2me.essentials.api.Economy.setMoney(Economy.java:147) ~[?:?]
14.05 19:33:57 [Server] INFO at com.earth2me.essentials.api.Economy.add(Economy.java:174) ~[?:?]
14.05 19:33:57 [Server] INFO at com.earth2me.essentials.api.Economy.add(Economy.java:166) ~[?:?]
14.05 19:33:57 [Server] INFO at net.milkbowl.vault.economy.plugins.Economy_Essentials.tryDepositPlayer(Economy_Essentials.java:149) ~[?:?]
14.05 19:33:57 [Server] INFO at net.milkbowl.vault.economy.plugins.Economy_Essentials.depositPlayer(Economy_Essentials.java:180) ~[?:?]
14.05 19:33:57 [Server] INFO at net.milkbowl.vault.economy.AbstractEconomy.depositPlayer(AbstractEconomy.java:50) ~[?:?]
14.05 19:33:57 [Server] INFO at com.gamingmesh.jobs.economy.VaultEconomy.depositPlayer(VaultEconomy.java:32) ~[?:?]
14.05 19:33:57 [Server] INFO at com.gamingmesh.jobs.tasks.BufferedPaymentTask.run(BufferedPaymentTask.java:40) ~[?:?]
14.05 19:33:57 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.jar:git-Spigot-1eece4f-8879c31]
14.05 19:33:57 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.jar:git-Spigot-1eece4f-8879c31]
14.05 19:33:57 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
14.05 19:33:57 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
14.05 19:33:57 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

**Comment by CodingKoopa** [comment]
Not sure how relevant/updated this is, but [this](https://www.spigotmc.org/wiki/spigot-1-14-plugin-compatibility-list/) page says that EssentialsX has issues on 1.14.

**Comment by Elibaby** [comment]
> same problem
> 14.05 19:33:57 [Server] Craft Scheduler Thread - 0/WARN [Jobs] Plugin Jobs v4.11.1 generated an exception while executing task 598
> 14.05 19:33:57 [Server] INFO java.lang.IllegalStateException: UserBalanceUpdateEvent cannot be triggered asynchronously from another thread.
> 14.05 19:33:57 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[spigot-1.14.jar:git-Spigot-1eece4f-8879c31]
> 14.05 19:33:57 [Server] INFO at com.earth2me.essentials.User.setMoney(User.java:429) ~[?:?]
> 14.05 19:33:57 [Server] INFO at com.earth2me.essentials.api.Economy.setMoney(Economy.java:147) ~[?:?]
> 14.05 19:33:57 [Server] INFO at com.earth2me.essentials.api.Economy.add(Economy.java:174) ~[?:?]
> 14.05 19:33:57 [Server] INFO at com.earth2me.essentials.api.Economy.add(Economy.java:166) ~[?:?]
> 14.05 19:33:57 [Server] INFO at net.milkbowl.vault.economy.plugins.Economy_Essentials.tryDepositPlayer(Economy_Essentials.java:149) ~[?:?]
> 14.05 19:33:57 [Server] INFO at net.milkbowl.vault.economy.plugins.Economy_Essentials.depositPlayer(Economy_Essentials.java:180) ~[?:?]
> 14.05 19:33:57 [Server] INFO at net.milkbowl.vault.economy.AbstractEconomy.depositPlayer(AbstractEconomy.java:50) ~[?:?]
> 14.05 19:33:57 [Server] INFO at com.gamingmesh.jobs.economy.VaultEconomy.depositPlayer(VaultEconomy.java:32) ~[?:?]
> 14.05 19:33:57 [Server] INFO at com.gamingmesh.jobs.tasks.BufferedPaymentTask.run(BufferedPaymentTask.java:40) ~[?:?]
> 14.05 19:33:57 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.jar:git-Spigot-1eece4f-8879c31]
> 14.05 19:33:57 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.jar:git-Spigot-1eece4f-8879c31]
> 14.05 19:33:57 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
> 14.05 19:33:57 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
> 14.05 19:33:57 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

I actually get this exact error, I overlooked it in my console thinking it was something else.

**Comment by Elibaby** [comment]
> Not sure how relevant/updated this is, but [this](https://www.spigotmc.org/wiki/spigot-1-14-plugin-compatibility-list/) page says that EssentialsX has issues on 1.14.

I noticed that, but I feel like since Vault knows it's hooked to Essentials, its Jobs that isn't doing the right thing here. Especially because the error

**Comment by PassiAPI** [comment]
Have the same issue. Think, that the update from 4.11.1 -> 4.11.1 didn't fix it.

**Comment by Zrips** [comment]
This is issue from Essentials itself not handling events correctly. Which economy-async to false to solve this issue until Essentials fix at their end.
