### ISSUE TITLE
CPU Usage

### ISSUE THREAD

**Issue by Straiker123** [Zrips/Jobs#425]
Jobs: 4.11.2
Minecraft: Spigot 1.14.1

Hello, my server is lagging very much, I test server with timings and result is Jobs have 36% CPU usage (lower than residence)
Please improve cpu usage of plugin.

**Comment by montlikadani** [comment]
Timings paste?

**Comment by Straiker123** [comment]
[timings.txt](https://github.com/Zrips/Jobs/files/3194818/timings.txt)
here

**Comment by montlikadani** [comment]
In order for your server to work properly, Bukkit events are needed to allow the player to do something on his server. Use the [SpigotTimings](https://www.spigotmc.org/wiki/timings/) option to check the server ram.

**Comment by Straiker123** [comment]
https://timings.spigotmc.org/?url=eqomekihoh

**Comment by Straiker123** [comment]
https://bugs.mojang.com/browse/MC-150824
