### ISSUE TITLE
Can't load data from MySQL database. 

### ISSUE THREAD

**Issue by mickcoyne** [Zrips/Jobs#43]
29.08 22:45:54 [Server] ERROR [Jobs] Could not initialize database! Could not determine schema version!

Help.... I am using MySQL. My players data is in the database...I really need to be able to use it but the plugin just decided not to load that data anymore. This was out of the blue and I can't think of any related issues.

Do to my laziness I am adding this notice from my server to my players:
For those of you wondering what is going on with the jobs plugin:
Yesterday, Oodely noticed that jobs was not syncing between servers/it was glitchy. I thought this was an issue with syncing on the grinder server but I ended up finding out that the towny server was not saving to the database. We couldn't see this at first because jobs leveling was normal on the towny server since it was all loaded in temporary memory (RAM) However, once the server restarted that temporary memory was flushed and we found out that not only could it not save data--but it couldn't load it either. Here is what we know...
1. The error is: [Server] ERROR [Jobs] Could not initialize database! Could not determine schema version!
2. We know that it has nothing to do with the machine itself as other plugins use the same database.
3. We know it's not the config as I did not change it.
4. Because of 1-3 we can assume it is something wrong with the plugin and the dev has been contacted
5. All your jobs data is safe, it just can't be loaded for some reason.

**Comment by montlikadani** [comment]
**Try update to the latest version.**
