### ISSUE TITLE
Invalis items and block types

### ISSUE THREAD

**Issue by Klawdek** [Zrips/Jobs#431]
I am using the latest dev build 4.11.2 DEV and minecraft/spigot 1.13.2 and I get the following error:
24.05 19:38:51 [Server] INFO Enabling Jobs v4.11.2
24.05 19:38:59 [Server] INFO PlaceholderAPI hooked.
24.05 19:38:59 [Server] INFO PlaceholderAPI was found - Enabling capabilities.
24.05 19:39:00 [Server] INFO Loaded 8 titles!
24.05 19:39:00 [Server] INFO Loaded 75 protected blocks timers!
24.05 19:39:00 [Server] INFO Loaded 890 custom item names!
24.05 19:39:00 [Server] INFO Loaded 59 custom entity names!
24.05 19:39:00 [Server] INFO Loaded 34 custom enchant names!
24.05 19:39:00 [Server] INFO Loaded 16 custom color names!
24.05 19:39:00 [Server] INFO Loaded 35 custom potion names!
24.05 19:39:00 [Server] ERROR Shop item SuperPickAxe has an invalid Icon name property. Skipping!
24.05 19:39:00 [Server] ERROR Shop item WoodenShovel has an invalid Icon name property. Skipping!
24.05 19:39:00 [Server] ERROR Shop item LureEnchantBook has an invalid Icon name property. Skipping!
24.05 19:39:00 [Server] ERROR Shop item Elytra has an invalid Icon name property. Skipping!
24.05 19:39:01 [Server] WARN Job Miner has an invalid Break type property: NETHER_BRICK (nether_brick)! Material must be a block!
24.05 19:39:01 [Server] WARN Job Builder has an invalid Place type property: NETHER_BRICK (nether_brick)! Material must be a block!
24.05 19:39:01 [Server] INFO Loaded 12 jobs!

**Comment by montlikadani** [comment]
See the latest changes. This is not a plugin code error.
