### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by comonier** [Zrips/Jobs#432]
https://paste.ofcode.org/8Zfzih2uZEjNtxgNLjshng

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/issues/428

**Comment by comonier** [comment]
mine is not from 4.11.1 is 4.11.2 u link wrong its not about the same version.

**Comment by montlikadani** [comment]
The 4.11.2 dev version the problem what you post, this fixes.

**Comment by montlikadani** [comment]
In 4.11.2 dev version fixes the problem, that you sent.

**Comment by comonier** [comment]
the money problem its already solved on 4.11.2 yes agreed the jobs is working, yes i agreed, but the console erro still on 4.11.2 like i link so... its complety fixed? no.

**Comment by montlikadani** [comment]
Install the latest 1.14 version of EssentialsX

**Comment by comonier** [comment]
[Sat, 25. May 2019 11:37:35 EDT INFO] CONSOLE issued server command: /ess version
[Sat, 25. May 2019 11:37:35 EDT INFO] Server version: 1.14.1-R0.1-SNAPSHOT git-Spigot-03bd4b0-c45c0a9 (MC: 1.14.1)
[Sat, 25. May 2019 11:37:35 EDT INFO] EssentialsX version: 2.16.1.156
[Sat, 25. May 2019 11:37:35 EDT INFO] PermissionsEx version: 1.23.4
[Sat, 25. May 2019 11:37:35 EDT INFO] Vault version: 1.7.2-b107
[Sat, 25. May 2019 11:37:35 EDT INFO] EssentialsXChat version: 2.16.1.156
[Sat, 25. May 2019 11:37:35 EDT INFO] EssentialsXGeoIP version: 2.16.1.156
[Sat, 25. May 2019 11:37:35 EDT INFO] EssentialsXSpawn version: 2.16.1.156

you can check that here:
https://ci.ender.zone/job/EssentialsX/

**Comment by montlikadani** [comment]
The 2.16.1.156 version is only for under 1.13
Use this: https://ci.ender.zone/job/EssentialsX-Experimental/
