### ISSUE TITLE
Sometimes excepting when blocks broken in creative

### ISSUE THREAD

**Issue by smellyonionman** [Zrips/Jobs#434]
FYI.  Nothing in-game seems broken.  Hope you're having a good weekend.

25.05 17:28:50 [Server] ERROR Could not pass event BlockBreakEvent to Jobs v4.11.2
25.05 17:28:50 [Server] INFO java.lang.NullPointerException: null
25.05 17:28:50 [Server] INFO at com.gamingmesh.jobs.nmsUtil.v1_13.getDurability(v1_13.java:47) ~[?:?]
25.05 17:28:50 [Server] INFO at com.gamingmesh.jobs.listeners.JobsPaymentListener.onBlockBreak(JobsPaymentListener.java:404) ~[?:?]
25.05 17:28:50 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor487.execute(Unknown Source) ~[?:?]
25.05 17:28:50 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-624]
25.05 17:28:50 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-624]
25.05 17:28:50 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-624]
25.05 17:28:50 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-624]
25.05 17:28:50 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerInteractManager.breakBlock(PlayerInteractManager.java:299) ~[patched_1.13.2.jar:git-Paper-624]
25.05 17:28:50 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:129) ~[patched_1.13.2.jar:git-Paper-624]
25.05 17:28:50 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1271) ~[patched_1.13.2.jar:git-Paper-624]
25.05 17:28:50 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.13.2.jar:git-Paper-624]
25.05 17:28:50 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.13.2.jar:git-Paper-624]
25.05 17:28:50 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-624]
25.05 17:28:50 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
25.05 17:28:50 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
25.05 17:28:50 [Server] INFO at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-624]
25.05 17:28:50 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-624]
25.05 17:28:50 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-624]
25.05 17:28:50 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-624]
25.05 17:28:50 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-624]
25.05 17:28:50 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by montlikadani** [comment]
#427
