### ISSUE TITLE
console error Jobs v4.11.2 EssentialsX version: 2.16.1.180-mc114-b95

### ISSUE THREAD

**Issue by comonier** [Zrips/Jobs#435]
https://paste.ofcode.org/F6BR2efjhNt23mY68t6dxa
https://paste.ofcode.org/3p6k7hnDYNrActEH77akCB
https://paste.ofcode.org/TpQ5SbKepLpqSXFLiA8gv9
ess version:
[Sat, 25. May 2019 21:19:22 EDT INFO] CONSOLE issued server command: /ess version
[Sat, 25. May 2019 21:19:22 EDT INFO] Server version: 1.14.1-R0.1-SNAPSHOT git-Spigot-03bd4b0-17da342 (MC: 1.14.1)
[Sat, 25. May 2019 21:19:22 EDT INFO] EssentialsX version: 2.16.1.180-mc114-b95
[Sat, 25. May 2019 21:19:22 EDT INFO] PermissionsEx version: 1.23.4
[Sat, 25. May 2019 21:19:22 EDT INFO] Vault version: 1.7.2-b107
[Sat, 25. May 2019 21:19:22 EDT INFO] EssentialsXChat version: 2.16.1.180-mc114-b95
[Sat, 25. May 2019 21:19:22 EDT INFO] EssentialsXGeoIP version: 2.16.1.180-mc114-b95
[Sat, 25. May 2019 21:19:22 EDT INFO] EssentialsXSpawn version: 2.16.1.180-mc114-b95

**Comment by Zrips** [comment]
update **economy-async** and change it to **false** and wait for essentials update which can handle async payments. Until then we cant really do anything about it from our end.

**Comment by comonier** [comment]
> update **economy-async** and change it to **false** and wait for essentials update which can handle async payments. Until then we cant really do anything about it from our end.

`# Enable async economy calls.
# Disable this if you have issues with payments or your plugin is not thread safe.
economy-async: false
did it on generalConfig.yml`

what it do?
