### ISSUE TITLE
Job limit resets after player reconnect twice when MultiServerCompatability is enabled.

### ISSUE THREAD

**Issue by ysy960108** [Zrips/Jobs#436]
I have MultiServerCompatability set to true, and I have 2 servers sharing one Jobs database. 
When player reached its limit, the limit can be reset in following steps in a short period:
1. Quit the server (by player itself)
2. Re-connect the server
3. Quit server again
4. Re-connect the server again, and the limit is gone.

I have tested on single server with MultiServerCompatability set to true, it can also happens.

---

**CONFIG SECTION:**

save-on-disconnect: true
...
MultiServerCompatability: true

---

**Server Type: Spigot
**Server Version:  1.12.2

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/issues/198
