### ISSUE TITLE
Some Material name don't work

### ISSUE THREAD

**Issue by Aurelien30000** [Zrips/Jobs#440]
***Description of issue:**
Hello,
I have a 1.12.2 server on PaperSpigot with the last version of JobsReborn.
I would like to use some of the material names in 1.12.2 like MELON_BLOCK or REDSTONE_LAMP_ON, but it does not work, even after trying the legacy_name, or whatever, is this a bug or is there a particular handling to carry out ? Thank you :)
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## Job Cultivateur has an invalid Break type property: MELON_BLOCK!
## Job Ingenieur has an invalid Break type property: REDSTONE_LAMP_ON!
####################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE 
## 
##      REDSTONE_LAMP_ON:
##        income: -10.5
##        points: -10.5
##      MELON_BLOCK:
##        income: 3.0
##        points: 3.0
##        experience: 3.0
#####################################
```

---

**Server Type (Spigot/Paperspigot/etc):** Paper Spigot

**Server Version (using `/ver`):** git-Paper-1613 (MC: 1.12.2)

**Comment by montlikadani** [comment]
Did you tried with lower-cased chars such as `melon_block`?

**Comment by Aurelien30000** [comment]
Yep, with the same problem :/

**Comment by montlikadani** [comment]
Use the `melon` instead of melon_block
The redstone_lamp_on is not been added, and we try to use the `legacy_redstone_lamp_on` material, but this not added now.

**Comment by Aurelien30000** [comment]
`Job Cultivateur has an invalid Break type property: MELON (melon)! Material must be a block!` Doesn't work either :/

**Comment by montlikadani** [comment]
In this commit fixes the melon and added the redstone_lamp_on material. This will be able in the next release.
To work this use: `melon_block` and `legacy_redstone_lamp_on`

**Comment by Aurelien30000** [comment]
Oh thank you !
But sorry to be so embarrassing but I found other items for which the action of eating this time does not work :/
```
Job Cultivateur has an invalid Eat type property: POTATO_ITEM!
 Job Cultivateur has an invalid Eat type property: CARROT_ITEM!
```

**Comment by montlikadani** [comment]
Use `potato` and `carrot`

**Comment by Aurelien30000** [comment]
Already tried, but it doesn't seem well detected, because I don't receive the payment of the trade.

**Comment by montlikadani** [comment]
Try with `potatoes` and `carrots`

**Comment by Aurelien30000** [comment]
Sadly still not working :/

**Comment by Aurelien30000** [comment]
Is there a build server or a way to get the "fixed" jar file ? :)

**Comment by DonSensiLeone** [comment]
melon or melon_block as well as many blocks (or mobs) are not recognized anymore for paiements under last build for a 1.13.2 server

**Comment by montlikadani** [comment]
These material names are work correctly with the dev version. It is only one changes for the melon is not recognized correctly and should be fixed in the dev release. So install it and test. If some materials are not work just see [this instructions](https://github.com/Zrips/Jobs/wiki/Legacy-config-support) to improve. If this listed materials still not work with this instructions, then this issue will related to client issue and not plugin, because the materials are correctly specified in the code.

**Comment by DonSensiLeone** [comment]
Since my last message my server went to version 1.14.4 and there , yes everything works (most of things that didn"t in 1.13.2) but in version 1.13.2 i never succeed to have a jobs plugin that was fully working , now it's ok :)
