### ISSUE TITLE
Removing old block protection entries takes very long time

### ISSUE THREAD

**Issue by Dakotaa** [Zrips/Jobs#441]
***Description of issue:**
On server shutdown, Jobs causes a very long wait for the server to close while it is removing old block protection entries and doing other entries. Jobs is connected to an external MySQL database. Here's an example, you can see how long it takes from the timestamps. 

```
29.05 14:00:48 [Server] INFO [Jobs] Saved 3450 new explorer entries.
29.05 14:01:57 [Server] INFO [Jobs] Updated 7139 explorer entries.
29.05 14:01:57 [Server] INFO [Jobs] Saving blocks
29.05 14:04:09 [Server] INFO [Jobs] Removed 10000 old block protection entries.
29.05 14:05:48 [Server] INFO [Jobs] Removed 20000 old block protection entries
```
---

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** Paper 626 Minecraft 1.13.2

**Comment by Flexxxxx** [comment]
We run into this on our server occasionally too. It adds a good 10-20 minutes to our restart times.

**Comment by Zrips** [comment]
229be42d64af385e7e1b41a6fbd5d614743e17ab
