### ISSUE TITLE
names not fitting on signs 

### ISSUE THREAD

**Issue by slvlr** [Zrips/Jobs#443]
if the name is short enough to fit on a sign WITHOUT color codes, then they should fit. However your plugin is using the black color code or something and is making them too long to fit on the sign so is adding a ~ to them

**Server Type paper 1.14.2  -58

**Comment by montlikadani** [comment]
This is not a bug. We need to shorts the player name on sign to ignore player name duplicate on double line on sign.

**Comment by slvlr** [comment]
This doesn't make sense?
If a name fits on a line normally, why ruin what it looks like? @montlikadani

**Comment by montlikadani** [comment]
If a player's name contains more than 8 characters, it will automatically put a "~" after the player's name so that there is no two lines in the name.

**Comment by slvlr** [comment]
But you can put 15 letters on a line.... so why would you put a ~ if they are more than 8 long? @montlikadani

**Comment by montlikadani** [comment]
![kép](https://user-images.githubusercontent.com/30026208/58753589-c890d400-84c1-11e9-80b7-a54e5dbfbe61.png)
This is an example of sign, when using **[toplist]** line.

**Comment by slvlr** [comment]
![image](https://user-images.githubusercontent.com/8680731/58753610-aeeb8e80-84b9-11e9-9684-b23d246e22eb.png)


No no, I'm talking about the name on the first, second and third boards. I understand about the long lists being shortened, but why these? @montlikadani

**Comment by montlikadani** [comment]
In this commit changes the char limit on sign. The update soon will be available on Releases tab or official page.
