### ISSUE TITLE
[Question] Clean up players' progress

### ISSUE THREAD

**Issue by DmitryRendov** [Zrips/Jobs#445]
**Description of new idea or improvement on existing one**
I have pretty clear server just making some clean up regularly in an automatic way. It'd be great to reset a player's stats using a separate command or specify term to rotate/clean up old users from the database

**Detailed information what should do what and when**
/jobs playerreset _NAME_
/jobs cleanup 100d
or smth like that

Many thanks in advance!

**Comment by montlikadani** [comment]
To clear player data from database, use `Optimizations.DBCleaning` option, that can be found in generalConfig file.
