### ISSUE TITLE
/jobs shop not working in 1.14.2

### ISSUE THREAD

**Issue by PSILONCRAFT** [Zrips/Jobs#447]
***Description of issue:**
/jobs shop command not working
---

only get Can´t open this page

**Server Type Spigot** 

**Server Version (1.14.2):**

**Comment by montlikadani** [comment]
More informations about the issue? Shop configuration, screenshot?

**Comment by PSILONCRAFT** [comment]
wow that was fast. let me do that later when im home from work

**Comment by montlikadani** [comment]
The jobs shop works correctly without any error. You have something problem in the shopItems file, that cause the shop not work.

**Comment by PSILONCRAFT** [comment]
ok so i i removed the shopitem.yml and it works. has the syntax changed since 1.13.2 cause there it worked like a charm
[shopItems.yml.txt](https://github.com/Zrips/Jobs/files/3317330/shopItems.yml.txt)
