### ISSUE TITLE
ID Conflict

### ISSUE THREAD

**Issue by lKhyst** [Zrips/Jobs#449]
***Description of issue:**

When I put, for example, to break a wood in the quests, it conflicts with other woods. The same happens with sand because of the id 12 and 12:1. But sand is a special case, if I break, it resets after a certain number.

Miner example: (WORKING)
    maxDailyQuests: 5
    Quests:
      '1':
        Name: Ferro Puro!
        Action: Break
        Target: 15-0
        Amount: 64
        RewardCommands:
        - eco give [playerName] 500
        - msg [playerName] Tarefa concluída.!
        RewardDesc:
        - Minere 64 ferros
        - para ganhar $500.
        Chance: 40
        toLevel: 100
        fromLevel: 2

Woodcutter example (NOT WORKING)

    maxDailyQuests: 5
    Quests:
      '1':
        Name: Coletar Oak Wood
        Action: Break
        Target: 17-0
        Amount: 300
        RewardCommands:
        - money give [playerName] 1250
        - msg [playerName] tarefa completada!
        RewardDesc:
        - Colete 300 Madeiras de Carvalho
        - E ganhe $1250.
        Chance: 40
        toLevel: 100
        fromLevel: 0
---

**Server Type (Spigot/Paperspigot/etc):*Spigot 1.8.8-R0.1-SNAPSHOT* 

**Server Version (using `/ver`):*1.8.8*

**Comment by montlikadani** [comment]
Do you use the latest version of Jobs?

**Comment by lKhyst** [comment]
Yes, for sure

**Comment by montlikadani** [comment]
Try with using the new format of quests targets:
such as:
```
Quests:
  myQuest:
    Objectives:
    - Break;17-0;300
```

**Comment by lKhyst** [comment]
I cant understand but like this:

Quests:
    1:
    Name: LMAO
    Objectives:
    - Break;17-0;300
?

**Comment by lKhyst** [comment]
After doing /jobs quests at Woodcutter, using this format returns to me:
There are no quests

**Comment by montlikadani** [comment]
Reload the Jobs plugin with /jobs reload and reset your quests with /jobs reset command.

**Comment by lKhyst** [comment]
There is no command by this name!
^In /jobs reset

**Comment by montlikadani** [comment]
uh, `/jobs resetquest`

**Comment by lKhyst** [comment]
Can't find any quests

**Comment by lKhyst** [comment]
It is only id conflict because the wood has several, the miner ids does not present any bug

**Comment by montlikadani** [comment]
Try to use the full name of the material. Such as: `Break;oak_log;300`

**Comment by lKhyst** [comment]
Nothing.

**Comment by lKhyst** [comment]
So?

**Comment by lKhyst** [comment]
I need help fast, my server has players and is hosted, I dont want to change the plugin to another one

**Comment by montlikadani** [comment]
This seems works with the latest version. Also you have `Chance` setting, which means you have a 40% chance of increasing your quest.
