### ISSUE TITLE
New event to modify jobs payments - JobsPrePaymentEvent

### ISSUE THREAD

**Issue by Draycia** [Zrips/Jobs#450]
**Description of new idea or improvement on existing one**
The ability to modify payments via API on an individual level and per player, instead of in batches, would be greatly appreciated and would let me add compatibility bridges with other plugins.

**Detailed information what should do what and when**
JobsPrePaymentEvent - getAmount, setAmount, getPoints, setPoints, getJob, getPlayer

Called each time a payment is calculated, after the calculation and before payment is added to the batch.

I'm willing to PR this if approved, and the event can be named something else / added onto if desired.

**Comment by montlikadani** [comment]
You can use the [JobsPaymentEvent](https://github.com/Zrips/Jobs/blob/master/src/main/java/com/gamingmesh/jobs/api/JobsPaymentEvent.java) that these methods contains in this event. Only the points are not in this, to get the exp event, use  [JobsExpGainEvent](https://github.com/Zrips/Jobs/blob/master/src/main/java/com/gamingmesh/jobs/api/JobsExpGainEvent.java)

**Comment by Draycia** [comment]
PaymentEvent doesn't say which job it's for, as it triggers when the player receives money, not when the payment is calculated from an action.

**Comment by montlikadani** [comment]
You can create a PR that contains the API event modifications that are required for the payment event.
