### ISSUE TITLE
%jobsr_name_jname% don't work :(

### ISSUE THREAD

**Issue by SamuDu24** [Zrips/Jobs#451]
***Description of issue:**

Hi, I'm having a problem with JobsReborn. I would like to show the skill exercised by the player in the scoreboard, but the variable does not work. No matter what job you do, the variable displays a job that never changes, and even new players have the first connection to this job displayed.
It does not come from the Scoreboard plugin, I have tried several, the result is the same. I leave you a maximum of images to present you the worries, the trades concerned are in French.

This is the jobConfig.yml : https://pastebin.com/36RjXhtR
I used for the images the command _/jobs placeholder parse %jobsr_name_1%_.

<a href="https://www.noelshack.com/2019-23-2-1559664421-jobs-result.jpg"><img src="https://image.noelshack.com/minis/2019/23/2/1559664421-jobs-result.png" border="0" alt="1559664421-jobs-result.jpg - envoi d'image avec NoelShack" title="1559664421-jobs-result.jpg"/></a>

<a href="https://www.noelshack.com/2019-23-2-1559664424-jobs-stats.jpg"><img src="https://image.noelshack.com/minis/2019/23/2/1559664424-jobs-stats.png" border="0" alt="1559664424-jobs-stats.jpg - envoi d'image avec NoelShack" title="1559664424-jobs-stats.jpg"/></a>

<a href="https://www.noelshack.com/2019-23-2-1559664427-versions.jpg"><img src="https://image.noelshack.com/minis/2019/23/2/1559664427-versions.png" border="0" alt="1559664427-versions.jpg - envoi d'image avec NoelShack" title="1559664427-versions.jpg"/></a>

Thanks you so much !

**Comment by montlikadani** [comment]
You should use the latest version of Jobs and needs PlaceholderAPI to work the placeholders.

**Comment by SamuDu24** [comment]
Yes, I already have PlacerHolderAPI, and the command /papi parse me %jobsr_name_1% also gives me the result of Bûcheron job.

**Comment by montlikadani** [comment]
Did you installed the Jobs expansion to papi ecloud with `/papi ecloud download Jobs` command?

**Comment by SamuDu24** [comment]
Yes :/

**Comment by montlikadani** [comment]
This working properly, just you using the %jobsr_name_jname% and not the jobname in that placeholder. If you specify %jobsr_name_jname% placeholder then returns null, so you need to specify instead jname the job name.

**Comment by SamuDu24** [comment]
Oh no, I thought this placeholder could display in the scoreboard the job done by the player, I was totally wrong I'm sorry ... There is no placeholder to display the job of the player ?

**Comment by montlikadani** [comment]
Currently no, only specifiable manually the job with %jobsr_name_1% placeholder.

**Comment by SamuDu24** [comment]
Ah it's been so long since I tried to solve this problem, I was not expecting it, sorry for making you waste your time! :x

**Comment by montlikadani** [comment]
If you want a placeholder to show the current job name when the player is in, open a new issue with New feature suggestion label.
