### ISSUE TITLE
Player dont receive money for job

### ISSUE THREAD

**Issue by ReaperofSouls89** [Zrips/Jobs#453]
***Description of issue:**
So I installed this plugin 2 nights ago, it was working fine but players had access to all commands, I was going to look into that the next day.  The next day I got on none of the players, nor I the owner, had access to any command and no permission to do /jobs join.  After going through permission after permission I was finally able to see the problem.  My UPERMS plugin didnt have the permission jobs.join.[job], so I typed in the permission ,jobs.join.*, and it worked players could do /jobs join.  But, they couldnt select a job, so back to permission after permission enabling everything that didnt have to do with admin commands or access to all commands.  Finally found it to where they could now join a profession, but they didnt get paid for the jobs they completed.  Back to the permissions again, this time I just enabled jobs.*, and success players got paid but they had access to all commands.  Id add the config but I have since then removed the plugin from the server as I had tried to ask my question on discord and it was over looked by staff.  Is there a permission Im missing or does it not work with the UPERMS or essentialsX plugins?

**Server Type (Spigot/Paperspigot/etc):** 

Spigot

**Server Version (using `/ver`):** 

1.14.2

**Relevant plugins (Delete if this isn't needed):**

Ultra perms, essentialsX, mcmmo, towny, advanced region market, worldguard, worldedit, chestshop, clearlagg, donate craft, no phantoms, set the spawn, spawnsilk, superbvote, vault, votifier, and wildtp.

Dont know if thats what you wanted for relevant plugins but thats all the plugins I have on my server so far.

**Comment by montlikadani** [comment]
Have you tried to specify `jobs.use` permission?

**Comment by CodingKoopa** [comment]
I have granted my players `jobs.use` and `jobs.world.main` (`main`) being my world name) with LuckPerms, but players are not paid.

**Comment by montlikadani** [comment]
@CodingKoopa
Make sure you using the vault plugin.
Make sure you using the CMI plugin and vault then you should enable the vault integration option to make compatibility with CMI and vault.

**Comment by CodingKoopa** [comment]
For me updating the Jobs plugin to the latest version fixed the issue.

**Comment by DonSensiLeone** [comment]
On a 1.13.2 server , nothing touched in the configs (was working quite before , quite because mobs are bugged for paiement) jobs don't pay for all actions anymore , especially miner that won't get pay to mine any kind of stone or ores.. with latest update of Jobs (4.13.0)
