### ISSUE TITLE
Jobs Tax system bypass permision

### ISSUE THREAD

**Issue by TheSalon112** [Zrips/Jobs#455]
Hello

Im here for feature request

As title saying, could you please add Job TAX bypass, and /or something like jobs tax percentage permission (group with permision jobs.tax.percentage.20, will have 20% jobs taxes; etc)

Thanks

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/42969fb8b372476de4291b1ccb2be1765dceb51d
