### ISSUE TITLE
Error on command

### ISSUE THREAD

**Issue by HollishKid** [Zrips/Jobs#456]
***Description of issue:***
When I use the command /jobs playerinfo [non-existing player] job action, I get the following error. Not that it matters, just wanted to let you know.
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
https://pastebin.com/YGH8rB33
---

**Server Version (using `/ver`):** 
 This server is running CraftBukkit version git-Spigot-1a3504a-dfa7583 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Relevant plugins (Delete if this isn't needed):**
I dont this this section is required.
Thanks for your help and this very nice resource!

**Comment by montlikadani** [comment]
Jobs plugin version?
