### ISSUE TITLE
Quest reset doesn't work.

### ISSUE THREAD

**Issue by Aurelien30000** [Zrips/Jobs#460]
**Description of issue:**
With the command /jobs resetquest or the automatic refresh of the quests, it doesn't work, the are not reset :/

If you need more information, don't hesitate to ask me :)

Thank you in advance.

---

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot

**Server Version (using `/ver`):** This server is running Paper version git-Paper-1615 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by montlikadani** [comment]
- Any console error?
- In what job occurs this (send that job section to pastebin.com with quests)
- Jobs version

**Comment by Aurelien30000** [comment]
- No console error
- Occurs with all my jobs : https://pastebin.com/Pqk6XgFL
- Jobs v4.13.0

**Comment by montlikadani** [comment]
A lot of quests loaded in one job. Did you know to use the Objectives in multiple lines in one quest?
Such as:
```
Objectives:
- Break;oak_log;15
- Place;stone;30
```

**Comment by Aurelien30000** [comment]
Yes but it's not considered as an independent quest :/ Moreover, I think that a dozen quests per job is not excessive, without that, the quest would be repetitive and boring :/

**Comment by Aurelien30000** [comment]
Should I test something specific with them ? I also want to clarify that nothing changes, not even my quest progression, it's as if I had never executed this command.

**Comment by Daxxas** [comment]
I also have the same issue as him, could it be because we use the old quest format ?
 ```   Quests:
      IronQuest:
        Name: "&7Récupère du fer"
        Action: Break
        Target: "iron_ore"
        Amount: 96
        RewardCommands:
        - "money give [playerName] 750"
        - "msg ![playerName] &7Tu as complété la quête!"
        RewardDesc:
        - "&7Casse &ax96 Minerais de fers&r"
        - "&7Récompense:"
        - "- &e750 Or&r"
        Chance: 10
        toLevel: 50
        fromLevel: 1```

**Comment by Aurelien30000** [comment]
I don't think, I used the old format, but with the new, there is the same issue :/

**Comment by mercurialmusic** [comment]
I'm getting the same. Not everyone is reporting it, but I'm not sure how much everyone is paying attention.

**Comment by Aurelien30000** [comment]
Any news, please it's annoying for my players and I can't back to the previous version :/

Thank you in advance :)

**Comment by Drewflav** [comment]
Same issue here after updating to 4.13 from 4.11. Quests were resetting automatically just fine the day before.

**Comment by Aurelien30000** [comment]
Any news, please, it's annoying :x

**Comment by Drewflav** [comment]
Still waiting on an update here.

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/a569f84a734dff42a7db3123932d85656c1e89d6
This commit includes a fix that will now completely restore the player and all in-progress quests, including both completed and ongoing quests. This was not added because those who reset the quest completely to 0 were complimented by the fact that their previously collected quest went to 0, making the user nervous. But it will still do so.

We are sorry that we added this late because we couldn't decide whether to completely reset the quest or only time, so far only time has been restored for the reasons mentioned above.

**Comment by mercurialmusic** [comment]
This bug is still occurring.

**Comment by Aurelien30000** [comment]
I can confirm, quests are the same everyday, progression seems to be reset but never change :x

**Comment by mercurialmusic** [comment]
Progression still doesn't change for me. They mine 1 stone and get the mine 500 stone quest.
