### ISSUE TITLE
configurable balancing

### ISSUE THREAD

**Issue by DailyStruggle** [Zrips/Jobs#461]
**Description of new idea or improvement on existing one**
It's often an issue that one job gets more attention than others. It's a pain to constantly monitor occupations, balance rewards in the config, and reload to update.

I would like jobs to allow automatically weighted rewards, based on the percentage of players gravitating to one job. or away from another 

**Detailed information what should do what and when**
set each job's weight to 1.
check the number of jobs available and the number of players in each job field. 
infer the number of players that should occupy a job.
adjust by a configurable amount, shifting the reward to the other jobs
multiply the original rewards by the weight.

ex:
If a job in a 7-job system is more than 1/7 of occupied jobs after a day, multiply the weight by 0.95 and adjust the other jobs such that the sum of the weights is constant.
If a job in a 7-job system is less than 1/7 of occupied jobs after a day, multiply the weight by 1.05  and adjust the other jobs such that the sum of the weights is constant.

**Comment by PhantomXN** [comment]
It's my opinion.
Is it possible to add some parameter for progression equation?
like the number of jobs available, and the number of player that has joined at least a job, and the number of how many players join the current job.
if so, then we can config the progression for balancing.

**Comment by DailyStruggle** [comment]
My goal is to get players to try different jobs.

correct me if I'm wrong, but I thought pay for high-level job members was just a multiple of the base pay. If the base pay changes, so would the pay for any job members at higher levels. 

If you instead want to adjust progression tables for more active or less active job fields, you could still use:
- number of jobs (constant int)
- total sum of occupations (int)
- number of players in this job field (int)

**Comment by Zrips** [comment]
@DailyStruggle Did you checked DynamicPayment? There is an option to add a penalty or bonus to jobs which have a bunch of people working in it. So you can add 50% penalty to payment for a job miner which has 1000 workers while adding like 100% (double pay) bonus to a farmer jobs which only has like 10 workers. So its more or less self-balancing system.
