### ISSUE TITLE
Melon block not recognized

### ISSUE THREAD

**Issue by Daxxas** [Zrips/Jobs#464]
***Description of issue:**
The melon block is not recognized by the plugin
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**

https://pastebin.com/d2hcXvYP

---

**Server Type (Spigot/Paperspigot/etc):**  Spigot

**Server Version (using `/ver`):** 

[23:26:15 INFO]: This server is running CraftBukkit version git-Spigot-1a3504a-dfa7583 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[23:26:15 INFO]: This is a final build for 1.13.2. Please see https://www.spigotmc.org/go/1.13.2 for details about upgrading.

**Comment by montlikadani** [comment]
Changed in this commit: https://github.com/Zrips/Jobs/commit/f8519abfa161fd06f540ee23c164d517a3606ce3

**Comment by PackCraft** [comment]
Sorry but i'm in 4.13.0 version of jobs reborn but the "melon_block" doesn't work

**Comment by montlikadani** [comment]
@PackCraft Because we not released a new version of Jobs to fix this. You should wait for it or compile the code.

**Comment by mrdollardx44** [comment]
We still need a fix for this problem we've been testing every value that we found on internet but we still have the bug when you break the melon
(server running in 1.12.2 <ith Jobs Reborn 4.17.1)
