### ISSUE TITLE
GlobalBlockTimer cannot be deactivated

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/Jobs#465]
Since version 4.13.0 the GlobalBlockTimer can no longer be turned off. The Config looks like this:
```
    GlobalBlockTimer:
      use: false
      timer: 0
```
Nevertheless the message "You have to wait 60 sec more to get paid for this" is displayed. 

Jobs 4.13.0
Paper 1.13.2 - 633

**Comment by montlikadani** [comment]
GlobalBlockTimer turns off when the option is disabled and the plugin is reloaded. You have a problem that cannot be improved.

**Comment by TheoRetisch1** [comment]
Strange, it's actually not there anymore. I could have sworn that I had the problem after a restart. But it disappeared, so you're right. Thank you for the answer! #closed
