### ISSUE TITLE
Make non-Blocks placable

### ISSUE THREAD

**Issue by NurPech** [Zrips/Jobs#466]
**Description of new idea or improvement on existing one**
Please add the possibility to get paid for placing/breaking blocks like Redstone, Repeater and Comperator.

**Detailed information what should do what and when**
Currently it is not possible that users get paid for placing things like redstone:

[21:17:53 WARN]: [Jobs] Job Redstonetechnican has an invalid Place type property: REDSTONE (REDSTONE)! Material must be a block!
[21:17:53 WARN]: [Jobs] Job Redstonetechnican has an invalid Place type property: REPEATER (REPEATER)! Material must be a block!
[21:17:53 WARN]: [Jobs] Job Redstonetechnican has an invalid Place type property: COMPARATOR (COMPARATOR)! Material must be a block!

**Comment by montlikadani** [comment]
We need more informations about the plugin version & mc version.

Anyway, if the block is invalid, then not possible to get paid for that material.

**Comment by NurPech** [comment]
Im using Jobs 4.13.0 and Spigot 1.12.2

This is the corresponding job-Configuration:
`  Redstonetechnican:
    fullname: Redstonetechniker
    shortname: R
    description: Erhält Geld für/ndas Erbauen/nvonRedstonetechniken
    ChatColour: GOLD
    chat-display: full
    max-level: 200
    #slots: 10
    leveling-progression-equation: 10*(joblevel)+(joblevel*joblevel*4)
    income-progression-equation: baseincome+(baseincome*(joblevel-1)*0.027)-((baseincome+(joblevel-1)*0.032) * ((numjobs-1)*0.05))
    points-progression-equation: basepoints+(basepoints*(joblevel-1)*0.01)-((basepoints+(joblevel-1)*0.01) * ((numjobs-1)*0.05))
    experience-progression-equation: baseexperience+(baseexperience*(joblevel-1)*0.01)-((baseexperience+(joblevel-1)*0.01) * ((numjobs-1)*0.05))
    rejoinCooldown: 10
    Gui:
      Id: 331
      Data: 0
    Place:
      REDSTONE:
        income: 0.1
        experience: 0.05
      REDSTONE_BLOCK:
        income: 0.1
        experience: 0.05
      REDSTONE_TORCH:
        income: 0.3
        experience: 0.15
      REPEATER:
        income: 0.5
        experience: 0.25
      PISTON:
        income: 0.5
        experience: 0.25
      STICKY_PISTON:
        income: 0.5
        experience: 0.25
      NOTE_BLOCK:
        income: 1
        experience: 0.5
      RAIL:
        income: 0.2
        experience: 0.1
      POWERED_RAIL:
        income: 0.2
        experience: 0.1
      DETECTOR_RAIL:
        income: 0.2
        experience: 0.1
      ACTIVATOR_RAIL:
        income: 0.2
        experience: 0.1
      REDSTONE_LAMP:
        income: 0.5
        experience: 0.25
      DROPPER:
        income: 0.5
        experience: 0.25
      DISPENSER:
        income: 0.5
        experience: 0.25
      OBSERVER:
        income: 0.5
        experience: 0.25
      COMPARATOR:
        income: 0.5
        experience: 0.25
      TRIPWIRE_HOOK:
        income: 0.1
        experience: 0.05
      STONE_BUTTON:
        income: 0.1
        experience: 0.05
      WOODEN_BUTTON:
        income: 0.1
        experience: 0.05
      LEVER:
        income: 0.1
        experience: 0.05
      STONE_PRESSURE_PLATE:
        income: 0.2
        experience: 0.1
      WOODEN_PRESSURE_PLATE:
        income: 0.2
        experience: 0.1
      HOPPER:
        income: 1
        experience: 0.5`

**Comment by NurPech** [comment]
Sry, it's my fault.

The nameing of the blocks are redstone_wire, unpowered_repeater and unpowered_comparator. Sry for any inconvience
