### ISSUE TITLE
negative income and job boost

### ISSUE THREAD

**Issue by NurPech** [Zrips/Jobs#467]
***Description of issue:**
I want to reference https://github.com/Zrips/Jobs/issues/60

In my case it is neccessary that some Actions have a negative payout. Let's say a player is enchanting a pickaxe, he should receive always a positive payout. But if he is detroying an enchanting table he has to got some penalty. I've realized this with a negative baseincome for breaking an enchanting table.

If we activated a job boost, to make our players to receive more money for enchanting a pickaxe, we would also have the penalty higher.

Let's say we want to have a boost with a multipler of 2. All positive incomes are really doubled. But the negative incomes are now zero.

This is breaking our whole economy. We need a real multipler as it is descriped in the documentation.
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## PASTE ERROR HERE ##
####################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```
    Break:
      CHEST:
        income: -4
        experience: -2
      TRAPPED_CHEST:
        income: -4
        experience: -2
      WALL_SIGN:
        income: -2
        experience: -1
    Kill:
      Villager:
        income: -20
        experience: -10

  NightBoost:
    Enabled: true
    From: '17:00:00'
    Until: '24:00:00'
    Exp: 2.0
    Money: 2.0

---

**Server Type (Spigot/Paperspigot/etc):** 
Spigot 1.12.2 / 1.14.2
**Server Version (using `/ver`):** 
 This server is running CraftBukkit version git-Spigot-79a30d7-acbc348 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
This server is running CraftBukkit version git-Spigot-df0eb25-efd8a2b (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)
**Relevant plugins (Delete if this isn't needed):**
Jobs Reborn 4.13.0

**Comment by Zrips** [comment]
But isint this is how it should actually work? If its 1 buck for mining a block, then double pay will give you double that. If you have -1 buck for breaking table, then it will go to 0, because that bonus will add 100%, thish zeros out that penalty. We could simply add an option to skip negative incomes and avoid doing anything with them if needed. So people would get 2 bucks for a block with a boost while breaking table would still take away 1 buck.

**Comment by Zrips** [comment]
ebe321fc4215bc6f9aed16b171979ebd0334973a
