### ISSUE TITLE
BoostedItems buggy, enchantments not working

### ISSUE THREAD

**Issue by Faceless0102** [Zrips/Jobs#468]
***Description of issue:**
In the boosteditems config file, the enchantments are not working.
I type the jobs give command correctly, and only gives me a normal diamond pickaxe with name, no enchantments.
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
DallasCsakany:
  id: DIAMOND_PICKAXE
  name: '&dDallas Csákány'
  enchants:
  - DIG_SPEED=5
  - DURABILITY=3
  - LOOT_BONUS_BLOCKS=3
  moneyBoost: 1.2
  expBoost: 1.0
  pointsBoost: 1.0
  jobs:
  - Bányász
```

**Server Type (Spigot/Paperspigot/etc):** 
TacoSpigot, also tried PaperSpigot...

**Server Version (using `/ver`):** 
This server is running CraftBukkit version git-TacoSpigot-"95870a93" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

**Comment by montlikadani** [comment]
Could you please take a screenshot about the problem?

**Comment by Faceless0102** [comment]
It gives me a normal diamond pickaxe with the name, that's it. No error in console or anything like that.

**Comment by montlikadani** [comment]
Then please send a boostedItems file.

**Comment by Faceless0102** [comment]
https://pastebin.com/UwhrdQ2U

**Comment by montlikadani** [comment]
Make sure you have reseted the TranslatableWords file. (Delete all files and generate new when server start)

**Comment by Faceless0102** [comment]
![image](https://user-images.githubusercontent.com/41546701/60511452-4cf99100-9cd2-11e9-8e85-68a42d1f83d0.png)
Still gives me a normal named axe without enchantments...

**Comment by Faceless0102** [comment]
with /jobs give command

**Comment by montlikadani** [comment]
Try with specify only one enchantment name in the "Harris Balta" item.

**Comment by Faceless0102** [comment]
Okay, I will try Durability

**Comment by Faceless0102** [comment]
The result is the same.
Here is the config:
https://pastebin.com/Mk5gfu3g
I also tried with durability 3, none of the named items (or even normal ones) want to work.

**Comment by montlikadani** [comment]
For me works correctly. Try the Jobs plugin on a test server on 1.9 or higher version.

**Comment by Faceless0102** [comment]
Why do I need to use 1.9?

**Comment by montlikadani** [comment]
Because it has a lot of fixes and improvements more than 1.8.

**Comment by Faceless0102** [comment]
Ok. I make a 1.12.2 server with viarewind

**Comment by Faceless0102** [comment]
![image](https://user-images.githubusercontent.com/41546701/60512431-d1e5aa00-9cd4-11e9-8a3b-808d88480c83.png)
Now the plugin is not even working

**Comment by montlikadani** [comment]
Because you not changed the server jar fully, just installed ViaRewind. To work you should change the server jar to higher version.

**Comment by Faceless0102** [comment]
![image](https://user-images.githubusercontent.com/41546701/60512543-183b0900-9cd5-11e9-8e12-dc55f5555adc.png)
:D

**Comment by Faceless0102** [comment]
got it fixed by updating worldguard but the issue is the same
![image](https://user-images.githubusercontent.com/41546701/60512722-a9aa7b00-9cd5-11e9-9079-88db3696e751.png)

**Comment by Faceless0102** [comment]
no ideas?

**Comment by Faceless0102** [comment]
:/

**Comment by Faceless0102** [comment]
I want to use this plugin...

**Comment by Faceless0102** [comment]
wow

**Comment by Faceless0102** [comment]
is this fixed in the latest update?

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/d62349badc46dc884d1b061b39e7ab851c08dbe1
