### ISSUE TITLE
Sum up the boost permissions if a players have multiple boosts

### ISSUE THREAD

**Issue by Daxxas** [Zrips/Jobs#469]
**Description of new idea or improvement on existing one**

Actually when a player has jobs.boost.all.all.0.5 for example, he will have a 50% boost on his jobs, but if he has jobs.boost.all.all.0.5 and jobs.boost.all.all.0.2 at the same time, the biggest permission will be the boost. it would be cool to sum up the boosts of a player if he has more than one.

**Detailed information what should do what and when**
If a player have jobs.boost.all.all.0.25 and jobs.boost.all.all.0.4, instead of having a 40% boost, he would have a 65% boost

**Comment by ArathiaMC** [comment]
I disagree with this unless an option to use the current system is implemented too.

**Comment by Seeroh** [comment]
This could conceivably be done by using an additional bonus, I'd think.

It might be a little messy, but could add additional nodes that can stack, like `jobs.boost.[jobname].all.[amount]`, `jobs.boost2.[jobname].all.[amount]`, `jobs.boost3.[jobname].all.[amount]` etc. But that's kind of ugly. There's likely a better way to do it, but I'd love to see this, myself.

**Comment by Seeroh** [comment]
I'm not sure this works. I have a fresh install of 4.17.2 installed, using Paper-288 (MC: 1.16.4), and using LuckPerms for permissions.

I set two permissions:
![image](https://user-images.githubusercontent.com/9147655/121509303-5e0dab00-c99b-11eb-8fa9-2867f595c563.png)

This is the output of /jobs bonus [Job]
![image](https://user-images.githubusercontent.com/9147655/121509385-6fef4e00-c99b-11eb-85ee-55dc7ec01bae.png)
