### ISSUE TITLE
Enchantments jobs shop

### ISSUE THREAD

**Issue by TwerkRekt** [Zrips/Jobs#471]
Hi with Jobs Reborn 4.13.0 enchantments dont work in jobs shop (work with 4.12.0)
And wither skeleton dont work in 1.12.2
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
No error
```

```
Config:
https://pastebin.com/APpF5MUp
```

---

**Server Type (Spigot/Paperspigot/etc):** 1.12.2 spigot

**Server Version (using `/ver`):**  1.12.2

**Comment by montlikadani** [comment]
Same as https://github.com/Zrips/Jobs/issues/468

**Comment by montlikadani** [comment]
Could you please take a screenshot about the problem?
