### ISSUE TITLE
Regular Break Event for mining not working.

### ISSUE THREAD

**Issue by Dracathio** [Zrips/Jobs#472]
Alright... so I haven't a clue as to why this isn't working.
It would work maybe for a short time, like 1 or 2 blocks.  mainly just a single block. Then it would just stop.

The entire config shows that everything is apparently working, no errors or warns for mining at all.
TNT break works fine even with using mcmmo blast mining.
Crafting works fine when making pickaxes.
It's just the default break event that's causing me so many issues.
Is there for some reason a limit to how many blocks we can have in this section?
Because I added several blocks to it, such as infested blocks and other blocks you find in jungle temples and strong holds, as well as glowstone and sea lanterns.

The /jobs browse lists every single block I've added to break action as well.
---

**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
git-Paper-597 (MC: 1.13.2)
(API version 1.13.2-R0.1-SNAPSHOT)
**Relevant plugins (Delete if this isn't needed):**
4.13.0 Jobs Reborn.

**Comment by montlikadani** [comment]
We need the jobConfig configuration to see what to do.

_Anyway, what is infested blocks?_

**Comment by Dracathio** [comment]
just a bad setting because I read a comment wrong...
