### ISSUE TITLE
Melon blocks not recognized

### ISSUE THREAD

**Issue by PengBread** [Zrips/Jobs#473]
***Description of issue:**

--- My server is using jobs 4.13.0 [ the latest version ]. In the updates it says melon_block should be fixed but its not. Breaking melon blocks doesn't give my players income.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
      melon_block:
        income: 0.11
        points: 0
        experience: 0.08

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Server Version (using `/ver`):** 
git-Paper-404 (MC: 1.13.2)

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/issues/464

**Comment by PengBread** [comment]
Is that a version that's not been released yet or is it released somewhere?

**Comment by montlikadani** [comment]
It's not released, but if we release a new version then hopefully fix this problem.
