### ISSUE TITLE
Archived Job levels vanish when switching between servers

### ISSUE THREAD

**Issue by Flexxxxx** [Zrips/Jobs#475]
***Description of issue:**
Archived job levels disappear whenever any player switches between any server within our Bungeecord network. The issue began after we enabled jobs to work in sync on two of our servers within our network. There are no visible errors in console when this happens. We're currently running Jobs v4.13.0.

**Server Type (Spigot/Paperspigot/etc):**  git-paper-121

**Server Version (using `/ver`):** 1.14.3

**Relevant plugins (Delete if this isn't needed):** Jobs, Bungeecord (if you consider that a plugin)

**Comment by montlikadani** [comment]
Is the `MultiServerCompatability` is enabled in generalConfig file?

**Comment by Flexxxxx** [comment]
Yes it is enabled.

**Comment by LightningDesign** [comment]
This big is still not fixed yet on version 4.14 ... 
if i leave a job with level 10 on Server A and connect to Server B, join same Job as before, now i have LvL1

**Comment by Flexxxxx** [comment]
+1 this has started to reoccur recently for our players too.

**Comment by montlikadani** [comment]
@LightningDesign, @Flexxxxx Install the dev version from releases tab.

**Comment by LightningDesign** [comment]
@montlikadani Already done, but still dont work. Should i delete the configs too ?

**Comment by nokisenpai** [comment]
Hello ! I tried your 4.14.0 version and this still doesn't work. It seems the plugin doesn't load archived jobs.

**Comment by LightningDesign** [comment]
@montlikadani how is the fix status for the Level los bug on server switch ?
we need this urgently :(

**Comment by montlikadani** [comment]
Feel free to open a pull request to fix and help to improve this.

**Comment by Flexxxxx** [comment]
Are there any updates on the progress of this?

**Comment by nokisenpai** [comment]
I searched in the code. That's too hard for me. Sorry =/
It seems you never load "per player archived jobs". I saw a global load of archived jobs when the plugin start but I don't know how you "match" player with his archived jobs. I hope you fix this easily =/

**Comment by BlueSoapTurtle** [comment]
@montlikadani perhaps an alternate way of syncing job levels per server would be a better option? Like using redis to sync it, saving when the player disconnects and loading when he connects isn't very reliable.

**Comment by montlikadani** [comment]
Feel free to open a pull request to fix and help to improve this.

**Comment by montlikadani** [comment]
Is this still happens in the latest version?
