### ISSUE TITLE
Builider job bug

### ISSUE THREAD

**Issue by Aides123** [Zrips/Jobs#476]
***Description of issue:**
Hi! I found bugs with job Builider.
When a player who is at work Builder
clicking meat, for example a block of diamond, gets money for placing
Video:
https://www.youtube.com/watch?v=CnbGwFUR0wc&feature=youtu.be

**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot 1.14.3

**Server Version (using `/ver`):**
revious version: git-Paper-111 (MC: 1.14.3)

**Comment by montlikadani** [comment]
That's why you get income because prismarine_bricks is added to the job, and if you are breaking the block in creative mode, you get money. So that's not a mistake.

**Comment by Aides123** [comment]
> That's why you get income because prismarine_bricks is added to the job, and if you are breaking the block in creative mode, you get money. So that's not a mistake.

Normal player on survival mode has discovered ...

**Comment by montlikadani** [comment]
Because the player broken that block and get paid.

**Comment by Aides123** [comment]
When a player clicks on meat, he get money from placing blocks

**Comment by Aides123** [comment]
When a player clicks on meat, he get money from placing blocks
lmao check 00-0.7 sec

**Comment by Aides123** [comment]
@montlikadani

**Comment by montlikadani** [comment]
yes, because that block has placed

**Comment by Aides123** [comment]
Okey so does block of diamond make an infinity of money?

**Comment by Aides123** [comment]
The player puts one block of diamond and clicks on the object and then gets money for each time

**Comment by montlikadani** [comment]
Wut? If a player breaks a block and is listed in that list, gets paid based on the values given.

**Comment by Aides123** [comment]
But he does not get the money for destruction just for clicking on it with an object

**Comment by Aides123** [comment]
0-7s in video u can see
Player get money for clicking a block

**Comment by Aides123** [comment]
I can make long video if u want

**Comment by montlikadani** [comment]
> 
> 
> But he does not get the money for destruction just for clicking on it with an object



> 
> 
> 0-7s in video u can see
> Player get money for clicking a block

Then WHat? Player get money or not?

**Comment by Aides123** [comment]
The player receives money not for destroying or putting a block

**Comment by Aides123** [comment]
only for clicking on an object on the block

**Comment by Aides123** [comment]
in this way he can get an infinite number of money

**Comment by montlikadani** [comment]
You can make a more detailed new video about the problem

**Comment by Aides123** [comment]
https://youtu.be/aE1HwL-8W7Y

**Comment by montlikadani** [comment]
Based on the test results the player does not get money for clicking diamond block.
What Jobs version are you using (number)?

**Comment by Aides123** [comment]
latest

**Comment by montlikadani** [comment]
But the version number.

**Comment by Aides123** [comment]
4.13.0

**Comment by montlikadani** [comment]
**Make sure** that a plugin on your server does not make payments with Jobs.

**Comment by Zrips** [comment]
Payment actions are done for specific actions. Block break only triggers when you actually break a block. Same goes with place. Right-clicking something in your hand will not trigger that event. So you have some broken plugin interfering with jobs work.
