### ISSUE TITLE
Players won't earn experience

### ISSUE THREAD

**Issue by Estarqui** [Zrips/Jobs#478]
**Description of issue:** After many tries and many configuration tweaks, my players can't get experience from their Jobs.
I tried the plugin without any changes on the General Config file but still can't get any experience.
Any ideas on how to solve this? Maybe i'm doing something wrong... I've tried everything i know.

---
**Config section:** https://pastebin.com/4vvBGF9L

**Permissions given to my players:**
- jobs.command.brose
- jobs.command.help
- jobs.command.info
- jobs.command.join
- jobs.command.leave
- jobs.command.leaveall
- jobs.command.stats
- jobs.command.top
- jobs.join.minero
- jobs.use
---

**Server Type:** Spigot

**Server Version:** git-Spigot-d05d3c1-a2275f1 (MC: 1.14.3) 

**Relevant plugins:** AuthMe, Citizens, CoreProtect, Essentials, Holograms, KarenProtect, LuckPerms, Multiverse.Core, MySkin, PaperMoney, PlugMan, PvPToggle, Quests, RestrictedCreative, Shopkeepers, SimplePortals, TAB, TradeSystem, WorldBorder, WorldEdit, WorldGuard

**Comment by montlikadani** [comment]
Add this permission `jobs.world.[worldName]` to group.

**Comment by Estarqui** [comment]
No... I'll try adding that permissions node and letting you know if it's fixed :)

**Comment by Estarqui** [comment]
No wait... I just remembered, I can't get XP myself and I'm supposed to have every single permissions.

**Comment by Estarqui** [comment]
I still have the issue after adding jobs.world.world

**Comment by montlikadani** [comment]
So only you not get xp income for doing actions?
