### ISSUE TITLE
Players can't leave jobs (sporadic issue)

### ISSUE THREAD

**Issue by skulltraill** [Zrips/Jobs#48]
One of my players, who has joined the fisherman job, says he can't leave the job because it says he isn't in the job.

However, his Chat title still has Fr in it, and he can't join another job because it says he has 3.

However, when he tries to quit, or when I try to fire him with admin perms, it just says "Player does not have the job Fisherman." But he clearly does.

**Comment by skulltraill** [comment]
This is really becoming quite an issue. I'll post on the thread too.

**Comment by Zrips** [comment]
Should be fixed in latest builds
