### ISSUE TITLE
SWEET_BERRY_BUSH growing Status is missing

### ISSUE THREAD

**Issue by Sulort** [Zrips/Jobs#483]
***Description of issue:**

---
Its not possible to set the growing status for the sweet_berry_bush in the jobconfig.yml
e.g. SWEET_BEERY_BUSH-4
Could you pls. fix it. Thanks a lot.
---

**Server Type (Spigot):** 

**Server Version (1.14.3):**

**Comment by montlikadani** [comment]
With `SWEET_BERRY_BUSH` material has no official ID released and we could not fix it.
See this page to make sure: https://minecraft.gamepedia.com/Sweet_Berry_Bush

**Comment by Sulort** [comment]
ok, thanks
