### ISSUE TITLE
Getting Money by farming sweet berries

### ISSUE THREAD

**Issue by Sulort** [Zrips/Jobs#484]
**Description of new idea or improvement on existing one**

is it possible to add a new feature (like the break or place function) for earning money if you are farming the sweet berry bush by right clicking on the bush.

**Detailed information what should do what and when**

**Comment by Sulort** [comment]
first of all: thanks a lot for your fast and perfect job. 
could you pls add in the language file for the new type "collect" the message like this:
      collect:
        info: '&eCollect'
        none: '%jobname% does not get money for collecting blocks.'

and also pls implement the sweet_berry_bush-3 into the translatable words file. at the moment its not recognizing the growing state, so i cant use another language. 

thanks a lot

**Comment by montlikadani** [comment]
> first of all: thanks a lot for your fast and perfect job.

Thanks!

> could you pls add in the language file for the new type "collect" the message like this:
> collect:
> info: '&eCollect'
> none: '%jobname% does not get money for collecting blocks.'

Oh, I forgot to add this. Thank you!

> and also pls implement the sweet_berry_bush-3 into the translatable words file. at the moment its not recognizing the growing state, so i cant use another language.

No, I don't implement this material, because the plugin will automatically implement the materials to the file **if has official ID**. If a material has no ID, then not generates it, for saving memory.
