### ISSUE TITLE
EntityList in words_xx.yml

### ISSUE THREAD

**Issue by Sulort** [Zrips/Jobs#486]
**Detailed information what should do what and when**

The EntityList contain several new 1.14. mobs with the same id 916
Could you pls. give them an unique id. thx a lot
  
  916-PANDA: Panda
  916-PILLAGER: Pillager
  916-RAVAGER: Ravager
  916-TRADER_LLAMA: Trader Llama
  916-WANDERING_TRADER: Wandering Trader
  916-FOX: Fox

**Comment by montlikadani** [comment]
Added, https://github.com/Zrips/Jobs/commit/01898220ccbcc891ea3b17a3028a51cf8859dfe1
Some entities such as `TRADER_LLAMA` and `WANDERING_TRADER` has no Internal ID released.
