### ISSUE TITLE
Earning issue with sweetberries

### ISSUE THREAD

**Issue by Sulort** [Zrips/Jobs#487]
***Description of issue:**

A player could earn money by collecting sweetberries (rightclick), if he has the job farmer. so far so good. but the player will also get money, even if he is not a member of a worldguard region or a plotworld region. It only works if the player has the farmer job. Could you pls. fix this issue. 
---

**Server Type (Spigot/Paperspigot/etc):** 
paperspigot
**Server Version (using `/ver`):** 
1.14.4

**Comment by montlikadani** [comment]
wat? Can you describe it more clearly?

**Comment by Sulort** [comment]
ok, so a player has the farmer job and is the owner of a worldguardregion. now the player collecting sweetberries from a sweetberrybush in his region. now he will earn money. so far so good. 
now another player, who is not a member of this region, will also earn money by collecting sweetberries from the same sweetberrybush. and this is the problem. the other player shouldn't earn money. maybe you can test it on a testserver

**Comment by montlikadani** [comment]
Get paid for not blocking the ability to **collect or interact** in the worldguard flag.

**Comment by Sulort** [comment]
the worldguard flag for interacting is diasabled per default, so that couldn't be the problem

**Comment by Sulort** [comment]
fell free to join our server, and also to our discord for solving the problem. could i send you the ip per discord?

**Comment by Sulort** [comment]
hi, i checked the source code of worldguard, and there is already implementet the sweetberrybush for the interact flag. and its also working for a worldguardregion if a nonmember player would rightclick on a sweetberrybush. he wont get any berries. so its not a flag problem! but as a farmer he will get money. so its a job problem. could you pls. check it
