### ISSUE TITLE
Placeholders

### ISSUE THREAD

**Issue by ronc617** [Zrips/Jobs#488]
This server is running CraftBukkit version git-Spigot-1981d55-3e7b386 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

if i run /jobs placeholders it shows here fine but if i try to use the placeholder in a menu it just displays the placeholder and not the data. any idea?
https://cdn.discordapp.com/attachments/526402919826849804/604522494216634391/unknown.png
https://cdn.discordapp.com/attachments/526402919826849804/604522512679829514/unknown.png
Other placeholders im using seem to work fine
https://cdn.discordapp.com/attachments/526402919826849804/604522838426386432/unknown.png

**Comment by montlikadani** [comment]
And anywhere where you want to use the placeholder?

**Comment by ronc617** [comment]
Was just trying to display that place holder like I have with a few others
in a menu but that one doesn’t seem to populate the information like the
others do

**Comment by montlikadani** [comment]
You should install the PlaceholderAPI and installing the jobs extension to work. And you should read the plugin usage on main page to know how to work.

**Comment by ronc617** [comment]
I have the placeholdersapi installed with the jobs extension. I can make
sure the extension is updated. Was just trying to figure out why I got the
others to display correctly but not that one.

**Comment by montlikadani** [comment]
Make sure that gui plugin or what you using plugin where the placeholder not work are compatible with placeholderapi.

**Comment by ronc617** [comment]
The other place holders are working which I should have attached the screen
shot as well that’s why I was confused as to why the user points wasn’t
displaying

**Comment by montlikadani** [comment]
Ok, but which plugin do you use where the points not show?

**Comment by ronc617** [comment]
MyCommand in a menu

**Comment by montlikadani** [comment]
Try to install dev release from https://github.com/Zrips/Jobs/releases

**Comment by ronc617** [comment]
Installed that last night still seemed to handle about the same

**Comment by Zrips** [comment]
9efaa425f2a6167b14ad732d5eb20e7dbeae2870
