### ISSUE TITLE
Permission Bonus are not applying on 3.6.2

### ISSUE THREAD

**Issue by MonoLime** [Zrips/Jobs#49]
Permission Bonuses granted with the jobs.boost.xxx.xxx permission does not grant the bonuses. In previous version, 3.5.6 it works though.

**Comment by sumdream** [comment]
the same to me,could u fix it?

**Comment by joblo2213** [comment]
This seems to be a issue with **all boosts**!
I had the problem that the restricted areas where loaded, but the multipliers weren't applied.
So I got the source-code and had a look on it with ecllipse. 
I couldn't get out what exactly is the problem, but I think it has something todo with the way the plugin is calculating the boosts and rewards.

**Comment by Zrips** [comment]
Should be fixed with latest builds
