### ISSUE TITLE
Jobs demote does not remove the correct levels

### ISSUE THREAD

**Issue by Flexxxxx** [Zrips/Jobs#490]
***Description of issue:** /jobs demote does not remove the specified levels. You could literally type /jobs demote miner 100009929416427 and it'll only do 10 levels. This issue has been around for YEARS, through every Jobs version dating back to 2017 (when I first started using the demote command) but never been fixed so I figure it's due time to actually report it.

Live example:
https://gyazo.com/1de4b3edc210ca85971613fcd551ad34

---

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):** 1.14.4 (running git-paper-6fad1adc)

**Comment by montlikadani** [comment]
Because you have exceeded the level that Blacksmith is working on at level 60, you cannot write the level minus because there is no level in Jobs, so you need to enter the level amount that is currently in Blacksmith 60th.

**Comment by Flexxxxx** [comment]
An new alternative command that sets a job level, without the need to use promote/demote would be nice or a useful workaround if it's simple to implement. e.g. /jobs set name miner 1 (would set the players Miner level as 1).

**Comment by montlikadani** [comment]
Seems this works in the latest version.
