### ISSUE TITLE
Slow restarts due to Jobs block protection entry

### ISSUE THREAD

**Issue by ArathiaMC** [Zrips/Jobs#492]
Every time I do reboots it always takes almost an hour due to the block protection entries being cleared via the Jobs plugin. This should be sped up or fixed.

---

>.... [10:05:08 INFO]: [Jobs] Removed 30000 old block protection entries.
>.... [10:12:21 INFO]: [Jobs] Removed 40000 old block protection entries.
>.... [10:19:33 INFO]: [Jobs] Removed 50000 old block protection entries.

*** It continues for a while, you get the idea.

---

PaperSpigot 1.14.4 build 154

**Comment by montlikadani** [comment]
This can be closed due to duplicate.
https://github.com/Zrips/Jobs/issues/441
