### ISSUE TITLE
Further settings for players getting paid while using hoppers

### ISSUE THREAD

**Issue by kaniesha** [Zrips/Jobs#493]
**Description of new idea or improvement on existing one**
Currently there is a true/false setting to allow players to continue to use hoppers when smelting or brewing but they don't get paid when any/all items enter the furnaces or brewing stands with hoppers. 

Could there be additional settings that allow players to get paid when certain items are used in the hoppers? For example, I want brewers to still be paid when using hoppers to place water bottles in brewing stands.

**Detailed information what should do what and when**
Smelting gets paid for auto placing fuel (charcoal, coal, lava buckets, etc) with hoppers: true/false
Brewing gets paid for auto placing fuel with hoppers: true/false
Brewing gets paid for placing water bottles with hoppers: true/false

**Comment by montlikadani** [comment]
We will not add it because it will again be a money dupping, which will mean money for the players. https://github.com/Zrips/Jobs/issues/388 For this issue, it has been reported that when using this mode money dupping comes in so a lot of money accumulates at a player.
