### ISSUE TITLE
One Time Only Quests

### ISSUE THREAD

**Issue by UnioDex** [Zrips/Jobs#494]
**Description of new idea or improvement on existing one**
Quests that each player can finish only once. These quests won't reset everyday and rewards will be better. 

**Detailed information what should do what and when**
Quitting jobs will not reset these quests (although it can be configurable)

**Comment by montlikadani** [comment]
This absolutely makes no sense, because quests are in jobs, so the players should join to a job to get that quests. Making that quests separated from jobs, it just memory leak, and also thats not worker-things.
