### ISSUE TITLE
display error

### ISSUE THREAD

**Issue by J3fftw1** [Zrips/Jobs#495]
if you add the new mobs to the hunter config for example a fox it shows up as panda.
I think it has to do becasue the mobs are listed as the same number (916)
as seen as below
https://prnt.sc/oo774x
https://prnt.sc/oo77j8
---

**Server Type Spigot:**  

**Server Version (1,14,4):** 

edit: sorry for the text being in full bold

**Comment by montlikadani** [comment]
Already added: https://github.com/Zrips/Jobs/commit/01898220ccbcc891ea3b17a3028a51cf8859dfe1
Install the dev version from releases tab.
Next time follow the commits.
