### ISSUE TITLE
Quest objectives with multiple materials

### ISSUE THREAD

**Issue by UnioDex** [Zrips/Jobs#496]
**Description of new idea or improvement on existing one**
I want to make a quest for Builder job that place 10000 blocks. It doesn't matter which block type player placed. But right now it's not possible (or i don't know how to do).

**Detailed information what should do what and when**
Configuration example:
Place any block:
`- Place;*;10000`
Place 10000 glass or stained glass.
`- Place;glass,stained_glass;10000`

**Comment by montlikadani** [comment]
You should specify the materials in per-lines.
Example:
```
Objectives:
- Break;17-0;300
- Break;spruce_door;5
- Place;oak_door;1
```
and so on..
If you don't know how to do, then learn the YAML usage.

**Comment by UnioDex** [comment]
@montlikadani that's not really what I wanted. If I do that players must place 5 spruce_door and 1 oak door. But I want players to place any blocks in the list no matter how much they placed. For this example:
`- Place;glass,stained_glass;10000`

- Players can place 5000 glass and 5000 stained glass
- Players can place 10000 glass and 0 stained glass.
- Players can place 10000 stained glass and 0 stained glass.
And goes on.

It's simply, place 10000 blocks but it doesn't matter how much you placed a specific block.

**Comment by montlikadani** [comment]
If you want to put each block in an action with an "*" mark, then server console spam is expected, so the server will shut down because there may be missing data on materials that Mojang has not released.
And if you want the player to get a reward even if they don't reach 10000? It is not possible that if that were the case, Quest would make no sense.

**Comment by UnioDex** [comment]
I think we are having a communication problem because what I want is very simple and almost every quest plugin (even vanilla Minecraft advancements) has that.

I simply want a player to place 10000 block and it doesn't matter what block it is. I only want to reward the placing process. Not the block that placed.

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/09fe31dba179287e9edd0d11ba1c7375e6bfcb4b

We will not implement this for "*" because Minecraft contains a lot of material, so adding it to a list also affects memory leaks and server performance.
