### ISSUE TITLE
 Override Vault Economy

### ISSUE THREAD

**Issue by Pyario** [Zrips/Jobs#498]
Hey, would it be possible to override the default economy?

OverrideEconomy: true/false
AddMoneyCommand: coins give %player% %amount%
RemoveMoney: coins take %player% %amount%

Description:

If in the config, the override economy is true, and then what in the job degrades, the money is executed via these commands, because unfortunately I do not know in the Payment Api how to connect to the own economy system. :) If there is a possibility, I would like to know, if this is not possible, it would be nice to do as described above. :)

Best Regards, 

Pyario

**Comment by montlikadani** [comment]
Nop, use the [JobsPrePaymentEvent](https://github.com/Zrips/Jobs/wiki/API#jobsprepaymentevent) to cancel the reward, and overriding to your economy system.

**Comment by Pyario** [comment]
Thanks for the answer. Can you give me an example of how exactly I can do that?

**Comment by montlikadani** [comment]
@Pyario Open again that tab, which I posted above ^
If you don't know how to code a plugin, I think learn first the Bukkit usage. And actually, we not creating an option to overwrite the economy command, because we using the VaultAPI, that has custom methods to pay.

**Comment by Pyario** [comment]
@montlikadani 

I know how to program plugins, but each Api is numbered differently, and I do not quite look at it, please do not misunderstand it, but everyone is different. Then I have to see how it works. Thanks anyway for the answer.
