### ISSUE TITLE
is MMkill still working on Jobs4.13.0?

### ISSUE THREAD

**Issue by Cheubajjang** [Zrips/Jobs#499]
Hello, is MMkill still support on Jobs4.13.0?
I put CustomName Correctly but Not Working.
        Objectives:
        - MMKill;goblin;10

Server Type: Spigot
Server Version: 1.13.2
Relevant plugins: Jobs4.13.0, Mythicmobs4.6.5(Premium)

**Comment by UnioDex** [comment]
I tried Jobs 4.13.1 with MythicMobs 4.6.5 (Free) and it's working.
