### ISSUE TITLE
Job-Cooldown Problem

### ISSUE THREAD

**Issue by Sulort** [Zrips/Jobs#503]
**Description of new idea or improvement on existing one**

In the JobsConfig.yml you can add a cooldown for rejoining the job. Works perfectly until a player is rejoining the server. so the time of the cooldown, lets say 7 days, was not saved in the mysql database. (we are using mysql)

Could you pls save the value of the cooldown in the mysql database, so that we can use the 
cooldown-functionality. Thx a lot.

**Comment by montlikadani** [comment]
Why not saved? For me its saved: 
![kép](https://user-images.githubusercontent.com/30026208/63226756-7026c400-c1de-11e9-9f87-373e361f6c21.png)

Jobs data will be saved when plugin has been stopped or during server restart.

**Comment by Sulort** [comment]
that might be correct. but my problem is, if a player is rejoining the server the time of the cooldown is set to 0. so the player could join again the job. pls check this behaviour on a test server, or contact me via discord. thanks.

**Comment by Sulort** [comment]
i found the problem. when you are setting in the generalconfig.yml the parameter
MultiServerCompatability: true
then it is not working. it works only with MultiServerCompatability: false
maybe you can check it, thx

**Comment by montlikadani** [comment]
It's free to open a Pull Request and implement this.

**Comment by montlikadani** [comment]
I just tested it and it seems to work properly, it is set to MultiserverCompatibility false or true. I don't think you are using the latest version.

**Comment by Sulort** [comment]
jep, i tested it with the new version 1.13.1 and it works. :-)
thanks a lot for your quick support.
