### ISSUE TITLE
Jobs MySQL database errors

### ISSUE THREAD

**Issue by rikyriky232** [Zrips/Jobs#506]
***Description of issue:**
We are currently experiencing lag spikes whenever a sql error pops up in console and we have no idea why it happens. We only updated our plugin to the latest version without any changes in configurations

```
https://pastebin.com/bb0sujrx
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Server Type (Spigot/Paperspigot/etc):**  paperspigot 1.13.2

**Server Version (using `/ver`):**  1.13.2

**Comment by Zrips** [comment]
8e7a959f39733828f9564ccd9a4fc3f6ae5aeebf
