### ISSUE TITLE
Hello! I need help! When my players open up Jobs:Jobs Browse (The jobs GUI) they cant join the job they want! How do i allow them to join the job they want?

### ISSUE THREAD

**Issue by StormyBlueyss** [Zrips/Jobs#508]
***Description of issue:**
Hello! I need help! When my players open up Jobs:Jobs Browse (The jobs GUI) they cant join the job they want! How do i allow them to join the job they want? In the gui people can get into the GUI of the Jobs however they cannot join it. They can get into the jobs however they cannot join anything in the GUI. Any ideas?, ive tried everything!
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
20.08 14:35:35 [Server] Server thread/INFO CONSOLE issued server command: /sudo Stormy_Bluey jobs:jobs browse Stormy_Bluey
20.08 14:35:35 [Server] Server thread/INFO Forcing Stormy_Bluey to run: /jobs:jobs browse Stormy_Bluey
20.08 14:35:35 [Server] Server thread/INFO Stormy_Bluey issued server command: /jobs:jobs browse Stormy_Bluey
20.08 14:35:38 [Server] Craft Scheduler Thread - 14/INFO Fetching all due players...
20.08 14:35:38 [Server] Craft Scheduler Thread - 14/INFO Fetched due players (0 found).
#####################################
```

---

Server Type - Spigot

Server Version - 1.14.4

**Comment by montlikadani** [comment]
You not read everything on the wiki page to understand. Just specify `jobs.use`, `jobs.world.yourworld` and `jobs.join.jobName` permissions to your permission system plugin.

**Comment by StormyBlueyss** [comment]
![Here](https://user-images.githubusercontent.com/53452237/63374866-b3a53d80-c358-11e9-8e3a-6daf210d8a02.JPG)
I added all the commands to my permissions plugin to the General/Default groups. Nothing pops up in the console other then the Browse command. No one can join the jobs not even the mods or OP'S.

**Comment by montlikadani** [comment]
What message get the players when tries to join a job?

**Comment by StormyBlueyss** [comment]
Through the GUI nothing. Like this

20.08 14:46:22 [Server] Server thread/INFO CONSOLE issued server command: /sudo Yuxie jobs:jobs browse Yuxie
20.08 14:46:22 [Server] Server thread/INFO Forcing Yuxie to run: /jobs:jobs browse Yuxie
20.08 14:46:22 [Server] Server thread/INFO Yuxie issued server command: /jobs:jobs browse Yuxie

After that when the player closes the Browse nothing pops up also. No-one can join a job through the GUI.

**Comment by montlikadani** [comment]
Yes, because you using the sudo command which forcing you to execute that command, that prevents joining a job and using the `/jobs:jobs` format which causing the problem. Simply just use the `/jobs browse`.

**Comment by StormyBlueyss** [comment]
Alright so i tried that now re-doing a few commands now the GUI does pop up as a normal command through the player as if they where typing it when clicking a NPC. When they get on the GUI still nothing pops up however when they join a job, they just cant join a job through the GUI. However joining a job in command format such as for example ./jobs:jobs join Brewer it allows the player to join thats it however. Sadly. Through the GUI spificaly they cant join

**Comment by montlikadani** [comment]
Why not join to jobs via GUI? Every user knows, only you have confused permission in LuckPerms that the plugin is confused so they cannot join. So give only the permission I have described above and remove the all other jobs permission. Otherwise, what I said in the `/jobs:jobs` format is incorrect and nobody uses it.
