### ISSUE TITLE
Issue with Quests (Custom Item)

### ISSUE THREAD

**Issue by ElKirioso** [Zrips/Jobs#509]
Hello,

I have a little issue with the Quest of the plugin Jobs. 

I'm gonna explain my problem. 
In fact, I wanna do my daily quest with the following objective : Breaking a 43:10 block finishes the quest. 
Here's the code I put : - Break;stone_slab-10;1

I tried different things : - Break;jungle_slab:10;1
                                      - Break;jungle_slab-10;1
                                      - Break;stone_slab:10;1
                                      - Break;43:10;1
                                      - Break;43-10;1

But nothing works...

Could you please help me ? Thanks !

Have a great day !

**Comment by montlikadani** [comment]
More info about the plugin? Version, configuration?

**Comment by ElKirioso** [comment]
Hello, 

I'm using the last version, I changed nothing about configuration just changed some stuff here : https://pastebin.com/X9T2bBHx

No console error, sadly... Thanks !

**Comment by montlikadani** [comment]
Yes, because this material `stone_slab-10` is not correct. Just use stone_slab and nothing.

`materialName-number` - number is displaying the id of an material, such as wool

**Comment by ElKirioso** [comment]
Then I can't display my item ? Or there is another way to do that ?

**Comment by montlikadani** [comment]
WUT? Its displaying...

**Comment by ElKirioso** [comment]
Well I use 43:10, so you can see here that the max id can be 7 and I use 10 for my custom item, so I think that's why it doesn't work for Minecraft. https://image.noelshack.com/fichiers/2019/34/2/1566328896-stairs.png

**Comment by montlikadani** [comment]
Well, double_slab doesn't have the correct name yet, because the problem is that it has the same Id as the stone, so Mojang didn't give it correctly, so we can't do what.

**Comment by ElKirioso** [comment]
Oh ok, so it's not Jobs problem, my bad then.
Sorry!

**Comment by Zrips** [comment]
Double stone slab doesn't exist as a thing, any slab placed on each other will convert that block into regular equivalent block, like 2 stone slabs will be converted into stone block. So there is no way for us to know if it was a slab when breaking it.
