### ISSUE TITLE
Boost permissions not working at all...

### ISSUE THREAD

**Issue by RasmonT** [Zrips/Jobs#510]
**Jobs boots permissions seems not working**

Hello,

I have 4 groups with different boost permission, but even the player (default) has same payout that person with permission - jobs.boost.all.all.2 (tested by myself, when i changed group from player to the different group payout from stone and exp rate was exactly same..) Every other permission seems working (Like negating the job for certain group like - -jobs.join.woodcutter for example) but cannot figure out why the boost does not seem work at all.

Server version: Spigot 1.13.2
Jobs version: 4.13.1

**Comment by montlikadani** [comment]
Why not work? It's work properly... Just you have missed the boost permission from you group. Any screenshot about the permissions?

**Comment by RasmonT** [comment]
![PERMS](https://user-images.githubusercontent.com/35234558/63418222-03d8da00-c403-11e9-9f3e-d17f03d1a18c.png)
This is the 4th group with the permission all.2 and there is same payout from the First group where there is no boost permission for default group.

**Comment by RasmonT** [comment]
After few tests i managed to fix that.. (Tested several times at the moment.) 

Closing this issue.
