### ISSUE TITLE
Bungee Network Database Issue

### ISSUE THREAD

**Issue by Sulort** [Zrips/Jobs#511]
***Description of issue:**

---
We are using a bungeecord network with 2 servers. on both servers the jobs plugin 4.13.1 is running. Both Servers are using the same MySQL-Database. 
If a player is leveling a job on the first server and switching to the second server the jobxp are gone. and if the player leveling the same job on the second server and switching back to the first server the jobxp are the old one from the first server, and not the jobxp from the second server. so there is a big issue with getting the correct data from the database. 
the jobs plugin is not bungeecord capable. 
could you pls help us, maybe there is something wrong in the config.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```
storage:
  method: MySQL

mysql:
  username: xxx
  password: xxx
  hostname: xxx
  database: xxx
  table-prefix: jobs_
  verify-server-certificate: false
  use-ssl: false
  auto-reconnect: false

save-period: 10

save-on-disconnect: true

selectionTool: golden_hoe

MultiServerCompatability: true
---

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
1.14.4

**Comment by Sulort** [comment]
Hi, I found out, that with your last dev-version here on github, it was version 4.14-dev, it is working with bungeecord, but in that version its not possible to get the lvl of the job back, if a player rejoin a job. in this case the rejoined job is set to lvl 1. 
so we need a mixture between the official 4.13.1 spigot-version and your github-dev-version

**Comment by montlikadani** [comment]
There is no dev release found, already removed. You not get back the job level, because you not configured the `old-job` option in generalConfig, which means, every job leave, you will lost level/exp in that job.

**Comment by Sulort** [comment]
ok, 
first, i know that you have already removed the dev-version. this was only a possibility for you to test the strange behaviour.

here is our part of the config for the old-job section:

old-job:
  level-loss-percentage: 0
  fix-at-max-level: true
  # Percentage to loose when leaving job at max level
  # Only works when fix-at-max-level is set to false
  level-loss-from-max-level: 0

maybe you can find the mistake, thanks

**Comment by Sulort** [comment]
hi, i created a complete new bungee network with two servers as a local version on my desktop pc for testing purpose. 
I tested the 4.13.1 version and the result is the same as described above. the job lvl and the jobxp of a level is mismatching, if a player switching between the two servers. the configuration of the plugin is correct. so could you pls help me. pls contact me, we need a solutions, its urgent.

**Comment by jere62smi** [comment]
I also have the same sync problem, though a lot of my plugins are connected to the database to allow this sync and I do not have that kind of problem with it. If you could fix that quickly, it would be really useful for multi-servers and it would not lose players or hear them rally on things that we can not correct us as a server administrator.

**Comment by Sulort** [comment]
could anybody help, please

**Comment by jere62smi** [comment]
Still no news? Will you take this into account for the next update?

**Comment by Zrips** [comment]
0a7072ffabab1942f3023cc4a8fd07b11b190d9c
