### ISSUE TITLE
Add methods to api

### ISSUE THREAD

**Issue by xXQuantumSoulXx** [Zrips/Jobs#515]
**Description of new idea or improvement on existing one**
You should add methods to the API like for example add a method to boost a player's money for a specfic time by a specific amount, another example is to boost a player's xp on a job

**Detailed information what should do what and when**
If we focus on the first example above, boost player's money, there should be parameters like duration, by how much(x2, x5), and I cant think of anymore that could be needed.

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/blob/master/src/main/java/com/gamingmesh/jobs/api/JobsScheduleStartEvent.java

**Comment by xXQuantumSoulXx** [comment]
Thats not quite what i am looking for

**Comment by BlueSoapTurtle** [comment]
You can do this with permissions as well as listening to the JobsPaymentEvent and boost it via that.

**Comment by montlikadani** [comment]
Now you can do this with [BoostMultiplier#add](https://github.com/Zrips/Jobs/blob/master/src/main/java/com/gamingmesh/jobs/container/BoostMultiplier.java#L31)
