### ISSUE TITLE
When mcMMO says a spot has been overfished, even though you don't actually get the item, you still get the fishing xp and money

### ISSUE THREAD

**Issue by WhatsTheBadNews** [Zrips/Jobs#518]
***Description of issue:** When mcMMO says a spot has been overfished, even though you don't actually get the item, you still get the fishing xp and money

---

**Server Type (Spigot/Paperspigot/etc):** Paper 183

**Server Version (using `/ver`):** 1.14.4

**Relevant plugins (Delete if this isn't needed):** mcMMO, Jobs Reborn

**Comment by TwerkRekt** [comment]
same problem but in 1.12.2

**Comment by WhatsTheBadNews** [comment]
This issue still persists in Minecraft 1.16.5, with the latest versions of Spigot/Paper/all relevant plugins. Any update?

**Comment by icarapovic** [comment]
I made a pull request to fix this -> #1081
As mentioned there - not the ideal solution, but seems to work.

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/ff8747008875a577b3a8653a605c9957be37bbda
