### ISSUE TITLE
Compatibility with CraftBook (and custom-drops plugins)

### ISSUE THREAD

**Issue by Lemrigue** [Zrips/Jobs#52]
When I use the custom-drops option of CraftBook (it makes the stone mined changing in custom stone with name and lore for example) It doesn't count as stone anymore and I did not get EXP or income from jobs.
Can you add compatibility with custom drops plugin

**Comment by Zrips** [comment]
Broken blocks are being checked by their type, not by name or lore.  CraftBook dont have official API and its seams that its cancel's break event and manually drops new stuff on ground, then there is too much of work to add support for it.
