### ISSUE TITLE
Furnace and brewing limits not working.

### ISSUE THREAD

**Issue by Dracathio** [Zrips/Jobs#520]
***Description of issue:**

So no clue why this is being an issue, it worked fine before.
So clear ownership isn't working, right clicking a brewing stand doesn't register it.
This is definitely a  bug for 1.14.4 for sure; no clue why it won't delete my ownership when I try to do /jobs ClearOwnership
More so when I try to do this manually it doesn't register me  right clicking a brewing stand, nor does it register that I have 0 brewing stands owned. It views that I still have 21 owned.

**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot
**Server Version (using `/ver`):** 
1.14.4-RO.1-SNAPSHOT

**Comment by Dracathio** [comment]
...
Or more or less this would be an issue for those who update their server from 1.13.2 to 1.14.4

I fixed this apparently by completely deleting the yml file.

so I guess this is a minor issue, that just forces people to reset up their areas.

**Comment by jere62smi** [comment]
It seems that I also have this problem but only on the furnaces that was already present on the map 1.13.

**Comment by montlikadani** [comment]
This is an old issue... But this works in the latest versions.
