### ISSUE TITLE
Proposing a change to a return value of the Jobs API

### ISSUE THREAD

**Issue by smellyonionman** [Zrips/Jobs#521]
**Description of new idea or improvement on existing one**

Proposing a change to a return value of the Jobs API.  As we are able to set the YAML key "Jobs.exampleJob" to whatever values we want, having API access to it in our code would be handy.  Then we won't have to use the "fullname" in our code, which is ugly and feels bad! 

**Detailed information what should do what and when**

I'm writing code which depends on Jobs and after speaking to some other developers, we've agreed that our lives would be *a lot* easier here if `Jobs.getJob(string)` returned the YAML key `Jobs.exampleJob` instead of `Jobs.exampleJob.fullname`, is this a change you can possibly make?  Thanks!!

**Comment by montlikadani** [comment]
In [this](https://github.com/Zrips/Jobs/commit/ab9ae0da1b4be7a32124bddf5e8d72cd4596748f) added a new method to get the fullName from Job, so the `getName()` method will returns the `Jobs.jobName`.

**Comment by smellyonionman** [comment]
Thank you, thank you so much!  My heart sank when I saw the ticket was closed so fast, you are my hero of the day.  However it did the associations in boostedItems.yml, schedule.yml, shopItems.yml and likely other files I'm less familiar with.  Just an FYI for the next release, and thanks again!
