### ISSUE TITLE
SQLException: Can't call commit when autocommit=true

### ISSUE THREAD

**Issue by Deathinflames** [Zrips/Jobs#526]
Hello, we just updated Jobs Reborn from v4.13.0 to 4.13.1 and now we seem to be having an SQL exception pop up in the console.

It looks like it might be related to this latest change perhaps?

> Now block protection will save/update/delete data in small batches during server runtime. This will prevent from server performing quite a few actions on server stop and stalling server restart action. 

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**

https://pastebin.com/raw/xeUYxcJ0

---

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-645 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/issues/506
Closed due to same.
