### ISSUE TITLE
Custom Max Level Perms

### ISSUE THREAD

**Issue by BloodshotPico** [Zrips/Jobs#528]
**Description of new idea or improvement on existing one**

Basically take the part in the config where it is talking about:

'//[OPTIONAL] - the maximum level of this class with specific permission
//use jobs.[jobsname].vipmaxlevel, in this case it will be jobs.exampleJob.vipmaxlevel
vip-max-level: 20'

And allow us to add our own, giving us free control over this.

**Detailed information what should do what and when**
When a user has the correct perm they will be able to go over the default max level and also allow them to go over the top of each other for example:

Default Level: 10
Basic Group Level: 15
VIP Group Level: 25
VIP2 Group Level: 50
etc etc.

**Comment by montlikadani** [comment]
There is a permission for this: `jobs.max.[number]`
