### ISSUE TITLE
Stone Cutter 1.14

### ISSUE THREAD

**Issue by Drakanoiderna** [Zrips/Jobs#529]
Geting paid when crafting in the new tabels

I notice one dont get paid when craft items in new table like stone cutting table.
it would be nice if that was the case.

(Edit: Spell correction)

**Comment by montlikadani** [comment]
What is tabel?

**Comment by Drakanoiderna** [comment]
What more information do you need?

**Comment by montlikadani** [comment]
Man.. Do you understand what im wrote before?? Im said, what is tabels? Tabel is not an existent thing in the Minecraft.

**Comment by Drakanoiderna** [comment]
Man.. I did correct my post. 
Man.. if you take the time to read the post instead of looking for flaws in the post.
You might understand I placed le wrong order second time i wrote table.

**Comment by montlikadani** [comment]
Well, for stone_cutter has no event called in the Bukkit API, so this not implemented. Also, the InventoryMoveItemEvent & CraftItemEvent is not called equally.

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/c22875bb5916042c6c8b54e7e9317a8be6fac374
