### ISSUE TITLE
Some Jobs don't work fine (question)

### ISSUE THREAD

**Issue by Sprungente** [Zrips/Jobs#53]
Hello 

Anyone here they can help me? Since update to 1.11 and the newest Jobs-Version actually many jobs don't work correctly.
for example
miner
hunter
woodcutter

don't work.

Here's my Jobsconfig: https://gist.github.com/Sprungente/2d79bfdb21f318292b5ba8bff3c36374

No error in any Log or console

Thanks for help

**Comment by Zrips** [comment]
What exactly don't work?

**Comment by Sprungente** [comment]
With the newest version a lot of jobs are working fine only Explorer.
Explore is meaning to explore as first player a chunk or i have it wrong understanded?

When yes, on my server the player will not earn experience, money and points. What have doing wrong or it is a bug?

**Comment by Zrips** [comment]
You should see "[17:50:04 INFO]: [Jobs] Explorer job manager registered!" message in console when starting up to inform about Explorer job successful start. And yes, you will be gaining money depending how many people there where before you in that chunk. By default players who is flying will not gain any money, turn it off in config file.
