### ISSUE TITLE
Problems with the new collect action

### ISSUE THREAD

**Issue by Gorderok** [Zrips/Jobs#530]
When a player makes a left click on a composter or on a sweet of berries and that player is not added to the region, he earns money and xp with the action of collect.
This is a big problem because it can spam click and earn money and XP permanently.

**Comment by montlikadani** [comment]
What region? In worldguard or Jobs area?

**Comment by Gorderok** [comment]
On the spawn of the server or the players can not do anything

**Comment by montlikadani** [comment]
Because maybe the `spawn-protection` is in higher than 0, so has spawn protection, or maybe the worldguard is blocking the usage of composter and sweet-berries.

**Comment by Gorderok** [comment]
Nothing of the sort. the spawn-protection is at 0 and the players can use the composter and the sweet-berries on their parcels.

**Comment by Gorderok** [comment]
And I do not understand why the left click (even where the player can do it) carries money. The action is to collect not to break O_o

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/648c6f412a5e0d0a1dd2eba2da6bed0e2ee930a6
