### ISSUE TITLE
Bone Meal acts like placed block

### ISSUE THREAD

**Issue by UnioDex** [Zrips/Jobs#531]
***Description of issue:**
Bone meal acts like I placed the block I interacted with. 

Example:
I placed wheat seeds, waited for payment. Used bone meal to grow it and then I got paid again.
GIF:
https://i.imgur.com/uTXmEf2.gif

**Server Type (Spigot/Paperspigot/etc):** 
Paper version git-Paper-"f59f630b" (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by montlikadani** [comment]
Are you using the latest version of Jobs plugin? Because in the latest version the player does not get paid when growing wheat seeds with bone meal.

**Comment by UnioDex** [comment]
Updated to latest version. Still happening.

**Comment by montlikadani** [comment]
Send the current plugins on your server and the jobConfig file.

**Comment by UnioDex** [comment]
jobConfig.yml
https://pastebin.com/brwQPQzn

Plugins:
https://pastebin.com/rEwMcFpN

**Comment by UnioDex** [comment]
@montlikadani did you use 1.13 or above for reproducing? It might be relevant with 1.12 and below.
