### ISSUE TITLE
Messages are using Job Key instead of Job Full Name

### ISSUE THREAD

**Issue by UnioDex** [Zrips/Jobs#536]
***Description of issue:**

Messages like levelup, leveldown using jobs config key instead of full name.

Probably started with this:
https://github.com/Zrips/Jobs/commit/ab9ae0da1b4be7a32124bddf5e8d72cd4596748f

**Comment by montlikadani** [comment]
Well, someone wanted to get the job name from the Jobs section instead of the full name, https://github.com/Zrips/Jobs/issues/521

**Comment by UnioDex** [comment]
Instead of changing job.getName() method you should add a new method like job.getRealName() or something because job.getName() has 151 usages throughout the project and probably more on other plugins that use Jobs API. It also broke GUI's, /jobs join <job full name> command.
