### ISSUE TITLE
Passive mob and wither skeleton does not pay | Askyblock

### ISSUE THREAD

**Issue by TwerkRekt** [Zrips/Jobs#540]
***Description of issue:**

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## PASTE ERROR HERE ##
####################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Server Type (Spigot/Paperspigot/etc): Paper 1.12.2 (1618)** 

**Server Version (using `/ver`): 1.12.2 ** 

**Relevant plugins (Delete if this isn't needed):**
Helllo !
Im using aSkyblock for plugin for my skyblock server but on island mob passive like cow, pig, sheep, chicken and wither skeleton dont pay and dont give xp/money

**Comment by montlikadani** [comment]
oh god...
Relevant plugins means, plugins in your server. Also send the jobConfig file and console error if have from Jobs.

**Comment by TwerkRekt** [comment]
https://code.alwyn974.re/okovogofuh.nginx Plugins

https://code.alwyn974.re/junuroyere.php JobConfig
i do not have error

**Comment by montlikadani** [comment]
Wither skeleton is fixed in [this](https://github.com/Zrips/Jobs/commit/ab2405eaff64c3023ea3e7f6698fe10f6cdd4512) commit. Also the cow, pig, sheep, chicken is works with 1.12.2

**Comment by TwerkRekt** [comment]
yes i know it's work but not on island (with askyblock)

**Comment by montlikadani** [comment]
Check in askyblock configuration for passive mobs, because this is not jobs problem, but askyblock which disables entities.
