### ISSUE TITLE
PreventHopperFillUps don't work with option MaxDefaultAvailable

### ISSUE THREAD

**Issue by jere62smi** [Zrips/Jobs#544]
Hello,

I'm coming back to you regarding the "PreventHopperFillUps" option that does not work properly in 1.14.
Currently, players can use the hoppers to earn XP and money for their job by activating the option that logically should prohibit this.
Yet the furnace and brewing are selected in the clearownership.
To put it simply, if the oven belongs to a player, he still wins with the hoppers while if the furnace does not belong to him then he does not earn money.
But do you really think that if we activate the option to limit the number of furnace and brewing, the players will not go out and click on the furnace to get their reward and win winnings. They will not have fun at clearownership / jobs with every use of the oven, it would make no sense and nobody would do it.
I really hope you can quickly fix this problem because it destroys the economy of our servers.

**Comment by Gorderok** [comment]
Indeed, it does not work as in 1.13. PreventHopperFillUps: true does not prevent money and XP gain when the player places items in the hopper above the oven. He should not win anything.

**Comment by jere62smi** [comment]
Should one day be given an answer and a fix? It's already 15 days since my topic is open, no answer, no correction, for against to close the topic of another player who had the same problem as me a few weeks ago without correcting him by saying that there no problem, its was very fast, if only it could be the same to regulate and keep informing people.

**Comment by Gorderok** [comment]
Have you forgotten to answer us or do you not know how to solve the problem?

**Comment by jere62smi** [comment]
Hi, I would like to know if this bug will be fixed soon because I must admit that it strongly handicap the economy of my server.
I am sending you exactly the videos of the problems with the hoppers.
https://www.youtube.com/watch?v=7QnXU9Ewijw
https://www.youtube.com/watch?v=DBqBAGso0PI

**Comment by Zrips** [comment]
4d0ed50e2b9cca59dc60a2276ced666c7bd96c52
