### ISSUE TITLE
"Right/Left click to leave job" in the GUI menu

### ISSUE THREAD

**Issue by Lammendam** [Zrips/Jobs#546]
**Description of new idea or improvement on existing one**
I would suggest to replace "Right/Left click to join job" in job GUI menu with "Right/Left click to leave job" depending on whether a person joined selected job or not.

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/1513e32afcfe77fd70a1f5d3aa2672e46e4e112a
