### ISSUE TITLE
jobs running at 99% cpu

### ISSUE THREAD

**Issue by irobertrs** [Zrips/Jobs#547]
***Description of issue:**
When ever i run jobs it lags my server out its 10gb server but makes the cpu skyrocket

---

**Server Type (Spigot/Paperspigot/etc):** 
paper 1.14.4
**Server Version (using `/ver`):** 
paper 186 
**Relevant plugins (Delete if this isn't needed):**

**Comment by montlikadani** [comment]
Paste server timings report and plugins list.

**Comment by LogGits** [comment]
@irobertrs What cpu model are you running out of curiosity?

**Comment by irobertrs** [comment]
I dont have timings as i was asking for help for a few days on discord but never got any help so i just deleted jobs and cpu is Xeon E5-1650v3 @ 3.8Ghz

basically what happens is i load up my server with jobs and it just goes laggy. even if i delete every plugin but vault and jobs

**Comment by montlikadani** [comment]
Run `/timings paste` and done.

@LogGits CPU information is only needed if we have run out of ideas and there is no way to fix it. So the CPU has no place right now, because it only needs to run our server on a very weak server machine.

Also, for help on discord mention me to get help about your problem.

**Comment by irobertrs** [comment]
i dont have it installed on my server i will put it on a spare server running the same specs later and do a timings report.

also who are u on discord?

**Comment by montlikadani** [comment]
Without server timings this issue can't reproduce. Or just use a memory leak checker and send a screenshot about it.

Same as here.
