### ISSUE TITLE
jobs area commands cause the server to crash

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/Jobs#555]
When one tries to use an area command, the server crashes. Deleting and regenerating the restrictedAreas.yml did not help. The problem applies to all area commands. For example, I tried /jobs area info, /jobs area list and /jobs area add wg:prisma -1.

error: https://pastebin.com/wJzqjxpH
Jobs: 4.13.1
Worldguard: worldguard-legacy-7.0.0-beta-03
FAWE: 1.13 - 184
Paper 1.13.2 - 650

**Comment by montlikadani** [comment]
Known issue https://github.com/Zrips/Jobs/issues/507, #506

**Comment by TheoRetisch1** [comment]
Ahh I missed the tickets because they are so ambiguously titled xD

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/d740b534c3c3b95f77eb00cef036be54a10c2f25

**Comment by TheoRetisch1** [comment]
That sounds awesome thank you!
