### ISSUE TITLE
Database synchronization problem for multi-servers.

### ISSUE THREAD

**Issue by jere62smi** [Zrips/Jobs#556]
Hello, still having no answer and solution for the topic #511, I allow myself to relaunch the subject because I also have the same problem of synchronization between my servers. However, my 2 job configurations are configured on the same database but the data does not synchronize at all between the 2 servers. That is, if I join a trade on server A, by going to server B, I do not have it. Similarly if I pass lvl 10 on a job on server A, and I go on server B, I lost my level progress. Currently the plugin is not at all functional for multi-servers and that for months. I am desperately waiting for a fix of this problem that becomes more than URGENT!
I hope you can do some things for it quickly because it really starts to become a pain for the players.
I use the latest build on the github, the latest version of paper in 1.14.4. I want to point out that I have other plugins in databases and they have no problem of synchronization ...

**Comment by Sulort** [comment]
I highly can confirm this issue. We also have the same BIG Problem on our server. Please could montlikadani or Zribs test this strange behaviour and give us a feedback and hopefully a bugfix. This would be very nice. Thanks a lot!!!

We are also using the latest paper version 1.14.4 and the latest version of the jobs-plugin.
