### ISSUE TITLE
Jobs resets every restart and minor console errors

### ISSUE THREAD

**Issue by mamilicalmir** [Zrips/Jobs#559]
***Description of issue:**
Let me jump to the problem Sir :)
Whenever I restart the server, the player's jobs level, exp and everything resets back to fresh. And some minor console errors regarding with version compatibility.
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## https://pastebin.com/Ajj5LhbL ##
####################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## https://pastebin.com/ZkRXSuWj GeneralConfig ##
## https://pastebin.com/n3AAzcHB JobsConfig ##
#####################################
```

---

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
https://gyazo.com/9b7af5e76d8460618f3bc99f50cfbe38
**Relevant plugins (Delete if this isn't needed):**
https://gyazo.com/cc0115e004b2f875f480c06c05bc321d

**Comment by FeroxDrood** [comment]
Getting this problem too
