### ISSUE TITLE
Offline mode and case sensitive

### ISSUE THREAD

**Issue by xion87** [Zrips/Jobs#56]
Hi i just noticed a thing, if a player log with the name Rick, and later log with the incorect name capitalization (example rIcK), it will still have access to the job but he will not earn any money, can you fix this? thank you

**Comment by Zrips** [comment]
Mainly capitalization issue should be controlled by login plugin. Will be doing some changes related to that to solve main issue that you are not getting money with incorrect name, but this is only will allow to actually have different "account" with different name capitalization what should not be possible in real life situations. I cant attach same jobs account to different players even if difference is in capitalization, their UUID is completely different and plugin is based on UUID, so yea..
