### ISSUE TITLE
Can't put a cooldown on breaking double plants

### ISSUE THREAD

**Issue by Elric02** [Zrips/Jobs#560]
***Description of issue:**

When destroying a double plant by its top, you can bypass the restrictedBlocks.yml cooldown, because it doesn't recognise that you've placed the plant, as you've placed it from the bottom.

So I can't put the double plants in the job I want, because people can abuse it and spam left-click / right-click to earn money as there's no cooldown when you break it by the top.

(not sure if I'm totally clear, if you didn't understand send me a comment)

**Server Type (Spigot/Paperspigot/etc):** 

Spigot

**Server Version (using `/ver`):** 

1.12.2

**Comment by montlikadani** [comment]
This works in the latest versions. Just make sure you have enabled `PlaceAndBreakProtection` option in generalConfig and added the ID of the tall_grass to the restricted_blocks file.
