### ISSUE TITLE
Database write requests asynchronously

### ISSUE THREAD

**Issue by BoomEaro** [Zrips/Jobs#565]
**Description of new idea or improvement on existing one**
I propose to make all queries to the database asynchronous. I think it will be enough to use bukkit to create asynchronous tasks.

**Detailed information what should do what and when**
Currently, all queries in the SqLite database are executed in the main thread, which may cause the server to freeze. This can adversely affect servers that do not have an ssd drive.

I suggest making every request to the database asynchronous in order to avoid unnecessary load on the main thread.

**Comment by BoomEaro** [comment]
Unfortunately, I did not find a centralized method for adding various data to the database.
Therefore, I propose to create a manager to add objects to the database, the methods of which will have a lambda of the following form:

        //example
	public void joinJob(JobsPlayer jPlayer, Job job) {
		Bukkit.getScheduler().runTaskAsynchronously(Jobs.getInstance(), () -> {
			Jobs.getJobsDAO().joinJob(jPlayer, jPlayer.getJobProgression(job));
		});
	}

The problem is still relevant, because several players can take turns abusing this problem. Cooldown does not help often.

**Comment by montlikadani** [comment]
Free to open PR-s and implement this.

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/db987fb532e2170216f7e8efa92b11e4ab61ade2
