### ISSUE TITLE
Command for skipping a job quest once per day

### ISSUE THREAD

**Issue by ShirleyNekoDev** [Zrips/Jobs#566]
**Description of new idea or improvement on existing one**
Our players would like to manually skip a daily quest via command.
This can be necessary when a quest gets randomly selected on two following days and the player would like to have a new one.

**Detailed information what should do what and when**
Players would like to...
- have a command like ```/jobs quests skip <name>```.
  This will remove the named quest from the daily quest list of the player and randomly select a new quest which is not the removed one.

Administrators would like to...
- configure how many quests can be skipped per day.
- add permissions for skipping quests.

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/e7c49d900693a7987f5a8c5735306ac0981a7756
