### ISSUE TITLE
Item Boost issue

### ISSUE THREAD

**Issue by PengBread** [Zrips/Jobs#567]
Hello,
I have encountered a bug which is related to Jobs item-boost issue. 
Apparently armor boosted items doesn't increase xp/income when wearing them on your character. Holding it/on offhand only works.

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** 1.13.2 #651

**Comment by Zrips** [comment]
Could not reproduce. Could you show output from /jobs itembonus or/and /jobs bonus [jobName] to check out if its being detected?

**Comment by PengBread** [comment]
It's detected in /jobs itembonus but the income/exp doesn't increase. 

/jobs itembonus image
![image](https://user-images.githubusercontent.com/28775590/67925910-a1b10800-fbef-11e9-950e-c287fa866961.png)

/jobs bonus woodcutter image
![image](https://user-images.githubusercontent.com/28775590/67926002-d755f100-fbef-11e9-9668-f2e3a697c584.png)



Furthermore, on Jobs v4.14.1, all item bonus don't work as in they are not detected at all in /jobs itembonus.

**Comment by montlikadani** [comment]
It should works as it expected. Just have some issues regarding to NBTs that sometimes works sometimes not even correctly configured. For `MLF` messages, you have to reset your locale file or finding what have been changed.
