### ISSUE TITLE
Re-add the Drink Action Or Remove The Drink Section From The Default Configuration For People In The Future

### ISSUE THREAD

**Issue by DC-FLASH** [Zrips/Jobs#570]
**Description of new idea or improvement on existing one**
Re-adding the old Drink feature or removing it from the default configuration as I and those in the future will see it and think its an option and then wonder why it doesn't appear to be working. Although preferably I would like to see it back as it goes with the Eat action which still does work

**Detailed information what should do what and when**
Work as it was originally intended with the support for mcMMO alchemy potions too please

**Comment by montlikadani** [comment]
We will not add it back because it was superfluous and did not make sense. It has been removed from the default configuration before, but has not followed the changes on GitHub. Otherwise, this Drink action didn't work.
