### ISSUE TITLE
BUG WITH GUI

### ISSUE THREAD

**Issue by zkodz** [Zrips/Jobs#573]
You can get items from the Jobs Browse with a hacked client. This videos explain it easier.

https://www.youtube.com/watch?v=sPOWBW4FMUc&feature=youtu.be

**Comment by montlikadani** [comment]
You're using a hacked client which overwrites the minecraft and bukkit code logics, so it can not be fixed in this place.

**Comment by zkodz** [comment]
You don't understand, some players can enter to the server and with that client dupe/glitch the items from the Jobs Browse command!. That error only work on Jobs, that's why is a error of the plugin. I have tried my self in different servers and the bug is on all! But only in Jobs!

**Comment by montlikadani** [comment]
Players don't have permission to edit/modify the GUI, because not possible. Maybe some GUI plugins are overwrites the Jobs events and this is the problem. Just try to find what plugin uses GUI managers, and report to that plugin owner.

**Comment by BoomEaro** [comment]
I did not find InventoryDragEvent in the JobListener listener.
Probably the lack of cancellation of the InventoryDragEvent event leads to this result.

**Comment by montlikadani** [comment]
We don't called an event InventoryDragEvent, we just using the InventoryClickEvent which handles the jobs browse, [and cancels the interact in the gui](https://github.com/Zrips/Jobs/blob/master/src/main/java/com/gamingmesh/jobs/listeners/JobsListener.java#L240), so the allowed just clicking in the GUI. The problem I think the [priority of event](https://github.com/Zrips/Jobs/blob/master/src/main/java/com/gamingmesh/jobs/listeners/JobsListener.java#L222), because we set to Lowest, prevents other gui plugins doing this same issue. So every interact are cancelled in the jobs gui, just as I said, other gui plugins are overwrites the jobs browse.

**Comment by BoomEaro** [comment]
This is not enough.
You also need to check InvetoryDrageEvent.
InventoryClickEvent does not cancel all events related to inventory. Also, InvetoryDrageEvent is not inherited from InventoryClickEvent, which means it works as a separate event.

**Comment by BoomEaro** [comment]
I noticed a slight oddity.
If you take any thing in survival mode, open /jobs browse and instantly move it with a shift, then it will disappear forever. And this is not a visual bug.
It seems that this happens only with Jobs, because other plugins with the exact same action do not delete the item.

**Comment by BoomEaro** [comment]
This server is running Paper version git-Paper-1615 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[19:49:30] [Server thread / INFO]: Plugins (9): Essentials, EssentialsChat, EssentialsSpawn, Jobs, LuckPerms, ProtocolLib, Vault, WorldEdit, WorldGuard

**Comment by montlikadani** [comment]
Not sure this is the best fix for this issue, so I re-open this issue and stay in open, when we can find a best solution for this. Temporary this is the fix: https://github.com/Zrips/Jobs/commit/c2e0dcd3668f6a2f659e3dddc883e63c1758047a

**Comment by BoomEaro** [comment]
I recommend using your inventory class that implements InventoryHolder.
When creating a menu, you can use it, and also with InventoryClickEvent it is very simple to check for the presence of the required InventoryHolder.
For example:

Inventory inv = Bukkit.createInventory(new JobsInventoryHolder(), 54, "title");
player.openInventory(inv);

InventoryHolder topInventory = event.getView().getTopInventory().getHolder();
if (topInventory instanceof JobsInventoryHolder) {
JobsInventoryHolder jobsInventory = (JobsInventoryHolder) topInventory;
// jobs inventory
}
It can also improve compatibility with any plugins.

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/e2629b4ea653c1a2156d28ada36badce64f19589

I don't close it, because it needs a test to work or not.

**Comment by Zrips** [comment]
804da86dc1a83da03e5171e8e7406a8eb01c6c74
