### ISSUE TITLE
Jobs level command bug

### ISSUE THREAD

**Issue by MrMorganCz** [Zrips/Jobs#574]
Command: 

/jobs level nick jobsname add 5 does not add 5 levels but sets it to 5 so the command works like /jobs level nick jobsname set 5

Jobs version 4.13.1

Server: Paper version git-Paper-214 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by montlikadani** [comment]
Fixed in this commit: https://github.com/Zrips/Jobs/commit/f19138db4d621de1c64ce1cec720e79b157979c3#diff-935fce87ef33baaea920ca6e584eed61
