### ISSUE TITLE
Very much lag with jobs

### ISSUE THREAD

**Issue by Kedarin** [Zrips/Jobs#581]
HI,
I have a problem on my server I have try to change config more and more times bug altime on my /timings the same result jobs take very very much ressources and the server really lag:
https://imgur.com/zniyE57

This server is running CraftBukkit version git-TacoSpigot-fd3209f3 (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

Thank's

**Comment by Zrips** [comment]
b142d68c63ced19448c67df3c86bb1d7ebd8b5f6
