### ISSUE TITLE
Spamming error in console

### ISSUE THREAD

**Issue by Straiker123** [Zrips/Jobs#587]
***Description of issue:**
EconomyDepositEvent event spamming console
---

**ERROR:**
```
https://pastebin.com/idMCpx9P
```

---

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** CraftBukkit version git-Spigot-94af569-6ddeb98 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Relevant plugins:** ServerControlReloade plugin for Economy

**Comment by montlikadani** [comment]
This is not jobs plugins problem, this is the economy plugin, when calling the economy take, set or other, it will calls a new event, which sometimes needs asynchronous task. Same as https://github.com/Zrips/Jobs/issues/584

**Comment by Straiker123** [comment]
This problem isn't in previous version of jobs.
