### ISSUE TITLE
Jobs browse glitch : DUPLICATE items

### ISSUE THREAD

**Issue by Blamo27** [Zrips/Jobs#59]
Hello,

You can glitch the /jobs browse items out of the menu very easily : shift click an item in the jobs browse so it goes in your inventory, then quickly close your inventory while the item is still in your inventory. If you do it well (might take a few tries), the item will stay in your inventory and you'll be free to use it (it's not a ghost item, it's an actual, usable item). It's actually so easy it's becoming a huge issue, since players can find this out without difficulty. Please fix this as soon as possible.
This issue is there on all versions of the plugin.

Thank you for adressing this issue.

**Comment by vcdf** [comment]
There is an even worse version of this glitch:
If you quickly right click a [jobs] browse sign twice, before the GUI opens, you can take all the items to your inventory.

**Comment by Zrips** [comment]
Will be fixed with 3.8.1 version
