### ISSUE TITLE
Initilizing JobsReborn 4.14.2 causes some Error 

### ISSUE THREAD

**Issue by Sulort** [Zrips/Jobs#590]
When restarting the server and after enabling the jobs-plugin, it is producing the same error-logs again and again during the jobs convertion to the new database format.
---
####################
https://pastebin.com/UGHjmwzm
####################

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
Paper 1.14.4  vers. 225

**Comment by montlikadani** [comment]
Send the full console log and the plugin version.

**Comment by Sulort** [comment]
https://pastebin.com/UYi4usqT

Please take a look at the title: Plugin-Version latest 4.14.2

**Comment by montlikadani** [comment]
https://github.com/PaperMC/Paper/issues/720#issuecomment-307236705

So, disable watchdog.

Also, for me it works correctly without this error.
