### ISSUE TITLE
DailyQuests Reset

### ISSUE THREAD

**Issue by DjeyMute** [Zrips/Jobs#591]
Hello,
Now that the quests work pretty well, the reset should work too.
Because it's been months now that we expect to be able to reset the quests every day.
I allow myself to propose if you can not run your "timer" to reset the quests at each reload of the plugin for example or at a time that you set yourself.
This would only be temporary but we would be able to use the quests.
Because at this moment the DailyQuest are unusable without reset.

Thank you in advance for your answer.

**Comment by montlikadani** [comment]
Known issue: https://github.com/Zrips/Jobs/issues/512

**Comment by DjeyMute** [comment]
Yes I know this has already been posted several months ago.
But I do not understand why this is still not fixed? This is not a gray problem, however, I think

**Comment by RSLuke** [comment]
Same here

**Comment by WhatsTheBadNews** [comment]
I am also experiencing this issue.

**Comment by Zrips** [comment]
c598b45fc71b15e7d00852135456a3f0b0749c41
