### ISSUE TITLE
Details of jobs repeating

### ISSUE THREAD

**Issue by PapiCapi** [Zrips/Jobs#592]
***Description of issue:**

Since i installed the last update (4.14.2) , my details of jobs are repeating themselves. So if i do /jobs browse , left click on a job and then put my cursor on the items, it shows me the same text
(for exemple : http://prntscr.com/pr72o1 http://prntscr.com/pr731m http://prntscr.com/pr7355 )

**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper-163 (1.14.4)

**Comment by Sulort** [comment]
I have the same issue.

Server Type (Spigot/Paperspigot/etc):
Paperspigot
Server Version (using /ver):
Paper 1.14.4 vers. 225
Plugin Version:
4.14.2

**Comment by Futurixel** [comment]
Little video of the bug: https://youtu.be/nVOLxdvcEss

**Comment by RSLuke** [comment]
Same here

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/3a7eb6547226ba5be21cac239bc488c4838204f1
