### ISSUE TITLE
JobsGUI -> Buttons reversed with latest version 

### ISSUE THREAD

**Issue by RSLuke** [Zrips/Jobs#593]
***Description of issue:**

No matter if I set this to true or false, the result ingame will always be false, right click will always show more info, left click will always join the job :
  ```# With true left mouse button will join job and right will show more info.
  # With false left mouse button will show more info, right will join job or inversely.
  # Don't forget to adjust locale file!
  SwitcheButtons: true
```

**Server Type (Spigot/Paperspigot/etc):** Paper 1.13.2

**Comment by montlikadani** [comment]
Can you write down your problem more clearly?

**Comment by RSLuke** [comment]
I edited my first message, things went wrong with markdown.

**Comment by Zrips** [comment]
0ece576f58b17a3bfbf7c48331b2eb6f005612bd
