### ISSUE TITLE
JobsGUI -> Workers all set to 0 with latest version

### ISSUE THREAD

**Issue by RSLuke** [Zrips/Jobs#594]
***Description of issue:**

I have hundreds of workers in the differents jobs, since the latest version, the number is 0 on every job (It's only a display problem, things work fine otherwise)

**Server Type (Spigot/Paperspigot/etc):** Paper 1.13.2

**Comment by Zrips** [comment]
Should be back to working condition with latest build, Jobs4.14.2

**Comment by RSLuke** [comment]
I'm using Jobs 4.14.2 actually. and the problem came when I updated to 4.14.2
