### ISSUE TITLE
JobsGUI -> Workers all set to 0 with latest version

### ISSUE THREAD

**Issue by RSLuke** [Zrips/Jobs#595]
Description of issue:

I don't why you closed my last issue, it was a problem in Jobs 4.14.2, and is still here in 4.14.3
I have hundreds of workers in the differents jobs, the number is 0 on every job (It's only a display problem, things work fine otherwise)

Server Type (Spigot/Paperspigot/etc): Paper 1.13.2

**Comment by Zrips** [comment]
database type? Any pictures? It does work for me personally as it should. Shows player count for a jobs with correct values, so something is diffrent in your setup or mine or there is a bug i cant reproduce currently.

**Comment by RSLuke** [comment]
Sure, I'm using MariaDB (10.1.41-MariaDB-0+deb9u1)
https://puu.sh/EXZhq/dd31f7d566.png

**Comment by montlikadani** [comment]
Is this still happens on latest (v4.15.4) version?

**Comment by RSLuke** [comment]
Yes @montlikadani 
https://puu.sh/Fa9gk/927dd698e0.png

**Comment by montlikadani** [comment]
Did you tried to reset your database? If no, then backup your current db, remove the file, and create new by restarting the server.

**Comment by RSLuke** [comment]
I tried to open a new server with the latest version of jobs, got the same problem. everything stays at 0 workers

**Comment by montlikadani** [comment]
Maybe you can switch manually to sqlite instead of mariadb. We don't tested the database with mariadb. Also, this has been already fixed and should works for me with mysql and for others.

**Comment by RSLuke** [comment]
Isn't sqlite slower with big databases ?

**Comment by montlikadani** [comment]
Every database type are in still development, so this issue with slow loading with big database get fixed if you use latest version of sqlite. Only the file size accumulates.

**Comment by montlikadani** [comment]
Is this still reproduce in latest v4.15.7 version?

**Comment by RSLuke** [comment]
The GUI won't even open in v4.15.7
#716
