### ISSUE TITLE
Cancelling JobLeaveEvent

### ISSUE THREAD

**Issue by MidnightSugar** [Zrips/Jobs#599]
***Description of issue:** When I cancel jobleaveevent via API, it will display the message "That job doesn't exist!". Is it possible for you to make it so when the event is cancelled it does not print this message?

**Server Type (Spigot/Paperspigot/etc):**  paper

**Server Version (using `/ver`):** Paper version git-Paper-225 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by montlikadani** [comment]
> That job doesn't exist!

Where this message appear? In command or browse?

**Comment by MidnightSugar** [comment]
In chat. Its the message that appears if you do /jobs join <job> with a job that doesn't exist.

**Comment by montlikadani** [comment]
This works correctly. I think you trying to join to a non-existing job, when you typed the job name.
