### ISSUE TITLE
Jobs Boost Calculates Negative Payout Incorrectly

### ISSUE THREAD

**Issue by delbertina** [Zrips/Jobs#60]
Previously, 0.10 boost would turn +10 into +1 and -10 into -1.
(This was with the permission boost and area boost)

Now, 0.10 boost would turn +10 into +1 and -10 into an a number lower than -10 like -20.

Not sure if this is an intended feature and there is a different way of getting the expected output.

**Comment by Zrips** [comment]
Boost calculation changed to be in simpler format. In example if boost is more than 1, then its bonus, if its less than 1 then its penalty. In example 10 bucks income with 0.1 bonus will result in 11 as 0.1 represents +10%, if it would be -0.1 then final result would be 9, as -0.1 represent -10%. So if you have negative income and getting negative bonus, then you will get event bigger negative income, in example -10 with -0.1 bonus (jobs.bonus.[jobsName].money.-0.1) will result in -11, when 0.1 would result for -9. So in general by getting positive bonus your income will increase in any situation, and when getting negative, it will decrease up to -100% (just to avoid some issues).
