### ISSUE TITLE
Cancelling JobLeaveEvent

### ISSUE THREAD

**Issue by MidnightSugar** [Zrips/Jobs#601]
***Description of issue:** 
My last issue was closed because I don't think you guys understood what I meant. Hopefully this is more clear.

When I cancel jobleaveevent via API, 

For example event.setCancelled(true)

The event is successfully cancelled however, it will display the message "That job doesn't exist!". 

I am not using the command /jobs join or /jobs info where the message is supposed to show. I am cancelling the event, so when a person tries to leave a job, it is cancelled via API, and the player won't leave the job.

In my case, I am requiring players to have $1000 to leave a job, but when they don't have enough money, it will say "That job doesn't exist!" Which doesn't make sense in this context. This message should not be sent if the job leave event is cancelled.

**Server Type (Spigot/Paperspigot/etc):**  paper

**Server Version (using `/ver`):** Paper version git-Paper-225 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by montlikadani** [comment]
> I am not using the command /jobs join or /jobs info where the message is supposed to show. I am cancelling the event, so when a person tries to leave a job, it is cancelled via API, and the player won't leave the job.

You said, a player can't leave a job due to cancelled the event. So you cancelled, and the player can't able to leave from the job.

**Comment by MidnightSugar** [comment]
Yes, exactly. That is what I am trying to do, but I keep getting the "job does not exist" message.

**Comment by montlikadani** [comment]
Send a video/gif/screenshot about this message.

**Comment by MidnightSugar** [comment]
I can't do that was a couple weeks since I away from home/my computer. But just do /jobs join <job> with an invalid job. That is the message that is being sent.

**Comment by montlikadani** [comment]
> an invalid job

With an invalid job? If you give an invalid job in the /jobs join command, it will send this message, because this job is invalid and does not exists in the whole job config.
