### ISSUE TITLE
Jobs server thread/warn

### ISSUE THREAD

**Issue by ChitterChatter** [Zrips/Jobs#602]
Description of issue:
Hi there, we are getting the following warnings. 
Please see the attached pastebin. 
My apologies as I am not good with coding etc and I don't understand the entire warnings.
---

*ERROR - warning:

https://pastebin.com/KcUqtGyP

```

*CONFIG SECTION (DELETE IF NOT RELEVANT):
```
I am not sure which section in the config is relevant. 
I am unable to paste the entire config into pastebin as I am not a pro user. 
Please advise on what further information you require from me. 

```
---

*Server Type:* PaperSpigot

*Server Version:* 1.14.4

**Comment by montlikadani** [comment]
Send the jobConfig file to [hastebin.com](https://hastebin.com/) site and send the link here.

**Comment by ChitterChatter** [comment]
It still says the file exceeds the maximum limit :(

**Comment by montlikadani** [comment]
Then use other site where you can paste the whole file, just google it. Use pastebin.com
