### ISSUE TITLE
memory leak with version 4.14.13

### ISSUE THREAD

**Issue by mrcoffee1026** [Zrips/Jobs#603]
Recently started getting server crashes and this is one of only 3 plugins I'd updated on my server.  After working with the dev on one of them the initial errors during crashes were being thrown by theirs but they said it was due to my running out of memory... of which there is (or should be) plenty free (8gb free+ most anytime)... Although having me examine a heap dump is showing that jobs is taking up an enormous amount of memory with virtually no users on, and will likely overtake the server's capacity every few hours at this rate.

Screen captures I've taken from Eclipse Memory Analyzer:
https://imgur.com/a/WWfJUZG

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
[17:02:43 INFO]: This server is running Paper version git-Paper-226 (MC: 1.14.4)
 (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by montlikadani** [comment]
Well, this is because in order for jobs to work properly, we need to store data in a bunch to avoid losing server restarts. The scheduler (as a background task) is needed to successfully convert money into the Vault economy bank.
