### ISSUE TITLE
Boss Plugin Support

### ISSUE THREAD

**Issue by BobbyMere** [Zrips/Jobs#604]
**Description of new idea or improvement on existing one**
Add support for [Boss](https://www.spigotmc.org/resources/%E2%98%9B-boss%E2%84%A2-custom-monsters-and-animals-on-your-server-1-8-9-1-14-4.46497/)

**Detailed information what should do what and when**
function the same as support for Mythicmobs does

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/02178fc7195330df6c6f3360dfcf3afb0fc6a12e
