### ISSUE TITLE
Problem of /jobs exp player jobs add exp

### ISSUE THREAD

**Issue by Tomodu** [Zrips/Jobs#605]
For a while we have a problem with the / give exp. When you give a sum it is multiplied. Example, I give myself an exp point.
https://image.noelshack.com/fichiers/2019/47/2/1574187707-unknown.png
(before giving an experience point)
https://image.noelshack.com/fichiers/2019/47/2/1574187744-unknown.png
(after giving an experience point)
Having found no solution so far, I come to you for help.

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/92e9e9d15b97fb01dfbd055a6595fca0f7c98dbb
