### ISSUE TITLE
MythicMobs Display Translation/Modification

### ISSUE THREAD

**Issue by C0LiSii0N** [Zrips/Jobs#607]
Hi, I think that implementing a feature to let us translate(Or modify) the mobs name(display) from MythicMobs would be awesome.

Let me explain myself: In MythicMobs we can chose a certain `'Display'` to show as the mob name, the problem is that if, for example;
I add a custom witch(Lets refer as `'FMage'`) that throw fireball with some display like `'&6Fire Mage'`

well if I add `FMage` to the `MMKill` in a job, in the `/jobs info` it will show the exact same thing that I putted in the `'Display'`

the thing is, it as color, and I don't want it to be in color in the `/jobs info`. So if we could add the possibility to change the display in the jobs info (For example, adding support for MythicMobs in the translation file, so I could add something like `FMage: &rFire Mage` under `EntityList`)

With that we could also add some hidden mobs to a certain job like for example GhostBuster so in the `/jobs info ghostbuster` I could put some things like `Casper: &kaaaaaa&r (Unknown Ghost)` in the translation config but still have a mob name like `Casper` in the `MMKill` section and still display the name on top of the mob.

**Comment by Zrips** [comment]
8c4ae9dcf5658208f9be09bb6dfcad949f88f794
