### ISSUE TITLE
[SOLVED] Limiter not working correctly.

### ISSUE THREAD

**Issue by Jozznak** [Zrips/Jobs#61]
Jobs version: 3.8.0
Spigot: Paperclip 1.10.2

Well a player reported me a BUG with limiters that consist in this: When he got exp. limit.. he went out the server to spend some time, when he came back the xp limiter was still on 50 min remaining, but he placed a block and he got exp paid. I don't know if money and Points have the same issue, it's seems not. 
Other problems is with /jobs limit display.
![captura de pantalla 2017-01-25 a las 12 59 35 p m](https://cloud.githubusercontent.com/assets/14141372/22298492/72f02304-e2ff-11e6-9316-4e14120fcba0.png)

When the money limit get 0 it disappears from the /jobs limit

**Comment by Nachodiazv** [comment]
Nothing, it was a LOCALE issue.
