### ISSUE TITLE
Add "all" to /jobs [exp/money/points]boost

### ISSUE THREAD

**Issue by Seeroh** [Zrips/Jobs#611]
**Description of new idea or improvement on existing one**

One upon a time, there used to be a `/jobs boost all [rate]` command. Now, we have `/jobs expboost`, `/jobs moneyboost`, and `/jobs pointsboost`. But "all" no longer works. It just says `The job you selected do not exist!`

**Detailed information what should do what and when**

Just re-implement the "all" option for boosts.

**Comment by montlikadani** [comment]
Why you made a New Feature issue, when this is a bug, which needs a fix?

But nvm, the "all" argument should fixed in https://github.com/Zrips/Jobs/commit/834da89d10655c45d0cbbab8eee11ffdeef3ca98

**Comment by Seeroh** [comment]
Ah, I thought the removal of ALL might have been intended, so I used feature, instead of bug. Thank you for the fix though. :)
