### ISSUE TITLE
Can you troubleshoot database problems with the plugin?

### ISSUE THREAD

**Issue by lanessNet** [Zrips/Jobs#613]
I think it's about the miner break event.

Do you have problems with characters other than English? But the problem didn't happen at other job events like woodcutters or architects

I found out what was wrong yesterday. I hope the problem is solved quickly.

Server Type (Spigot/Paperspigot/etc):

Paperspigot

Server Version (using /ver):

This server is running Paper version git-Paper-235 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

```
  Miner:
    fullname: '광부'
    shortname: M
    description: '광부는 석재나 광물을 캐서 돈을 벌 수 있습니다.(주의*원석을 다시 놓으면 돈과 경험치가 동일하게 환불됩니다.)'
    ChatColour: DARK_GRAY
    chat-display: full
    max-level: 200
    #slots: 10
    leveling-progression-equation: 10*(joblevel)+(joblevel*joblevel*4)
    income-progression-equation: baseincome+(baseincome*(joblevel-1)*0.01)-((baseincome+(joblevel-1)*0.01) * ((numjobs-1)*0.05))
    points-progression-equation: basepoints+(basepoints*(joblevel-1)*0.01)-((basepoints+(joblevel-1)*0.01) * ((numjobs-1)*0.05))
    experience-progression-equation: baseexperience-(baseexperience*((numjobs-1) *0.01))
    rejoinCooldown: 10
    Gui:
      Id: 270
      Data: 0
    Break:
      stone:
        income: 0.88
        experience: 46.26
      granite:
        income: 0.88
        experience: 46.26
      diorite:
        income: 0.88
        experience: 46.26
      andesite:
        income: 0.88
        experience: 46.26
      coal_ore:
        income: 6.13
        experience: 323.29
      iron_ore:
        income: 14.00
        experience: 740.09
      gold_ore:
        income: 61.25
        experience: 3237.90
      lapis_ore:
        income: 9.63
        experience: 508.81
      redstone_ore:
        income: 9.63
        experience: 508.81
      emerald_ore:
        income: 560.00
        experience: 29603.66
    Place:
      coal_ore:
        income: -6.13
        experience: -323.29
      iron_ore:
        income: -14.00
        experience: -740.09
      gold_ore:
        income: -61.25
        experience: -3237.90
      lapis_ore:
        income: -9.63
        experience: -508.81
      redstone_ore:
        income: -9.63
        experience: -508.81
      emerald_ore:
        income: -560.00
        experience: -29603.66
  ##```

**Comment by montlikadani** [comment]
We don't have any database problems, just other reported issues. Also, other chars are works correctly. You should insert the console error if have about jobs.

**Comment by lanessNet** [comment]
There was no console error. Only miner had problems.

**Comment by montlikadani** [comment]
Can you please describe it again what's your problem?

**Comment by lanessNet** [comment]
good

after setting in jobconfig

I have verified that the events of the miner job are working fine in the sqlite repository.

But when I converted to mysql repository state the miner job event didn't work

Other job events have worked

Oddly, only the miner didn't work.

**Comment by montlikadani** [comment]
Could you please paste the whole jobconfig file, to hastebin.com site?

**Comment by lanessNet** [comment]
https://hastebin.com/vamuyubeme.coffeescript

check cfg

**Comment by lanessNet** [comment]
Isn't it possible to send only miner data? Other occupations work normally. "Woodcutter" "Builder"

**Comment by montlikadani** [comment]
> 
> 
> Isn't it possible to send only miner data? Other occupations work normally. "Woodcutter" "Builder"

Why you want to save only one job? We need to save all jobs, because if we don't save the jobs data, then it will loss the player jobs.

> 
> 
> https://pastebin.com/wkxWAUUz - jobconfig
> 
> https://pastebin.com/WDVYXRct - gconfig
> 
> check cfg

Well, recently there has been an update to the database that uses ids instead of job names for easier searching. The problem with this is that it is not completely finished and causes errors.

Here are some things you can try:
- Save your database to other folder, so save the file to another location.
- Rebuild the database, shut down the server, delete the current database and restart the server.
- Log in to the server and join the miner job and do something and see if it works properly.

**Comment by lanessNet** [comment]
shit.... 

Are you still converting item id to item name?

When will it be released? If there's a plug-in problem, there's nothing more to do.

If you still try to create another database, the miner will not work the same.

**Comment by lanessNet** [comment]
> > Isn't it possible to send only miner data? Other occupations work normally. "Woodcutter" "Builder"
> 
> Why you want to save only one job? We need to save all jobs, because if we don't save the jobs data, then it will loss the player jobs.
> 
> > https://pastebin.com/wkxWAUUz - jobconfig
> > https://pastebin.com/WDVYXRct - gconfig
> > check cfg
> 
> Well, recently there has been an update to the database that uses ids instead of job names for easier searching. The problem with this is that it is not completely finished and causes errors.
> 
> Here are some things you can try:
> 
> * Save your database to other folder, so save the file to another location.
> * Rebuild the database, shut down the server, delete the current database and restart the server.
> * Log in to the server and join the miner job and do something and see if it works properly.

I forgot to say it before.

Could it be a problem with the paper bucket or the latest version of 1.14.4?

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/3e0ed72a3fca6fe6e01b1985dda5ac5fe9b33ccf
