### ISSUE TITLE
Jobs v4.15.0-devBuild + dev placeholderapi

### ISSUE THREAD

**Issue by minecraft7net** [Zrips/Jobs#614]
problem when using laststdev placeholderapi + latest dev jobs

https://pastebin.com/f6jBMWkn

Jobs Reborn 4.15.0-DevBuild

https://ci.extendedclip.com/job/PlaceholderAPI/82/

https://pastebin.com/f6jBMWkn

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/d30f0d578dc8e59ea64fa722b15ff0b97a797e90
