### ISSUE TITLE
PreventHopperFillUps does not work in 1.14.4 and 1.15

### ISSUE THREAD

**Issue by Gorderok** [Zrips/Jobs#615]
We are several servers to have the same problem for months!

1.13 if player have furnace linked, put fish ores or other smelting items IN furnace, player GET exp/money, if using hopper, DONT GET anything
1.14.4 and 1.15 if player have furnace linked, put fish ores or other smelting items IN hopper linked to furnace, player GETexp/money, if using hopper, GET TOO anything

https://github.com/Zrips/Jobs/issues/517
https://github.com/Zrips/Jobs/issues/544

**It becomes urgent to correct the problem.**

**Comment by Zzheyd** [comment]
Up ! doesnt work on 1.14/1.15 ... and Smelt is broken ...

**Comment by Zrips** [comment]
4d0ed50e2b9cca59dc60a2276ced666c7bd96c52
