### ISSUE TITLE
Add a Number Of Daily Quests Completed Placeholder for PlaceholderAPI

### ISSUE THREAD

**Issue by WhatsTheBadNews** [Zrips/Jobs#616]
**Description of new idea or improvement on existing one**
![image](https://user-images.githubusercontent.com/29821149/70849678-8caed200-1e47-11ea-96e0-4388e83276bb.png)
Add a placeholder for the number of quests completed. It would be the same as the number shown in the photo that comes up when you do /jobs quests

**Detailed information what should do what and when**

**Comment by montlikadani** [comment]
Use `%jobsr_user_doneq%`, also make sure you are see the wiki of [Placeholders](https://github.com/Zrips/Jobs/wiki/Placeholders), before posting issues.
