### ISSUE TITLE
No money no xp

### ISSUE THREAD

**Issue by rogerxavier93** [Zrips/Jobs#617]
***Description of issue:**
My user are not getting paid but ops or anyone with perm * yes, any idea of what perm might be affecting or creating a conflict? Ussing essentials x and vault
---

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):**  1.14.4 and 1.15 not working

**Relevant plugins (Delete if this isn't needed):** AdvancedLogin*, AdvancedTPA*, AntiForceOP*, AntiVPN, AuctionHouse, BanItem, BeastWithdraw, BeautyIndicator*, Bot-Sentry-Spigot, Cenotaph, ChestCommands, ConsoleSpamFix, DynamicShop, EasyWhitelist*, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsGeoIP, EssentialsProtect, FastLogin*, GHolo, GUIShopSpawners, Harbor, HolographicDisplays, HungerGames, IllegalStack, ItemRenamerReloaded, Jobs, Lasso, LiteBans, MarriageMaster, Matrix, MineableSpawners, Multiverse-Core*, MVdWPlaceholderAPI*, NoPlugins*, PlaceholderAPI, Playtimes*, ProtectionStones, ProtocolLib, SAML, Scoreboard-revision*, SkinsRestorer, Spawn*, SuperVanish, TitleManager*, TradeSystem, UltraPermissions, UUIDGuardian*, Vault, ViaBackwards*, ViaVersion*, VillagerOptimiser, void-generator*, WorldBorder, WorldEdit, WorldGuard

**Comment by montlikadani** [comment]
Make sure you grant the `jobs.world.worldName` permission to your group to get income.

**Comment by rogerxavier93** [comment]
Done now working thanks <3
