### ISSUE TITLE
Melon block don't work

### ISSUE THREAD

**Issue by draysix** [Zrips/Jobs#619]
***Description of issue:**
For my jobs farmer i have add the melon_block. But when people break melon block, they don't win EXP/money.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
## [21:20:56] [Server thread/WARN]: [Jobs] Job Fermier has an invalid Break type property: MELON (MELON_BLOCK)! Material must be a block! Use "/jobs blockinfo" on a target block ##
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
![image](https://user-images.githubusercontent.com/40336956/70944655-d23fea80-2053-11ea-9ddf-67cff999df7f.png)

```
---

**Server Type (Spigot/Paperspigot/etc):paperspigot** 

**Server Version (using `/ver`):1.12.2**

**Comment by Exillium313** [comment]
If you look at the item name for this block its "minecraft:melon"
Replace your "melon_block" with just "melon" and pretty sure it works.
