### ISSUE TITLE
All Jobs not working

### ISSUE THREAD

**Issue by RikoDEV** [Zrips/Jobs#62]
When a player joins to work Miner and start to dig you do not receive exp / money happens all jobs.

JobConfig:
http://pastebin.com/bs0bMiEe

GeneralConfig:
http://pastebin.com/Avpp93DY

**Spigot:** PaperSpigot 1.11.2 (latest)
**Jobs Reborn:** Latest
**Permissions:** LuckyPerms

**Comment by xion87** [comment]
Got same issue with recent releases

**Comment by smmmadden** [comment]
No issues with Spigot 1.11.2, Jobs 3.8.0 and PermissionsEX.  All jobs work fine and paid accordingly.  Not using Dynamic Payments, but pay per block.  If some blocks do not pay, you simply have to edit your jobConfig.yml and add that block to the job in question.  Not all blocks are listed, it is only a starting/default to use.  If a block for a job is not working, check the ID/Name listed in the config in case you are using a name that no longer exists or changed slightly.  There were a handful of entities that changed in 1.11.

**Comment by RikoDEV** [comment]
I don't use permissionsex, without plugins all jobs works fine. This need fix, I test and use default config but the same error. @Zrips can you see this issuse?...

**Comment by Zrips** [comment]
Working on this, next version should be working.
