### ISSUE TITLE
Smelting is giving income even there is a hopper connection. - Smoker

### ISSUE THREAD

**Issue by Getblock** [Zrips/Jobs#621]
***Description of issue:**
Players are able to get income from smelting by using smokers with a hopper feeding into it. 

Jobs reborn version: 4.14.3

```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  Smelt:
    # Prevent payments when hoppers moving items into furnace
    # Player will not get paid, but items will be smelted
    PreventHopperFillUps: true
```

---

**Server Type (Spigot/Paperspigot/etc):**  paperspigot

**Server Version (using `/ver`):** git-Paper-237 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by Gorderok** [comment]
Hi, we have had the same problem for months. I don't think they can fix the problem.
https://github.com/Zrips/Jobs/issues/615

**Comment by Zzheyd** [comment]
Same here ...

**Comment by Zrips** [comment]
4d0ed50e2b9cca59dc60a2276ced666c7bd96c52
