### ISSUE TITLE
Error when loading (1.15.1)

### ISSUE THREAD

**Issue by Momonche** [Zrips/Jobs#622]
***Description of issue: When my server start, Jobs doesn't load, I can see something with PlaceHolderAPI. My version of PlaceHolderAPI is the latest for 1.15 https://ci.extendedclip.com/job/PlaceholderAPI/82/**

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## https://pastebin.com/s6z6yRPq ##
####################
```

---

**Server Type (Spigot/Paperspigot/etc): PaperSpigot** 

**Server Version (using `/ver`): git-paper-23 (MC: 1.15.1)** 

**Relevant plugins (Delete if this isn't needed): PlaceHolderAPI ?**

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/issues/614

**Comment by Momonche** [comment]
Sorry for the duplicate :/
