### ISSUE TITLE
database save task bug

### ISSUE THREAD

**Issue by p82183645** [Zrips/Jobs#624]
![image](https://user-images.githubusercontent.com/5382252/71302822-f3edf880-23ea-11ea-9f0f-1ea856d41dd6.png)

what happen? 
if remove some jobs, plugins can't load

if fullname: 'test'  change to fullname: 'test1'
plugins can't load

**Server Type (Spigot/Paperspigot/etc):** paper

**Server Version (using `/ver`):** 1.14.4

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/3e0ed72a3fca6fe6e01b1985dda5ac5fe9b33ccf
