### ISSUE TITLE
Spam console

### ISSUE THREAD

**Issue by n54b** [Zrips/Jobs#628]
> [00:00:00] [Server thread/WARN]: java.lang.NoClassDefFoundError: Could not initialize class com.gamingmesh.jobs.CMILib.CMIMaterial$1
> [00:00:00] [Server thread/WARN]: 	at com.gamingmesh.jobs.CMILib.CMIMaterial.isPotion(CMIMaterial.java:1545)
> [00:00:00] [Server thread/WARN]: 	at com.gamingmesh.jobs.CMILib.CMIItemStack.isSimilar(CMIItemStack.java:353)
> [00:00:00] [Server thread/WARN]: 	at com.gamingmesh.jobs.listeners.JobsPaymentListener.onBlockPlace(JobsPaymentListener.java:430)
> [00:00:00] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor501.invoke(Unknown Source)
> [00:00:00] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [00:00:00] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
> [00:00:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
> [00:00:00] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
> [00:00:00] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
> [00:00:00] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
> [00:00:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:150)
> [00:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.ItemStack.placeItem(ItemStack.java:207)
> [00:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:505)
> [00:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:953)
> [00:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
> [00:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1)
> [00:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
> [00:00:00] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [00:00:00] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [00:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
> [00:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
> [00:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
> [00:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
> [00:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
> [00:00:00] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
> [00:00:00] [Server thread/ERROR]: Could not pass event BlockPlaceEvent to Jobs v4.15.0-devBuild
> org.bukkit.event.EventException: null
> 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:150) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at net.minecraft.server.v1_12_R1.ItemStack.placeItem(ItemStack.java:207) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:505) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:953) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
> 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

I noticed that this spam occurs when players use a cable generator.
Plugin: Askyblock

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/3e0ed72a3fca6fe6e01b1985dda5ac5fe9b33ccf
