### ISSUE TITLE
Block Placing Error

### ISSUE THREAD

**Issue by LonelyTreeMc** [Zrips/Jobs#629]
***Description of issue:**
Error happens when I place a block 
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## https://pastebin.com/UmDS2FrA ##
####################
```

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Server Version (using `/ver`):** 
1.8.8

**Relevant plugins (Delete if this isn't needed):**

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/3e0ed72a3fca6fe6e01b1985dda5ac5fe9b33ccf
