### ISSUE TITLE
Repeated BUG

### ISSUE THREAD

**Issue by p82183645** [Zrips/Jobs#630]
player can Repeated place block, and break get money and exp

how to fix?

and this https://github.com/Zrips/Jobs/issues/624
still no fix
still happen

**Server Type (Spigot/Paperspigot/etc):** paper

**Server Version (using `/ver`):** 1.14.4

Jobs Reborn 4.15.0-DevBuild

**Comment by montlikadani** [comment]
> player can Repeated place block, and break get money and exp

Yes, the player get money if he/she breaks them.
Also, install the dev-version from releases page.
