### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by KarlPro123** [Zrips/Jobs#631]
***Description of issue:**

---

So I noticed my server started lagging after a day of activity w/o restarts. Timings showed, that old-gen memory was used too much, that means usually its a memory leak or something?
Here's a picture I took while viewing a paper heap dump in visualvm: 
https://imgur.com/a/qkFa2CM
Something with chunks? What is causing this? Are there any other ways that memory leaks occur? Why is even a plugin released that has memory leaks in it?

---

**Server Type (Spigot/Paperspigot/etc):** 

Paper 

**Server Version (using `/ver`):** 

1.15.1 build 27 Paper

**Comment by montlikadani** [comment]
Show the memory report in more detail.

**Comment by KarlPro123** [comment]
https://imgur.com/a/aYmWizI

**Comment by KarlPro123** [comment]
It seems that this is the class that causes the problem 
https://github.com/Zrips/Jobs/blob/master/src/main/java/com/gamingmesh/jobs/container/ExploreChunk.java
Again I am not very professional at this, but it has quite many instances of hit in the memory and the first thing that popped up when I started analyzing some heap dumps.

**Comment by Zrips** [comment]
ca8ea40f7faf2a597a91ff51b821bdd9ff8df0e4
