### ISSUE TITLE
Brewer profession does not displaying

### ISSUE THREAD

**Issue by MaxIsV** [Zrips/Jobs#634]
***Description of issue:**
Hello, please help, for some reason the Brewer profession is not displayed in the menu (/ jobs browse). What to do?

![image](https://user-images.githubusercontent.com/58142896/71851142-89250880-30de-11ea-8f2a-c843a7c43e2a.png)

plugin information:
Jobs version 4.15.1 (just installed, did not change anything in the settings)

I also had this problem on previous versions of the plugin
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```

brewer configuration: https://pastebin.com/bWhj2c9L 

```

---

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
1.12.2

**Comment by n54b** [comment]
error in console ?

**Comment by MaxIsV** [comment]
> error in console ?

no error in console

**Comment by montlikadani** [comment]
You should use 117 ID of GUI item.
```
    Gui:
      Id: 117
      Data: 0
```
