### ISSUE TITLE
Jobs Item Shop | RequiredJobLevels defined in shopitems.yml are Non-Functional

### ISSUE THREAD

**Issue by BoozleDoof** [Zrips/Jobs#638]
**Description of issue:**
Defining RequiredJobLevels in the shopitems.yml configuration does not function properly.

When players view a shop item's requirements, the Jobs Required all list properly, however the level required in those jobs all display a requirement of level 1 despite the configuration in shopitems.yml reflecting different levels for each job for said item.

Plugin allows players to purchase items at level 1 in any of the jobs listed in the config, despite the level requirements associated with them.

**TLDR:**
- Item Configured to require Jobs Miner, Crafter, and Enchanter at levels 5, 3, and 2 respectively.
- Item in shop GUI shows as requiring Jobs Miner, Crafter, and Enchanter at levels 1, 1, and 1.
- Not just a display problem in the GUI, it allows players to purchase at lower than defined levels.
---
**CONFIG SECTION**
shopitems.yml
```
  SpawnerPick_Lv1:
    Price: 2500.0
    Icon:
      Id: wooden_pickaxe
      Amount: 1
      Name: "&bSpawnerPick &aLv1"
      Lore:
      - "&eAdvanced Silk Touch"
      - "&eGentle enough for Mob Spawners."
      HideWithoutPermission: true
      HideIfThereIsNoEnoughPoints: false
    RequiredPermission:
    - jobs.item.rank1
    RequiredJobLevels:
    - Miner-5
    - Crafter-3
    - Enchanter-2
    RequiredTotalLevels: 10
    PerformCommands:
    - "msg &eWhy not try that new pick out on a mob spawner?"
    GiveItems:
      SpawnerPickLv1:
        Id: wooden_pickaxe
        Amount: 1
        Name: "&bSpawnerPick &aLv1"
        Lore:
        - "&eAdvanced Silk Touch"
        Enchants:
        - SILK_TOUCH=2
```
---
![JobsRequiredBug](https://user-images.githubusercontent.com/40279667/72212550-0bbd1780-3493-11ea-9df0-f941d484944b.jpg)
---

**Server Type:** 
 Paperspigot (git-Paper-42)

**Server Version:**
1.15.1 

**Relevant Plugins:**
JobsReborn 4.15.2 | LuckPerms 5.0.39 | mcMMO 1.111| Vault 1.7.2

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/95c3ae35786364e3f8dc385eeb49d24e6635356c
