### ISSUE TITLE
Database xp decimal

### ISSUE THREAD

**Issue by n54b** [Zrips/Jobs#640]
***Description of issue:**

The database does not save the trades exp to 2 decimal.
0.1 👍 
0.01 👎 
---

**Server Type (Spigot/Paperspigot/etc): spigot

**Server Version (using `/ver`): 1.12.2-R0.1

**Comment by montlikadani** [comment]
Please write your problem/suggestion more clearly what you want.

**Comment by n54b** [comment]
My earnings for the trades are around 0.01 / 0.001 and the database does not save below the XP below 0.1. It should be saved anyway.

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/28a8d28818385fb716a3dcec77fc5f1d836bcdcd
