### ISSUE TITLE
xp reset on connection

### ISSUE THREAD

**Issue by n54b** [Zrips/Jobs#641]
14.01 08:32:59 [Server] INFO *********************** Natsu_Rigolx ***********************
14.01 08:32:59 [Server] INFO ▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏  lvl3 Bucheron : 144.0/240 xp
14.01 08:32:59 [Server] INFO ▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏  lvl2 Chasseur : 0.1/140 xp
14.01 08:32:59 [Server] INFO *******************************************************
14.01 08:33:02 [Server] INFO UUID of player Natsu_Rigolx is ****
14.01 08:33:02 [Server] INFO Chargement du profil de Natsu_Rigolx en cours
14.01 08:33:02 [Server] INFO is leader = false
14.01 08:33:02 [Server] INFO Player 'Harnniel' cannot be found
14.01 08:33:02 [Server] INFO Player 'n54b' cannot be found
14.01 08:33:02 [Server] INFO Player 'Lemonad42' cannot be found
14.01 08:33:02 [Server] INFO 【Guide】Natsu_Rigolx s'est connecté
14.01 08:33:02 [Multicraft] Natsu_Rigolx ran command Message of the Day
14.01 08:33:02 [Server] INFO Profil de Natsu_Rigolx chargé en 142ms
14.01 08:33:06 [Server] INFO *********************** Natsu_Rigolx ***********************
14.01 08:33:06 [Server] INFO ▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏  lvl3 Bucheron : 144.0/240 xp
14.01 08:33:06 [Server] INFO ▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏▏  lvl2 Chasseur : 0.0/140 xp
14.01 08:33:06 [Server] INFO *******************************************************

Only for this job, the xp are reset on connection ... I checked my config and found nothing
---

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):**  1.12.2-R0.1

**Comment by montlikadani** [comment]
Which Jobs version are you running?

**Comment by n54b** [comment]
4.15.2 sir

**Comment by montlikadani** [comment]
What type of database are you using?

**Comment by n54b** [comment]
Sqlite sqlite

**Comment by montlikadani** [comment]
Does this still happens in 4.15.3 version?

**Comment by n54b** [comment]
Yea all its ok !!! =D
