### ISSUE TITLE
jobs top showing 50 results, instead of the 15 in config 

### ISSUE THREAD

**Issue by MrMorganCz** [Zrips/Jobs#642]
When using /jobs top {job}, it should give out 15 results to the chat, as specified in my config. But instead, it gives out 50...

ScreenShot:
http://prntscr.com/qnhu9c

`PageRow:
  JobsTop:
    # Defines amount of players to be shown in one page for /jobs top & /jobs gtop
    AmountToShow: 15
  Placeholders:
    # Defines amount of placeholders to be shown in one page for /jobs placeholders
    AmountToShow: 10`

Jobs version 4.15.2

Version:
This server is running Paper version git-Paper-48 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
66fae7ed39a578b4600cb0e89c3d06f06d4e16fc
