### ISSUE TITLE
Player get money for killing other players even if player don`t have any job.

### ISSUE THREAD

**Issue by baxandrei** [Zrips/Jobs#645]
***Description of issue:**
On the server, players who do not have a job receive money because they kill other players.

---

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):** This server is running Paper version git-Paper-51 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)

**Comment by montlikadani** [comment]
Please complete the issue template. Write the Jobs version what you're using and send some screenshots.

**Comment by Zrips** [comment]
@baxandrei 
Go to jobConfig and at the bottom, you will see None job section, remove Kill section if you dont want to reward for killing players when player doesn't have job.
