### ISSUE TITLE
Jobs actions are showing with "none"

### ISSUE THREAD

**Issue by sKye27** [Zrips/Jobs#647]
***Description of issue:**
In the browse menu, when selection a job and looking at the actions to get money some items that are showed with "none", instead of item's name. https://prnt.sc/qqy4xb
---

**Server Type (Spigot/Paperspigot/etc):** paperspigot

**Server Version (using `/ver`):** 1.12.2-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Plugin version and woodcutter config section would be nice to have

**Comment by sKye27** [comment]
Latest version of the plugin and the default generated config.

**Comment by TwerkRektDev** [comment]
same issue here 1.12.2

**Comment by TwerkRektDev** [comment]
latest version paper 1.12.2 (1618) and default config

**Comment by Zrips** [comment]
a707bf8155ddb1e4fa1055083e728c05e148e52a

**Comment by TwerkRektDev** [comment]
issue with planks^^ same problem
