### ISSUE TITLE
The required level of job in the store doesn't work correctly

### ISSUE THREAD

**Issue by MaxIsV** [Zrips/Jobs#649]
***Description of issue:**
I installed the latest version of the plugin (4.15.2), did not configure anything. But in the shop for points, the level of required work is always displayed as 1, although 50 is set in shopItems.yml. And when buying an item, only the 1st level of job is also required.
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**

My shopItems.yml:  
https://pastebin.com/UECiGLrB
---

**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot
**Server Version (using `/ver`):** 
1.12.2

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/issues/638

**Comment by MaxIsV** [comment]
> #638

How do I download commit as a jar?
