### ISSUE TITLE
Cooldown: Switch jobs

### ISSUE THREAD

**Issue by Platinteufel** [Zrips/Jobs#65]
Well, I don't want my players to be able to change a job for 7 days (after 7 days they can pick a new one if they want to). 
I know that it should be possible with some timed permission plugin, but maybe there's a chance to implement this cooldown into Jobs Reborn? 

Cheers ;-)

**Comment by Zrips** [comment]
Currently no, but keep this idea in mind for future updates.

**Comment by Platinteufel** [comment]
It would be awesome if you could add it in one of the next updates, I'd really appreciate it!
