### ISSUE TITLE
Bug with " questtoplist "

### ISSUE THREAD

**Issue by DjeyMute** [Zrips/Jobs#651]
Hi, 

Quest ranking doesn't work.
Once the sign is configured for "questtoplist", the sign convert to a "toplist" when a player joins the jobs
The signs change function as if I had configured them for "toplist".

**Before** --> 
![1](https://user-images.githubusercontent.com/47302852/73211616-e09e1d80-414c-11ea-9aaa-0b87dd0d94d9.png)

**After player take a job** --> 
![2](https://user-images.githubusercontent.com/47302852/73211632-e562d180-414c-11ea-9916-17d8a942af5a.png)

Server : Spigot 1.15.2
Version of Jobs : 4.15.3
Thank's in advance.

**Comment by montlikadani** [comment]
Please send a screenshot for proof thing and change the "Latest version" to the version number what you using currently.

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/06db89af5ed6d2ef8486a1320b855c217085befa
