### ISSUE TITLE
Bug with SQL

### ISSUE THREAD

**Issue by DjeyMute** [Zrips/Jobs#652]
**Thirst error :**

WARN [Jobs] Plugin Jobs v4.15.3 generated an exception while executing task 43707
27.01 21:38:31 [Server] INFO java.lang.NumberFormatException: null
27.01 21:38:31 [Server] INFO at java.math.BigDecimal.<init>(BigDecimal.java:497) ~[?:1.8.0_221]
27.01 21:38:31 [Server] INFO at java.math.BigDecimal.<init>(BigDecimal.java:383) ~[?:1.8.0_221]
27.01 21:38:31 [Server] INFO at java.math.BigDecimal.<init>(BigDecimal.java:809) ~[?:1.8.0_221]
27.01 21:38:31 [Server] INFO at java.math.BigDecimal.valueOf(BigDecimal.java:1277) ~[?:1.8.0_221]
27.01 21:38:31 [Server] INFO at com.earth2me.essentials.api.Economy.subtract(Economy.java:191) ~[?:?]
27.01 21:38:31 [Server] INFO at net.milkbowl.vault.economy.plugins.Economy_Essentials.withdrawPlayer(Economy_Essentials.java:107) ~[?:?]
27.01 21:38:31 [Server] INFO at net.milkbowl.vault.economy.AbstractEconomy.withdrawPlayer(AbstractEconomy.java:40) ~[?:?]
27.01 21:38:31 [Server] INFO at com.gamingmesh.jobs.economy.VaultEconomy.withdrawPlayer(VaultEconomy.java:43) ~[?:?]
27.01 21:38:31 [Server] INFO at com.gamingmesh.jobs.tasks.BufferedPaymentTask.run(BufferedPaymentTask.java:43) ~[?:?]
27.01 21:38:31 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.1.jar:git-Paper-62]
27.01 21:38:31 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.1.jar:git-Paper-62]
27.01 21:38:31 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.1.jar:git-Paper-62]
27.01 21:38:31 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_221]
27.01 21:38:31 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_221]
27.01 21:38:31 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]

**Second error :** 

27.01 21:48:56 [Server] WARN java.sql.SQLException: 'NaN' is not a valid numeric or approximate numeric value
27.01 21:48:56 [Server] WARN at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
27.01 21:48:56 [Server] WARN at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
27.01 21:48:56 [Server] WARN at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
27.01 21:48:56 [Server] WARN at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
27.01 21:48:56 [Server] WARN at com.mysql.jdbc.PreparedStatement.setDouble(PreparedStatement.java:3315)
27.01 21:48:56 [Server] WARN at com.gamingmesh.jobs.dao.JobsDAO.save(JobsDAO.java:1902)
27.01 21:48:56 [Server] WARN at com.gamingmesh.jobs.container.JobsPlayer.save(JobsPlayer.java:760)
27.01 21:48:56 [Server] WARN at com.gamingmesh.jobs.PlayerManager.saveAll(PlayerManager.java:247)
27.01 21:48:56 [Server] WARN at com.gamingmesh.jobs.tasks.DatabaseSaveThread.run(DatabaseSaveThread.java:46)

**Server : Spigot 1.15.2
Version of Jobs : 4.15.3**
Thank's in advance.

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/a521ac7b5a830243acf73ad7f96996baa562ad90
