### ISSUE TITLE
New message when leaving a job.

### ISSUE THREAD

**Issue by baxandrei** [Zrips/Jobs#653]
**Description of new idea or improvement on existing one**
New message when trying to leave a job that was already leaved. 

**Detailed information what should do what and when**
For example, if you already leaved job miner, instead of message `The job you selected does not exist! ` to show something like `You are not emplyed in this job.`

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/0d684ea41c19fe6cc123b9d088359b685540f1fb

**Comment by baxandrei** [comment]
It's not exactly how I thought it would be, but it's ok. Thanks.

**Comment by montlikadani** [comment]
Free to open a PR to change to yours translation.

**Comment by baxandrei** [comment]
I am not familiar with java and I would not want to ruin anything, I just wanted that when the player wants to leave a job where he is not hired to appear a completely different message.

Something like that: 
```
c.get("general.error.job", "&cThe job you selected does not exist!");
c.get("general.error.job.not_employed", "&cYou are not employed for this job.");
```
