### ISSUE TITLE
Bug enchantments in the "/jobs shop"

### ISSUE THREAD

**Issue by Silverfabien** [Zrips/Jobs#655]
Hi, (sorry about my English),

The enchantments of the objects of the shop "/jobs shop" do not work. During the purchase, the object is received with the enchantments on level 1 (screen below). 

_The tests were performed with the default configuration._
![jobshop](https://user-images.githubusercontent.com/29354438/73263340-a4140580-41d0-11ea-8a8c-e5b187a59772.png)

Configuration of shopitem.yml : https://pastebin.com/ewjSSLsU

**Server :** Spigot 1.15.2
**Version :** 4.15.3 

Thank's in advance.

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/892c91cdf0b593d697a1511b913885df6024df86
