### ISSUE TITLE
EventException Console Spam on Jobs 4.15.3

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/Jobs#656]
**Description of issue:**

Getting some major console spam every time someone breaks a block when first updating to Jobs 1.15.3 on Spigot 1.15.1. 

**ERROR:**

https://gist.github.com/mercurialmusic/014cbda53d1a134a235e98f543321ba2

---

**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
CraftBukkit version git-Spigot-037559e-5c6b0dc (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/d5752453dde084402da577ec6c0f67ee29abe462
