### ISSUE TITLE
Gtoplist Sign

### ISSUE THREAD

**Issue by ghost** [Zrips/Jobs#658]
***Description of issue:**
We wanted to create signs with the job toplist but it doesn‘t work: Maybe the fault is on us, but we can‘t see it: https://gyazo.com/6a061f56302fa50088325a4ca962e6e3

---

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** 1.15.2

**Comment by montlikadani** [comment]
Can you please send the jobs plugin version?

**Comment by N0tMyFaultOG** [comment]
I seem to experience the same issue. I can create signs fine using `toplist`, but if I use `gtoplist` the sign turns blank.
https://i.gyazo.com/d7c1fd602368ae4c1e377dfc7683f0ff.mp4
Jobs version 4.15.4
Server Version: Paper 1.15.1 build 62

**Comment by BeastyGK** [comment]
We have got the newest version of the Jobs plugin

**Comment by Hyronymos1337** [comment]
we have the same bugg, do you still need more informations?

**Comment by Italoplcl** [comment]
we have the same bug in 1.15.2 paper 89

**Comment by MeesterMaarten** [comment]
The problem persists. Is there a solution on the way for this problem?
Jobs Reborn: 4.15.5
Server Version: Paper version git-Paper-121 (MC: 1.15.2)

**Comment by Italoplcl** [comment]
En alguna versión antigua el plugin funciono correctamente? Alguien sabe que version es y si funciona en la 1.15.2 para usar esa version hasta que puedan solucionar los problemas?

Por discord pregunte pero no hay soporte o no responden los designados. (hace semanas)

**Comment by MeesterMaarten** [comment]
The problem persists. Is there a solution on the way for this problem?
Jobs Reborn: 4.15.5
Server Version: Paper version git-Paper-137 (MC: 1.15.2)

**Comment by MeesterMaarten** [comment]
Marked as 'Fixed' in latest 4.15.6 version, but 'gtoplist' signs are still not working when marked as: 'Fixed database syntax issue when getting the global top list' on Spigot. Other signs such as 'toplist' are working, but 'gtoplist' keeps the signs empty without information! Paper version git-Paper-144 (MC: 1.15.2).

**Comment by MeesterMaarten** [comment]
![Bug](https://user-images.githubusercontent.com/46909512/78035159-0328fe80-7369-11ea-8a39-aa88d8cffae7.png)
Toplist signs also turn into "quest"...  Bug: confirmed indeed!

**Comment by montlikadani** [comment]
Is this still reproduce in latest v4.15.7 version?

**Comment by Zimoune** [comment]
Hello, this version solved the issue for me
