### ISSUE TITLE
PlaceAndBreakProtection not paying after CD

### ISSUE THREAD

**Issue by omar31** [Zrips/Jobs#66]
So i have set this to true in the config
PlaceAndBreakProtection: true

when this is set to true if the item i place is on the  restricted blocks config i just get the message that i need to wait X secs before i get paid.  however i never got paid for any of those blocks i even made sure that the cool down time had already passed and that the payout time had already passed too.
Am i using the feature incorrectly or is it a bug?

info you might need:
running on spigot-1.11.2
plugin version Jobs3.8.1
i have vault and core protection installed
The general config is uploaded below ( i changed the yml into txt so i can upload)
[generalConfig.txt](https://github.com/Zrips/Jobs/files/753365/generalConfig.txt)

Thanks in advance.

**Comment by omar31** [comment]
it seems as though in order to get paid for placing a restricted block you have to destroy it and put it again after the cool down has passed to get paid. the break protection seems to be working fine though.

**Comment by Zrips** [comment]
Core protection is no longer supported as it was making more issues than solving. Currently there is build in block protection and some fixes will be added with next build too.
