### ISSUE TITLE
Jobs tab completer and staff in vanish

### ISSUE THREAD

**Issue by Zzheyd** [Zrips/Jobs#662]
Hi here, have a little problem with jobs.

Jobs version 4.1.5.4 / Paper 1.15.1 

You can see here : https://cdn.discordapp.com/attachments/285777124139466753/673862233465552917/2020-02-03_12.54.02.png

5 players online (1 staff on vanish, wth SuperVanish >> Be invisible 6.1.3)

But, with jobs tab completer ... all player can see this : 
https://cdn.discordapp.com/attachments/285777124139466753/673861726684577823/2020-02-03_12.54.37.png

I dont know if it's bug, or it's only jobs cant fix it :/

Thank you for reading !

**Comment by montlikadani** [comment]
We will not add the ability to filter hidden players from appearing in the tab-completer. This plugin is not a tab-completer filter, but a job manager and a payer. Anyway, you don't need to filter out hidden players from the tab-completer plugin because we need to.

**Comment by Zzheyd** [comment]
Strangely, because with "Fe 0.9" or "essentialsX" it's work fine :)
In tab completer, nobody player can see player in vanish :)

Maybe can it a good idea to add this ...

**Comment by montlikadani** [comment]
As I said, we need to show all (including hidden) players in tab-completer to (example) force kick from a job. So it's not a good idea to hide vanished players from the list, what we want to kick from all jobs.

**Comment by Gorderok** [comment]
Hello I have the same problem. It would be good to add a blacklist for administrators.

**Comment by montlikadani** [comment]
Why? It just an unnecessary feature for Jobs which is not jobs related thing.

**Comment by Gorderok** [comment]
Because the players can see the administrators who are vanish. Being in vanish allows us to be invisible to players! 
However, the /jobs stats <tab> display the hidden administrators.

**Comment by Zzheyd** [comment]
Why ?
Question, if i'm administrator, if i'm on vanished for checking if player cheat or glith ... it's simple for any player to check if staff are on vanish mode with this :

/jobs stats * <- look here is staff is present ... oh wait, staff is on vanish mode ... i'm waiting it pass offline for cheating ... 

But, with "Fe 0.9" or "essentialsX", is staff is on vanish mode, players can't see staff nickname in tab completer.

I hope i was explain why with my no perfect english ^^

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/975dd3cd87cd0cad7c8197593a13b1ac04ff9931 (incomplete)
