### ISSUE TITLE
Translation bug

### ISSUE THREAD

**Issue by Gorderok** [Zrips/Jobs#663]
Hello, on the latest version, the translation for the collect still does not work. It puts the translation of Honey_bottle for the 3.
![1](https://user-images.githubusercontent.com/43994828/73674187-468c2700-46b0-11ea-9e28-39581c6e06f6.png)

**Comment by Gorderok** [comment]
Jobs Version 4.15.4
PaperSpigot #89

**Comment by montlikadani** [comment]
These materials have no official ids that we can support. You should wait for Mojang to release it.

**Comment by Zrips** [comment]
d9791c51fa5b0f9bdb68f82ece2ef24d7832b94d
