### ISSUE TITLE
Top job is buged

### ISSUE THREAD

**Issue by Gorderok** [Zrips/Jobs#664]
Hi, I have a new problem. The top in a profession. For example here my player is level 25 "Chasseur" and when I look in the /jobs top Chasseur it does not appear. Players are hidden between page 1 and 2. Can you fix this?
![job1](https://user-images.githubusercontent.com/43994828/73674286-789d8900-46b0-11ea-9c4f-d3fe17df6d58.PNG)
![job2](https://user-images.githubusercontent.com/43994828/73674290-7a674c80-46b0-11ea-83d9-091a57c8bf76.PNG)
![job3](https://user-images.githubusercontent.com/43994828/73674294-7b987980-46b0-11ea-85ac-5c93a386e496.PNG)

**Comment by montlikadani** [comment]
Please complete the issue template. What jobs version are you running (version number)?

**Comment by Gorderok** [comment]
Jobs Version 4.15.4
PaperSpigot #89

**Comment by Sulort** [comment]
we also have the same problem. could you pls fix it.
we are using paperspigot 1.15.2 latest version and
jobs version 4.15.4

**Comment by Zrips** [comment]
11bcc004e572eafd488b7fb57f4e98658038f131

**Comment by Gorderok** [comment]
Always the problem with the latest version 4.15.5.

**Comment by mechcalvin** [comment]
the latest release fixed the gtop, but if you do gtop 2, gtop 3, there is nothing to see

**Comment by Gorderok** [comment]
Always the problem with the latest version 4.15.6
