### ISSUE TITLE
Bug jobGui

### ISSUE THREAD

**Issue by Gorderok** [Zrips/Jobs#666]
I also have an error when I click on one of the trades. May be there are too many items?
https://pastebin.com/sM8bMABP

May be there are too many action in this job. I was try reduce many action in this job and work find, but the return button disapear.

![2020-02-06_19 56 41](https://user-images.githubusercontent.com/43994828/73970237-12696e00-491d-11ea-99d0-c3ca4093220a.png)

If I add actions, I get the error message again and the interface does not open. We should add the possibility of having several pages for a job.

**Comment by Gorderok** [comment]
Always the problem with the latest version 4.15.5.
https://pastebin.com/druRwn6q

**Comment by montlikadani** [comment]
Can you please send your current jobConfig file?

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/d43817520fced0907c6cdf9f79982c2ba9f1b70e This commit should fixes this issue (tested).

**Comment by Gorderok** [comment]
The fix does not produce a bug but we cannot have other pages. All my job does not fit in a menu page.
