### ISSUE TITLE
Custom Objective

### ISSUE THREAD

**Issue by quochungudon** [Zrips/Jobs#668]
You can set the objective to type custom with name identifer "x" . Then if you run a command like 'jobr customobjective (identifername) (playername) (amount)" , it will add a amount to the identifer , and if player achive the amount , player will done the quest. It will easier to hook with another plugin

Flow chart:
1. Player get the quest with custom objective "swiminlava" with amount 1
2. Now the server owner will hook with other plugin , and add reward when player done objective to a command like "jobs customobjective swiminlava playername 1"
3. Jobs Reborn receive command and check the amount 1=1 => objective complete

It will easier for server owner to hook up with other plugin fast and easy.

**Comment by montlikadani** [comment]
I do not think this is related to Jobs. It's more of an achievement that you can use to complete different quests. The [AdvancedAchievements](https://www.spigotmc.org/resources/6239/) plugin is designed for this.

**Comment by quochungudon** [comment]
> I do not think this is related to Jobs. It's more of an achievement that you can use to complete different quests. The [AdvancedAchievements](https://www.spigotmc.org/resources/6239/) plugin is designed for this.

No , it is a feature for server admin make custom task without use api to connect jobsreborn with some plugin . For example , if jobsreborn not support mythicmobs mob kill yet , server owner can make a custom trigger for the mob will run a command to trigger jobsreborn custom task , and jobsreborn make player complete quest

**Comment by montlikadani** [comment]
This would be a huge job again and unnecessary, because we create unique things, it wouldn't make sense, because then the jobs would disappear, because the unique option is to create the jobs. To do this, I now recommend using job quests. Other plugins can create jobs with the Jobs API and create quests.
