### ISSUE TITLE
There is an error where the placeholder of a worker is not displayed.

### ISSUE THREAD

**Issue by geumu** [Zrips/Jobs#669]
**Bukkit**: Paperspigot 1.13.2
**Plugin**: Jobs Reborn 4.15.2
**jobConfig**: https://pastebin.com/Cmx7PLFi
**Desc**: There is an error where the %jobsr_total_workers%, %jobsr_totalplayers_[jname/number]% placeholder of a worker is not displayed.
**Image**: https://imgur.com/a/M9QT31t

**Comment by montlikadani** [comment]
Where you using this placeholder?

**Comment by geumu** [comment]
> Where you using this placeholder?

i found reason
if i change fullname:

**Example)**
Woodcutter:
     fullname: test
placeholder does not work.

Video: https://youtu.be/XIm50IOsIXY

**Comment by geumu** [comment]
> Where you using this placeholder?

We also found a bug that increases the number of workers by two.

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/7271bda0c592025959d3cc2d9343eb3ef6d98a61
