### ISSUE TITLE
Jobs Limits improvements

### ISSUE THREAD

**Issue by evernife** [Zrips/Jobs#67]
Hello there.
First, ty for the great plugin!

(Note: I dont know if i should ask this only in the spigot discussion, or here in the gifhub, i read it
![image](https://cloud.githubusercontent.com/assets/11357801/22855487/6556662e-f068-11e6-820b-6161520a4c7e.png)
and got myself confused...)

I want to ask you a feature for the limitation of money per players.

I would like to make in my server a daily reward money limit of , for exemple, 500 $
But i want to limitate the hour reward, for each hour the player can receive only, for exemple, 100 $

So, the player needs to enter in the server into 5 different hours to win all money disponible in that day.
This is my first request.

If that is acceptable, i would ask a permission to bypass the second time limitation, for exemple, a player has rank "Worker++" (the rank has the permission) he could take all the 500 $ inside an only hour but not get more then the daily limit.
I don't know if i was clear in what i am asking, sorry, bad english.

**Comment by montlikadani** [comment]
Use the [Advanced Achievements](https://www.spigotmc.org/resources/advanced-achievements.6239/) plugin for question 1.

To question 2, open a Pull Request.
