### ISSUE TITLE
Activate scheduled boosters with a command

### ISSUE THREAD

**Issue by TastyBlueberry** [Zrips/Jobs#671]
Hello,

Could you add a feature to enable boosters with a command? Something like the point/exp/moneyboost command, but than pre-configured like the scheduled boosters. So for example if you have a booster (named votebooster) configured in the scheduledboosters.yml, you can enable that weekendbooster with the command /jobs booster votebooster 1h. This will enable that booster for one hour. This would be amazing, because I'd like to enable boosters when a certain amount of votes is reached.

Thanks!

Roel

**Comment by montlikadani** [comment]
I don't understand why a command is needed to do a simple thing. People are very lazy to open the configuration and do some simple things in the config to work. So, go into the config and enable the configuration, configure the time, then reload the plugin and you're done.

**Comment by TastyBlueberry** [comment]
The configuration is limited because you can only activate boosters at certain times. It's not that I'm lazy, but I want to automatically activate boosters when certain events happen (by which I mean buycraft/votingplugin automatically execute a command when someone buys something / when certain amount of votes is reached). This is just not possible to configure, because the boosters have to be activated at random times. Players love the boosters, but when you can only use them at pre-configured times you limit the use of the booster feature.
