### ISSUE TITLE
only in certain worlds?

### ISSUE THREAD

**Issue by Resi23** [Zrips/Jobs#672]
Is it possible that jobs only work in certain worlds. For example, miners in the farm world only get XP, points and money. and hunters can only get xp, points and money in the nether.

**Comment by montlikadani** [comment]
You should use disabledWorlds option that found in generalConfig.

**Comment by Resi23** [comment]
But with disableworlds I can only generally exclude a world from all jobs. But I would like to ban various jobs in different worlds.

**Comment by montlikadani** [comment]
You can change the behaviour of the disabledwords, so if you enable that option then you can disable that worlds.

**Comment by Resi23** [comment]
Sorry I don't understand you could give me an example. No matter how I do it, either all jobs go or none.

**Comment by montlikadani** [comment]
Find this:
![kép](https://user-images.githubusercontent.com/30026208/74666316-90413b00-51a1-11ea-8f90-78bbc6585711.png)
So, you should enable the `Use` option. Make sure the `UseAsWhiteList` is enabled, and put the world names to the `List` section, where the jobs works.

**Comment by BijuuKrunos** [comment]
I think you missunderstand waht Resi wants xD.
He want to have some of the Jobs be only aktive in certein worlds. He is not speaking about disable/enable the plugin itself in the world.

for example:

the Miner gets xp in the overworld. But he cant get xp from mining Nether Quarz in the nether.

the Hunter dont get xp for killing mobs in the overworld. But he get xp from killing mobs in the nether.

He wants that job a get xp on world 1 and 2 but not on 3. Like this.

Hope you now understand 📦 
Greetz the German Dude.

**Comment by Resi23** [comment]
> I think you missunderstand waht Resi wants xD.
> He want to have some of the Jobs be only aktive in certein worlds. He is not speaking about disable/enable the plugin itself in the world.
> 
> for example:
> 
> the Miner gets xp in the overworld. But he cant get xp from mining Nether Quarz in the nether.
> 
> the Hunter dont get xp for killing mobs in the overworld. But he get xp from killing mobs in the nether.
> 
> He wants that job a get xp on world 1 and 2 but not on 3. Like this.
> 
> Hope you now understand 📦
> Greetz the German Dude.

Yes that is what i mean
