### ISSUE TITLE
Quite high consumption of certain Event

### ISSUE THREAD

**Issue by jere62smi** [Zrips/Jobs#673]
Hello,

By analyzing the / timings of my server, I noticed a fairly high consumption of the following events:
- BlockBreakEvent
- FurnaceSmeltEvent

As you can see under my screens,
http://prntscr.com/r32nk2
http://prntscr.com/r32o9d
http://prntscr.com/r32ojr

I will provide you with the complete timings if this can be useful, but I have trouble understanding why a smelt consumes more than a furnace.

https://timings.aikar.co/?id=d85e7777a33546ebb11a88449645a8de#timings

Server version: Paper-105 (MC-1.15.2)
Jobs version: 4.15.5

**Comment by montlikadani** [comment]
This cannot be fixed in the plugin. These are the events that players can use to collect rewards. So if a player breaks a block then the event is called and even more than once the player does it. This can only be improved by having fewer players on the server working.
