### ISSUE TITLE
Hostile mobs not rewarding XP

### ISSUE THREAD

**Issue by Abbnoxious** [Zrips/Jobs#674]
Hey. So I was setting up some custom jobs in jobsconfig. I didn't change much besides names, and I took what was in the "Hunter" jobs present as far as the "Kills" section went and put that into every other job. Unfortunately no matter what I do, XP is only gained from killing a small set of friendly mobs (literally just chicken, cows, pigs, sheep, wolves). I have tried to deop myself, switching between gamemodes, killing naturally and artificially spawned mobs, and the problem remains the same. 
I assumed that being able to earn XP by killing most hostile and passive mobs was a feature because many of them were under the Hunter preset. Other presets that don't involve killing for XP work fine. Is there any reason that this would happen such as being on an older version of Minecraft or am I making a silly mistake?

Running latest version of Jobs Reborn on Craftbukkit Spigot 1.13.2.

**Comment by montlikadani** [comment]
Send the jobConfig file to pastebin.com site.

**Comment by Abbnoxious** [comment]
https://pastebin.com/n9jeXyeB

**Comment by Abbnoxious** [comment]
I actually figured it out myself, but thanks for the assistance. Turned off MythicMob support and that fixed it. Wasn't clear on what " # Disable if you having issues with it or using old version" was specifically referring to (server version, jobs version, or MM version?). Feel a bit silly now. Might want to mention this in the config for people who are still on 1.13. :)

**Comment by Abbnoxious** [comment]
I actually figured it out myself, but thanks for the assistance. Turned off MythicMob support and that fixed it. Wasn't clear on what " # Disable if you having issues with it or using old version" was specifically referring to (server version, jobs version, or MM version?). Feel a bit silly now. Might want to mention this in the config for people who are still on 1.13. :)
