### ISSUE TITLE
XP Gain on movement for Jobs without Explore options for XP gain.

### ISSUE THREAD

**Issue by Abbnoxious** [Zrips/Jobs#675]
So I'm having an issue where players will gain XP from exploring without actually having any exploring XP gain options for the job they have. Any fix for this? Running Spigot 1.13.2.

**Comment by montlikadani** [comment]
What is not specified in the jobConfig file will not be eligible for rewards. The plugin does not reward you simply by doing nothing at work that is not included.

**Comment by Abbnoxious** [comment]
Maybe I worded it wrong, sorry! I'm just a bit confused. I'm saying that the plugin IS rewarding XP by doing nothing at work that is not included.

**Comment by montlikadani** [comment]
Do you have any video or gif for that? _Last text removed.._

**Comment by Abbnoxious** [comment]
The jobsConfig shown in Notepad++ is the same as what's live on the server.
The only job I have is Monk, which has no Explore for XP gain options on it. Only killing mobs. Here you go.
https://youtu.be/0Dna0MMiDs4

**Comment by Abbnoxious** [comment]
Actually just tested some more and it seems it's a problem that occurs just in survival and not creative. Hope that helps.

**Comment by montlikadani** [comment]
You should check the plugins what plugins are compatible with jobs and doing this problem. If you don't know what plugin is causing then you should remove one by one.

**Comment by Abbnoxious** [comment]
We have quite a few plugins, but most of the core ones I noted were compatible with Jobs... before I test further and get into all of that, do you think any of these might cause a problem?
![image](https://user-images.githubusercontent.com/61202341/74874940-80eff800-532f-11ea-8d02-54dacfcc2521.png)

**Comment by montlikadani** [comment]
Are you using the latest (v4.15.5) version of Jobs? And you reloaded the plugin?
