### ISSUE TITLE
Points dissapears

### ISSUE THREAD

**Issue by Superola86** [Zrips/Jobs#677]
***Description of issue:**

I do use CMI to hourly reward players with 100 jobs points. 
This points do get saved into the DB like it should. When we restart the serer some of the points dissapears, it can be everything between 10min to 6 hours between the restarts.

**Server Type (Spigot/Paperspigot/etc): Spigot

**Server Version (using `/ver`): 1.15.1 -R0.1 - Snapshot

**Relevant plugins (Delete if this isn't needed): CMI, JOBS

**Comment by Superola86** [comment]
Also they get points back if they spendet them in the pointshop

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/f1b1ba48e4a24e272aa079f8ad14ded5c6dfcf7a
