### ISSUE TITLE
Creative Pay Option: Not Working

### ISSUE THREAD

**Issue by SteeltonMC** [Zrips/Jobs#679]
***Description of issue:**

Greetings, in the Config, there is an option for enabling/disabling creative pay.

This option seems to be broken. No matter what I set it to, or what permissions I have in place, all users can get exp, money, points for all actions.
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
# Option to allow payment to be made in creative mode. This ignoring when a group has 'jobs.paycreative' permission.
enable-pay-creative: true/false
```

---

**Server Type (Spigot/Paperspigot/etc):** 

Paper

**Server Version (using `/ver`):** 

Build 118

**Comment by montlikadani** [comment]
It's working correctly.

- Make sure the player is not an operator. (Double check /deop)
- Make sure the player have permission `jobs.paycreative`, if have then **negate** that.

```
enable-pay-creative: true/false
```
is not a logic value. Please use only one value.
