### ISSUE TITLE
[Bug Report] User with underscores in his name breaks Sign formatting.

### ISSUE THREAD

**Issue by MrAmos123** [Zrips/Jobs#680]
***Description of issue:***
https://i.imgur.com/Z6kmj34.png

I have a player named `your_FBI_agent7` and on the Sign, for the top list, it doesn't display his name. It just displays `4.`, or his position.

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 1.15.2, Paper 105

**Comment by montlikadani** [comment]
Which version of Jobs? Don't write latest, write the number of your current version.

**Comment by MrAmos123** [comment]
Sorry! 

**Jobs Version:** `4.15.5`

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/41e205691031c723cd057345c28d63aec2496970
