### ISSUE TITLE
[Bug Report] When using /Jobs top <job>, only 3 pages are printed, pages after 3 are not printed. - ★

### ISSUE THREAD

**Issue by geumu** [Zrips/Jobs#681]
**Bukkit**: Paperspigot 1.13.2
**Plugin**: Jobs Reborn 4.15.5
**Bug Severity**: ★
**Explanation**: When using /Jobs top <job>, only 3 pages are printed, pages after 3 are not printed.
**Video**: https://youtu.be/g9GKEg44Quk
**Jobs Config Download**: https://www.upload.ee/files/11197846/Jobs.zip.html
**Additional Notes**: 
I have localized the names of Jobs.
Example) Miner-> 광부

**Comment by montlikadani** [comment]
Is this still reproduce in latest versions (4.15.9)?
