### ISSUE TITLE
Command run when level reach seem not work

### ISSUE THREAD

**Issue by kodkod1612** [Zrips/Jobs#682]
I trying to give player a permission when player reach a level with condition and permissision node , but not work . So i try command , and it still not work .-.

Config: https://pastebin.com/Pu0EA7Vg

---

**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
1.13.2 Lastest
**Relevant plugins (Delete if this isn't needed):**

**Comment by montlikadani** [comment]
Is the player reached the 40 level of job and got something?

**Comment by kodkod1612** [comment]
I use the /job level command to increase player level , the command section should run a command tell player something , but nothing happen

**Comment by montlikadani** [comment]
This works properly with your configuration. You should see that the player is jumping at levels 40 to 100 to receive the command and also check that the player has joined that job.
