### ISSUE TITLE
Bug with "Added bee_nest and beehive as a Collect action"

### ISSUE THREAD

**Issue by DjeyMute** [Zrips/Jobs#687]
Hi,

I have a bug with the "Collect' action for bee nest and beehive.
If a player have a glass bottle he can spam the bee nest or the beehive and even if they are empty it still collects money and experience.

Server : Spigot 1.15.2
Version of Jobs : 4.15.5
Thank's in advance.

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/ab3ea2e77d1ac13f7a34811af7caa974977b5893
