### ISSUE TITLE
Is it possible for a miner to not break LOGS and to a Woodcutter to not break ores ?

### ISSUE THREAD

**Issue by MorenaDaniel** [Zrips/Jobs#69]
Hi ! 

I would like to know if it's possible to restrict some blocks per class, exemple a miner can't break logs but a woodcutter can.

If it's not possible, do you plan to add this functionnality or do you know a plugin that can help me to achieve that ?

**Comment by BlueSoapTurtle** [comment]
What would this be good for?
A guy joins Miner and he cannot break the stuff in Woodcutter job or?

**Comment by Bysokar** [comment]
Exactly.

Might be better to limit this to crafting of higher end tools or something though, So players don't become completely dependant on eachother

**Comment by Zrips** [comment]
Currently no plans for this
