### ISSUE TITLE
PK feature with custom kill

### ISSUE THREAD

**Issue by eaeniko** [Zrips/Jobs#690]
A job group called PK (player kill)
The players cant join this manually.

IF a player kill another player this player enter automaticly in the PK and get a BOUND for being PK. job like a normal job (we can add what we want so this pk can win doing something (more kill, place block, break etc)

but the feature is: 
If any other player with another job Kill this PK player, the player will receive the bound and the PK player resets (he lose his Pk "job") and everything gets normal again.

I was trying to do this with customkill but the documantation is pretty dark in spigot so I dont know if its possible.

**Comment by montlikadani** [comment]
It makes no sense. Namely, if a player kills another player and the killer can automatically join a job, it is not a work order, but a utilization and unnecessary thing. There are other plugins that can do this, but not linked to Jobs. For example, AdvancedAchievements.
