### ISSUE TITLE
Optionally Timer for how long a player can be in a job

### ISSUE THREAD

**Issue by eaeniko** [Zrips/Jobs#691]
Feature a timer a player can be in the job? (optionally)

Like I wanna set when a player join a job they will get fire every X times so I dont need to reset manually everytime with /jobs fireall *.
(I want to do this because I set a Max Jobs players and with this timer all players has the change to join anothe jobs. And I've set a Max Jobs to avoid over player in just one job)

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/91bf7eb93d6e02b7477bad462f1e25cff26fc9c7
