### ISSUE TITLE
/hat duplicates head/skull items when placing them while having a non-head item in your helmet slot

### ISSUE THREAD

**Issue by ylhs403-2019** [Zrips/Jobs#693]
***Description of issue:**
---
When you /hat a non-head item (such as a sapling) and you place a head item (or skull) on the ground, it removes the non-head item you used /hat on from your helmet slot and replaces it with the head item you placed, effectively duplicating the head item- the one on the ground and the one in your helmet slot both stay.

**Server Type (Spigot/Paperspigot/etc):** 
Paper 122

**Server Version (using `/ver`):** 
1.15.2

**Relevant plugins (Delete if this isn't needed):**
CMI

**Comment by montlikadani** [comment]
Is this jobs related?
