### ISSUE TITLE
[Question] + [Sugestions] Farmer job

### ISSUE THREAD

**Issue by NikolaiCinotti** [Zrips/Jobs#694]
How can I make a farmer job?

I mean, if a player place the carrot/potato/wheat seed in a farmlan to grow the "place"doesnt work.

I though if a put a  "break block" when it is already growed then they need to "break" the potato to take and win the xp/$

but there inst any id/name for this growed plants.

How can I make something to make this farmer job?

And if theres no other way... well this can be a recomendation to create a feature or improve the  "place" for this kind of item that is not a block but can be put in a farmland for example.

**Comment by montlikadani** [comment]
It is not a job to get money for plant growth. You need to work on that. To make money, you must place it or break it at a given level specified in the Place action.
```
Place:
  wheat_seeds:
    income: 0.3
Break:
  wheat-7:
    income: 1.0
    points: 1.0
  carrots-7:
    income: 1.0
    experience: 1.0
```
Levels 1-7 differ. 7 is the total level of cultivated plants that are on the soil. If you set it to less then you will only get rewarded at that level.

**Comment by NikolaiCinotti** [comment]
So with Break:
when the carrots-7 are all growed when the player break he will receive the income and xp? all cultivated plants has 7 levels?

**Comment by NikolaiCinotti** [comment]
So the 
`Place:
  wheat_seeds:
    income: 0.3`

Doesnt work. 
Im gonna try to break with this levels. all plants has this 7 levels?

**Comment by NikolaiCinotti** [comment]
So..
None food with place work.
and for Break some works some not with the level -7
This is my code.
Can you check and tell me/explain?

`Place:
      wheat_seeds:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
      potato:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
      carrot:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
    Break:
      wheat-7:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
      potatos-7:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
      carrots-7:
        income: 0.0005
        points: 0.00010
        experience: 0.00010`

**Comment by NikolaiCinotti** [comment]
![image](https://user-images.githubusercontent.com/20131062/76470434-e2573400-63ce-11ea-9a7f-de6f0a217b1c.png)
Place food doesnt work as a block.

**Comment by NikolaiCinotti** [comment]
So... I use the /jobs blockinfo to get the name, and for wheat_seeds its just wheat. why? (Now it works)
The name base I've use is from https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

**Comment by montlikadani** [comment]
Instead of `wheat_seeds` you need to use only `wheat` for Place action.
Correct values:
```
wheat:
   income: 1
   experience: 1
potatoes:
   income: 1
carrots:
   income: 1
   experience: 1
```
