### ISSUE TITLE
After restarting mysql data is gone.

### ISSUE THREAD

**Issue by Walabise** [Zrips/Jobs#696]
Hello,

Yes, let me explain. I can go from SQLITE -> MySQL.
I enter my SQL information in the file. I'm doing a / reload jobs.
Then I do a /jobs convert in the console. No error, I restart the server. I check that in storage it is SQL. And the plugin goes back to 0 when I connect and I order /jobs stats or /jobs archive
> https://prnt.sc/rj2lvb
> https://prnt.sc/rj2p2v
After restart > https://prnt.sc/rj2q2s
My SQL data is no longer recognized but no error

> PaperSpigot

> Paper 1.15.2

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/647533f57a365bdc1805f31a3f568d1c9df9ef37
