### ISSUE TITLE
Minus experience in job

### ISSUE THREAD

**Issue by Johandrex** [Zrips/Jobs#70]
Hello, one of my players are having minus experience in his hunter job. I'm unable to fix this since I can't edit the SQL database, there's neither any commands you can use to give a player experience in a specific job. I've attempted to give him one level in the hunter job, but didn't seem to fix it. Kindly add a command which gives me the possibility to set/add experience in a players job.

Version: Jobs 3.8.2
Spigot: git-Spigot-d4f98a3-4448a7e (MC: 1.11.2)
Preview of his stats: https://imgur.com/a/XiJoP

**Comment by Zrips** [comment]
Will be added with next build
