### ISSUE TITLE
Help : my brewing stands aren't assigned anymore

### ISSUE THREAD

**Issue by Elric02** [Zrips/Jobs#702]
***Description of issue:**

When I click on a brewing stand, it doesn't give me ownership, even if this functionnality is activated, because it's working fine for furnace.
And as brewing stands aren't assigned, I gain no money for brewing potions anymore. Could anyone help ?

---

**Server Version (using `/ver`):** 
PaperSpigot 1.15.2 version 143
Using Jobs 4.15.5

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/issues/661
