### ISSUE TITLE
When a player leave the job the slot is not released for someone else to enter

### ISSUE THREAD

**Issue by eaeniko** [Zrips/Jobs#704]
I've put the job miner 10 slots, so only 10 can join,
They can enter in the job with a custom gui with the /jobs join [jobname] command to confirm the job and the jobs leave [name] to leave the job.

The problem is: Seems when the player leave the job the slot doesnt free a espace. So only 2 players has enterer 5 times each and then the jobs with 10 slots are full and nobody can join again even they

And everyone get the "the jobs is full text" no error, no console, nothing show.

Any Ideia?

**Comment by montlikadani** [comment]
Send some screenshots in game that shows as 10 slots full.

**Comment by NikolaiCinotti** [comment]
Where? The mysql?

**Comment by montlikadani** [comment]
> in game

**Comment by NikolaiCinotti** [comment]
Ok will. Dont close the issue xD

**Comment by montlikadani** [comment]
It works as it should. Maybe you have some delay in the database when a player joins multiple times to a job or your server overloaded by something.
