### ISSUE TITLE
Server thread/INFO Error: You can only use that command in game

### ISSUE THREAD

**Issue by NikolaiCinotti** [Zrips/Jobs#705]
So, I use a custom gui to players join and leave a jobs with right click without need to type any command. When they confirm the button 2 command are trigger: /jobs join jobsname and a temp group inside luckperms.

The player get the job, and almost always works, but in the console show this error:

![image](https://user-images.githubusercontent.com/20131062/77409232-a5f4e200-6d97-11ea-8fa2-9cf13d171399.png)

But in chat it seems all fine, the player has enter in the job and the spy ping me with the console temp perm.
![image](https://user-images.githubusercontent.com/20131062/77408363-5d88f480-6d96-11ea-9631-56fdccfc476a.png)

If I try to double check, the response is  Im in the job. 
![image](https://user-images.githubusercontent.com/20131062/77409306-c9b82800-6d97-11ea-80d7-206b26b77da3.png)

I think this can be a reason to my another issue I've post before this.

**Comment by montlikadani** [comment]
Check for other plugins that executing commands and make sure you don't have any commands in jobConfig file where `Terraplanagem` job `join-commands` are.

**Comment by Zrips** [comment]
@NikolaiCinotti 
Feedback message doesn't match anything found in Jobs plugin and as a player gets his desired job this would mean that this error message originates from another plugin and not from jobs.
