### ISSUE TITLE
[Bug] Error command /Gtop

### ISSUE THREAD

**Issue by Silverfabien** [Zrips/Jobs#706]
Hi, (sorry about my English),

The command "/jobs gtop" no longer works since the last update, for info the plugin is connected to bdd with Mysql.

Here is the result on minecraft and console 
https://hastebin.com/esoyovunup.shell
![2020-03-25_00 20 41](https://user-images.githubusercontent.com/29354438/77487580-1f8dde00-6e33-11ea-8f28-fcb261254192.png)

**Server :** Spigot 1.15.2
**Version :** 4.15.5 

Thank's in advance.

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/issues/678
