### ISSUE TITLE
Jobs per world option in jobConfig.yml

### ISSUE THREAD

**Issue by Resi23** [Zrips/Jobs#708]
Last time I think we talked past each other. I would think it would be great if there was a blacklist for locked worlds in the jobConfig.yml not in generalConfig.yml. So that I can, for example, allow the farmer job in a "plotworld". The miner only in the "farmworld". The current solution in generalConfig.yml blocks all jobs and commands in this world.

For Example:

  Miner:
    fullname: Miner
    shortname: Mi
    description: Mining minerals and ores.
    ChatColour: DARK_GRAY
    chat-display: shortjob
    world-blacklist: 
      - plotworld
      - teamworld

I hope to have formulated it more clearly this time :)

**Comment by Zrips** [comment]
843b07b1768b8600056d94ab9291b5e4413f49e7
