### ISSUE TITLE
A lot of blocks doesnt work.

### ISSUE THREAD

**Issue by NikolaiCinotti** [Zrips/Jobs#709]
All ore blocks doesnt work with break or smelt. a ton of other blocks too doesnt work.
no error in chat, no console. anything, just dont show anything.
I've sent a lot of print in your discord if you wanna see.

and block smooth_stone that the usage is smooth_stone-8 doesnt work too, and if you try put the original name, it trow exeception in console and "income NaN xp NaN" etc in mc.

some of the conversation with mont

 here https://cdn.discordapp.com/attachments/526402919826849804/692347409379885066/unknown.png

my job config, the comment line are some of the block I've test and doesnt work, like the iron ore = iron bars

I wont test every block because its not my job (I've test 10/15 diffrente blocks with the original name and the usage nem ~if they are dif~), but cleary theres more block with the same issue.

https://hastebin.com/bijojemafu.bash log

**Comment by Zrips** [comment]
Its not your job to test all blocks, but it would be yours to atleast provide server version... Block names have changed over the years and it might depend on your server version. Next, would be nice to actually have your jobCongif file or atleast a particular job just to be on same page and have same exact example what dint worked for you so we can test at our end. 
And last thing, there no such thing as smooth_stone-8, what this should even represent? Slab? If so then use smooth_stone_slab just like https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html lists them. If material which is listed at this page doesnt work for you, then report it.

**Comment by NikolaiCinotti** [comment]
Heres de file 
[jobconfig.txt](https://github.com/Zrips/Jobs/files/4383546/jobconfig.txt)

about the smooth_stone-8 is what mont said to use with /jobs blockinfo, lol. Theres 2 names with blockinfo the original name withou the -8 and the usage with -8
