### ISSUE TITLE
Jobs MythicMobs version check bug (newest MM version is too old?)

### ISSUE THREAD

**Issue by PsychoLynx** [Zrips/Jobs#71]
Hey! Using the lates MythicMobs dev build (4.1.0 b#2014) with Jobs gives this message on startup:

[Server thread/INFO]: [0;33;1m[Jobs] [0;33;22mMythicMobs was found - [0;31;1mBut your version is outdated, please update for full support.[m

Not sure if it messes with the gameplay, but it's a bug nonetheless.

**Comment by Zrips** [comment]
Well they have jumped from 2.x to 4.x... And entire API have changed because of that. Will have to remake part of code and add backwards compatibility.
