### ISSUE TITLE
Only baby version off ALL zombie type give rewards

### ISSUE THREAD

**Issue by zephirox58** [Zrips/Jobs#710]
hello =) 

Only baby version off ALL zombie type give rewards

Plugin version 4.15.5
Serveur version 1.15.2

My hunter config :

https://pastebin.com/1NkC2caQ

**Comment by montlikadani** [comment]
> 1.115.2

This is not a valid server version number. Please correct it.

**Comment by zephirox58** [comment]
it's done

**Comment by montlikadani** [comment]
This works correctly. You should delete the TranslatableWords file and re-create a new with /jobs reload command. Also ZombieVillager should be `Zombie_Villager`
