### ISSUE TITLE
BAKE Job Action only registering one campfire

### ISSUE THREAD

**Issue by Csoii** [Zrips/Jobs#711]
**Description of issue:**

**Video showing issue:** [https://youtu.be/yivC_x53qeA](url)
The BAKE job action only registers one campfire. On the server, cooking porkchops give the player $0.62 & 0.45xp at Level One. However, as you can see in the video, it registers perfectly for one campfire but not the other.
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
[https://pastebin.com/dS824EZr](url)

---

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot

**Server Version (using `/ver`):** Paper version git-Paper-122 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Jobs Version:** 4.15.5

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/9e006ebe8911aa53987f6a959c0ed6de0213c9bd
