### ISSUE TITLE
A random job stops working when you do /jobs reload

### ISSUE THREAD

**Issue by FeroxDrood** [Zrips/Jobs#712]
When you do /jobs reload a random job will stop working.

**Comment by montlikadani** [comment]
Send more information like jobconfig, what database are you using, jobs version and console log.

**Comment by FeroxDrood** [comment]
> Send more information like jobconfig, what database are you using, jobs version and console log.

Version 4.15.6
Jobsconfig https://pastebin.com/6jwhaU3E

Database: MYSQL

**Comment by FeroxDrood** [comment]
Also heres job console on server startup https://pastebin.com/1u0zAyFt

**Comment by montlikadani** [comment]
Can't reproduce, every job works correctly with mysql database. Maybe you have some issues in your database, check it.

**Comment by FeroxDrood** [comment]
hmm well it only started happening as of the latest update and I was only 1 version behind so i guess ill just try revert back to the previous version.
