### ISSUE TITLE
EntityDeathEvent - Error in console

### ISSUE THREAD

**Issue by pvvvo** [Zrips/Jobs#717]
**Description of issue: Error in console**

 https://pastebin.com/8GeCXNDk

**Server Type (Spigot/Paperspigot/etc): Tuinity** 

**Server Version (using `/ver`): git-Tuinity-"84d7587" (1.15.2)**

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/53824f18513fee477f71fd4b4fdc52be4063a3d7
