### ISSUE TITLE
Wrong payment even with Dynamic and taxes off

### ISSUE THREAD

**Issue by eaeniko** [Zrips/Jobs#719]
This is wrong
![image](https://user-images.githubusercontent.com/20131062/77808955-5a2e8b00-706c-11ea-8c03-1e9d185f90c7.png)

This is the correct
![image](https://user-images.githubusercontent.com/20131062/77808962-5ef33f00-706c-11ea-9e6c-bfc711a0cce4.png)

This is what I gain
![image](https://user-images.githubusercontent.com/20131062/77808997-8b0ec000-706c-11ea-9a45-08059badcadc.png)

This is what I gain if I've 2 jobs, the first has a break dirt, the second dont. So this decrease should't happen. 
![image](https://user-images.githubusercontent.com/20131062/77809040-bdb8b880-706c-11ea-92e7-93ba133aed7f.png)
Plus, if both jobs has the same break block gain, the gain should be 2x more. Like (0.005 x 2). 0.005 for 1 job + 0.005 for the other job

**Comment by Zrips** [comment]
We will nead to have your income-progression-equation as it can and by default contains variable which will lower income depending on how many jobs you have.

**Comment by montlikadani** [comment]
Closing due to there is no response.
