### ISSUE TITLE
COCOA-4 does not work

### ISSUE THREAD

**Issue by LemonLight** [Zrips/Jobs#72]
Hi,

I have got a problem on my server with jobs farmer. My players told me that cocoa doesn't work.
So I tried and when cocoa has grown to its maximum I don't earn money or xp. 
Here there is the config : 
      COCOA-4:
        income: 0.1
        points: 4
        experience: 4.0

Many thanks for help

**Comment by Zrips** [comment]
Its should be cocoa-2 which determines its stage from 0 to 2 when 2 is fully grown
