### ISSUE TITLE
Reward for Taming

### ISSUE THREAD

**Issue by BackWheel** [Zrips/Jobs#721]
I tried to tame the animals, but I didn't get any reward after I tame them. The server version I use is Paper-146 and the plugin version is 4.15.6.

**Comment by BackWheel** [comment]
This is the plugin I am using: BlockLocker, BookShelf, Brewery, ChestSort, CMI, CoreProtect, CoreProtectTNT, FastAsyncWorldEdit, FKeyCommand *, Graves, HackedCore *, HackedServer *, IllegalStack, InfiniteScoreboard, InventoryRollback, Jobs, JukeBox, LiquidTanks, Luck MobFarmManager, MoreVaultPlus, NoBoom, NoteBlockAPI, PL-Hide, PlaceholderAPI, ProCosmetics, ProtocolLib, PublicCrafters, QuickShop, SurvivalPlus, TrMenu, Vault, WorldEdit

**Comment by BackWheel** [comment]
`Tame:
      Wolf:
        income: 1
        points: 1
        experience: 1
      Horse:
        income: 2
        points: 2
        experience: 2
      Parrot:
        income: 2
        points: 2
        experience: 2
      Ocelot:
        income: 2.5
        points: 2.5
        experience: 2.5
      Llama:
        income: 2
        points: 2
        experience: 2`

This is the configuration content

**Comment by montlikadani** [comment]
Send more informations like jobConfig file, and console log.

**Comment by Zrips** [comment]
d1d467bc0d77c12294ee84e562c6285ec274e2f9
