### ISSUE TITLE
Toplist Job Signs Showing 0

### ISSUE THREAD

**Issue by BoosterBots** [Zrips/Jobs#723]
***Description of issue:**
Having some issues with the latest update. My Toplist job signs have always tracked and worked fine until I did the latest update. Now signs keep bugging out and saying the players have 0 level.

When I remove the signs then make new ones its fixed for a little while then back to 0

Here is a screen shot: http://prntscr.com/roxjrm

Edit: I just noticed this error in console today as well.
`30.03 00:34:34 [Server] WARN java.lang.NullPointerException
30.03 00:34:34 [Server] WARN at com.Zrips.CMI.Modules.Economy.EconomyManager.getBalTopMap(EconomyManager.java:267)
30.03 00:34:34 [Server] WARN at com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1056)
30.03 00:34:34 [Server] WARN at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:546)
30.03 00:34:34 [Server] WARN at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:508)
30.03 00:34:34 [Server] WARN at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:470)
30.03 00:34:34 [Server] WARN at com.Zrips.CMI.Modules.Holograms.CMIHologram$1.run(CMIHologram.java:654)
30.03 00:34:34 [Server] WARN at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
30.03 00:34:34 [Server] WARN at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
30.03 00:34:34 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
30.03 00:34:34 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
30.03 00:34:34 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
30.03 00:34:34 [Server] WARN at java.lang.Thread.run(Thread.java:748)`

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
git-Paper-146 (1.15.2)

**Plugin Version**
Jobs Reborn 4.15.6

**Comment by Zrips** [comment]
823f89707dc6ffdc016bda490faa86f0e19afd80
