### ISSUE TITLE
Server taking very long to load

### ISSUE THREAD

**Issue by Elric02** [Zrips/Jobs#724]
***Description of issue:**

I just upgraded from 4.15.5 to 4.15.6, and everytime I start the server loading gets stuck a few minutes on this : 
```
>.... [22:26:31 INFO]: [Jobs] Started database save task.
>.... [22:26:31 INFO]: [Jobs] Started buffered payment thread.
```
It's actually taking 4 minutes when it was taking a few seconds on 4.15.5. I didn't make any change in the configs.
I'm considering going back to 4.15.5.

**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot

**Server Version (using `/ver`):** 
Paper Version 155

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/issues/720
