### ISSUE TITLE
Started buffered payment thread.

### ISSUE THREAD

**Issue by XxPoNaGeXx** [Zrips/Jobs#726]
Paper MC versio: 155
Jobs Version: 4.15.6
MC 1.15.2

Starting server and the start up stops:

01.04 19:12:38 [Server] INFO [Jobs] Enabling Jobs v4.15.6
01.04 19:12:38 [Server] INFO [Jobs] PlaceholderAPI hooked.
01.04 19:12:38 [Server] INFO PlaceholderAPI was found - Enabling capabilities.
01.04 19:12:44 [Server] INFO [Jobs] Loaded 8 titles!
01.04 19:12:44 [Server] INFO [Jobs] Loaded 75 protected blocks timers!
01.04 19:12:44 [Server] INFO [Jobs] Loaded 995 custom item names!
01.04 19:12:44 [Server] INFO [Jobs] Loaded 67 custom entity names!
01.04 19:12:44 [Server] INFO [Jobs] Loaded 2 custom MythicMobs names!
01.04 19:12:44 [Server] INFO [Jobs] Loaded 37 custom enchant names!
01.04 19:12:44 [Server] INFO [Jobs] Loaded 16 custom color names!
01.04 19:12:44 [Server] INFO [Jobs] Loaded 4 shop items!
01.04 19:12:44 [Server] INFO [Jobs] Loaded 1 quests for Woodcutter
01.04 19:12:44 [Server] INFO [Jobs] Loaded 1 quests for Miner
01.04 19:12:44 [Server] INFO [Jobs] Loaded 1 quests for Builder
01.04 19:12:44 [Server] INFO [Jobs] Loaded 1 quests for Digger
01.04 19:12:44 [Server] INFO [Jobs] Loaded 1 quests for Farmer
01.04 19:12:44 [Server] INFO [Jobs] Loaded 1 quests for Hunter
01.04 19:12:44 [Server] INFO [Jobs] Loaded 1 quests for Explorer
01.04 19:12:44 [Server] INFO [Jobs] Loaded 1 quests for Crafter
01.04 19:12:44 [Server] INFO [Jobs] Loaded 1 quests for Fisherman
01.04 19:12:44 [Server] INFO [Jobs] Loaded 1 quests for Weaponsmith
01.04 19:12:44 [Server] INFO [Jobs] Loaded 1 quests for Brewer
01.04 19:12:44 [Server] INFO [Jobs] Loaded 1 quests for Enchanter
01.04 19:12:44 [Server] INFO [Jobs] Loaded 12 jobs!
01.04 19:12:44 [Server] INFO [Jobs] Explorer job manager registered!
01.04 19:12:44 [Server] INFO [Jobs] Loaded 439 furnaces and 89 brewing stands for reassigning.
01.04 19:12:44 [Server] INFO [Jobs] Started database save task.
01.04 19:12:44 [Server] INFO [Jobs] Started buffered payment thread.

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/issues/724
