### ISSUE TITLE
Quest same material issue

### ISSUE THREAD

**Issue by Bedah95** [Zrips/Jobs#727]
If you use the same material name multiple times in the quest, only the last one will be used.

#####################################
Jobconfig: 
    Quests:
      'quest-name':
        Name: Stone
        Objectives:
        - Break;STONE;3500                             #ignored
        - Smelt;STONE;3500                                
        RewardCommands: ....
#####################################

Server Type (Spigot/Paperspigot/etc):
Paper

Server Version (using /ver):
git-Paper-155 (1.15.2)

Plugin Version
Jobs Reborn 4.15.6

**Comment by Zrips** [comment]
891bca964a1524e4f1385b5240c22f29393357ee
