### ISSUE TITLE
Cow milk bucket

### ISSUE THREAD

**Issue by Bricec6** [Zrips/Jobs#728]
***Description of issue:**
Hello, any player taking the cow milk sends him a message that has to wait x seconds before being paid, except that this milk recovery system I put them only to the farmer and not to the other trades.Hello, any player taking the cow milk sends him a message that has to wait x seconds before being paid, except that this milk recovery system I put them only to the farmer and not to the other jobs
https://cdn.discordapp.com/attachments/692673447704133663/694869775918301204/unknown.png
**

---

**Server Type (Spigot/Paperspigot/etc): paper** 

**Server Version (using `/ver`): This server is running Paper version git-Paper-146 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
**

**Comment by montlikadani** [comment]
What version of Jobs are you using?

**Comment by Bricec6** [comment]
Jobs Reborn 4.15.7

**Comment by montlikadani** [comment]
Fixed in that commit ^
