### ISSUE TITLE
Permissions Jobs

### ISSUE THREAD

**Issue by istarengwa** [Zrips/Jobs#730]
Hello, I have a problem, when I restart my server, the config jobs modifies it alone, and this no longer gives the right permissions to players.

before restart :  
https://image.noelshack.com/fichiers/2020/14/5/1585909972-avant.png

after restart : 
https://image.noelshack.com/fichiers/2020/14/5/1585909984-restart.png

Minecraft Paper-Spigot 1.15.2 / Jobs 4.15.7

**Comment by montlikadani** [comment]
You should use `_` instead of dots `.`

YamlConfigurations have this issue when saving with dots, so its probably can't fix this.

**Comment by istarengwa** [comment]
I just tried, it keeps my configuration after the restart, but the permission does not work

**Comment by montlikadani** [comment]
Got fixed with this [commit](https://github.com/Zrips/Jobs/commit/297a89126d3961f147077762f3044b014941a708)
