### ISSUE TITLE
Add multiple pages to /jobs browse

### ISSUE THREAD

**Issue by Gorderok** [Zrips/Jobs#734]
![job](https://user-images.githubusercontent.com/43994828/78465933-f3f4d880-76fb-11ea-9b71-f198224833d3.png)

You must add the   ##possibility of having multiple pages for a job in the / jobs browse

**Comment by montlikadani** [comment]
https://imgur.com/a/JIkID9S

**Comment by Gorderok** [comment]
Great !

**Comment by Gorderok** [comment]
It is fixed but there is not everything to display in the menu despite the 2 pages.

![2020-07-07_19 09 55](https://user-images.githubusercontent.com/43994828/87252284-022c6080-c472-11ea-9e00-5519f4c17322.png)

**Comment by Gorderok** [comment]
The problem is still not fixed..
