### ISSUE TITLE
CRAFT reward for Tipped_Arrow don't work

### ISSUE THREAD

**Issue by Futurixel** [Zrips/Jobs#735]
***Description of issue:** CRAFT action not working for tipped_arrow
---

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot 

**Server Version (using `/ver`):** git-Paper-162 (MC: 1.15.2)

**Jobs version used:** 4.15.7

**Comment by montlikadani** [comment]
This is a suggestion: https://github.com/Zrips/Jobs/issues/732
