### ISSUE TITLE
 BREED action for Turtle don't work

### ISSUE THREAD

**Issue by Futurixel** [Zrips/Jobs#736]
***Description of issue:** BREED action for Turtle is not working

Server Type (Spigot/Paperspigot/etc): PaperSpigot

Server Version (using /ver): git-Paper-162 (MC: 1.15.2)

Jobs version used: 4.15.7

**Comment by montlikadani** [comment]
For me works correctly. Send here the breed section from jobConfig and paste to a code block.

**Comment by Futurixel** [comment]
All others breed work correclty for me but not for turtle 
`    Breed:
      Wolf:
        income: 0.78
        points: 0
        experience: 2.86
      Ocelot:
        income: 0.78
        points: 0
        experience: 2.86
      Pig:
        income: 0.78
        points: 0
        experience: 2.86
      Cow:
        income: 0.78
        points: 0
        experience: 2.86
      Horse:
        income: 0.78
        points: 0
        experience: 2.86
      Rabbit:
        income: 0.78
        points: 0
        experience: 2.86
      Sheep:
        income: 0.78
        points: 0
        experience: 2.86
      Chicken:
        income: 0.78
        points: 0
        experience: 2.86
      Llama:
        income: 0.78
        points: 0
        experience: 2.86
      turtle:
        income: 0.78
        points: 0
        experience: 2.86`

**Comment by Zrips** [comment]
@Futurixel 
Because its based on turtle hatching from eggs and not on turtles actually laying eggs. You will need to way, for quite a bit before they hatch and you will get your payment.
