### ISSUE TITLE
BossBarColour

### ISSUE THREAD

**Issue by Bricec6** [Zrips/Jobs#741]
***Description of issue:**
If you want to change the color of the bossbar it doesn't work.
---

![image](https://user-images.githubusercontent.com/51750055/79014543-68e86800-7b6b-11ea-9958-6d4aabac67d5.png)

![image](https://user-images.githubusercontent.com/51750055/79014605-861d3680-7b6b-11ea-9491-bb9bce7b685e.png)

#####################################
#####################################
```
  Mineur:
    fullname: Mineur
    shortname: Min
    description: Récoltez du minerais/blocs!
    ChatColour: BLUE
    BossBarColour: GRAY
    chat-display: full
    max-level: 500
---

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):**  Paper-164 (1.15.2)

Jobs Reborn 4.15.7

**Comment by montlikadani** [comment]
There is no bossbar color by `GRAY`
see https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarColor.html
