### ISSUE TITLE
EnabledByDefault

### ISSUE THREAD

**Issue by Bricec6** [Zrips/Jobs#742]
***Description of issue:**
I'd like to put 
EnabledByDefault: true

in false so that my players don't display it by default, but use the /jobs toggle bossbar command themselves to enable it, except that when I set it: EnabledByDefault: false, the bossbar will no longer display for everyone.
---
EnabledByDefault: true

![image](https://user-images.githubusercontent.com/51750055/79014783-e57b4680-7b6b-11ea-8ab6-e787d998f080.png)

![image](https://user-images.githubusercontent.com/51750055/79014816-f3c96280-7b6b-11ea-83d1-42ea0468c4ce.png)

![image](https://user-images.githubusercontent.com/51750055/79014834-fdeb6100-7b6b-11ea-859b-a571d5d31a71.png)

IF EnabledByDefault: false

![image](https://user-images.githubusercontent.com/51750055/79014873-0f346d80-7b6c-11ea-8424-8c48516f03da.png)

![image](https://user-images.githubusercontent.com/51750055/79014887-16f41200-7b6c-11ea-93da-2078a0903f9e.png)

![image](https://user-images.githubusercontent.com/51750055/79014915-21aea700-7b6c-11ea-8c27-0b4b48e99eb4.png)

![image](https://user-images.githubusercontent.com/51750055/79014931-2a9f7880-7b6c-11ea-8187-d2dde4bf917a.png)

---

**Server Type (Spigot/Paperspigot/etc):** paper

**Server Version (using `/ver`):** Paper-164 (1.15.2)

Jobs Reborn 4.15.7

**Comment by montlikadani** [comment]
Yes, because the `EnabledByDefault` disables fully the bossbar.

**Comment by Bricec6** [comment]
Ok so no need to put Enable: true ... wtf
