### ISSUE TITLE
Jobs being disabled by CMI enchantment?

### ISSUE THREAD

**Issue by GothkittyGirl** [Zrips/Jobs#743]
***Description of issue:**

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```

https://pastebin.com/97di6qNi 
https://pastebin.com/D11pgEwZ

```

---

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):**  1.15.2

**Relevant plugins (Delete if this isn't needed):** CMI

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/58b045f5e3b2772b62e4ca5f2bd72d741db0cc5f

**Comment by GothkittyGirl** [comment]
why close this its not fixed..... and i dont know how to add that to the thing :/
