### ISSUE TITLE
Not resolved> CMI enchantment issue

### ISSUE THREAD

**Issue by GothkittyGirl** [Zrips/Jobs#744]
***Description of issue:**
No idea what your meant to do with this > https://github.com/Zrips/Jobs/commit/58b045f5e3b2772b62e4ca5f2bd72d741db0cc5f

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://pastebin.com/97di6qNi 
https://pastebin.com/D11pgEwZ
```

---

**Server Type (Spigot/Paperspigot/etc):**  Spigot

**Server Version (using `/ver`):** 1.15.2

**Relevant plugins (Delete if this isn't needed):** CMI

**Comment by montlikadani** [comment]
If you see that commit, that means it is fixed and it will be released as soon as we have time.
