### ISSUE TITLE
Ore don't give money when moved by piston

### ISSUE THREAD

**Issue by PoulpinSky** [Zrips/Jobs#747]
***Description of issue:**
When you move some ore with pistons, you recieve no money with miner job.

---

**Server Type (Spigot/Paperspigot/etc):** Papier 1.12.2

**Server Version (using `/ver`):** git-Paper-1618 (MC: 1.12.2)

**Relevant plugins (Delete if this isn't needed):** Jobs reborn

**Comment by montlikadani** [comment]
Check in the restrictedBlocks file and find ores. Make sure the values are removed or setting to -1

**Comment by PoulpinSky** [comment]
I’ve already defined all ores at -1, i try to remove them too but nothing change

**Comment by montlikadani** [comment]
If you disable the `PlaceAndBreakProtection` option in generalConfig will works.

**Comment by PoulpinSky** [comment]
Thanks, it will be fixed soon?

**Comment by Zrips** [comment]
4198a28967bb38e1705bfa703ddb78ce60400fbb
