### ISSUE TITLE
Question: How to turn of the update notification?

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/Jobs#751]
How can I turn off the update message that appears after a join? Normally it is quite useful, but if you use the github releases, there will be no more proper synchronization (${project.version}) and it will end up in spam. For this reason I would like to turn it off :D

**Comment by montlikadani** [comment]
Find `Optimizations.NewVersion` in genealConfig.

**Comment by TheoRetisch1** [comment]
Thank you very much :)
