### ISSUE TITLE
how is that not a jobs problem?

### ISSUE THREAD

**Issue by unholymac** [Zrips/Jobs#754]
I can spawn that item on Minecraft I just can't get it to execute through jobsconfig I'm guessing because the colons are messing up the config file

**Comment by montlikadani** [comment]
You have misconfigured the whole command. You should put the command to a string type.
Check it with this: https://codebeautify.org/yaml-validator

**Comment by unholymac** [comment]
im not sure how to do this? I've never had to do this before

**Comment by unholymac** [comment]
How do i create it into a string type?  it says


Error : Unexpected characters near ", Lore:['{"text":"Rewarded for reaching level 120 in Slayer!", "italic": false, "color": "dark_red"}']},AttributeModifiers:[{AttributeName:generic.luck,Amount:5,Operation:0,UUIDLeast:110483600,UUIDMost:99,Slot:offhand,Name:generic.luck},{AttributeName:generic.armorToughness,Amount:1,Operation:0,UUIDLeast:110483700,UUIDMost:99,Slot:offhand,Name:generic.armorToughness},{AttributeName:generic.maxHealth,Amount:2,Operation:0,UUIDLeast:110483800,UUIDMost:99,Slot:offhand,Name:generic.maxHealth},{AttributeName:generic.attackSpeed,Amount:0.1,Operation:2,UUIDLeast:110483900,UUIDMost:99,Slot:offhand,Name:generic.attackSpeed}]}".
Line : 1  minecraft:give unholymac minecraft:rabbit_hide{CustomModelData:109, display:{Name: '[{"text": "Slayer ", "italic": false, "color": "dark_red"}, {"text": "Cape", "italic": false,  "color": "dark_gray"}]', Lore:['{"text":"Rewarded for reaching level 120 in Slayer!", "italic": false, "color": "dark_red"}']},AttributeModifiers:[{AttributeName:generic.luck,Amount:5,Operation:0,UUIDLeast:110483600,UUIDMost:99,Slot:offhand,Name:generic.luck},{AttributeName:generic.armorToughness,Amount:1,Operation:0,UUIDLeast:110483700,UUIDMost:99,Slot:offhand,Name:generic.armorToughness},{AttributeName:generic.maxHealth,Amount:2,Operation:0,UUIDLeast:110483800,UUIDMost:99,Slot:offhand,Name:generic.maxHealth},{AttributeName:generic.attackSpeed,Amount:0.1,Operation:2,UUIDLeast:110483900,UUIDMost:99,Slot:offhand,Name:generic.attackSpeed}]}

**Comment by unholymac** [comment]
is this ticket still open or do I need to make another? its been 5 days since I've had a reply which has not fixed my issue :(

**Comment by Nuolong** [comment]
montlikadani is saying that you need to put the command to a string type, so surround your command with single quotes. ' '

**Comment by unholymac** [comment]
im really not sure what that means tho? he send me a link but I don't know what to do with it

**Comment by unholymac** [comment]
i put ' infront and at end of command and it still comes up with a error

**Comment by Nuolong** [comment]
Did you surround the entire command with the single quotes? He gave you the link so you can check your code. Copy paste your code into that site and it will tell you what may be wrong with what you're doing.

**Comment by unholymac** [comment]
'minecraft:give unholymac minecraft:rabbit_hide{CustomModelData:109, display:{Name: '[{"text": "Slayer ", "italic": false, "color": "dark_red"}, {"text": "Cape", "italic": false,  "color": "dark_gray"}]', Lore:['{"text":"Rewarded for reaching level 120 in Slayer!", "italic": false, "color": "dark_red"}']},AttributeModifiers:[{AttributeName:generic.luck,Amount:5,Operation:0,UUIDLeast:110483600,UUIDMost:99,Slot:offhand,Name:generic.luck},{AttributeName:generic.armorToughness,Amount:1,Operation:0,UUIDLeast:110483700,UUIDMost:99,Slot:offhand,Name:generic.armorToughness},{AttributeName:generic.maxHealth,Amount:2,Operation:0,UUIDLeast:110483800,UUIDMost:99,Slot:offhand,Name:generic.maxHealth},{AttributeName:generic.attackSpeed,Amount:0.1,Operation:2,UUIDLeast:110483900,UUIDMost:99,Slot:offhand,Name:generic.attackSpeed}]}'

**Comment by unholymac** [comment]
i clicked validate and it gave me this error

Error : Unexpected characters near "[{"text": "Slayer ", "italic": false, "color": "dark_red"}, {"text": "Cape", "italic": false,  "color": "dark_gray"}]', Lore:['{"text":"Rewarded for reaching level 120 in Slayer!", "italic": false, "color": "dark_red"}']},AttributeModifiers:[{AttributeName:generic.luck,Amount:5,Operation:0,UUIDLeast:110483600,UUIDMost:99,Slot:offhand,Name:generic.luck},{AttributeName:generic.armorToughness,Amount:1,Operation:0,UUIDLeast:110483700,UUIDMost:99,Slot:offhand,Name:generic.armorToughness},{AttributeName:generic.maxHealth,Amount:2,Operation:0,UUIDLeast:110483800,UUIDMost:99,Slot:offhand,Name:generic.maxHealth},{AttributeName:generic.attackSpeed,Amount:0.1,Operation:2,UUIDLeast:110483900,UUIDMost:99,Slot:offhand,Name:generic.attackSpeed}]}'".
Line : 1  'minecraft:give unholymac minecraft:rabbit_hide{CustomModelData:109, display:{Name: '[{"text": "Slayer ", "italic": false, "color": "dark_red"}, {"text": "Cape", "italic": false,  "color": "dark_gray"}]', Lore:['{"text":"Rewarded for reaching level 120 in Slayer!", "italic": false, "color": "dark_red"}']},AttributeModifiers:[{AttributeName:generic.luck,Amount:5,Operation:0,UUIDLeast:110483600,UUIDMost:99,Slot:offhand,Name:generic.luck},{AttributeName:generic.armorToughness,Amount:1,Operation:0,UUIDLeast:110483700,UUIDMost:99,Slot:offhand,Name:generic.armorToughness},{AttributeName:generic.maxHealth,Amount:2,Operation:0,UUIDLeast:110483800,UUIDMost:99,Slot:offhand,Name:generic.maxHealth},{AttributeName:generic.attackSpeed,Amount:0.1,Operation:2,UUIDLeast:110483900,UUIDMost:99,Slot:offhand,Name:generic.attackSpeed}]}'

**Comment by unholymac** [comment]
im really not sure what to do that's the item I want to give as a reward

**Comment by unholymac** [comment]
hopefully i can get this to work soon :(

**Comment by unholymac** [comment]
can someone help me? i really dont know how to turn it into a string type, when I click validate it gives me a error

**Comment by supersnellehenk** [comment]
> can someone help me? i really dont know how to turn it into a string type, when I click validate it gives me a error

Message me on discord, I'll have a look with you. supersnellehenk#8869
