### ISSUE TITLE
More jobs stats

### ISSUE THREAD

**Issue by K0bus** [Zrips/Jobs#755]
**Description of new idea or improvement on existing one**

For every people who like statistics and want real improve of his jobs system. We need more efficiency stats. For that i suggest two stats.

**Statistics list**

- Reward / Time played with this Jobs (If possible top player reward/time)
- More used action per Jobs (actually this stats is general)

**Another improvement for stats**

If possible add a statistics gui for reading data.

**Comment by montlikadani** [comment]
Too much data for the server, this shouldn't be added. There are api in this jobs plugin, so other developers can make that collecting data from jobs (top player, top stats) and includes that in another plugin.
