### ISSUE TITLE
API - MySQL

### ISSUE THREAD

**Issue by TUBEOF** [Zrips/Jobs#758]
***Description of issue:**
Unfortunately the API does not store the data correctly in MySQL when I use the API.

In this case I let the player set into the job as follows:
jobsPlayer.joinJob(Jobs.getJob("Hunter"));
jobsPlayer.save();'

Unfortunately the data is not stored in MySQL, even if I leave the server. I have entered everything correctly in the Config so that the data is saved when I quit.

Info: With this command the data is saved in MySQL without any problems. (Where is the problem?)

---

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Server Version (using `/ver`):** 
1618 Paper Builder 1.12.2

**Comment by Zrips** [comment]
Use allot more universal method which will perform all needed actions after player joins a job
`Jobs.getPlayerManager().joinJob(jPlayer, job);`
This will properly execute all needed actions, will fire appropriate job join events and so on.
