### ISSUE TITLE
LevelUp XP via Command

### ISSUE THREAD

**Issue by Bedah95** [Zrips/Jobs#759]
LevelUp commands were not executed if a player gets JobXP via command.

Paperspigot: git-Paper-213
Jobs 4.15.7

**Comment by Zrips** [comment]
Could you elaborate more on which exactly commands you performed and what was the outcome?

**Comment by Bedah95** [comment]
In my particular case, JobXP are given as a reward for completing quests.

    Quests:
      'Oak':
        Name: Oak
        Objectives:
        - BREAK;OAK_LOG;200
        RewardCommands:
        - jobs exp [playerName] Woodcutter add 3000
        RewardDesc:
        - ...
        Chance: 25
        fromLevel: 1
        toLevel: 50

So the command /job exp [PlayerName] JOB add XP is used.

If a player reaches a levelup while completing a quest, they will not receive a reward because the command is not executed.

  Woodcutter:
    commands:
      Level10:
        command: jobs editpoints add [player] 1
        levelFrom: 10
        levelUntil: 10

**Comment by Zrips** [comment]
d96798532599df1e1bacc52383dbd11251dc03cf

**Comment by Bedah95** [comment]
Commands in jobconfig.yml still get not executed on levelup in 4.15.9.

Levelup message and sound works.

**Comment by montlikadani** [comment]
It works as it should in the latest versions. Maybe you not watched the console when the player level up and the console send a message about adding points.

**Comment by Bedah95** [comment]
Example:
https://youtu.be/Vi-u2NGim6M

**Comment by montlikadani** [comment]
There can be no change between Jobs exp and Jobs points because jobs points do not increase if we change exp with a command. This only happens when we do something in a job.

**Comment by Bedah95** [comment]
On the left you can see the jobconfig, where there is a command for level 10 that would increase the job points, this is not executed.

**Comment by montlikadani** [comment]
Why would we want that if an exp command has been executed and there is a level increase, why execute the commands from jobConfig? That wouldn’t make sense and there would be an infinite number of points or exps. So commands are only executed when we have level up in a job (not a command).

**Comment by Bedah95** [comment]
In my particular case, XP is given by command as a quest reward to speed up the jobs leveling. Unfortunately, this does not work if the commands in the configuration are not executed.
