### ISSUE TITLE
world-blacklist in jobConfig no Effect on TNTBreak

### ISSUE THREAD

**Issue by Resi23** [Zrips/Jobs#763]
***Description of issue:**
To reproduce:

Add a world to world-blacklist of the Miner Job. Use tnt to destroy stone, granite or diorite in this world. You become Money.

**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
1.15.2

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/e7f7c7deb0b37c674456522017d17dab41859ff6
