### ISSUE TITLE
Possibility to use @p

### ISSUE THREAD

**Issue by AgesRoleplay** [Zrips/Jobs#765]
Possibillity to use @p in commands

I want to run commands on console for employ players to job with crafttweaker script and sync jobs with Reskillable proffesions. But plugin not support using @p in the commands.

Example: /jobs employ @p miner

Sorry for my English. Thanks

**Comment by montlikadani** [comment]
Np, the correct usage is `/jobs employ <player>`. This is how you can employ the player in a job from console. The `@p` is not the best thing to get a player from console even the console is not a alive thing. Also, the `@p` is used for command-blocks and for minecraft-related commands. We will not implement this to get a player with `@p`. Use the correct form of that command.
