### ISSUE TITLE
everyone has all rights

### ISSUE THREAD

**Issue by Produktecheck** [Zrips/Jobs#770]
***Description of issue: I installed the plugin and everyone has all rights without giving any permissions. All admin rights too.**

---

---

**Server Type (Spigot/Paperspigot/etc): Paper** 

**Server Version (using `/ver`): 1.15.2**

**Comment by montlikadani** [comment]
Can you describe more clearly what's your problem? With the `right` word we understand that everything is good so working.

**Comment by supersnellehenk** [comment]
I've been helping him on Discord for a bit, he says everyone has all permissions including the admin permissions without even setting them. He set `jobs.use` to true and that's it. The perms he has set are in this pastebin https://pastebin.com/vzgpUNbF. He's using LuckPerms as his permission plugin.

**Comment by montlikadani** [comment]
Well, there are other options that need to be checked for it to work:
- Make sure you are using a permission plugin that is constantly updated.
- Make sure jobs.world.worldName permission is added to the permission plugin.
- Make sure that no restricted area is selected.
- Check that the world in which there is no payment is the world that is not disabled in generalConfig.
- Check for Vault and Essentials (or CMI) if is installed.

It’s that there’s no payment for just a few users, but it works properly if the plugins are configured correctly.

**Comment by supersnellehenk** [comment]
Why are you suddenly talking about payment issues? The original problem was players getting admin permissions without setting those permissions. I've asked the OP to add `jobs.world.worldName` to his permissions for the players to see if that works.

**Comment by montlikadani** [comment]
In short, we can’t decide what he wants?
The Jobs plugin does not give permissions to groups, only basic and necessary ones when possible. Because the default group gets admin permissions is not the Jobs task because there is no such way to execute. You need to check this in other plugins or in the permission plugin.
