### ISSUE TITLE
BlockBreakEvent & FurnaceSmeltEvent

### ISSUE THREAD

**Issue by jere62smi** [Zrips/Jobs#771]
Hello, for quite a few months, I have noticed a very high use in my Timings of Jobs.
JobsPaymentListener (BlockBreakEvent) & JobsPaymentListener (FurnaceSmeltEvent). I use the latest version of Jobs but this problem has been there for quite a while. Tell yourself that there are 50 players on my server and I have drops in TPS and an increase in the 2 arguments mentioned above in my timings if many players use these actions for their profession, I let you imagine 100 players latency felt.
I remain available for more questions, to provide more information or to carry out tests.
https://timings.aikar.co/?id=83a8853ea0ca4070896b1df3a339f886

**Comment by jere62smi** [comment]
Another timings showing the problem I exposed.
https://timings.aikar.co/?id=30e422dd91074a8496fddfd057353a53

**Comment by jere62smi** [comment]
Hello,
So after doing a little research and analysis, I noticed a use of RestrictedArea, but I never used this file because I don't use it, proof on this bin> http://bin.mc-imperia.fr/olKcxsz86v
I also provide you with my java profiler with details.
![Screenshot_1](https://user-images.githubusercontent.com/31114661/81010958-64a42780-8e57-11ea-8838-333a676cd912.png)

**Comment by Zrips** [comment]
@jere62smi 
Interestingly enough, it looks like there is a issue when we are getting worldguard area. In any case will make some optimizations for this part of code.

**Comment by Zrips** [comment]
14eeb9e73fd264970cc1a58f5d873f5ec558c9f6

**Comment by jere62smi** [comment]
Indeed, the plugin is much more optimized with the new version, I have no feedback, thank you!
