### ISSUE TITLE
Jobs enchantement in French

### ISSUE THREAD

**Issue by epicfail76** [Zrips/Jobs#773]
***Description of issue:**

The enchantement traduction doesn't works with the name of enchant
https://image.noelshack.com/fichiers/2020/19/1/1588602404-enchant.png

When we enchant and the pickaxe have 2 enchantements, we won just 1.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## https://we.tl/t-Yq9IZuDcMl ##
#####################################
```

---

**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
1.15.2

**Comment by montlikadani** [comment]
Did you translated the `TranslatableWords_fr.yml` file?

**Comment by epicfail76** [comment]
Yes but it's doesn't works

**Comment by montlikadani** [comment]
- Did you changed the `locale-language` to your language code?
- Is the `UseCustomNames` is enabled in generalConfig file?

**Comment by epicfail76** [comment]
yes : 
locale-language: fr
UseCustomNames: true

**Comment by montlikadani** [comment]
Can you upload here your TranslatableWords_fr file?

**Comment by epicfail76** [comment]
generalconfig : https://we.tl/t-sSKJRtKWCv
Words_fr : https://we.tl/t-MayTHBEhx0

**Comment by montlikadani** [comment]
You not finished translating enchantments that are in the image. For example the `Fortune`, `Efficiency` is not translated.

**Comment by epicfail76** [comment]
I do it juste for DURABILITY-3

**Comment by montlikadani** [comment]
durability = unbreaking, this two names are equal just due to mc versions this changed. Use
```
Unbreaking: Unbreaking
```
instead.

**Comment by epicfail76** [comment]
Okay ! The traduction works, but my second problem don't change.

**Comment by epicfail76** [comment]
Thank you for the first Resolution

**Comment by montlikadani** [comment]
Can you describe it your second problem? We don't see that.

**Comment by epicfail76** [comment]
When you enchanting a pickaxe, and it have 2 enchantements, we won juste 1 reward.

**Comment by montlikadani** [comment]
Because you have the incorrect enchantment name. You should find the correct enchant name that equally to your mc client.
