### ISSUE TITLE
Enchantment double rewards

### ISSUE THREAD

**Issue by epicfail76** [Zrips/Jobs#775]
***Description of issue:**
When I enchant 1 item and it have double enchantment. We win just 1 reward.
---

####################
####################
```


**Server Type (Spigot/Paperspigot/etc):** 
spigot
**Server Version (using `/ver`):** 
1.15.2

**Comment by epicfail76** [comment]
if on the object there is only 1 enchantment it works, while if there are 2 it does not work completely

**Comment by Zrips** [comment]
As of testing with your provided setup everything seams to be working correctly, you are getting paid for multiple enchants. You might want to double-check enchant names, as some of them are not correct for 1.15.2 version. Like DAMAGE_ARTHROPODS should be bane_of_arthropods
https://minecraft.gamepedia.com/Enchanting

**Comment by epicfail76** [comment]
I change it, but it's same. When the enchantment is one it's ok for all but when it's 2 enchantment we haven't all rewards

**Comment by epicfail76** [comment]
jobsconfig : https://we.tl/t-fpkt5pDebz
