### ISSUE TITLE
Cross server option setting doesn't seem to work

### ISSUE THREAD

**Issue by Devillion** [Zrips/Jobs#776]
***Description of issue:**
Saving on disconnect doesn't seem to work with the setting set to true. When I change servers, the data does not update or show on the other server. Both servers are connected to the same mysql database.

# Turning this on will decrease database performance.
save-on-disconnect: true

Jobs Version: 4.15.7
Spigot 1.15.2
Server Version https://i.imgur.com/brOG0p3.png

**Comment by Zrips** [comment]
Do you have MultiServerCompatability enabled?

**Comment by Devillion** [comment]
looks like I missed that setting, I'll try that out, thanks.

**Comment by Devillion** [comment]
So, the jobs are showing up cross server. The issue now is that it shows we are getting money for our jobs, but our balance is not updating.

I'm using these 2 plugins https://www.spigotmc.org/resources/mysql-player-data-bridge.8117/ and https://www.spigotmc.org/resources/essentials-mysql-storage-extension.25673/

When I sell things to our essentials shop my balance updates. For some reason jobs is not updating on payouts, even though jobs is showing up in game that we get paid for doing the job actions.

**Comment by montlikadani** [comment]
- Do you have Vault installed on your server?
- Do you have CMI? If you have CMI make sure you installed the cmi vault plugin, and enabled the Vault integration in cmi configuration.

**Comment by Devillion** [comment]
I have vault and I don't use CMI

**Comment by Devillion** [comment]
I just noticed this error: https://pastebin.com/A0B7zKbU

**Comment by Zrips** [comment]
@Devillion 
Go to generalConfig file and change **economy-async** to false. Essentials fails to handle async payments and this is why you are getting this error message
