### ISSUE TITLE
Bug for the TopQuest

### ISSUE THREAD

**Issue by DjeyMute** [Zrips/Jobs#778]
Hi !

There is a problem with TopQuest stopping at player number 15.
https://image.noelshack.com/fichiers/2020/19/2/1588679650-1.png

---------------

Server Type : PaperSpigot
Version plugin : 4.15.7
Server version : 1.15.2

**Comment by montlikadani** [comment]
How many players you have?

**Comment by DjeyMute** [comment]
Right now 122 connected.
More than 15 people are doing quests I already checked.

**Comment by Zrips** [comment]
99d88a59f0f7036d39d1dca93c3e99a92ec4accd
