### ISSUE TITLE
returned entity is arrow when we kill entity with a bow instead the killed entity in JobsPrePayementEvent 

### ISSUE THREAD

**Issue by Futurixel** [Zrips/Jobs#779]
***Description of issue:** returned entity is Arrow when we kill entity with a bow instead the killed entity in JobsPrePayementEvent 

**Server Type (Spigot/Paperspigot/etc):**  Paperspigot 1.15.2

**Server Version (using `/ver`):**  4.15.7

**Comment by Zrips** [comment]
6a7b588c18a88274c861d0c3bf179f11585a4b1b
