### ISSUE TITLE
Jobs Reborn v4.15.9 doesn't load at server start

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/Jobs#780]
Jobs Reborn version 4.15.9 doesn't load on a server start, the following error occurs in the log: https://pastebin.com/wY2UHKqR

Version 4.15.7 works fine (there is no 4.15.8 in the version history). 

For all users who joined before we downgraded the job plugin that was disabled at the server start a second entry was created in the database, which caused job loss.

Paper 1.15.2 - 226

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/ca459b62e98bfeff38bd158d72ae8a124df397c9

**Comment by TheoRetisch1** [comment]
Thank you for the fix!, will there be a github release? :D
