### ISSUE TITLE
Duplicate player_uuid in mysql database

### ISSUE THREAD

**Issue by kikelkik** [Zrips/Jobs#781]
As you can see, there are duplicate entries in the jobs_users database causing the lost of some jobs at some points. 
Keeping in mind that we've got 4628 entries in that table might sound negligible, but these few players are active playing (besides the first two players). 

I suspect that these duplications all were caused by jobs plugin updates as it just happened after updating to the latest version.

![unknown](https://user-images.githubusercontent.com/14167723/81330465-66acf700-90a0-11ea-8d24-e9f98fe9a7c2.png)

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/ca459b62e98bfeff38bd158d72ae8a124df397c9
