### ISSUE TITLE
Jobs breaks the permissions engine as of 4.15.9

### ISSUE THREAD

**Issue by runelynx** [Zrips/Jobs#784]
***Description of issue:**
After installing Jobs 4.15.9, I get endless permission failures after a player logs in. Luckperms starts screaming bloody murder about async and NPE problems. Nothing else changed other than Jobs and when I remove Jobs, the problem goes away. The problem persists in 4.15.10 released this morning

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
See here for my full startup and the errors that come when someone logs in
https://controlc.com/71b80630

```

Paper server
This server is running Paper version git-Paper-264 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
Checking version, please wait...
08:21:46
Previous version: git-Paper-217 (MC: 1.15.2)
You are running the latest version

**Comment by runelynx** [comment]
My previous version was 4.15.7. Going back to that version works fine.

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/issues/783#issuecomment-625657366

**Comment by montlikadani** [comment]
Also you using and oldest luckperms version.
