### ISSUE TITLE
Freezes server on "loading explorer data" on server start 4.15.9-4.15.10

### ISSUE THREAD

**Issue by mrcoffee1026** [Zrips/Jobs#785]
***Description of issue:**
Server freezes up and does not proceed to start up after this step.  It might, eventually, but after 5-10 minutes, I assume it's not going to happen and since 4.15.9 supposedly  "Improved database loading", something is clearly wrong, since 4.15.7 loads up fine.
https://pastebin.com/t4X4DYZG

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
build 264  (can't do /ver with this plugin since it won't finish starting up).

**Comment by montlikadani** [comment]
- What database type are you using?
- How many players do you have saved in the database?

**Comment by mrcoffee1026** [comment]
mysql - locally - and miriadb on the live ubuntu server.  4212 users in the user table so i'm guessing that many.

**Comment by Zrips** [comment]
27bc14f21463ef0db67640fe60dfe1f6556f1513
