### ISSUE TITLE
Versions 4.15.9 and 4.15.10 break LuckPerms / WorldGuard

### ISSUE THREAD

**Issue by Drc-DEV** [Zrips/Jobs#788]
***Description of issue:**
Versions from 4.15.9 onwards of Jobs break LuckPerms
https://hastebin.com/wukaliface.sql
It also breaks worldguard
https://hastebin.com/opuvutefat.sql

Downgrading to Jobs 4.15.7 fixes the issue, so the bug was introduced in versions above 4.15.7, (referring to spigot builds, idk about the commits)

**Server Type (Spigot/Paperspigot/etc):** Paper build 273 [1.15.2], also tested with Tuinity build 84 [1.15.2]

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/issues/784

So this is not jobs problem.

**Comment by Tolmikarc** [comment]
How is this not a jobs problem if being at the recent jobs update is what causes the issue...
