### ISSUE TITLE
Permission and commands when player reach a level don't work

### ISSUE THREAD

**Issue by EgidioBezerra** [Zrips/Jobs#790]
***Description of issue:***

```
In my server when a player reach a certain level in some job it's supposed to get a perm, but that feature don't seems to work. 
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## https://pastebin.com/MNtGZdCs ##
#####################################
```

---

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
1.15.2 git-Paper-246

**Comment by montlikadani** [comment]
Duplicate of https://github.com/Zrips/Jobs/issues/639
