### ISSUE TITLE
Jobs EXP Bug

### ISSUE THREAD

**Issue by FeroxDrood** [Zrips/Jobs#791]
When a player leaves a Job and joins another job quickly it can bug our and only give them money from the new job not EXP. Even when they do /jobs and they look at the job payouts EXP is not there only money shows.

No Error

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
Paper 280 1.15.2

**Comment by montlikadani** [comment]
Can't reproduce. Maybe you have some misconfiguration in jobConfig, or you have disabled the Exp payment, or you have exp limitations enabled in configs that stops exp payment.
