### ISSUE TITLE
GlobalTimer on cobble generator gives gains immediately

### ISSUE THREAD

**Issue by n54b** [Zrips/Jobs#793]
***Description of issue:**
I noticed that with the new version of the plugin the globaltimer no longer worked.
I explain I am on a skyblock with people who afk mining for 30min, I had activated the global timer so that the players at least put 2min before winning something ...
But now it no longer works and a block generated by a cobble generator gives gains immediately.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################
##     GlobalBlockTimer:    ##
##     use: true                  ##
##     timer: 60                 ##
######################
```

---

**Server Type : **Spigot**** 

**Server Version **1.12.2**:** 

**Relevant plugins :**
https://www.spigotmc.org/resources/advancedoregen.40527/

**Comment by montlikadani** [comment]
Is the `PlaceAndBreakProtection` option is enabled in generalConfig?

**Comment by n54b** [comment]
![image](https://user-images.githubusercontent.com/12047619/82912394-5ab0a880-9f6d-11ea-83f7-e3606a2aaaef.png)
Yes sir !

**Comment by n54b** [comment]
https://github.com/Zrips/Jobs/issues/797
Its the same bug ...
Place & Break give immediatly money

**Comment by montlikadani** [comment]
Without "OreGenerator" plugins this works correctly.

**Comment by n54b** [comment]
oh shit ... its possible to support this plugin or not ? :S

**Comment by Bricec6** [comment]
i use CustomOreGen
not OreGenerator
