### ISSUE TITLE
Jobs with Grindstone

### ISSUE THREAD

**Issue by epicfail76** [Zrips/Jobs#794]
Hello !

It can possible to add action to pay with Grindstone.

Thank's

**Comment by montlikadani** [comment]
Already exists [CMIMaterial.java#L930](https://github.com/Zrips/Jobs/blob/master/src/main/java/com/gamingmesh/jobs/CMILib/CMIMaterial.java#L930)

**Comment by K0bus** [comment]
Hi, i think @epicfail76 want to say pay for GrindStone use event not GrindStone craft / place.

**Comment by epicfail76** [comment]
Hi @K0bus thank's you for your help. Yes it that. I'm Sorry for my english

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/b8fdad7c6099b11fd442a795d2d6f555ab7a2c80
