### ISSUE TITLE
Hunter unarmed payment bug

### ISSUE THREAD

**Issue by trevor1097** [Zrips/Jobs#803]
**Description of issue:**
The hunter job doesn't register a kill when a player is unarmed. If they have any tool in hand gives a payout but unarmed does nothing.

**Server Type (Spigot/Paperspigot/etc):** 
Paper 1.15.2

**Server Version (using `/ver`):** 
Paper version git-Paper-307 (MC: 1.15.2)

**Jobs Version**
Jobs v4.15.11

**Comment by montlikadani** [comment]
Can't reproduce, this works as it should. Can you show a video/gif about that?

**Comment by trevor1097** [comment]
Here is a video of it not paying out and a zip of my jobs folder.
Running on git-Paper-318

https://youtu.be/-c-W8uYgqWE?t=11
[Jobs.zip](https://github.com/Zrips/Jobs/files/4683971/Jobs.zip)

So i just did some testing and with mcMMO removed it pays for unarmed kills as it should.
mcMMO: Dev build #962
https://papermc.io/ci/view/all/job/mcMMO/962/

**Comment by montlikadani** [comment]
Without MCMMO this works as it should. You should find an option that handles the jobs, or the items in mcmmo. This is not jobs issue.
