### ISSUE TITLE
/jobs not working after change in config.

### ISSUE THREAD

**Issue by Alp1352** [Zrips/Jobs#804]
***Description of issue:**
I seem to can't use the plugin, whenever I use a /jobs command like /jobs join, it just says: Correct Usage: /jobs. This started to happen after I change the blocks in config that are not valid for 1.8.8.

**CONFIG SECTION:**
```
#####################################
## https://pastebin.com/FTV1qhPR / JobConfig 
## https://pastebin.com/UFwe52BK / GeneralConfig 
#####################################
```

---

**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot
**Server Version (using `/ver`):** 
1.8.8

**Comment by Alp1352** [comment]
Btw, there is no errors what so ever other than some unsupported blocks (which I was trying to fix before this happened). It also says Jobs plugin is succesfully enabled, so there is no errors but its not working.

**Comment by montlikadani** [comment]
Can't reproduce. This works as it should. You can try to update your mc version, or check your console for console errors and trying to fix it.
