### ISSUE TITLE
Disable/cap income after I reach max level

### ISSUE THREAD

**Issue by Baterka** [Zrips/Jobs#806]
**Description of new idea or improvement on existing one**
Ability to cap or completely disable money income after some level.

**Detailed information what should do what and when**
I am creating Survival server with strict economy. It means that money are limited resource and every player can make just X money (and never can make more after he reach limits). This means that I need to also cap Jobs to stop earning money after I hit max level.

**Comment by montlikadani** [comment]
There is a `max-level` option in [jobConfig](https://github.com/Zrips/Jobs/blob/master/src/main/resources/jobConfig.yml#L41).

**Comment by Baterka** [comment]
> There is a `max-level` option in [jobConfig](https://github.com/Zrips/Jobs/blob/master/src/main/resources/jobConfig.yml#L41).

Thats not what I described. Max-level option will not stop giving money

**Comment by Baterka** [comment]
Thanks for closing this just for being lazy :dancing_women:
