### ISSUE TITLE
Jobs' Quest rewards not fully compatible with EssentialsX

### ISSUE THREAD

**Issue by xana43** [Zrips/Jobs#807]
EssentialsX I know is basically the same as essentials, but there's better performance and bug fixes(plus it supports 1.15). However being as they're slightly different the command that jobs issues for quest completion in the console (from the console output it seems to be doing /money give {Player} {Amount}) but EssentialsX doesn't use this command, instead it uses /economy give {Player} {Amount}) maybe there should be an option there to either switch between these two syntaxes, or maybe even run a custom command upon completion of a quest

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/101bd5656f3c7d07edf43809cfe81e286c76fed7
