### ISSUE TITLE
Missing locale for general.info.time.days

### ISSUE THREAD

**Issue by mibby** [Zrips/Jobs#81]
Compiled source as of https://github.com/Zrips/Jobs/commit/3f71080b028ac26e85fab586f37b319961e08ee3
Paper dev 1104 (Spigot 1.11.2)

When using a daily limit and typing ```/jobs limit```.

https://github.com/Zrips/Jobs/blob/153352195c90227f214c65ee6e4be99acc1ec0ab/src/main/java/com/gamingmesh/jobs/stuff/TimeManage.java#L32

Needs to be changed to 'day' or the language file itself needs to be changed to days.

**Comment by Zrips** [comment]
Will be fixed
