### ISSUE TITLE
Boots blocking xpboosted armor

### ISSUE THREAD

**Issue by MrYanini** [Zrips/Jobs#811]
I have xpboost on armor, if i have example xpboosted leggings and i have normal boots it wont give extra xp. But if i remove the boots it works, am i doing wrong or is it a bug?
---
Kakans-Pyjamasbyxor:
  id: Golden_leggings
  name: '&9Kakans Pyjamasbyxor'
  lore:
  - '&2'
  - '&770% XP-Boost'
  expBoost: 70.0
  jobs:
  - Wop
  levelFrom: 1
  levelUntil: 200
---

Paper

git-Paper-333 (1.15.2)

**Comment by Zrips** [comment]
d151fbec0f65e7800ed85d73513386ab548166f6
