### ISSUE TITLE
Jobs progress is reset and messed up. in MySQL job names look like "???????"

### ISSUE THREAD

**Issue by MaxIsV** [Zrips/Jobs#813]
***Description of issue:**

--- When I updated from Jobs-4.15.5 to Jobs-4.15.11 the jobs of all the players is messed up and very strange displayed. The progress of some jobs has been reset, and some jobs have been swapped or displayed twice. In MySQL I noticed that job names in the jobs_jobs table look 
like "????????". Although, as in version 4.15.5, the encoding is utf8mb4_unicode_ci, so it seems to me that new version of the plugin writes data incorrectly.

--- 
![JobsBug](https://user-images.githubusercontent.com/58142896/84060717-5a7cc800-a9c5-11ea-9cb2-73e0470dcb24.jpg)

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot

**Server Version (using `/ver`):** git-Paper-1618 (MC: 1.12.2)

**Comment by montlikadani** [comment]
Please make a screenshot about your mysql `jobs_jobs` table where the `?` occurs.

**Comment by MaxIsV** [comment]
> Please make a screenshot about your mysql `jobs_jobs` table where the `?` occurs.

![MySQLWTF](https://user-images.githubusercontent.com/58142896/84062038-99ac1880-a9c7-11ea-9bfa-30a554ab4832.png)

**Comment by montlikadani** [comment]
Try to re-create your database, and find the correct unicode code to accept your language. Re-creating I mean, make a backup to the current one, delete from Jobs folder and re-generate by restarting your server. If we use English characters in database, it will works, because there is no any special character in it.

**Comment by MaxIsV** [comment]
> Try to re-create your database, and find the correct unicode code to accept your language. Re-creating I mean, make a backup to the current one, delete from Jobs folder and re-generate by restarting your server. If we use English characters in database, it will works, because there is no any special character in it.

I do not quite understand you, why should I delete a file if the database is in MySQL and why should I recreate it if I can edit the table? I set the encoding "utf8_general_ci", which 100% supports the Russian language, but still the data is displayed as "?????", then the problem is in the plugin.

**Comment by montlikadani** [comment]
I'm sorry. I confused MySQL with SQLite... So, try saving the MySQL Jobs database, then deleting it, and then creating a new one by restarting the server. If you have this, check to see if it is still incorrect. There is nothing in the plugin that can change the job names in the database. These will only be saved if the database encoding can accept your language.

**Comment by MaxIsV** [comment]
> I'm sorry. I confused MySQL with SQLite... So, try saving the MySQL Jobs database, then deleting it, and then creating a new one by restarting the server. If you have this, check to see if it is still incorrect. There is nothing in the plugin that can change the job names in the database. These will only be saved if the database encoding can accept your language.

I just set the encoding to "utf8_general_ci", restarted the server, but the data is still displayed as "?????". After that I installed Jobs-4.15.5 (instead of Jobs-4.15.11) and with the same encoding everything works.

So the problem is not in the encoding, but in the plugin.
