### ISSUE TITLE
Removing everyone from database on server startup

### ISSUE THREAD

**Issue by Volgeop** [Zrips/Jobs#814]
Hi, when I have enabled in my config database cleanup for 90 days... it removes everyone from database after server startup. Shouldn't it remove only players that weren't online 90 days?

---

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
    Users:
      # Warning!!! before enabling this feature, please make data base backup, just in case there will be some issues with data base cleaning
      # When set to true, data base will be cleaned on each startup from user data to avoid having old player data
      Use: true -> when enabled, edeleting ALL player data on server startup, not just those who were offline 90 days
      # Any one who not played for defined amount of days, will be removed from data base
      Days: 90
```

**Server Type (Spigot/Paperspigot/etc):**  Paper
 
**Server Version (using `/ver`):**  343

**Jobs version:** Jobs4.15.11

PS: this works normally.... it deletes just users with level 1
```
      # Warning!!! before enabling this feature, please make data base backup, just in case there will be some issues with data base cleaning
      # When set to true, jobs data base will be cleaned on each startup to avoid having not used jobs
      # keep in mind that this will only clean actual jobs, but not recorded players
      Use: true
      # Any one who has jobs level equal or less then set, hies job will be removed from data base
      Level: 1
```
and it has same description as mentioned above.... about cleaning database on each startup....

**Comment by montlikadani** [comment]
What version of Jobs you using?

**Comment by Volgeop** [comment]
Edited, see now. also edited it works normally when using deleting while on level 1... but deleting users older than 90 days delete all of them on server startup...

**Comment by Volgeop** [comment]
@montlikadani I gave here more info.

**Comment by Volgeop** [comment]
What's missing here? :D

**Comment by montlikadani** [comment]
> 
> 
> What version of Jobs you using?

**Comment by Volgeop** [comment]
Tried the newest build and players with some permission probably (for ex. it doesn't happen to my helpers) have their jobs after restart.... but default players don't. Please, still waiting for fix.
