### ISSUE TITLE
Jobs data (MySQL) damaged

### ISSUE THREAD

**Issue by MaxIsV** [Zrips/Jobs#820]
***Description of issue:** Hello. Not so long ago, a very strange event happened on my server, the jobs data was mixed and damaged, it happened after updating the plug-in from version 4.15.5 to 4.15.11.
I noticed that in MySQL the names of jobs in Russian are displayed as "??????" and suggested that the problem is this. But in a recent dev-release, this problem was fixed, but the data on the server did not return to normal.

I tested this dev-release and found that the names of the jobs that display as "???????" do not affect anything and I don’t know why they are recorded in the database.

![IMG20200614155316](https://user-images.githubusercontent.com/58142896/84594255-bf1ea380-ae59-11ea-9f81-8bdf4d626761.jpg)

The screenshot shows that some jobs are displayed 2 times, but also I noticed that the jobs that I used were reset to zero, and the jobs that I did not use, on the contrary, went up in level. Everything is exactly the same in the database.

I thought this was all related to the problem (https://github.com/Zrips/Jobs/issues/813) that was solved recently, but it is not. I'm scared because I don’t want to lose the data that was accumulated by the players, but I don’t know why it happened and how to solve it, please help.

![JobsDB](https://user-images.githubusercontent.com/58142896/84594288-e1182600-ae59-11ea-856c-1b565ee38a69.png)

---

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** git-Paper-1618 (MC: 1.12.2)

**Comment by MaxIsV** [comment]
I tested and received new information. When a server crashes on a version of Jobs-4.15.11, the data breaks, but when a server crashes on a version of Jobs-4.15.5, the data remains in order.

And the data is always mixed the same way, not randomly.

**Comment by montlikadani** [comment]
![kép](https://user-images.githubusercontent.com/30026208/86017391-46584380-ba24-11ea-8ef6-a61773fcafbc.png)
For me works very well with your current language and with `utf8mb4_general_ci` unicode.

**Comment by MaxIsV** [comment]
> ![kép](https://user-images.githubusercontent.com/30026208/86017593-7ef81d00-ba24-11ea-97ec-2fc242d7a8d3.png)
> For me works very well with your current language and with `utf8mb4_general_ci` unicode.

Are you using 4.15.12-dev? There, the encoding problem has already been solved. But my problem is that the data is mixed up. After the server crash, the player’s progress will be completely different, and he can be arranged for the same job several times.

**Comment by MaxIsV** [comment]
Before crash:
![before](https://user-images.githubusercontent.com/58142896/86018921-a48a2400-ba2e-11ea-845e-ecb225a105bf.png)
After crash:
![After](https://user-images.githubusercontent.com/58142896/86018952-ace25f00-ba2e-11ea-9256-004cdbc2faeb.png)

**Comment by MaxIsV** [comment]
@montlikadani ._.

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/876d5f7af2b985bd2d1f6d0c0c78608fcd7b7206
