### ISSUE TITLE
Bonus not work (the return !)

### ISSUE THREAD

**Issue by n54b** [Zrips/Jobs#821]
No bonus work again :(
I use the last version (4.15.12)

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**

![nobonus](https://user-images.githubusercontent.com/12047619/84594877-3d2c7b80-ae55-11ea-8da9-6c9442515436.jpg)

---

**Server Type (Spigot/Paperspigot/etc): Spigot** 

**Server Version (using `/ver`): 1.12.2 (Latest)**

**Comment by n54b** [comment]
So I have to give back a piece of stuff to the player ... it's really strange

**Comment by montlikadani** [comment]
Are you used the `/jobs itembonus` command to check the bonus for items?

**Comment by n54b** [comment]
Now itembonus don't work (with the last version)
![jobs points bug](https://user-images.githubusercontent.com/12047619/86528083-24881200-bea5-11ea-8516-a895fd185f19.PNG)

**Comment by Zrips** [comment]
7f485bbbc59344d8bd1b010d6bbe6e24e8c4b16c
