### ISSUE TITLE
VIp max level permission jobs.all.vipmaxlevel doesn't work

### ISSUE THREAD

**Issue by Volgeop** [Zrips/Jobs#827]
***Description of issue:**
Hi, I'm having trouble with this permission... If I wanna set it to jobs.**all**.vipmaxlevel it doesn't work... But when I set it for ex. to jobs.**hornik**.vipmaxlevel, it does. Couldn't all option or * work here too like in boosts – jobs.boost.**all**.**all**.[amount].

---

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):**  354

**Comment by Zrips** [comment]
d0616e873b46495773eec7fa3291c00572b9d383
