### ISSUE TITLE
Ability to set how long the pay message shows on screen

### ISSUE THREAD

**Issue by notenoughbees** [Zrips/Jobs#830]
**Description of new idea or improvement on existing one**
Just like how we can set how long the boss bar showing our job level gets displayed for, we should be able to set how long the message telling us our money/points/xp gain gets displayed for. It gets especially hard to read this message the longer you set the interval before players get paid: on my server for example, players get paid every 2 minutes, so when the message pops up telling them their pay, it can catch them off guard and not leave them enough time to read it.

**Detailed information what should do what and when**
We need an option in the config for how many seconds to display the message that shows on the bottom of the screen when we get paid.
![pay message](https://user-images.githubusercontent.com/62003733/85839886-b6ca4f00-b7ef-11ea-8a44-18ed39a30600.png)

**Comment by montlikadani** [comment]
Adding this would break the minecraft default animation play, decreases the server performance with unnecessary scheduler tasks, show and hide the actionbar according to the minecraft code, so it can't be handled inside a plugin unless it's loaded with unnecessary tasks. So if the minecraft can make this, to handle actionbar tasks, then will be implemented.
