### ISSUE TITLE
Ender Dragon not paying or giving xp when using the hunter job

### ISSUE THREAD

**Issue by DCArmageddon** [Zrips/Jobs#831]
***Description of issue:**

While my players are using the Hunter job, they are not being paid or receiving xp for doing so. I have set it in config and tried different variations such as - end dragon, ender dragon, ender drag etc but the issue still persists. As per previous recommendation through discord support, I have disabled dynamic payment and it worked for a day and the issue is still persisting. While we were testing, it works 'some' of the time but not every single time.

**Server Type (Spigot/Paperspigot/etc):** 

Spigot

**Server Version (using `/ver`):** 

1.15.2

**Comment by montlikadani** [comment]
The names should be `ender_dragon`. Also send here your Hunter job section.

**Comment by DCArmageddon** [comment]
Hunter:
    fullname: Hunter
    shortname: H
    description: Earns money killing monsters.
    ChatColour: RED
    chat-display: full
    max-level: 200
    softIncomeLimit: 100
    softExpLimit: 50
    softPointsLimit: 50
    leveling-progression-equation: 20*(joblevel+joblevel)+(joblevel*joblevel)
    income-progression-equation: baseincome+(baseincome*(joblevel-1)*0.01)
    points-progression-equation: basepoints+(basepoints*(joblevel-1)*0.01)
    experience-progression-equation: (baseexperience*0.25)
    rejoinCooldown: 10
    Gui:
      Id: 261
      Data: 0
    MMKill:
      mm_effectcreeper:
        income: 2.5
        points: 2
        experience: 1.75
    Kill:
      Creeper:
        income: 2.6
        points: 2
        experience: 1.75
      Skeleton:
        income: 3.1
        points: 2
        experience: 2.0
      Spider:
        income: 2.6
        points: 2
        experience: 2.0
      Zombie:
        income: 1.85
        points: 2
        experience: 1.25
      BLAZE:
        income: 3.6
        points: 4.5
        experience: 4.5
      CAVE_SPIDER:
        income: 3.5
        points: 2.0
        experience: 2.0
      ENDERMAN:
        income: 0.2
        points: 0.1
        experience: 0.1
      GHAST:
        income: 12.0
        points: 8
        experience: 8.0
      pig_zombie:
        income: 0.12
        points: 0.1
        experience: 0.1
      SILVERFISH:
        income: 2.0
        points: 2
        experience: 2.0
      GUARDIAN:
        income: 0.2
        points: 0.1
        experience: 0.1
      SHULKER:
        income: 2.0
        points: 2
        experience: 2.0
      PHANTOM:
        income: 3.0
        points: 3
        experience: 3.0
      HUSK:
        income: 2.0
        points: 2
        experience: 2.0
      WITHER_SKELETON:
        income: 3.0
        points: 2
        experience: 4.0
      DROWNED:
        income: 1.75
        points: 2
        experience: 1.25
      SLIME:
        income: 0.45
        points: 0.25
        experience: 0.15
      MAGMA_CUBE:
        income: 0.6
        points: 0.3
        experience: 0.2
      WITHER:
        income: 19.5
        points: 40
        experience: 15.0
      ENDER_DRAGON:
        income: 500.0
        points: 1000
        experience: 240.0

**Comment by DCArmageddon** [comment]
https://pastebin.com/uz4M0aYJ - here is the Hunter section of jobs

**Comment by montlikadani** [comment]
It works correctly. You need to check the generalConfig what you've been enabled before, and trying to disable that, like limitations. If you don't know what was your changes, regenerate the config.
