### ISSUE TITLE
Material not recognize

### ISSUE THREAD

**Issue by n54b** [Zrips/Jobs#832]
in order to make compatible jobs in the last version you skipped the materials for versions lower than 1.13
Monster / Enchantment 

---

**ERROR:**

![jsbo bug](https://user-images.githubusercontent.com/12047619/85946860-98776700-b947-11ea-9cf7-7e68cf627ee3.PNG)

---

**Server Type :Spigot ** 

**Server Version (using `/ver`): 1.12.2 (latest) **

**Comment by Zrips** [comment]
071b70609dea44c740230a855295c23b372f21b9
