### ISSUE TITLE
Bug with Tipped arrow

### ISSUE THREAD

**Issue by DjeyMute** [Zrips/Jobs#837]
Hello,
I wanted to add the " tipped_arrow " craft on my job but it doesn't work... ^^

[https://image.noelshack.com/fichiers/2020/27/1/1593452018-2.png
](url)

Server Type : Paperspigot
Server version : 1.15.2

**Comment by montlikadani** [comment]
This already been implemented https://github.com/Zrips/Jobs/commit/12ffc67eede60eedfb5f3a64e40b79db768ca008
check discord #dev-releases to test out

**Comment by DjeyMute** [comment]
Implemented but this doesn't world check my screenshoot :/

**Comment by montlikadani** [comment]
> world

? eh

You should add the tipped arrow effect, like `tipped_arrow:slowness`

**Comment by DjeyMute** [comment]
Oh okey i go tested this !

**Comment by DjeyMute** [comment]
Don't work... 

30.06 11:34:19 [Server] WARN [Jobs] Job Chasseur has an invalid Craft type property: tipped_arrow:slowness!

**Comment by montlikadani** [comment]
Because you not using the new version from dev-releases

**Comment by DjeyMute** [comment]
Hi !
I can't add this tipped arrow :

- tipped_arrow:long_leaping:
- tipped_arrow:healing:
- tipped_arrow:regeneration:

All the other types work but not these 3.

**Comment by montlikadani** [comment]
Should be `tipped_arrow:jump`, `tipped_arrow:instant_heal` and the third will fix it

**Comment by DjeyMute** [comment]
Thanks it works!
For clarification I did not find a way to translate them because I am French
