### ISSUE TITLE
Loading warn message.

### ISSUE THREAD

**Issue by ZagyMC** [Zrips/Jobs#838]
***Description of issue:**
when the server starts and jobs reborn is loading, i have this message in console:
[Jobs] Job Hunter has an invalid Kill type property: PIG_ZOMBIE!
---

Server Type (Spigot/Paperspigot/etc):  Spigot 

Server Version (using `/ver`): build 1.8.0_242-b08

Jobs reborn version: latest v4.5.12 from discord

**Comment by montlikadani** [comment]
use `zombified_piglin`
