### ISSUE TITLE
Mysql

### ISSUE THREAD

**Issue by ZagyMC** [Zrips/Jobs#839]
***Description of issue:**
when i want to use my mysql i have error in console for some "jobnames" in sqlite is everything working. Maybe is problem on database, but on 1.15.2 it worked so i dont know.

---
> [15:13:57] [Server thread/WARN]: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect string value: '\xC5\x99evor...' for column `s7_survival`.`jobs_jobNames`.`name` at row 1
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3931)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1915)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2136)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2070)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5187)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2055)
> [15:13:57] [Server thread/WARN]: at com.gamingmesh.jobs.dao.JobsDAO.recordNewJobName(JobsDAO.java:1129)
> [15:13:57] [Server thread/WARN]: at com.gamingmesh.jobs.dao.JobsDAO.loadAllJobsNames(JobsDAO.java:1171)
> [15:13:57] [Server thread/WARN]: at com.gamingmesh.jobs.Jobs.reload(Jobs.java:760)
> [15:13:57] [Server thread/WARN]: at com.gamingmesh.jobs.Jobs.startup(Jobs.java:441)
> [15:13:57] [Server thread/WARN]: at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:673)
> [15:13:57] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
> [15:13:57] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
> [15:13:57] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
> [15:13:57] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:493)
> [15:13:57] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:407)
> [15:13:57] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:438)
> [15:13:57] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:219)
> [15:13:57] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:810)
> [15:13:57] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164)
> [15:13:57] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)
> [15:13:57] [Server thread/WARN]: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect string value: '\xC4\x8D' for column `s7_survival`.`jobs_jobNames`.`name` at row 1
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3931)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1915)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2136)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2070)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5187)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2055)
> [15:13:57] [Server thread/WARN]: at com.gamingmesh.jobs.dao.JobsDAO.recordNewJobName(JobsDAO.java:1129)
> [15:13:57] [Server thread/WARN]: at com.gamingmesh.jobs.dao.JobsDAO.loadAllJobsNames(JobsDAO.java:1171)
> [15:13:57] [Server thread/WARN]: at com.gamingmesh.jobs.Jobs.reload(Jobs.java:760)
> [15:13:57] [Server thread/WARN]: at com.gamingmesh.jobs.Jobs.startup(Jobs.java:441)
> [15:13:57] [Server thread/WARN]: at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:673)
> [15:13:57] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
> [15:13:57] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
> [15:13:57] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
> [15:13:57] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:493)
> [15:13:57] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:407)
> [15:13:57] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:438)
> [15:13:57] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:219)
> [15:13:57] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:810)
> [15:13:57] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164)
> [15:13:57] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)
> [15:13:57] [Server thread/WARN]: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect string value: '\xC5\x99' for column `s7_survival`.`jobs_jobNames`.`name` at row 1
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3931)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1915)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2136)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2070)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5187)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2055)
> [15:13:57] [Server thread/WARN]: at com.gamingmesh.jobs.dao.JobsDAO.recordNewJobName(JobsDAO.java:1129)
> [15:13:57] [Server thread/WARN]: at com.gamingmesh.jobs.dao.JobsDAO.loadAllJobsNames(JobsDAO.java:1171)
> [15:13:57] [Server thread/WARN]: at com.gamingmesh.jobs.Jobs.reload(Jobs.java:760)
> [15:13:57] [Server thread/WARN]: at com.gamingmesh.jobs.Jobs.startup(Jobs.java:441)
> [15:13:57] [Server thread/WARN]: at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:673)
> [15:13:57] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
> [15:13:57] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
> [15:13:57] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
> [15:13:57] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:493)
> [15:13:57] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:407)
> [15:13:57] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:438)
> [15:13:57] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:219)
> [15:13:57] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:810)
> [15:13:57] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164)
> [15:13:57] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)
> [15:13:57] [Server thread/WARN]: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect string value: '\xC5\x99' for column `s7_survival`.`jobs_jobNames`.`name` at row 1
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3931)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1915)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2136)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2070)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5187)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2055)
> [15:13:57] [Server thread/WARN]: at com.gamingmesh.jobs.dao.JobsDAO.recordNewJobName(JobsDAO.java:1129)
> [15:13:57] [Server thread/WARN]: at com.gamingmesh.jobs.dao.JobsDAO.loadAllJobsNames(JobsDAO.java:1171)
> [15:13:57] [Server thread/WARN]: at com.gamingmesh.jobs.Jobs.reload(Jobs.java:760)
> [15:13:57] [Server thread/WARN]: at com.gamingmesh.jobs.Jobs.startup(Jobs.java:441)
> [15:13:57] [Server thread/WARN]: at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:673)
> [15:13:57] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
> [15:13:57] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
> [15:13:57] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
> [15:13:57] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:493)
> [15:13:57] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:407)
> [15:13:57] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:438)
> [15:13:57] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:219)
> [15:13:57] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:810)
> [15:13:57] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164)
> [15:13:57] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)
> [15:13:57] [Server thread/WARN]: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect string value: '\xC5\x99' for column `s7_survival`.`jobs_jobNames`.`name` at row 1
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3931)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1915)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2136)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2070)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5187)
> [15:13:57] [Server thread/WARN]: at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2055)
> [15:13:57] [Server thread/WARN]: at com.gamingmesh.jobs.dao.JobsDAO.recordNewJobName(JobsDAO.java:1129)
> [15:13:57] [Server thread/WARN]: at com.gamingmesh.jobs.dao.JobsDAO.loadAllJobsNames(JobsDAO.java:1171)
> [15:13:57] [Server thread/WARN]: at com.gamingmesh.jobs.Jobs.reload(Jobs.java:760)
> [15:13:57] [Server thread/WARN]: at com.gamingmesh.jobs.Jobs.startup(Jobs.java:441)
> [15:13:57] [Server thread/WARN]: at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:673)
> [15:13:57] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
> [15:13:57] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
> [15:13:57] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
> [15:13:57] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:493)
> [15:13:57] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:407)
> [15:13:57] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:438)
> [15:13:57] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:219)
> [15:13:57] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:810)
> [15:13:57] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164)
> [15:13:57] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)

---

**Server Type (Spigot/Paperspigot/etc): Spigot

**Server Version (using `/ver`): 1.8.0_242-b08

**Comment by montlikadani** [comment]
Send here a screenshot about jobs database, from `jobs_jobNames` table.

**Comment by Zrips** [comment]
@ZagyMC 
Fix your jobs name you defined in config file, it cant contain any weird characters and NO color codes.
