### ISSUE TITLE
McMMO Classic doesn't work with Jobs

### ISSUE THREAD

**Issue by jordanwilliams1** [Zrips/Jobs#842]
***Description of issue:**

McMMO TreeFellerMultiplier doesn't work. It just ignores all of McMMO's changes within the jobs config

**Comment by ned98** [comment]
Players will get not just a part, but ALL of the money from cutting trees with the treefeller ability. It will always be 100%. Tested with the latest mcmmo classic for 1.15 and 1.16 and the latest jobs plugin from spigot.

**Comment by Zrips** [comment]
0a21c1308cc883e7bc45c89b6d6f96b6c2225e74
