### ISSUE TITLE
Generator cobblestone support

### ISSUE THREAD

**Issue by Bricec6** [Zrips/Jobs#846]
**Description of new idea or improvement on existing one**

Hello, my miners are complaining because with their cobble generator or ore its telling them to wait x time, but I don't want to set the protection to 0 to avoid cheating, can you adapt and make sure that there is no protection time for the cobble generator for example? thank you.

**Detailed information what should do what and when**

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/issues/793
