### ISSUE TITLE
Jobs stats do not show

### ISSUE THREAD

**Issue by Iggy8068** [Zrips/Jobs#849]
***Description of issue:**
The Jobs are all working fine, but the jobs stats command is empty, it only shows the #

**Server Type (Spigot/Paperspigot/etc):** 
paper latest for 1.16.1
**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-74 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Comment by montlikadani** [comment]
Inserting a screenshot would better than `#`
