### ISSUE TITLE
jobs info doesn't show browse menu

### ISSUE THREAD

**Issue by Volgeop** [Zrips/Jobs#850]
***Description of issue:**
---
Hi, I have set new feature to true but it doesn't show browse menu.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  JobsInfo:
    # Open up the jobs browse action list, when your performed /jobs info command?
    open-browse: true
```

Image: https://imgur.com/a/UyV1UxR

---

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):**  Paper 83

**Comment by montlikadani** [comment]
It describes you should another argument. Type `/jobs info <jobName>`
