### ISSUE TITLE
jobs browse gui shows $1 more

### ISSUE THREAD

**Issue by Mechy71** [Zrips/Jobs#851]
Hi,

My jobs browse GUI shows all job action rewards $1 over the actual amount. Another user has also encounted the same issue on discord.

Server Type (Spigot/Paperspigot/etc):
Paper 1.16.1
Server Version (using /ver):
Paper-82

Thanks

**Comment by montlikadani** [comment]
Inserting a screenshot would better.

**Comment by Mechy71** [comment]
/Jobs Browse: 
![image](https://user-images.githubusercontent.com/20552472/87069088-c3ba5a00-c255-11ea-82f6-b8db614975c6.png)
/Jobs Info:
![image](https://user-images.githubusercontent.com/20552472/87069127-d2a10c80-c255-11ea-9804-398d4e2c1db3.png)

**Comment by FeroxDrood** [comment]
Having the same issue is this being fixed as it was closed?

**Comment by rosiejane** [comment]
Also a user on discord reported this with the 1.16 update

Is the new 1.16 jobs update working correctly for anyone? Its acting weird for me.
For example On 1.15.2 (Miner Job) I had Netherrack set to 0.02 income: 0.01 experience: 0.02 points and this is how it was (see link)

https://imgur.com/a/OFs0VFh
![image](https://user-images.githubusercontent.com/54243352/87573681-3055ae80-c6c5-11ea-888f-34cc5f5ab1c2.png)

When i updated to 1.16.1 with the same job settings (0.02 income: 0.01 experience: 0.02 points) it now displays this
https://imgur.com/a/frctZMm
![image](https://user-images.githubusercontent.com/54243352/87573708-3d729d80-c6c5-11ea-9ebb-655e8a7a81e8.png)

Updating to 1.16.1 has changed most of my job items/blocks. Very frustrating. It also seems that you cannot make any item give below $1.00
Any ideas?

**Comment by montlikadani** [comment]
Did you see that commit link? This been fixed and this change not in the latest build.

**Comment by rosiejane** [comment]
Is there a date for when this update will be released.
