### ISSUE TITLE
Invalid Mob Type

### ISSUE THREAD

**Issue by ZEROOblivious** [Zrips/Jobs#853]
***Description of issue:**

[Server] WARN [Jobs] Job Hunter has an invalid Kill type property: PIG_ZOMBIE!

FRESH CONFIG WHEN INSTALLING PLUGIN
This was a small WARN Message that showed up since the DEV Builds of Jobs Reborn, just wanted to point out its still popping up since first DEV Build of 1.16

![image](https://user-images.githubusercontent.com/32251194/87214806-00da2700-c2fe-11ea-8621-40080eeb4698.png)

Jobs4.16.0.jar  <-- Current Version

**Comment by montlikadani** [comment]
Use `zombified_piglin`
