### ISSUE TITLE
 DisableJoiningJobThroughGui

### ISSUE THREAD

**Issue by blakedj012** [Zrips/Jobs#855]
***Description of issue:**
 DisableJoiningJobThroughGui: true does nothing. Players can allways join via command "jobs join miner" as example

Latest Jobs Reborn Version
Latest Spigot 1.16.1 version

**Comment by montlikadani** [comment]
Is the `JobsGUI.SwitcheButtons` option is disabled or enabled?

**Comment by blakedj012** [comment]
You mean in the generalconfig? There is "true" to this setting

**Comment by montlikadani** [comment]
`DisableJoiningJobThroughGui` option is only for gui not for command, If you want to disable joining via command, then deny `jobs.command.join` from users. Also `DisableJoiningJobThroughGui` works.
