### ISSUE TITLE
New mechanic on "vip" max levels, much more useful

### ISSUE THREAD

**Issue by Tomi010817** [Zrips/Jobs#859]
### Description
Currently you can only set one vip max level to each job, but what about being able to create multiple max levels to your jobs so that way you can give a different maxlevel to different groups basing on permissions? That would be a really dope idea.

### Functionality
To add multiple max levels on a job, you could simply do like [**_this_**](https://hastebin.com/paqoviciku.coffeescript) for example.
So in that given example, you can see that you are able to set different names to those max levels. And I'm guessing that this feature would require a little change on the `jobs.[jobsname].vipmaxlevel` permission since it was designed to only work with "vip". And it should be changed to something like `jobs.[jobsname].maxlevel.[maxlevelsname]`. NOTE: It would override the one with higher value.

**Not sure on how it should work?** No problem, here are some examples basing on the [previous max-levels example given above](https://hastebin.com/paqoviciku.coffeescript):
- If you give `jobs.WoodCutter.maxlevel.another` to someone, then that player will be able to reach level 30 on the WoodCutter job.
- If you give `jobs.WoodCutter.maxlevel.vip` and `jobs.WoodCutter.maxlevel.ultimate` to someone, then that player will be able to reach level 100 on the WoodCutter job. (since "ultimate" has a higher value than "vip" max level)
- If you give `jobs.all.maxlevel.ultimate` to someone, then that player will be able to reach level 100 on the WoodCutter job and the specified level (only if it is the higher value) on all other jobs that also include "ultimate" max level on their settings. 

Hope you liked the idea! Cheers

**Comment by Zrips** [comment]
jobs.[jobsname].vipmaxlevel.[level] does just that, give this permission to the player with defined level and player will be able to reach this level, if player has access to multiple permissions like this, then biggest one will be used.

**Comment by Tomi010817** [comment]
Sorry for my stupidity
