### ISSUE TITLE
TNTBreak not working

### ISSUE THREAD

**Issue by rikyriky232** [Zrips/Jobs#860]
***Description of issue:** After my update from 1.15.2 to 1.16.1, the blastmining or TNTBreak from jobs suddenly stopped working. No config changes were done when the update was made besides updating the plugin to latest version

Jobs version: 4.16.0
---

**Server Type (Spigot/Paperspigot/etc):** Paperspigot build 108

**Server Version (using `/ver`):** Paper version git-Paper-108 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Comment by montlikadani** [comment]
1. there is no blastmining action in jobs
  2. insert here your TNTBreak section from jobConfig
  3. make sure your world is not on disabled worlds list

**Comment by rikyriky232** [comment]
Apologize for calling it blastmining (got used to calling it like so)

I can't seem to upload the config itself hence i uploaded it here: https://pastebin.com/LTB0xsTd
I'm honestly not sure if i'm doing it wrong or it's due to some other plugins interfering with it

**Comment by montlikadani** [comment]
>     3. make sure your world is not on disabled worlds list

Also, you have oldest jobConfig, that can reproduce future issues. Regenerate it and see what was changed,
