### ISSUE TITLE
Blocks pay again after being moved by a slime block

### ISSUE THREAD

**Issue by sh1mrr4** [Zrips/Jobs#864]
***Description of issue:**

When a block (e.g. diamond ore) is moved by a slime block, it can be mined again to get additional money, even if it was placed only seconds ago. Interestingly this only works if the slime block was blaced by hand and not if it was placed by FAWE.

Screenshot of an exemplary setup:
[https://imgur.com/LQ3uveI](url)

**Version of JobsReborn: 4.16.0

**Server Type (Spigot/Paperspigot/etc): Paper

**Server Version (using `/ver`): 1.15.2-378

**Comment by Zrips** [comment]
2d2b6ccb608c5e439e68e690987c73289c33796d
