### ISSUE TITLE
Difference between /job info and /job browse

### ISSUE THREAD

**Issue by WIBOR2002222** [Zrips/Jobs#865]
When I order /jobs info, it shows me the right amount of money and XP on a certain job. However, in the /jobs browse, the amount is not the right one. It is too high. I can't change that.

/jobs info :

https://ibb.co/ZG6Zzmj

/jobs browse :

https://ibb.co/2nzjq0T

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/issues/851
