### ISSUE TITLE
Spam in console

### ISSUE THREAD

**Issue by WIBOR2002222** [Zrips/Jobs#866]
Do you know this bug ? 

https://ibb.co/FgygJTM

**Comment by montlikadani** [comment]
More info? Which jobs version you using?

**Comment by WIBOR2002222** [comment]
The last version of jobs (Jobs4.16.0)
And we use paper 1.16.1

**Comment by montlikadani** [comment]
This issue currently can't reproduce. Issue closing until there is a new release of Jobs. If you still have issues with the new release, please make a new ticket.
