### ISSUE TITLE
RGB Title Support

### ISSUE THREAD

**Issue by mattirizarry** [Zrips/Jobs#867]
**Description of new idea or improvement on existing one**

In the titles.yml the ChatColor variable should support a Hex Code since 1.16.1 supports RGB Chat. Pretty self explanatory

**Comment by mattirizarry** [comment]
I can try and pick this up myself and put in a PR for it. Doesn't seem too difficult...

**Comment by Zrips** [comment]
dc855411078e3091f398a32bc8e286a2cf6d4d73
