### ISSUE TITLE
Jobs limit not refreshing at level up

### ISSUE THREAD

**Issue by Gumpah** [Zrips/Jobs#868]
**Description of issue:**

I have a non-static jobs limit set on my server, depending of the job level of the player, which means that it increases each time you level up. The issue is that the jobs limit doesn't refresh and stays the same unless we reload the plugin manually (`/jobs reload`) or reboot the server.
It would be nice if the limit could refresh everytime you level up.

---

**Server Type (Spigot/Paperspigot/etc):** PaperMC

**Server Version (using `/ver`):** Paper-379 1.15.2

**Jobs version:** Jobs 4.16

Thank you for your time!

**Comment by Zrips** [comment]
6dc5fb9ba14afa2bc266812e8c5fab7d07f5b495
