### ISSUE TITLE
Add actions for Grindstones, Blast Furnace, & Enchantment type

### ISSUE THREAD

**Issue by IgnisCraft** [Zrips/Jobs#869]
I don't want to use the Enchanter job because players can just strip the enchants off a Grindstone, enchant Netherite or diamond over and over again with level 1 enchants, and make a bunch of money. If I nerf the job, then players who didn't think to do that get paid nothing. If there was a grindstone action, I could deduct money for players who use it.

Also, players should not get paid the same for doing a level 30 enchant compared to a level 1 enchant.

It'd be cool if we could also make an action for putting two tools together but I understand if that's not gonna happen.

**Comment by montlikadani** [comment]
Thats already a thing, use Grindstone for repair, and blast furnace to smelt
