### ISSUE TITLE
Option to enable PlaceAndBreakProtection for all placed blocks by default.

### ISSUE THREAD

**Issue by mibby** [Zrips/Jobs#87]
Would it be possible to add an option to globally protect all placed blocks to prevent xp/money gain from player placed items for x number of days instead of having to manually define every single block used?

**Comment by Zrips** [comment]
Global timer value will be used with next build when there is no defined cooldown for particular block and global timer is enabled in generalConfig file

**Comment by mibby** [comment]
Does the global timer log every single block placed/broken into a database?
