### ISSUE TITLE
Wrong calculation on number of employees in /jobs browse gui

### ISSUE THREAD

**Issue by Bloodlex** [Zrips/Jobs#876]
***Description of issue:**

Number of people in a specific job is wrong in /jobs browse. Maybe it has something to do with that, that I have a translated jobs name and it doesn't recognize it or something? I wasn't able to trace it more in details - I don't get any errors or something.

Could you help please? 😢

**Config**

jobConfig: 
[https://pastebin.com/NKnJW0hs](https://pastebin.com/NKnJW0hs) 
generalConfig:
[https://pastebin.com/yMMjwK9L](https://pastebin.com/yMMjwK9L) 

**Server Type (Spigot/Paperspigot/etc):** 
PaperMC

**Server Version (using `/ver`):** 
git-Paper-380 (MC: 1.15.2)

Screenshot:
![unnamed](https://user-images.githubusercontent.com/1086720/89710521-323d2580-d984-11ea-99e6-78b2dfe91363.png)

It means that I already work as Woodcutter but still number of employees is 0. It is also same with other jobs I don't know why, they are 0 or incorrect.

**Comment by montlikadani** [comment]
Probably because you have an outdated database when you upgrading from older versions of Jobs. Try to enable `MultiServerCompatability` in generalConfig

**Comment by Bloodlex** [comment]
I'v

> Probably because you have an outdated database when you upgrading from older versions of Jobs. Try to enable `MultiServerCompatability` in generalConfig

I've just done it and reloaded with /jobs reload but haven't noticed any difference. Should I restart the server then?

**Comment by montlikadani** [comment]
Which jobs version you using? (not latest)

**Comment by Bloodlex** [comment]
> Which jobs version you using? (not latest)

4.16.0

**Comment by montlikadani** [comment]
Try to reset your sql database, by deleting it and regenerate it by restarting your server.

**Comment by Bloodlex** [comment]
> Try to reset your sql database, by deleting it and regenerate it by restarting your server.

I can't do that, my players would be very miserable 😢 

I can show you my database if you would like to take a look. I haven't seen anything suspicious there myself, but I can be wrong. Thank you for helping me.

[jobs.sqlite.zip](https://github.com/Zrips/Jobs/files/5045303/jobs.sqlite.zip)

**Comment by BoomEaro** [comment]
I can confirm.
Removing the database and creating a new one does not solve the problem.

**Comment by montlikadani** [comment]
Can't reproduce. Still works like a charm.

**Comment by BoomEaro** [comment]
I found out what the problem is.

The problem arises if the fullname in the job config differs from the section name.

You will understand what I mean if you insert this configuration of job.

https://pastebin.com/nGaKdTsU

If you name the section the same as fullname, then no problems are observed. I don't know if this is a mistake, but it is worth pointing out somewhere in the documentation.
