### ISSUE TITLE
FullDescription not visible in /jobs browse gui

### ISSUE THREAD

**Issue by Bloodlex** [Zrips/Jobs#877]
***Description of issue:**

Cannot see FullDescription in /jobs browse gui. I can only see short description.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**

  Woodcutter:
    fullname: Drwal
    shortname: D
    description: Zarabia scinając i sadząc drzewa
    FullDescription:
    - '&2Dostajesz pieniądze za:'
    - '  &7Sadzenie drzew'
    - '  &7Ścinanie drzew'
    - '  &7Eliminując graczy'

---

**Server Type (Spigot/Paperspigot/etc):** 
PaperMC

**Server Version (using `/ver`):** 
git-Paper-380 (MC: 1.15.2)

**Comment by montlikadani** [comment]
`FullDescription` is only for chat when you enabled chat displaying in generalConfig at browse settings. `description` is displayed in gui.
