### ISSUE TITLE
Permission node for boost not working everywhere

### ISSUE THREAD

**Issue by StenaCS** [Zrips/Jobs#879]
Okay so I have applied the following permission node to a group: jobs.boost.all.all.[amount] for example jobs.boost.all.all.5
It shows the updated income on /jobs browse but does not pay the player that amount but just pays the default amount on /jobs info miner.

So the boost is not activating at all with that permission, I am using luckperms.

**Comment by montlikadani** [comment]
Can't reproduce. Boosts works like a charm. Can we see a `/jobs bonus` output?

**Comment by StenaCS** [comment]
Could I youtube a video with a fresh install and show you?
