### ISSUE TITLE
Jobs Reborn bug

### ISSUE THREAD

**Issue by Baylorai** [Zrips/Jobs#881]
***Description of issue:**
When i join more then 1 job the next job takes away money and exp i should be getting by the other job and lowers it. Why is this happening?
---
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
1.16.1

**Comment by montlikadani** [comment]
This is normal thing. You can configure jobs exp take in generalConfig

**Comment by Baylorai** [comment]
Yo, ive struggled with this for awhile and can not find where to fix this, can you plz show me or something

**Comment by Baylorai** [comment]
> This is normal thing. You can configure jobs exp take in generalConfig

I quite literally cant find anything on how to fix this...
