### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Baylorai** [Zrips/Jobs#882]
***Description of issue:**
I know you told me its in GeneralConfig, But ive looked through it for hours and ive changed a few different things to see if that was it and i have run into no luck, if you could please explain or screenshot the line or something please, Ill explain the issue alittle more, When i join a job (ex: Digger) i get 0.25exp when i join a 2nd job the money and exp goes down to 0.24 and then 0.23 when i join the 3rd job. I have literally looked through this file for a solid 2hours and cant find nothing
---

**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
1.16.1

**Comment by Baylorai** [comment]
And dont close the thing right away please, i really need help with this its been a bug to me for so long and i cant fix it!

**Comment by montlikadani** [comment]
Find `old-job` section in generalConfig. These are options where the user should configure how the jobs leave takes levels (exp).

Closing, because this is not the community place. Ask questions in discord server.
