### ISSUE TITLE
shift clicking out of a crafting table only awards 1 item

### ISSUE THREAD

**Issue by ltei01** [Zrips/Jobs#884]
a player does his quest and he need to craft 16 bread. But if he craft 16 bread in one go he dont get rewarder for 16 bread but only for one. It only counts if a player craft one bread one by one.

---

```

```

---

Paper 1.16.1

paper-134 1.16.1

**Comment by montlikadani** [comment]
You should enable `PayForEachCraft` in generalConfig.
