### ISSUE TITLE
jobs.petpay permission not working

### ISSUE THREAD

**Issue by Loiytzia** [Zrips/Jobs#888]
***Description of issue:**

---
*Description of issue:

Player had the permission jobs.petpay false.If the Pet hits Mobs they get Job EXP and Payout, they shouldnt get it.---

---

Server Type (Spigot/Paperspigot/etc): 
Paper 1.16.1

Server Version (using /ver): 
git-paper-131 (MC:1.16.1)

**Comment by montlikadani** [comment]
jobs.petpay is not enough to be a verified permission. You should give `jobs.petpay.1`, because this permission is boosts your jobs if you have pet.
