### ISSUE TITLE
/jobs browse say +1$ and +1xp

### ISSUE THREAD

**Issue by DjeyMute** [Zrips/Jobs#889]
Hi,

When a player does /jobs browse it displays +1$ and +1xp compared to the / jobs info command.
The visual of the /jobs browse command is false, it adds +1$ and + 1xp to all actions.

**Configuration** :
[https://image.noelshack.com/fichiers/2020/34/1/1597657180-1.png](url)

**Visual of /jobs browse** :
[https://image.noelshack.com/fichiers/2020/34/1/1597657180-2.png](url)

Paper : 135 latest version
Server version : 1.16.1
Jobs version : 4.16.0

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/issues/865

**Comment by DjeyMute** [comment]
Do you know when the update will arrive?
