### ISSUE TITLE
Players dosn't get payed for there Jobs.

### ISSUE THREAD

**Issue by Tsumitsuki** [Zrips/Jobs#890]
Less of a bug i guess. More likely that i missed something while configuration.

Players dosn't get payed for there Jobs.
What did i missed?

paper 135 (MC: 1.16.1)
jobs 4.16.0
cmi 8.7.6.2
vault 1.7.3 (from cmi)
LuckPerms  5.1.93

jobconfig: https://pastebin.com/hVMGb40V
generalconfig: https://pastebin.com/M87ZwqrD

just in case:
cmiconfig: https://pastebin.com/Zh6sADRa
luckpermsconfig: https://pastebin.com/LUynCVPT

**Comment by montlikadani** [comment]
Make sure you have added the `jobs.world.worldName` permission to your group to get income. (`worldName` is your world where the jobs should pay). Also check for `jobs.use` its been set.
