### ISSUE TITLE
job info showing less than base price in config

### ISSUE THREAD

**Issue by elaineandsparky** [Zrips/Jobs#893]
version 4.16.0 on a 1.16.2 server.

I understand there is a known bug with jobs browse showing the wrong price compared to jobs info but i'm also having problems with people on a higher level of the job getting paid less than people on level 1 and less than the config is set to. If we look at the miner job for example  and tube coral block (but same problem with everything):

Gui config is set to $2 (I'm assuming at job level 1)

For me at miner level 29: 
gui ingame price is set to $2.15
/job info miner it says $1.15 (less than what it is set to in config)

For player at level 1 and just joined job so not broken any blocks it is listed correctly in /job info:
gui ingame price is set to $3
/job info miner it says $2

Potentially the price changes aren't being updated for people already on the job when changes are made in configs.

**Comment by elaineandsparky** [comment]
we were also able to keep player data when switching from 1.15.2 to 1.16 using multiverse could it be that the plugin isn't recognising the levels obtained from 1.15?

**Comment by Zrips** [comment]
@elaineandsparky 
Your entire issue originates from one simple variable in equation **numjobs** where depending on how many jobs you have your payment will be lowered down by 5% for each extra job above first one. So by having 11 jobs you will gain 50% of income. If you want to minimize this or even remove, then you will need to remove  *** ((numjobs-1)*0.05))** part from every equation in jobConfig file
