### ISSUE TITLE
%jobsr_maxjobs% per permission

### ISSUE THREAD

**Issue by Volgeop** [Zrips/Jobs#894]
**Description of new idea or improvement on existing one**
Hi, this is improvement of actual placeholder %jobsr_maxjobs%. I think that it should be per permission instead per global default maximum.... Because I can join for ex. 5 jobs, but placeholder %jobsr_maxjobs% still show, that I can join just 2 of them... so it's default maximum players can join... but when they have jobs.max.X, they can join more of them....

DoN¨t know if this is bug or improvement, but would be great if you can "fix" or improve it.

**Comment by Volgeop** [comment]
But wait... when I'm using jobs.max.amount, shouldn't be jobsr_maxjobs different than default number? Could you check if it really works please?

**Comment by montlikadani** [comment]
If you give `jobs.max.amount` to your group, the return of this placeholder will be what've been given in the permission. Its described in above max-jobs generalConfig option, so the permission overwrites the config value.

**Comment by Volgeop** [comment]
But I already saying you that it doesn't work :D I given this permission and I tested it via papi parse etc. and it showed default value from max-jobs in generalConfig.... Could you check if it really works for you?

**Comment by Volgeop** [comment]
Could you send me link to download please?
