### ISSUE TITLE
/jobs expboost <job> <rate> <TIME>

### ISSUE THREAD

**Issue by bobhenl** [Zrips/Jobs#895]
**Description of new idea or improvement on existing one**
Hi, I wanna suggest adding time to boost commands in Jobs. Would be useful if we wanna make for ex. global boost as perk that can be bought in the store.

**Detailed information what should do what and when**
Just specific time, how long will boost last.

**Comment by Volgeop** [comment]
Maybe you can add it to command info

**Comment by Volgeop** [comment]
But wait... when I wanna active it for specific player?

**Comment by montlikadani** [comment]
You can only for specific jobs.

**Comment by Volgeop** [comment]
/jobs expboost all 8s 1

won't work?

And I can't specify there player? Couldn't you improve it please?

**Comment by montlikadani** [comment]
> /jobs expboost all 8s 1

Ah, yea you can apply for all jobs.


> And I can't specify there player? Couldn't you improve it please?

no, thats will causing lot of issues, but you can have per-permission based boosts

**Comment by Volgeop** [comment]
Oh yeah, I forgot on per permission based. Thanks, will try do it this way. If there will be problem, will write here agian.

**Comment by montlikadani** [comment]
It would better on discord.
