### ISSUE TITLE
"Break" ores not working most of the time

### ISSUE THREAD

**Issue by nickoo9043** [Zrips/Jobs#896]
***Always I think it's something I'm doing wrong, but this time is different, because sometimes it works, and sometimes just don't, it's literally random. For doing this easier I'll put a link to the youtube video. Everytime I break a ORE, it doesn't count it, and sometimes without doing anything, it works, but most of the time don't.  What can I do? Tell me every info do you need to help me, I know it's a weird bug or something. Thank you for your time!:** PD: All my other personalized jobs are working 100% good, is just this one.

Youtube link: https://www.youtube.com/watch?v=tQN2-y0CvIk

Sorry if I don't talk, english is not my main language. In the video I show you in the first part the default configs are the same I'm using. Second when I break diorite it works. I did it with every block, and it works 99,9% fine, the big deal are the ores.

```

**CONFIG SECTION:**
```
#####################################
## 
![Screenshot_16](https://user-images.githubusercontent.com/60305334/90995371-c1079000-e589-11ea-97d8-02e729530549.png)
 ##
#####################################
```

---

**Server Type Paperspigot:** 

**Server Version 1.15.2:** 

**Relevant plugins
![plugins](https://user-images.githubusercontent.com/60305334/90995365-ba791880-e589-11ea-859b-709e36b740f1.png)

**Comment by nickoo9043** [comment]
![plugins](https://user-images.githubusercontent.com/60305334/90996264-3c6a4100-e58c-11ea-8837-b8bfe7e35b72.png)
Plugins

**Comment by nickoo9043** [comment]
![Screenshot_15](https://user-images.githubusercontent.com/60305334/90996312-63c10e00-e58c-11ea-9258-7fe53d40758d.png)
Console, not bugs related shows

**Comment by montlikadani** [comment]
You probably have enabled PlaceAndBreakProtection in generalConfig. Also check for restrictedBlocks to make sure that blocks what you're trying to break is not in the list.

**Comment by nickoo9043** [comment]
Thank you very much. Never saw ores in -1, my baad. Last question before closing this, "By setting time to -1 will keep block protected until global cleanup". What is it "Global cleanup" I don't understand it, what needs to happen to remove the protection?. Again, so much thanks.

**Comment by montlikadani** [comment]
Global cleanup: when you or atleast server restart doing reseting protections, so the block protections will remove from memory.
