### ISSUE TITLE
Blocks pulled by slime blocks pay again

### ISSUE THREAD

**Issue by sh1mrr4** [Zrips/Jobs#900]
***Description of issue:**
If a block is pulled by a slime block, it is paying money again, even if it was placed by hand. The block has to be pulled, the bug does not occur if the block is pushed or moved along with the slime block. Here is an exemplary [picture](https://cdn.discordapp.com/attachments/691934654957223978/748642247096139826/unknown.png) (the diamond block on the right pays again). 

**Server Type (Spigot/Paperspigot/etc): Paper

**Server Version (using `/ver`): 1.15.2-378

**Jobs Version: 4.16.1

**Comment by montlikadani** [comment]
So basically if the block pushed by piston and slime block then should pay, because it changed the position, right? But if the block pushed by piston & slime block and the pistopn extended back, then it shouldn't pay?

**Comment by sh1mrr4** [comment]
Woops, sorry for not being very specific there. So, essentially blocks that are on the list of restricted blocks should not pay at all when you place them and then break them again (like this gold ore). However, this protection can be bypassed by pulling them with a slime block (as shown in the screenshot).
