### ISSUE TITLE
Jobs Rewards Not Displaying

### ISSUE THREAD

**Issue by PseudonymousColby** [Zrips/Jobs#901]
***When looking at the Jobs GUI using /jobs browse, players are unable to see the rewards for each job. The config says that they should be able to, and they have the permission to join that respective job, and yet the info for it cannot be seen. Might it have something to do with the Jobs Bonuses being turned on? Thank you in advance!**

---
![image](https://user-images.githubusercontent.com/30609492/91592914-3e862400-e92d-11ea-9a0d-c0e66cc36c07.png)

![image](https://user-images.githubusercontent.com/30609492/91592763-0979d180-e92d-11ea-908b-df4272a3d832.png)

---

**Server Type: Paper** 

**Server Version: 1.16.2**

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/issues/798
