### ISSUE TITLE
Jobs API

### ISSUE THREAD

**Issue by Nino1500** [Zrips/Jobs#902]
**Ladies and Gentlemen!**

I have a suggestion to improve the **API**.

I would love to see, that the JobsExpGainEvent gets the same methods as the JobsPrePaymentEvent, like **getBlock**, **getEntity**, **getActioninfo**.

I hope that it will get implemented!

Greetings
Ninoo

**Comment by montlikadani** [comment]
It would be good next time to open a PR by yourself.

**Comment by Nino1500** [comment]
Okay, I am not very familiar with GitHub, but I ll do it next time. 
Thank you!
