### ISSUE TITLE
Latest of everything has a few errors

### ISSUE THREAD

**Issue by StenaCS** [Zrips/Jobs#906]
So did an update to the latest version and players are not getting exp for jobs, the jobs bossbar at the top no longer shows and they cannot register furnaces at all. It only shows for OP for me. Is there a new permission or setting somewhere?

**Comment by montlikadani** [comment]
> not getting exp for jobs

You're not getting for the specific things:
- You literally disabled Exp payment in generalConfig
- You have limitations set in generalConfig
- Your jobs does not contain "experience" value, and you modified the `exp-progression-equation`

Watch out all settings that the plugin have, revert your last modifications in files and will be good.

> the jobs bossbar at the top no longer shows

You literally disabled bossbar in generalConfig or you using old minecraft version which the bossbar is not supported.

> Is there a new permission or setting somewhere?

There are wiki for the required permissions: https://github.com/Zrips/Jobs/wiki/Permissions
The required permissions is granted every server-startup, but your permission plugin does not support that.

**Comment by StenaCS** [comment]
Using 1.16.2 paper build 174.
Permission plugin is Luckperms using latest version
Jobs reborn is latest version

I never edited or removed (logically) anything all I did was update the jars...

**Comment by montlikadani** [comment]
> There are wiki for the required permissions: https://github.com/Zrips/Jobs/wiki/Permissions
> The required permissions is granted every server-startup, but your permission plugin does not support that.

So?

**Comment by StenaCS** [comment]
*Not using PEX, Using Luckperms*
I have autojoin on true and my players automatically join all jobs so the initial permisssion is irrelevant.
What I need to know is why the bossbar no longer shows at the top and players are no longer getting experience.
I have attached my jobsconfig.yml and generalconfig files.
[jobs.zip](https://github.com/Zrips/Jobs/files/5156100/jobs.zip)

**Comment by montlikadani** [comment]
Grant `jobs.world.worldname` and `jobs.use` for groups where not works.

**Comment by StenaCS** [comment]
Done, no changes. Can I hire someone to come in and take a look :D

**Comment by montlikadani** [comment]
Make sure that you (probably you) not toggled the bossbar with `/jobs toggle bossbar`. If you find a file named with "actionBarBossbar" and have some data in it, then remove and reload the jobs.

**Comment by StenaCS** [comment]
Okay what about the furnace issue, other server owners are also having it.

**Comment by StenaCS** [comment]
![2020-09-02_11 21 56](https://user-images.githubusercontent.com/65764569/91963837-b75ef480-ed0e-11ea-8b6a-53812316ffca.png)
![2020-09-02_11 22 00](https://user-images.githubusercontent.com/65764569/91963843-b8902180-ed0e-11ea-8713-dd91ac7b0fd2.png)

As you can see the only boss bars that are appearing are for MCMMO and players getting paid but not getting exp. Please do not accuse me of changing config files. Many other server owners are saying the same thing why do you keep telling us this is our fault?

**Comment by StenaCS** [comment]
RangewonkYesterday at 12:40 PM
@Stager Latest version has many bugs - use version 4.16.0.

I have done this and guess what?? everything works! So the issue is with your latest version, please stop blaming server owners.

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/78c6368c092e94f9e17aa6a0409a1677468571c3

**Comment by StenaCS** [comment]
Wait you re-opened the ticket then referenced some issue that only applies to furnaces? - https://github.com/Zrips/Jobs/commit/78c6368c092e94f9e17aa6a0409a1677468571c3

The thing is that going to the previous version fixed everything, so why not fix the current version since I do not see any updates here since 25th August?

**Comment by StenaCS** [comment]
This issue is NOT just for furnaces, you presumed so based on pictures but ALL jobs were not giving exp or showing bossbar. I can install on a new server and show you?

**Comment by broken1arrow** [comment]
> 
> 
> This issue is NOT just for furnaces, you presumed so based on pictures but ALL jobs were not giving exp or showing bossbar. I can install on a new server and show you?

Yes he need open this again, i have pay issues on 4.16.1 too. builder get not pay for players (work in 4.16).

**Comment by StenaCS** [comment]
Yea I hear you, but I just gave up because they made it seem like it was my fault that is why I closed it.

**Comment by broken1arrow** [comment]
> Yea I hear you, but I just gave up because they made it seem like it was my fault that is why I closed it.

It is all ways like this with some of Zrips plugins he not care about. Mob farm manger new version has serious bugs he don't care about. 

He has at lest step up and fix bugs in cmi atleast.

**Comment by StenaCS** [comment]
I would like to say that this has all been fixed with the last 2 updates.
