### ISSUE TITLE
Max Jobs not working

### ISSUE THREAD

**Issue by slvlr** [Zrips/Jobs#907]
***Description of issue:**

Max Jobs in config is set to 1.
I use permissions to allow some ranks to join more jobs.

players are able to join as many jobs as they like on version 4.16.1.

**Server Type (Spigot/Paperspigot/etc):** 
Paper Spigot

**Server Version (using `/ver`):** 
Paper build 137 version 1.16.1

**Relevant plugins (Delete if this isn't needed):**

**Comment by montlikadani** [comment]
> players are able to join as many jobs as they like on version 4.16.1.

> I use permissions to allow some ranks to join more jobs.

If you allowed to join for more jobs than 1 for some groups, then your players groups probably inherits the specific groups and the player are in that group.

**Comment by slvlr** [comment]
@montlikadani 

The max Jobs group has 5 jobs. But we have 10 jobs in total.
Players were able to join 10 jobs.

This is not a permissions inheritance problem.
I backdated jobs to version 4.16.0 and this fixed the issue. 

This is an issue in build 4.16.1.
