### ISSUE TITLE
No suport for extra world?

### ISSUE THREAD

**Issue by broken1arrow** [Zrips/Jobs#911]
We have a extra world on the server, but you dont get paid in that world. 

No worlds is blacklisted.

**Server Type (Spigot/Paperspigot/etc):** 
papermc 
**Server Version (using `/ver`):** 
1.16.1 133

**Comment by montlikadani** [comment]
You were not granted `jobs.world.yourWorld` permission.

**Comment by broken1arrow** [comment]
> 
> 
> You were not granted `jobs.world.yourWorld` permission.

Yes it work.
