### ISSUE TITLE
Commit that Allowed End Crystal as Killed Entity Breaks TNTBreak Action

### ISSUE THREAD

**Issue by JGMinimule** [Zrips/Jobs#912]
***Description of issue:***
The change in logic from [this commit/line](https://github.com/Zrips/Jobs/commit/439665039b098e8f2b942ab6a1f34964dfb38b66#diff-e094452f709d92d9ec5f71a3e933b6f8L1590) breaks TNT mining as a result of the not operator apparently inverting `Jobs.getGCManager().isUseTntFinder()` instead of `Jobs.getGCManager().isUseTntFinder() || type != CMIEntityType.ENDER_CRYSTAL.getType()`.
I believe this to be the root issue of #860 and I hope that this will be useful to you.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
This test used the default generated configuration file.

---

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
git-Paper-184 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

**Relevant plugins (Delete if this isn't needed):**
Jobs

**Comment by montlikadani** [comment]
It would be good next time to fix this and submitting a PR to make less work for us if you know these.

**Comment by JGMinimule** [comment]
I do apologize - I don't use Github, but I will look into getting more familiar with it
