### ISSUE TITLE
Task kill doesn't work

### ISSUE THREAD

**Issue by Typheonn** [Zrips/Jobs#913]
When mobs such as chicken, cow, ... are killed, players don't earn exp, money, ...

I try on paper 137(1.16.1) and paper-185 (1.16.2) with Jobs 1.16.0 and 1.16.1

Thanks you.

**Comment by Typheonn** [comment]
I find a solution : allow kill mobs from spawners, even if there is not spawner.

**Comment by broken1arrow** [comment]
You shall not need turn this on, so it is a bug. 

If it naturally spawned mobs.

**Comment by Typheonn** [comment]
I'm so silly, the mob spawned from an egg, sorry if I disturbed you.
