### ISSUE TITLE
Hostile mobs no longer pay for Hunter

### ISSUE THREAD

**Issue by mrcoffee1026** [Zrips/Jobs#914]
***Description of issue:**
Hunter job not paying for kills of any hostile mobs (naturally spawned).
- works fine with non-hostile/passive mobs.

---

**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
[17:00:39 INFO]: This server is running Paper version git-Paper-183 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
[17:00:39 INFO]: Checking version, please wait...
[17:00:39 INFO]: Previous version: git-Paper-178 (MC: 1.16.2)

**Relevant plugins (Delete if this isn't needed):**
Jobs 4.16.1

**Comment by montlikadani** [comment]
Literally you not enabled pay-near-spawner option in generalConfig

**Comment by mrcoffee1026** [comment]
Yes, I "literally" have not enabled that option, but these mobs were not spawned by a spawner.

**Comment by montlikadani** [comment]
We need more info. Send your current job from jobConfig

**Comment by mrcoffee1026** [comment]
[jobConfig.zip](https://github.com/Zrips/Jobs/files/5195769/jobConfig.zip)

**Comment by montlikadani** [comment]
Can't reproduce. Every hostile mobs works like a charm (naturally/non-naturally). You probably have some limitations or restrictions in some of jobs configuration, or something plugin which prevents from paying out.

**Comment by mrcoffee1026** [comment]
I can find no option anywhere that disables pay for hostile mobs, and no other plugins of mine alters pay or exp with the job plugin.  If you're getting paid for unnaturally spawned mobs then you've enabled the option for players to be paid for killing mobs from spawners, however, and if disabling this disables pay for naturally spawned mobs too, then it isn't doing what it's supposed to be doing.

**Comment by montlikadani** [comment]
> If you're getting paid for unnaturally spawned mobs then you've enabled the option for players to be paid for killing mobs from spawners, however, and if disabling this disables pay for naturally spawned mobs too, then it isn't doing what it's supposed to be doing.

Literally I got paid from spawners and naturally mobs not just from spawners.

You have to make sure that you aren't in a restrictedArea, you don't have income limit set in generalConfig, or your current world is in disabled worlds and its enabled, and many other things that can relates to income. In this case send your generalConfig.

**Comment by mrcoffee1026** [comment]
"Literally I got paid from spawners" which means you set 
"enable-pay-near-spawner:" to true.  I have this set to false.  Setting this to false should not disable pay for naturally spawned mobs: further verified by naturally spawned non-hostile mobs in the same area paying for this job.  The current world is NOT disabled, verified by every other job paying in the same world, same with restricted areas since I don't have a single one set.  
[generalConfig.zip](https://github.com/Zrips/Jobs/files/5197208/generalConfig.zip)

**Comment by mrcoffee1026** [comment]
Nupe didn't work for me at all.  Saw the same trouble reverting... AND even non hostile mobs would not pay on my local copy so I began thinking it may just be something else interfering and narrowed it down to StackMob... which - once I updated the config file to the latest version - no longer seems to be an issue.
