### ISSUE TITLE
Jobs Quests doesn't update the subscript

### ISSUE THREAD

**Issue by Chip1129** [Zrips/Jobs#915]
When hovering the quest in the chat, it will say the whole "Break 0/10 Stone --- Break 0/10 Granite" however, when a player breaks 10/10 stone, the "total" for the quest will say "10/20" but the sub will still say "Break 0/10 Stone".  This becomes an issue when there's a quest to slay 10 zombies, skeletons, spiders, and creepers.  If they have a "25/40" done, it won't tell them which of them have how many completed.  Not sure how to fix this.  Thank you!

**Comment by Chip1129** [comment]
Forgot this in the above post. My bad.

**Server Type (Spigot/Paperspigot/etc):** 

Paperspigot

**Server Version (using `/ver`):** 

Version 1.16.2

**Comment by montlikadani** [comment]
Would be good some screenshots about it and include Jobs version what you using.

**Comment by Chip1129** [comment]
Inconsistent results.  It works now but wasn't the other night.  Unsure how to replicate.  Closing ticket.
