### ISSUE TITLE
Bungee Server Placeholders

### ISSUE THREAD

**Issue by Cryper** [Zrips/Jobs#916]
**Description of new idea or improvement on existing one**
Add a placeholder like "%jobsr_user_jtoplvl_[jname/number]_[number]_[server]%"
So u can set a Toplist of the Jobs in your Main World but only have Jobs enabled in another farm world.

(Idea came cause MultiServerCompatability: true, decrease the TPS of the server alot)

**Comment by montlikadani** [comment]
Jobs is Bukkit plugin not bungee.
