### ISSUE TITLE
Jobs Quests do not reset

### ISSUE THREAD

**Issue by Chip1129** [Zrips/Jobs#917]
I have my jobs set on a way with around 5-7 quests and they all have a decreasing chance of showing up with increasing rewards. (To my knowledge, the chances didn't have to add to 100%). Upon logging on,a staff member got the exact same quests as last night. Two if these quests have the lowest chance of showing up. Do the "chance" have to add to 100 to work properly?? If not, what might be wrong?

**Comment by montlikadani** [comment]
Include more informations like jobs version and your quests that is in jobConfig. Also quest reset depends from quest times that is set in generalConfig.

**Comment by Chip1129** [comment]
Jobs4.16.1.jar

my quests are to reset every 8 hours.  after sleeping and waking up (they had 3 hours till reset when my girlfriend logged off) she got the same quests in the morning brand new non completed (after completing the chance: 15 one.)
*paste of miner job quests*

Quests:
      '1':
        Name: Mine Mine Mine!
        Objectives:
        - Break;stone;100
        - Break;granite;50
        - Break;andesite;50
        - Break;diorite;50
        RewardCommands:
        - money give [playerName] 100
        - msg [playerName] Quest complete!
        RewardDesc:
        - Mine Stone, Granite, Andesite, Diorite!
        - Get 100 Credits upon completion!
        Chance: 80
      '2':
        Name: Coal Miner
        Objectives:
        - Break;coal_ore;258
        RewardCommands:
        - money give [playerName] 500
        - msg [playerName] Quest complete!
        rewardDesc:
        - Mine coal for the furnaces!
        - Get 500 Credits upon completion!
        Chance: 70
      '3':
        Name: Dwarven Mine
        Objectives:
        - Break;iron_ore;64
        - Break;gold_ore;16
        - Break;coal_ore;64
        RewardCommands:
        - money give [playerName] 750
        - msg [playerName] Quest complete!
        rewardDesc:
        - Mine Iron, Gold, and Coal for the Dwarves!
        - Get 750 Credits upon completion!
        Chance: 50
      '4':
        Name: Motherload
        Objectives:
        - Break;diamond_ore;10
        - Break;emerald_ore;2
        - Break;gold_ore;15
        - Break;lapis_ore;25
        RewardCommands:
        - money give [playerName] 1000
        - msg [playerName] Quest complete!
        rewardDesc:
        - Mine Diamond, Emerald, Gold, and Lapis ores!
        - Get 1000 Credits upon completion!
        Chance: 15

**Comment by Chip1129** [comment]
Still not sure what to do with this.  Players are still getting repeat quests on reset.  I'd expect repeat quests on the high chance ones, but these are the chance:15 and 10 ones that keep repeating after 3 resets of the counter now.

**Comment by Zrips** [comment]
7715864301a87bcc41ef24a672b94c5742ad3a02
