### ISSUE TITLE
Animals don't work right?

### ISSUE THREAD

**Issue by Chip1129** [Zrips/Jobs#918]
Having an issue where the "Breed" and the "Shear" handlers for a quest don't register when a player actually does so.

PaperSpigot

1.16.2

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/2e3e86f10b54275decbb8f8493e5aa4ad0f002f5
and for Breed action: should works just you are too far away from the breed entities, so it not pays.

Also, make sure that you have enabled `pay-near-spawner` option in generalConfig
