### ISSUE TITLE
Jobs Reborn Upgrade 4.13.1->4.14.3 mysql database error. Trying to upgrade to 4.16.1

### ISSUE THREAD

**Issue by Erlpil** [Zrips/Jobs#919]
I am far behind on this plugin due to having the server still running 1.13.2 ([paper 655, 1.13.2](https://papermc.io/ci/job/Paper-1.13/655/)).
Time has come to upgrade since we are going to 1.15.2+. I am currently at version 4.10.3 and are attempting to upgrade all the way to 4.16.1
I am doing incremental upgrades of the final version of each major release to make sure nothing will go wrong.
Updates are done in this version order:
4.11.1Experimental
4.12.0
4.13.1
4.14.3
4.15.11
4.16.1

Everything works fine until I go from 4.13.1 to 4.14.3.
Adding console log (edited to include only relevant info) [https://pastebin.com/raw/EBAx6jMJ](https://pastebin.com/raw/EBAx6jMJ)

From 4.14.3 it will do this on every server startup even though it states ”[Jobs] Converted to new database format” The only difference is that it will not run the CREATE TABLE IF NOT EXISTS queries as these already are created on the first run.

Tried to upgrade to 4.15.11 and 4.16.1 as well with the same result. It will run this “[Jobs] Converting to new database format” task on each server boot.

Is there a way to fix this so I don’t have to reset my Jobs database?

**Comment by montlikadani** [comment]
First thing, would be good to not use old versions if you got an exception in console. You probably using an oldest sql database version which is not supported (assuming to mysql).

**Comment by Erlpil** [comment]
Thank you for the quick reply!
I am running Jobs Reborn 4.10.3 in prod currently, but I am working in a test environment to upgrade it to 4.16.1.
Wont the "Converting to new database format" task upgrade my current jobs reborn mysql database to a new format that is supported?
It does not produce these exceptions before I jump from 4.13.1 to 4.14.3.

**Comment by montlikadani** [comment]
> Wont the "Converting to new database format" task upgrade my current jobs reborn mysql database to a new format that is supported?

wat? Jobs is not a mysql updater. Jobs is updating own tables with datas to a new one.

**Comment by Erlpil** [comment]
Sorry for the confusion. Not sure if you are talking about the table format created by Jobs og the mySQL database in itself.
My mySQL database is up to date.
mysql  Ver 14.14 Distrib 5.7.31, for Linux (x86_64) using  EditLine wrapper

**Comment by Erlpil** [comment]
Found a workaround for the issue:
- Upgrading the plugin to 4.16.1
- Reboot once after update
- Ran /jobs convert (converting from mysql til sqlite)
- New reboot
- Deleted jobs_* tables in mysql (make sure to take a backup)
- Ran jobs convert again (converting from sqlite back to mysql)
- New reboot

This resolved the issue with Jobs running a DB convertion on each boot.

For info: The data in the tables: jobs_blocks & jobs_explorerData did not survive the conversion and was lost.

Hope this can help anyone if they are stuck with the same problem.
Feel free to close the issue if you dont plan on looking into this bug :)

**Comment by ken-kentan** [comment]
it isn't related to upgrade 4.16.1.
I tried to install this plugin(4.16.1) with MySQL mode. But, it doesn't create jobs tables when starting server.

I tried [this](https://github.com/Zrips/Jobs/issues/919#issuecomment-691548815). but still not create tables...
