### ISSUE TITLE
Disable jobs/actions by world

### ISSUE THREAD

**Issue by EkonC** [Zrips/Jobs#920]
**Description of new idea or improvement on existing one**
I was thinking if it was possible to add something like "Disabled worlds" to the jobConfig for each job or each action. This feature would be great for any server owner who wants players to receive less money from farming Endermen in the End but more from killing them in the Overworld.

**Detailed information what should do what and when**
In the jobConfig, there should be a parameter like _DisabledWorlds:_ for certain jobs or actions. If the player is in the world written in the config, he won't receive money for that job/action.

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/blob/master/src/main/resources/jobConfig.yml#L552
