### ISSUE TITLE
jobs.max permissions appear broken in the latest update

### ISSUE THREAD

**Issue by Wolfhound1Z** [Zrips/Jobs#924]
**Description of issue:**
We have ranks that provide user's with the ability to join additional jobs. The default rank gets 1 job (jobs.max.1), a rankup down the line gives 2 jobs (jobs.max.2), another rankup down the line gives 3 jobs (jobs.max.3). Higher ranks on this track inherit from previous ranks. 
A rank on a separate track provides 4 jobs.
We recently updated to 1.16.3, and updated jobs to 4.16.1. Before updating, these permission nodes would just apply a flat permission that only allowed the user to join as many jobs as their highest jobs.max permission was. Now however it seems to be adding permissions together, or something along those lines. A user with all 4 permissions from their ranks (jobs.max.1, jobs.max.2, jobs.max.3, and jobs.max.4) was able to join 10 jobs instead of 4 as it was before, as if the permissions are adding together. Trying to set jobs.max.[x] permissions as false permissions just seems to allow users to join as many jobs as they like. This does not seem like intentional behaviour as I've not seen it written anywhere that permissions were changed to act this way, and I've seen others report on the discord. Any fix or help is appreciated 🙂 
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
generalConfig.yml
```
# Maximum number of jobs a player can join.
# Use 0 for no maximum
# Keep in mind that jobs.max.[amount] will bypass this setting
max-jobs: 1
```

---

**Server Type (Spigot/Paperspigot/etc):** 
Tuinity
**Server Version (using `/ver`):** 
MC version 1.16.3
**Relevant plugins (Delete if this isn't needed):**
Luckperms version 5.1.93

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/issues/909
