### ISSUE TITLE
Permission Cumulation issue

### ISSUE THREAD

**Issue by LogGits** [Zrips/Jobs#927]
***Description of issue:**
Jobs max is set to cumulation mode by default via:
https://github.com/Zrips/Jobs/blob/d00d4a59a6f43e4b8d4751abc0d2283d64b855ce/src/main/java/com/gamingmesh/jobs/PermissionManager.java#L123-L125

Can we get a config value for the cumulation mode defaulting to `false`?
I was also testing it out with luckperms:
```
/lp user {user} permission set jobs.max.3
/lp user {user} permission set jobs.max.2 false
```
With those permissions the player has access to 5 jobs even though its set to false (which should be skipped)

---
**Server Version (using `/ver`):** paper 1.16.2 build 204

**Comment by montlikadani** [comment]
Probably doing a `hasPermission` will fixes it.
```java
if (cumulative && jPlayer.getPlayer().hasPermission(permission.getKey()))
    amount += temp;
else if (temp > amount)
    amount = temp;
```

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/497673f2dcf6a73f48a5f882a27a1445384f8995
k
