### ISSUE TITLE
Permission for jobs.petpay.1 unfortunately is still not working

### ISSUE THREAD

**Issue by Sulort** [Zrips/Jobs#930]
**Description of issue:**
Hi, we still have an issue with the permission jobs.petpay.1

see #922 

---

**Server Type:** Paperspigot

**Server Version:** papermc 1.16.3 version 195

**Relevant plugins:** JobsReborn 4.16.2 MyPet-3.11-SNAPSHOT-B1571

**Comment by montlikadani** [comment]
Are you sure that you're on 4.16.2?

**Comment by Sulort** [comment]
yes off course, I'm sure.
The problem is that the argument [HookManager.getMyPetManager().isMyPet(ent)] is still false, because ent is not the correct given entity. I downloaded the 4.16.2 version from github and put some debug messages into. As I mentioned it in #922

**Comment by montlikadani** [comment]
> because ent is not the correct given entity

Yes, so your "existing" pet is not a valid mypet entity, so the MyPet api can't recognise that you have pet saved into database.

**Comment by Sulort** [comment]
nope, it is a valid mypet and the api is working correctly. I'm using the mypet api in another plugin and the mypet is correctly recognized. so the mypet api is not the problem
