### ISSUE TITLE
Problem with plugin vehilces

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/Jobs#931]
We are using a plugin that can spawn different vehicles
One of them is a drill. 
Problem is if the drill is s used he mines so fast. For the drilling player get fast job xp, lvl, money when the use it. Currently we have no idea how we can prevent this. 
Best would be if people get no money when the drill breaks the Blocks.
So we may thought yoi can add a hook or something to prevent this <3

Here is a link to the plugin 
https://www.spigotmc.org/resources/%E2%9C%88%EF%B8%8Fvehicles-no-resourcepacks-needed.12446/

**Comment by montlikadani** [comment]
Would be good to make a video/gif for proof.

**Comment by CloudeLecaw** [comment]
i vrrote the dev of the vehilce plugin he said:

> They are the ones listening to the BlockBreakEvent i generate
> So they should add a (player.getVehicle() == null) check

im no programmer but may you know whhat he means.

Here is the video. its not so long but i think it shows you whats the problem
https://www.lululand.de/Download/vehicle.mp4

**Comment by montlikadani** [comment]
There is an option in generalConfig to disable payment when riding on entity, `disablePaymentIfRiding`

**Comment by CloudeLecaw** [comment]
Your a genius <3 u saved our day :-*
