### ISSUE TITLE
Jobs Quests not working on last version (4.16.2)

### ISSUE THREAD

**Issue by SliderKP** [Zrips/Jobs#936]
in the latest version of jobs (4.16.2 on spigot page) quests dont working T_T

/jobs quests > No missions avaible

**Comment by montlikadani** [comment]
You don't have quests setup in jobConfig

**Comment by SliderKP** [comment]
> You don't have quests setup in jobConfig

before the update, i have the quests working fine... my job with job:

    Quests:
      '1':
        Name: Leñador
        Objectives:
        - Break;oak_log;50
        RewardCommands:
        - eco give [playerName] 1000
        - msg [playerName] Completaste la mision de Leñador y obtuviste 1000 de dinero
          y cofre de gemas!
        - voucher give gemasRandom 1 [playerName]
        RewardDesc:
        - Romper 50 bloques de madera
        - Obtendras Dinero y Gemas

**Comment by SliderKP** [comment]
@montlikadani why you closed ?

**Comment by SliderKP** [comment]
@montlikadani can you tell me my error ?

**Comment by montlikadani** [comment]
DID YOU SEE THE COMMIT?

**Comment by SliderKP** [comment]
> DID YOU SEE THE COMMIT?

i dont known what is commit.

**Comment by montlikadani** [comment]
Ok, then do not open another issue

**Comment by SliderKP** [comment]
but you dont tell me anything and closed my issue bro, can you tell me how to solve my error ?

**Comment by SliderKP** [comment]
where i can download the latest realease with this commit?

 montlikadani closed this in 2c369c5 8 hours ago

**Comment by SliderKP** [comment]
@montlikadani when i can get the new release?
