### ISSUE TITLE
Payout Not Occurring for Miner, Woodcutter, Digger, and Hunter

### ISSUE THREAD

**Issue by Lord-Lofi** [Zrips/Jobs#937]
***Description of issue: Miner, Woodcutter, Digger, and Hunter do not pay out nor do they update at all. (No progress is made performing actions for that job)***

Running Jobs4.16.2 although issue occurred initially on Jobs4.16.1

---
**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
`
[PasteBin of jobsconfig](https://pastebin.com/S2jeDmvq)
[PasteBin of generalconfig](https://pastebin.com/iNSrkABq)
`
```

---

**Server Type (Spigot/Paperspigot/etc):Spigot** 

**Server Version (using `/ver`):CraftBukkit version git-Spigot-988b411-aa8206a (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT**

**Comment by Lord-Lofi** [comment]
Just to note, i have looked at previous tickets and have tried the solutions to no avail. The worlds are enabled. The permissions, jobs.use and jobs.world.worldnamehere are given for each world. pay near spawner is also set to true.

**Comment by Lord-Lofi** [comment]
Also wanted to note i have the latest version of vault (1.7.3) and essentials x (2.18.1.14)

**Comment by montlikadani** [comment]
Are you sure that you're not on `Creative` world?
Make sure that you're in survival mode not in creative.

Re-enable `allow-pay-for-durability-loss` in generalConfig, if you don't understand what this option do.

**Comment by Lord-Lofi** [comment]
Haha smh, i had disable the durability loss config setting because in the way way older config, i was confused about the meaning. Thanks for solving my dumb mistake.
