### ISSUE TITLE
Line duplication when saving to the business point database.

### ISSUE THREAD

**Issue by AxelJoue** [Zrips/Jobs#939]
**This bug is still valid and has not been fixed on version 4.16.2 :** https://github.com/Zrips/Jobs/issues/898

After a while you might need to test your plugin to see if the bug this product, because it’s still the third or fourth time that you are told and that the problem is still there.
And if you can release an update from when you have fixed the problem, that would be great because me and other people are waiting for this problem to be fixed so that our players can finally enjoy the system again.

**Comment by montlikadani** [comment]
This issue can't reproducable here. Jobs have many of data that needs to be saved and users are still requesting to add more. But we not. I don't saw users who had the same issue like this. I think you should re-generate your database and seeing that this issue still reproduce. Also the userID is not used everywhere only used to get the players data in some cases.

**Comment by AxelJoue** [comment]
**I just reset it that’s the result :**

When the operation was normal the user line was modified to update the number of points. Now it duplicates. Is this normal operation?

However, when the data is saved in a local file the problem does not occur.

_(The other users in my opinion not noticed the problem, because myself I did not notice it, there are 2 people among the 1,700 others in my community who have pointed it out to me.)_

![image](https://user-images.githubusercontent.com/64502429/95011865-2abc9480-0634-11eb-8c5e-8d29dbc1585f.png)

**Comment by Zrips** [comment]
pointInfo.getDbId()
