### ISSUE TITLE
quests not working, any can help ?

### ISSUE THREAD

**Issue by SliderKP** [Zrips/Jobs#941]
in the latest version of jobs (4.16.2 on spigot page) quests dont working T_T

/jobs quests > No missions avaible

before the update, i have the quests working fine... my job with quest:

Quests:
  '1':
    Name: Leñador
    Objectives:
    - Break;oak_log;50
    RewardCommands:
    - eco give [playerName] 1000
    - msg [playerName] Completaste la mision de Leñador y obtuviste 1000 de dinero
      y cofre de gemas!
    - voucher give gemasRandom 1 [playerName]
    RewardDesc:
    - Romper 50 bloques de madera
    - Obtendras Dinero y Gemas

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/issues/936
