### ISSUE TITLE
PayForCombiningItems: false option doesn't work

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/Jobs#942]
The config option PayForCombiningItems: false does not work in all cases. If at least one piece of armour is damaged, you will still be rewarded for combining the items:
https://imgur.com/a/T5dBdaC

It's because you just check wether there are two equal items next to each other while iterating through inventory: 466b1ce#diff-e094452f709d92d9ec5f71a3e933b6f8R588
Unfortunatly we have no idea how to fix it so we can't open a pullrequest. Hopefully you can fix this issue :)

Jobs 4.16.2
Paper 1.16.3 - 204

**Comment by montlikadani** [comment]
Can't reproduce, works like a charm here. There are another commit for it: https://github.com/Zrips/Jobs/commit/9545af4dd656a0598e555840f8bcd37b9146ad53#diff-e094452f709d92d9ec5f71a3e933b6f8 which is working.

**Comment by TheoRetisch1** [comment]
Yeah, I linked the wrong commit, sorry. But the latest commit doesn't work either. Here is my testsetup:
![Schmied_1](https://user-images.githubusercontent.com/24480321/95022549-56616e00-0678-11eb-9d94-799e66142be6.png)
![Schmied_2](https://user-images.githubusercontent.com/24480321/95022552-5a8d8b80-0678-11eb-8a8a-bb4b899b3689.png)
![Schmied_3](https://user-images.githubusercontent.com/24480321/95022556-5d887c00-0678-11eb-9acc-aafdadade8b6.png)
![Schmied_4](https://user-images.githubusercontent.com/24480321/95022558-60836c80-0678-11eb-945b-0d5ec8c98eee.png)

Jobs 4.16.2
Paper 1.16.3 - 204

**Comment by montlikadani** [comment]
I still don't get any of job xp increase when I'm repairs an item. I think you have duplicated diamond_pickaxe with repair action given in jobConfig.

**Comment by TheoRetisch1** [comment]
We have no duplicate entries in jobConfig. I have just checked it. Also, the payment does not come from the repair action, but from the crafting action. Furthermore the crafted result is not taken out of the field with shift, but dragged and dropped from the crafting field into the inventory.

**Comment by kikelkik** [comment]
Did you forget to commit some changes? 
https://github.com/Zrips/Jobs/blob/master/pom.xml#L8 is building 4.16.1 versions. Maybe some other changes are not up to date yet.

**Comment by TheoRetisch1** [comment]
We made a mistake testing it, it works like a charm! Thank you :)

**Comment by kikelkik** [comment]
Did you forget to commit some changes?
https://github.com/Zrips/Jobs/blob/master/pom.xml#L8 is building 4.16.1 versions. Maybe some other changes are not up to date yet.
