### ISSUE TITLE
Jobs.Max permission stacks instead of finding highest

### ISSUE THREAD

**Issue by GenSecrets** [Zrips/Jobs#943]
***Description:***
If a player has multiple `jobs.max.<amount>` permissions set, it stacks the <amount> rather than looks for the highest. So for instance, if Steve has `jobs.max.3` and `jobs.max.7` set, their max jobs they can join will be 10, when ideally it should be 7 since seven is the higher of 3 and 7. 

***Reproduction steps:***
Join a server, and do the following
- Apply the perm: jobs.max.2 
- Join 2 jobs, attempt to join the 3rd and it will say you're at your max (2 total jobs)
- Apply the perm: jobs.max.3
- Join 3 additional jobs. It will allow you to join them. Attempt to join one more, it will say you're at your max. (5 total jobs)
- Apply the perm: jobs.max.1
- Join 1 additional hob. It will allow you to join it. (6 total jobs)

***Ideal steps:***
- Apply the perm: jobs.max.2
- Join 2 jobs successfully, attempting to join a third will error
- Apply the perm: jobs.max.1
- Attempting to join any more jobs will error
- Apply the perm: jobs.max.3
- Join 1 job (now 3 jobs total have been joined), attempt to join another and it errors

---

**Server Type:** 
Paperspigot

**Plugin info:**
Jobs (4.16.1)

**Relevant plugins:**
Luckperms (5.1.107)

**Comment by montlikadani** [comment]
It should count the max job numbers, because you granted these two permission into a group/user. I don't see why this not good.

**Comment by GenSecrets** [comment]
Example:
In the game, we have items that will give out a permission `jobs.max.2` and later in the game they can obtain an item that gives them `jobs.max.3`. This would mean their MAX jobs is 3, not add them to 5.

If it's intended to add, maybe rename the permission to `jobs.addmax.<amount>` ????? or make an additional permission, one for max (the actual max total) and one for addmax ?

**Comment by GenSecrets** [comment]
Also, with the current setup, if we want to add only 1 job to the user's max, we'd have to remove all of their `jobs.max<amount>` permissions and set `jobs.max.2`, then so on and so forth. We can only give a person the permission `jobs.max.1` once, not counting for the "max jobs" default in the config

**Comment by montlikadani** [comment]
> Jobs (4.16.1)

Ah I see that you are on this version, You should update now, because there is a fix for your issue: https://github.com/Zrips/Jobs/pull/926

**Comment by GenSecrets** [comment]
ahh, perfect, will update and give it a try 👍 
We've been seeing this for a couple weeks and were on the latest(4.16.1) when we noticed this issue had started, release of 4.16.2 slipped under my eye haha. Will update then and comment back here once that's done! Thanks!

**Comment by GenSecrets** [comment]
Confirmed this is fixed in **Jobs 4.16.2** after we just got the update pushed through our test servers then to live.
Thanks!

**Comment by GenSecrets** [comment]
Is there a way to find all people who have joined jobs past their max jobs limit?

While this was a bug, some people on our server have joined jobs past the intended max(could be 6 people, could be 200 people). So now that we've updated and fixed this underlying issue, their "Joined Jobs" is greater than their "Max Jobs". How do we find who all is like this right now?

**Comment by montlikadani** [comment]
`/jobs fire` and check database

**Comment by GenSecrets** [comment]
Gotcha - I know we can fire the ones who are over, I guess that means database is the best/only way to find anyone who's jobs_joined is greater than max_jobs?

**Comment by montlikadani** [comment]
`/jobs playerinfo` prints some things about the given player
