### ISSUE TITLE
money from mobs 

### ISSUE THREAD

**Issue by 100petr** [Zrips/Jobs#946]
**Description of issue:**
Players earn money by killing mobs from a slimefun electricspawner. Not from normal spawners. (I don't want to they get money from the electricspawners)
**Server Type (Spigot/Paperspigot/etc):** 
Paper 
**Server Version (using `/ver`):** 
Paper version git-Paper-216 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
**Relevant plugins (Delete if this isn't needed):**
slimefun, electricspawners

**Comment by montlikadani** [comment]
Disable `enable-pay-near-spawner` in generalConfig

**Comment by 100petr** [comment]
I have it set.

**Comment by montlikadani** [comment]
Then "electricspawner" does not supports `CreatureSpawnEvent` which will get fired when an entity spawns from egg/spawner. You should contact the author of that plugin to make available for other plugins to call `CreatureSpawnEvent` to avoid for "spawner" plugins adding as dependency.

**Comment by 100petr** [comment]
ok.
