### ISSUE TITLE
Explaination for what "points" do

### ISSUE THREAD

**Issue by Beetrootmonkey** [Zrips/Jobs#949]
I've been searching for 30 minutes straight, and I found NO resource explaining what experience, income and points do.

From what I understand, experience is directly used to level up the player's job level. That's a no-brainer.
Income is propably used to buy stuff. Easy.
But what the hell do "points" do?

Would you be kind enough to give players a brief description of what these three resources are used for? Neither on the bukkit nor on the spigot page does it say anything about it. The config has good has good descriptions, but even it doesn't say anything about what stuff does.
You do have a wiki that's very much suited for something like that. And if I'm just too dumb to find already existing info please let me know where to find it.

**Comment by montlikadani** [comment]
Translate income, experience and points to your language and you will understand. Income is used to increase your Vault money account, points is used for JobsReborn related thing, but it can be found in some plugins as a dependency, experience is increasing the player job level to level-up in jobs and getting some rewards.
