### ISSUE TITLE
[BUG] Moneyboost and Expboost not working. v4.16.2

### ISSUE THREAD

**Issue by Tomi010817** [Zrips/Jobs#950]
### Description of issue:
Apparently on version 4.16.2 of the plugin, the commands for moneyboost and expboost don't work properly. When you run the commands, they do show the message correctly, but they won't really change your earnings at all.
I just confirmed this bug on a localhost with the default config of the plugin. 

---
### Additional:
I also wanted to talk about a misbehavior of this moneyboost and expboost thing, but I'm not sure if it keeps happening on the newer versions of Jobs since it used to happened me on an older version that I was using. So I remember that whenever I set a multiplier rate with decimals, it would not work properly or it would be rounded, for example "1.75" as a multiplier rate. But again, I'm not sure if it has been fixed on newer versions and I can't prove it out since now the command doesn't even work well.

---

**Server Type (Spigot/Paperspigot/etc):**
Spigot

**Server Version (using `/ver`):** 
1.8.8

Regards!

**Comment by montlikadani** [comment]
`/jobs moneyboost jobName number` the correct usage for boost.

**Comment by Baylorai** [comment]
@montlikadani how does this help the problem as they said they was using the command, I’m having this problem as well on my server, it shows it works and everything, puts it into the global boost but the final boost is 0

**Comment by Tomi010817** [comment]
thanks for fixing this @montlikadani !
