### ISSUE TITLE
Unable To Disable Pay For Pet Kills

### ISSUE THREAD

**Issue by WhatsTheBadNews** [Zrips/Jobs#951]
***Description of issue:** In Jobs 4.16.2, I am unable to disable pet pay for Hunter job. I tried setting the jobs.petpay permission to false, but that did not work. And as far as I can tell, there is no config option to disable it.

**Server Type (Spigot/Paperspigot/etc):** Tuinity (Paper)

**Server Version (using `/ver`):**  MC 1.16.3, latest build of Tuinity

**Comment by montlikadani** [comment]
Players not getting paid if they don't have petpay permission. Remove it, or set it to `jobs.petpay.-1`

**Comment by WhatsTheBadNews** [comment]
I just tested on a clean server with no permissions setup and fresh jobs config. Pet kills pay with hunter job. Setting `jobs.petpay.-1` did not work either.
