### ISSUE TITLE
Players Missing In Gaps Between Pages of /jobs top

### ISSUE THREAD

**Issue by WhatsTheBadNews** [Zrips/Jobs#952]
***Description of issue:** On my server, there is an issue with people missing from the pages of /jobs top. There seems to be a gap of missing people between each page of the leaderboard.

Here is the example of one player:
![image](https://user-images.githubusercontent.com/29821149/95657774-e28dee00-0adb-11eb-8089-bdced1ad2429.png)
![image](https://user-images.githubusercontent.com/29821149/95657777-eb7ebf80-0adb-11eb-98e5-e37973fd6420.png)
Eden333 should clearly be on the 2nd page of` /jobs top fisherman`.

Here is another example. We know for certain that there are people between level 113 and 145 in Hunter job, but for some reason they are excluded from the leaderboard.
![image](https://user-images.githubusercontent.com/29821149/95657832-4dd7c000-0adc-11eb-92e2-5bec7ef88f69.png)
![image](https://user-images.githubusercontent.com/29821149/95657836-56c89180-0adc-11eb-85cf-936812996273.png)

**Server Type (Spigot/Paperspigot/etc):** Tuinity (Paper)

**Server Version (using `/ver`):** MC 1.16.3, latest build of Tuinity

**Comment by Zrips** [comment]
Could you provide your database for testing? Or atleast check missing player entries in database to make sure that its in correct format and contains jobs id and not only its name in the record

**Comment by WhatsTheBadNews** [comment]
@Zrips I've attached a ZIP with my database.
[jobs.sqlite.zip](https://github.com/Zrips/Jobs/files/5458523/jobs.sqlite.zip)

**Comment by Zrips** [comment]
07e97f50ae79d076b9b2adfc9d467839ee402a87
Thanks for the db
