### ISSUE TITLE
Jobs Moneyboost/expboost not showing the final bonus 

### ISSUE THREAD

**Issue by Baylorai** [Zrips/Jobs#954]
***Description of issue:**
When I try and add a boost to the server, it shows its going on no errors, no warning no nothing, but then when I check /jobs bonus miner the final bonus shows 0.0% but the Global bonus shows +50.0%, Im using version 4.16.2 for jobs, I dont understand why its not working as no errors or anything pop up in console or anything when doing the command /jobs moneyboost [jobname] [rate]
---

---

**Server Type (Spigot/Paperspigot/etc):** 
Spigot

**Server Version (using `/ver`):** 
1.16.3

**Comment by montlikadani** [comment]
#950
