### ISSUE TITLE
Stripping of wood is not rewarded

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/Jobs#955]
After the update from version 4.16.2 to version 4.16.3 the stripping of wood is no longer rewarded. This is probably due to the following commitment: https://github.com/Zrips/Jobs/pull/945

config: 
```  Break:
      STRIPPED_OAK_LOG:
        income: 1.03
        experience: 1.03
      STRIPPED_SPRUCE_LOG:
        income: 1.02
        experience: 1.02
      STRIPPED_BIRCH_LOG:
        income: 1.46
        experience: 1.46
      STRIPPED_JUNGLE_LOG:
        income: 1.27
        experience: 1.27
      STRIPPED_DARK_OAK_LOG:
        income: 1.28
        experience: 1.28
      STRIPPED_ACACIA_LOG:
        income: 2.57
        experience: 2.57
```
Paper 1.16.3 - 233
Jobs 4.16.3

**Comment by montlikadani** [comment]
> This is probably due to the following commitment: #945

No, read what is changed in that PR.

From where you got the new jar file? From discord?

**Comment by TheoRetisch1** [comment]
Yes I got the jar from the discord dev-releases channel. What am I doing wrong?

**Comment by montlikadani** [comment]
Send here your generalConfig, paste into a paste server

**Comment by TheoRetisch1** [comment]
Thanks for helping!
generalConfig: https://pastebin.com/LGF4ZHUq
