### ISSUE TITLE
Block ownership: smokers, blastfurnaces, furnaces all count towards the same Furnace ownership limits

### ISSUE THREAD

**Issue by GenSecrets** [Zrips/Jobs#956]
***Description of issue and replication steps:**
Place 50 furnaces, 50 blast furnaces, and 50 smokers down on the ground. Run "/jobs clearownership" so that you have absolutely nothing registered.

- Give yourself `jobs.maxfurnaces.500` and register 1 furnace (just right click to use the furnace). It will say **"Registered job ownership for furnace: 1/500"**
- Now right click a smoker and it says **"Registered job ownership for furnace: 2/15"**. See the issue here is that the "2" should actually be a "1". It shouldn't count the smoker as a furnace. "Furnace" should say "Smoker". It says "15" because smokers aren't tied to the maxfurnaces permission.
- Give yourself `jobs.maxsmokers.400` and right click a smoker again. It says "**Registered job ownership for furnace: 3/400**". Notice here, the 3 increased again which includes 2 smokes and 1 furnace. The 400 is from the maxsmokers permission.
- Now right click a blastfurnace and it says **"Registered job ownership for furnace: 4/15"**. Same issue as above. "4" because it's 2 smokers, 1 furnace, 1 blast furnace. "15" because that's the default and we've not given ourselves the `jobs.maxblastfurnaces.###` permission yet. 

If a player has `jobs.maxfurnaces.50` and `jobs.maxblastfurnaces.50`, ideally they would be able to register 50 blast furnaces, 50 furnaces, and 50 smokers to work for them. However with the current setup, this means they could have 49 furnaces ant 1 blast furnace and be at their max of 50 altogether because the plugin is counting them towards the same value.

I've personally not tested if other blocks could be doing the same thing? I **did** look and made sure that brewing stands are not falling into this category, which is a good thing, just seems to be the 3 blocks mentioned above. I have no personal experience if there are other blocks like smokers/furnaces/blast furnaces that can do this as well

---

**Server Type:** 
Paperspigot

**Relevant plugin information:**
Jobs (ver:  4.16.2)

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/3059833910e88c903e5b25b76de976ed53b1ec1c, this commit should fixes this
