### ISSUE TITLE
Compatibility with vehicles plugin

### ISSUE THREAD

**Issue by AnthoBear** [Zrips/Jobs#957]
Hi, I am a user of your **Jobs Reborn** plugin and I would like them to be compatible with the **Vehicles plugin**.

**Link plugin:**
https://www.spigotmc.org/resources/%E2%9C%88%EF%B8%8Fvehicles-no-resourcepacks-needed.12446/

When players use the drill vehicle, they are paid as if they normally mine with the pickaxe.  This is fast, giving too much advantage by getting money and experience in your Jobs plugin.

The plugin generates a BlockBreakEvent which you can listen to, therefore you could add a check of (player.getVehicle () == null) which can be activated and deactivated.

Any extra technical question, the developer of the vehicle plugin is willing to answer it (@Pollitoyeye)
Discord: https://discord.com/invite/buUaUHd

Thank you for reading :)

**Comment by montlikadani** [comment]
You can use `disablePaymentIfRiding` in generalConfig
