### ISSUE TITLE
Bug with the titleconfig.yml of jobs

### ISSUE THREAD

**Issue by DjeyMute** [Zrips/Jobs#959]
Hello,

The titleconfig.yml don't workd with the last release Jobs-v4.16.3.jar .
I have the chat-display to "full".

My config is great : 

Titles:
  Apprentice:
    Name: Apprenti
    ShortName: A
    ChatColour: YELLOW
    levelReq: 0
  Novice:
    Name: Novice
    ShortName: N
    ChatColour: GREEN
    levelReq: 15
  Initie:
    Name: Initié
    ShortName: I
    ChatColour: DARK_GREEN
    levelReq: 30
  Pro:
    Name: Pro
    ShortName: P
    ChatColour: AQUA
    levelReq: 45
  Expert:
    Name: Expert
    ShortName: E
    ChatColour: RED
    levelReq: 60
  Genie:
    Name: Génie
    ShortName: G
    ChatColour: DARK_RED
    levelReq: 75

---

Server PaperSpigot last version
Version 1.16.3

Thk in advance for the support and repair.

**Comment by montlikadani** [comment]
Can't reproduce. It works for me. Show a screenshot for proof in chat formatting and make sure `modify-chat` is enabled.

**Comment by DjeyMute** [comment]
![2](https://user-images.githubusercontent.com/47302852/95885027-13d91900-0d7d-11eb-8e3a-0a5498bc75d4.png)

**Comment by DjeyMute** [comment]
![3](https://user-images.githubusercontent.com/47302852/95885041-16d40980-0d7d-11eb-9f53-e51c4301d76b.png)

**Comment by montlikadani** [comment]
There is no any {jobs} placeholder added to JobsReborn, use `%jobsr_user_displayhonorific%`. Also Jobs have own built chat-formatting which should work with titles. [Available placeholders](https://github.com/Zrips/Jobs/wiki/Placeholders)

**Comment by DjeyMute** [comment]
# Modifys chat to add chat titles. If you're using a chat manager, you may add the tag {jobs} to your chat format and disable this.

It's written in the generalconfig ...

**Comment by montlikadani** [comment]
Whats the result in game within chat?

**Comment by DjeyMute** [comment]
Only the name of the Jobs
![1](https://user-images.githubusercontent.com/47302852/95887021-a5498a80-0d7f-11eb-8675-d70fcab581a6.png)

**Comment by montlikadani** [comment]
Do you have `Mineur` title set in titleConfig? What you sent before does not have.

**Comment by DjeyMute** [comment]
> Do you have `Mineur` title set in titleConfig? What you sent before does not have.

No because the title wa based to the level of job. Mineur is the name of the Jobs.



> Which version of jobs you used before you installed the dev release?

The last version in spigot.

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/2c5dcbc5a1562b0c1765ab0ce6a8619ce550a48a, This should fixes this issue. You can get the new jar file from dev-releases channel after I uploaded a new one (see the date time).
