### ISSUE TITLE
moneyboost and expboost doesn't work.

### ISSUE THREAD

**Issue by Typheonn** [Zrips/Jobs#961]
***Description of issue:**
When i use command /jobs moneyboost or /jobs expboost, I don't earn more money or experience by doing tasks.

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** paper-192 (1.16.3)

**Plugins :**
JobsReborn (4.16.2)

**Comment by montlikadani** [comment]
Can we see an output of `/jobs bonus` from game?

**Comment by Typheonn** [comment]
I get this screen with command /jobs bonus
![image](https://user-images.githubusercontent.com/34997962/96013103-2a4aa780-0e45-11eb-801e-65968f28592c.png)

**Comment by montlikadani** [comment]
Seems that you have exp boost set globally which should works for specific jobs. Make sure that you don't have any exp limitations enabled in generalConfig.

**Comment by montlikadani** [comment]
Seems like it was an issue with 4.16.2 version. In the next version should works.
