### ISSUE TITLE
Piglins not dropping Hunter experience

### ISSUE THREAD

**Issue by PeterDorvay** [Zrips/Jobs#962]
***Description of issue:**
Zombie Piglins are not giving Hunter experience in 1.16.1. They give money, but no experience. I have specified the amount of experience to give in jobConfig.yml but it doesn't seem to be working. This is on jobs 4.16.2

![image](https://user-images.githubusercontent.com/21300105/96151173-f95b8880-0ebf-11eb-8770-3bf3dd5e4122.png)

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## PASTE ERROR HERE ##
####################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Server Type (Spigot/Paperspigot/etc):** 

**Server Version (using `/ver`):** 

**Relevant plugins (Delete if this isn't needed):**

**Comment by montlikadani** [comment]
Did the Piglins come from spawners?

**Comment by PeterDorvay** [comment]
They came from a natural spawner. If I spawn them using spawn eggs, they also give no experience

**Comment by montlikadani** [comment]
You should enable `enable-pay-near-spawner` in generalConfig

**Comment by PeterDorvay** [comment]
It is enabled, but the issue still stands

**Comment by montlikadani** [comment]
Under `zombified_piglin` seems there is no experience value set. Is this your issue?

**Comment by PeterDorvay** [comment]
Yes that was it :) Thank you
