### ISSUE TITLE
When a block of any wood type is dropped.......

### ISSUE THREAD

**Issue by ruthlesslure** [Zrips/Jobs#963]
When a block of any wood type is dropped then picked back up again by the same person, they get money for it is this an error or something else. 

default configs.  

---

Server Type Paperspigot 

Server Version using git-Paper-189 (MC: 1.16.2) (Implementing API version1.16.2-R0.1-SNAPSHOT)

**Comment by montlikadani** [comment]
Can't reproduce. Can you make a gif/video about this issue?
