### ISSUE TITLE
Overall daily quest

### ISSUE THREAD

**Issue by AlexanderMoebius** [Zrips/Jobs#964]
**Description of new idea or improvement on existing one**
Add a new permission to give how many quests a player can complete in a day for all jobs. The permission should be given as `jobs.maxquest.3.all`, so if it granted to a player, this user only can do 3 quests in one day for overall jobs (not job specific).

**Comment by montlikadani** [comment]
There is an option in jobConfig where how many quest can be done in one day, called `maxDailyQuests`, this does not requires any of option to be added.

**Comment by AlexanderMoebius** [comment]
But this option is only per Job and not for all jobs

**Comment by montlikadani** [comment]
What about if we have a permission `jobs.maxquest.3.all`, then it would affect for all jobs. Is this better than a new config option?

**Comment by AlexanderMoebius** [comment]
But this would only apply for active jobs, wouldn't it?
So that there can be x quests active but when a quest is finished the next quest from another job would start?!

**Comment by montlikadani** [comment]
No, the quests are still active but that quest can not be completed again at that day. The completed quests not start again when this permission granted to a player, quests will reset at the next day. This permission is for how many quest can be completed in one day for all jobs.

**Comment by AlexanderMoebius** [comment]
ok, then there is no need for a new config option.
thx!

**Comment by AlexanderMoebius** [comment]
Is this permission restrictive?
It doesn't work for me

**Comment by sh1mrr4** [comment]
It I understand it correctly, they were just asking what would be the better thing to have, not that it already exists. 

Either way, I would greatly appreciate either a permission or a config setting like that. Though the permission might make customization easier (e.g. to give people with a certain rank more quests per day).
