### ISSUE TITLE
quests objectives do not trigger/count correctly

### ISSUE THREAD

**Issue by Sandukhan** [Zrips/Jobs#967]
Hi,
since i updated to latest version of jobs 4.16.2 (29 Sep), quests objectives like "Break;DARK_OAK_LOG;128" do not trigger/count correctly, for every time i break a oak log. There seems to be a delay of 1-2 sec before the plugin can registers a new breaking event.

That been said, it only applies to quests, the nomal payment works fine.
Same issue i seen with furnaces and again only for quests.

How many quests can jobs handle? 

---

Paper 1.16.3 (220)

Jobs Reborn 4.16.2 (29 Sep)

Vault 1.7.3-b131

**Comment by montlikadani** [comment]
There is payment delay called `economy-batch-delay` in generalConfig which can be decreased.

**Comment by Bedah95** [comment]
Same problem here.

> 
> 
> There is payment delay called `economy-batch-delay` in generalConfig which can be decreased.
No effect.


Payment and leveling works in all versions correctly.
Only the quests don´t count the total amount of **destroyed** blocks in versions 4.16.2 and 4.16.3. No problems by placing blocks.
4.16.1 runs fine.

```
Quest:
      Wheat:
        Name: Wheat
        Objectives:
        - Break;WHEAT-7;700
        - Place;WHEAT-0;700
```

Paper 1.16.3 (238)
Jobs Reborn 4.16.2,4.16.3

**Comment by sh1mrr4** [comment]
I am experiencing the same issue with Jobs 4.16.2 and Paper 1.15.2 (384)

**Comment by Bedah95** [comment]
No problem with Paper 1.16.4 (275) and Jobs 4.16.3.
