### ISSUE TITLE
Problem with the pay of Wither Skeleton

### ISSUE THREAD

**Issue by DjeyMute** [Zrips/Jobs#968]
Hi,

I have a problem with the pay money and xp for wither_skeleton.
It's not work.

![1](https://user-images.githubusercontent.com/47302852/96581209-c3f8d580-12d9-11eb-93d0-83c778ab43ee.png)

---

Server type : PaperSpigot 240

Server version : 1.16.3

Version Jobs release : 4.16.3

**Comment by montlikadani** [comment]
Did you spawned that entity from spawner?

**Comment by DjeyMute** [comment]
No, natural spawning.

**Comment by montlikadani** [comment]
Can't reproduce. Works like a charm here.

**Comment by DjeyMute** [comment]
But my configuration is good :( 
All jobs work fine just this wither_skeleton don't work.
I have tested on my 1.15 server and it's work fine.
But on my server 1.16 with the last release it's doesn't work.

**Comment by montlikadani** [comment]
Still works here. Make a gif/video for proof.

**Comment by DjeyMute** [comment]
Okey i go to do this.

**Comment by DjeyMute** [comment]
Okey I check again and it's work...
So I still have a problem.
But the "wither skeleton" was in the gui.
But not pay....

**Comment by DjeyMute** [comment]
https://youtu.be/WSaF_ry0wjs

**Comment by DjeyMute** [comment]
![2](https://user-images.githubusercontent.com/47302852/96869792-3f8c8b00-1470-11eb-8ec6-8b4795acbcbf.png)

**Comment by montlikadani** [comment]
Why you say naturally spawned even you're in the overworld and the only way to spawn withers with spawn egg or command?

**Comment by DjeyMute** [comment]
Because i have tested a few minutes ago with the natural spawn.

**Comment by montlikadani** [comment]
Natural spawn literally is not in the overworld. It should be in the nether.

**Comment by DjeyMute** [comment]
Yeah I'm in the nether. ^^

**Comment by montlikadani** [comment]
Show your generalConfig file

**Comment by DjeyMute** [comment]
[generalConfig.txt](https://github.com/Zrips/Jobs/files/5422768/generalConfig.txt)

**Comment by DjeyMute** [comment]
[generalConfig.txt](https://github.com/Zrips/Jobs/files/5422780/generalConfig.txt)

**Comment by montlikadani** [comment]
Enable `enable-pay-creative` & `enable-pay-near-spawner`

**Comment by DjeyMute** [comment]
In my tested server this options was set to false.
And it's work... :/

**Comment by montlikadani** [comment]
Yes, because in the video you're in creative

**Comment by DjeyMute** [comment]
I have tested in the nether with the natural spawn and in survival mode it's doesn't work

**Comment by DjeyMute** [comment]
The problem is that since the last update while the skeleton wither appears in the jobs browse when you kill a mob it does not give money or xp.

**Comment by montlikadani** [comment]
For me it gives. You have a plugin which overwrites the handling of killing entities. Take a look at other plugins, or if you don't know how to check event handling, then remove one by one. We can't help you to anymore, because wither skeleton literally works like a charm. Also wait for the new release, or download the dev version from discord.
