### ISSUE TITLE
3.9.3 not displaying job title

### ISSUE THREAD

**Issue by LeadMagnet** [Zrips/Jobs#97]
I was running 3.9.2 without issue. {jobs} parameter inserted into chat overlay permissions. All was working fine.

Now with 3.9.3 the preface in chat just shows "{jobs}" and not the actual job list. I have double checked the parameters and config settings to make sure nothing has changed. 

All jobs have the same setting: chat-display: shortjob

Changing this to shorttitle generates an error in the console.

Side note: The options available should be...

full, short, both, none

The current list of full, title, job, shortfull, shorttitle, shortjob and none makes no sense.

**Comment by Zrips** [comment]
Check if you have modify-chat: true in your generalConfig file.

**Comment by LeadMagnet** [comment]
Yes that is set "true". As I said this and all other settings worked fine with 3.9.2.

**Comment by Zrips** [comment]
Try running without any additional plugin as this can be caused by 3rd party plugin changing chat formating. or try to add {jobs} into prefix for your chat plugin and disable modify-chat

**Comment by montlikadani** [comment]
You don't joined a job. You need to join the job because if you not joined to job then not showing.
[commit](https://github.com/Zrips/Jobs/commit/9dfa9177d164058bdc3cf847b37d6ef6b0a779ef#diff-7560ad1fc16c719b73f931540e010119)
