### ISSUE TITLE
Break and Place action not work

### ISSUE THREAD

**Issue by BoomEaro** [Zrips/Jobs#973]
***Description of issue:**
Action Place and Break no longer work as expected.
If you join a miner's job, breaking any blocks will not give you money.
If you join the Builder's job, you will be able to receive money for placing blocks, however, for the destruction of the same blocks you will also receive money, although the Builder's work does not specify the Action break of these same blocks.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
The default config jobConfig.yml is used for the test:
https://github.com/Zrips/Jobs/blob/master/src/main/resources/jobConfig.yml

**Server Type (Spigot/Paperspigot/etc):** 
paper

**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-1615 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

Jobs version: 4.16.3, latest build

**Comment by montlikadani** [comment]
Send your generalConfig file into paste server

**Comment by BoomEaro** [comment]
Tested with the default config generalConfig.yml (deleted and the plugin recreated it)
Problem still exists.

**Comment by montlikadani** [comment]
Can't reproduce. Works like a charm here. By default `PlaceAndBreakProtection` is enabled. Disable that if you place and break the same block again.

**Comment by BoomEaro** [comment]
Strange and floating bug.
If you turn off the server, delete all plugin configs (so that the plugin recreates them), start the server, join builder or miner job, then the behavior that I described above is observed.

After restarting the server, the error disappears, but this error exists even now on my main server, where there was a restart more than once.

**Comment by montlikadani** [comment]
By default there are some options in generalConfig, which may affect the payment. The first option is the `enable-pay-in-creative`, which adds ability to pay in creative, second is `PlaceAndBreakProtection`, which prevents any of block place and break again, making tons of payment.

**Comment by BoomEaro** [comment]
The test is carried out in survival mode.
PlaceAndBreakProtection does not affect this behavior at all.

I also found out that in order to achieve this bug, you need to repeat everything I wrote above, but before, for example, break the redstone block, you need to put it somewhere.
As soon as the plugin gives out money, try to break another redstone block altogether, then for some reason it will count it too.
It's not even a matter of PlaceAndBreakProtection

**Comment by BoomEaro** [comment]
I can't repeat this bug on 4.16.1.
Probably between 4.16.1 and 4.16.2 something broke, because the problem appeared with 4.16.2.

**Comment by BoomEaro** [comment]
I managed to find the error in the code.
Here's a logical error:
https://github.com/Zrips/Jobs/blob/master/src/main/java/com/gamingmesh/jobs/listeners/JobsPaymentListener.java#L387-L388

Since you refactor recently, you also decided to fit everything into one condition:
"fp.getTime() > System.currentTimeMillis() && fp.getInfo().getName().equalsIgnoreCase(bInfo.getName()) || fp.getInfo().getNameWithSub().equalsIgnoreCase(bInfo.getNameWithSub())"

However, the result will always be true.
Your logic is as follows:
"a && b || C"
Based on the truth table and the intended behavior, it will always be true.
You need to do this:
"a && (b || c)"
In this case, if "a" is true, then a test with "b" and "c" is performed.
That is, do it like this:

"fp.getTime() > System.currentTimeMillis() && (fp.getInfo().getName().equalsIgnoreCase(bInfo.getName()) || fp.getInfo().getNameWithSub().equalsIgnoreCase(bInfo.getNameWithSub()))"

(I am referring to this commit that broke everything: https://github.com/Zrips/Jobs/commit/fe66a49c562217478a41a73354062e8f3c22eebb)

I think it's worth looking at all the commits where there were such changes and fixing the logic.

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/21673860c7b784189c8695a62308873e343f28c6
Next time would be good a PR to fix these issues.
