### ISSUE TITLE
permission boosts dont work for negative values. 

### ISSUE THREAD

**Issue by IgnisCraft** [Zrips/Jobs#979]
jobs.boost.miner.exp.-0.5 < these permission nodes no longer work. Is there an alternate or a new way of doing this? I am trying to have a temp node applied when a player applies haste potions.

**Comment by montlikadani** [comment]
How do you think that it not works? More information? What version of jobs you using? Which of the permission plugin you using?

**Comment by IgnisCraft** [comment]
1) Newest version available on the spigot page (4.16.2)
Luckperms newest version
Paper spigot 1.16.3
2) I applied the permission exactly as shown on the site.
3) the perm boosts work fine with a positive integer.
4) It shows on /jobs bonus

Really isn’t much information to provide other than the version. The boosts don’t allow a negative value and I wasn’t able to find a work around

**Comment by Zrips** [comment]
874fd3ce5c50ce6bdd3fff6af2962a31506452e4
