### ISSUE TITLE
Milestones for the jobs

### ISSUE THREAD

**Issue by ArnoPompio** [Zrips/Jobs#980]
**Description of new idea or improvement on existing one**
Milestones for the jobs
> Levels 
> Quests Finished
> Blocks mined (miner, woodcutter, ...) / Block placed (builder, ...) / ...
...

**Detailed information what should do what and when**
When a player hits a milestone, like being level 10 at Miner, he is able to get a reward (so run a command for this player).

I believe it's enough explicit heh. Thanks

**Comment by montlikadani** [comment]
Take a look at `commands` https://github.com/Zrips/Jobs/blob/master/src/main/resources/jobConfig.yml#L533-L550
