### ISSUE TITLE
Incorrect Maven setup

### ISSUE THREAD

**Issue by PyvesB** [Zrips/Jobs#982]
Hello there! 👋🏻 

I'm helping @n54b adding Jobs Reborn support to the Advanced Achievements plugin (see https://github.com/PyvesB/advanced-achievements/pull/874).

The API documentation in the README outlines the following:
```
<dependency>
    <groupId>com.github.Zrips</groupId>
    <artifactId>Jobs</artifactId>
    <version>LATEST</version> <!-- Change the LATEST to the current version of jobs -->
    <scope>provided</scope>
</dependency>
```

This suggests that I should be replacing `LATEST` with `4.16.2`. Unfortunately, this does not work. JitPack only supports specifying versions from a release tag, commit hash or master-SNAPSHOT, as highlighted in its [documentation](https://jitpack.io/docs/). As you've got no release tags, specifying `4.16.2` or any other version simply doesn't work, users instead have to specify a commit hash or keep on pulling new builds from master. This isn't great.

Could you please start tagging new plugin releases or update the documentation?

**Comment by montlikadani** [comment]
Whats the problem with `master-SNAPSHOT`? It is well good, because you don't need to every time check if there is a new version of this plugin, and every time there is a commit push, you builds your project, so you will get the latest changes.

**Comment by PyvesB** [comment]
> Whats the problem with `master-SNAPSHOT`?

This is generally considered very bad practice. It means that Maven builds are no longer reproducible: build results may vary from one day to another without anything actually changing in the project using the dependencies. If ever you release a new major version of the API with breaking changes, or mistakenly mess up with the API in a commit, you break all dependent projects and block their builds. Old versions of Maven supported the `LATEST` and `RELEASE` keywords out of the box for versioning, but they dropped support for that years ago in Maven 3.x for these exact reasons. Similarly most programming languages and tools nowadays enforce pinning down of versions (e.g. _Pipfile.lock_ in Python, _package-lock.json_ with Node.js, _Gemfile.lock_ in Ruby, etc.).

When using JitPack, there's an additional problem: artefacts are built lazily. If you push a new commit to JobsReborn and I'm the first person to do a Maven build on a project consuming the JobsReborn API, the artefact corresponding to `master-SNAPSHOT` will only be created at that point. That's a ~3 minute hit every single time (according to [these build logs](https://jitpack.io/com/github/Zrips/Jobs/master-3d48656311-1/build.log) anyway). As an example downloading the dependencies for Advanced Achievements takes less than a minute, so integrating with JobsReborn with your proposed `master-SNAPSHOT` effectively multiplies my build time by four. If every single dependency I rely on did this, building my plugin would take several hours.

**Comment by montlikadani** [comment]
> This is generally considered very bad practice. It means that Maven builds are no longer reproducible: build results may vary from one day to another without anything actually changing in the project using the dependencies. If ever you release a new major version of the API with breaking changes, or mistakenly mess up with the API in a commit, you break all dependent projects and block their builds. Old versions of Maven supported the `LATEST` and `RELEASE` keywords out of the box for versioning, but they dropped support for that years ago in Maven 3.x for these exact reasons. Similarly most programming languages and tools nowadays enforce pinning down of versions (e.g. _Pipfile.lock_ in Python, _package-lock.json_ with Node.js, _Gemfile.lock_ in Ruby, etc.).

I can assure you that if a broken commit is pushed, we can use the Travis CI build interface to check for any broken code changes that we missed and I don’t think anyone would build the maven/gradle project at exactly the time the commit pushed. By that I mean that we need an interface where the Jobs repository can be found and downloaded by URL using Maven or Gradle? Well, we're not going to host.

> When using JitPack, there's an additional problem: artefacts are built lazily. If you push a new commit to JobsReborn and I'm the first person to do a Maven build on a project consuming the JobsReborn API, the artefact corresponding to `master-SNAPSHOT` will only be created at that point. That's a ~3 minute hit every single time (according to [these build logs](https://jitpack.io/com/github/Zrips/Jobs/master-3d48656311-1/build.log) anyway). As an example downloading the dependencies for Advanced Achievements takes less than a minute, so integrating with JobsReborn with your proposed `master-SNAPSHOT` effectively multiplies my build time by four. If every single dependency I rely on did this, building my plugin would take several hours.

Build time depends on more than one specified repository. The first may be Internet access, which is usually not a problem (I mean, developers are aware of internet connection). The build time may even depend on access to the specified repository url, the number of requests that the page with the specified address can process at one time. JitPack is very lazy, but it can process download requests quickly as if you were using your own hosted repository interface. I use the jitPack repository in several projects, so far I have had no problems with it and the download request is as fast as my own host.

Note: if JitPack is not right for you, we will return to "library mode", which accepts external jar files as dependency.

**Comment by PyvesB** [comment]
> I can assure you that if a broken commit is pushed, we can use the Travis CI build interface to check for any broken code changes that we missed and I don’t think anyone would build the maven/gradle project at exactly the time the commit pushed. By that I mean that we need an interface where the Jobs repository can be found and downloaded by URL using Maven or Gradle? Well, we're not going to host.

This misses the point. Regardless of CI passing on your side, the Maven build will not be reproduceable on downstream projects - as pointed out this is really an agreed standard in the industry. Regardless of CI passing on your side, they'll be a point when you'll want to evolve the API and make a major version bump with breaking API changes for downstream projects.

I'm also unsure what you mean by "we're not going to host", no one is asking you to host anything, properly tagging releases as indicated in the JitPack documentation I linked is a couple of simple git commands or clicks in the GitHub UI.

> Build time depends on more than one specified repository. The first may be Internet access, which is usually not a problem (I mean, developers are aware of internet connection). The build time may even depend on access to the specified repository url, the number of requests that the page with the specified address can process at one time. JitPack is very lazy, but it can process download requests quickly as if you were using your own hosted repository interface. I use the jitPack repository in several projects, so far I have had no problems with it and the download request is as fast as my own host.

There is misunderstanding here as well. JitPack _cannot_ process requests quickly unless they're tagged. When you request the dependency form `master-SNAPSHOT` it first has to rebuild the whole JobsReborn dependency, then only can it publish it and return it to the project requesting it. That takes several minutes as you can see in the logs I shared. If you tag your releases, it will serve artefacts it's already built and published once. That's why you're observing it as being fast in other projects.

> Note: if JitPack is not right for you, we will return to "library mode", which accepts external jar files as dependency.

This is another feature strongly discouraged by Maven and which they plan to drop in future releases, as they did with `LATEST` and `RELEASE`.

**Comment by PyvesB** [comment]
Yet another reason for tagging releases properly: widely used tools such as Dependabot will otherwise get confused and pull out some old incorrect versions. See https://github.com/PyvesB/advanced-achievements/pull/886 as an example.

**Comment by montlikadani** [comment]
Now you can specify the Jobs latest version (4.16.3), using https://github.com/Zrips/Jobs/releases

**Comment by PyvesB** [comment]
Thank you! 👍🏻
