### ISSUE TITLE
Is exist %jobsr_user_maxbstandcount% and %jobsr_user_maxfurncount% but not %jobsr_user_maxjobscount%

### ISSUE THREAD

**Issue by broken1arrow** [Zrips/Jobs#983]
**Description of new idea or improvement on existing one**

We can only use %jobsr_maxjobs% some only give maxjobs from settings.

**Detailed information what should do what and when**

So we can see and players can see how many jobs they have and even to see if it something wrong with jobs.max. perm (In some newr version it was som problem with this perm, so nice if we can easier see if some problems) or if we give wrong amount for jobs.max. so can we spot it and easier to set it up with placeholders and manually type it in players current max.

I use this in a menu Like this &#FF4500 %jobsr_user_joinedjobcount%&b/&#FF45003&bst is better If i can do like this &#FF4500 %jobsr_user_joinedjobcount%&b/&#FF4500%jobsr_user_maxjobscount%&bst so I not need add number after (it get easier for me to not get it wrong and easy copy paste it in). In the paste, You cant see what the number is because of the colorcode.

I use deluxe menu (so that player see he have 8 jobs max total and if he buy more, the placeholder get update with players new max).

I can do it with furnaces and brewing stands so way not on how many jobs player can join?

**Comment by montlikadani** [comment]
I don't see why we need again a new placeholder for user maxJobs even the `%jobsr_maxjobs%` variable already returns the max amount of jobs that have given in jobConfig/generalConfig or at least with permissions. If player have max jobs permission, it will be overwritten the config values.

**Comment by broken1arrow** [comment]
> **Description of new idea or improvement on existing one**
> 
> We can only use %jobsr_maxjobs% some only give maxjobs from settings.
> 
> **Detailed information what should do what and when**
> 
> So we can see and players can see how many jobs they have and even to see if it something wrong with jobs.max. perm (In some newr version it was som problem with this perm, so nice if we can easier see if some problems) or if we give wrong amount for jobs.max. and easier to set it up with placeholders.
> 
> I use this in a menu Like this &#FF4500 %jobsr_user_joinedjobcount%&b/&#FF45003&bst is better If i can do like this &#FF4500 %jobsr_user_joinedjobcount%&b/&#FF4500%jobsr_user_maxjobscount%&bst so I not need add number after (it get easier for me to not get it wrong and easy copy paste it in).
> 
> I use delux menu (So add a new lore for how many jobs player can buy (so that can have 8 jobs total or buy more) and if I can easy copy paste it is faster to fix it right).
> 
> I can do it with furnaces and brewing stands so way not on how many jobs player can join?



> I don't see why we need again a new placeholder for user maxJobs even the `%jobsr_maxjobs%` variable already returns the max amount of jobs that have given in jobConfig/generalConfig or at least with permissions. If player have max jobs permission, it will be overwritten the config values.

It only give the max from generalConfig, not from perms as other do and I can get less of a mess when I use the placeholder. In short, I can easy copy paste this %jobsr_user_bstandcount%&b/&#FF4500%jobsr_user_maxbstandcount%&bst Brewingstands bot not on jobs because I have to add a number how many jobs player can join if he upgrades. Ingame it get like this "You use  5/10 jobs" , So i Have too manually remove 10 and add to higher number when player buy so he get more jobs . 
Go from this
`  Job_count3:
    material: stone_pickaxe
    hide_attributes: true
    enchantments:
    slot: 19
    priority: 6
    view_requirement:
      requirements:
        permission:
          type: has permission
          permission: jobs.max.3
    display_name: '&2&l⚜ Uppgradera antal Jobb ⚜'
    lore:
      - ''
      - '&6> &bDu använder&#8A2BE2 %jobsr_user_joinedjobcount%&b/&#FF45003&bst job.'
      - ''
      - '&8╔════════════════╗'
      - '&#0080ff   Vänster klicka för'
      - '&#0080ff   uppgradera till&#FF4500 4&#0080ff jobs:'
      - '&#d86044   Guld på kontot:&6  %vault_eco_balance_fixed% &eⒼ'
      - '&#d86044   Köp 4 jobs:&6 10.000 &eⒼ'
      - '&8╚════════════════╝'`
To this 
`  Brewing_links10:
    material: brewing_stand
    slot: 16
    priority: 2
    view_requirement:
      requirements:
        permission:
          type: has permission
          permission: jobs.maxbrewingstands.10
    display_name: '&2&l⚜ Uppgradera antal Brewingstands ⚜'
    lore:
      - ''
      - '&6>&b Du har länkat&#8A2BE2 %jobsr_user_bstandcount%&b/&#FF4500%jobsr_user_maxbstandcount%&bst Brewingstands'
      - ''
      - '&bUppgradera antalet länkade brewingstands,'
      - '&bdu får betalt för och du behöver jobbet'
      - '&bBrewer.%jobsr_user_maxbstandcount%'
      - ''
      - '&6> &3För ta jobbet:'
      - '  &f/&6jobs join Brewer '
      - '  &f/&6jobs browse &3För se alla jobb'
      - ''
      - '&8╔═════════════════╗'
      - '&#0080ff   Vänster klicka för'
      - '&#0080ff   uppgradera till&#FF4500 12&#0080ff länkningar:'
      - '&#d86044   Guld på kontot:&6  %vault_eco_balance_fixed% &eⒼ'
      - '&#d86044   Köp 12 länkningar:&6 12.000 &eⒼ'
      - '&8╚═════════════════╝'`

**Comment by broken1arrow** [comment]
> I don't see why we need again a new placeholder for user maxJobs even the `%jobsr_maxjobs%` variable already returns the max amount of jobs that have given in jobConfig/generalConfig or at least with permissions. If player have max jobs permission, it will be overwritten the config values.

As i say %jobsr_maxjobs% only show generalConfig max, not when you override this with permissions.
