### ISSUE TITLE
Smaller boost values taking precedence over larger ones

### ISSUE THREAD

**Issue by WhatsTheBadNews** [Zrips/Jobs#984]
In previous versions of Jobs, larger boosts values would overtake smaller ones. In the version that was released today (4.16.3), smaller boosts like jobs.boost.all.money.0.15 are overriding larger ones like jobs.boost.all.money.1

---

**Server Type (Spigot/Paperspigot/etc):**  Latest Tuinity (Paper)

**Server Version (using `/ver`):** MC 1.16.3

**Comment by montlikadani** [comment]
Yes, it has been changed. What's the problem with it?

**Comment by WhatsTheBadNews** [comment]
Well, as an example, we let players have 100% Global Income Boosts and 15% Personal Income Boosts. In older versions the 100% Income Boosts would always take priority over the 15% Income Boosts. But now, people who also have a 15% Income Boost active during a 100% Income Boost will only get the 15% Income Boost.

Is there any way for us to make the larger boosts take priority again or workarounds we can use? This change breaks the expected behavior our server was configured around.

**Comment by broken1arrow** [comment]
> Yes, it has been changed. What's the problem with it?

It odd if lower number override a higher number. But is it a reason for this?

**Comment by pacificminer** [comment]
Please fix this garbage.

**Comment by pacificminer** [comment]
@montlikadani The changes to Job boosting is the dumbest decision. It ruins the plugin. Please revert it. I'll pay.

**Comment by WhatsTheBadNews** [comment]
I've just tested on Job v4.16.4 and this problem still persists.

Method to test:
1.) Install Jobs and give jobs.use permission
2.) Join Woodcutter job
3.) Chop 1 log, this should (and does) give $1 as you have no boosts
4.) /lp group default permission set jobs.boost.all.money.0.15
5.) Chop 1 log, this should (and does) give $1.15 as you have a 15% boost
6.) /lp group default permission set jobs.boost.all.money.1
7.) Chop 1 log, this should give $2 as you have a 100% boost that should override the 15% boost you also have. However, the 15% boost overrides the 100% boost and you still only get $1.15 from chopping the log

**Comment by broken1arrow** [comment]
So he not fix it completely?

I has hold of update from 16.0 because of all problems, so hope he fix this too.

I think you can use this, if he cant fix the problem @WhatsTheBadNews 

https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Permission

**Comment by DjeyMute** [comment]
They no fix the problem in the dev build...

**Comment by Zrips** [comment]
32ffb88e9d96ad7cabe20915d827a6e6bb0b3a53
