### ISSUE TITLE
Boss Plugin Support

### ISSUE THREAD

**Issue by BobbyMere** [Zrips/Jobs#985]
Asking for the plugin [Boss](https://github.com/kangarko/Boss/wiki/Developer-API) to be added

Asking for the same function Mythicmobs has in tracking kills

**Comment by montlikadani** [comment]
You already reported a same issue, #604 
We removed in the 4.16.3 version, because it is not used by anyone and unnecessary to store this action.

**Comment by BobbyMere** [comment]
Wasn't aware it was ever added
