### ISSUE TITLE
Prevent Furnace and Brewing Stand Fill Ups

### ISSUE THREAD

**Issue by PackCraft** [Zrips/Jobs#988]
I think this options not working.
I'ts on true in my config but my players can use hopper to fil their furnace or brewing stand

**Comment by montlikadani** [comment]
Yes, thats normal thing. Players are able to fill up the furnaces/brewing stand. It just disables to pay for filling up these blocks.

**Comment by PackCraft** [comment]
Sorry, I misunderstood
