### ISSUE TITLE
We get money just for right-clicking on a cow

### ISSUE THREAD

**Issue by lemafor** [Zrips/Jobs#991]
***Description of issue:**
I have paper 1.16.4, last jobs ( 4.16.3), I deleted the whole jobs/ directory. Then I started server, `/jobs join farmer`, empty both hands and right-click on cow -  I am getting money for every right-click for nothing. No breeding, no milking - just for right-click.
---

**Server Type (Spigot/Paperspigot/etc):** 

paper 1.16.4

**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-260 (MC: 1.16.4) 
(Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Comment by zxopher** [comment]
Also experiencing this on 1.16.3 with the most recent build of Jobs.
