### ISSUE TITLE
Typo in the default boost message

### ISSUE THREAD

**Issue by jarim5891** [Zrips/Jobs#993]
`[Thu, 5. Nov 2020 07:00:05 UTC INFO] ***********************************************
[Thu, 5. Nov 2020 07:00:05 UTC INFO] * Boost time for jobs have beed stoped
[Thu, 5. Nov 2020 07:00:05 UTC INFO] * All rates reseted to original ones
[Thu, 5. Nov 2020 07:00:05 UTC INFO]    ###**********************************************`

**Comment by montlikadani** [comment]
Update your config then.

**Comment by jarim5891** [comment]
This is the default config. It's not /my/ config.
