### ISSUE TITLE
Points Refresh Issue

### ISSUE THREAD

**Issue by AxelJoue** [Zrips/Jobs#995]
**Description of issue:** 
The Jobs plugin does not reactualize the player’s points that are saved in the database during the connection. 
For example for my case, when a player passes from server 1 to server 2 the points that server 1 recorded in the database does not refresh on server 2, just as when it gains points on server 2, When disconnecting the changes are well saved in the database, but when connecting to server 1 it finds the points it had when disconnecting on this server.
(The points are well recorded in the database but are not recovered as it should be.)

---

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** 1.16.1

**Comment by montlikadani** [comment]
First thing, you should have `MultiServerCompatibility` enabled in generalConfig. Make sure you have the same database connected with your server as well as you using MySql.

**Comment by AxelJoue** [comment]
I checked the configuration, the system of multiple servers is well activated `MultiServerCompatibility: true`, and the configurations on the 3 different servers are exactly the same.
I also did other tests 2 days ago on a separate server, and the problem comes from the plugin.

**Comment by AxelJoue** [comment]
I am using a MySQL database.

**Comment by Zrips** [comment]
8cd5061eced23fc4615a0d34c1ed7e534193d4c1
