### ISSUE TITLE
Update for the boost

### ISSUE THREAD

**Issue by DjeyMute** [Zrips/Jobs#996]
Hi guy,

I am using the LuckPerm plugin.
With this plugin it is possible to give temporary permissions.
My players already have + 20% boost but if they add a temporary permission of + 30%, this is not taken into account.

So would it be possible to take into account the temporary permission of LuckPerm and give the highest boost to the players during the time he obtains this temporary permission?

Thanks in advance for reading.

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/issues/984

**Comment by DjeyMute** [comment]
Maj on spigot.... ? :/
More than 1 month... :(
